### ISSUE TITLE
[New API] Google Lens Image Source API

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1003]
Google Lens includes a "Find image source" button users can click to see web pages that include the exact image.

A customer recommended we support this.

<img width="511" alt="Screenshot 2023-07-20 at 9 05 42 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/99f39df5-9082-48a4-825f-a1e11ebd4708">
<img width="508" alt="Screenshot 2023-07-20 at 9 06 27 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/b0afc29b-bc6c-497f-95b6-12950ec03d52">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000044972?view=List)

**Comment by marm123** [comment]
I've only now noticed that this thread and https://github.com/serpapi/public-roadmap/issues/1096 are the same. I'm closing it as completed.
