### ISSUE TITLE
[Home Depot Product API] Returning Uncaught Null Error

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#1005]
Home Depot Product API returns Uncaught Null Error and not working.

![image](https://github.com/serpapi/public-roadmap/assets/64849049/ed2a3352-cc86-4d07-a77e-7f35117c5fe6)

[Playground Link](https://serpapi.com/playground?engine=home_depot_product&product_id=202054749) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000045003?view=List)

**Comment by schaferyan** [comment]
Probably a duplicate of #1001 and should be fixed now
