### ISSUE TITLE
[Google Lens API] Scrape image's information

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1006]
It appears that for some images, we scrape only visual matches but no image information:

<img width="1428" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/740b83b2-c5aa-4073-8e45-41641e143123">

[Playground](https://serpapi.com/playground?engine=google_lens&url=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F1132077979648938016%2F1132420237321568406%2FIMG_6333.jpg) | [Inspect](https://serpapi.com/searches/64be0ff85f22037fe38b81d9/inspect) | [Google Lens link](https://lens.google.com/search?p=Acn1BYc-FrZjf7T14Nswaq5y1bjF6TMvmsYY7sl7WDDue1LoE_F-bros9CepN3UR00BkZ-BtdtkvElqDIHfVtNuJW2h58Dzf4JvSUToZ6sgGpZmFofj3GuLSdAOo3aTymvUy4JI0cyhqOqSCM9l6wbRHPpBNpILN--9GwZSCkSZO79voBk3npN--vqyQCygCcs5g0n5775WwO1bK38mpzxQywY9_1oOsMcFnEuWn1Bws8H76RBCDBBYHBnwEjfS_wnVXUTY%3D&plm=Cg8IDxILCNyd%2BKUGEPCpziwKDwgXEgsI3J34pQYQkMDRLAoPCBgSCwjcnfilBhC4ycxsCg8ILRILCNyd%2BKUGEJinzWwKEAguEgwI3J34pQYQgL6gowEKEAgQEgwI3J34pQYQyPeCpAEKEAgZEgwI3J34pQYQ%2BN6FpAEKEAgaEgwI3J34pQYQ0PqOpAE%3D#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKRE5oWTJRME5tUm1MVGN6WkRrdE5HTXhOQzFpT1RZMExUbGpNbVUwWWpNelpHUTRNQklmU1RJeWRXZFllbnB5Tkd0aWIwUk1aa3hPVEZCZlpVMWhOalpDYlcxQ1p3PT0iXQ==)

**Comment by schaferyan** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000045774?view=List)

**Comment by marm123** [comment]
Another customer requested thsi

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000046522?view=List)
