### ISSUE TITLE
[Google Finance API] Scrape Annual `financials`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1008]
Currently, we only scrape Quarterly `financials`. A customer requested us to also scrape Annual `financials`.

<img width="1435" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/3cf58210-a77f-47e1-b895-da3b93497484">

[Playground](https://serpapi.com/playground?engine=google_finance&q=GOOGL%3ANASDAQ) | [Inspect](https://serpapi.com/searches/64be30271d986e417dee2dfb/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000045102?view=List)

**Comment by ocvit** [comment]
Feature has been released.

Now we fetch all available `quarterly` and `annual` data.

<img width="1260" alt="Screenshot 2024-09-18 at 10 44 50" src="https://github.com/user-attachments/assets/291a948e-3fb0-44d0-a921-d08c9ab00081">
