### ISSUE TITLE
Add a Team page and allow account owner to invite teammates

### ISSUE THREAD

**Issue by hartator** [serpapi/public-roadmap#1017]
This issue cleans up https://github.com/serpapi/public-roadmap/issues/270, https://github.com/serpapi/public-roadmap/issues/901, and https://github.com/serpapi/SerpApi/issues/2604 issues into one.

The goal is to add a team tab and allow account owners to invite teammates.

In the PR to implement this, I think we want to do all of this:
- Add a "Team" menu item under "Your Account" in dashboard
- In "Team" page, allow `Owner`s to invite `Admin` teammates (with just email + full name)
- This a new `Admin` role that can do everything an `Owner` can do except removing the `Owner`
- The `Owner` role will be just how our current accounts work; we just name this `Owner` role
- Inviting an `Admin` teammate sends them an email requesting to create an account on serpapi.com
- When creating an `Admin` account, we skip the `/users/welcome` verification process
- `Admin` accounts share same billing info, stats views, and searches views as `Owner`s
- `Admin` accounts can edit billing info of `Owner`s account
- `Admin` accounts have their own API key, but it's the `Owner`'s plan that got charged plan searches or credits for all `Admin` API key usage; `Admin` accounts don't have their own plan usage 
- `Admin` accounts otherwise are regular users; and have their own email, full name, profile picture, and other profile details
- New "Team" page shows list of teammates with email, full name, role (`Owner` or `Admin`), and their API keys
- "Your Searches" table can filter by teammate or "All" (aggregate of all teammates' searches). Like our engine filter.
- "API Absolute Numbers",  "API Response Times", and "API Success Rates" graph pages can filter by teammate or "All" (sum of all teammates' searches). Like our engine filter.

That alone should solve bench of issues in addition of adding team support. For customers who want a separation between environments, we can recommend them to just add a "Production",  "Development", and "Staging"-named users. For customers who want a separation between projects, we can also recommend them to just add a "Project 1",  "Project 2", and "Project 3"-named users. Each user will still have strictly one API key, but they will indirectly then have several API keys through these virtual users. So, they can filter by these virtual users in their searches and stats pages, and see the data they want.

In future PRs, we would want to:
- Support SSO
- Support a "Billing" role
- Support a "View-only" role
- Support an "Engineer" role
- Add a graph that shows API usages per teammate for customers to see
- Maybe multiple orgs and multiple teams support

**Comment by marm123** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000047022?view=List)

**Comment by marm123** [comment]
Another user requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000052269?view=List)

**Comment by zyc9012** [comment]
With @hartator, we decided to disable inviting existing account. If the owner enters an existing email, we'll show a error message and hint the owner to delete the account before inviting.

Internally, the account will be soft-deleted, and should be re-initialized when accepting the invitation.

**Comment by zyc9012** [comment]
With @hartator, we've decided to disallow inviting existing accounts for now.

**Comment by martin-serpapi** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000052468?view=List)

**Comment by mrtipale** [comment]
Another customer request. @martin-serpapi . 

if not another user account. do you have way to provision system account for using it on prod shared systems.

**Comment by schaferyan** [comment]
Two more customers requested this.
[
Intercom 1](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054807?view=List)
[Intercom 2](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000037518?view=List)

**Comment by marm123** [comment]
Another customer requested this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055548?view=List)

**Comment by marm123** [comment]
Another customer requested this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055563?view=List)

**Comment by schaferyan** [comment]
Another user with this request, they had some additional notes about related features that would be helpful for their use case:

>It would still leave the challenge of how to automate the creation of API Keys, as it would be appropriate to minimise or ideally eliminate manual intervention in the on-boarding process.
>
>Support for a tenancy or end-user identifier in the APIs and a means to extract a usage report at that level would be preferable. This would avoid the provisioning step altogether.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056461?view=List)

**Comment by hilmanski** [comment]
A user requested to be able to add a teammate with "READ ONLY" permission.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056547?view=List)

**Comment by schaferyan** [comment]
Another user requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000057417?view=List)
