### ISSUE TITLE
Verify my phone number

### ISSUE THREAD

**Issue by LongRodSilver** [serpapi/public-roadmap#1021]
Hey,

I am from Gabon and I cannot verify my phone number because there is an unknown error.

The number should be entered as follow: +24162262777 This is for Gabon Central Africa.

When I enter that number I have an unknown error and the code is not sent therefore I cannot verify my number.

Can you please help me?

Regards.

Rodney

**Comment by tmb9206** [comment]
7656159252

**Comment by schaferyan** [comment]
Hi @LongRodSilver, I'm sorry to hear you're having trouble verifying your phone number. Please contact us at support@serpapi.com, or through the chat interface on our website for assistance with this. 

Note that you may wish to remove your phone number from this issue as this is public.

I'm also leaving this issue open as we've recently had a higher number of customers with this problem.

**Comment by joegoogIe** [comment]
2055191034

**Comment by schaferyan** [comment]
@joegoogIe can you please explain why you have posted this number here?
