### ISSUE TITLE
[Google Search API] Mistakenly parsed `phone` for some `ads`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1028]
<img width="1458" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/61daaaba-00b5-4d84-a636-5fba0605cb9f">

[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&num=50&device=mobile&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client)
[Inspect](https://serpapi.com/searches/64d2276b9c84acd8395a59ea/inspect)

**Comment by aciddjus** [comment]
Closing the issue as I can't reproduce it.
