### ISSUE TITLE
[Google Search API] `cached_page_link` of `organic_results` is missing domain for some searches

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1033]
<img width="1455" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/0101b657-578d-4729-a687-0d0a121a3afe">

[Playground](https://serpapi.com/playground?q=Elon+Musk&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&num=50&device=desktop&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client)
[Inspect](https://serpapi.com/searches/64d22fee9bddf74c99249970/inspect)

**Comment by aciddjus** [comment]
Cached page links have been [discontinued](https://www.theverge.com/2024/2/2/24058985/google-search-cache-feature-discontinued) for Google Search.
