### ISSUE TITLE
[Google Maps API] Scrape prices in local currency for `admissions` block

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1039]
Currently, all prices are in USD. However, when accessing the same link in with VPN set to different locations, the currency changes. Maybe we can find a way to scrape allow users to determine their currency for the `admissions` block.

Current state (prices in USD for google.pl/hl=pl search):
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/365502cb-212b-4fa8-941f-f0fbd8fbb95b">

Google results from Poland:
<img width="325" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/ba1ba70b-67f0-498b-a071-82bf0bdb649f">

Google results from Germany:
<img width="323" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/00e01dc8-124a-4da6-87ff-61d8a09e31fb">

Google results from Japan:
<img width="324" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/6c3e33e5-83ce-40bb-987d-59958b19b0f4">

[Playground](https://serpapi.com/playground?engine=google_maps&q=Eiffel+Tower&place_id=ChIJLU7jZClu5kcR4PcOOO6p3I0&type=search) | [Inspect](https://serpapi.com/searches/64d38b17b7b1cc07e8482024/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000046065?view=List)

**Comment by hilmanski** [comment]
Another user reported this issue: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000065706?view=List)

I can confirm when using a VPN in the original country, I can see the currency change. [Google maps link that shows Euro for the pricing](https://www.google.de/maps/place/Museum+f%C3%BCr+Naturkunde/@52.5305758,13.3765952,16z/data=!3m1!4b1!4m6!3m5!1s0x47a85194aaaae5dd:0x7bd0323eded9828c!8m2!3d52.5305726!4d13.3791755!16zL20vMDRyNTNu?entry=ttu) VS [Google Maps result on our playground that shows USD](https://serpapi.com/playground?engine=google_maps&ll=%4052.5305758%2C13.3765952%2C16z&google_domain=google.de&hl=de&place_id=ChIJ3eWqqpRRqEcRjILZ3j4y0Hs&type=place&no_cache=true)

**Comment by aciddjus** [comment]
We perhaps do this by adding support for `gl` country parameter.

With `gl=jp`: [Google link](https://www.google.co.jp/maps/place/?q=place_id:ChIJLU7jZClu5kcR4PcOOO6p3I0&hl=ja&gl=jp)

<img width="476" alt="image" src="https://github.com/user-attachments/assets/3fa201a6-36f8-4b92-8320-919928312416">

--

Without `gl` (showing my local curency): [Google link](https://www.google.co.jp/maps/place/?q=place_id:ChIJLU7jZClu5kcR4PcOOO6p3I0&hl=ja)

<img width="476" alt="image" src="https://github.com/user-attachments/assets/56a3d87a-2c43-4034-8ab8-8dbe268c64f5">

**Comment by mikemorcerf** [comment]
This ticket has been implemented. Now Google Maps API has `gl` parameter, which influences the currency in the results.
[Documentation was updated introducing the `gl` parameter to Google Maps API](https://serpapi.com/google-maps-api#api-parameters-localization-gl)

Examples below:
[Playground - Poland](https://serpapi.com/playground?engine=google_maps&gl=pl&place_id=ChIJLU7jZClu5kcR4PcOOO6p3I0&type=search&no_cache=true)
![Screenshot 2024-10-01 at 11 59 48 AM](https://github.com/user-attachments/assets/650c0513-4700-4f30-bf9d-258c1621d551)

[Playground - Germany](https://serpapi.com/playground?engine=google_maps&gl=de&place_id=ChIJLU7jZClu5kcR4PcOOO6p3I0&type=search&no_cache=true)
![Screenshot 2024-10-01 at 12 02 19 PM](https://github.com/user-attachments/assets/46ee8e69-51c8-4807-ba70-9a8937d03bdd)

[Playground - Japan](https://serpapi.com/playground?engine=google_maps&gl=jp&place_id=ChIJLU7jZClu5kcR4PcOOO6p3I0&type=search&no_cache=true)
![Screenshot 2024-10-01 at 12 05 47 PM](https://github.com/user-attachments/assets/89ffc01b-718e-493c-acef-8b7412e924f3)

**Comment by schaferyan** [comment]
Thanks, @mikemorcerf, I've notified the users who reported this
