### ISSUE TITLE
[Google Local Results API] `phone` is mistakenly scraped in `hours`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#104]
![hours_phone](https://user-images.githubusercontent.com/73674035/161549641-e2eb0ca5-0253-4073-b0f3-b7007bcdfed9.png)
[Inspect Link](https://serpapi.com/searches/624adc8aeb690f4dcdd2c86f/inspect)
[Playground Link](https://serpapi.com/search.json?engine=google&gl=us&google_domain=google.com&hl=en&location=United+States&no_cache=true&num=100&q=Upland+Unified+School+District+Energy+Department&tbm=lcl)

**Comment by hartator** [comment]
Same. Closing this as fixed.
