### ISSUE TITLE
[Google Search API] Parse All Data from `product_result` in `desktop` and `mobile` searches

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1040]
A user reported we are missing several fields for the `product_result` returned in some mobile searches. They requested we scrape these. At a glance, we seem to be missing the title, some images, a price range, and seller info/product offers:

<img width="562" alt="Screenshot 2023-08-09 at 10 05 02 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/842319ed-a336-4e50-be19-100ad2aeb53e">

Upon investigating, I also noticed we don't seem to be scraping the  "typical" price range or seller/offers in the desktop version.

<img width="1467" alt="Screenshot 2023-08-09 at 10 09 30 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/de5e92f6-6bfb-4ac0-a6a6-0c4ee5cf79c7">

[Search Inspector (mobile) ](https://serpapi.com/searches/64d3bc9f2bc7d8bd0c9e20a5/inspect)| [Search Inspector (desktop)](https://serpapi.com/searches/64d3c2f547ccf1bd8cca9bd3/inspect) | [Playground (mobile)](https://serpapi.com/playground?q=heat+commander&location=West+Saint+Paul%2C+Minnesota%2C+United+States&gl=us&hl=en&device=mobile) | [Playground (desktop)](https://serpapi.com/playground?q=heat+commander&location=West+Saint+Paul%2C+Minnesota%2C+United+States&gl=us&hl=en) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000046090?view=List) | [Google](https://www.google.com/search?q=heat+commander&oq=heat+commander&uule=w+CAIQICInV2VzdCBTYWludCBQYXVsLE1pbm5lc290YSxVbml0ZWQgU3RhdGVz&hl=en&gl=us&sourceid=chrome-mobile&ie=UTF-8)

**Comment by lancejohnson** [comment]
Not sure if this is helpful on your quest, but it looks like the data is very similar to a direct Google Product query.

The Google Product query returns more information, but is definitely a good workaround until this is implemented.

**Comment by marm123** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000058069?view=List)

**Comment by martin-serpapi** [comment]
Another user requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061432?view=List)
