### ISSUE TITLE
[New APIs] Scrape Product/Pricing info from Additional Hardware Store Pages

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1044]
A customer requested we add APIs to support scraping product and pricing info from other hardware store pages in addition to Home Depot. They named the following stores:

Lowe's, Menards, Sherwin Williams, Lumber Liquidators, ABC Supply, Grainger, Fastenal, Ace Hardware, Ferguson, Build and HD Supply.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042936?view=List)

**Comment by hilmanski** [comment]
I'm adding `build` to the list as well.

**Comment by hilmanski** [comment]
Lowes request is also available on another thread https://github.com/serpapi/public-roadmap/issues/1145

**Comment by schaferyan** [comment]
Thanks @hilmanski. I added a few more feature requests for other stores listed above. Lumber Liquidators is now LL Flooring and seems too specialized, HD Supply and ABC Supply don't seem to have a search-engine-like interface so I didn't add those. Since the rest of these now have their own feature requests, I'm closing this one to help keep things cleaner.
