### ISSUE TITLE
[Google Maps Reviews API] Scrape `data-review-id`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1050]
One of our customers requested us to scrape `data-review-id`, which is present in HTML for each review in Google Maps Reviews.

Example:
<img width="1440" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/79172766-6ed1-4b68-89b0-0ee8e4925b55">

[Google Maps Reviews](https://www.google.com/maps/place/Stumptown+Coffee+Roasters/@40.7457399,-73.9882272,17z/data=!4m8!3m7!1s0x89c259a61c75684f:0x79d31adb123348d2!8m2!3d40.7457399!4d-73.9882272!9m1!1b1!16s%2Fg%2F1hhw712x0?authuser=0&hl=en&entry=ttu)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000046521?view=List)

**Comment by andypple83** [comment]
Do we still need to scrape `data-review-id`? Is this field helpful?

**Comment by marm123** [comment]
I'm not 100% sure about the use case, but it might be helpful, considering that one of our users asked if there is a way for us to extract it.
