### ISSUE TITLE
[Google Scholar Cite API] BibTeX link returns invalid results

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1053]
One of our customers reported that they often encounter 403 Forbidden errors when trying to access scraped BibTeX link. When trying to recreate the search, the link is different, and works fine. However, a lot of customer searches return incorrect link.

Result through Google Scholar Cite API:
<img width="1043" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/6851f9a9-844d-4f1f-998f-333d56d28a75">

BibTeX results obtained through Google Scholar Cite API:
<img width="1134" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/6184ee41-d3b0-4dad-9338-e39823f59af6">

Results through Google Scholar Cite:
<img width="1440" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/e6cb4834-f521-4e32-9ae2-f4592e9ce040">

BibTeX results obtained through Google Scholar Cite:
<img width="1002" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/5581012a-4b0d-4236-9406-3162cd3d03a9">

[Inspect - Customer's search
](https://serpapi.com/searches/64b65cb9e4a23d63302242b5/inspect)
[Playground](https://serpapi.com/playground?engine=google_scholar_cite&q=dlyzfK7ViPAJ) | [Inspect](https://serpapi.com/searches/64de278f216a9db78e90963f/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000046792?view=List)

**Comment by andypple83** [comment]
I'm testing these links. It works for new searches. The links may have expired time.

**Comment by marm123** [comment]
Thank you, @andypple83, you are right. Those BibTeX links appear to have an expiration date. I tested it yesterday in the Playground, and every link worked fine. I went to my search history today to check if the links that were working yesterday are still there. However, none of them works, and I receive 403 errors for every single one.

I assume there is not much we can do other than just advising customers to use the links immediately, as they change constantly.

**Comment by andypple83** [comment]
Let's me add a note on our document page.

**Comment by andypple83** [comment]
We've updated our document about expired links. This is a default behavior of Google results. Hope this help. Thanks

![Screenshot 2024-06-07 at 15 19 14](https://github.com/serpapi/public-roadmap/assets/99160364/add445a5-aeee-43d9-ac27-3e459242a666)
