### ISSUE TITLE
[Feature Request] General Request to Support New AI Tools and Features

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1054]
One of our customers reached out to request that we support scraping new AI features. They specifically mentioned Bing AI Chat and Perplexity AI.

I let them know we are working on the implementation for Bing Chat and may not be able to scrape Perplexity AI.

They requested that I create the issue and share the link so that they can update it with details about what they are looking for.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000046634?view=List)

**Comment by alexbarron** [comment]
We received a request to support Google's [AI Overviews](https://support.google.com/websearch/answer/13572151?hl=en&co=GENIE.Platform%3DAndroid) feature. Unfortunately, it's still limited access, but leaving this comment here in case Google opens it up.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000065945)

**Comment by alexbarron** [comment]
Another customer interested in AI Overviews. Logging them here so we can follow up if we ever support this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000066052?view=List) [Customer](https://serpapi.com/admin/users/63468d39f05eb8bdd240792f)

**Comment by schaferyan** [comment]
We received another request to scrape Perplexity.

Also, I'm closing this issue as I think it's better to have specific issues than a catch-all. We already have https://github.com/serpapi/public-roadmap/issues/2062, and https://github.com/serpapi/public-roadmap/issues/902 for Bing AI, we've already implemented support for Google AIO, and I've opened a [new issue](https://github.com/serpapi/public-roadmap/issues/2235) for Perplexity.
