### ISSUE TITLE
[Google Shopping] - Full Prices are not shown

### ISSUE THREAD

**Issue by dtmaltrain** [serpapi/public-roadmap#1058]
Hi, i'm aware that something similar to this was also reported on #848 , but 

As you can see in the images below, if a search in google shopping filtering by Seller Puma, there are some products that have the monthly price instead of the full price, im getting that issue on several sellers, is there anything to do to retrieve the real price from these products?

![image](https://github.com/serpapi/public-roadmap/assets/37244943/f06710cd-6eda-454c-b8c5-72dbd3be41f0)

![image](https://github.com/serpapi/public-roadmap/assets/37244943/f1ee6400-3029-4e80-9194-dd89e196152d)

**Comment by ilyazub** [comment]
Looks like it's possible to extract the full price in addition to the monthly price. The data is in the HTML too

![image](https://github.com/serpapi/public-roadmap/assets/282605/3573596c-33fb-4bc4-9567-8fd4af4fcf77)

**Comment by dtmaltrain** [comment]
but its not an attribute in the json returned, it would be nice to have that, I do not want to have to search for the full price in every seller, because every html is different

**Comment by stgolarrain** [comment]
+1

**Comment by schaferyan** [comment]
@stgolarrain can you please clarify what you mean by "+1"?

**Comment by marm123** [comment]
@dtmaltrain Yes, you are right. The data is not extracted in the JSON response. @ilyazub was just pointing out that it's possible for our internal processes and implementations. Of course, we do not expect you to search for the data in HTML yourself, and we'll do our best to have this data in the JSON response.

**Comment by stgolarrain** [comment]
Hi @schaferyan,

It's just a signal to support the request for this new feature. In our case, the Google Shopping module is pointless if some prices have different scales. By scale, I mean that some products are displayed using a credit logic, while others show the full price. We cannot compare and interpret the API results.

Cheers!

**Comment by marm123** [comment]
Another user requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067433?view=List)

**Comment by tanys123** [comment]
We have added `installment` to the Shopping Results, feel free to checkout the [documentation](https://serpapi.com/shopping-results).


<img width="1307" alt="Screenshot 2024-08-12 at 11 32 02 AM" src="https://github.com/user-attachments/assets/bb26e72f-6824-4690-abfc-8ce4c01efb1f">
