### ISSUE TITLE
[Google Local Results API] `reviews` is mistakenly scraped in `address`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#106]
![add_reviews](https://user-images.githubusercontent.com/73674035/161550301-18d4e4f1-1272-4928-ad19-36fceac2dcba.png)
[Inspect Link](https://serpapi.com/searches/624add14d3aba2790e1cc98d/inspect)
[Playground Link](https://serpapi.com/search.json?engine=google&gl=uk&google_domain=google.co.uk&hl=en&location=United+Kingdom&no_cache=true&num=100&q=AWC+Water+Billing+Ltd&tbm=lcl)

**Comment by hartator** [comment]
Closing this as stale. (And fixed I think)
