### ISSUE TITLE
[Google Knowledge Graph API] Shopping results are not parsed

### ISSUE THREAD

**Issue by tanys123** [serpapi/public-roadmap#1062]
<img width="1236" alt="Screenshot 2023-08-23 at 7 48 32 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/21a7791b-0d0b-4c26-a103-ececcd0a89ce">

Shopping results seems likely to show in Knowledge Graph when it is about product and `kgmid` is present.

[Playground](https://serpapi.com/playground?q=GoPro+HERO11+Black&kgmid=%2Fg%2F11sb0_xxl8&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/64e5490c37b24a3d536187a3/inspect)

**Comment by aciddjus** [comment]
This has been resolved.

<img width="806" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/e286dce7-80c6-4a07-b13f-4f49a65f5d43">

-------------

[Playground](https://serpapi.com/playground?q=GoPro+HERO11+Black&kgmid=%2Fg%2F11sb0_xxl8&gl=us&hl=en&google_domain=google.com)

Resolved in: https://github.com/serpapi/SerpApi/pull/4123
