### ISSUE TITLE
[New API] Google Travel Flights

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1065]
We already have a couple of Google Travel requests (https://github.com/serpapi/public-roadmap/issues/389, https://github.com/serpapi/public-roadmap/issues/618, https://github.com/serpapi/public-roadmap/issues/1024). We can also add Google Travel Flights, which was requested by one of our customers:

Google Travel Flights search:
<img width="1374" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/16482d97-c3ca-46bd-a3d5-4f29b775f431">

Google Travel Flights results:
<img width="1379" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/77a7e012-633a-40b3-ad95-8909d3436511">

[Google Travel Flights search](https://www.google.com/travel/flights) | [Google Travel Flights results](https://www.google.com/travel/flights/search?tfs=CBwQAhooEgoyMDIzLTA5LTAxagwIAhIIL20vMDM1bTZyDAgDEggvbS8wNGpwbBooEgoyMDIzLTA5LTA4agwIAxIIL20vMDRqcGxyDAgCEggvbS8wMzVtNkABSAFwAYIBCwj___________8BmAEB)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000047482?view=List)

**Comment by aliayar** [comment]
Another user requested this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000048482?view=List)

**Comment by aliayar** [comment]
Another user requested this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000048379?view=List)
