### ISSUE TITLE
[Google Search API] `tabs` array Parsed Into `knowledge_graph` for Some Searches

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1068]
A customer reported that some searches return a `tabs` array inside a `knowledge_graph` key. This seems to be in addition to the `menu_items` array, and it seems to occur for searches that don't actually return a knowledge graph.

<img width="1223" alt="Screenshot 2023-08-24 at 2 55 47 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/a19dd5c4-3802-414e-b955-775cf44b4ea8">

[Inspector](https://serpapi.com/searches/64e7cae0660dbd6f86b58ba7/inspect) | [Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000047541?view=List)

**Comment by kagermanov27** [comment]
@schaferyan I'll look into this. But this is quite normal. Some of the menu items' structure is inseparable from knowledge graph tabs, and they work in the same way with knowledge graph tabs. We may avoid it by checking for the presence of the knowledge graph for sure though.
