### ISSUE TITLE
[Google Local Results API] `years_in_business` is mistakenly scraped in `address`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#107]
![add_years](https://user-images.githubusercontent.com/73674035/161550586-5246ff78-ae75-40f1-a07e-f259039063ee.png)
[Inspect Link](https://serpapi.com/searches/624ad62ef0adfb63a370d708/inspect)
[Playground Link](https://serpapi.com/search.json?engine=google&gl=uk&google_domain=google.co.uk&hl=en&location=United+Kingdom&no_cache=true&num=100&q=Accountant&tbm=lcl)

**Comment by andypple83** [comment]
Closed because this is outdated.
