### ISSUE TITLE
[Google Search API] Scrape "Book Online" Link from Knowledge Graph

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1072]
Some `kniowledge_graph` elements have a "Book Online" button. A customer has requested we scrape the URL from this button.

<img width="1467" alt="Screenshot 2023-08-29 at 4 03 58 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/f449ae9b-88c7-4320-88d2-a5c6f103be50">

[Playground](https://serpapi.com/playground?q=royalty+blends+barbershop+los+angeles+ca&location=United+States&gl=us&hl=en&newPara=chips) | [Google](https://www.google.com/search?q=royalty+blends+barbershop+los+angeles+ca&sca_esv=561127710&ei=EnnuZPOEIMjn0PEPop6-6AI&ved=0ahUKEwjz1av3_IKBAxXIMzQIHSKPDy0Q4dUDCBA&uact=5&oq=royalty+blends+barbershop+los+angeles+ca&gs_lp=Egxnd3Mtd2l6LXNlcnAiKHJveWFsdHkgYmxlbmRzIGJhcmJlcnNob3AgbG9zIGFuZ2VsZXMgY2EyBRAhGKABMgUQIRirAkjDCFDeBVjeBXABeACQAQCYAYUBoAGFAaoBAzAuMbgBA8gBAPgBAcICCBAAGKIEGLAD4gMEGAEgQYgGAZAGBA&sclient=gws-wiz-serp) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000048027?view=List)

**Comment by shyam-coris** [comment]
Hi @schaferyan , @btaunt 
  Any update on this ticket ? Very eager to see this working 

thanks
Shyam

**Comment by schaferyan** [comment]
Hi @shyam-coris, it looks like a solution has been implemented and it is currently in the review process.

I can't give you a precise ETA, but I would expect this to be completed fairly soon.

**Comment by shyam-coris** [comment]
@schaferyan thanks for the update.  Is this still in review process ?
