### ISSUE TITLE
[Google Maps Photos API] Omit `next_page_token` on Last Page

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1073]
A customer requested that we omit the `next_page_token` on the final page of Google Maps Photos results. This would save them from having to send the request and receive a response with `search_information.photos_state = "Fully empty"` to know when they've reached the last page.

<img width="1463" alt="Screenshot 2023-08-30 at 2 36 27 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/a89a97f9-c6b1-4491-8cae-3a95e3620008">

<img width="1465" alt="Screenshot 2023-08-30 at 2 32 41 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/770685c8-273a-4510-b949-de99e6077dcb">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000048133?view=List) | [Playground](https://serpapi.com/playground?engine=google_maps_photos&data_id=0x89c259a1820824bd%3A0x2b79dcdc251b8415&hl=en&category_id=CgIgARICEAE&next_page_token=EvgDKYQi49-NlUMIDwAAAAEAAAMAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAgAAAAAAAAAAAAAAACQAAAABAAAAAAAAAAAAAAAABIAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAEAAAACAAAAAAAAAAAAAAAAAIIAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAgAABAAAAAAAAAAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAACAAEAAAAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAQAAAAAEgAAAAAQAAIAAAAAAQAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAACAAAAAAAAAQAAAAgAAAAAEAAAAAAABAAAABABAAAEgAAAAAAAAAAAAABAAAAAAAAAgAAAAAAAAAAAAIAAAAAAAAAAAAAAAABAAAAAAAAEAAAAAAAAAAAAAAACABAAAAAAAAAAAAIAAAAIQAAAAAAAAAQAAAAIAAAAAAGBRCVCmEIuPfjZVD6AEAACAAAAADAAAAAAAgIEABCZBGAgAAQAYwQAAIABgYQEAASBAAIMAAAIAGAAgIBAAAgAMA4AAABACJAUAACCIAAAAIQEAUAgAAAA)

**Comment by ilyazub** [comment]
Similar to https://github.com/serpapi/public-roadmap/issues/921 and https://github.com/serpapi/public-roadmap/issues/145.
