### ISSUE TITLE
[Google Search API] Scrape Time from Answer Box

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#1075]
Currently, we don't scrape the time from the answer box. We can scrape and return it in the results.

![image](https://github.com/serpapi/public-roadmap/assets/64849049/c26d1a50-97a9-47b7-b1f1-9315ec0f83c5)

[Google](https://www.google.com/search?q=what+time+is+it+in+atlanta) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000048187?view=List)

**Comment by btaunt** [comment]
Closing this issue. Fixed with https://github.com/serpapi/SerpApi/pull/4336
