### ISSUE TITLE
[Google Events API] Parse Event Name from Details Page

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#1077]
Currently, Google Events API parses event names from events' list. When the event name is not full in the list, three dots are added like in the example below:

![eventsapi](https://github.com/serpapi/public-roadmap/assets/64849049/db6433ea-e37f-4b2d-aa59-9e6567d10290)

However, details page have full name of the event without being shortened and three dots.

![eventsapi](https://github.com/serpapi/public-roadmap/assets/64849049/f5fffa3c-d724-4f46-9091-546331ca7d54)

We can improve the Event API by parsing the event name from details page instead of events list.

**Comment by vpctorr** [comment]
If this could be applied to the description as well, it would be greatly appreciated!
