### ISSUE TITLE
[Google Lens API] Direct Image URL not Returned

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#1079]
Google Lens API doesn't return full image URLs but thumbnails from visual_matches section.

![lens2](https://github.com/serpapi/public-roadmap/assets/64849049/c7593383-cc3a-45cc-9bce-28b762dba4f0)

It seems that some of the images in Knowledge Graph can also have full resolution but only thumbnail address is returned:

![lens3](https://github.com/serpapi/public-roadmap/assets/64849049/3fc97cb6-000e-4a0c-90a4-2886f602d479)

[Playground Link](https://serpapi.com/playground?engine=google_lens&url=https%3A%2F%2Fi.imgur.com%2FHBrB8p0.png) | [Inspect Link](https://serpapi.com/searches/64f705f02348841669358550/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000048530?view=List)

**Comment by btaunt** [comment]
@aliayar Just confirming this is the `visual_matches` section? Your screenshot looks as though you are targeting the direct `knowledge_graph > images` section (reference to what I matched below)

![2023-09-11-152214_913x555_scrot](https://github.com/serpapi/public-roadmap/assets/137819397/bc9b4805-b290-41d8-9309-a4c73805232f)

**Comment by aliayar** [comment]
I gave this another look and it seems that Google doesn't have direct image links on the page for any of the sections.

What do you think @btaunt?

**Comment by btaunt** [comment]
@aliayar Yeah this is odd. I notice the `source` for items under `images`, but others are no longer displayed. But even that "source" is not always a direct image URL - it can often times be a site URL where the image originated.

**Comment by aliayar** [comment]
Thank you Bradley. I will close this one.
