### ISSUE TITLE
[Google Local Results API] `type` is mistakenly scraped in `address`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#108]
This is a problem with less chance of being happening, and a problem I have encountered when updating the queries for the ML model. `Cafe`, `Coffee` etc. were the types that were mistakenly parsed in address. However, I wasn't able to recreate it with the possible values used in expanding the dataset. I am opening an issue just in case it occurs to someone else.

**Comment by hartator** [comment]
Closing this as stale.
