### ISSUE TITLE
[Google Product API] Can't find product details

### ISSUE THREAD

**Issue by sebastianchmiel** [serpapi/public-roadmap#1081]
I'm trying to search for products by query by parameters:
![serpapi-search-params](https://github.com/serpapi/public-roadmap/assets/6066869/812f1e0f-044e-4f8f-b581-8cdb0e9eae4c)

And, for example, I get this result:
![serpapi-search-single-result](https://github.com/serpapi/public-roadmap/assets/6066869/7b8a959b-269f-4f7e-addf-c74636dae4d3)

Unfortunately, when I later want to get the details of this product, I get the message "Product page blank"
![serpapi-single-search-not-found](https://github.com/serpapi/public-roadmap/assets/6066869/d8ae702c-e699-4326-b0f0-f937e67c6b34)

Is there something wrong on your side here? Alternatively, can I somehow reject search results for which retrieving details does not work?

**Comment by ilyazub** [comment]
Hello @sebastianchmiel. Sorry for the inconveniences. We are working on fixing this issue.

_Duplicate of https://github.com/serpapi/public-roadmap/issues/988._

**Comment by TadasPik** [comment]
Hello. Any ETA's on when it's gonna be merged?
