### ISSUE TITLE
[Google Search API] `organic_results_state` is "Fully empty" Despite Results Present in HTML

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1083]
A customer reported that some of their searches are returning with a `organic_results_state` of "Fully empty", and no results in the JSON, despite the presence of results in the HTML response. 

I was unable to recreate it in the Playground.

Notable things about their query are the absences of `location` parameters and the use of `num=4`. However when using these parameters in the Playground I still couldn't reproduce this result.

<img width="1184" alt="Screenshot 2023-09-06 at 11 32 23 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/8dba9960-c940-4e2c-96fa-998e35db2fdc">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000048754?view=List) | [Search Inspector](https://serpapi.com/searches/64f8925910d744693089b8ec/inspect)

**Comment by aliayar** [comment]
[Another user](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000048849?view=List) reported this.

**Comment by schaferyan** [comment]
The user in the thread Ali linked to above was also using a value less than 10 for `num`, so the issue is likely related to that.

**Comment by matsoob** [comment]
Just wanted to add in case helpful:

We have observed the same issue occur sporadically (maybe 5-10% or less of requests), also using a num parameter lower than 10 (we use this low parameter all the time -- however the empty organic results only occur occasionally). We will try increasing the limit to 10 to see if this helps.

Also wanted to point out that the results caching on serpapi (meant to save us $$ for identical requests) makes this a bit more painful, as even when the query is re-sent it results in the same erroneous "empty" result getting returned.

I'm unable to access the link Ali shared -- apologies if info is redundant!

**Comment by zyc9012** [comment]
@matsoob Thanks for the info! We are working on this right now. This issue will automatically close when it's resolved.

**Comment by zyc9012** [comment]
@matsoob We can't ensure an exact ETA but the fix is already under review. It should be quick, usually within a week.
