### ISSUE TITLE
[Google Autocomplete API] Scrape Thumbnails and Subtitles

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1084]
Google Autocomplete provides thumbnails and subtitles with additional disambiguating information for knowledge graph entities. A customer has requested that we scrape these. 

<img width="1529" alt="image (1)" src="https://github.com/serpapi/public-roadmap/assets/30915304/dabd6202-72d2-4a53-9ed2-f93c973f728c">
<img width="1283" alt="image" src="https://github.com/serpapi/public-roadmap/assets/30915304/cd59514e-9fd3-472d-bd74-46442ccffe08">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000048786?view=List)

**Comment by johnstetic** [comment]
I see this other api is doing this https://zylalabs.com/api-marketplace/data/google+search+autocomplete+api/1184

**Comment by ilyazub** [comment]
Related to https://github.com/serpapi/public-roadmap/issues/423 and https://github.com/serpapi/public-roadmap/issues/424
