### ISSUE TITLE
[Google Images API] `images_results` Not Being Parsed

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1092]
A user reported that our Google Images API has stopped returning `images_results` in the JSON.

<img width="1467" alt="Screenshot 2023-09-11 at 12 44 26 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/fffbbe74-7f8e-4f2f-8e0f-8bdc18696b9f">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000049164?view=List)  | [Inspector](https://serpapi.com/searches/64ff68062f542e9edf89bffb/inspect) | [Playground](https://serpapi.com/playground?engine=google_images&q=coffee&location=United+States&gl=us&hl=en&no_cache=true&newPara=chips+ijn)

**Comment by schaferyan** [comment]
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000049175?view=List)

**Comment by schaferyan** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000049177?view=List)

**Comment by ritu1337** [comment]
Issue should be resolved now 👍

**Comment by johnstetic** [comment]
@ritu1337, thanks for the quick fix. I just tested and everything is working again for me.

**Comment by ritu1337** [comment]
> @ritu1337, thanks for the quick fix. I just tested and everything is working again for me.

Awesome!
