### ISSUE TITLE
[Google Search API] `about_page_link` and `about_page_serpapi_link` Missing the `ilps` Parameter

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1098]
A customer reported that the `about_page_link` and `about_page_serpapi_link` are missing the `ilps` parameter.

While the `about_page_link` seems to work, our About This Result API depends on the `ilps` parameter in order to work.

Because of the absence of `ilps` the `about_page_serpapi_link` is broken.

The customer also doesn't have any way of getting the `ilps` parameter in order to use our About This Result API.

<img width="1453" alt="Screenshot 2023-09-14 at 1 04 26 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/6a7d2c38-16a9-4c8e-bed8-143cf913d0c5">
<img width="1229" alt="Screenshot 2023-09-14 at 1 07 58 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/7dada516-6a18-4547-8d99-8dda5a756983">

Related to #1094

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000049221?view=List) | [Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&newPara=chips) | [Inspector](https://serpapi.com/searches/65036249e135088fcee42c1e/inspect) | [`about_page_serpapi_link` ](https://serpapi.com/search.json?engine=google_about_this_result&google_domain=google.com&q=About+https%3A%2F%2Fwww.ncausa.org%2Fabout-coffee%2Fhistory-of-coffee)

**Comment by alanhagerman** [comment]
This is a total blocker to using the About This Result API.

**Comment by ilyazub** [comment]
`ilps` is no longer required by Google and we can make `ilps` parameter optional in the SerpApi codebase.

![image](https://github.com/serpapi/public-roadmap/assets/282605/a46b6a4f-4953-42ae-a88f-64158ddc9627)
(ref: https://www.google.com/search?q=About+https://www.ncausa.org/about-coffee/history-of-coffee&tbm=ilp)

Passing an arbitrary `ilps` parameter also works.

![image](https://github.com/serpapi/public-roadmap/assets/282605/1d2f0df9-e934-4dbb-a8ad-dca939e74ebc)
(ref: https://www.google.com/search?q=About+https://www.ncausa.org/about-coffee/history-of-coffee&tbm=ilp&ilps=42)

**Comment by schaferyan** [comment]
Another user with this issue. They correctly discovered the work around of passing an arbitrary `ilps` value.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000050097?view=List)

**Comment by kagermanov27** [comment]
This issue can be marked as resolved since Google no longer utilizes the 'ilps' parameter. The blocker in the Google About This Result API has been addressed, and it no longer necessitates the use of 'ilps' to function properly.
