### ISSUE TITLE
[Google Jobs API] Update `chips` parameter to `htchips`

### ISSUE THREAD

**Issue by hartator** [serpapi/public-roadmap#11]
An user has noticed that the Google url has changed from `chips` to `htchips`. And the filters are not working anymore otherwise:

https://www.google.com/search?q=Barista&ibp=htl;jobs#htivrt=jobs&fpstate=tldetail&htichips=employment_type:CONTRACTOR&htischips=employment_type;CONTRACTOR&htidocid=rKKHXOEcrR4AAAAAAAAAAA%3D%3D

Justin tried to add this to the playground but it did not work because we don't support that parameter:

https://serpapi.com/playground?engine=google_jobs&q=Barista&htchips=employment_type%3BCONTRACTOR%26htidocid%3DrKKHXOEcrR4AAAAAAAAAAA%253D%253D&newPara=htchips

![image](https://user-images.githubusercontent.com/307597/156085232-7d1befc7-2884-4127-8536-ada819b19445.png)

Original Canny issue: https://forum.serpapi.com/bugs/p/google-jobs-api-update-chips-parameter-to-htchips

**Comment by aciddjus** [comment]
The issue is not in the change of parameter name, it is in the way Google started serving data when `chips` parameter is used.

The content is loaded asynchronously now when using `chips`.

Correct link to retrieve the data: https://www.google.com/search?rciv=jb&chips=employment_type:CONTRACTOR&q=Barista&asearch=jb_list&async=_id:VoQFxe,_pms:hts,_fmt:pc

**Comment by darrenwestall** [comment]
How do I use this via Serp API?

**Comment by aciddjus** [comment]
> How do I use this via Serp API?

Hi @darrenwestall.

If you are talking about the `chips` parameter, the value should look like this: `employment_type:CONTRACTOR`.

Example search: https://serpapi.com/playground?engine=google_jobs&q=Barista&chips=employment_type%3ACONTRACTOR&no_cache=true

--------------------

Our JSON response will include `chips` values and it looks like this:

```json
"chips": [
  ...
  {
    "type": "Type",
    "param": "employment_type",
    "options": [
      {
        "text": "All"
      },
      {
        "text": "Full-time",
        "value": "FULLTIME"
      },
      {
        "text": "Part-time",
        "value": "PARTTIME"
      },
      {
        "text": "Contractor",
        "value": "CONTRACTOR"
      },
      {
        "text": "Internship",
        "value": "INTERN"
      }
    ]
  },
  {
    "type": "Date posted",
    "param": "date_posted",
    "options": [
      {
        "text": "All"
      },
      {
        "text": "Past day",
        "value": "today"
      },
      {
        "text": "Past 3 days",
        "value": "3days"
      },
      {
        "text": "Past week",
        "value": "week"
      },
      {
        "text": "Past month",
        "value": "month"
      }
    ]
  },
  ...
]
```

To extract the `chips` value from here you need to combine `param` field with `value` field.

In this case:

- `employment_type` + `:` (colon) + `CONTRACTOR`, will result in chips value: `employment_type:CONTRACTOR`

If you want to combine `chips` multiple values you can do so by separating them with `,` (comma): `employment_type:CONTRACTOR,date_posted:today`
