### ISSUE TITLE
[Baidu Search API] Specific section of organic result is not parse 

### ISSUE THREAD

**Issue by tanys123** [serpapi/public-roadmap#110]
For below search, we left out one of the organic result
[Inspect](https://serpapi.com/searches/624e9c4729d1777808773de9/inspect)

<img width="939" alt="Screenshot 2022-04-07 at 4 25 52 PM" src="https://user-images.githubusercontent.com/10222402/162155223-2aa8fc21-9f52-4a54-8f05-761b21890073.png">

**Comment by Alaa-abdulridha** [comment]
This issue already got fixed in #2725
