### ISSUE TITLE
[Walmart Search API] Filters not Scraped, Even When `include_filters = true`

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1101]
A customer reported we don't seem to be scraping the `filters` in Walmart Search, even if the `include_filters` parameter is set to true. It looks like possibly the parameter isn't getting applied correctly for some reason.

<img width="1469" alt="Screenshot 2023-09-18 at 6 00 32 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/2c930227-d7ff-430e-8c5e-5f5c046d43c0">

[Playground](https://serpapi.com/playground?engine=walmart&query=candles&include_filters=true) |[ Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000050067?view=List) | [Search Inspector](https://serpapi.com/searches/6508f1d187a0eee5ba76492e/inspect)

**Comment by ilyazub** [comment]
Related to https://github.com/serpapi/public-roadmap/issues/543

**Comment by schaferyan** [comment]
A customer whose use case a fix for this would support:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000052209?view=List)
