### ISSUE TITLE
[Google Search API] `extensions` are parsed in the `name` field in `knowledge_graph`

### ISSUE THREAD

**Issue by vkrasnoselskikh** [serpapi/public-roadmap#1102]
An error occurs when parsing film cards in the Knowlege graph -> movies_playing section. There is unnecessary information in the "name" field.

 Examples of queries:
- movies in cinema
 
![image](https://github.com/serpapi/public-roadmap/assets/6583856/1e1d47ee-0129-4913-ba57-5790119a841c)

[Playground](https://serpapi.com/playground?q=Movies+in+cinema&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&newPara=chips) | [Inspect](https://serpapi.com/searches/6509a783ada54b9269a68aae/inspect)

**Comment by marm123** [comment]
Thank you for reporting the issue @vkrasnoselskikh! I've updated your comment with the Playground and Inspect links and changed the title. It looks like `extensions` are parsed incorrectly in the `name` field.
