### ISSUE TITLE
[Google Maps API and Google Local API] Provide a Way to Use the Same Identifier with Both APIs

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1104]
A customer recently requested help getting the `ludocid` for businesses they have a business name, `place_id` and `data_id` for. Right now, there doesn't seem to be a way to use the `place_id` and/or `data_id` for a place to get the `ludocid`. 

The main way I can see for getting the `ludocid` of a business is to perform a Google Local Search.  It would be helpful for this customer's use case if we could either scrape `ludocid` from Google Maps or Google Maps Places (if available) or provide a way to search Google Local with a Google Maps `place_id` or `data_id` (if possible).

I believe it would also be helpful for our customers in general to have a bridge between our Google Maps API and our Google Local API, as currently there isn't a good way to use them in conjunction.

<img width="1449" alt="Screenshot 2023-09-19 at 10 31 33 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/82a39c1d-4ed8-4ea2-a070-2c5bb24104ed">

![Screenshot 2023-09-19 at 10 32 14 AM](https://github.com/serpapi/public-roadmap/assets/30915304/42752c46-0691-4222-99d6-6632ef124f72)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000049207?view=List)| [Playground(Google Local)](https://serpapi.com/playground?engine=google_local&q=Coffee) | [Playground(Google Maps)](https://serpapi.com/playground?engine=google_maps&q=Coffee&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&type=search)

**Comment by zyc9012** [comment]
@schaferyan The `data_cid` from Google Maps API can be used as `ludocid` in Google Local API.
