### ISSUE TITLE
[Google Trends] Support `hl` parameter

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1105]
Google Trends supports the `hl` parameter for specifying language. A customer has requested we support `hl` with our Google Trends API.

<img width="1323" alt="Screenshot 2023-09-19 at 12 54 15 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/6acd67d6-04a1-4622-92f8-c64a9dc3ca23">

[Google Trends](https://trends.google.com/trends/explore?q=Taylor%20Swift&date=now%201-d&geo=US&hl=es) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000050379?view=List)

**Comment by hilmanski** [comment]
A user asked about this as well:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053860?view=List)

**Comment by hilmanski** [comment]
Another user requested this:

[Intercom](https://github.com/serpapi/public-roadmap/issues/1105)

**Comment by schaferyan** [comment]
Another user requested this. 

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067701?view=List)

**Comment by schaferyan** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067824?view=List)

**Comment by ishiharaf** [comment]
We have added support for the `hl` parameter.

With `hl=ru` parameter
![image](https://github.com/user-attachments/assets/d8479745-f2e9-43b1-ab14-822f83661517)

Default `hl` parameter
![image](https://github.com/user-attachments/assets/56460ac7-0e89-448d-8e92-137dc10426aa)

[Playground](https://serpapi.com/playground?engine=google_trends&q=%E3%82%B9%E3%83%9D%E3%83%BC%E3%83%84%E3%82%AF%E3%83%A9%E3%82%A4%E3%83%9F%E3%83%B3%E3%82%B0+%E8%A4%87%E5%90%88+%E4%BA%94%E8%BC%AA%E3%83%AA%E3%83%B3%E3%83%94%E3%83%83%E3%82%AF&hl=ja&geo=JP&no_cache=true) | [Playground (Related Topics)](https://serpapi.com/playground?engine=google_trends&q=%D0%9D%D0%B8%D0%B6%D0%B5%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D1%81%D0%BA%D0%B0%D1%8F+%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C&hl=ru&geo=RU-NIZ&data_type=RELATED_TOPICS&date=today+1-m) | [Playground (Interest by region)](https://serpapi.com/playground?engine=google_trends&q=%D0%9D%D0%B8%D0%B6%D0%B5%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D1%81%D0%BA%D0%B0%D1%8F+%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C&hl=ru&geo=RU-NIZ&data_type=GEO_MAP_0&date=today+1-m) | [Playground (Related queries)](https://serpapi.com/playground?engine=google_trends&q=%D0%9D%D0%B8%D0%B6%D0%B5%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D1%81%D0%BA%D0%B0%D1%8F+%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C&hl=ru&geo=RU-NIZ&data_type=RELATED_QUERIES&date=today+1-m)
