### ISSUE TITLE
[Google Search API Mobile] Internal Server Error [500]

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1111]
One of the customers reported that for their query they are getting `"error":"Internal Server Error [500]."`. While I couldn't recreate the issue with a different search query, it happens very often for the one customer linked.

<img width="1433" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/2db7a086-f11a-4986-a1ba-ba46396b992c">

[Playground](https://serpapi.com/playground?q=%E7%8C%AB%E9%B3%B4%E3%81%8D+%E7%97%87%E5%80%99%E7%BE%A4&location=Tokyo%2C+Japan&google_domain=google.co.jp&gl=jp&hl=ja&num=100&device=mobile&no_cache=true) | [Inspect 1](https://serpapi.com/searches/651264f5477c0ee7fad0ae9f/inspect) | [Inspect 2](https://serpapi.com/searches/6512650c10d7449a69fc6261/inspect) | [Inspect 3](https://serpapi.com/searches/6512651bc56d9356c5959a7d/inspect)

**Comment by andypple83** [comment]
May related to this error: https://github.com/serpapi/SerpApi/issues/4148. @kagermanov27 finished the fix and the PR is deploying to production.

**Comment by andypple83** [comment]
This issue should be resolved. Thanks @marm123 @kagermanov27

**Comment by marm123** [comment]
Thank you, @andypple83 and @kagermanov27!
