### ISSUE TITLE
[Google Local Services API] Some Searches Returning Fully Empty Response

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1128]
A customer reported some Google Local Services API searches are returning with a `fully_empty` response. When retried, they return results.  I was unable to replicate it in the Playground, but you can see in the screenshots that the parameters are the same but one returned empty.

<img width="1447" alt="Screenshot 2023-10-05 at 10 51 03 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/49c25c44-cbb3-4e49-9d57-95c9f7358e46">
<img width="1139" alt="Screenshot 2023-10-05 at 10 50 42 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/073e0dc3-0d87-4bbc-821f-94b6e231fe69">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000051529?view=List) | [Search Inspector ](https://serpapi.com/searches/651eef750b506216a2f7ae2e/inspect)| [Playground](https://serpapi.com/playground?engine=google_local_services&q=personal_injury_lawyer&data_cid=14091982268702231483&hl=en&job_type=auto_accidents&no_cache=true)

**Comment by andypple83** [comment]
I answered in this issue: https://github.com/serpapi/public-roadmap/issues/1211#issuecomment-2167655151

**Comment by hartator** [comment]
@andypple83's comment says:

> The official Google services local results page is broken right now. Google also introduced a new page for local services results. We'll update the SerpApi Local Service engine to scrape the new Google page.

**Comment by andypple83** [comment]
We've updated our [Google Local Services document](https://serpapi.com/google-local-services-api#api-parameters-geographic-location). Google Local Services only returns data for places inside the USA.

![Screenshot 2024-08-30 at 14 42 18](https://github.com/user-attachments/assets/b70fa7a0-ed1f-4653-bb31-9485fbc85d03)

For outside of the USA, we recommended using our [Google Local API](https://serpapi.com/google-local-api) or [Google
Maps](https://serpapi.com/maps-local-results) for now.

We will provide updates when we support the new Google Local Services page as I mentioned [above](https://github.com/serpapi/public-roadmap/issues/1128#issuecomment-2168854084).
