### ISSUE TITLE
[Google Jobs API] `hl` parameter is inconsistent and doesn't work on some searches

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1133]
It appears that for some searches, the `hl` parameter is ignored. One of our customers reported this, and I've been able to replicate the issue.

Search in English:
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/9aa53338-57ee-4e9d-8fb6-49b5336827f8">

The same search with the exact parameters and `hl=en` in Spanish:
<img width="1435" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/9b9a2542-450d-48eb-b29b-8a8b7a5e9f35">

[Inspect - English](https://serpapi.com/searches/6523e2f0ce87f8cced5f277c/inspect) | [Inspect - Spanish](https://serpapi.com/searches/6523e2d82c0844fe53369d15/inspect)
[Playground](https://serpapi.com/playground?engine=google_jobs&q=Alcampo&location=Spain&gl=es&hl=en&no_cache=true)
[Intercom
](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000051679?view=List)

Might be connected to https://github.com/serpapi/public-roadmap/issues/643

**Comment by kagermanov27** [comment]
>Might be connected to https://github.com/serpapi/public-roadmap/issues/643

This is not connected. The `hl` parameter is not manipulated before put into action like in https://github.com/serpapi/public-roadmap/issues/643.

**Comment by marm123** [comment]
I've tested this issue on a couple of API calls, including `hl=en`, `hl=es`, `hl=fr`, and `hl=de`. Every result was returned with the correct language. However, the customer reported that they still encounter the issue. I've asked for some search `ids`, so I'm leaving it open for now until we receive more data from the customer.

**Comment by marm123** [comment]
I'm closing this as the results the customer reported returned interface in the correct language. The issue the customer reported was with the job posting (description, etc.) not being translated. Since this is not what the `hl` parameter is used for, the issue seems to be resolved for now.
