### ISSUE TITLE
how can i search 'case law' part of the Google Scholar?

### ISSUE THREAD

**Issue by text2sql** [serpapi/public-roadmap#1136]
url would be https://scholar.google.com/scholar?hl=en&as_sdt=800006&q=<query>
thank you

**Comment by dimitryzub** [comment]
Hey guys 🙂 I've just received a notification and decided to leave a comment.

I wrote an [article](https://python.plainenglish.io/scrape-google-scholar-case-law-results-to-csv-in-python-and-serpapi-af4777fcfc87#3db8) some time ago about it that has both SerpApi and a custom solution.

To extract case law results, make sure that [`as_sdt` parameter](https://serpapi.com/google-scholar-api#api-parameters-search-type-as-sdt) has a value of `6`. For your exact case (from the link you showed) the value will be `800006`.

[SerpApi playground link with case law results](https://serpapi.com/playground?engine=google_scholar&q=Coffee&hl=en&as_sdt=6).

![image](https://github.com/serpapi/public-roadmap/assets/78694043/0e96bf35-0b46-4eeb-9eb9-dea33fd575f8)

**Comment by text2sql** [comment]
awesome thanks! while i was waiting for your response, i asked my buddy chatgpt to play a logical game if this is serp api url for .... , what would be serp api url for this url . got https://serpapi.com/search.html?engine=google_scholar&q=coffee&hl=en&as_sdt=800006&api_key=<api_key>

**Comment by schaferyan** [comment]
Closing this as @dimitryzub answered the question
