### ISSUE TITLE
[Google Lens API] Result Served from Cache When `country` is Changed

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1137]
A customer reported that the Google Lens API is serving results from the cache when `country` is changed.

I have verified this in the Playground. I was unable to quickly find a good example of a Google Lens search that should change based on locale, but I can see from the `created_at` and `processed_at` fields that the result is being served from the cache.

<img width="1463" alt="Screenshot 2023-10-11 at 9 36 55 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/ca9d86fc-dd8a-4487-b2ae-3223e8857787">

[Playground](https://serpapi.com/playground?engine=google_lens&url=https%3A%2F%2Fi.imgur.com%2FHBrB8p0.png&country=bd) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000051960?view=List)

**Comment by aliayar** [comment]
When I search for a different image (a dog) after default Danny Devito search, it returns correct results. A country parameter was present in this search.

[Playground](https://serpapi.com/playground?engine=google_lens&url=https%3A%2F%2Fi.imgur.com%2Fttq3F9E.jpeg&country=pl)
URL: https://serpapi.com/playground?engine=google_lens&url=https%3A%2F%2Fi.imgur.com%2Fttq3F9E.jpeg&country=pl
search_metadata > id: **6527cb42797ac6ce26ff7106**

When I search for the same image with a different country, SerpApi serves the results from the cache.

[Playground](https://serpapi.com/playground?engine=google_lens&url=https%3A%2F%2Fi.imgur.com%2Fttq3F9E.jpeg&country=us)
URL: https://serpapi.com/playground?engine=google_lens&url=https%3A%2F%2Fi.imgur.com%2Fttq3F9E.jpeg&country=us
search_metada > id: **6527cb42797ac6ce26ff7106**

When I go back to Playground and perform the same search (same URL) without any country, it still serves from the cache.

[Playground](https://serpapi.com/playground?engine=google_lens&url=https%3A%2F%2Fi.imgur.com%2Fttq3F9E.jpeg)
URL: https://serpapi.com/playground?engine=google_lens&url=https%3A%2F%2Fi.imgur.com%2Fttq3F9E.jpeg
search_metada > id: 6527cb42797ac6ce26ff7106
