### ISSUE TITLE
[Google Reverse Image Search]`total_results` Varies Significantly for the Same Search

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1138]
A customer reported their attempts to paginate using `start` were returning empty, despite the value of `total-results` in the initial request being high enough for pagination.

After investigating in the Playground, I can see that the number of results returned seems to vary significantly if you repeat the same request with `no_cache=true` several times.

This can make paginating difficult, as it's impossible to predict accurately how many pages of results you can get.

I'm uncertain whether there is anything we can do about this on our side. My only thought is that this might have to do with the rotating proxies - maybe we can try to use the same proxy again for requests where only `start` changes? 

<img width="1401" alt="Screenshot 2023-10-12 at 11 24 08 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/c7a6266a-3fd9-4643-adae-7928968c5fdc">
<img width="1399" alt="Screenshot 2023-10-12 at 11 37 58 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/2d1463e0-3238-4dfc-a795-4aa57f0f6cec">
<img width="1396" alt="Screenshot 2023-10-12 at 11 39 05 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/99424621-fe38-4320-8f15-bc8d98235092">

[Search Inspector (15 total results)](https://serpapi.com/searches/6528254e5fc4930a6650859b/inspect) | [Search Inspector (44 total results)](https://serpapi.com/searches/65282509681ebeb350d3b439/inspect) | [Playground ](https://serpapi.com/playground?engine=google_reverse_image&start=10&image_url=https%3A%2F%2Fcdn.imgchest.com%2Ffiles%2F6yxkcx8kv27.jpg&no_cache=true)| [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000051968?view=List)

**Comment by schaferyan** [comment]
Another customer asked about this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000053082?view=List)

**Comment by marm123** [comment]
Marking this as urgent as the customer is inquiring about the solution.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055545?view=List)

**Comment by tanys123** [comment]
Google returns inconsistent result for nearly every new page. 

<img width="397" alt="Screenshot 2023-12-27 at 11 17 25 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/c7a15b17-5b36-4535-9159-0271c6fd05d2">

<img width="742" alt="Screenshot 2023-12-27 at 11 17 39 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/d59d7814-600c-4125-9901-346bef4af454">

<img width="737" alt="Screenshot 2023-12-27 at 11 17 47 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/72229b2c-9283-4bbc-8072-697a02dafb17">

<img width="730" alt="Screenshot 2023-12-27 at 11 20 12 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/aed13cdf-40e0-441b-bcdb-1bd73e4baf46">

---

It seems the total result isn't accurate either. The accurate total results is only shown at the last page (which cannot be determined initially)

[Example 1](https://www.google.com/search?sca_esv=593893048&tbs=sbi:AMhZZiv2NTBpR6tIdabERX2NqcXIhEJMW8ng_12jl-J0iTq1iIKtjvohWppArAZb1pWZaMWEy7XJnoYN-ElQPJNaV5qAmRq5OzwpUCl6OlzsqXw5cbZNp7lbvIxxgLRfH39FU-dP_1Epmfp5XvnkcBspGRNWde1PaT-dBJL99vcwPUNlGre_12DgqLMq9z459vvv-DlyyrMTD8W0ikDLHIVmJsf4vWk9729kySSvYLOCU9OMKDV667asATls-RkNhVhcCFUOu9_1BnWaHU_1s9DrtW4w99NTmD-OJRCVxYiLP1REFJDnyKLWzMcLMo_1bQwen3mA7zOkkbYgnWpvvWe0InoHP2720CrQIO3Q&ei=ap-LZbL2FougnesPwdO18A8&start=223&sa=N&biw=1470&bih=798&dpr=2)

First page:
<img width="763" alt="Screenshot 2023-12-27 at 12 02 11 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/533f6554-c472-47bf-9ef2-1e4812e2b1b5">

When `start=223`, the total results drop to `228` and `223 + 5 = 228` which match the total results. 
![screencapture-google-search-2023-12-27-12_05_18](https://github.com/serpapi/public-roadmap/assets/10222402/4132432e-828e-4a9f-ad97-df946b640d68)

---

[Example 2](https://www.google.com/search?sca_esv=593893048&tbs=sbi:AMhZZivDlGnOwE6CMxhnqjlpE8YQJ5RZOAxk6sO8-zdONYcSxP2n-dyF_1f9QNejpQpbdna9HjHIXxYUsU5QOiKpVDfuxYsnAOJ0UGgNpIo1knSwQgh6X4pEymDQ76ak5F9DdEqnUTpv-GWFI6YUUnMhOmgqzXrYeQT9hHdxA1Y9upng3xS1tpBd0c-2Wp3Yq4d7VyLvexkmshgfY_1e4CSeeWnAQMNjhyi6J4V0cz5cyWTtPLvaWoT6sxUIdD7kVYDhw-ywFA7CjRoBkI7XFNc8zfug8GMYnpycZO8d72Q8AzF6RKo9vzy8AWGjrTkoiEaeqE16oZmj6iKGVeZFQUmydPTV0iY-SPHw&ei=Yp2LZdWWHrGgseMPhvmN2AQ&start=93&sa=N&biw=1470&bih=798&dpr=2)

First page:
<img width="712" alt="Screenshot 2023-12-27 at 12 02 37 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/6d10fa5a-b8cc-4d96-b3cd-3f4e572f6b60">

End of page:
<img width="746" alt="Screenshot 2023-12-27 at 12 02 24 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/6592c955-4449-4311-82d8-1c56db013e0e">

---

[Another example](https://www.google.com/search?sca_esv=593893048&tbs=sbi:AMhZZisq1AdrKmHj2ozZvrObW9SO4mDSCquw_1jUDLyGxLTaXkm4eRTNQgIEXBHBX8dQClw73K_1NdlJicfBwAGJgT-vk2OjAOXyXvG15ztSCj0i_1zKez8M0MbhIzK8GuUwotMRO8xT-HrPWeI8cCLXwkuDD5xEcPdxa1p92c9H7DwNU3ACSfMQYAQlQ_1BE6guKD_1AfhOWFahlI_16aVINDE_19PA5KZgJLV2F9WbxYoeQjkXveeewx2Vqz6xN3KlJgsA1-HX_1Og1fc8rUTafgkb9gVlcwit7cyxe_1yd-xTprT--z3QiN6r73fPEUisc2jTMzjIoNQ475do0o1I_1u4d3a1u71RAL60RrCo0K_1yj_1z8eM-LZ8tErA0j8&ei=e56LZfj2F4yNnesPmdexyAM&start=130&sa=N&biw=1470&bih=798&dpr=2) 

---

That's said, I think there is room for improvement on [Google Reverse Image API](https://serpapi.com/google-reverse-image) about the paginated results. 

We can make use of `tbs` value returned from the reverse image response. The `tbs` value increase the consistency of result until the end of the page.

[Playground Example](https://serpapi.com/playground?q=Elon+Musk&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbs=sbi%3AAMhZZivBgxan6w6oG6HcR9SoW5vX3IORUuEcLo1GICsCYVULob3jw6SQJiKpgbLy8XvZU6cROQvGkZ3b_1moIbfLDgVznmIKOr4SXcIKQ9PoEzmgxT0bLv3KD5kUQfpb607P6vBZ85Tna7gak5eGfNKqthTyEwr1abu1YdpvfATbsNK5pU8-HbbmbVXaxobJ0OpIRx3WF6RQsk5JWOr9kh0hiRxhCu6z58IbFtEjlYxs2e9vKDplOgX8NpVgytc2OBUSpKpNtcNhkfhuQIjvKO-NflTwVVyFlaKPnHdlqdYx7Cgcocrg0u4dfxAEChf08yGdMp966iI42y8WDUMhUUsCFh0ETEn-2cw&start=200&no_cache=true&google_domain=google.com&newPara=ie+oe+pws+ibp+votes+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client)

**Comment by hartator** [comment]
> Google returns inconsistent result for nearly every new page.

Yes, it's random also on my computer.

Let's close this as it seems purely on Google side. Maybe we can write a blog post about these findings.
