### ISSUE TITLE
[New API] Support Google Patents detail page

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1141]
We currently support Google Patents search, but we can also support the Google Patents detail page, similar to how our `Google Shopping-Google Product` or `Google Jobs-Google Jobs Listing` work. Details pages are based on the `patent_id` that we already extract:

<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/3e1ff472-2b0a-45ee-bb90-814a56f9f255">

Google Patents detail page:
<img width="1161" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/ff2bbbc2-7fb9-4b39-a8a6-290669049bc9">

[Google Patents detail page](https://patents.google.com/patent/US11266160B2/en)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000052266?view=List)

**Comment by martin-serpapi** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053525?view=List)

**Comment by tdalessio** [comment]
@schaferyan thanks for updating this, I'm happy to help test as I'm the one who just requested being able to view multiple assignees

**Comment by tdalessio** [comment]
Just following back up on this to see if there are any updates, please let me know if there is anything I can do to assist.  Looking to use this API for an active project we have going on.

**Comment by zyc9012** [comment]
@tdalessio The implementation is under review. It should be out soon.

**Comment by zyc9012** [comment]
@tdalessio The API is available now. [Documentation link](https://serpapi.com/google-patents-details-api)
