### ISSUE TITLE
[Google Maps Place Results API] Scrape and Return Booking Link

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#1142]
Google Maps Place Results pages may include a booking link along with website link. We currently don't scrape the booking link.

![booking_maps](https://github.com/serpapi/public-roadmap/assets/64849049/d969ae36-70d5-4b12-a324-1a84d0b2d51c)

![image](https://github.com/serpapi/public-roadmap/assets/64849049/028ff387-14fe-4bb1-b470-27943b8be53a)

[Playground](https://serpapi.com/playground?engine=google_maps&q=Coffee&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&data=!3m1!4b1!4m6!3m5!1s0x487760d5a813a0ed%3A0xa081a873e2f526a7!8m2!3d52.6360771!4d-1.1311002!16s%252Fg%252F11b6j113kn&type=place) | [Inspect](https://serpapi.com/searches/652e82cbf05eb8356bb18438/inspect) | [Google Maps](https://www.google.com/maps/place/Maid2Clean/@52.6360485,-1.2134998,12z/data=!3m1!4b1!4m6!3m5!1s0x487760d5a813a0ed:0xa081a873e2f526a7!8m2!3d52.6360771!4d-1.1311002!16s%2Fg%2F11b6j113kn?entry=ttu) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000052273?view=List)

**Comment by spirie** [comment]
Awesome, quick work guys - thank you!
