### ISSUE TITLE
[Google Trends API] Searches Taking Over 30 Seconds and Failing

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1143]
A customer reported they are experiencing a lot of Google Trends API searches failing with a 502 error.

I tried the example they provided in the Playground- it failed the first time but worked when I retried without the cache.

All Google Trends API searches seem to be very slow right now though, which is reflected in our status graph. Oddly, they seem to be taking even longer with Ludicrous Speed than without.

<img width="1026" alt="Screenshot 2023-10-17 at 2 56 19 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/955d349a-9282-45b3-9cbd-5a07115ee1fb">
<img width="1077" alt="Screenshot 2023-10-17 at 2 55 48 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/d1f6d5b2-46e1-4fdb-a513-8ea0ed250411">

[Inspector ](https://serpapi.com/searches/652efad9b7b1cc696e35f14e/inspect)| [Playground](https://serpapi.com/playground?engine=google_trends&q=bikes&geo=US&data_type=RELATED_QUERIES&cat=0&date=now+1-d&no_cache=true) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000052301?view=List)

**Comment by hilmanski** [comment]
Looks like this is still happening.

- [Intercom1](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000052323?view=List

**Comment by martin-serpapi** [comment]
Another customer reported the issue. The error In the search ID they've provided is different:

"_We couldn't get valid results for this search. Please try again later._"

![image](https://github.com/serpapi/public-roadmap/assets/144151895/5c2a4f9d-db30-4a3b-9666-fb48c2a6e205)

[Inspector](https://serpapi.com/searches/6538e44a2f542eb04aed9c7b/inspect)

But when I tried to execute a search with the same parameters I received the same error that @schaferyan reported originally:

"_We couldn't get valid results for this search. Please try again later. Set the `no_cache` parameter to true in order to force a retry._"

![image](https://github.com/serpapi/public-roadmap/assets/144151895/bf889273-7499-476e-95ad-bd8d3e9872b9)

[Inspector](https://serpapi.com/searches/6538e9420574f532c3d4ea15/inspect) | [Playground](https://serpapi.com/playground?engine=google_trends&q=bokeh&geo=ID&data_type=RELATED_TOPICS&date=now+1-d)

I got the same error when I tried with different date parameter as well (`now 7-d` & `now 4-H`):

![image](https://github.com/serpapi/public-roadmap/assets/144151895/2b074d4d-c739-440f-815b-e6be7bd55827)

[Inspector](https://serpapi.com/searches/6538ebc7c999030c8a9a50cd/inspect) | [Playground](https://serpapi.com/playground?engine=google_trends&q=bokeh&geo=ID&data_type=RELATED_TOPICS&date=now+7-d) 

![image](https://github.com/serpapi/public-roadmap/assets/144151895/9b8e1c21-953b-4d2e-ab02-f54a6f580b5e)

[Inspector](https://serpapi.com/searches/6538ebec9d158678c1748616/inspect) | [Playground](https://serpapi.com/playground?engine=google_trends&q=bokeh&geo=ID&data_type=RELATED_TOPICS&date=now+4-H)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000052753?view=List)

**Comment by hilmanski** [comment]
A potential customer is asking about our Google Trends API status.
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053002?view=List)

**Comment by aliayar** [comment]
Another user reported long response times.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053026)

**Comment by martin-serpapi** [comment]
Another customer reported slow response times:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053268?view=List)

**Comment by robrady** [comment]
Hi, I was wondering do you have any update on this issue and whether there is a solution in the pipeline? Thanks, R

**Comment by schaferyan** [comment]
Another customer with this issue. They are using `data_type=RELATED_TOPICS` and they are only experiencing the issue when `date` indicates a shorter time span than 1 month. I was able to verify this in the Playground. For example, this search returns the error:

[Playground](https://serpapi.com/playground?engine=google_trends&q=Cat&geo=US&data_type=RELATED_TOPICS&tz=420&date=now+1-d) | [Inspector](https://serpapi.com/searches/655e5fa69c84ac10e79db9f2/inspect)

This search does not:

[Playground](https://serpapi.com/playground?engine=google_trends&q=Cat&geo=US&data_type=RELATED_TOPICS&tz=420&date=today+1-m) | [Inspector](https://serpapi.com/searches/655e624eedb03477e43f123e/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054108?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054415?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054795?view=List)

**Comment by marm123** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055215?view=List)

**Comment by tvierb** [comment]
I have that problem, too.
I try to get data for data_type=RELATED_QUERIES. There's a timeout "503 Service Unavailable" after 90 seconds.

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055238?view=List)

**Comment by djsegal** [comment]
This may have been partially resolved by: https://github.com/serpapi/SerpApi/pull/4397

Will monitor more in the coming days/weeks

**Comment by hilmanski** [comment]
A user reported this issue.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056548?view=List) | [Inspect1](https://serpapi.com/searches/659b62bdedb03490867bf581/inspect) | [Inspect2](https://serpapi.com/searches/659b5f40ca968fec2050546b/inspect) | [Inspect3](https://serpapi.com/searches/659b55e4f636ff6a16e1f4c5/inspect) 

Upon testing, I'm also not able to finish the request on the playground (coffee sample).
[Playground](https://serpapi.com/playground?engine=google_trends&q=Coffee&newPara=hl)

**Comment by marm123** [comment]
Another user is reporting the same.

[Inspect](https://serpapi.com/searches/659b1de5e815af75eeb4dc63/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056594?view=List)

**Comment by schaferyan** [comment]
Another user is reporting this issue, this time they are using `"data_type":
"RELATED_TOPICS"`.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056625?view=List) | [Inspect 1](https://serpapi.com/searches/659c34dc66440ae176503ac4/inspect) | [Inspect 2](https://serpapi.com/searches/659c25119b647237fb1b6ab7/inspect) | [Inspect 3](https://serpapi.com/searches/659c25540ead41624c8877be/inspect) | [Inspect 4](https://serpapi.com/searches/659c25e50574f5d297cd16c8/inspect)

**Comment by schaferyan** [comment]
A customer interested in using our Google Trends API at high volume after it is fixed:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055332?view=List)

**Comment by schaferyan** [comment]
Another customer with this issue:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056643?view=List)

**Comment by schaferyan** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056641?view=List)

**Comment by schaferyan** [comment]
I want to note for customers checking this issue that while we've seen this symptom previously with our Google Trends API, the consistent problem reported recently seems to be due to fresh changes on Google's side. We are actively working toward a solution and hope to have an update soon.

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056680?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056683?view=List)

**Comment by marm123** [comment]
A couple of more customers reported the same, including a potential Enterprise Customer:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000050506?view=List) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056694?view=List) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056695?view=List)

**Comment by marm123** [comment]
One of our customers shared their solution. I'm not sure if this is relevant in our case, but maybe parts of it might be helpful.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056694?view=List)

**Comment by schaferyan** [comment]
An Enterprise customer asked for an update on this

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056731?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056791?view=List)

**Comment by schaferyan** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056844?view=List)

**Comment by schaferyan** [comment]
A potential customer who wants to subscribe to use Google Trends:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056852?view=List)

**Comment by marm123** [comment]
Another report from a user:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056871?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056906?view=List)

**Comment by schaferyan** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056926?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056963?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056967?view=List)

**Comment by marm123** [comment]
Another report from the customer:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056992?view=List)

**Comment by schaferyan** [comment]
UPDATE: we have determined a potential solution and are taking steps to implement it.

However, the new approach may cause the Google Trends API  not to perform at the same speed it did previously. Will response times be a significant problem for users of this API?

**Comment by marm123** [comment]
Some more users reported the issue:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000057093?view=List) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000057094?view=List)

**Comment by AbhishekThalanki** [comment]
Hello @schaferyan,
As a regular user of the API, speed isn't a deal-breaker for me as long as the response is reliable and consistent. I appreciate the efforts being made to implement a solution. Could you provide an estimate for when the solution will be made available?
Thank you!

**Comment by ilyazub** [comment]
Closing this issue because we fixed our Google Trends API. Please let us know if it doesn't work _for you_.
