### ISSUE TITLE
[Google Related Questions API] Default Token to be Changed

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#1146]
Currently, the default token for `Google Related Questions API` in **Playground** doesn't work. We need to change it so that when users browse `Related Questions API` in Playground, they can see that it is working. We received two questions about it so far.

![image](https://github.com/serpapi/public-roadmap/assets/64849049/8f96298d-695d-4f9b-8d07-b1cacd33d694)

[Intercom 1](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000052318?view=List) | [Intercom 2](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000052256?view=List) | [Playground](https://serpapi.com/playground?engine=google_related_questions&next_page_token=eyJvbnMiOiI2MjAiLCJmYyI6IkVxRUJDbUpCUVhSV2JHSkNYMHBVWWxScWFubHlYemRYY2paUmQzQmZUbkE0WWxSTE9VWkxaMmcyYW10elZHSkJSRkp0V0Zsa1dWQjBlbEpZTkdOQmFFTXdNVVpCVjB0UE5rWTNVMGhXTkdaQmFVazBjVmgzT0hjdExXVTRaVW94TTJaUVNtOVBaeElYWTNoVFpsbHlYMFZGUzIxeWNYUnpVSFZQUzJKblFYTWFJa0ZFVlhsRlIyTlVWams0WkZOMFgyMVpaemM0ZVRkVlVqRlhVMDUwYkRGa1lrRSIsImZjdiI6IjMiLCJlaSI6ImN4U2ZZcl9FRUttcnF0c1B1T0tiZ0FzIiwicWMiOiJDZ1pqYjJabVpXVVFBSDBNVlVRXyIsInF1ZXN0aW9uIjoiSXMgY29mZmVlIGdvb2QgZm9yIHlvdXIgaGVhbHRoPyIsImxrIjoiR2g1cGN5QmpiMlptWldVZ1oyOXZaQ0JtYjNJZ2VXOTFjaUJvWldGc2RHZyIsImJzIjoiYy1OUzRaTDNMRlpJems5TFMwMVZTTV9QVDFGSXl5OVNxTXd2TFZMSVNFM01LY213bDdoandLWEJwUnlla1ZpaWtGbXNVSktScXBDVW1wZWFsbGxTckpDZkJ1WkR0TnRMVEtybHdtNWVlV3BtZWthSlFrNS1jYkc5eENwaExqa3VTWVNxM01TVVZJVzBvdnhjaFlMOF9BSjdpWVlTQVVZQSJ9)

**Comment by schaferyan** [comment]
We could also consider using a static example, similar to what we use for https://serpapi.com/playground. It would save us from having to update the default token regularly.

**Comment by aciddjus** [comment]
This has been fixed. The empty results for all queries will be addressed in [this PR](https://github.com/serpapi/SerpApi/pull/5222).
