### ISSUE TITLE
[Google Maps Reviews API] No Results Returned for Searches with Some place_id Values

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1147]
A user reported that some `Google Maps Reviews API` searches don't return any reviews, when using `place_id` parameter to perform the searches.

`place_id`: ChIJYTo-lRC9oRQR0qmidOZXGWk

![image](https://github.com/serpapi/public-roadmap/assets/144151895/96665afa-d7bc-4cdc-8d0b-39c11e6bffe2)

[Playground](https://serpapi.com/playground?engine=google_maps_reviews&hl=en&place_id=ChIJYTo-lRC9oRQR0qmidOZXGWk) | [Inspect](https://serpapi.com/searches/652fbefe8b7ed23412968af2/inspect)

`place_id`: ChIJieKS_dOK12oRHG--MnPmil8

![image](https://github.com/serpapi/public-roadmap/assets/144151895/c7effc1c-2c2d-47d3-bff3-0765cc8898b6)

[Playground](https://serpapi.com/playground?engine=google_maps_reviews&hl=en&place_id=ChIJieKS_dOK12oRHG--MnPmil8) | [Inspect](https://serpapi.com/searches/652fa93aaef2647e620b148c/inspect)

`Google Maps API` returns results when using the same `place_id` for the search.

`place_id`: ChIJYTo-lRC9oRQR0qmidOZXGWk

![image](https://github.com/serpapi/public-roadmap/assets/144151895/341e843e-4491-4675-93d4-b27e08ce9b9a)

[Playground](https://serpapi.com/playground?engine=google_maps&ll=%4041.39551101804151%2C+2.169972293465933%2C14z&hl=en&place_id=ChIJYTo-lRC9oRQR0qmidOZXGWk&type=search) | [Inspect](https://serpapi.com/searches/652fafbef0adfb248a751fb2/inspect)

`place_id`: ChIJieKS_dOK12oRHG--MnPmil8 

![image](https://github.com/serpapi/public-roadmap/assets/144151895/917c1aca-ae82-4b5e-b14e-d73bf1b5b6dd)

[Playground](https://serpapi.com/playground?engine=google_maps&ll=%4041.39551101804151%2C+2.169972293465933%2C14z&hl=en&place_id=ChIJieKS_dOK12oRHG--MnPmil8&type=search) | [Inspect](https://serpapi.com/searches/652fb59ae1350820d0a35bde/inspect)

`Google Maps Reviews API` returns results when performing searches with the `data_id`'s corresponding to those `place_id`'s.

`place_id`: ChIJYTo-lRC9oRQR0qmidOZXGWk | `data_id`: 0x14a1bd10953e3a61:0x691957e674a2a9d2

![image](https://github.com/serpapi/public-roadmap/assets/144151895/70a35f60-fac4-431b-9272-4d837deee678)

[Playground](https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x14a1bd10953e3a61%3A0x691957e674a2a9d2&hl=en) | [Inspect](https://serpapi.com/searches/652fbff496f5d7f14099a63f/inspect)

`place_id`: ChIJieKS_dOK12oRHG--MnPmil8 | `data_id`: 0x6ad78ad3fd92e289:0x5f8ae67332be6f1c

![image](https://github.com/serpapi/public-roadmap/assets/144151895/cc615e9a-5a9b-475a-bbb0-35d1f4a04d57)

[Playground](https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x6ad78ad3fd92e289%3A0x5f8ae67332be6f1c&hl=en) | [Inspect](https://serpapi.com/searches/652fb7a3382427c11ad3871c/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000052328?view=List)

**Comment by aciddjus** [comment]
It looks like it is happening for hotels only. When using `place_id`, Google redirects the page to Google Travel Hotels, which we do not scrape.

[Example Google search](https://search.google.com/local/reviews?placeid=ChIJnexAMO6ipBIRJXdyhVotT8g) for "El Palace Hotel Barcelona" with place_id: `ChIJnexAMO6ipBIRJXdyhVotT8g`

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059194?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059485?view=List)

**Comment by aciddjus** [comment]
This issue has been resolved.

We can now extract reviews for hotels, rentals, and other similar places using their `place_id` parameter.

![image](https://github.com/serpapi/public-roadmap/assets/6929257/13864913-2b2b-46ab-aae2-ad433b701dfd)


[Playground link](https://serpapi.com/playground?engine=google_maps_reviews&hl=en&place_id=ChIJYTo-lRC9oRQR0qmidOZXGWk&no_cache=true)
