### ISSUE TITLE
[Google Trends API] `related_queries` not returning results

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1149]
A customer reported that Google Trends API does not return any results. I've tested it in the Playground with `"q":"Coffee"` and `"date":"today 12-m"` and no results are returned:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/416baf62-0d27-429e-91d7-15d61878144e)

[Playground](https://serpapi.com/playground?engine=google_trends&q=Coffee&data_type=RELATED_QUERIES) | [Inspect](https://serpapi.com/searches/65312beea5ad6d59ca5bbd35/inspect)

Customer Searches Inspector [1](https://serpapi.com/searches/653128f09c449db4651fe13a/inspect) | [2](https://serpapi.com/searches/653128b40ead413cefe4ab46/inspect) | [3](https://serpapi.com/searches/65311a5b3e86ace11f95a1ac/inspect) | [4](https://serpapi.com/searches/6531184dc640d228369fb6b6/inspect) | [5](https://serpapi.com/searches/653117f718ca8623496e78de/inspect) | [6](https://serpapi.com/searches/653117282e7d6bc2062c53b3/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000052409?view=List)

**Comment by aliayar** [comment]
Related #1069.

**Comment by ali-ghadimi** [comment]
I've been encountering an error with your "google_trends" feature, specifically the "RELATED_QUERIES" function. The issue began around midday London time (6 Nov 2023) and has been inconsistent over the past few days. This has caused significant delays in my work.

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053427?view=List)

**Comment by aciddjus** [comment]
Closing this as it should have been fixed, and there are other related issues open.
