### ISSUE TITLE
[Google Shopping Product API] Reviews Pagination not Working

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#115]
SerpApi can't paginate to second and following pages to parse more reviews. Despite parameters, it gets stuck on the first page of reviews.

First page:  [The Playground](https://serpapi.com/playground?engine=google_product&product_id=4887235756540435899&gl=us&hl=en&reviews=1) | [The Inspect](https://serpapi.com/searches/625e6b44c640d295227d8cf9/inspect) | [Google](https://www.google.com/shopping/product/4887235756540435899?sourceid=chrome&ie=UTF-8&hl=en&gl=us)

<img width="953" alt="shopping_first_page" src="https://user-images.githubusercontent.com/64849049/163955378-aa8e8c5b-e3e3-417f-8c80-f96d6af8b39b.png">

Second page: [The Playground](https://serpapi.com/playground?engine=google_product&product_id=4887235756540435899&gl=us&hl=en&start=10&reviews=1) | [The Inspect](https://serpapi.com/searches/625e6bb14055aac9ef4d9024/inspect) | [Google](https://www.google.com/shopping/product/4887235756540435899/reviews?sourceid=chrome&ie=UTF-8&hl=en&gl=us&prds=rstart:10)

<img width="953" alt="shopping_second_page" src="https://user-images.githubusercontent.com/64849049/163955972-e5ff6053-015d-4359-aca3-8a0483bd0b84.png">

Neither start nor page params are working at the moment.

**Comment by ilyazub** [comment]
Google started using `rpt:C<int><int>` filter (`prds`) parameter for pagination. [Example URL](https://www.google.com/shopping/product/4887235756540435899/reviews?sourceid=chrome&ie=UTF-8&hl=en&gl=us&prds=rpt:CBO).

While we're working on the fix, the `rnum:100` filter parameter can be used to fetch at least the first 100 reviews. Our documentation is missing this filter.

[Example Google URL](https://www.google.com/shopping/product/4887235756540435899/reviews?sourceid=chrome&ie=UTF-8&hl=en&gl=us&prds=rpt:CBO,rnum:100)

![2022-04-21_21-18](https://user-images.githubusercontent.com/282605/164527231-08b801a9-c2f1-4658-ad5f-06d29be6488c.png)

[Playground URL](https://serpapi.com/playground?engine=google_product&product_id=4887235756540435899&location=United+States&gl=us&hl=en&reviews=1&filter=rnum%3A100)

![image](https://user-images.githubusercontent.com/282605/164527475-a43e9846-0161-48a4-9abd-8445fa956420.png)

**Comment by ilyazub** [comment]
We've just shipped a fix. Sorry for the huge delay with this issue.

The next page URL is available via `serpapi_pagination.next`. There's also a `serpapi_pagination.next_page_filter` that contains the value for the filter parameter. Here's an example [Playground page](https://serpapi.com/playground?engine=google_product&product_id=4887235756540435899&gl=us&reviews=1&filter=rnum%3A100%2Crpt%3ACGQ).

![image](https://user-images.githubusercontent.com/282605/167600657-6869537f-1326-49be-a6c4-19cd949b3860.png)
