### ISSUE TITLE
[Google Search API] [Answer Box API] Hotel `price` is not extracted

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1158]
We are not extracting hotel `price` in our `answer_box` on both desktop and mobile.

<img width="1468" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/7bc16487-dce9-4f66-95e6-d3ebbb1a9b56">

[Playground](https://serpapi.com/playground?q=hotels+in+boston&gl=us&hl=en&highlight=answer_box&google_domain=google.com)
[Inspect](https://serpapi.com/searches/6571e06924e88e134b8a52c1/inspect)
[Documentation](https://serpapi.com/direct-answer-box-api#api-examples-hotels-answer-box)

------------------

TODO:

- [ ] Add parser to extract results on desktop and mobile
- [ ] Add tests for desktop and mobile
- [ ] Confirm that the solution works using different localization

**Comment by Freaky** [comment]
I can't reproduce this problem - prices are extracted successfully from multiple sites and locations and across multiple queries on both desktop and mobile layouts.

**Comment by Freaky** [comment]
Looks like a variation on an alternative layout we added support for last year.  I'll expand the testing to include this case and implement a fix.

**Comment by ilyazub** [comment]
`reviews` are extracted incorrectly:

![image](https://github.com/serpapi/public-roadmap/assets/282605/ba73282d-4a86-40e5-9270-9413bb451069)
[Playground](https://serpapi.com/playground?q=ny+hotels&location=Turkey) | [Search Inspector](https://serpapi.com/searches/6585d29c477c0ed1c257b5f2/inspect)

**Comment by Freaky** [comment]
Thanks @ilyazub - looks Turkish-specific.  Will make this extraction more robust.
