### ISSUE TITLE
[Google Shopping Product API] Support Review Insights

### ISSUE THREAD

**Issue by ilyazub** [serpapi/public-roadmap#116]
[Sample page URL]( https://www.google.com/shopping/product/4887235756540435899/reviews?sourceid=chrome&ie=UTF-8&hl=en&gl=us&prds=cid:4887235756540435899,cs:1,rnum:8,rsk:PC_9780189300843342177,rsort:1,sgro:or).

![image](https://user-images.githubusercontent.com/282605/164458189-1451e123-751a-4604-bd2e-32b9272b4e46.png)

Sample URL with Insights: https://www.google.com/shopping/insights?cid=9&prds=asp:652,rsk:PC_9780189300843342177&ved=0ahUKEwiugofik6X3AhVtlosKHRbkAi0Qk9AHCBkoBw&fmt=json

**Comment by hartator** [comment]
Closing this as stale.
