### ISSUE TITLE
[Google Search API] `time` type `answer_box` not parsed for some searches

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1162]
<img width="1468" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/60d24e5c-769a-4877-8ccb-6d27e1f03a83">

[Playground](https://serpapi.com/playground?q=Sunset+in+Austin%2C+TX&highlight=answer_box&google_domain=google.com&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client)
[Inspect](https://serpapi.com/searches/653315b4607393267aaf31c8/inspect)

**Comment by btaunt** [comment]
Making a note that on mobile we also pull this `answer_box` into organic results:

![image](https://github.com/serpapi/public-roadmap/assets/137819397/0a4e7a32-b7b7-453d-9939-9d81c515440c)
