### ISSUE TITLE
[Google Search API] `ludocid` and `lsig` parameters don't work

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1175]
I've tested a couple of cases with different `ludocid` parameters extracted from Google Maps (they are considered `data_cid` there) and `lsig` parameters from Google Local. None of them work. My understanding is that they should override the search query, like `kgmid` parameter in Google Search API or `ludocid` in Google Local.

Google Search API with `ludocid`:
<img width="1437" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/195e2a64-8e69-4da4-a35f-cd392f1a3d1b">

Google Local API with the same `ludocid`:
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/d7aa8d85-183b-402d-8a56-96b2c9adaf1c">

`lsig` from Google Local API is ignored in Google Search API:
<img width="1438" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/2536b897-797d-4269-96b8-91ce44dea9f0">

Perhaps these parameters are deprecated by Google. If that's the case we should remove them from the Playground and our Documentation.

[Playground with `ludocid`](https://serpapi.com/playground?q=Football&location=Austin%2C+Texas%2C+United+States&ludocid=11859840425088059614&gl=us&hl=en&google_domain=google.com&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client) | [Inspect with `ludocid`](https://serpapi.com/searches/653911b010d744bebb28da6a/inspect)
[Playground with `lsig`](https://serpapi.com/playground?q=Football&location=Austin%2C+Texas%2C+United+States&lsig=AB86z5WkM5El4xKH_xwD9BA_zMCz&gl=us&hl=en&google_domain=google.com&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client) | [Inspect with `lsig`](https://serpapi.com/searches/65391283f8f5f7ff1a86df93/inspect)

**Comment by martin-serpapi** [comment]
Another high volume customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000066769?view=List)

**Comment by schaferyan** [comment]
After some investigating, `ludocid` and `lsig` do seem to work on Google's side, at least for some searches:

https://www.google.com/search?q=Starbucks&ludocid=10605736027611436825&lsig=AB86z5WTpvaQGLXDoCOu1q-5cDoT

However, both `lsig` and `ludocid` need to be included, and the query needs to match the name of the business. A random `q` value will not be overrriden. Notice also `lsig` is different, compared to the `lsig` we scrape with our Google Local API for this business: 

AB86z5XTJ_Io_anVBu2fU6Zaqu3b
AB86z5WTpvaQGLXDoCOu1q-5cDoT

https://serpapi.com/playground?engine=google_local&q=coffee&ludocid=10605736027611436825

So we may be scraping `lsig` incorrectly.

I also noticed that it doesn't work if the `oq`, `sourceid` and `ie` parameters are included:

https://www.google.com/search?q=starbucks&oq=starbucks&ludocid=10605736027611436825&lsig=AB86z5WTpvaQGLXDoCOu1q-5cDoT&sourceid=chrome&ie=UTF-8

The CID can also be used with a URL like https://local.google.com/place?id=10605736027611436825&use=srp. It resolves to https://serpapi.com/playground?engine=google_local&q=coffee&ludocid=10605736027611436825.

**Comment by schaferyan** [comment]
After taking another look at this, it seems like the first letter of `q` has to be capitalized to get the knowledge graph this way. The  `oq`, `sourceid` and `ie` parameters for some reason seem to affect whether Google automatically capitalizes it. If you capitalize the query, it works even with those parameters included.

This is true when using SerpApi:

[not capitalized](http://localhost:3000/playground?q=starbucks&ludocid=10605736027611436825&lsig=AB86z5WTpvaQGLXDoCOu1q-5cDoT&no_cache=true) |  [Capitalized](https://serpapi.com/playground?q=Starbucks&location=Austin%2C+Texas%2C+United+States&ludocid=10605736027611436825&lsig=AB86z5WTpvaQGLXDoCOu1q-5cDoT&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=chips+as_sitesearch+highlight+stick+lr+as_qdr+votes+site+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+rlz+ijn+interval+as_dt)

**Comment by schaferyan** [comment]
Closing this in favor of https://github.com/serpapi/public-roadmap/issues/2003 since the parameters work when used correctly, we just need to clarify the documentation for these
