### ISSUE TITLE
[Google Play Product API] False Empty Results when `sort_by` is set to `Rating`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1177]
<img width="1196" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/86664153-c8f5-444b-b5db-5c9fbd1cfc7b">

[Playground](https://serpapi.com/playground?engine=google_play_product&product_id=KjWNBwAAQBAJ&gl=us&store=books&all_reviews=true&platform=tablet&sort_by=3&num=10&no_cache=true)
[Inspect](https://serpapi.com/searches/6539aa11f26ac6734594baa4/inspect)

The same search with other `sort_by` values works just fine.

**Comment by andypple83** [comment]
Changelog: https://github.com/serpapi/public-roadmap/issues/1203#issuecomment-1960820395
