### ISSUE TITLE
[Google Maps API] No Results Returned for Some Searches Where Results are Returned in the Playground

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1180]
A customer reported that their search is not returning any results:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/6ebff321-0c58-4e7e-af02-0d00639ef66a)

[Inspect](https://serpapi.com/searches/6537fcc4aef264ba5a471458/inspect)

Using the same search parameters n the Playground, there are results returned:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/43d030f2-aac3-475b-82ef-3ec546e98a63)

[Playground](https://serpapi.com/playground?engine=google_maps&q=movers%2C+storage%2C+moving+company+near&ll=%4036.07536%2C-119.8155%2C14z&hl=en&type=search&start=20&no_cache=true) | [Inspect](https://serpapi.com/searches/653b7ebfd3aba2920fa81ffa/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000052687?view=List)

**Comment by hartator** [comment]
This might be a random failure. Let's refund the search and re-open if there are more.
