### ISSUE TITLE
Documentation for Error Codes

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1181]
A customer has requested a documentation of the errors and status codes that they can expect to be returned when using our APIs.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000052687?view=List)

**Comment by hilmanski** [comment]
I think documentation for possible errors is very important as well.

Possible errors I could think of:
- Missing API Key.
- Exceed hourly throughput limit.
- Exceed monthly plan.
- Problem on SerpApi side.

Other users have asked this as well in the past.
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000052221#part_id=comment-102910000052221-21909681868)

**Comment by marm123** [comment]
Another customer requested this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055762?view=List)

**Comment by martin-serpapi** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056793?view=List)

**Comment by martin-serpapi** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070147?view=List)

**Comment by NateSkiles** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071564?view=List)

**Comment by hilmanski** [comment]
A high-volume customer requested this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072134?view=List)

**Comment by tanys123** [comment]
We have documented the Error Codes, feel free to checkout the [documentation](https://serpapi.com/api-errors).

<img width="1066" alt="Screenshot 2024-11-25 at 11 20 20 AM" src="https://github.com/user-attachments/assets/a168e3ad-96fb-4da6-b519-61f03d6f73c1">
