### ISSUE TITLE
[Google Maps Reviews API] Scrape Translated Snippet

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1184]
Google sometimes provides translations for reviews. When available, they provide a link or button that can be clicked to display either the translated or the original version of the review.

A customer reported that we are not currently scraping the translated `snippet` in reviews when it is available.

I believe we implemented a solution related to this in https://github.com/serpapi/SerpApi/pull/3913 and https://github.com/serpapi/SerpApi/pull/3948 previously, in response to #923. However, something may have changed on Google's side since then.

<img width="1464" alt="Screenshot 2023-10-30 at 12 54 56 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/29e8d683-0e01-4f40-84d9-8886d1aa8438">

<img width="1468" alt="Screenshot 2023-10-30 at 12 53 59 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/d253bf98-a014-4792-ac05-6c100838bfd0">

<img width="1469" alt="Screenshot 2023-10-30 at 12 53 27 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/16c7aad4-337a-47a1-add6-a1ab05a6c056">

[Google 1](https://www.google.com/maps/place/Space+Needle/@47.6189266,-122.3393975,15.07z/data=!4m17!1m8!3m7!1s0x5490102c93e83355:0x102565466944d59a!2sSeattle,+Washington!3b1!8m2!3d47.6061389!4d-122.3328481!16zL20vMGQ5anI!3m7!1s0x5490151f4ed5b7f9:0xdb2ba8689ed0920d!8m2!3d47.6205063!4d-122.3492774!9m1!1b1!16zL20vMDFrN3Y3?hl=es&entry=ttu) | [Google 2](https://www.google.com/maps/place/El+Gran+Tlapalero/@19.4245881,-99.1333369,15.48z/data=!4m15!1m8!3m7!1s0x85ce0026db097507:0x54061076265ee841!2sMexico+City,+CDMX,+Mexico!3b1!8m2!3d19.4326077!4d-99.133208!16zL20vMDRzcWo!3m5!1s0x85d1fecc837ab5cb:0x23cf374867f8ef0!8m2!3d19.4311996!4d-99.1293493!16s%2Fg%2F1tzgpkjy?entry=ttu) | [Playground](https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x85d1fecc837ab5cb%3A0x23cf374867f8ef0&hl=en) | [Inspector 1](https://serpapi.com/searches/653ff072d5b1c5c73ce9f14e/inspect) |[ Inspector 2](https://serpapi.com/searches/65400afffe41d0b2c44f565b/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053046?view=List)

**Comment by natanavra** [comment]
Any updates?

**Comment by schaferyan** [comment]
@natanavra this is still a work in progress and unfortunately, we don't have an ETA. We will close this issue when there is a fix. You are welcome to email us at **support@serpapi.com** if you would like us to reach out to you when the fix is implemented. Thank you for your patience in the meantime.

**Comment by zyc9012** [comment]
@natanavra It's fixed.
