### ISSUE TITLE
[Google Search API Mobile] AMP News not Being Parsed and Returned

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#119]
AMP News results from the Google search does not parse the AMP links.

[The Playground](https://serpapi.com/playground?q=Novak+Djokovic&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile) | [The Inspect](https://serpapi.com/searches/626165a6c640d268a500b362/inspect)

<img width="735" alt="ampnews" src="https://user-images.githubusercontent.com/64849049/165512241-41ee6048-d773-40cb-a90f-50e259dda2b2.PNG">

I believe those are not AMP news anymore and there is nothing to scrape but user insists that those are AMP redirects? 

Initial user report:

> 
> AMP URLs are no longer recognized in Top Stories, it seems google changed some syntax
> For example 
> https://serpapi.com/searches/626165a6c640d268a500b362/inspect
> link 1 "Yahoo" in top stories, the url is "https://www.yahoo.com/amphtml/entertainment/novak-djokovic-calls-wimbledon-ban-130817359.html", which is AMP url 
> while link 4 "Reuters" is not
> https://www.reuters.com/lifestyle/sports/djokovic-slams-crazy-wimbledon-ban-russian-belarusian-players-2022-04-21/ 
> BTW, it was working fine till 4/13-14
> https://serpapi.com/searches/6260d575d5a5318d26923146/inspect

My response:

> Hi JS,
> This is not a bug. Reuters, Teleghraph and [Atptour.com](http://atptour.com/) are not publishing their content in AMP form anymore. Web is gradually getting away from amp due to controversies.
> You can check this from the raw html:
> https://serpapi.com/searches/10c6c1f5add54b12/626165a6c640d268a500b362.html
> I hope this helps.

User's findings:

> notice how the AMP div is 
> <div class="amp_re E7YbUb" data-hveid="CBIQAA" data-ved="2ahUKEwjO6LTKqqX3AhW-mHIEHf98B2YQz_ADKAB6BAgSEAA">
> <div class="xCURGd">
> <a class="WlydOe" data-amp-cur="" data-amp-title="[yahoo.com](http://yahoo.com/)" data-amp-vgi="" href="https://www.yahoo.com/amphtml/entertainment/novak-djokovic-calls-wimbledon-ban-130817359.html" 
> while the non-amp is 
> <div class="E7YbUb" data-hveid="CAsQAA" data-ved="2ahUKEwjO6LTKqqX3AhW-mHIEHf98B2YQz_ADKAB6BAgLEAA">
> <div class="xCURGd">
> <a class="WlydOe" href="https://www.reuters.com/lifestyle/sports/djokovic-slams-crazy-wimbledon-ban-russian-belarusian-players-2022-04-21/"

Another post from user:

> 
> Actually, they are AMP links but some sites redirect  
> for example:
> Yahoo (/amphtml/): https://www.yahoo.com/amphtml/entertainment/novak-djokovic-calls-wimbledon-ban-130817359.html 
> BR (/amp/)
> https://syndication.bleacherreport.com/amp/10033367-novak-djokovic-says-he-cannot-support-wimbledon-banning-russian-belarusian-players.amp.html
> Reuters (not amp)
> https://www.reuters.com/lifestyle/sports/djokovic-slams-crazy-wimbledon-ban-russian-belarusian-players-2022-04-21/
> CNN ([amp.cnn.com](http://amp.cnn.com/))
> https://amp.cnn.com/cnn/2022/04/21/tennis/djokovic-wimbledon-tennis-russia-ban-intl-spt/index.html

It is all [here](https://forum.serpapi.com/admin/feedback/bugs/p/urgent-amp-urls-in-top-stories-are-no-longer-recognized?boards=bugs).

**Comment by githubfan21** [comment]
any updates when will this be fixed?

**Comment by githubfan21** [comment]
Hi, any ETA here. this is a very old ticket from the old system

**Comment by ilyazub** [comment]
It seems that `amp_link` is extracted when it's available.

https://serpapi.com/playground?q=Novak+Djokovic&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile


![image](https://user-images.githubusercontent.com/282605/169398178-1a212b75-764a-448d-92cf-78be58f0f41e.png)

**Comment by githubfan21** [comment]
it seems it got fixed in few places but not all - about 10% improvement but the majority of links still not recognized at AMP
for example: https://serpapi.com/searches/6286e9dd37014c390cf68afd/inspect
the first 2 links from cnn are amp and have the unique identifier i mentioned before which is "amp_r" in the url which doesn't exist in non amp urls

AMP example
<a class="WlydOe amp_r" data-amp="https://amp.cnn.com/cnn/europe/live-news/russia-ukraine-war-news-05-18-22/index.html" data-amp-cur=""

**Comment by ilyazub** [comment]
> AMP example
> <a class="WlydOe amp_r" data-amp="https://amp.cnn.com/cnn/europe/live-news/russia-ukraine-war-news-05-18-22/index.html" data-amp-cur=""

Thank you :+1:

**Comment by githubfan21** [comment]
please let me know when it is fixed

**Comment by aciddjus** [comment]
Hey @githubfan21, this issue should be resolved now.
