### ISSUE TITLE
[Google News Result API] Wrong `showing_results_for` value in the response 

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1192]
A customer reported that a wrong `showing_results_for` value is returned in the response from the Google News Result API.

The part, highlighted in red in the screenshot below, is what Google is actually showing results for. It is different than the value from 
`showing_results_for` in the response:

<img width="903" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/32485db4-a3c0-4fb9-8335-97335eea83b0">

[Playground](https://serpapi.com/playground?q=%22%D7%9E%D7%A8%D7%95%D7%95%D7%90%D7%9F+%D7%A9%D7%9C%D7%95%D7%A3%22&location=Tel+Aviv+District%2C+Israel&gl=il&hl=iw&tbs=as_epq&tbm=nws) | [Inspect](https://serpapi.com/searches/6548f05b11c881b1ff594d2e/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053378?view=List)

**Comment by ezebrotsky** [comment]
Let me know guys if you need more clarification. Despite the language, the "showing_results_for" does not match with Google's "Showing results for"
