### ISSUE TITLE
[Raw HTML File] Broken link on the individual site

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1194]
When opening the raw_html_file link, some pages can't be accessed.

Try clicking the individual search result, will redirect to this URL: https://serpapi.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwip_J-7u7CCAxUKmGoFHWmvCegQFnoECBUQAQ&url=https%3A%2F%2Fwww.freecodecamp.org%2Fnews%2Fweb-scraping-in-javascript-with-puppeteer%2F&usg=AOvVaw0hZLa6ew4k-CauYO2GejV4&opi=89978449 instead of the actual URL (https://www.freecodecamp.org...)

Unfortunately, I can't replicate it from our Playground.

[Inspector](https://serpapi.com/searches/65496e4da4be10e86a873de0/inspect) || [Raw HTML File](https://serpapi.com/searches/4f3bb49eeef9d543/65496e4da4be10e86a873de0.html)

[Inspector](https://serpapi.com/searches/6549a79914b245ad92a41446/inspect) || [Raw HTML File](https://serpapi.com/searches/d062ce055bbdf231/6549a79914b245ad92a41446.html)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053417?view=List)

**Comment by aliayar** [comment]
In the original issue, user notes that opening a website in a new tab from html results isn't possible for some links.

While organic_results can be clicked and opened in new tab, shopping results on the page can't be opened or clicked.

**Comment by ilyazub** [comment]
We may fix that by adding the [`<base>` URL](https://html.spec.whatwg.org/multipage/semantics.html#the-base-element) to the HTML files we serve.

![image](https://github.com/serpapi/public-roadmap/assets/282605/4430ed78-ab28-4c34-8799-71ea07b1d6f0)

For the `shopping_results`, adding the [`<base>` URL](https://html.spec.whatwg.org/multipage/semantics.html#the-base-element) also helps.

![image](https://github.com/serpapi/public-roadmap/assets/282605/44e2493b-8ba6-4387-998a-11d38ee23786)
(ref: https://serpapi.com/searches/5fa06db3008b6dc3/654a7c3237b24a15a49b596c.html)

**Comment by hartator** [comment]
Oh, yes `<base>` seems like a clean idea. Wouldn't that mess up our `prettify` HTML work?
