### ISSUE TITLE
[Google Search API] Provide actual results number

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1196]
**Context:** Right now, we're providing the total_search_results based on what Google provides. But this number doesn't represent the actual returned results.

![Screenshot 2023-11-09 at 08 16 52](https://github.com/serpapi/SerpApi/assets/4522467/2088b5fe-2ae0-436a-907c-8df3f157437b)

VS the actual number
![Screenshot 2023-11-09 at 08 17 26](https://github.com/serpapi/SerpApi/assets/4522467/8b87ad4a-e2f6-41fb-aee2-5efbae8cf79c)

I think we can get the actual number by adding `&start=990` in the query. Since Google limited their results up to 1000, and got the number from the bottom part of the page (see in the screenshot above)

When using `991` or above
![Screenshot 2023-11-09 at 08 19 09](https://github.com/serpapi/SerpApi/assets/4522467/e7357a62-1e64-417c-93a7-039fb67c520b)

Notes: we have to add an extra scrape to this particular page, `&start=990`. So, if it's possible, maybe we could provide this as a "separate API".

[Example end of page](https://www.google.com/search?q=coffee+healthy&oq=coffee+healthy&start=990)  
[Intercom1](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053379?view=List) || [Intercom2](https://app.intercom.com/a/inbox/yzck75jr/inbox/search/conversation/102910000052936?query=allintitle&view=List)

**Comment by hilmanski** [comment]
What if this is a separate API? Cost 1 credit as well. 
/total-google-serp-results-api

**Comment by hartator** [comment]
> What if this is a separate API? Cost 1 credit as well, since some users need it.
> /total-google-serp-results-api

Yes, why not.

It might be overkill to have a full API just for `start=990` hack. Maybe a blog post? We already have Justin that topped HN: https://serpapi.com/blog/googles-millions-of-search-results-are-not-being-served-in-the-later-pages-search-results/

We can have "How to get accurate number of results on Google" or something like that.

**Comment by hilmanski** [comment]
It might be overkill, but not if some customers really need it. Let's see if there is more demand for this in the future.

**Comment by hilmanski** [comment]
This could be an alternative when Google is not displaying the total_results on a search.

Related issue: https://github.com/serpapi/public-roadmap/issues/1313
[Example case](https://app.intercom.com/a/inbox/yzck75jr/inbox/admin/6755014/conversation/102910000057716?view=List)
