### ISSUE TITLE
[Yandex Search API] "Реклама" removed from `displayed_link`

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1199]
Some Yandex search results include the word "Реклама" (Advertisement) to the right of the displayed link.

A customer reported we used to parse this word into the `displayed_link` field following the truncated URL, but we are no longer parsing it.

It is important to the customer's use case that we parse this. They haven't clarified whether this should be returned in `displayed_link` or in a separate field to best support their use case.

<img width="1122" alt="image" src="https://github.com/serpapi/public-roadmap/assets/30915304/abcc9928-d0a0-4a6d-9833-4c250516356e">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053588?view=List) | [Inspector](https://serpapi.com/searches/654e6be12ff421ef71ca6be4/inspect) | [Playground](https://serpapi.com/playground?engine=yandex&text=%D1%87%D1%82%D0%BE+%D0%BD%D1%83%D0%B6%D0%BD%D0%BE+%D0%B4%D0%BB%D1%8F+%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%B0+%D0%BA%D0%BE%D1%80%D0%BC%D0%B0+%D0%B4%D0%BB%D1%8F+%D0%BA%D0%BE%D1%88%D0%B5%D0%BA+%D0%B8+%D1%81%D0%BE%D0%B1%D0%B0%D0%BA&yandex_domain=yandex.ru&lang=ru&lr=213&p=0)

**Comment by btaunt** [comment]
Hey @schaferyan 

Any word on if the customer would prefer this rendered alongside the existing `displayed_link` or separated out into its own value? ie.

```
"displayed_link": "fdsp.turbo.site›КормовоеОборудование…Реклама",
```

or something like:

```
"displayed_link": "fdsp.turbo.site›КормовоеОборудование…",
"advertisement" : true,
```

**Comment by schaferyan** [comment]
@btaunt, no they didn't answer my question. I think you can use your best judgment. The second makes more sense to me personally, as it's not really part of the link.

**Comment by hilmanski** [comment]
The customer reported that this issue has reappeared.

[Front](https://app.frontapp.com/open/msg_2eqtxijg?key=GtSzDZD6OAWCXpOQuJQsylpGQIjYZ-vA)

**Comment by zyc9012** [comment]
We've released a fix for this. `advertisement` is properly scraped.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/f6300017-38d3-4ac8-ac30-8c2012ac6b6d)
