### ISSUE TITLE
[Google Search API Mobile] Returning Desktop View Instead of Mobile

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#120]
"device": "mobile" argument returns desktop view, just not in every other request.

[The Playground (may or may not bring mobile view](https://serpapi.com/playground?q=kansas+city+chiefs&location=United+States&gl=us&hl=en&device=mobile) | [The Inspect](https://serpapi.com/searches/62633de110d744ef45f95745/inspect)

<img width="741" alt="mobiledesktop" src="https://user-images.githubusercontent.com/64849049/165513911-6f431bf8-03be-4401-a7d5-0ebb3620879e.PNG">

**Comment by githubfan21** [comment]
this is happening frequently

**Comment by githubfan21** [comment]
![image](https://user-images.githubusercontent.com/15785331/166295922-b11fef9c-46cb-4c8b-b294-4c475808fbaa.png)

**Comment by ilyazub** [comment]
Also noticed it.

![image](https://user-images.githubusercontent.com/282605/166300509-e430db10-7be4-40c7-8aaa-ad3d37b89577.png)

**Comment by ilyazub** [comment]
> [The Inspect](https://serpapi.com/searches/62633de110d744ef45f95745/inspect)

There's a 500 HTTP Error when visiting this search. But a JSON and HTML endpoint works and there's no notice in Error Monitoring.

![image](https://user-images.githubusercontent.com/282605/166302401-a61ffb87-436d-4d6d-a598-b2075f58b2d3.png)

**Comment by ritu1337** [comment]
There was an issue with one of our external proxy providers. The mobile view is now correctly being returned.
