### ISSUE TITLE
[Documentation] Clarify the `zoom` requirement in the `ll` parameter in Google Maps API

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1204]
Currently, our documentation states that the `zoom` parameter is optional, while in fact it is required in the `ll` parameter. The `ll` parameter is optional itself, but if used, it needs to contain the `zoom` value as well.

Current state:
<img width="780" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/0ef61617-8943-4e95-bd64-cbd07fda916a">

Error when searching without the `zoom` part of the `ll` parameter:
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/ed5263d6-63bc-44a6-8809-bd168445f3a4">

[Google Maps `ll` parameter documentation](https://serpapi.com/google-maps-api#api-parameters-geographic-location)

**Comment by dsojevic** [comment]
The documentation has been updated to better clarify this:
[Google Maps ll parameter documentation](https://serpapi.com/google-maps-api#api-parameters-geographic-location)

The page now also includes an informational box at the top to give further detail on it:
[Note on Geographic Location and Search Queries](https://serpapi.com/google-maps-api#geographic-search-notes)
