### ISSUE TITLE
[Bing Knowledge Graph API] Inconsistencie in Structure of reviews_from_the_web Key

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#1206]
Bing Knowledge Graph API returns `reviews_from_the_web` array in different structure when there is 1 results and 3 results.

Example with one item:

![bing_knowledge2](https://github.com/serpapi/public-roadmap/assets/64849049/2e91d772-c6f7-4661-95d7-b1b5035ddf0b)

[Playground Link](https://serpapi.com/playground?engine=bing&q=REPICI%2C+ANTHONY%2C+19426) | [Inspect Link](https://serpapi.com/searches/65560ff30f9866310548bb44/inspect)

Example with three items:

![bing_knowledge1](https://github.com/serpapi/public-roadmap/assets/64849049/43143d29-93b8-4d2f-ba00-89084e8eacb6)

[Playground Link](https://serpapi.com/playground?engine=bing&q=Joint+Base+Andrews%2C+20762) | [Inspect Link](https://serpapi.com/searches/65561f18f636ffdeaa2e5e4b/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000050827?view=List)

**Comment by marm123** [comment]
It appears that there is still an issue with some Bing searches. I'm reopening this. Let me know if you think this should be in a separate thread @tanys123, and I'll open one.

<img width="1078" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/361abb2b-c489-4424-8639-eab3200f95ce">

[Playground](https://serpapi.com/playground?engine=bing&q=CC+GUNS+%26+AMMO+LLC%2C+35404) | [Inspect](https://serpapi.com/searches/6565db7596f5d77b77353f1b/inspect)

**Comment by marm123** [comment]
Changing the status to prioritized.
