### ISSUE TITLE
[Google Search API] Scrape Author Name, Date and Cites of Articles from Medical Sources

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#1208]
Google adds author name, date and cites of article returned in the Google search results. We don't scrape those elements currently.

![scholarly_cites](https://github.com/serpapi/public-roadmap/assets/64849049/c8f7f872-f184-4579-afb2-29ca0ae6d727)

[Playground](https://serpapi.com/playground?q=hearth+failure+mechanism+of+disease&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/655626fd9c84ace6e04af49c/inspect) | [Google](https://www.google.com/search?q=hearth+failure+mechanism+of+disease) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053829?view=List)

**Comment by marm123** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000054577?view=List)
