### ISSUE TITLE
[Google Search API Mobile] Carousel Content not Fully Parsed

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#121]
Carousel title and other details are not being picked up by our parser.

[The Playground](https://serpapi.com/playground?q=Kansas+City+Chiefs&location=United+States&gl=us&hl=en&device=mobile) | [The Inspect](https://serpapi.com/searches/62633940033e94649de87ce0/inspect)

<img width="954" alt="mobile_carousel" src="https://user-images.githubusercontent.com/64849049/165514402-4b68ef0e-783b-464f-9046-98c713a70f1f.png">

**Comment by githubfan21** [comment]
any updates?

**Comment by aciddjus** [comment]
This issue has been resolved.
