### ISSUE TITLE
[NEW API] Google Hotels Listing API

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#1210]
We currently scrape Google Hotels search results page but we don't scrape listing pages for each hotel. User who asked for this is interested in prices, especially "`Sponsored - Featured Options`" part of it.

![hotels_listings](https://github.com/serpapi/public-roadmap/assets/64849049/ed754e85-5e03-43b5-99bc-5083fa8a6803)

[Example Hotel Page](https://www.google.com/travel/search?q=hotels%20in%20bali&g2lb=2502548%2C2503771%2C2503781%2C4258168%2C4284970%2C4291517%2C4597339%2C4754388%2C4757164%2C4814050%2C4874190%2C4893075%2C4924070%2C4963888%2C4965990%2C4990494%2C72277293%2C72298667%2C72302247%2C72317059%2C72349959%2C72364011%2C72378185%2C72379816%2C72385362%2C72402232%2C72406588%2C72412680%2C72414906%2C72415677&hl=en-PL&gl=pl&cs=1&ssta=1&ts=CAESCgoCCAMKAggDEAAaTwovEi0yJTB4MmRkMTQxZDNlODEwMGZhMToweDI0OTEwZmIxNGIyNGU2OTA6BEJhbGkSHBIUCgcI5w8QCxgSEgcI5w8QCxgTGAEyBAgAEAAqBwoFOgNQTE4&qs=CAEyJkNoZ0l1dkRSaXRuY2tlUmxHZ3d2Wnk4eGNIUjZOblI1WkcwUUFROAZCCQk6eFSR5UbIZUIJCRTo2kxFD0E9QgkJifqxje5GuuZCCQnextr7fmLMOEgA&ap=KigKEgn95bfPVswhwBES6BP50MdcQBISCW_pqPW0qCDAERLoE_lT21xAMABoAboBCG92ZXJ2aWV3&ictx=1&sa=X)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053867?view=List)

**Comment by schaferyan** [comment]
A customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000047076?view=List)
