### ISSUE TITLE
[Google Search API] Not parsing `title` from "Top Stories" and "Also in the News" blocks

### ISSUE THREAD

**Issue by githubfan21** [serpapi/public-roadmap#1212]
titles are missing from "top stories", "also in the news" and sitelinks in carousels

https://serpapi.com/searches/65563370681ebe5a63355409/inspect
https://serpapi.com/searches/65579f07359e99e914f18f08/inspect
https://serpapi.com/searches/65579f07359e99e914f18f08/inspect

**top stories: https://serpapi.com/searches/65563370681ebe5a63355409/inspect**
![image](https://github.com/serpapi/public-roadmap/assets/15785331/6eb5d696-577e-4a54-866f-4364850b2ec0)
![image](https://github.com/serpapi/public-roadmap/assets/15785331/dad85bf1-76b7-48e1-9b1d-cd75a8316e15)

**also in news: https://serpapi.com/searches/65579f07359e99e914f18f08/inspect**
![image](https://github.com/serpapi/public-roadmap/assets/15785331/49b86d92-9a38-44fc-b3ea-b01956b8d0af)

**carousel site links : https://serpapi.com/searches/65579f07359e99e914f18f08/inspect**
![image](https://github.com/serpapi/public-roadmap/assets/15785331/c35b2048-9af4-4065-a7af-88e1aac4af3e)

**Comment by schaferyan** [comment]
Thank you again, @githubfan21. As with the other issues you opened, we will fix this as soon as possible. Thank you for your patience in the meantime.

I can verify that the titles are missing from the "Top Stories" and "Also in the News" blocks. 

I don't see anything wrong with the carousel `sitelinks` - they all seem to have a `title` in the example you shared. Let me know if I am misunderstanding something.

**Comment by githubfan21** [comment]
please provide an update on this
this is extremely urgent especially with black friday in 2 days
this needs to be fixed asap

**Comment by tanys123** [comment]
Thanks @githubfan21 for report the issue. The fix is on it's way, it is pending review. Thank you for your patience.

**Comment by hilmanski** [comment]
Hi @githubfan21,

Thank you for your report. Our engineers have implemented a fix. Now, all the titles are available:
- [Playground sample for top_stories section](https://serpapi.com/playground?q=Duane+Martin&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client)
- [Playground sample for also_in_the_news section](https://serpapi.com/playground?q=Luis+D%C3%ADaz&location=United+Kingdom&google_domain=google.co.uk&gl=uk&hl=en&device=mobile&google_domain=google.co.uk&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client)
