### ISSUE TITLE
[Google Search API] "Short Videos" not Parsed in `mobile` Results

### ISSUE THREAD

**Issue by githubfan21** [serpapi/public-roadmap#1213]
https://serpapi.com/searches/65579f07359e99e914f18f08/inspect

can't find it in json feed
![image](https://github.com/serpapi/public-roadmap/assets/15785331/ad1c9d7f-224d-4087-a312-d4dd905c319a)

**Comment by schaferyan** [comment]
Thank you @githubfan21 

Confirmed in [Playground](https://serpapi.com/playground?q=Chapell+Roan&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile)

**Comment by hilmanski** [comment]
Thank you @githubfan21, for your report and patience. The short_videos are now available in the response.
[Playground sample](https://serpapi.com/playground?q=luis+diaz&location=United+Kingdom&google_domain=google.co.uk&gl=uk&hl=en&device=mobile&google_domain=google.co.uk&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client)
