### ISSUE TITLE
[Google Search API] New "Perspectives" Block Parsed Incorrectly

### ISSUE THREAD

**Issue by githubfan21** [serpapi/public-roadmap#1214]
https://serpapi.com/playground?q=black+friday&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en
https://serpapi.com/playground?q=black+friday&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile

this is a new feature in it should have its block 
in desktop, it is bundled under top stories, and in mobile it is bundled under knowledge graph

![image](https://github.com/serpapi/public-roadmap/assets/15785331/c6cc15a3-eb51-41e0-9e9d-67cde92238a9)

**Comment by schaferyan** [comment]
Thank you @githubfan21, we will develop a fix for this as soon as possible. Thank you for your patience in the meantime!

**Comment by schaferyan** [comment]
[Inspect Mobile](https://serpapi.com/searches/6557b3e91071f4d291a2803d/inspect) | [Inspect Desktop](https://serpapi.com/searches/6557b2ffa74fe0ed4e7f64ad/inspect)

**Comment by githubfan21** [comment]
when something is complete, please update us on the resolution, was there a new serp feature added as prospective?
