### ISSUE TITLE
[Google Maps Reviews API] Translations not Rendered on Page and Returned in Response

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#1216]
When our users scrape Google Maps Reviews for a particular place, Google page doesn't render translations of the reviews. Due to that, SerpApi doesn't scrape and return them in our response.

**Google Maps Reviews**

![maps_trans](https://github.com/serpapi/public-roadmap/assets/64849049/d096bddf-d4cb-4811-b936-13e3dc0840f5)

**SerpApi Maps Reviews**

![maps_no_trans](https://github.com/serpapi/public-roadmap/assets/64849049/e73b295c-c95a-4deb-bb34-35eb6569cbd3)

[Playground](https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x1502cd20b2aeadd9%3A0xd660321348d04d80&hl=en&sort_by=newestFirst) | [Inspect](https://serpapi.com/searches/655b4ebd1d64ea183d92598d/inspect) | [Google](https://www.google.com/maps/place/TOYBER+-+Marketing+Well+Played/@31.9219965,34.9665247,17z/data=!4m8!3m7!1s0x1502cd20b2aeadd9:0xd660321348d04d80!8m2!3d31.921992!4d34.969105!9m1!1b1!16s%2Fg%2F11l4mnmmyb?entry=ttu) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053965?view=List)

**Comment by schaferyan** [comment]
Duplicate of #1184

**Comment by aliayar** [comment]
I am closing this since if it is duplicate of #1184.
