### ISSUE TITLE
[Google Search API] Some `mobile` Searches Return an HTML File With Scrolling Disabled

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1217]
A user reported they couldn't scroll in the HTML response for some of their searches.

When I retried the search in the Playground, it returned a normal response. I was able to open the `raw_html_file` and scroll to the bottom. 

However, I  opened the `raw_html_file` in their example and verified that scrolling seems to be disabled for some reason.

The JSON doesn't seem to be missing anything, and when zooming out, I was still able to see the whole page.

I'm not sure if it's related, but in the example where scrolling is disabled, the HTML includes a prompt from Google to rate the search at the bottom of the window.

<img width="536" alt="Screenshot 2023-11-20 at 9 51 48 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/2d633194-f2cb-492e-8081-0c2215cf6efa">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053975?view=List) | [Playground](https://serpapi.com/playground?q=sports+betting+apps&location=United+States&gl=us&hl=en&device=mobile) | [Search Inspector ](https://serpapi.com/searches/655b8b527f8361374de3d9a6/inspect)

**Comment by kennethreitz** [comment]
I miss you guys already. I've never been happier working anywhere in my life.
I'm sorry I was so trusting.

**Comment by kennethreitz** [comment]
shalom ~

**Comment by zyc9012** [comment]
Somehow the `<body>` class was added `TaoyYc` which prevents scrolling.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/509d3fd0-8f4a-4dc4-b6f2-b3eb913fef6f)
