### ISSUE TITLE
[Account] User got rate limited error 1015

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1219]
A user reported that they got a rate limited error 1015 message upon visiting their dashboard.

![imagen](https://github.com/serpapi/public-roadmap/assets/4522467/55281fe2-e7cc-4710-bcb1-fbb7b741d570)

I suspect that this is an error that the user sees after exceeding "hourly throughput limit" from their API.
Is this an expected behavior?

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054008?view=List)

**Comment by kennethreitz** [comment]
This is not a valid HTTP response, FYI.

**Comment by hilmanski** [comment]
Documentation on this rate-limit error from [Cloudflare](https://community.cloudflare.com/t/community-tip-fixing-error-1015-you-are-being-rate-limited/66398).

So far, there is only one report for this, so I assume it's not a mistake in our configuration.
