### ISSUE TITLE
[Yahoo Shopping API] Not Parsing and Returning any Product

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#122]
Yahoo Shopping API currently can not render HTML properly and parse the products.

[The Playground](https://serpapi.com/playground?engine=yahoo_shopping&p=coffee) | [The Inspect](https://serpapi.com/searches/62694d29c90e0aaa2072380e/inspect)

<img width="955" alt="yahoo_shopping_not_working" src="https://user-images.githubusercontent.com/64849049/165540037-b0148881-e18d-4e7d-a92e-b20131d3b27e.png">

**Comment by Alaa-abdulridha** [comment]
Looks like they changed something in the GraphQL.
