### ISSUE TITLE
[Google Search API] Some Top Stories fields are not extracted

### ISSUE THREAD

**Issue by aciddjus** [serpapi/public-roadmap#1224]
We are not extracting several fields from Top Stories on mobile.

<img width="1400" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/20846454-f517-41ca-92dd-0961f7ef401e">

------------------

[Inspect](https://serpapi.com/searches/655f29089d1586d7597a3f0f/inspect)
[Playground](https://serpapi.com/playground?q=black+friday+deals&location=New+York%2C+New+York%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com)
[Documentation](https://serpapi.com/top-stories)

**Comment by tanys123** [comment]
Fixed on https://github.com/serpapi/SerpApi/pull/4311
