### ISSUE TITLE
[Walmart Product API] Different price returned for the same `product_id`

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1225]
A customer reported that a different price is returned from our Walmart Product API for the same product_id:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/364abda4-1f70-4167-8e7b-d10c4d9b55c8)

`"seller_name": "Buildcom"`

![image](https://github.com/serpapi/public-roadmap/assets/144151895/fd32e6b5-2fb2-4c1e-b3fe-ce09fda4d6e5)

[Playground](https://serpapi.com/playground?engine=walmart_product&product_id=313510979) | [Inspect](https://serpapi.com/searches/655f4a2ee4a23ded2360f5e1/inspect)

![image](https://github.com/serpapi/public-roadmap/assets/144151895/655bdc92-8c27-42da-98a2-703cb6f5acae)

`"seller_name": "Walmart.com"`

![image](https://github.com/serpapi/public-roadmap/assets/144151895/2ab55b6e-16f4-4de4-a480-42a2a29bfeb6)

[Playground](https://serpapi.com/playground?engine=walmart_product&product_id=313510979&no_cache=true) | [Inspector](https://serpapi.com/searches/655f4ac1d04d6d0e6c4a4167/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054106?view=List)

**Comment by andypple83** [comment]
The results are controlled by Warlmart. The prices are different from sellers. SerpApi can be able to scrape the data correctly.

Let me know if you need more information.
