### ISSUE TITLE
[Google Search API] Scrape "How to solve your problem" Answer Box

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1227]
When you search for an algebraic equation or a more complex math problem in Google, Google provides a "How to solve your problem" answer box that is different than the Calculator Answer Box. It includes the steps to solve the problem, the solution, and links to different math providers. A user requested we scrape this information.

<img width="735" alt="Screenshot 2023-11-23 at 10 55 46 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/7d2f6e73-e8fa-4f9e-83ea-8c7c80a55dee">

[Google](https://www.google.com/search?q=x*5%3Dx%2B2&sca_esv=584907651&ei=zZ1fZYqVF5nD0PEPtsi10Aw&ved=0ahUKEwjKr_zs49qCAxWZITQIHTZkDcoQ4dUDCBE&uact=5&oq=x*5%3Dx%2B2&gs_lp=Egxnd3Mtd2l6LXNlcnAiB3gqNT14KzIyBBAAGB4yBBAAGB4yBBAAGB4yBBAAGB4yBBAAGB4yBBAAGB4yBBAAGB4yBBAAGB4yBBAAGB4yBBAAGB5Iv0FQAFifPHABeAGQAQCYAeABoAHFBqoBBTUuMC4yuAEDyAEA-AEBqAISwgIUEAAYgAQY4wQY6QQY6gIYtALYAQHCAhYQABgDGI8BGOUCGOoCGLQCGIwD2AECwgIWEC4YAxiPARjlAhjqAhi0AhiMA9gBAsICFBAuGIAEGIoFGJECGLEDGMcBGNEDwgIREAAYgAQYigUYkQIYsQMYgwHCAg4QLhiABBixAxiDARjlBMICCBAAGIAEGLEDwgIFEAAYgATCAgsQABiABBixAxiDAcICCxAuGIAEGLEDGIMBwgIjEC4YgAQYigUYkQIYsQMYxwEY0QMYlwUY3AQY3gQY4ATYAQPiAwQYACBBiAYBugYECAEYB7oGBggCEAEYCroGBggDEAEYFA&sclient=gws-wiz-serp) | [Playground](https://serpapi.com/playground?q=2x%5E2+2x%3D0&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&newPara=votes) |[ Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000048413?view=List)

**Comment by Wolbyworld** [comment]
This would be awesome to complement the LLM capabilities
