### ISSUE TITLE
[Google Search API] Missing `related_searches` section for some `mobile` searches

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1230]
A user reported the `people_also_search_for` section is not available.

Here is the screenshot of what's missing on the response
![CleanShot 2023-11-27 at 21 13 03](https://github.com/serpapi/public-roadmap/assets/4522467/213b7470-a9a5-4556-b4c3-65f036f0d8b4)

"People also search for" is displayed with this in Japanese 他の人はこちらも検索

**I'm not able to replicate this issue** using another query. The related searches are available for other query search upon testing on the playground. Sample:  [Playground](https://serpapi.com/playground?q=milk+tea&location=Japan&google_domain=google.co.jp&gl=jp&hl=ja&device=mobile&google_domain=google.co.jp&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client)

![CleanShot 2023-11-27 at 21 17 01](https://github.com/serpapi/public-roadmap/assets/4522467/8bd41d1c-8553-4cfb-a7ea-ec4c37fb5745)

[Playground with no result](https://serpapi.com/playground?q=%E3%83%AA%E3%82%AB%E3%83%AC%E3%83%B3%E3%83%88+%E7%A4%BE%E4%BC%9A%E4%BA%BA&location=Japan&google_domain=google.co.jp&gl=jp&hl=ja&device=mobile&google_domain=google.co.jp&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client) || [User's inspector](https://serpapi.com/searches/65626f221071f4caecd78015/inspect) || [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054243?view=List)

**Comment by kagermanov27** [comment]
@hilmanski I have renamed the issue since the inline people also search for blocks have been deprecated in favor of related_searches. More info at: https://serpapi.com/inline-people-also-search-for
