### ISSUE TITLE
[Google Local API] No results returned in the response sometimes

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1233]
A customer reported that sometimes Google Local API does not return results on mobile. I was able to reproduce it in the Playground:

<img width="1416" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/4a0075ce-a8b1-4e5c-b51d-97f1922e2363">

[Playground](https://serpapi.com/playground?engine=google_local&q=charter+bus+rental+Chicago%2C+Illinois&location=United+States&gl=us&hl=en&device=mobile) | [Inspector](https://serpapi.com/searches/6564d12049ecdbcb2927e52a/inspect)

Results were returned when I executed the same requests a few seconds later with a no_cache=true:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/4f2b18b0-3432-4c41-ae46-b714bf893947)

[Playground](https://serpapi.com/playground?engine=google_local&q=charter+bus+rental+Chicago%2C+Illinois&location=United+States&gl=us&hl=en&device=mobile&no_cache=true) | [Inspector](https://serpapi.com/searches/6564d1d3a4be1049205c77f0/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054313?view=List)

**Comment by martin-serpapi** [comment]
The issue seems to be happening when using `device=desktop` parameter as well.

![image](https://github.com/serpapi/public-roadmap/assets/144151895/c441de93-6793-4fe1-98e5-6736e4a72b34)

[Playground](https://serpapi.com/playground?engine=google_local&q=Boxen+Essen&location=Karlsruhe%2C+Baden-Wurttemberg%2C+Germany&google_domain=google.de&gl=de&hl=de&no_cache=true) | [Inspect](https://serpapi.com/searches/65aa7807d3aba2aab5959c23/inspect)
  
![image](https://github.com/serpapi/public-roadmap/assets/144151895/454caf9e-8a5b-460d-88fe-16d9b893f1eb)

[Playground](https://serpapi.com/playground?engine=google_local&q=Boxen+Essen&location=Karlsruhe%2C+Baden-Wurttemberg%2C+Germany&google_domain=google.de&gl=de&hl=de&no_cache=true) | [Inspect](https://serpapi.com/searches/65aa7816ad7fa9736fc57420/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000057401?view=List)

**Comment by aciddjus** [comment]
This has likely been fixed in https://github.com/serpapi/SerpApi/pull/4370
