### ISSUE TITLE
[Google Search API] Different results returned in `top_stories` on mobile

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1235]
A customer reported that his code no longer returns results. They're trying to access the `carousel` key in `top_stories`, which doesn't seem to be available in the response:

```python
top_stories = results.get("top_stories", {}).get("carousel", [])
```

The customer reported that this code was working normally until recently.

I've tested it in the Playground, and different types of results are returned sometimes for the same search parameters:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/2fb2430c-8c35-43e0-adc4-dd11d48683f4)

[Playground](https://serpapi.com/playground?q=samsung+s24+ultra&location=Chicago%2C+Illinois%2C+United+States&gl=us&hl=en&device=mobile) | [Inspect](https://serpapi.com/searches/6564e867a74fe030a3c53cbd/inspect)

![image](https://github.com/serpapi/public-roadmap/assets/144151895/2ecd3979-51c6-4bc8-81d9-258de38dc4dc)

[Playground](https://serpapi.com/playground?q=samsung+s24+ultra&location=Chicago%2C+Illinois%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true) | [Inspect](https://serpapi.com/searches/6564e9da5fc493a9f7b76c0e/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054308?view=List)

**Comment by kagermanov27** [comment]
I've mistakenly assigned myself to this issue.

**Comment by ilyazub** [comment]
> ```python
> top_stories = results.get("top_stories", {}).get("carousel", [])
> ```

SerpApi tries to extract the label dynamically, and `carousel` is the fallback top stories label. The workaround is to loop over the keys of the `top_stories`, instead of accessing a key directly (as @martin-serpapi suggested on Intercom).

I'm not sure if we can make it more convenient here.

**Comment by aciddjus** [comment]
This has likely been fixed in https://github.com/serpapi/SerpApi/pull/4370
