### ISSUE TITLE
[Google Search API] Support `ibp` Parameter

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1236]
A customer requested that we add support for the `ibp` parameter. This parameter changes the presentation of search results. The customer who reported this specifically would like to use `ibp=gwp%3B0,7` to display certain results like horizontal cards when the user agent is `mobile`.

The customer also noted that this parameter appears in some SerpApi searches in the URL associated with the `more_events` key. In these instances, `ibp=htl;events` is used to display only events.

<img width="1036" alt="Screenshot 2023-11-27 at 2 38 20 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/2a7b0d49-d5d6-43d5-8fed-f7851aa9b1a5">
<img width="1225" alt="Screenshot 2023-11-27 at 2 38 09 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/5d3180c3-5192-4b63-841d-82d4f18e63e0">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000043831?view=List) | [Google (with ibp=gwp%3B0,7)](https://www.google.com/search?hl=en&q=Climate+Pledge+Arena&ludocid=15998104634649095719&ibp=gwp%3B0,7#lpg=cid:CgIgAQ%3D%3D) | [Google (without ibp)](https://www.google.com/search?hl=en&q=Climate+Pledge+Arena&ludocid=15998104634649095719) | [Google (with ibp=htl;events)
](https://www.google.com/search?hl=en&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM&oq=events+in+seattle&ie=UTF-8&gl=us&q=events+in+seattle&ibp=htl;events&rciv=evn&sa=X&ved=2ahUKEwi177TDnOWCAxV1TTABHS_kAq0Q5bwDegQIbhAB#fpstate=tldetail&htidocid=L2F1dGhvcml0eS9ob3Jpem9uL2NsdXN0ZXJlZF9ldmVudC8yMDIzLTEyLTAxfDEzMTE2Mjk4Mjk2NTc2MzIzNTEz&htivrt=events&mid=/g/11ksrv54sx)

**Comment by kagermanov27** [comment]
The `ibp` parameter is now supported for Google Search API:

Before:
<img width="1457" alt="Pasted Graphic 9" src="https://github.com/serpapi/public-roadmap/assets/73674035/c6134076-7905-40ea-bdec-96d8b940e697">

After:
<img width="1457" alt="ibp" src="https://github.com/serpapi/public-roadmap/assets/73674035/67a5003c-175b-4ff1-8e47-fe75412a29df">
