### ISSUE TITLE
[Google Search Results] Incorrectly Parsed Local Result

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1238]
A customer reported a phone number parsed inside a `link` in organic_results.

The element appears to be an alternate form of local pack results,  however, we are currently parsing it as an organic result.

<img width="1341" alt="Screenshot 2023-11-27 at 3 02 14 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/5380eeb6-3ab6-4a31-9490-f2efc6d8f55d">

[Inspector ](https://serpapi.com/searches/6564d6f21d986e3f2ab0ab68/inspect)| [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054338?view=List) | [Playground](https://serpapi.com/playground?q=harrison+law+reviews&location=Oklahoma+City%2C+Oklahoma%2C+United+States&gl=us&hl=en&device=mobile&newPara=votes)

**Comment by andypple83** [comment]
I've tested the " Harrison Law" keyword with some places. SerpApi can scrape the correct mobile phone number right now. I've enhanced our system to give more accurate results.

![Screenshot 2024-06-14 at 15 50 55](https://github.com/serpapi/public-roadmap/assets/99160364/efba8dd2-3ee2-47db-934b-aa5713d3b8ad)


Let me know if you need more information.
Best
