### ISSUE TITLE
[Google Trends API] It returns a different result for the 'interest_over_time' data type when the 'geo' parameter is set

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1244]
A customer reported that we show different results with the Google Trends site for 'interest_over_time' data type and 'geo' parameter is set.

Google Trends API results on our playground for the word "crox" with location set to US
![CleanShot 2023-11-29 at 12 51 47@2x](https://github.com/serpapi/public-roadmap/assets/4522467/f793fbbf-68d8-41bc-93a2-5448099cc6ed)

Actual result from Google Trends
![CleanShot 2023-11-29 at 12 52 53@2x](https://github.com/serpapi/public-roadmap/assets/4522467/cc8e916f-0407-4858-8c1e-e02046e8e645)

- I'm not able to replicate this issue for other words
- I'm not able to replicate this issue for other countries

This could be related to:
- https://github.com/serpapi/public-roadmap/issues/300
- https://github.com/serpapi/public-roadmap/issues/887

[Playground without geo](https://serpapi.com/playground?engine=google_trends&q=crox&data_type=TIMESERIES) || [Inspector](https://serpapi.com/searches/6566c3139f55b3c1799d7874/inspect)
[Playground with geo](https://serpapi.com/playground?engine=google_trends&q=crox&geo=US&data_type=TIMESERIES&no_cache=true)  || [Inspector](https://serpapi.com/searches/6566c35c1988e53e1db515c8/inspect) || [Google Trends result](https://trends.google.com/trends/explore?geo=US&q=crox&hl=en) 

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054409?view=List)

**Comment by schaferyan** [comment]
Another customer reported this

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000065158?view=List)

**Comment by alexbarron** [comment]
@tanys123's fix appears to have resolved this issue. Confirmed with the original "crox" query. Closing this.

![image](https://github.com/serpapi/public-roadmap/assets/9811728/d07f32c1-5925-4af7-8977-34e92cd42beb)

![image](https://github.com/serpapi/public-roadmap/assets/9811728/86c6a0f5-6af0-422a-8e06-47cdaf9ffe1e)
