### ISSUE TITLE
[Google News API] Some Searches with `q` Return 500 Error

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1246]
A customer reported some searches with the new Google News API return a 500 error.

The API appears to work as expected if `q` is omitted. 

Strangely, it also appears to work consistently when certain values of `q` are supplied, while consistently returning the 500 error for other `q` values (even with `no_cache=true`.

For example, it consistently works when searching for "Canada", but consistently fails when searching for "coffee" or "journalist". 

It also returned the error once when searching for "space", but returned the expected results the 5-10 other times I tried that search.

<img width="1431" alt="Screenshot 2023-11-29 at 11 14 31 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/39d95cee-3912-4e70-8a5c-3f8cedffbfa0">
<img width="1430" alt="Screenshot 2023-11-29 at 11 13 49 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/79a55cf7-4ccd-40c8-8776-dafce2baa412">
<img width="1431" alt="Screenshot 2023-11-29 at 11 13 30 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/e73b47cb-25ed-4a2e-bc5d-ef68afd046eb">
<img width="1431" alt="Screenshot 2023-11-29 at 11 13 11 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/76d6949f-4d9e-44dd-9809-260338ae6f15">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054453?view=List) | [Playground](https://serpapi.com/playground?engine=google_news&q=journalist&gl=us&no_cache=true) | [Search Inspector 1 ](https://serpapi.com/searches/65678e22f636ffa6f3feed1e/inspect)| [Search Inspector 2 ](https://serpapi.com/searches/65678e482fe302ed9aedfeb7/inspect)| [Search Inspector 3](https://serpapi.com/searches/65678e6010d744107fe0c280/inspect) | [Search Inspector 4  ](https://serpapi.com/searches/65678d60ad7fa9dcb7ae28d3/inspect)

**Comment by martin-serpapi** [comment]
Another customer reported this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054481?view=List)
