### ISSUE TITLE
[New API] Add product_id in Google Lens shopping results item

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1248]
A user asked if he could get a `product_id` from Google Lens `knowledge_graph > shopping_results` item.
The end goal is to determine the width, length, height, and weight of a product, which is usually available at Google Product API.

![CleanShot 2023-12-01 at 09 15 35@2x](https://github.com/serpapi/public-roadmap/assets/4522467/f750168c-0b1b-4508-b527-01cf03730eeb)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054538?view=List) || [Google Lens Playground with shopping results](https://serpapi.com/playground?engine=google_lens&url=https%3A%2F%2Fi.ibb.co%2FpPD59gh%2FClean-Shot-2023-12-01-at-08-00-39.png)

**Comment by tanys123** [comment]
It directly points to the source instead of the Google Product page, so we can't extract it. Google Product ID isn't present in the HTML either. Feel free to reopen when it is possible.
