### ISSUE TITLE
[Documentation] Pagination links in JavaScript integration documentation not working

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1254]
The Pagination links in the JavaScript integration documentation are returning HTTP 404:

https://serpapi.com/integrations/javascript

![image](https://github.com/serpapi/public-roadmap/assets/144151895/99cc99fb-2a83-4d08-96a6-4a65a23d0a78)

**Comment by ilyazub** [comment]
Here are the broken links:

![image](https://github.com/serpapi/public-roadmap/assets/282605/38782bff-ebef-4e62-919a-bd150013ff8b)
(ref: https://serpapi.com/integrations/javascript)
