### ISSUE TITLE
[Google Jobs Listing API] Results is not fully returned

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1259]
A user reported that they got an "empty result" upon performing a request to Google Jobs Listing API: 

![image](https://github.com/serpapi/public-roadmap/assets/4522467/8d28c227-c14f-4ee1-b053-37044e49af67)

It somehow returns a result, but only partial, as if the search still needs to be finished.

User's initial Google Jobs API call:
[Inspector](https://serpapi.com/searches/656d3cccf636ff14f3d82afd/inspect)  

User's Google Jobs Listing API call:
[Inspector](https://serpapi.com/searches/656d430be4a23d156c73a1e5/inspect)

Upon trying to test this on our playground, it returned more results (I can't recreate the issue):
[My Playground with same id](https://serpapi.com/playground?engine=google_jobs_listing&q=eyJqb2JfdGl0bGUiOiJMZWFkIFByb2R1Y3QgTWFuYWdlciwgQUkgUHJvZHVjdCBSXHUwMDI2RCIsImh0aWRvY2lkIjoieTV3eGFvMnI0MDdOS09WV0FBQUFBQT09IiwiZ2wiOiJ1cyIsImZjIjoiRXFJQ0N1SUJRVXhQYm5CWlZsOTVSR3M0WjJGcFNFcE1WVkpLTUU5T05XZHRZbDh0TVhCelpWOUpTVzUzWDBNNVkxUlpTREZCWkZseU5tRjRjMUZIWkhaMFNsSlJia3d5VkZCcFUyc3pOekZCTlZOSWJsOXZWRXhaTUUxNlQweERNa1ZOYldWRFVHcHZlbFU0WTIxeVJXNTRaVkV3ZVdKWk4zcE1URzluTVVSVWNUQnNXVVJrWDNCNVMwSktMVUZWWldJeFZERkRla3B1YzBSWWJGazFlRE5YT0hvNFNtZG9OSFl0WTJwcloybzJTazFCZDFoaU5FRk1jSFJNY0c1U1RuZDZiemxrWnpsM1ZrUlVTbUkzUkU5WlgwNHhSMnRLUVU5MWJscHlPRTFNZGt0emRHZFNRUklYZWtSNGRGcGtSMEZKTFRKd2EyUlZVRFpQYVRSblFXOGFJa0ZLZDJzdE9HTkRVRW94WWtGdU5VaE9NekpvVkZKYWMxOXljMkp1YlVsck1FRSIsImZjdiI6IjMiLCJmY19pZCI6ImZjXzEiLCJhcHBseV9saW5rIjp7InRpdGxlIjoiLm5GZzJlYntmb250LXdlaWdodDo1MDB9LkJpNkRkY3tmb250LXdlaWdodDo1MDB9QXBwbHkgb24gTkJBIENhcmVlcnMiLCJsaW5rIjoiaHR0cHM6Ly9uYmFjYXJlZXJzLm5iYS5jb20vam9iL05ldy1Zb3JrLUxlYWQtUHJvZHVjdC1NYW5hZ2VyJTJDLUFJLVByb2R1Y3QtUlx1MDAyNkQtTlktMTAwMjIvOTczMzk3MjAxLz91dG1fY2FtcGFpZ249Z29vZ2xlX2pvYnNfYXBwbHlcdTAwMjZ1dG1fc291cmNlPWdvb2dsZV9qb2JzX2FwcGx5XHUwMDI2dXRtX21lZGl1bT1vcmdhbmljIn19)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054689?view=List)

**Comment by schaferyan** [comment]
Another user with this issue:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055329?view=List)

**Comment by schaferyan** [comment]
I'm bumping this up to `urgent`, as all Google Job Listing API queries now seem to have this result, including the Playground example @hilmanski shared above that was working a few weeks ago.

**Comment by hilmanski** [comment]
Another customer reported this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055347?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055359?view=List)

**Comment by AbhyCGApp** [comment]
Thanks for prioritizing this. It's affecting our app in production and users are not able to apply for jobs.

**Comment by kagermanov27** [comment]
This may be relevant to https://github.com/serpapi/public-roadmap/issues/1294 or https://github.com/serpapi/public-roadmap/issues/1294#issuecomment-1858246348. I couldn't reproduce any effect of these problems on this problem though.

**Comment by AbhyCGApp** [comment]
@kagermanov27 try with this freshly received job id related to an amazon job posting scrapped via LinkedIn. It doesn't return any apply link. This is happening across all google listings. `eyJ1dWxlIjoidytDQUlRSUNJT1ZXNXBkR1ZrSUV0cGJtZGtiMjAiLCJobCI6ImVuIiwiZmMiOiJFc3dDQ293Q1FVeFBibkJaVlVkVVVEbGpVVVEwYVhSV2IxODVYMlJJVERRNVFtRmtVa3hWVDI5RWJTMVlkRXRKVFVGVmEyaGliRmwyWlRGeFVUa3dRVTl3U0VaT1pWOVpXR2N0UlVKTGNWQlBWREJZUjFWT1JsOXlZMU4yVVdodFZ6SmljVjk0UVhKek9HaEVNMVZSZW1neVVqaDJUV1JVWW5NdFNVNTJOM1pZVW14NU5DMXZkVjlQVEROTVpraHdWVXhJWW5KV1FsWjJPRUZ3YlVFNGVHZE5MVU40TUZaa09WUkhNVWhZWjFObWJHZExXV3N5YlhCeFdITXdhRGxCUmpCZmFsZ3RjMUJaYWtveVkwMWxhRUpYYkZSblExRkVSVU0zYzJwalZrTk5aVTVSVlVOMVIzcDFiV1l3ZFc1c1pFeHpkMWhuU1dKUkxYUnJhekJQY1dGVWVsRnlVekI1T1VZMVRqSmFPRGRMZFJJWE5HRmtPRnBrVURoSk9DMW5OVTV2VUdwSlIyd3dRVkVhSWtGS2Qyc3RPR1pMT1RSak5VOXpXWFphTVZsMFltOXBaM2N5UkhVd2JrTmFYM2MiLCJmY3YiOiIzIiwiZmNfaWQiOiJmY18zIiwiYXBwbHlfbGluayI6eyJ0aXRsZSI6IkFwcGx5IG9uIExpbmtlZEluIiwibGluayI6Imh0dHBzOi8vdWsubGlua2VkaW4uY29tL2pvYnMvdmlldy9wcmluY2lwYWwtYXBwbGllZC1zY2llbnRpc3QtcGVyc29uYWxpemF0aW9uLXRlYW0tYXQtYW1hem9uLTM3ODExNzYxNDk/dXRtX2NhbXBhaWduPWdvb2dsZV9qb2JzX2FwcGx5XHUwMDI2dXRtX3NvdXJjZT1nb29nbGVfam9ic19hcHBseVx1MDAyNnV0bV9tZWRpdW09b3JnYW5pYyJ9fQ==`

**Comment by hilmanski** [comment]
Another customer reported this

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055451?view=List)

**Comment by hilmanski** [comment]
A potential customer asking about Google Jobs listing API. We need to reach out, once we have a fix

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055366?view=List)

**Comment by schaferyan** [comment]
Another customer reporting this issue:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054396?view=List)

**Comment by schaferyan** [comment]
Another user with this issue. Also note thread #1303 is a duplicate opened by a customer, and commented on by a second customer.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055498?view=List)

**Comment by schaferyan** [comment]
A user also reported this in a commentr on #1295

**Comment by schaferyan** [comment]
Due to the constant inflow of reports, I'm bumping this up another level to `urgent`.

**Comment by schaferyan** [comment]
Two more customers reported this:

[Intercom 1](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053239?view=List)

[Intercom 2](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055571?view=List)

**Comment by hilmanski** [comment]
Another customer reported this

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055582?view=List)

**Comment by alexbarron** [comment]
I'm afraid we need to reopen this as the same issue has come up.

The linked customer below reported not being able to get `apply_options` like they used to. I tried with the `job_id` they provided and also did not get `apply_options`. I subsequently tried some of my own queries and could not get `apply_options` for any of them.

[Google Job Listing Playground](https://serpapi.com/playground?engine=google_jobs_listing&q=eyJqb2JfdGl0bGUiOiJCYXJpc3RhIC0gU3RhcmJ1Y2tzIiwiaHRpZG9jaWQiOiJCQnVYY25UbWZIa1VSN1lPQUFBQUFBPT0iLCJ1dWxlIjoidytDQUlRSUNJYVFYVnpkR2x1TEZSbGVHRnpMRlZ1YVhSbFpDQlRkR0YwWlhNIiwiZ2wiOiJ1cyIsImhsIjoiZW4iLCJmYyI6IkVxSUNDdUlCUVVwSE9VcHJUV2hzVlVGbE0wMW1RbVZxZEZKRFRFcFNibVJVTVdad2VsWnVNMmhaZVVrekxYUmpValZ3VDFKUmVFTnFXakpYVUhOc1dFWnZSMHR0ZFhJeGRETlRjbFpNWWpnM1dFTTBOemhuVUhvelRuWXpiMjF4TkU1M1p6VnNWM0Z3VDJ3elZYSmZhWHBVWDJoME0yUkxjbGx4WmxFM2VsYzJlV3h4ZW1oVllUTkRYMHRUT1dKUFZHSlNia2c1TkVOblZFUTJiM1ZtY214MmNXNXlOWGR2U0hwUk5sSkRaVVJXVUV0NldVTlVNbWRuUlhjelNXRnVjMVU0WW1FMU1uQkJlakJFU1VwSFNqVjZTRFV5ZVdKa2FtVnZSM1ZZTkROV2FIbFJhV05CUVJJWFdUbExSRnB2U0ZKSFMwODJhMUJKVUhaa1Iyb3RRVFFhSWtGR1dISkZZMjh0ZDBWTlZHVXlRbmt6WTJKWWFYSTVOalk1Um5wSmNuRmhhMmMiLCJmY3YiOiIzIiwiZmNfaWQiOiJmY18xIiwiYXBwbHlfbGluayI6eyJ0aXRsZSI6Ii5uRmcyZWJ7Zm9udC13ZWlnaHQ6NTAwfS5CaTZEZGN7Zm9udC13ZWlnaHQ6NTAwfUFwcGx5IG9uIFdoaXRlIExvZGdpbmcgSm9icyIsImxpbmsiOiJodHRwczovL2NhcmVlcnMud2hpdGVsb2RnaW5nLmNvbS9iYXJpc3RhLXN0YXJidWNrcy9qb2IvMjc5OTY3MDk%2FdXRtX2NhbXBhaWduPWdvb2dsZV9qb2JzX2FwcGx5XHUwMDI2dXRtX3NvdXJjZT1nb29nbGVfam9ic19hcHBseVx1MDAyNnV0bV9tZWRpdW09b3JnYW5pYyJ9fQ%3D%3D&no_cache=true)

![image](https://github.com/serpapi/public-roadmap/assets/9811728/a4d81f0c-925e-41df-b572-a6362769034c)

Sample `job_id` above was pulled from this query: [Google Jobs Playground](https://serpapi.com/playground?engine=google_jobs&q=Barista&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068313?view=List)

**Comment by NateSkiles** [comment]
Two other customers reported this.

[Front](https://app.frontapp.com/open/cnv_1bl3qf18?key=r9HNOu8XaHT1DLk1IuajPh6Uwv64mMXE)
[Front](https://app.frontapp.com/open/cnv_1bl3pobg?key=5gRhnhhdZf1_-7WCUqvY_fn4tFRS27zy)

**Comment by nadeemsupport** [comment]
I am encountering same issue with the SERP job listing endpoint. When I request job listings, the apply options are not being returned. Can you please investigate whether there is an issue with the SERP endpoint?

**Comment by schaferyan** [comment]
Another customer affected by this issue:

[Front](https://app.frontapp.com/open/msg_2eq9kkgs?key=L_A3OPc7wAo23nRh6LrtSCUZcZGN2vE8)

**Comment by hilmanski** [comment]
Another customer reported this.

[Front](https://app.frontapp.com/open/msg_2equxuho?key=Q5HOR7PKByg3GjrG2xy_TF7e3ilSLZD8)

**Comment by marm123** [comment]
Another customer reported it:

[Front](https://app.frontapp.com/open/cnv_1bljkz8c)

**Comment by aciddjus** [comment]
Thanks @Freaky 👍 
Please update the status of the issue to `completed`.

**Comment by Freaky** [comment]
A fix for this has been deployed:

`apply_options`, `ratings`, `salaries_comparison`: [[Playground](https://serpapi.com/playground?engine=google_jobs_listing&q=eyJqb2JfdGl0bGUiOiJNYW5hZ2VtZW50IGNvbnN1bHRhbnQiLCJodGlkb2NpZCI6InNnNHpvd2J1MlpteFhFaTBBQUFBQUE9PSIsImZjIjoiRXFJQ0N1SUJRVXBIT1VwclRXTTRjbmhIV1VzNFFtMVdSRVZXTUhsTWNHNUVjRmhqT0UxNFJVUnpNMjV6Y0ZnMlFtZHJjbWQ2UlRkdFUxQkZZakE1VVV0MVJrcDVhWFl0UmpWb2VXazFRM3B6TkcxQ2NVcDFVa3cyUW1oRVFVUlpiVmcyWWtaNWNqVktkMmhxY2pCQ1ZWSTBRMEpZU1ROdGVtZG5URGh1VTJwQ1pqWjRZM1JwY1hsQlQydzNTR1pzUTNCTVkyWjBRbHBUYWtoNFRreHViRGd6YVdKb2NEQlZlVFk1ZFY5YWFsOUVaMWhXVm14TE9WQXljVWRsU1RORWJrMDVYelpIWDFObVFscEhVVEpMVmtjeGIwRm5aVGQ2U2xCSWFrOHlZVkpIYVU1UE9HSlRVUklYUVVwRFIxcDBiVWxEVG1ZdGQySnJVRzFPYVVNMFFWVWFJa0ZHV0hKRlkyOXlhMnhUUlhFNWMwbElNVVJRWVMxZllXZElSRzFMVG5CM01rRSIsImZjdiI6IjMiLCJmY19pZCI6ImZjXzQiLCJhcHBseV9saW5rIjp7InRpdGxlIjoiQXBwbHkgb24gVGFsZW50LmNvbSIsImxpbmsiOiJodHRwczovL3d3dy50YWxlbnQuY29tL3ZpZXc%2FaWQ9N2EzNjZmYjExZDk3XHUwMDI2dXRtX2NhbXBhaWduPWdvb2dsZV9qb2JzX2FwcGx5XHUwMDI2dXRtX3NvdXJjZT1nb29nbGVfam9ic19hcHBseVx1MDAyNnV0bV9tZWRpdW09b3JnYW5pYyJ9fQ%3D%3D)]

![1259-1](https://github.com/serpapi/public-roadmap/assets/58758/fcf8b458-e901-4f32-9f99-9b185086e6f9)

`salaries`: [[Playground](https://serpapi.com/playground?engine=google_jobs_listing&q=eyJqb2JfdGl0bGUiOiJQcm9qZWN0IE1hbmFnZW1lbnQgQ29uc3VsdGFudCIsImh0aWRvY2lkIjoicWNrR0VjbVBSdEpvS0Z2ckFBQUFBQT09IiwiZmMiOiJFcmNDQ3ZjQlFVcEhPVXByVG5wblVtOVpaMmhmZFcxdlkycFRhRFphVldkcVRIaE1WVFUwVDBkbWREUjZWR1IyVHpSNWRtOXJPVU0zY2tkYU1sVTNUVzV3TVdabWNHNVJWRkZwY2pSVVJYRjBUR2xaUmpCT01VazBVVVZ4YUhWVFpHeEVTamhmVVVoMk9EVXRTVXBUUlVOU1NqZG1Zemw2V0RaZlREQlNkelJPYUhkYVpGRjJaMGhqTFZoYWQwRk5lVFZOTFV0dVFYTjFMVUUwU2xGYWVGbzBNVGxNYlV4S2FGSm5NbTR5VG1saVRIUjJOMGRGYVVaSVUwSjRhRmhIUmt0ZlZqVlBRVVZwVGtSSGJDMUViRXQxWDJGVVNWVnZiR2hpZWtjNVJFNWFjRVZ0TUVnMFVsQXpia0ZDVUVsVFUzQnNhVFkyZVMxUFRFSmZZeElYUVVwRFIxcDBiVWxEVG1ZdGQySnJVRzFPYVVNMFFWVWFJa0ZHV0hKRlkzRnJaVEpwWTNoU09HWjVlV3RSYjBaUWNDMUdURWRmY0RjdGVIYyIsImZjdiI6IjMiLCJmY19pZCI6ImZjXzEiLCJhcHBseV9saW5rIjp7InRpdGxlIjoiLm5GZzJlYntmb250LXdlaWdodDo1MDB9LkJpNkRkY3tmb250LXdlaWdodDo1MDB9QXBwbHkgb24gTGlua2VkSW4iLCJsaW5rIjoiaHR0cHM6Ly93d3cubGlua2VkaW4uY29tL2pvYnMvdmlldy9wcm9qZWN0LW1hbmFnZW1lbnQtY29uc3VsdGFudC1hdC1hdWdtZW50LWpvYnMtMzk2NTk0MjI5NT91dG1fY2FtcGFpZ249Z29vZ2xlX2pvYnNfYXBwbHlcdTAwMjZ1dG1fc291cmNlPWdvb2dsZV9qb2JzX2FwcGx5XHUwMDI2dXRtX21lZGl1bT1vcmdhbmljIn19)]

![1259-2](https://github.com/serpapi/public-roadmap/assets/58758/de72d236-0a57-482f-9cba-0ff1c07569dc)

I haven't been able to find any responses with `similar_jobs` sections, and browsing Google Jobs I suspect they've been removed.
