### ISSUE TITLE
[Google Search API] Images are parsed as `top_stories` for some searches on mobile

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1260]
One of the customers reported that some searches on mobile return incorrect responses for `top_stories`. It looks like the Images are parsed in this block, while they should be in a separate endpoint. Those are also redirect links instead of direct image links. Unfortunately, I wasn't able to recreate this issue.

<img width="1112" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/9e20046a-907c-4fac-9e87-c641bbbe62bd">

[Playground](https://serpapi.com/playground?q=iphone+13&location=Chicago%2C+Illinois%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true) | [Inspect](https://serpapi.com/searches/656d96371071f40c8422c038/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000054308?view=List)

**Comment by kagermanov27** [comment]
Just a note here that it is unrelated to https://github.com/serpapi/public-roadmap/issues/1247. The changes in https://github.com/serpapi/SerpApi/pull/4337 (solution for it) are irrelevant to the case.

**Comment by marm123** [comment]
Thanks for the clarification @kagermanov27. I'll remove the comment to not confuse anyone then 👍

**Comment by tanys123** [comment]
I think we probably should pause on fixing this light version of Google layout, it seems to have deep issue we need to fix instead of the parser.

**Comment by kagermanov27** [comment]
>I think we probably should pause on fixing this light version of Google layout, it seems to have deeper issue we need to fix instead of the parser.

@tanys123 For sure, let's try to aim for that while serving the customer wherever needed by fixing parsers until the deeper issue is resolved as @aciddjus mentioned in https://github.com/serpapi/SerpApi/pull/4338#issuecomment-1835859973
