### ISSUE TITLE
[Google Search API] Exclude search extra info from organic results

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#1263]
Google returns new layout for search information. We scraped it as first organic result.

![Screenshot 2023-12-05 at 17 27 21](https://github.com/serpapi/public-roadmap/assets/99160364/d39ae874-df57-46b9-ace4-5503cbf26fa4)

[Playground](https://serpapi.com/playground?q=Coffeeee+wiki&location=United+States&gl=us&hl=en&tbs=as_epq&tbm=nws&device=tablet&no_cache=true&google_domain=google.com&newPara=votes+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client) | [Inspect](https://serpapi.com/searches/656ef98a2c0844b149c190b2/inspect)

**Comment by aciddjus** [comment]
Related to: https://github.com/serpapi/SerpApi/pull/4338#issuecomment-1835859973

**Comment by ilyazub** [comment]
Let's stop using this outdated iPad user-agent:

![image](https://github.com/serpapi/public-roadmap/assets/282605/1e1daae7-fe49-470f-8ede-c84f593c0610)
(ref: https://serpapi.com/searches/656ef98a2c0844b149c190b2/inspect)

An expected SERP layout for the modern iPad user-agent:

![image](https://github.com/serpapi/public-roadmap/assets/282605/0b973c76-e493-41e3-8a13-915ec14b641c)

**Comment by aciddjus** [comment]
@ilyazub I don't think the issue is with outdated user-agents on our side. I was able to reproduce the light page with new user-agents as well.
