### ISSUE TITLE
[Google Search API] `type` not Parsed for Some Knowledge Graphs

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1266]
A customer reported the `type` field is missing from the `knowledge_graph` in the JSON response for some searches. They shared a Playground example:

<img width="1424" alt="Screenshot 2023-12-05 at 12 29 07 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/75a3d70f-e1dc-4a1f-be1f-9cb861f712c5">

[Inspector](https://serpapi.com/searches) | [Playground](https://serpapi.com/playground?q=taylor+swift&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054806?view=List)

**Comment by hilmanski** [comment]
I believe this one is solved as well.

https://serpapi.com/playground?q=taylor+swift&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=site+votes+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client
