### ISSUE TITLE
[Accounts] Warning Email Sent to Wrong User

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#127]
A newly registered user has received the following warning email:

> Hi, Your application has just tried to submit a search on SerpApi. However you have run out of searches for the month.
> 
> You have 0 searches done this month
> 
> You have 100 searches per month
> 
> You can upgrade to a bigger plan with more searches.
> 
> [Upgrade plan](https://serpapi.com/change-plan)
> 
> Have a great day!
> SerpApi Team

User shouldn't receive this email as they haven't completed even the activation. I suspect queue is the culprit.

I won't add the email address of the person here due to privacy reasons.

**Comment by hartator** [comment]
@aliayar Can you share the ID of the user with the issue? Thank you. 👍

**Comment by aliayar** [comment]
ID of the user is  626a4fb649ecdb74e5c52774.
