### ISSUE TITLE
[Google Search] snippet with date instead of text (with parameter qdr:m)

### ISSUE THREAD

**Issue by RedBillyOne** [serpapi/public-roadmap#1270]
Hi,

![Capture d’écran 2023-12-07 150229](https://github.com/serpapi/public-roadmap/assets/152279883/7bc8f712-d63f-4daf-a733-f3acf5252545)

A search on Google with qdr:m (example [/search?api_key=XXX&engine=google&gl=fr&google_domain=google.fr&hl=fr&location=France&q=star+wars&tbs=qdr%3Am] return the date in Snippet (i.e "snippet": "il y a 5 jours —",) instead of the text snippet

Regards

**Comment by ilyazub** [comment]
@RedBillyOne, I'm sorry for the inconvenience and thanks for reporting this bug! We'll share an update here when we fix the `snippet` and `date` extraction.

Here's the additional info for our team:
[Search Inspect](https://serpapi.com/searches/6571d9c3797ac654a6101e89/inspect) | [Playground](https://serpapi.com/playground?q=star+wars&location=France&tbs=qdr%3As)

**Comment by RedBillyOne** [comment]
> @RedBillyOne, I'm sorry for the inconvenience and thanks for reporting this bug! We'll share an update here when we fix the `snippet` and `date` extraction.
> 
> Here's the additional info for our team: [Search Inspect](https://serpapi.com/searches/6571d9c3797ac654a6101e89/inspect) | [Playground](https://serpapi.com/playground?engine=google&gl=fr&google_domain=google.fr&hl=fr&location=France&q=star+wars&tbs=qdr%3Am)

@ilyazub we've got the same issue without parameter qdr:m) see screenshot below
![image](https://github.com/serpapi/public-roadmap/assets/152279883/6fce2475-f052-48d5-8019-e72053282a1d)

**Comment by ilyazub** [comment]
@RedBillyOne, thank you again for your patience and sharing an update.

We noticed the same bug for other locations: https://github.com/serpapi/public-roadmap/issues/1274

Apologies for the inconvenience this is causing.

**Comment by ilyazub** [comment]
@RedBillyOne We just deployed the fix.

![image](https://github.com/serpapi/public-roadmap/assets/282605/bce7b1da-34fe-49e4-a223-a613bc2aba92)
(ref: https://serpapi.com/playground?q=star+wars&location=France&tbs=qdr%3Am)

Let us know if it works for you.

**Comment by RedBillyOne** [comment]
Hi,

All is fine. Thanks you for  your quick answer
