### ISSUE TITLE
[Google Search API] "Search results for" block is not displayed

### ISSUE THREAD

**Issue by RedBillyOne** [serpapi/public-roadmap#1272]
Hi,

1. The "Search results for" block is not displayed in the API data.
https://serpapi.com/playground?q=coiffeur+neuilly+sur+seine&location=France&google_domain=google.fr&gl=fr&hl=fr&newPara=chips

![Capture d’écran 2023-12-07 155324](https://github.com/serpapi/public-roadmap/assets/152279883/bfd1917c-e224-4a76-b463-106c7f3218e0)

2. The "Search job offers on" block is not displayed in the API data.
https://serpapi.com/playground?q=recrutement+comptable&location=France&google_domain=google.fr&gl=fr&hl=fr&newPara=chips

![image](https://github.com/serpapi/public-roadmap/assets/152279883/f31d449f-a0b6-4453-83e2-75514ef801cb)

3. The "Search for" block is not showing

![image](https://github.com/serpapi/public-roadmap/assets/152279883/775a682b-d9ca-4709-aed6-6919cecf9df5)

https://serpapi.com/playground?q=meilleur+chirurgien+esthetique+paris&location=France&google_domain=google.fr&gl=fr&hl=fr&newPara=chips

Is it possible to add theses data ?

Regards

**Comment by tanys123** [comment]
Thanks @RedBillyOne for reporting the issue! We will let you know when there is an update for this.

**Comment by RedBillyOne** [comment]
@btaunt Hi, thank? BUT are you sure this is On lineIN serpapi json ?
If we made a search on this 2 examples, there isn't any block in SERPAPI Json
1.  https://serpapi.com/playground?q=recrutement+comptable&location=France&google_domain=google.fr&gl=fr&hl=fr&newPara=chips
![image](https://github.com/serpapi/public-roadmap/assets/152279883/5aa6d7b8-2cc3-401b-b867-bd66ee29641f)

2. https://serpapi.com/playground?q=coiffeur+neuilly+sur+seine&location=France&google_domain=google.fr&gl=fr&hl=fr&newPara=chips
![image](https://github.com/serpapi/public-roadmap/assets/152279883/f49e8111-092b-4841-bebf-7f6dcc7ee9ad)

**Comment by btaunt** [comment]
Hi @RedBillyOne 

Sorry, when a PR is merged it auto-closes the corresponding ticket which sometimes occurs before the full deploy has taken place. Your example URLs do work as intended now, but I wanted to follow up with you:

1. New docs for this `places_sites` can be found here for reference: https://serpapi.com/places-sites
2. The `Search job offers` is now parsed under the same `jobs_results` that we already extract
3. I was unable to replicate the `Search results for` sections (maybe Google no longer provides that section in their layouts?) 

As for point 3, if you happen to run into another instance of those elements, please feel free to open a separate ticket and ping me. Let me know if there are any issues. 👍
