### ISSUE TITLE
[Google Search API] `snippet` not parsed correctly for some results

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1274]
A customer reported that the `snippet` field is not being parsed correctly for some results:

<img width="1422" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/de2f5eac-5e1f-4d5b-9c8c-7ecfbc911b5b">

[Playground](https://serpapi.com/playground?q=How+many+people+have+died+in+the+Israeli-Palestinian+conflict%3F) | [Inspect](https://serpapi.com/searches/65730a74ada54bd0b4acdbab/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054970?view=List)

**Comment by ilyazub** [comment]
Related to https://github.com/serpapi/public-roadmap/issues/1270.

**Comment by martin-serpapi** [comment]
I'm re-opening this issue since another customer reported this for a search performed at 2023-12-12 05:19:57 UTC:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/1e965686-0be3-4faf-aead-2ab74371bec6)

[Inspect](https://serpapi.com/searches/6577ed7dc7ad417d941b066d/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055145?view=List)
