### ISSUE TITLE
[Yandex Search API] `lang=en` is passed for each request, event when not explicitly provided as a parameter

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1276]
According to our [Yandex Search API documentation](https://serpapi.com/yandex-search-api#api-parameters-localization-lang), the `lang` parameter is optional. However, `lang=en` is being passed for each request, event when it's not explicitly provided as a parameter:

<img width="1417" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/1ae5c40d-11b7-4ce9-960d-85755494514e">

[Playground](https://serpapi.com/playground?engine=yandex&text=coffee&yandex_domain=yandex.com&no_cache=true) | [Inspect](https://serpapi.com/searches/657315845c560658fa59bc84/inspect)

This is causing issues when trying to perform advanced searches using the pipe - `|` search operator. When this operator is used in combination with the `lang` parameter, our Yandex Search API and the actual Yandex Search engine do not return any results:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/8a97d8ee-67c6-407e-9d5d-c8012ff281c4)

![image](https://github.com/serpapi/public-roadmap/assets/144151895/eacd3d9b-5ccd-4bea-9fe6-825c43ca2375)

[Playground](https://serpapi.com/playground?engine=yandex&text=Late+Breakfast+%7C+Early+Lunch&yandex_domain=yandex.com&no_cache=true) | [Inspect](https://serpapi.com/searches/657316e5c99903ad0d1bb4f5/inspect) | [Yandex Search](https://yandex.com/search/?text=Late+Breakfast+%7C+Early+Lunch&lr=84&lang=en)

If no `lang` parameter is passed in the request, Yandex returns results successfully for searches with the `|` operator:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/b9472f8c-3cbb-4273-a800-862578785d5b)

[Yandex Search](https://yandex.com/search/?text=Late+Breakfast+%7C+Early+Lunch&lr=84)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054965?view=List)

**Comment by kagermanov27** [comment]
@zyc9012 I would suggest waiting until https://github.com/serpapi/SerpApi/pull/4369 is merged. It is not in conflict. But the method is going to change if it is approved and merged. So we would need to make a simple observation with no-lr searches. Up to you though.
