### ISSUE TITLE
[Yelp Places API] Some API calls are not executing at all

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1277]
One of our customers reported that our Yelp Places API is not working as intended and some searches are getting timed out. I've checked on our Playground, and this seems to be the case:

1st example:
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/bdf5801f-aee2-4044-93e5-e3e5e2772550">

2nd example:
<img width="1437" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/4e9707f0-474b-4d8f-960c-f9ad4f9ab0d2">

[Playground](https://serpapi.com/playground?engine=yelp_place&place_id=aaron-hatch-lmt-providence) | [Inspect](https://serpapi.com/searches/657323945fc4938a841fa718/inspect)
[Playground](https://serpapi.com/playground?engine=yelp_place&place_id=green-bubble-gorgeous-grand-rapids) | [Inspect](https://serpapi.com/searches/65732395dc02f1583f492fe2/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000054373?view=List)

**Comment by kagermanov27** [comment]
@ilyazub Details in https://github.com/serpapi/SerpApi/pull/4364 show that this is not about https://github.com/serpapi/SerpApi/pull/4332.

https://github.com/serpapi/SerpApi/pull/4332 is about problems with 200 response codes.
We have to deal with 301 in https://github.com/serpapi/SerpApi/pull/4364.
