### ISSUE TITLE
[Playground] `google_domain`, `gl`, and `hl` values are set to `location's` default even when link includes different values

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1281]
One of our customers tried to access the Playground with the direct link, but got different results that were provided. It looks like our Playground always defaults to `location's` default values for `google_domain`, `gl`, and `hl` parameters.

The following link specifies `location=Berlin, Berlin, Germany`, `google_domain=google.pl`, `gl=pl`, `hl=pl`, but when accessed, the values are different:
https://serpapi.com/playground?q=Coffee&location=Berlin%2C+Berlin%2C+Germany&google_domain=google.pl&gl=pl&hl=pl&device=desktop
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/2bfb5af5-fa64-4e62-abf9-fd9a3d7ddbc0">

The following link specifies `location=Abu Dhabi, Abu Dhabi, United Arab Emirates`, `google_domain=google.es`, `gl=es`, `hl=es`, but when accessed, the values are different:
https://serpapi.com/playground?q=Coffee&location=Abu+Dhabi%2C+Abu+Dhabi%2C+United+Arab+Emirates&google_domain=google.es&gl=es&hl=es&device=desktop
<img width="1434" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/15b0c431-b2bd-4ba1-acce-8f136df5773c">

[Playground 1](https://serpapi.com/playground?q=Coffee&location=Berlin%2C+Berlin%2C+Germany&google_domain=google.pl&gl=pl&hl=pl&device=desktop) | [Playground 2](https://serpapi.com/playground?q=Coffee&location=Abu+Dhabi%2C+Abu+Dhabi%2C+United+Arab+Emirates&google_domain=google.es&gl=es&hl=es&device=desktop)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055076?view=List)

**Comment by aciddjus** [comment]
It's a playground feature. If `location` is present in the URL when loading the playground, the `localization` fields will auto-adjust to that location. We are doing this to reduce unexpected results, as the "real world" situation would almost never be with the `location` parameter detached from the 'localization' parameters. 

Users can still change `localization` parameters directly in the playground.

Closing this as not planned.
