### ISSUE TITLE
[Google Search API] visual stories and publisher carousel are missing from JSON

### ISSUE THREAD

**Issue by githubfan21** [serpapi/public-roadmap#1283]
https://serpapi.com/playground?q=taylor+swift&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&newPara=ie+oe+pws+ibp

https://serpapi.com/playground?q=joe+biden&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&newPara=ie+oe+pws+ibp

missing visual stories
![image](https://github.com/serpapi/public-roadmap/assets/15785331/36de1bb9-717c-4603-9a55-24f2170d78d8)

missing publisher carousel
![image](https://github.com/serpapi/public-roadmap/assets/15785331/699962a3-db92-4567-ad7c-e73284d32d5f)

**Comment by kagermanov27** [comment]
Thanks for opening up an issue with us @githubfan21.

@tanys123 Should we split this issue into two? The elements seem unrelated to each other.
