### ISSUE TITLE
[Google Search API] `inline_images_suggested_searches` not parsed for some searches

### ISSUE THREAD

**Issue by RedBillyOne** [serpapi/public-roadmap#1286]
Hi,

When we made a search on https://serpapi.com/playground?q=affiner+pointe+du+nez+sans+chirurgie&location=France&google_domain=google.fr&gl=fr&hl=fr&newPara=chips

the suggested keywords (red circle below) are not display in the JSON file

![image](https://github.com/serpapi/public-roadmap/assets/152279883/81a578cb-5c68-499a-afb2-2d8c39908f8b)

Is it possible to add theses data ?

Regards

**Comment by kagermanov27** [comment]
[Playground](https://serpapi.com/playground?q=affiner+pointe+du+nez+sans+chirurgie&location=France&google_domain=google.fr&gl=fr&hl=fr&no_cache=true&google_domain=google.fr&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+votes)
[Inspect](https://serpapi.com/searches/6579fd4117f9230107da8a8e/inspect)
