### ISSUE TITLE
[Bing Search API] Date picker in the HTML response displaying wrong dates when using a date range filter

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1287]
A customer reported that when filtering the Bing Search API results by date range, the last date in the range is not included in the response. The issue seems to be with the date picker's displayed dates in the HTML response. The date of the actual results is displayed correctly.

Search with a `filters=ex1:"ez5_19704_19704"` (13/12/2023 - 13/12/2023) parameter:

<img width="1416" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/d81e9b94-776d-4279-9ff5-0bc5b572b153">

[Playground](https://serpapi.com/playground?engine=bing&q=machine+learning&location=Sofia+City+Province%2C+Bulgaria&filters=ex1%3A%22ez5_19704_19704%22) | [Inspect](https://serpapi.com/searches/6578e05366440aad0819c0ce/inspect)

Actual Bing search with a with a `filters=ex1:"ez5_19704_19704"` (13/12/2023 - 13/12/2023) parameter:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/9d14b39a-ece4-497b-b780-591a49bdc33b)

[Bing Search](https://www.bing.com/search?q=machine+learning&filters=ex1%3a%22ez5_19704_19704%22)

The issue seems to be happening when the search is performed shortly after midnight, in the timezone of the location specified in the `location` parameter.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/mentions/conversation/102910000055081?view=List)

**Comment by andypple83** [comment]
I've tested with multiple time zones. The time picker is showing the wrong date for some specific period. This is a bug from Bing search. We displayed correctly from Bing search results.

Let me know if you need more information.
Thanks
