### ISSUE TITLE
[Google Search API] Iframe Content Overflow Issue Due to Dynamic Class Addition

### ISSUE THREAD

**Issue by djsegal** [serpapi/public-roadmap#1289]
Encountered a UI issue in the [Google Search API] related to iframe content rendering. A dynamically added class – `TaoyYc` – within the iframe's `<html>` tag is enforcing an "overflow: hidden" style, leading to layout complications and obscured content.

![Screenshot of Issue](https://github.com/serpapi/public-roadmap/assets/3156114/e5fa1739-fcdc-4e0e-a45a-fb69a9e8ece0)

The issue impacts the functionality of iframe integrations, particularly where displaying the full content is essential. Eager to discuss potential solutions to this problem

[Search Inspector](https://serpapi.com/searches/6579e635eb690f3e3057ba77/inspect) | [Playground](https://serpapi.com/playground?q=hilton+hotel+sofia&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=votes+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client)

**Comment by tanys123** [comment]
I think we can either remove the `.TaoyYc{overflow:hidden}` or override it using CSS `important` - `html{overflow:auto !important;}`
