### ISSUE TITLE
[Walmart Product API] Searches with the `upc` parameter are not returning results

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1292]
Per our documentation, users can use `product_id`,`us_item_id` or `upc` to query results in Walmart Product API. While the first two parameters work, the `upc` returns no results. My best guess is that Walmart no longer allows searches with the `upc`, but it's worth investigating if there is an issue.

Documentation:
<img width="860" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/287d170f-ab3c-4074-8da3-2a2c84bd55a0">

All values for the product:
<img width="1439" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/0d1d76b5-a756-4c29-b8a6-7bd30fe59dce">

Search with `us_item_id`:
<img width="1435" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/279ba995-7a1b-4717-8339-37784f987ac6">

Search with `product_id`:
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/45a7706c-8697-4654-8641-3e6888871d59">

Search with `upc`:
<img width="1438" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/a0c4d671-2564-4ea2-8eb9-1c1aa5855299">

[Playground](https://serpapi.com/playground?engine=walmart_product&product_id=072323000142) | [Inspect](https://serpapi.com/searches/657aa1dc979054f7f30f64d7/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055290?view=List)

**Comment by dsojevic** [comment]
Search by UPC is no longer supported and we removed reference to it in the documentation in March to reflect this.

**Comment by zyc9012** [comment]
@dsojevic Let's close it as "not planned".
