### ISSUE TITLE
[Google Jobs API] `htidocid` missing in the `job_id` decoded value

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1294]
A customer reported that `htidocid` is no longer present in the `job_id` decoded value. They've noticed that this started happening since today. In their searches from 2023-12-13 the `htidocid` is present in the decode `job_id` value.

I was able to reproduce this in our Playground:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/226c8dff-8efb-4979-b748-9834d188a972)

[Playground](https://serpapi.com/playground?engine=google_jobs&q=software+developer&location=San+Francisco+Bay+Area%2C+United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/657b1b1958762b9ea220c263/inspect)

Below is the decode value of the first result's `job_id`:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/69bb2c3f-d880-4cbe-93b0-1278464a1daa)

Our Google Jobs Listing API doesn't seem to be returning results for those Job IDs as well:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/8b9ca7d7-d876-4143-99b1-b548d4757f79)

[Playground](https://serpapi.com/playground?engine=google_jobs_listing&q=eyJ1dWxlIjoidytDQUlRSUNJa1UyRnVJRVp5WVc1amFYTmpieUJDWVhrZ1FYSmxZU3hWYm1sMFpXUWdVM1JoZEdWeiIsImdsIjoidXMiLCJobCI6ImVuIiwiZmMiOiJFcUlDQ3VJQlFVeFBibkJaV0VGYU0yYzRhV2xPUW1SeVpYVk1aSFk0V1hsRFlUVmZlamhsTXpaNmRUUmZVbEJ6YVZSc1dXMHhabXRhTFhKZlgycGlkMUJEV2psNlZITXdYMVJWVEVOamJGbHpWbVY0TFVkMVowZ3hlRmN3V21aaE5tMUtkbGxJUlc0elQwbE5ZV2RGVmpGMVQwZ3pOMVJqTW1GcloybzBUSEJmTkc1V1IzVTRUbEpwUzNCNVJVdEplR0pZVVhVd1ZtWktNR1I2Vlhkd1NtcFpTRUl5T0RSd1YzYzNkMGRXVEVoVmMwVlFSbHBxTUdWTGFXaG9RM0pFVDJWZmJYbEZTR0Z2TVRCeGNWSXlZbmxJUmxKbU1HbDZZMWhXYjJOWlRtbzJhVjl4YzJwSVp4SVhSMmgwTjFwamNWSlBUVVJyTUZCRlVDMDFZWEJ4UVRnYUlrRktkMnN0T0dab1FYVXRjSE5qT0UwM09FcG9la1ZZVVV0RFR6SlVWbFU1UkhjIiwiZmN2IjoiMyIsImZjX2lkIjoiZmNfMSIsImFwcGx5X2xpbmsiOnsidGl0bGUiOiIubkZnMmVie2ZvbnQtd2VpZ2h0OjUwMH0uQmk2RGRje2ZvbnQtd2VpZ2h0OjUwMH1BcHBseSBvbiBMaW5rZWRJbiIsImxpbmsiOiJodHRwczovL3d3dy5saW5rZWRpbi5jb20vam9icy92aWV3L2xlYWQtc29mdHdhcmUtZW5naW5lZXItYXQtZ29saWF0aC1wYXJ0bmVycy0zNzg1ODY3NTI2P3V0bV9jYW1wYWlnbj1nb29nbGVfam9ic19hcHBseVx1MDAyNnV0bV9zb3VyY2U9Z29vZ2xlX2pvYnNfYXBwbHlcdTAwMjZ1dG1fbWVkaXVtPW9yZ2FuaWMifX0%3D) | [Inspect](https://serpapi.com/searches/657b1b3d4b91ebc4f5ed32f3/inspect)

[Customer results from 2023-12-13 Inspect](https://serpapi.com/searches/6579b41e14b245c9cca4fef3/inspect) | [Customer results from 2023-12-14 Inspect](https://serpapi.com/searches/657b0b0c2f542edfb0aacb12/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055316?view=List)

**Comment by ajyang818** [comment]
@ilyazub Do you think that's related to the missing `htidocid` key? I believe `htidocid` previously was a top-level key in that decoded JSON, not part of the `apply_link` value.

I was using `htidocid` as a unique ID for the job posting, one that would stay consistent across different searches done by serpapi. I believe `fc` does not satisfy that same criteria. Is there another field in the Google Jobs API response that can potentially be used for a unique identifier?

**Comment by martin-serpapi** [comment]
Another high volume customer reported the same issue. I was able to reproduce it in the Playground:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/dd79d83e-3578-4982-88c3-0f1da84547af)

[Playground](https://serpapi.com/playground?engine=google_jobs&q=sports+internship+volo+sports&location=Baltimore%2C+MD%2C+Maryland%2C+United+States&gl=us&hl=en&start=0&chips=date_posted%3Amonth) | [Inspect](https://serpapi.com/searches/66278dadc573d56cd12758be/inspect)

Below is the decoded value of the first result's `job_id`:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/86ac450a-0781-454b-8181-8facae4de3f6)

[Base64 Decode](https://www.base64decode.org/)

Our Google Jobs Listing API doesn't return results for this `job_id` either:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/1dcb3dcd-8c15-4809-ac6b-e77184ec3b7b)

[Playground](https://serpapi.com/playground?engine=google_jobs_listing&q=eyJ1dWxlIjoidytDQUlRSUNJalFtRnNkR2x0YjNKbExFMUVMRTFoY25sc1lXNWtMRlZ1YVhSbFpDQlRkR0YwWlhNIiwiZ2wiOiJ1cyIsImhsIjoiZW4iLCJmYyI6IkVzd0NDb3dDUVU1MVYyaGpibTB4V0dabVJWSlJTMDB4VVZreVMycDJTWEJ1UVVGbVVHTnhjWEJSVUhkR2VrVjRVREZ0Wlcxa1RGTkNaVFZaTFcxTFZWUm1WRlZZV0UxNmMyOXVRVloyU1RSbFlYUkhla3h0ZVU5cWRsZFZUakJGWVhCaE5GbEZNMlZvVDFoU1pYaEpWRTF1UW5GbFowRnJiVnBUVVRkNVh6TXlVQzFWYUZSd1RsZEdRblJxUmtwM1RuRlRiVEpPUWpGb04wOHhZVEZ3UTIxdldqTkNUMlEzV2xCc1NFMUxTblpIWVZaV2NFbERUV2hYVWxGak9XazBaMEV0U2pOellUTnliVWh5VkVwTmVXaFdVVjlYWm5jMll6WXhjSGR0TWpWUFdIcHRjREpXU3pKTmVYVnNhWFpZWkRKSVExbDFSMVIwTVd3eVZuaFlUbDlNTUhGV2FrWkRZaTF4Vms5MlZYbDZYeElYY2pRd2JscDJkbmxCTkdaMmFVeE5VSEJ6VjFkNVFUZ2FJa0ZRV0dodE5WcDZXaTEzZFRsMGEyNVdjeTFNZDJWSWFsTlJhRWRVWmxkNmNuYyIsImZjdiI6IjMiLCJmY19pZCI6ImZjXzEiLCJhcHBseV9saW5rIjp7InRpdGxlIjoiLm5GZzJlYntmb250LXdlaWdodDo1MDB9LkJpNkRkY3tmb250LXdlaWdodDo1MDB9QXBwbHkgb24gTGlua2VkSW4iLCJsaW5rIjoiaHR0cHM6Ly93d3cubGlua2VkaW4uY29tL2pvYnMvdmlldy9zdW1tZXIteW91dGgtc3BvcnRzLW1hbmFnZW1lbnQtYW5kLW1hcmtldGluZy1pbnRlcm5zaGlwLWF0LXZvbG8tc3BvcnRzLTM4OTk1MzcwMzU%2FdXRtX2NhbXBhaWduPWdvb2dsZV9qb2JzX2FwcGx5XHUwMDI2dXRtX3NvdXJjZT1nb29nbGVfam9ic19hcHBseVx1MDAyNnV0bV9tZWRpdW09b3JnYW5pYyJ9fQ%3D%3D) | [Inspect](https://serpapi.com/searches/66278de90b50620eb762b014/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000045445?view=List)

**Comment by tanys123** [comment]
We have deployed a fix to the issue

<img width="679" alt="Screenshot 2024-04-29 at 11 30 26 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/0c6fe605-fa1c-4a60-b00c-36c085c5d05a">
