### ISSUE TITLE
[UI][Playground] Google Jobs Listing API Playground Example is Expired 

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1295]
The default example when visiting the Playground and selecting the Google Jobs Listing API appears to be expired.

<img width="1444" alt="Screenshot 2023-12-14 at 11 03 44 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/7d5fdbb6-2379-4396-a203-c74e67778f9e">

[Playground](https://serpapi.com/playground?engine=google_jobs_listing&q=eyJqb2JfdGl0bGUiOiJDYWZlIEJhcmlzdGEiLCJodGlkb2NpZCI6Im1jSVlyZ1NNU1FvQUFBQUFBQUFBQUE9PSIsImZjIjoiRXVJQkNxSUJRVUYwVm14aVFqbENRbFJmYmtwMVptVnFVeTB3VFVKM1pEbDZhV2R0U201RmQxVmlZWFZ3UkU5QmFuSjRjRkZrUkhGUGJXRm9MVzR5WVdoMWRXRmxUVk4wVUVWdGRGUmhVVGM1UkZNd1pYWmhXbTlIYUZsS1ZGVTRhemRyU1dwa05UUkdNVlF6WWt4MVVWVnhTelpJZGxabWJESnVlQzEyTVdORGNVTjJjek00ZWw5eFNXZGlZWFZPWmtoRlMwMDFaR1ZCWTBSTVZGSldMV2szV1ZKT1FrSlJFaGN4TjJsdVdWOVRaMGwxVTFBNWRUaFFiRFpQYlRKQlNSb2lRVVJWZVVWSFpXUkZkSHBMVUZoTFVUZHRTMWRETFhCTVRFOWtPWEpoYWtoQ2R3IiwiZmN2IjoiMyIsImZjX2lkIjoiZmNfMSIsImFwcGx5X2xpbmsiOnsidGl0bGUiOiIubkZnMmVie2ZvbnQtd2VpZ2h0OjUwMH0uQmk2RGRje2ZvbnQtd2VpZ2h0OjUwMH1BcHBseSBvbiBDaG9vc2U5MDEiLCJsaW5rIjoiaHR0cHM6Ly9jaG9vc2U5MDEuY29tL2pvYi9wYXJrLWNoZXJyeS1tZW1waGlzLXRlbm5lc3NlZS04MC1jYWZlLWJhcmlzdGEvP3V0bV9jYW1wYWlnbj1nb29nbGVfam9ic19hcHBseVx1MDAyNnV0bV9zb3VyY2U9Z29vZ2xlX2pvYnNfYXBwbHlcdTAwMjZ1dG1fbWVkaXVtPW9yZ2FuaWMifX0) | [Inspect](https://serpapi.com/searches/657b5178f716ee114ebdcc6e/inspect)

**Comment by jacob-restart** [comment]
I think this might be a bigger problem than just the example. All of the calls we're making to the job listing api right now are returning no information about the job. We mainly use this call to get the apply link options in our app. If there's no apply link returned we consider the job expired. Right now every single call is returning nothing, even for a batch of jobs that are brand new. This started happening two days ago. Please help!

**Comment by schaferyan** [comment]
Thank you @jacob-restart. Yes, this is actually a separate issue. The example is expired, but there is also a larger bug with the Google Jobs Listing API. That issue is documented here:

https://github.com/serpapi/public-roadmap/issues/1259

**Comment by djsegal** [comment]
The issue seems to be caused by the Playground using a hard-coded job listing search id/query, as seen here:
- [demo-v5.jsx](https://github.com/serpapi/SerpApi/blob/master/app/assets/javascripts/components-playground/demo-v5.jsx#L1716-L1717)

Given that job postings are temporary, this method requires ongoing updates. A more sustainable approach might involve periodically refreshing the example with a current listing from the Google Jobs API, ensuring the Playground always demonstrates an active and relevant example

**Comment by schaferyan** [comment]
@jacob-restart I wanted to let you know our engineers have implemented a fix to the larger issue with the Google Jobs Listing API you mentioned, documented here: https://github.com/serpapi/public-roadmap/issues/1259. The Google Jobs Listing API now works as expected. You can see an example here:

https://serpapi.com/playground?engine=google_jobs_listing&q=eyJqb2JfdGl0bGUiOiJDYWZmZSBNYWNzIEJhcmlzdGEiLCJodGlkb2NpZCI6Ik5wTmJiSmw2aVJTUXJRYk9BQUFBQUE9PSIsImZjIjoiRW93Q0Nzd0JRVXhQYm5CWlYwaFVNVEEzTVhwUmVUSkJORE5yVlZwM2VqRkJTelZ6WmtaTVVtUkVSSGQzVDJaMlVrMXJMVFJQVEVJeVJUQTJXV2w2Y2pSbVRIZEVNM0pUZWpCS1YyaHZMWHB5ZW10V1MyeFRNRTUzTlVKNVlVbG9VVXBKVm1sMVZrazViWFJhY1doRmNtaENRVmgwYVV0SloydzFUak00WDFZME1sSjNaWEZtVFd0V2JUZzFiemRPVkZwa05UTnBiMlJYWm5aUFZsSTJVSEpYZUc1aldUTTVTWFpRU1UxNFJsSnVjRFpGY1hCQ01ITnVZbmRrYm5WWVQwSmFRakl0Y0dKRVEyVlJOamhxWVc1QkVoZHJhV1ZFV21NeVIwTmpiWHB3ZEZGUWJqZGhNSE5CWnhvaVFVcDNheTA0WTJwcmRWOXFNVkJLVjJGTWNYRm9NRk5GVkhwWFVrTnRNRU5yWnciLCJmY3YiOiIzIiwiZmNfaWQiOiJmY18xIiwiYXBwbHlfbGluayI6eyJ0aXRsZSI6Ii5uRmcyZWJ7Zm9udC13ZWlnaHQ6NTAwfS5CaTZEZGN7Zm9udC13ZWlnaHQ6NTAwfUFwcGx5IG9uIENhcmVlcnMgQXQgQXBwbGUiLCJsaW5rIjoiaHR0cHM6Ly9qb2JzLmFwcGxlLmNvbS9lbi11cy9kZXRhaWxzLzIwMDUwNTM4MC9jYWZmZS1tYWNzLWJhcmlzdGE%2FdXRtX2NhbXBhaWduPWdvb2dsZV9qb2JzX2FwcGx5XHUwMDI2dXRtX3NvdXJjZT1nb29nbGVfam9ic19hcHBseVx1MDAyNnV0bV9tZWRpdW09b3JnYW5pYyJ9fQ%3D%3D

Note that any job_ids you may already have from querying our Google Jobs API may be incomplete, we recommend using the Google Jobs API again to extract these now that the fix is in place.

Thank you so much for your patience during this process.
