### ISSUE TITLE
[Google Search API] Knowledge Graph is Missing the `place_id` and `link` Keys

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1299]
A customer reported we are no longer parsing the `place_id` and `link` keys from Knowledge Graphs of restaurants. It appears we are still providing the `links` key but it sometimes contains an empty object, despite the presence of order links in the HTML.

<img width="1105" alt="Screenshot 2023-12-15 at 1 23 25 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/adcb8dd7-5e09-4dfa-a98b-be643de11754">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055393?view=List) | [Playground ](https://serpapi.com/playground?q=Golden+Dragon+800+Wilcox+St+Joliet+IL+60435&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&newPara=votes)| [Inspector](https://serpapi.com/searches/657bedc8cace969d5b5139bb/inspect) | [Inspector 2](https://serpapi.com/searches/657bedcaaf5af13ebc28cb4f/inspect)

**Comment by schaferyan** [comment]
I marked this `priority` as the customer is on one of our larger plans and these keys are important for their business.

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055527?view=List)
