### ISSUE TITLE
[Google Lens API] Error when using the `country` parameter in the request

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1307]
A customer reported that the requests to our Google Lens API are either timing out or returning a error. The issue seems to be caused by the `country` parameter.

![image](https://github.com/serpapi/public-roadmap/assets/282605/68552578-9b61-4781-98a5-802f06780646)

[Playground](https://serpapi.com/playground?engine=google_lens&url=https%3A%2F%2Fi.imgur.com%2FHBrB8p0.png&hl=en&country=us) | [Inspect](https://serpapi.com/searches/6584495ffdca3ea6f9a56de6/inspect)

When not providing a `country` parameter, a response is returned successfully.

![image](https://github.com/serpapi/public-roadmap/assets/282605/a58a0549-192f-43d9-b6ae-02589f75dfa5)

[Playground](https://serpapi.com/playground?engine=google_lens&url=https%3A%2F%2Fi.imgur.com%2FHBrB8p0.png&hl=en) | [Inspect](https://serpapi.com/searches/65844b08ea1442871829ba60/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055692?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this. I'm increasing the priority, since all of the requests that contain `country` parameter seem to be failing.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055699?view=List)

**Comment by schaferyan** [comment]
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055725?view=List)

**Comment by tanys123** [comment]
Resolve by https://github.com/serpapi/SerpApi/pull/4339
