### ISSUE TITLE
[UI/UX] Allow Filtering Searches with Parameters

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1315]
<img width="1169" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/b93a573e-220d-40db-b076-bf06b6ab1dc6">

Right now, we are only allowing searches of users to be filtered by the engine. We can implement parameter-level filters for ease.

[Searches Page](https://serpapi.com/searches)

Moved from https://github.com/serpapi/SerpApi/issues/1250

**Comment by schaferyan** [comment]
This also exists here:

https://github.com/serpapi/public-roadmap/issues/125

**Comment by kagermanov27** [comment]
Closing this as it is a duplicate of https://github.com/serpapi/public-roadmap/issues/125
