### ISSUE TITLE
[Google Maps API] Support web_results

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1319]
Here is [Google Maps link](https://www.google.com/maps/place/Coffee+place/@44.7991539,20.5111755,13z/data=!4m10!1m2!2m1!1scoffee!3m6!1s0x475a7bc8a640b4bf:0x37b8db415aad53f6!8m2!3d44.8119313!4d20.4692388!15sCgZjb2ZmZWVaCCIGY29mZmVlkgELY29mZmVlX3Nob3CaASRDaGREU1VoTk1HOW5TMFZKUTBGblNVTndPRjlUTm5KUlJSQULgAQA!16s%2Fg%2F11pctfh0b5?entry=ttu) with web results at the bottom

![image](https://github.com/serpapi/SerpApi/assets/6929257/1f3ec903-392d-4ebb-a41c-f1451972296a)

And on our end:

![image](https://github.com/serpapi/SerpApi/assets/6929257/2cc53faf-0296-4863-977a-57d63e18df49)

[Playground](https://serpapi.com/playground?engine=google_maps&q=Coffee+Shop&ll=%4044.7991539%2C20.5111755%2C13z&hl=en&place_id=ChIJv7RApsh7WkcR9lOtWkHbuDc&type=search)
[Inspect](https://serpapi.com/searches/658eac22c90e0aaa1edff4e9/inspect)

Moved from https://github.com/serpapi/SerpApi/issues/1598
The recent layout found by @aciddjus at https://github.com/serpapi/SerpApi/issues/1598#issuecomment-1871969265

**Comment by schaferyan** [comment]
A customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059006?view=List)

**Comment by zyc9012** [comment]
The results were retreived by a separate request.

[Example link](https://www.google.com/search?q=local+guide+program&pcl=lp&ibp=gwp%3B0%2C26%2COigKJiIiQWxsZW5kYWxlIFRydWUgVmFsdWUgQWxsZW5kYWxlLCBNSSgD&opi=79508299)

**Comment by tanys123** [comment]
We have just deployed this feature. You can now retrieve Google Maps Web Results.

**How it works:**

We have added new attribute `web_results_link` and `serpapi_web_results_link` ([documentation](https://serpapi.com/maps-place-results#api-examples-example-of-web-results))
<img width="1082" alt="Screenshot 2024-05-17 at 10 25 53 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/c41ff0b3-4000-4a56-af43-67a1c3eba10a">

Follow the `serpapi_web_results_link` endpoint to get the Web Results data.
<img width="1351" alt="Screenshot 2024-05-17 at 10 29 56 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/2322b399-4bf7-48b8-93cc-99f0a4802d2a">

By default it only return 3 items, you can retrieve more items by specifying the `start` number, checkout the [documentation](https://serpapi.com/organic-results#api-examples-results-from-web-result-layout) for more info.
