### ISSUE TITLE
[Google Search API] answer_box title is mistakenly using the snippet

### ISSUE THREAD

**Issue by hangsu** [serpapi/public-roadmap#132]
The `title` and the `snippet` of the answer box are the same, even though the `title` should be the text of the link.

<img width="1257" alt="Screen Shot 2022-05-02 at 10 53 47 AM" src="https://user-images.githubusercontent.com/1279036/166266037-725ea318-d7a4-4098-924e-cf91e816a77b.png">

**Comment by aliayar** [comment]
This is still an ongoing problem and recently reported by another user:

https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000025926

[The Playground](https://serpapi.com/playground?q=%E5%BC%B7%E8%AA%BF%E3%82%B9%E3%83%8B%E3%83%9A%E3%83%83%E3%83%88&location=Tokyo%2C+Tokyo%2C+Japan&google_domain=google.co.jp&gl=jp&hl=ja&device=desktop&no_cache=true) | [The Inspect](https://serpapi.com/searches/62ac5cc73944b030a890a6aa/inspect)

<img width="946" alt="answer_box_my" src="https://user-images.githubusercontent.com/64849049/174286138-efabc1b9-4207-4608-a282-e5f34eb14bed.png">
