### ISSUE TITLE
[New API] Support the Home Depot Product Reviews API

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1321]
<img width="1464" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/17baff52-0085-4d57-a207-63ee9e33db85">

The Home Depot Product API is not returning reviews in the raw HTML. We would need another API for reviews.

Moved from: https://github.com/serpapi/SerpApi/issues/2091

**Comment by marm123** [comment]
A user requested this feature:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059501?view=List)

**Comment by marm123** [comment]
Our high volume customer also requested this. I'm changing the status to queued.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060432?view=List)

**Comment by schaferyan** [comment]
Another customer requested this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060732?view=List)

**Comment by tanys123** [comment]
We have deployed the new API. Here is the [documentation](https://serpapi.com/home-depot-product-reviews).

<img width="1267" alt="Screenshot 2024-03-26 at 4 44 42 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/9b9697cd-6f67-4cff-b53f-5bf09edd1046">
