### ISSUE TITLE
[Walmart Search API] `ps` parameter not working

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1324]
<img width="1468" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/2deec711-2869-4366-a96f-72f3f60d5f39">

[Playground](https://serpapi.com/playground?engine=walmart&query=Coffee&ps=100&no_cache=true)

`ps` parameter is not working. It should be replaced with an alternative or removed.

Moved from https://github.com/serpapi/SerpApi/issues/2246.

**Comment by schaferyan** [comment]
A potential Enterprise customer reported this during a meeting I had with them.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/search/conversation/102910000064190?query=%40squaretrade&view=List)

**Comment by btaunt** [comment]
Just as a point of reference - `ps` works with the Canadian Walmart website (https://www.walmart.ca/en), so unsure what they've altered with US.

- https://www.walmart.ca/en/search?query=Coffee&ps=10

<img width="958" alt="Screenshot 2024-06-13 at 8 51 30 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/3ea37fd3-5ebd-4509-a7a6-cdab75b12d48">

**Comment by schaferyan** [comment]
The potential Enterprise Customer I spoke to about this reported a bottleneck that would be improved if this could be fixed:

[Front](https://app.frontapp.com/open/msg_2g1ppmos?key=beibtduEUK2Z9TNNOubf8rnVvesmW4Sa)
