### ISSUE TITLE
[Knowledge Graph API] Support "details" modal

### ISSUE THREAD

**Issue by hartator** [serpapi/public-roadmap#133]
![image](https://user-images.githubusercontent.com/307597/166322534-5cb77151-7d18-499e-bf6c-9fc01c9961cc.png)

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/307597/166322585-5a12e803-8642-44e8-ae3c-6cb463f2fe73.png">

Ref: https://serpapi.com/playground?q=AW3423DW&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en

**Comment by kagermanov27** [comment]
Just sharing insights:

Information on the details modal is within the raw html:
![details](https://user-images.githubusercontent.com/73674035/175248373-1af8edc8-8b1a-4c0b-a641-598933c10e61.png)

However, responsible parts for extracting it doesn't have id for js extraction, and the element with js-data is not extracting responsible part with the methods we have (plus, it is an element that contains both modals, reviews and details). If we can find a way to tie the existing details element `.XpqX9[data-name="details"]` to a body in html that is carefully extracted, we can have a solution.
![details2](https://user-images.githubusercontent.com/73674035/175250776-e07552c1-27c0-4c6c-93c1-3070a429bcd2.png)

I tried and couldn't find a solution to it.

**Comment by ilyazub** [comment]
```ruby
id = doc.at_css('.psgQSb[data-name="details"]').id
# => "'_Hc25Yrz-EZmC0PEP_aaRkA8115'"

extract_js_div(id)

# parse data as usual
```

**Comment by ishiharaf** [comment]
We have implemented the details modal. It's working on production.

![image](https://github.com/user-attachments/assets/16707196-47e4-45ef-b715-130165efb33e)
![image](https://github.com/user-attachments/assets/520f31ac-e2c1-442f-9a47-022c985f7a40)
[Playground](https://serpapi.com/playground?q=AW3423DW&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com)
