### ISSUE TITLE
google sheets copy and paste formula get Oops field not found

### ISSUE THREAD

**Issue by pleabargain** [serpapi/public-roadmap#1335]
Here's the formula

=SERPAPI_RESULT("engine=google&q=new flights&location=Jeddah, Makkah Province, Saudi Arabia&google_domain=google.com.sa&gl=sa&hl=en&tbm=nws", "suggestions.0.value")

plugin is installed
API key is active

![image](https://github.com/serpapi/public-roadmap/assets/640846/e4689d26-5e4f-4881-a300-8383c53ba98b)

**Comment by hartator** [comment]
`Oops field is not found: suggestions (selector: suggestions.0 value` means that this search doesn't have `suggestions` results unfortunately.

Maybe try different search parameters?

**Comment by hilmanski** [comment]
Hi @pleabargain  
The `suggestions.0.value` is just a template. You should change it to the actual value you want to retrieve. For example, based on the result here: https://serpapi.com/playground?engine=google_flights&departure_id=CDG&arrival_id=AUS&gl=us&hl=en&currency=USD&outbound_date=2024-01-06&return_date=2024-01-12

Here is the JSON structure result:
![CleanShot 2024-01-05 at 11 24 48@2x](https://github.com/serpapi/public-roadmap/assets/4522467/93214d2e-006a-4000-b2d2-2e69dfc8d20d)

So to get the first value, we need to replace the `suggestions.0.value` with `best_flights.0.flights.0.departure_airport.name`

Here is a basic tutorial on using our Google Sheets extension: https://serpapi.com/blog/connect-serp-api-with-google-sheet-no-code/
