### ISSUE TITLE
[Google Maps API] Results from the first page are returned after reaching the last page.

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1340]
It appears that if you reach the last page of results in Google Maps API, the following pages are returning results from the first page instead of no results at all. One of our customers reported this issue recently.

1st page:
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/7521b5ed-6d4e-4d44-9326-bf0d702398e0">

2nd page (start=20):
<img width="1437" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/3ec7b908-15ba-4643-9d85-97048008a2f6">

3rd page (start=40, no actual results):
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/9f7783dd-ee9f-48ac-ae9c-a1c041b83cec">

[Playground 1st page](https://serpapi.com/playground?engine=google_maps&q=dentist+near+Barnhart%2C+Missouri%2C+USA&ll=%4038.3360%2C-90.4046%2C11z&hl=en&type=search) | [Inspect 1st page](https://serpapi.com/searches/659d6e52382427cddd751c5a/inspect)
[Playground 2nd page](https://serpapi.com/playground?engine=google_maps&q=dentist+near+Barnhart%2C+Missouri%2C+USA&ll=%4038.3360%2C-90.4046%2C11z&hl=en&type=search&start=20) | [Inspect 2nd page](https://serpapi.com/searches/659d6e6c9d1586a3dfb32478/inspect)
[Playground 3rd page](https://serpapi.com/playground?engine=google_maps&q=dentist+near+Barnhart%2C+Missouri%2C+USA&ll=%4038.3360%2C-90.4046%2C11z&hl=en&type=search&start=40) | [Inspect 3rd page](https://serpapi.com/searches/659d6e7c37014c212b1f03ac/inspect)

[Inspect start=0](https://serpapi.com/searches/659c7e4f359e99d38765d36a/inspect) | [Inspect start=1640](https://serpapi.com/searches/659c806966440a18b4395189/inspect) | [Inspect start=1960](https://serpapi.com/searches/659c8098dc02f1c45f9ab7ea/inspect) | [Inspect start=1980](https://serpapi.com/searches/659c809a10d7440a08a0b936/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056707?view=List)

**Comment by schaferyan** [comment]
Another customer reported this issue:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056839?view=List)

I'm bumping this up to "Prioritized" as it may cause our customers to unknowingly waste their search credits.

**Comment by hilmanski** [comment]
I remember a user reported this 7 days ago, I thought it was normal due to unlimited results from Maps.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/search/conversation/102910000056322?query=limit%20200&view=List)

**Comment by hilmanski** [comment]
A user having similar issues

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000057961?view=List)

**Comment by marm123** [comment]
Another user is reporting this issue. It's very confusing how the pagination works at the moment because of this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000022903?view=List)

**Comment by schaferyan** [comment]
Another customer with this issue:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000058036?view=List)
