### ISSUE TITLE
[Google Trends API] Search error for any parameters since yesterday

### ISSUE THREAD

**Issue by kpjwong** [serpapi/public-roadmap#1342]
Hi, starting yesterday, I have encountered search errors for Trends call, for example, the following response:

`{'search_metadata': {'id': '659ee38d87a0eedd349f5d50',
  'status': 'Error',
  'json_endpoint': 'https://serpapi.com/searches/1ee1febdea40d0ca/659ee38d87a0eedd349f5d50.json',
  'created_at': '2024-01-10 18:35:57 UTC',
  'processed_at': '2024-01-10 18:35:57 UTC',
  'google_trends_url': 'https://trends.google.com/trends/api/explore?tz=420&req=%7B%22comparisonItem%22%3A%5B%7B%22keyword%22%3A%22pasta%22%2C%22geo%22%3A%22%22%2C%22time%22%3A%22today+12-m%22%7D%5D%2C%22category%22%3A0%2C%22property%22%3A%22%22%2C%22userConfig%22%3A%22%7BuserType%3A+%5C%22USER_TYPE_LEGIT_USER%5C%22%7D%22%7D',
  'prettify_html_file': 'https://serpapi.com/searches/1ee1febdea40d0ca/659ee38d87a0eedd349f5d50.prettify',
  'total_time_taken': 90.14},
 'search_parameters': {'engine': 'google_trends',
  'q': 'pasta',
  'date': 'today 12-m',
  'tz': '420',
  'data_type': 'TIMESERIES'},
 'error': "We couldn't get valid results for this search. Please try again later."}`

I also did a search in the playground with the default parameters and that also did not successfully return search results:

![image](https://github.com/serpapi/public-roadmap/assets/46463846/9079b410-4f8c-40cf-9d1a-b0527e51960f)

I did not encounter similar errors with other engines.

Want to bring this to your attention. Thanks!

**Comment by schaferyan** [comment]
Related to #1143

**Comment by schaferyan** [comment]
@kpjwong would 10-15 seconds per request be an acceptable response time for your use case?

**Comment by ilyazub** [comment]
@dundil @kpjwong We just deployed the fix for our Google Trends API. Apologies for the inconvenience and _thank you_ for your understanding.

![image](https://github.com/serpapi/public-roadmap/assets/282605/fa6377b1-7abe-4172-ac52-f2f41b4d40dd)
(ref: https://serpapi.com/playground?engine=google_trends&q=coffee&geo=US&data_type=TIMESERIES&tz=420&date=all)

**Comment by ilyazub** [comment]
Closing this issue because we fixed our Google Trends API. Please let us know if it doesn't work _for you_.

![image](https://github.com/serpapi/public-roadmap/assets/282605/7a16d807-4fc8-4851-9aac-045f1130557c)
(ref: https://serpapi.com/playground?engine=google_trends)
