### ISSUE TITLE
[Google Lens API] Update `knowledge_graph` example in the documentation

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1346]
A user reported that the code generated from the Google Lens API documentation page results in a `KeyError: 'knowledge_graph'` after executing it. There is no longer a `knowledge_graph` returned in the results when using https://i.imgur.com/Jydn4Wb.jpeg URL:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/a052cf78-fc49-4e1b-a7a4-43a9189d5cee)

[Playground](https://serpapi.com/playground?engine=google_lens&url=https%3A%2F%2Fi.imgur.com%2FJydn4Wb.jpeg) | [Inspect](https://serpapi.com/searches/65a0344e0574f5d96f26c6d4/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056916?view=List)

**Comment by schaferyan** [comment]
I tried to find another example of a Google Lens search with a Knowledge Graph and couldn't find anything.

It's possible Google Lens no longer returns that element at all, in which case we should just remove that example from the documentation.

**Comment by andypple83** [comment]
Thanks @schaferyan and @martin-serpapi for reporting this issue.

Google still return knowldge_graph results for some searches. e.g:

![Screenshot 2024-06-11 at 16 23 59](https://github.com/serpapi/public-roadmap/assets/99160364/ced20d87-c20c-4975-a35c-0ea56d932623)

I found [a tweet](https://x.com/rajanpatel/status/1792700858679079166) from [Rajan Patel](https://x.com/rajanpatel) - "VP of Engineering at Google leading the Search experience, the Google app, Image Search, and Lens. Co-founded Lens, Gboard, and Google Podcasts." It seems like Google is working hard on the Knowledge graph and AI overview results. 

[Playground](https://serpapi.com/playground?engine=google_lens&url=https%3A%2F%2Fcdn.britannica.com%2F71%2F99571-050-DFF0A6E5%2FStatue-of-Liberty-Island-New-York.jpg&country=gb&no_cache=true) || [Inspect](https://serpapi.com/searches/66681780c56d93ed061e85d2/inspect)

Hope this help.

**Comment by andypple83** [comment]
We've updated our Google Lens document page to give more Knowledge Graph examples. Feel free to check it out. Best.

![Screenshot 2024-06-17 at 15 35 48](https://github.com/serpapi/public-roadmap/assets/99160364/6cf5d6f7-892e-46fa-b96c-96f3f57a1363)


Link: https://serpapi.com/google-lens-api

**Comment by hilmanski** [comment]
Another user confused about this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068600?view=List)
