### ISSUE TITLE
[Google search API] Wrong website URL on the Knowledge Graph

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1347]
A user reported that a knowledge graph result showing the wrong `website` information. The website link is coming from the `check availability` link.

The actual `website link` for this result should be: http://www.westdoverinn.com/

[Inspect](https://serpapi.com/searches/65a0375a18ca86bd2578ad57/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056925?view=List) | [Playground](https://serpapi.com/playground?q=west+dover+inn&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)

**Comment by schaferyan** [comment]
Just for clarity, this problem occurs for other Hotel Knowledge Graphs as well and is not a one-time issue:

<img width="969" alt="Screenshot 2024-01-12 at 10 07 37 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/7ece4075-2571-4cbd-b730-90b4a710da75">
<img width="966" alt="Screenshot 2024-01-12 at 10 07 22 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/977ed18c-9d40-4658-8a78-59a4e1665607">


[Inspect](https://serpapi.com/searches/65a0431e18ca8618c0fdcbf9/inspect)
