### ISSUE TITLE
[Google Play Product API] Same result on different county when sort by newest

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1349]
A user reported that Google Play Product API returns the same results when filtered by different countries and sorted by newest.

Upon visiting the pages and performing the same filter, the results are indeed the same as well. So, I'm not sure if it's something from the Google play itself, or there is a different parameter should be used to differentiate the country.

![CleanShot 2024-01-12 at 13 46 15@2x](https://github.com/serpapi/public-roadmap/assets/4522467/74322a1e-9bf7-4c53-8a1c-45d2506b57c8)

![CleanShot 2024-01-12 at 13 46 40@2x](https://github.com/serpapi/public-roadmap/assets/4522467/5017e260-bfc2-4ea5-a3e3-e8dae8177732)

[Playground for US](https://serpapi.com/playground?engine=google_play_product&product_id=com.google.android.youtube&gl=us&store=apps&all_reviews=true&platform=phone&sort_by=2) | [Playground for India](https://serpapi.com/playground?engine=google_play_product&product_id=com.google.android.youtube&gl=in&store=apps&all_reviews=true&platform=phone&sort_by=2) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056934?view=List) | [Inspect1](https://serpapi.com/searches/65a0c74e33b2366a93ff6ad9/inspect) | [Inspect2](https://serpapi.com/searches/65a0c735d036a74d121df517/inspect)

**Comment by schaferyan** [comment]
It looks like all Google Play reviews are available regardless of which country you are in.

The default sort order is "Most Relevant".  The `gl` parameter helps to determine which reviews are most relevant based on location and will change the sort order.

However, if you change the sort order to "Newest" it will display the reviews from newest to oldest, disregarding locale.

I'm closing this as our API already reflects the behavior of Google Play. We can re-open it if anyone presents an example indicating a different behavior of Google Play.
