### ISSUE TITLE
[Google Patents API] No `cpc` key is scraped for `organic_results`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1351]
One of our users noted that no `organic_results` return the `cpc` key. According to our documentation, this is one of the fields that should be returned. We should investigate if we can even scrape this endpoint, and if not, we should update the documentation to not mislead the customers.

Documentation:
<img width="1103" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/a22d95d5-a1b6-432f-9309-6644bce6d76b">

Example from the documentation:
<img width="515" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/14976a3a-ba3b-4ace-ad0f-8b3bd893e41a">

Live results:
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/bfd81de5-79f7-4623-8ec5-25aa8ca65bd6">

[Playground](https://serpapi.com/playground?engine=google_patents&q=Sony) | [Inspect](https://serpapi.com/searches/65a1684849ecdb809ff257b1/inspect) | [Documentation](https://serpapi.com/google-patents-api)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056932?view=List)

**Comment by schaferyan** [comment]
CPC doesn't seem to be provided by Google Patents for organic results, even on the patent details pages.

The most likely solution is just to remove these keys in our documentation.

**Comment by zyc9012** [comment]
@marm123 @schaferyan CPC is only returned when we set `clustered=true` in the request, or choose "Classification" in the playground

![image](https://github.com/serpapi/public-roadmap/assets/3034310/6f36e7bf-a74a-484d-b3b6-e386a975267b)
