### ISSUE TITLE
[Google Search API] `top_sights` are not returned

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1353]
A customer reported that the `top_sights` block is not returned for Google Search API:

<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/722cd5d5-4aea-4721-a680-e44a65903f70">

[Playground](https://serpapi.com/playground?q=Top+sights+London&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client) | [Inspect](https://serpapi.com/searches/65a4e9730ead41cfe8cd07d3/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000057038?view=List)

**Comment by hilmanski** [comment]
Another customer reported this

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000057219?view=List)

**Comment by andypple83** [comment]
Removed myself, anyoen feel free to pick this card. Will work on this card on tmr if no one picks. Thanks
