### ISSUE TITLE
[Google Maps Reviews API] Emoji is missing on reviews

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1354]
A user from Twitter reported that we're missing the emoji on our reviews Maps API.

[Sample Google Maps review page](https://www.google.com/maps/place/Game+Squad+NO/@60.3648249,5.434303,15.93z/data=!4m6!3m5!1s0x88f5a992231bb91:0x236d38572c95e1f2!8m2!3d60.3651855!4d5.4291706!16s%2Fg%2F11vd8wzs40?hl=no&entry=ttu)

![CleanShot 2024-01-16 at 07 40 11](https://github.com/serpapi/public-roadmap/assets/4522467/24550d56-4721-46f4-a4fd-9d7c17d72ee1)

The emoji's are missing on our API

[Playground](https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x88f5a992231bb91%3A0x236d38572c95e1f2&hl=en) | [Inspect](https://serpapi.com/searches/65a5c2304d443d118c0f0d07/inspect) | [Twitter DM](https://twitter.com/messages/) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000057140?view=List)

**Comment by zyc9012** [comment]
The source we are using replaced those emojis with spaces.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/26248624-9fd3-4a61-9fc6-2eb6eeb8c4e9)

**Comment by hartator** [comment]
> The source we are using replaced those emojis with spaces.

The proxy?

**Comment by zyc9012** [comment]
> The proxy?

No, the endpoint. We use a different endpoint from the Google page for easier scraping. Unfortunately, the endpoint seems to handle emojis incorrectly.

**Comment by hartator** [comment]
> No, the endpoint. We use a different endpoint from the Google page for easier scraping. Unfortunately, the endpoint seems to handle emojis incorrectly.

Do you think we should close this as a `wontfix` then or should we dig into it more?

**Comment by zyc9012** [comment]
I think it's a `wontfix` for now unless we decide to change the endpoint.
