### ISSUE TITLE
[Bing Search API] Link on organic results is broken

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1361]
A customer reported that the Bing search organic results returned a broken link.

I'm able to replicate this on our Playground
![CleanShot 2024-01-22 at 07 42 24](https://github.com/serpapi/public-roadmap/assets/4522467/39438b3a-3171-476d-a6ef-0a372157ee0b)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000057467?view=List) | [Inspect](https://serpapi.com/searches/65ac19abf05eb88fb3120ba3/inspect) | [Playground](https://serpapi.com/playground?engine=bing&q=reasonlabs+safer+web)

**Comment by tanys123** [comment]
It fixes by itself, [Inspect](https://serpapi.com/searches/65b0b82b5119a6beb95e9831/inspect)

If referring to the search conducted by the customer, it didn't have a valid link other than a `tracking_link`. When that happens, we [try to use](https://github.com/serpapi/SerpApi/pull/2977) `displayed_link` as `link`. It wouldn't work for this time as the displayed link is never complete. @kagermanov27 What do you think? Should we just not show `link`?

**Comment by hilmanski** [comment]
A customer just reported this issue as well.

![CleanShot 2024-01-31 at 13 03 53@2x](https://github.com/serpapi/public-roadmap/assets/4522467/608d957d-998d-4774-998c-0c7e9f0c5c81)


[Inspect](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000058052?view=List) | [Inspect](https://serpapi.com/searches/65b8e27a629a0126da009966/inspect)
