### ISSUE TITLE
[Dashboard] Typo in user avatar tooltip

### ISSUE THREAD

**Issue by ilyazub** [serpapi/public-roadmap#137]
The tooltip says "Run out of searches", it should say "Ran out of searches".

![image](https://user-images.githubusercontent.com/282605/166718962-2233b91c-4dfc-42cd-ad08-68dec8bb6fc2.png)

```diff
- Run out of searches
+ Ran out of searches
```

Migrated from the [thread on the old forum](https://forum.serpapi.com/bugs/p/website-typo-in-user-avatar-tooltip).

**Comment by hartator** [comment]
Fixed:
- https://github.com/serpapi/SerpApi/commit/f3bd4c7c3c398a3ecee58094507383cbbe090c1e
- https://github.com/serpapi/SerpApi/pull/3958
