### ISSUE TITLE
[Bing Search API] Empty results via SerpApi

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1374]
A user reported their search shows empty results when the actual Bing link can show it.

The search term is: `+"outin" &  (money laundering OR terrorism OR tax evasion OR illegal OR fraud OR scandal OR crime OR criminal OR sanctions OR laundered OR laundering OR corrupt OR corruption OR bribe OR bribery OR bribed OR prosecution OR prosecuted OR prosecution OR sanctioned OR OFAC OR elected OR investigation OR investigated OR minister OR defendant OR blacklist OR leader OR arms OR bearer share OR drug)`

I'm able to replicate this on our playground

[Playground](https://serpapi.com/playground?engine=bing&q=%2B%22outin%22+%26++(money+laundering+OR+terrorism+OR+tax+evasion+OR+illegal+OR+fraud+OR+scandal+OR+crime+OR+criminal+OR+sanctions+OR+laundered+OR+laundering+OR+corrupt+OR+corruption+OR+bribe+OR+bribery+OR+bribed+OR+prosecution+OR+prosecuted+OR+prosecution+OR+sanctioned+OR+OFAC+OR+elected+OR+investigation+OR+investigated+OR+minister+OR+defendant+OR+blacklist+OR+leader+OR+arms+OR+bearer+share+OR+drug)&location=United+Kingdom&first=1&count=5&safeSearch=off&filters=ex1%3A%22ez5_19748_19749%22) | [Inspect](https://serpapi.com/searches/65b4f75e29d1774b94bf8bbb/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000057865?view=List) | [Bing search result](https://www.bing.com/search?form=QBRE&q=%2B%22outin%22+%26++%28money+laundering+OR+terrorism+OR+tax+evasion+OR+illegal+OR+fraud+OR+scandal+OR+crime+OR+criminal+OR+sanctions+OR+laundered+OR+laundering+OR+corrupt+OR+corruption+OR+bribe+OR+bribery+OR+bribed+OR+prosecution+OR+prosecuted+OR+prosecution+OR+sanctioned+OR+OFAC+OR+elected+OR+investigation+OR+investigated+OR+minister+OR+defendant+OR+blacklist+OR+leader+OR+arms+OR+bearer+share+OR+drug%29&lq=0&first=1&count=5&safeSearch=off&filters=ex1:%22ez5_19748_19749%22&rdr=1)

**Comment by hartator** [comment]
This is working on our playground:

<img width="1504" alt="image" src="https://github.com/serpapi/public-roadmap/assets/307597/019077a9-f429-4475-b48b-24baed4e6bc0">

Note the date sensitiveness of the query: 

![image](https://github.com/serpapi/public-roadmap/assets/307597/0fad1fbd-79e9-4c0c-adcc-07cfa938b3cc)

This explains the randomness of the results. Some datacenters have the pages indexed yesterday or not. This is not something we can fix our side unfortunately. 

Feel free to add multiples screenshots to issues. This helps future debug.
