### ISSUE TITLE
[Bing Search API] Return highlighted word from the snippet

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1375]
An Enterprise Customer requested that the highlighted word be attached to the Bing result. Just like our Google search API

![CleanShot 2024-01-29 at 08 40 31](https://github.com/serpapi/public-roadmap/assets/4522467/f3f9d579-9b62-406e-8f68-8995d8cf9fb0)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000057864?view=List)

**Comment by aciddjus** [comment]
Thank you, @hilmanski 👍 

Make sure to add `status` badge to issues you open.

**Comment by btaunt** [comment]
This feature has been added. 

We now parse highlighted words as `snippet_highlighted_words` (if present) for Bing search results:

Desktop:
<img width="700" alt="Screenshot 2024-02-19 at 2 41 17 PM" src="https://github.com/serpapi/public-roadmap/assets/137819397/153af549-177b-402c-970c-dc71408c3cc2">

Mobile:
<img width="565" alt="Screenshot 2024-02-19 at 2 53 58 PM" src="https://github.com/serpapi/public-roadmap/assets/137819397/0e798df6-5d07-43f0-9e39-08f0a4a8b67e">

View live example: [Playground](https://serpapi.com/playground?engine=bing&q=Coffee)
