### ISSUE TITLE
[Bing Search API] Wrong `total_results` in Paginated Searches

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1380]
Paginated searches in Bing include an element displaying the range of results shown and the total number found. It appears in the format `[index of first result shown] - [index of last results shown] of [total number of results]`.

Currently, we are incorrectly parsing the index of the first result shown into the `total_results` key. 

<img width="730" alt="Screenshot 2024-01-30 at 12 42 24 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/e854813d-c682-447b-b2c3-078310c31213">

[Playground](https://serpapi.com/playground?engine=bing&q=Coffee&first=10) | [Inspect](https://serpapi.com/searches/65b95dacc504e9a672b88651/inspect)

**Comment by andypple83** [comment]
We've released a fix for this. The `total_results` should be correct now.

![image](https://github.com/serpapi/public-roadmap/assets/99160364/bc82dd98-ba4c-425a-b04a-ac499291eb59)
