### ISSUE TITLE
[Google Maps API] Parse Operating Hours from the HTML Body

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#139]
Currently the results support shown parts on the HTML. But deep in the HTML, there are parts that give information such as `Open 24 Hours`. We may be able to scrape them and serve them under a different key.

![arr](https://user-images.githubusercontent.com/73674035/167212463-69e54016-4d9c-47f1-8328-e3aa7f4af563.png)

[Inspect Link](https://serpapi.com/searches/62b355ce3e86ac89da767595/inspect)
[Playground Link](https://serpapi.com/playground?engine=google_maps&q=Keyword&ll=%4039.746214%2C-104.993489%2C21z&hl=en&type=search&no_cache=true)

**Comment by arusin-mind** [comment]
@kagermanov27 
'hours' param should be looks like 
```
[
{
friday: "6:30AM–5PM"
},
{
saturday: "7AM–5PM"
},
{
sunday: "7AM–5PM"
},
{
monday: "6:30AM–5PM"
},
{
tuesday: "6:30AM–5PM"
},
{
wednesday: "6:30AM–5PM"
},
{
thursday: "6:30AM–5PM"
}
],
```

Thanks
