### ISSUE TITLE
[Google Patents API] Generic URL returned in the response for `thumbnail` or `pdf` when they're not available

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1392]
A customer reported that they're receiving an error when trying to process the `thumbnail` URL for a patent entry in the `organic_results`. It seems that a generic https://patentimages.storage.googleapis.com/ URL is returned for the `thumbnail` or `pdf` fields when a thumbnail or a PDF file are not available for a patent.

<img width="1421" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/aedd5665-a4e0-457a-9e4a-61c777de85ab">

[Playground](https://serpapi.com/playground?engine=google_patents&num=10&sort=new&assignee=%22MGA+Thermal%22) | [Inspect](https://serpapi.com/searches/65bcb7e57690dc896cb648fb/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000058232?view=List)

**Comment by ilyazub** [comment]
This bug was fixed.

![image](https://github.com/serpapi/public-roadmap/assets/282605/3dd95642-9bd5-4c1b-8773-abb6e8483e34)
(ref: https://serpapi.com/playground?engine=google_patents&q=(Coffee)&sort=new)
