### ISSUE TITLE
[Google News API] Scrape Direct Links to Thumbnails

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1393]
We recently fixed support for scraping `thumbnail`s from Google News (https://github.com/serpapi/public-roadmap/issues/1350). However, the customer reported the images don't appear in the Playground iFrame (or the `raw_html_file`), or in their application using a method that previously worked.

According to [#4497](https://github.com/serpapi/SerpApi/pull/4497), the direct links aren't currently available in the HTML. I'm uncertain if there is another way to get these, but it would be helpful for the customer's use case if we can.

<img width="1457" alt="Screenshot 2024-02-02 at 10 11 58 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/61274e55-fb36-46d2-9225-e19256d10585">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056984?view=List) | [Playground](https://serpapi.com/playground?engine=google_news&q=dog&gl=us) | [Raw HTML File](https://serpapi.com/searches/d4fbe452fa7b0dd7/65bd2e49c47d3c92cdbb26ff.html)

**Comment by zyc9012** [comment]
The cause is that the browser automatically sends `sec-fetch-site: cross-site` HTTP header under `serpapi.com` domain, resulting in a 403 response.

**Comment by schaferyan** [comment]
Another customer asked for this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059528?view=List)
