### ISSUE TITLE
[Google Maps Reviews API] Next page token available when there is no more result

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1394]
Today, I discovered that a `next_page_token` is still returned even though there shouldn't be any more results on the next page.
It happens for example when the total reviews is 10.

![CleanShot 2024-02-05 at 16 23 49@2x](https://github.com/serpapi/public-roadmap/assets/4522467/53021fb9-24de-4778-8afd-dee2a94d6f50)

[Playground page 1](https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x2e68e76d48f39327%3A0x8a246ae3a0215553&hl=en) | [Inspect page 1](https://serpapi.com/searches/65c099dd87a0ee617843a743/inspect)
[Playground page 2](https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x2e68e76d48f39327%3A0x8a246ae3a0215553&hl=en&next_page_token=CAESBkVnSUlDZw%3D%3D) | [Inspect page 2](https://serpapi.com/searches/65c099f08cd8780bbcecf08a/inspect)

**Comment by zyc9012** [comment]
`next_page_token` is returned by Google and there's no indication if there's more data. So we can't do much about it on our side.
