### ISSUE TITLE
[FAQ] Spelling and grammar mistakes

### ISSUE THREAD

**Issue by ishiharaf** [serpapi/public-roadmap#1401]
I've noticed some spelling and grammar mistakes in the FAQs. It'd be nice to see them fixed.

## Spelling and grammar
[General](https://serpapi.com/faq/general) tab:
- Can I request that SerpApi adds an API for scraping some other search engine?
    - `adds` > `add`
    - Could be changed to `Can I request SerpAPI to add`
- I encountered an bug, where do I report it to get it fixed?
	- `an bug` > `a bug`
- We don't give access, sell, or share your data with any third party for any reason. Only exceptions are services needed to process your search [...]
	- `Only exceptions` > `The only exceptions`
- Location, language, and other paramters can affect what results are serverd even if the keyword [...]
	- `serverd` > `served`
- The best way to try and reproduce a search done with our API, is to follow the url for the search in the results JSON on an icognito mode browser. If you still see descripencies between the two after this [...]
	- `icognito` > `incognito`
	- `descripencies` > `discrepancies`

[Google > Search](https://serpapi.com/faq/google-search) tab:
- While Google likes to report millions or billions of total results, the actual number of results they server is generally around 350-450
	- `they server` > `they serve`

[Google > Shopping](https://serpapi.com/faq/google-shopping) tab:
- When you make a search with our Google Shopping API, you'll have a JSON selector for filters here you can find all [...]
	- `filters here` > `filters where`

[Google > Reverse Image](https://serpapi.com/faq/google-reverse-image) tab:
- SerpApi request the search engine results pages by URL and thus all of the parameters we are are the search engine's own URL parameters.
	- `SerpApi request` > `SerpApi requests`
	- `parameters we are` > `parameters we have`?
- [...] the only way we're able to pass an image to Google for the reverse image search, is with the image_url parameter that requires the image be submitted via URL.
	- `for the reverse` > `for reverse`
	- `be submitted` > `to be submitted`

[Baidu](https://serpapi.com/faq/baidu) tab:
- Baidu allows up to 50 results to be shown on a single results page with it's rn parameter. If you submit a rn value higher than 50, Baidu will serve the default 10 results instead.
	- `with it's rn` > `with its rn`
	- `a rn value` > `an rn value`

## Notes
- Usage of commas could be improved, mainly with `and`, `but`, and `or`.
- Some sentences could be rewritten for clarity. For example: "[...] we can set up a yearly option upon request manually at contact@serpapi.com" could be written as "we can manually set up a yearly option upon request at contact@serpapi.com".

**Comment by schaferyan** [comment]
Thank you for spotting this @ishiharaf. We already have a PR open to fix typos, I'll make sure these are addressed as well.

**Comment by ishiharaf** [comment]
Thanks for the reply @schaferyan. I'll let you know if I find anything else.
