### ISSUE TITLE
[Google Search API] Scrape `Events` section in the `knowledge_graph`

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1403]
A high volume customer requested that we scrape the `Events` section in the `knowledge_graph`:

<img width="1426" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/115bc325-e3f5-407e-a527-8a53cc5b9161">

[Playground](https://serpapi.com/playground?q=webster+hall&location=Austin%2C+Texas%2C+United+States&ludocid=ChIJaXQRs6lZwokRY6EFpJnhNNE&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/65c60b9ee0ded409fb6a5ab1/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000058763?view=List)

**Comment by btaunt** [comment]
This ticket is now resolved. SerpApi properly renders the newer `events` layout in Google `knowledge_graph`.

[Playground Example
](https://serpapi.com/playground?q=webster+hall&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true&google_domain=google.com&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+votes+site+ie+oe+pws+ibp+source)
<img width="647" alt="Screenshot 2024-03-12 at 11 05 19 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/c2c5b07e-aed6-4402-882e-c1fe05e9b8b2">


You can also find updated documentation: [SerpApi Google Knowledge Graph Docs](https://serpapi.com/knowledge-graph#api-examples-results-for-webster-hall)
