### ISSUE TITLE
[Google Search API] Top Stories not showing up during the Super Bowl on mobile and tablet

### ISSUE THREAD

**Issue by newzdashowner** [serpapi/public-roadmap#1404]
The `top_stories` are not scraped on `mobile` and `tablet`.

![image](https://github.com/serpapi/public-roadmap/assets/61591980/00cca44d-b4a7-455a-988e-efec65678bba)

[Playground - tablet](https://serpapi.com/playground?q=super+bowl&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=tablet) | [Inspect - tablet](https://serpapi.com/searches/65c9b967ca968fd66f916f74/inspect)
[Playground - mobile](https://serpapi.com/playground?q=super+bowl&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile) | [Inspect - mobile](https://serpapi.com/searches/65c9b919a1b4231465ea7a84/inspect)

**Comment by newzdashowner** [comment]
it is completely missing 
this is the super bowl and it should be fixed asap

**Comment by hilmanski** [comment]
An important customer reported the top_stories results are missing in the mobile and tablet devices.

[Inspect](https://serpapi.com/searches/65c959d58b7ed24641d25082/inspect) | [Playground](https://serpapi.com/playground?q=super+bowl&gl=us&hl=en&device=mobile&google_domain=google.com&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+votes+site) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000037494?view=List)
