### ISSUE TITLE
[Google Images API] Scrape all results from the first page

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1405]
A customer requested that we scrape all results from Google Images. We can also check and see if the `filter` parameter is applicable to Google Images (it is in our documentation). No matter what `filter` value we provide, the results are the same.

<img width="1675" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/849e5298-df7b-4d5e-b63c-e4ce0a20531c">

<img width="1668" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/f6ea9d97-83fe-4829-a674-4d4e6366bbc0">

[Playground](https://serpapi.com/playground?engine=google_images&q=Peel+garlic+with+microwave+Peel+inurl%3Aredd.it&gl=us&hl=en&filter=0) | [Inspect](https://serpapi.com/searches/65c9e6487d171aa7478a14bf/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000058859?view=List)

**Comment by aciddjus** [comment]
This is not related to the `filter` parameter. Results are returned, just hidden.

**Comment by marm123** [comment]
Got it. I'll investigate the `filter` issue further, as it looks like it has no effect anyway, so we might potentially disable it and remove it from the documentation if that's the case not to confuse users.

However, I'll need to check some more examples, to make sure this is the case.

Thank you @aciddjus

**Comment by aciddjus** [comment]
Thank you, @marm123 👍 

I tried a couple of examples but couldn't find one where `filter` has an effect. 

If you confirm we can probably retire it.
