### ISSUE TITLE
[Google Maps API] No results returned in the response

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1409]
A customer reported that Google Maps API is not returning results, but the actual Google Maps engine does return results with the same GPS coordinates. I was able to reproduce it in our Playground with multiple different locations.

New York - `@40.7127837,-74.0059413`

![image](https://github.com/serpapi/public-roadmap/assets/144151895/5874b394-bdc0-498f-81c3-0540ac20f777)

[Playground](https://serpapi.com/playground?engine=google_maps&q=Coffee&ll=%4040.7127837%2C-74.0059413%2C14z&hl=en&type=search) | [Inspect](https://serpapi.com/searches/65ccbf861c450a29d2b33d87/inspect)

![image](https://github.com/serpapi/public-roadmap/assets/144151895/a1a50dec-988b-4c2f-a367-3028386b39cf)

[Google Maps](https://www.google.com/maps/search/Coffee/@40.7127837,-74.0059413,14z)

Denver -` @39.7392358,-104.990251,14z`

<img width="1366" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/4ce7241c-8e46-4526-9795-d933363ae660">

[Playground](https://serpapi.com/playground?engine=google_maps&q=Coffee&ll=%4039.7392358%2C-104.990251%2C14z&hl=en&type=search) | [Inspect](https://serpapi.com/searches/65ccbdf166440a0d3b93b37a/inspect)

<img width="1322" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/d4d76432-c63b-469b-8aea-5586f2ce1c75">

[Google Maps](https://www.google.com/maps/search/Coffee/@39.7392358,-104.990251,14z)

London - `@51.5073509,-0.1277583,14z`

<img width="1369" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/80f6a5e2-8295-4e65-b3f5-33a6855bdeeb">

[Playground](https://serpapi.com/playground?engine=google_maps&q=Coffee&ll=%4051.5073509%2C-0.1277583%2C14z&hl=en&type=search) | [Inspect](https://serpapi.com/searches/65ccc0923bea7bb1b9cd2ff1/inspect)

![image](https://github.com/serpapi/public-roadmap/assets/144151895/3254161c-5f0a-49dc-8b5a-3300c3afd712)

[Google Maps](https://www.google.com/maps/search/Coffee/@51.5073509,-0.1277583,14z)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000058658?view=List)

**Comment by martin-serpapi** [comment]
Another important customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059053?view=List)

**Comment by aciddjus** [comment]
Closing this as resolved.
