### ISSUE TITLE
[Google Local API] No results returned in the response

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1410]
A customer reported that our Google Local API does not return results in the response. I was able to reproduce it with multiple different locations.

![image](https://github.com/serpapi/public-roadmap/assets/144151895/839cb554-c39b-4818-9506-69aed7f7b92e)

[Playground](https://serpapi.com/playground?engine=google_local&q=Coffee&location=Denver%2C+Colorado%2C+United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/65ccc5d59bddf75debd7edd1/inspect)

![image](https://github.com/serpapi/public-roadmap/assets/144151895/62843479-ce3e-4dcf-811a-72d759a18527)

[Playground](https://serpapi.com/playground?engine=google_local&q=Coffee&location=New+York%2C+New+York%2C+United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/65ccc68349ecdbeff5af1dea/inspect)

![image](https://github.com/serpapi/public-roadmap/assets/144151895/190972fa-f9e0-485c-a32b-490d208b04a2)

[Playground](https://serpapi.com/playground?engine=google_local&q=Coffee&location=Los+Angeles%2C+CA%2C+California%2C+United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/65ccc6761baebbde38f1d9cf/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059050?view=List)

**Comment by aciddjus** [comment]
The same query `mcdonald's`
- [Has results](https://serpapi.com/searches/65cce1f1f21801b6e2d44e48/inspect)
- [Empty results](https://serpapi.com/searches/65cce22a224db161e3771408/inspect)
