### ISSUE TITLE
[Google Patent API] Support Multiple Queries

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1411]
A customer is trying to use SerpApi to perform more complex Google Patent queries.

They are using "+" to append multiple CPCs to a text query (with multiple AND and OR operators). While I couldn't find official support for this, it does seem to work when using Google Patents directly, but not when using our Google Patents API.

When using our API, the "invalid argument: query syntax error" error is returned.

Google seems to separate it into two queries, which is also the same behavior as when adding multiple search terms in the Google Patents sidebar.

Currently, our API doesn't seem to support multiple queries. Adding support for multiple queries would allow the customer to process these more complex Google Patent searches.

<img width="1110" alt="Screenshot 2024-02-14 at 11 42 55 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/8eb8a122-4676-416c-85af-4e8293ff0c75">

<img width="1160" alt="Screenshot 2024-02-14 at 11 43 47 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/8d7fef5b-9325-4797-af8c-8ef33d0352e2">

[Google Patents](https://patents.google.com/?q=((diffusion+OR+%C3%A9mission+OR+lib%C3%A9ration)+AND+(odeur+OR+parfum+OR+fragrance)+AND+(haut-parleur+OR+enceinte+OR+audio)+AND+(coupl%C3%A9+OR+combin%C3%A9+OR+int%C3%A9gr%C3%A9))&q=(A61L+OR+H04R+OR+G10K)&oq=((diffusion+OR+%C3%A9mission+OR+lib%C3%A9ration)+AND+(odeur+OR+parfum+OR+fragrance)+AND+(haut-parleur+OR+enceinte+OR+audio)+AND+(coupl%C3%A9+OR+combin%C3%A9+OR+int%C3%A9gr%C3%A9))%2b+cpc:(A61L+OR+H04R+OR+G10K)) | [Playground](https://serpapi.com/playground?engine=google_patents&q=((diffusion+OR+%C3%A9mission+OR+lib%C3%A9ration)+AND+(odeur+OR+parfum+OR+fragrance)+AND+(haut-parleur+OR+enceinte+OR+audio)+AND+(coupl%C3%A9+OR+combin%C3%A9+OR+int%C3%A9gr%C3%A9))%2B+cpc%3A(A61L+OR+H04R+OR+G10K)) | [Search Inspector](https://serpapi.com/searches/65ccf38e0b50626a07e83fc1/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059065?view=List)

**Comment by zyc9012** [comment]
Supported using semicolon `;` to separate multiple search queries

The results are identical.

[Google Patents](https://patents.google.com/?q=((diffusion+OR+%C3%A9mission+OR+lib%C3%A9ration)+AND+(odeur+OR+parfum+OR+fragrance)+AND+(haut-parleur+OR+enceinte+OR+audio)+AND+(coupl%C3%A9+OR+combin%C3%A9+OR+int%C3%A9gr%C3%A9))%2b&q=(A61L+OR+H04R+OR+G10K))

![image](https://github.com/serpapi/public-roadmap/assets/3034310/1f5b0998-9474-4151-b152-178ad331b29a)


[SerpApi Playground](https://serpapi.com/playground?engine=google_patents&q=((diffusion+OR+%C3%A9mission+OR+lib%C3%A9ration)+AND+(odeur+OR+parfum+OR+fragrance)+AND+(haut-parleur+OR+enceinte+OR+audio)+AND+(coupl%C3%A9+OR+combin%C3%A9+OR+int%C3%A9gr%C3%A9))%2B%3B(A61L+OR+H04R+OR+G10K))

![image](https://github.com/serpapi/public-roadmap/assets/3034310/c901634d-3d72-4033-b3ed-6ec9a1e75569)
