### ISSUE TITLE
[Google Search API] Places Sites is not parsing

### ISSUE THREAD

**Issue by RedBillyOne** [serpapi/public-roadmap#1414]
[@ilyazub](https://github.com/ilyazub),

Serpapi seems not to parse data from the “Place Sites” blocké

![image](https://github.com/serpapi/public-roadmap/assets/152279883/bbd19791-ef17-4141-a73c-aadce298d830)

[Search Inspector](https://serpapi.com/searches/65ce450ed3aba2f3742bae1c/inspect) | [Playground](https://serpapi.com/playground?q=paris&location=Neuilly-sur-Seine%2C+Ile-de-France%2C+France&google_domain=google.fr&gl=fr&hl=fr)

Is it possible to correct this point ?

regards

**Comment by ilyazub** [comment]
@RedBillyOne Thanks for this feature request. We will update this issue when we start working on it.

**Comment by RedBillyOne** [comment]
@ilyazub 
Just for information, is this a request that can actually be processed? This “Place Sites” block is now present in the results pages in Europe, especially because of the lawsuit lost by Google (GDPR). Do you just have an idea of ​​the possible processing date?

**Comment by RedBillyOne** [comment]
@ilyazub do you have an estimate of when this feature will be added?
This is an important block (sites de lieux) that would be very useful to be able to recover
![image](https://github.com/serpapi/public-roadmap/assets/152279883/b0614e12-f919-4b00-988f-0c4a11dc3eb7)
https://serpapi.com/playground?q=restaurant+rungis&location=France&google_domain=google.fr&gl=fr&hl=fr&newPara=chips

**Comment by hartator** [comment]
@RedBillyOne It's unfortunately hard to provide ETA on new engineering work.
