### ISSUE TITLE
[Google Shopping API] Include filters input type in the response

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1415]
A user requested that we include the input type for filters returned in the response. For example, some filters are radio buttons and others are checkboxes.

<img width="1338" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/c3f660c5-77d2-4267-88a6-827d26562f6f">

[Playground](https://serpapi.com/playground?engine=google_shopping&q=Coffee) | [Inspect](https://serpapi.com/searches/65cdff501baebbc888159c95/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000059171?view=List)

**Comment by Ovi** [comment]
We now include input type as `input_type`:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/eaa5d109-1285-442e-89ce-624bacc14760">
