### ISSUE TITLE
[Google Ads Transparency Center API] Extract results that required login

### ISSUE THREAD

**Issue by tenhoudaisangen** [serpapi/public-roadmap#1419]
Not Working Example: [[Playground Link 1]](https://serpapi.com/playground?engine=google_ads_transparency_center&text=truthfinder.com&region=2840&start_date=20240101&end_date=20240215&creative_format=text) [[Working in ATC 1]](https://adstransparency.google.com/?region=US&start-date=2024-01-01&end-date=2024-02-15&format=TEXT&domain=truthfinder.com) [[Playground Link 2]](https://serpapi.com/playground?engine=google_ads_transparency_center&text=mysticmag.com&region=2840&start_date=20240101&end_date=20240215&creative_format=text) [[Working in ATC 2]](https://adstransparency.google.com/?region=US&start-date=2024-01-01&end-date=2024-02-15&format=TEXT&domain=mysticmag.com)

Working Example: [[Working Example 1]](https://serpapi.com/playground?engine=google_ads_transparency_center&text=apple.com&region=2840&start_date=20240101&end_date=20240215&creative_format=text) [[Working Example 2]](https://serpapi.com/playground?engine=google_ads_transparency_center&text=nomnomnow.com&region=2840&start_date=20240101&end_date=20240215&creative_format=text)

Some domains when placed in the `text` field causes the Google Ad Transparency Center API to return `fully empty` even though there is a working version of the same query when going directly to https://adstransparency.google.com/

**Comment by tanys123** [comment]
Thanks @tenhoudaisangen for reporting the issue 👍 

After some investigation, some ads like ([truthfinder.com](https://adstransparency.google.com/?region=US&start-date=2024-01-01&end-date=2024-02-15&format=TEXT&domain=truthfinder.com)) required login to view them. You can try the link in incognito mode, and there will be no ads.

<img width="1451" alt="Screenshot 2024-02-16 at 2 09 23 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/2f649c64-0b96-4819-9fe6-9501299f73ed">

I can make it work as a prototype (by using cookies) but haven't yet found a viable solution for production. I will let you know if there is an update on this.

**Comment by alexbarron** [comment]
Received another request:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072608?view=List)

**Comment by hartator** [comment]
We can't do this legally if it's behind a login page.

**Comment by alexbarron** [comment]
> We can't do this legally if it's behind a login page.

Yep, I set that expectation with the user already, but logged it here anyway since there's an open issue. Sounds like it would make sense to close this as unplanned?

**Comment by hartator** [comment]
> Yep, I set that expectation with the user already, but logged it here anyway since there's an open issue. Sounds like it would make sense to close this as unplanned?

Yes, we can double check their ToS, but usually it means we can't scrape data behind a login wall.
