### ISSUE TITLE
[Google Search API] Web stories (Visual Stories) not captured

### ISSUE THREAD

**Issue by githubfan21** [serpapi/public-roadmap#142]
https://serpapi.com/searches/627a8f259c449ddfcc200f3e/inspect

![image](https://user-images.githubusercontent.com/15785331/167708096-a8da07b3-7a1c-45d6-87dd-7ff0135a5150.png)

**Comment by kagermanov27** [comment]
Duplicate of https://github.com/serpapi/public-roadmap/issues/150
