### ISSUE TITLE
[Google Search tbs News] Result for complex query and filter not correct

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1420]
A customer got a wrong result displayed on the Google search with tbs=news. 

Expected result: 
![CleanShot 2024-02-16 at 10 30 17](https://github.com/serpapi/public-roadmap/assets/4522467/51a688fb-3358-4be4-a617-e16b940a3068)

SerpApi current behavior:
![CleanShot 2024-02-16 at 10 31 16](https://github.com/serpapi/public-roadmap/assets/4522467/d82317bc-cdf9-4327-a058-929e8786f5f8)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059181?view=List) | [Playground](https://serpapi.com/playground?q=%22PLBY+Group%22+site%3Ahttps%3A%2F%2Fwww.csmonitor.com%2FWorld+OR+site%3Ahttps%3A%2F%2Fwww.brookings.edu%2Fprograms%2Fforeign-policy%2Fabout%2F+OR+site%3Ahttps%3A%2F%2Fwww.easternherald.com%2F+OR+site%3Ahttps%3A%2F%2Finternewscast.com%2F+OR+site%3Ahttps%3A%2F%2Finsidexpress.com%2F+OR+site%3Ahttps%3A%2F%2Fwww.sec.gov%2Fpage%2Fnews%2F+OR+site%3Ahttps%3A%2F%2Fwww.seattletimes.com%2Fnation-world%2F&hl=en&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2023%2Ccd_max%3A02%2F15%2F2024%2Csbd%3A1&filter=0&tbm=nws&num=100&google_domain=google.com&filter=0&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+votes+site) | [Google URL](https://www.google.com/search?q=%22PLBY+Group%22+site%3Ahttps%3A%2F%2Fwww.csmonitor.com%2FWorld+OR+site%3Ahttps%3A%2F%2Fwww.brookings.edu%2Fprograms%2Fforeign-policy%2Fabout%2F+OR+site%3Ahttps%3A%2F%2Fwww.easternherald.com%2F+OR+site%3Ahttps%3A%2F%2Finternewscast.com%2F+OR+site%3Ahttps%3A%2F%2Finsidexpress.com%2F+OR+site%3Ahttps%3A%2F%2Fwww.sec.gov%2Fpage%2Fnews%2F+OR+site%3Ahttps%3A%2F%2Fwww.seattletimes.com%2Fnation-world%2F&oq=%22PLBY+Group%22+site%3Ahttps%3A%2F%2Fwww.csmonitor.com%2FWorld+OR+site%3Ahttps%3A%2F%2Fwww.brookings.edu%2Fprograms%2Fforeign-policy%2Fabout%2F+OR+site%3Ahttps%3A%2F%2Fwww.easternherald.com%2F+OR+site%3Ahttps%3A%2F%2Finternewscast.com%2F+OR+site%3Ahttps%3A%2F%2Finsidexpress.com%2F+OR+site%3Ahttps%3A%2F%2Fwww.sec.gov%2Fpage%2Fnews%2F+OR+site%3Ahttps%3A%2F%2Fwww.seattletimes.com%2Fnation-world%2F&hl=en&num=100&tbm=nws&tbs=cdr:1,cd_min:01/01/2023,cd_max:02/15/2024,sbd:1&filter=0&sourceid=chrome&ie=UTF-8) | [Inspect](https://serpapi.com/searches/65cec75595bf926f4bb62f84/inspect)

**Comment by aciddjus** [comment]
The reason for the difference is that the location is not set.

If I set the location to my own country (`gl=rs`)

[Inspect](https://serpapi.com/searches/65cf4982b5961e82a2ca9801/inspect) | [Playground](https://serpapi.com/playground?q=%22PLBY+Group%22+site%3Ahttps%3A%2F%2Fwww.csmonitor.com%2FWorld+OR+site%3Ahttps%3A%2F%2Fwww.brookings.edu%2Fprograms%2Fforeign-policy%2Fabout%2F+OR+site%3Ahttps%3A%2F%2Fwww.easternherald.com%2F+OR+site%3Ahttps%3A%2F%2Finternewscast.com%2F+OR+site%3Ahttps%3A%2F%2Finsidexpress.com%2F+OR+site%3Ahttps%3A%2F%2Fwww.sec.gov%2Fpage%2Fnews%2F+OR+site%3Ahttps%3A%2F%2Fwww.seattletimes.com%2Fnation-world%2F&gl=rs&hl=en&tbs=cdr%3A1%2Ccd_min%3A01%2F01%2F2023%2Ccd_max%3A02%2F15%2F2024%2Csbd%3A1&filter=0&tbm=nws&num=100&google_domain=google.com&no_cache=true)

<img width="2558" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/7a6d727a-0d8d-49af-99ca-5c3d3d60c4eb">

The results will match the live Google page I open on my side.

![image](https://github.com/serpapi/public-roadmap/assets/6929257/a9fbbe6c-a301-4a84-bac6-794f4770e1e2)

**Comment by aciddjus** [comment]
Closing this as not an issue. Feel free to re-open if we missed something.
