### ISSUE TITLE
[Google Lens Image Sources API] Playground example returns no results

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1422]
A user reported that the example from our Google Lens Image Sources API on Playground returns no results. This is because the `page_token` used from the Google Lens API example changed and is no longer valid:

Invalid search:
<img width="1674" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/8a21be92-1b47-4e54-96d6-d39ee987c084">

Valid search with new `page_token`:
<img width="1675" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/93cdd812-085c-4805-a3c5-b7c2953e1b6f">

[Playground - invalid](https://serpapi.com/playground?engine=google_lens_image_sources&page_token=YmE1MTU3NTgtZDdmZi00YjU0LWFmMDAtNmI2N2IxOGM3OWVh) | [Playground - valid](https://serpapi.com/playground?engine=google_lens_image_sources&page_token=YWVlYzVhYzQtMjFjOC00ODZjLTg0OGMtMjdiMTgzZGI1OTY3)

**Comment by hartator** [comment]
We have released a fix for https://serpapi.com/playground?engine=google_lens_image_sources:

![image](https://github.com/serpapi/public-roadmap/assets/307597/7ac4279f-ea35-4fc6-9a5c-d76df1dd35c3)
