### ISSUE TITLE
[Yandex Search API] Search take too long and sometimes it timeout

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1424]
A high-volume customer reported that Yandex Search sometimes takes too long if it does not return a timeout error.

<img width="1139" alt="image" src="https://github.com/serpapi/public-roadmap/assets/4522467/28cb75df-b7f9-4def-9bca-a10f7fdec0b5">

Some inspect links:
[Inspect: timeout](https://serpapi.com/searches/65d40b611baebba88742b159/inspect)
[Inspect: timeout](https://serpapi.com/searches/65d40b23defa13e0fe07c016/inspect)
[Inspect](https://serpapi.com/searches/65d408ef7d171a03787d96b7/inspect)

I'm able to replicate this as well. Performing a search on Yandex currently takes 30+ seconds:
[Inspect 80s](https://serpapi.com/searches/65d40aa89c449de05b47fa9c/inspect)
[Inspect 40s](https://serpapi.com/searches/65d40a7892564187ccc82e85/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059457?view=List)

**Comment by kagermanov27** [comment]
I am closing this issue again. The reporting customer has a separate problem, and it is covered in  https://github.com/serpapi/public-roadmap/issues/1461. Let's keep this issue for failures for similar cases like the initial request.

**Comment by marm123** [comment]
Ahh, that makes sense. Thank you, @kagermanov27, and sorry for opening it too fast!
