### ISSUE TITLE
[Yandex Search API] couldn't get valid results for search

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1425]
A high-volume customer reported that some results are not returning data.
While accessing the link directly can return this result [Yandex search page link](https://yandex.ru/search/?text=%26%231076%3B%26%231086%3B%26%231089%3B%26%231090%3B%26%231072%3B%26%231074%3B%26%231082%3B%26%231072%3B%26%2332%3B%26%231042%3B%26%231086%3B%26%231079%3B%26%231084%3B%26%231086%3B%26%231078%3B%26%231085%3B%26%231086%3B%26%2332%3B%26%231083%3B%26%231080%3B%26%2332%3B%26%231086%3B%26%231087%3B%26%231083%3B%26%231072%3B%26%231090%3B%26%231072%3B%26%2332%3B%26%231087%3B%26%231088%3B%26%231080%3B%26%2332%3B%26%231087%3B%26%231086%3B%26%231083%3B%26%231091%3B%26%231095%3B%26%231077%3B%26%231085%3B%26%231080%3B%26%231080%3B%26%2332%3B%26%231075%3B%26%231088%3B%26%231091%3B%26%231079%3B%26%231072%3B%26%2363%3B&p=4&lr=213)

I tried to replicate this issue, but I got a different result. I think it's a system from Yandex to prevent the search
![CleanShot 2024-02-20 at 10 45 00@2x](https://github.com/serpapi/public-roadmap/assets/4522467/023953f6-e5dd-44b0-aa2d-f5f9deab69be)
[My inspect page](https://serpapi.com/searches/65d4110ac47d3c05e9dffad0/inspect)

It could be related to this timeout issue as well: https://github.com/serpapi/public-roadmap/issues/1424

[Inspect](https://serpapi.com/searches/65d40aae0ead41e0f61a94e9/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059461?view=List) | [Playground](https://serpapi.com/playground?engine=yandex&text=доставка+Возможно+ли+оплата+при+получении+груза&yandex_domain=yandex.ru&lr=213&p=4)

**Comment by ilyazub** [comment]
We will add support for detecting several Yandex Captcha types.
