### ISSUE TITLE
[Google Maps Photos API] No results returned in the response for all searches

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1427]
A high volume customer reported that our Google Maps Photos API doesn't seem to return any results for any data_id. I was able to reproduce it in our Playground.

![image](https://github.com/serpapi/public-roadmap/assets/144151895/bf7c9452-041e-4653-b2f9-751abfca203c)

[Playground](https://serpapi.com/playground?engine=google_maps_photos&data_id=0x89c2591d4b919c2d%3A0xa7a1d8587c265503&hl=en) | [Inspect](https://serpapi.com/searches/65d72173c504e929c28bbfa8/inspect)

![image](https://github.com/serpapi/public-roadmap/assets/144151895/e4ff2243-7b90-4c3d-a43a-9e6a9972c181)

[Playground](https://serpapi.com/playground?engine=google_maps_photos&data_id=0x89c25855c5372c47%3A0xb01f497d2e67790e&hl=en) | [Inspect](https://serpapi.com/searches/65d7218cef7ddada571bc508/inspect)

![image](https://github.com/serpapi/public-roadmap/assets/144151895/ac545766-115e-442e-a268-3d9bb3c41ccb)

[Playground](https://serpapi.com/playground?engine=google_maps_photos&data_id=0x89c250b236697771%3A0xcdf5d24e19e12b5b&hl=en) | [Inspect](https://serpapi.com/searches/65d7220018ca860bbbc9cd4a/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000021857?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059684?view=List)

**Comment by aciddjus** [comment]
The issue has been resolved.

Google Maps Photos API is now returning all results. 

<img width="1633" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/aa8a1a57-aedd-4dc7-8d57-f0d2ae311150">

---------------

[Playground link](https://serpapi.com/playground?engine=google_maps_photos&data_id=0x89c259a61c75684f%3A0x79d31adb123348d2&hl=en&no_cache=true)
