### ISSUE TITLE
[Google Lens API] Scrape stock status

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1429]
A high volume customer requested that we scrape the stock status which is available for some results from Google Lens.

<img width="1428" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/9ea95bf6-e0d5-482f-9aca-2c87f62c2630">

[Playground](https://serpapi.com/playground?engine=google_lens&url=https%3A%2F%2Fimages.urbndata.com%2Fis%2Fimage%2FUrbanOutfitters%2F53946760_107_b%3F%24xlarge%24%26fit%3Dconstrain%26qlt%3D80%26wid%3D640&hl=en&country=us) | [Inspect](https://serpapi.com/searches/65d79d69ef7dda23af8d044e/inspect)

<img width="1429" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/4e61898b-12fa-472a-b6ce-0168c5c7c788">

[Google Lens Search](https://lens.google.com/search?ep=gsbubu&hl=en&re=df&p=AbrfA8p5Pe2H66oOukF80IsmLL30q-hhuztVH-9q43CYxvmEsIfdpeHiOK4ie3e5bcHCGDDRkvTOb5Z9qnzn6XLSxsb9_Rz1hfseyS0JClUuuCFt8NsrHLeBmEjNPB-JUqg42dLr25cCfQ3NPt39BzAj0AoP83emEmnS0EssbBK35VEIgi8lABEYFeu2ZWXrr5eJDEkel52egd160w%3D%3D#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKRGt6TkdFNU5UTTNMV00yWm1JdE5EY3haaTA1TlRFNUxUZzBaREkwWkRabU5HRTRZaElmVlRCaVZtRmxiblJ0U2tsV2MwNXBYM3AxVm1GWlRWZzNVeTF6YWpOU1p3PT0iXQ==)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000059697?view=List)

**Comment by i8ramin** [comment]
commenting to be notified. thx
