### ISSUE TITLE
[Bing Search API] Pagination incrementing wrong `next` page value

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#143]
Bing pagination is incrementing wrong `first=` values. It never exits the while loop because it paginates to the next page and then to the previous.

Playground link: https://serpapi.com/playground?engine=bing&q=minecraft+redstone&first=335

While at `first=335` (page 23), `"next"` key says that the next page is `first=321` which is a previous page number. It happens both in `pagination` and `serpapi_pagination`. 

![image](https://user-images.githubusercontent.com/78694043/167803949-f980c40f-61ed-4bc0-92d4-b2a3cf94a52c.png)

___

I tried to make it work with two approaches.

`if "next" in results.get("pagination", {})`:

```python
# never exits the while loop because paginates to the next 
# and then to the previous page at some moment

while True:
    results = search.get_dict()
    # ....
    if "next" in results.get("pagination", {}):
        search.params_dict.update(dict(parse_qsl(urlsplit(results.get("pagination", {}).get("next_link")).query)))
    else:
        break
```

Incrementing `first=` params value manually (_worked_):

```python

params = {
  "api_key": "...",
  "engine": "bing",
  "q": "minecraft redstone",
  "first": 11 👈👈👈👈
}

while True:
    results = search.get_dict()

    if "error" in results:
        print(results["error"])
        break
    # ....
    params["first"] += 11 👈👈👈👈
```

`pages = search.pagination()` stops at some point and hangs.

**Comment by ilyazub** [comment]
For me, Bing increments 14 results per page.

![image](https://user-images.githubusercontent.com/282605/168830585-22e99111-704b-4144-9920-9acc6c4c6801.png)

`first=231` &mdash; 18th page

https://serpapi.com/playground?engine=bing&q=minecraft+redstone&first=231

![image](https://user-images.githubusercontent.com/282605/168831038-6a2c30c1-2d85-4a09-9550-0b24b52576e7.png)

When `first` (result offset) is greater than the last result index, Bing displays some of the previous pages (similar to Google)

https://serpapi.com/playground?engine=bing&q=minecraft+redstone&location=United+States&first=290

![image](https://user-images.githubusercontent.com/282605/168831781-1987eb87-4be5-4bf7-b6e6-4d2d4f87a2db.png)

Repeating with different `first` displays the further page: https://serpapi.com/playground?engine=bing&q=minecraft+redstone&location=United+States&cc=US&first=385

I wasn't able to go after the 26th page.

**Comment by dimitryzub** [comment]
Thank you for the additional explanation 👍🏻 I'll then close this issue for now.
