### ISSUE TITLE
[Yelp Search API] `serpapi_pagination` Missing from a Specific Page of Results

### ISSUE THREAD

**Issue by nathaneidelson** [serpapi/public-roadmap#1432]
I came across a specific page that is page 13/24 on yelp, yet the json response has no key for `serpapi_pagination`. It worked well on all prior pages but seemed to break here. The specific url is https://www.yelp.com/search?find_desc=Solar+Installation&find_loc=San+Francisco%2C+CA&start=120&sortby=review_count

<img width="1876" alt="image" src="https://github.com/serpapi/public-roadmap/assets/3599948/0f0afc32-b3c8-4736-9b6b-0d303b43a96b">

**Comment by schaferyan** [comment]
The pages all seem to be available via `start`:

https://serpapi.com/playground?engine=yelp&find_desc=Solar+Installation&find_loc=San+Francisco%2C+CA&sortby=review_count&start=230&no_cache=true

And subsequent pages have serpapi_pagination.next, it is just specifically page 13 that is missing it.

[Search Inspector ](https://serpapi.com/searches/65d8f2b8d5ecf4f75e59b285/inspect)

**Comment by schaferyan** [comment]
The customer provided another example, this time it is the 7th page missing the `serpapi_pagination` key:

[Inspector](https://serpapi.com/searches/65d93ddd1e803f009a67191a/inspect)

**Comment by zyc9012** [comment]
We've fixed the missing pagination and enriched it.

Now the pagination looks like this.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/d9361cec-8edf-4194-af9c-d61eef5a4915)
