### ISSUE TITLE
[Google Images API] Delayed Response times 

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1433]
A customer reported Google Images API responses are currently sometimes much slower than usual. This is confirmed by our status graph:

<img width="1057" alt="Screenshot 2024-02-23 at 2 26 54 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/adafb32a-0644-434e-87e3-40da283c15d3">

AS @ritu1337 noted, this seems to have the same cause as https://github.com/serpapi/public-roadmap/issues/1407. It may also be fixed by https://github.com/serpapi/SerpApi/pull/4526.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059795?view=List) | [Inspector](https://serpapi.com/searches/65d8f3d6c640d2725d383307/inspect)

**Comment by ilyazub** [comment]
> The customer also noted that their searches seem to take significantly longer than our `total_time_taken` indicates. I let them know this is likely an issue on their side, but I wanted to document it here in case it's relevant.

Google Images results _parsing_ takes about 2.5 _seconds_ indeed (ref: https://serpapi.com/searches/65df061cd5ecf4a33236edd9/inspect). Thank you for noticing that! We will speed up our parsers.

```ruby
search = Search.new(q: "coffee", engine: "google_images", file_path: "https://serpapi.com/searches/11f54c18f1d286f9/65df06bb1d986ec0b323538e.html")

Benchmark.ms { search.parse! }
# => 2551.527031999285
Benchmark.ms { search.parse! }
# => 2614.588018000177
```

**Comment by zyc9012** [comment]
Before

```
Benchmark.ms { search.parse! }
=> 1682.000691000212
```

After

```
Benchmark.ms { search.parse! }
=> 98.42776899859018
```
