### ISSUE TITLE
[Google Trend] Bug Response api call

### ISSUE THREAD

**Issue by DataBitter** [serpapi/public-roadmap#1434]
Hi,
there is a bug on response, 
for this api:
https://serpapi.com/search.html?engine=google_trends&q=carbonara%2Camatriciana&geo=IT&data_type=TIMESERIES&date=now+1-d&api_key=********

The response is: 
)]}', {"default":{"timelineData":[{"time":"1708696800","formattedTime":"Feb 23, 2024 at 7:00\u202fAM","formattedAxisTime":"Feb 23 at 7:00\u202fAM","value":[8,5],"hasData":[true,true],"formattedValue":["8","5"]},{"time":....................................

The bug is that start with: ")]}', "

This is how I guess will be correct 

![image](https://github.com/serpapi/public-roadmap/assets/83430518/b527fe02-7610-4ea2-8518-bc833d0f3cf8)

**Comment by ilyazub** [comment]
Hello, @DataBitter.

My apologies for the confusion and thanks for your question.

Please use the JSON output format for the API endpoint (`/search.json?params=...`):

```
https://serpapi.com/search.json?engine=google_trends&q=carbonara%2Camatriciana&geo=IT&data_type=TIMESERIES&date=now+1-d&api_key=********
```

The JSON format is assumed by default and can be omitted (`/search?params=...`):

```
https://serpapi.com/search?engine=google_trends&q=carbonara%2Camatriciana&geo=IT&data_type=TIMESERIES&date=now+1-d&api_key=********
```

![image](https://github.com/serpapi/public-roadmap/assets/282605/db4a7181-5694-49a9-89a7-dfed9934b8ec)
(ref: https://serpapi.com/google-trends-api#api-parameters-serpapi-parameters-output)

Please let us know if it helps and if you have any questions.

**Comment by DataBitter** [comment]
No, the problem isn't the presence or not of parameters, but the starting with ")]}',"
 
)]}', {"default":{"timelineData":[{"time":"1709160480","formattedTime":"Feb 28, 2024 at 3:48\u202fPM","formattedAxisTime":"Feb 28 at 3:48\u202fPM","value":[26,0],"hasData":[true,false],"formattedValue":["26","0"]},... as example.

For make it work, i must substring, deleting  " )]}', "

**Comment by DataBitter** [comment]
No, the problem isn't the presence or not of parameters, but the starting with ")]}',"

)]}', {"default":{"timelineData":[{"time":"1709160480","formattedTime":"Feb 28, 2024 at 3:48\u202fPM","formattedAxisTime":"Feb 28 at 3:48\u202fPM","value":[26,0],"hasData":[true,false],"formattedValue":["26","0"]},... as example.

For make it work, i must substring, deleting " )]}', "

**Comment by ilyazub** [comment]
> https://serpapi.com/search.html?engine=google_trends&q=carbonara%2Camatriciana&geo=IT&data_type=TIMESERIES&date=now+1-d&api_key=********

Please use <code>/search<b>.json</b></code> URL path (instead of `.html`) to get the extracted data without `)]}',` at the beginning. I'm sorry for the confusion.

![image](https://github.com/serpapi/public-roadmap/assets/282605/42fbc762-d624-413b-9469-359899a832e8)
(ref: https://serpapi.com/search?engine=google_trends&q=Coffee)

`/search.html` is the endpoint for raw data SerpApi got from the search engine results page.

@DataBitter Please let us know if it help or if you want the actual Google Trends HTML response.

**Comment by DataBitter** [comment]
Thank you so much
