### ISSUE TITLE
[OpenAPI] a well defined schema would be nice to insure type safety with SerpAPI

### ISSUE THREAD

**Issue by hichemfantar** [serpapi/public-roadmap#1435]
I can't seem to find any well defined types for the API.

Something similar to [this](https://api.kombo.dev/openapi.json) would make working with SerpAPI much easier.

We can then use the schema with [openapi-typescript](https://github.com/drwpow/openapi-typescript) or [openapi-client-axios](https://github.com/openapistack/openapi-client-axios) to make things easier and type safe.

**Comment by hartator** [comment]
It's unfortunately not possible to publish a type-specific schema for search results.

Search result pages contain a variety of data that can be or not be present on the page. So, you would have a lot of `String | null` types that will make typing basicaly useless.

**Comment by hichemfantar** [comment]
@hartator the schema is about having type safety with serpAPI, not the google search results. It doesn't really matter if most or nullable.
It'd actually be very helpful if the types were available so at least we don't waste time creating our own types.
Like I said, we only need the openAPI schema, we can generate type safe clients using the previously mentioned tools.

**Comment by hartator** [comment]
Our Go library has type annotations: https://github.com/serpapi/google-search-results-golang/blob/master/model.go

As you can see, these are not super useful.

**Comment by hack-r** [comment]
It's the age of LLM Agents. I think it's critical not to reduce the usefulness of SerpAPI by 50% or more by not having the standard OpenAPI file expected of all production-ready APIs.

**Comment by hartator** [comment]
How is this related to LLM Agents?

LLMs are the reverse than statically typed as there inputs/outputs are by nature probabilistic and dynamic. It's counter nature for them to coerce into specific types and efforts in this domain have been unproductive.

**Comment by hichemfantar** [comment]
I think what he means is that he wants to provide the api schema to an llm and generate scripts based on the properties in the schema.

**Comment by hartator** [comment]
> Having `String | null ` is the point. The goal of the schema is to know the actual properties and types that are going to be returned. The fact that they are nullable is irrelevant.

Do you mean something as simple as https://github.com/serpapi/google-search-results-golang/blob/master/model.go, but in OpenAI schema would work?

**Comment by hichemfantar** [comment]
> > Having `String | null ` is the point. The goal of the schema is to know the actual properties and types that are going to be returned. The fact that they are nullable is irrelevant.
> 
> Do you mean something as simple as https://github.com/serpapi/google-search-results-golang/blob/master/model.go, but in OpenAI schema would work?

It should specify the actual properties that can be returned.

example of a TS interface for the response
```
export interface SerpApiGoogleMapsSearchResponse {
	search_metadata: SearchMetadata;
	search_parameters: SearchParameters;
	search_information: SearchInformation;
	local_results?: LocalResult[];
	place_results?: PlaceResults;
	serpapi_pagination: SerpapiPagination;
}

interface SearchMetadata {
	id: string;
	status: string;
	json_endpoint: string;
	created_at: string;
	processed_at: string;
	google_maps_url: string;
	raw_html_file: string;
	total_time_taken: number;
}

```

**Comment by schaferyan** [comment]
Thank you for clarifying @hichemfantar. 

Correct me if I'm wrong @hartator, but my understanding is that it's not unfortunately possible for us to compile an exhaustive list of all of the properties that may be returned, as some of the key names may be generated dynamically based on what the search engine returns.

**Comment by hichemfantar** [comment]
> Thank you for clarifying @hichemfantar.
> 
> Correct me if I'm wrong @hartator, but my understanding is that it's not unfortunately possible for us to compile an exhaustive list of all of the properties that may be returned, as some of the key names may be generated dynamically based on what the search engine returns.

If that's true (key names are dynamically generated) then that means there's no versioning in serpai which also means production code can break randomly.

**Comment by hartator** [comment]
> Are you using some kind of smart logic that auto parses the html and comes up with property names?

No, we do have static field names for most things. 

Regarding OpenAPI schema, it's only possible for predictable objects, not live searches by nature. Random example, a search can have - or not - `organic_results`, `ads`, or `knowledge_graph` data. Take an empty but successful search, how can you technically generate a public schema with types for this?

**Comment by hichemfantar** [comment]
> > Are you using some kind of smart logic that auto parses the html and comes up with property names?
> 
> No, we do have static field names for most things.
> 
> Regarding OpenAPI schema, it's only possible for predictable objects, not live searches by nature. Random example, a search can have - or not - `organic_results`, `ads`, or `knowledge_graph` data. Take an empty but successful search, how can you technically generate a public schema with types for this?

Yes, obviously the schema would only declare known properties whether they're nullable or not.
If serpapi has a specific predefined property then it should be included.
