### ISSUE TITLE
[Google Image API] How long is the image URL will be available?

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1437]
Upon using Google Images API, the image_results return a URL from serpapi.com like this

![CleanShot 2024-02-26 at 11 55 37](https://github.com/serpapi/public-roadmap/assets/4522467/e6d7341a-cd01-4ffc-ae45-924bb2148530)

Is there any time limit on how long the URL will be available?

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059860?view=List)

**Comment by ilyazub** [comment]
The image URLs are available up to 31 days, as long as searches are available via the [Search Archive API](https://serpapi.com/search-archive-api).

**Comment by hilmanski** [comment]
Another customer had an issue with this. I think we should share this in our documentation. We can share this on the overview page: https://github.com/serpapi/SerpApi/pull/4916 or on each API that returns images from SerpApi.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000061985?view=List)
