### ISSUE TITLE
[Apple Reviews API] `rating` missing in the response for some countries

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1438]
A high volume customer reported that `rating` is missing in the response for some countries, like Germany for example. I was able to reproduce it in our Playground.

![image](https://github.com/serpapi/public-roadmap/assets/144151895/9a807c0f-9a1e-4c65-b86f-49babf829908)

[Playground](https://serpapi.com/playground?engine=apple_reviews&product_id=1227579630&country=de&page=1&sort=mostrecent&no_cache=true) | [Inspect](https://serpapi.com/searches/65dcbcf9defa139e8a9b76ed/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059920?view=List)

**Comment by btaunt** [comment]
FYI - it seems to be an issue with reviews containing "no" rating. By default, we simply do not render the `rating` if this is the case. We _could_ fallback on a setting the rating to `0` if none are present.

**Comment by btaunt** [comment]
This issue has been resolved.

Ratings are now properly returned across all countries. See examples below:

[Germany](https://serpapi.com/playground?engine=apple_reviews&product_id=1227579630&country=de&page=1&sort=mostrecent&no_cache=true)
[Thailand](https://serpapi.com/playground?engine=apple_reviews&product_id=1227579630&country=th&page=1&sort=mostrecent&no_cache=true)
[Russia](https://serpapi.com/playground?engine=apple_reviews&product_id=1227579630&country=ru&page=1&sort=mostrecent&no_cache=true)
[Japan](https://serpapi.com/playground?engine=apple_reviews&product_id=1227579630&country=jp&page=1&sort=mostrecent&no_cache=true)
[United States](https://serpapi.com/playground?engine=apple_reviews&product_id=1227579630&country=th&page=1&sort=mostrecent&no_cache=true)
[Canada](https://serpapi.com/playground?engine=apple_reviews&product_id=1227579630&country=ca&page=1&sort=mostrecent&no_cache=true)

<img width="932" alt="Screenshot 2024-03-12 at 10 56 53 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/6bb9a7a5-5a59-4f82-8d19-8380c3c3c52f">
