### ISSUE TITLE
[Ebay Search API] Pagination returns the same results 

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#144]
`_pgn=25` and eBay displays 11th page. For some reason, eBay itself doesn't display something like "no results", it just shows the same last page over and over again even if the `_pgn` parameter will be `150`:

![image](https://user-images.githubusercontent.com/78694043/167829276-abcc051c-ebb4-4b14-8ce5-01a115a75dbb.png)

Because of that, there's no way to check if there're no more results. Checking for `"error"` key from the hash doesn't do anything because results are always present. 

![image](https://user-images.githubusercontent.com/78694043/167830173-28e6e382-c186-454c-9e6f-cfa2a079560c.png)

The page number is set to 125, and pagination is still there, although it shows that the current page is 19, and the next page is also 19:

![image](https://user-images.githubusercontent.com/78694043/167831262-9d9aed90-cb5f-4c80-8be1-f343a4dbabc2.png)

Playground link: https://serpapi.com/playground?engine=ebay&_nkw=minecraft+redstone&ebay_domain=ebay.com&_pgn=125

Video example:

https://user-images.githubusercontent.com/78694043/167829220-31128328-74b9-4acb-9618-41b0de62938c.mp4

Is there's anything I'm doing wrong?

**Comment by ilyazub** [comment]
Iterate through pages while `serpapi_pagination["current"]` increments. It's the same as the check with token-based pagination.

**Comment by dimitryzub** [comment]
Thank you, @ilyazub 💫

**Comment by ilyazub** [comment]
Sample code using SerpApi SDK for Python:

```python
# Workaround to update search parameters based on the SerpApi response
# In the future, it will be done internally in EbaySearch#pagination
#
# Sample query: _nkw=coffee&_pgn=4
# dict(parse_qsl(urlsplit("_nkw=coffee&_pgn=4").query))
# { "_nkw": "coffee", "_pgn": 4 }
next_page_query_dict = dict(
    parse_qsl(urlsplit(results["serpapi_pagination"]["next"]).query)
)

# Stop iterating results when _pgn srops incrementing
if int(results["serpapi_pagination"]["current"]) == int(next_page_query_dict["_pgn"]):
    break

search.params_dict.update(next_page_query_dict)
```

Full code in online IDE: https://replit.com/@serpapi/scrape-ebay-python-bs4-serpapi#serpapi_results.py

**Comment by ilyazub** [comment]
Draft PR in the `google-search-results` package to stop iterating automatically when parameters not change: https://github.com/serpapi/google-search-results-python/pull/30/files
