### ISSUE TITLE
[Google Search API] Google Knowledge graph for product comparison

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1444]
A customer reported that we're not returning results for the knowledge graph that includes a price comparison for a product.

![CleanShot 2024-02-29 at 07 55 31](https://github.com/serpapi/public-roadmap/assets/4522467/f383e3b2-d401-456f-8d38-7bec5aa55295)

There is also a button to compare all the prices (We might need a separate API for this)
![CleanShot 2024-02-29 at 07 58 15](https://github.com/serpapi/public-roadmap/assets/4522467/82fb93f3-3d22-451d-9287-2b0cc8d788a0)
[Compare price link](https://www.google.com/search?q=groen+128525&oq=groen+128525&gs_lcrp=EgZjaHJvbWUqBggAEEUYOzIGCAAQRRg7MgYIARBFGDwyBggCEEUYPDIGCAMQRRg80gEHMTgxajBqN6gCALACAA&sourceid=chrome&ie=UTF-8)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060108?view=List) | [Playground](https://serpapi.com/playground?q=groen+128525&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client) | [Inspect](https://serpapi.com/searches/65dfc12dfdca3e00635b837c/inspect)

**Comment by andypple83** [comment]
We've released a fix for this.

![Screenshot 2024-03-28 at 18 22 15](https://github.com/serpapi/public-roadmap/assets/99160364/3ec2686d-fe22-4853-a6ec-21b0c7fa86f1)


Thank you for reporting this issue. Let me know if you need any help with any searches.
