### ISSUE TITLE
[Google Lens Image Source API] Scrape Price and Availability

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1449]
Google Lens Image Source results include pricing and availability information when applicable. A customer reported we are not currently scraping this information.

<img width="1434" alt="Screenshot 2024-03-01 at 11 06 09 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/cada8c30-bf83-4a27-9b43-f53232b2961f">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060271?view=List) | [Playground](https://serpapi.com/playground?engine=google_lens_image_sources&page_token=YTkyNWI5OGUtZTFiOS00ZmM4LTgwZDAtZGIyYjJlOTFhMGY3&hl=en&country=us) | [Inspect](https://serpapi.com/searches/65e226f72236e211df73358c/inspect)

**Comment by i8ramin** [comment]
commenting to be notified of updates. thx
