### ISSUE TITLE
[Google Maps Contributor Reviews API] All Requests Failing w/ 500 Error

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1450]
A user reported that currently, our Google Maps Contributor Reviews API is returning a 500 error for valid requests. This includes our playground example. I've verified that the contributor ID is still valid. Other valid contributor IDs also return the 500 error.

<img width="1350" alt="Screenshot 2024-03-01 at 11 37 48 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/4b93c756-4233-4e9f-99f1-44599821642b">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060272?view=List) | [Playground](https://serpapi.com/playground?engine=google_maps_contributor_reviews&contributor_id=109736708296406538146&gl=us&hl=en) | [Inspector](https://serpapi.com/searches/65e228fcb7b1cc5e928ec7d6/inspect)

**Comment by djsegal** [comment]
It's related to review `rating` and `likes` being parsed correctly

**Comment by aciddjus** [comment]
This issue has now been resolved.

In addition to fixing the 500 error on our HTML endpoint, we have also updated our parser to extract all the missing fields.

<img width="1503" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/fb0720e9-6240-4bd1-b3ae-68be4b09d327">

----------------

[Playground link](https://serpapi.com/playground?engine=google_maps_contributor_reviews&contributor_id=109736708296406538146&gl=us&hl=en&no_cache=true)
