### ISSUE TITLE
[Google Search API] Scrape Quarter-by-Quarter Scores for Sports Events

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1451]
Google shows a quarter-by-quarter score breakdown for some Sports Results. Specifically, results for American Football games seem to have this element.

A user requested we scrape this information.

<img width="1460" alt="Screenshot 2024-03-01 at 3 08 39 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/101a1e60-92b3-47a6-8d14-23bd88d7662f">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060288?view=List) | [Search Inspector](https://serpapi.com/searches/65e2605dad7fa91ffcf26836/inspect) | [Playground](https://serpapi.com/playground?q=packers+vs+seahawks+2023&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)

**Comment by CompuGenius** [comment]
Thanks for handling this for me!
For more context, the documentation says it SHOULD support it, but it doesn't seem to, at least for football (or even maybe just the Superbowl, I haven't had a chance to test anything else yet).

https://serpapi.com/sports-results#api-examples-game-spotlight-results

**Comment by zyc9012** [comment]
@CompuGenius it's fixed.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/103145ec-c1a1-42b3-b88c-964933125ac4)
