### ISSUE TITLE
[Bing Search API] Support `zn-CN` and `ru-RU` values for `mkt` parameter and update link in documentation

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1452]
One of our high volume customers requested that we support `zn-CN` value for `mkt` parameter. It's indeed not supported at the moment. I compared the list of available `mkt` values, and we're missing only `zn-CN` and `ru-RU`.

![image](https://github.com/serpapi/public-roadmap/assets/28161162/eb9a5e10-8b09-47a1-8252-9ec67c165f4f)

We should also update the link in our documentation, as it's no longer accessible:
![image](https://github.com/serpapi/public-roadmap/assets/28161162/17533114-6537-4ff9-afe3-aab86245e1f6)

Current link:
https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-custom-search-api-v7-reference#market-codes

Working link:
https://learn.microsoft.com/en-us/bing/search-apis/bing-web-search/reference/market-codes

[Documentation](https://serpapi.com/bing-search-api#api-parameters-geographic-location-mkt)

**Comment by btaunt** [comment]
This feature has been added.

We now support both `zh-CN` and `ru-RU` for the `mkt` parameter:

<img width="336" alt="Screenshot 2024-03-11 at 10 46 53 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/291f774d-a92c-4295-951d-ee0a46b7092f">
<img width="334" alt="Screenshot 2024-03-11 at 10 47 06 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/69205c5e-2cae-4ece-befa-e334f0737663">

We have also updated the documentation to use the proper links to Microsoft's market codes:
<img width="835" alt="Screenshot 2024-03-11 at 10 48 08 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/a981a299-00d5-4dde-9315-ddd6f43d7173">
<img width="365" alt="Screenshot 2024-03-11 at 10 52 26 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/9ceeeadb-6223-4077-95b2-9c8964df72e9">

View live on the [Bing Playground (RU-RU)](https://serpapi.com/playground?engine=bing&q=Coffee&mkt=ru-ru&no_cache=true) & [Bing Playground (ZH-CN)](https://serpapi.com/playground?engine=bing&q=Coffee&mkt=zh-cn&no_cache=true)
