### ISSUE TITLE
[Baidu Search API] Some searches return incomplete `answer_box`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1453]
One of our high volume customers reported that the `answer_box` returned in Baidu Search API is missing most of its body:

<img width="1668" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/c41ab36e-7bfc-4c95-8349-8648ae82f735">

[Playground](https://serpapi.com/playground?engine=baidu&q=%E8%A5%BF%E7%BA%A2%E6%9F%BF%E7%82%92%E9%B8%A1%E8%9B%8B%E6%80%8E%E4%B9%88%E5%A5%BD%E5%90%83) | [Inspect](https://serpapi.com/searches/65e5878ba74fe071f02d26bf/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000059912?view=List)

**Comment by tanys123** [comment]
We have released a fix to the issue. Turn out it is an answer box with AI-generated content, we give it a type name `ai_content`. We also fixed some of the snippets missing for the `organic_result` answer box.

<img width="1459" alt="Screenshot 2024-04-05 at 10 16 39 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/722e27d9-3c9e-4014-b564-2f64fefa5acc">

[Documentation](https://serpapi.com/baidu-answer-box#api-examples-desktop-ai-content-answer-box)
