### ISSUE TITLE
[Google Images]Some Mobile Searches Return Without Parsing Anything

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1455]
A customer reported some of their Google Images searches with `device=mobile` are returning without parsing any images, despite the presence of images in the raw HTML.

The searches seem to return an empty `search_information` array, and no other keys besides the `search_parameters` and `search_metadata` in the JSON.

I was able to replicate it in the Playground.

<img width="1145" alt="Screenshot 2024-03-05 at 12 51 21 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/93643551-ad76-4c2a-b4b5-4f2ba9fc3c83">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060561?view=List) | [Playground](https://serpapi.com/playground?engine=google_images&q=Personalized+Recipe+Book&location=San+Francisco%2C+CA&gl=us&hl=en&device=mobile&no_cache=true&newPara=chips+ijn+num) | [Inspector 1](https://serpapi.com/searches/65e75bde2bc7d87e196819ca/inspect) | [Inspector 2](https://serpapi.com/searches/65e75e68224db1f41103f1a6/inspect)|  [Inspector 3](https://serpapi.com/searches/65e75e684055aa941060ec80/inspect)

**Comment by marm123** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060768?view=List)

**Comment by aciddjus** [comment]
This issue has been resolved.

We are now again extracting all Image results on mobile.

![image](https://github.com/serpapi/public-roadmap/assets/6929257/19a780bd-9d4a-4101-a598-c86e1dcc3ba3)


---------------------

[Playground link](https://serpapi.com/playground?engine=google_images&q=Personalized+Recipe+Book&location=San+Francisco%2C+CA&gl=us&hl=en&device=mobile&no_cache=true)
