### ISSUE TITLE
[Google Trends Autocomplete API] Some searches return no results

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1459]
One of our users reported that they are not getting any results for some searches. I was able to recreate the issue.

What is expected:
<img width="1321" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/74804231-8959-4744-a53d-159b07a5863d">

What they are getting:
<img width="1335" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/a883e3e9-58a6-41c7-b2dc-a5e100e64ffd">

[Playground](https://serpapi.com/playground?engine=google_trends_autocomplete&q=Antibiotics)
[Inspect - correct
](https://serpapi.com/searches/65e96db7e4a23d1c4fb49ab1/inspect)[Inspect - incorrect
](https://serpapi.com/searches/65e96f7ab5961e9093d0afab/inspect)[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060676)

**Comment by Freaky** [comment]
A fix for this has been deployed - the API should no longer intermittently return empty results.
