### ISSUE TITLE
[Google Product API] Grouped offers are not being properly scraped

### ISSUE THREAD

**Issue by lohmann** [serpapi/public-roadmap#1462]
The Google product page is now grouping similar offers from the same marketplace. Only one offer from each marketplace is initially displayed, but it is possible to expand the list and get the other offers.

The API only returns the first offer from each group, but we need the complete list of offers.

Collapsed offer list
![image](https://github.com/serpapi/public-roadmap/assets/933539/352b5159-ce36-4a39-8680-45d8f913ac9c)

Expanded offer list
![image](https://github.com/serpapi/public-roadmap/assets/933539/a8f992ce-84c8-4b22-adc5-5625d2abc256)

[HTML Result](https://serpapi.com/search.html?engine=google_product&product_id=13101501755961091744&google_domain=google.com&gl=br&hl=pt-br&offers=1&gRecaptchaResponse=03AFcWeA5y0NzbiyrSRgTN1bweRrNyPedf8bSMWSUmEQH2kx3c_Myq2i3Hq9_aCcR46ribacSizYb2j3hKADcxIrN8fUuSxlWN1wr6xD_nPghS6Tvn3l6oG8IvIFj4W59OZPlBGkbXiqctPsIw9k7gyjnzgyhU-nia1ioCE0Yt6luqNNX7o4lAr2gsh6d6HQFp_PrhX_25c9GZ3Lcsuf_LnxoqcKqu-SyyiyLix5KSSLhH1VOj62ouNxHiKQmKSGhElspjIQP2l44tZBDlVw7nlnlsytmUD4BTcKhEaP6AkZFNSNf0-N1pp_4IQryoYj4r3dpBGCKvJeeb4KIZdupY3lMa51ZBZXCAQOuRqqt3M6dZf9Zo3l3kZWbPFsDI0YSXoPzoFnUM3F-8WfiJPm2bDdJm8LMJRWe3ce6yqPOQHBNV9q40ZKYS9nKewYWVwJWDOZh5ay4GuDckISmJAYTbgO8JK-ZQFCI_GscrcP-zQomvlG6I8JoQY9pbZQP5VNMsdMZwpBouYjE_3srzztR0w9wPbK7CKGvxlGx0bG8Ty3C1oReX0cM2jTWI90f_ZVzA66uM2UdwWkLYCmp6zlXnnPLCn3-RFEzNWaTa3Xk2x_DWMQjWcARpoYAJpbmYb4sl8fCEBsljphx1)

[JSON Result](https://serpapi.com/search.json?engine=google_product&product_id=13101501755961091744&google_domain=google.com&gl=br&hl=pt-br&offers=1&gRecaptchaResponse=03AFcWeA5y0NzbiyrSRgTN1bweRrNyPedf8bSMWSUmEQH2kx3c_Myq2i3Hq9_aCcR46ribacSizYb2j3hKADcxIrN8fUuSxlWN1wr6xD_nPghS6Tvn3l6oG8IvIFj4W59OZPlBGkbXiqctPsIw9k7gyjnzgyhU-nia1ioCE0Yt6luqNNX7o4lAr2gsh6d6HQFp_PrhX_25c9GZ3Lcsuf_LnxoqcKqu-SyyiyLix5KSSLhH1VOj62ouNxHiKQmKSGhElspjIQP2l44tZBDlVw7nlnlsytmUD4BTcKhEaP6AkZFNSNf0-N1pp_4IQryoYj4r3dpBGCKvJeeb4KIZdupY3lMa51ZBZXCAQOuRqqt3M6dZf9Zo3l3kZWbPFsDI0YSXoPzoFnUM3F-8WfiJPm2bDdJm8LMJRWe3ce6yqPOQHBNV9q40ZKYS9nKewYWVwJWDOZh5ay4GuDckISmJAYTbgO8JK-ZQFCI_GscrcP-zQomvlG6I8JoQY9pbZQP5VNMsdMZwpBouYjE_3srzztR0w9wPbK7CKGvxlGx0bG8Ty3C1oReX0cM2jTWI90f_ZVzA66uM2UdwWkLYCmp6zlXnnPLCn3-RFEzNWaTa3Xk2x_DWMQjWcARpoYAJpbmYb4sl8fCEBsljphx1)

[Playground link](https://serpapi.com/playground?engine=google_product&product_id=13101501755961091744&gl=br&hl=pt-br&offers=1)

**Comment by schaferyan** [comment]
The customer who reported this also contacted us on Intercom:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060737?view=List)

**Comment by djsegal** [comment]
This would likely require a new API endpoint, because each of these collapsible offer groups makes a request to an endpoint like:

- https://www.google.com/shopping/product/13101501755961091744/plusbox/104823487?gl=br&hl=pt-br&sourceid=chrome&ie=UTF-8&prds=cid:13101501755961091744,cs:1,eto:16660138260552178762_0,pid:161884199083751359,rsk:PC_289061582183793313&fmt=json&ved=0ahUKEwi54Zv6kuWEAxXb8gIHHe25A-AQhxoIMg

However, we could still provide links to these URLs for each online seller's results?

**Comment by djsegal** [comment]
Hi @lohmann,

We're looking into providing direct links to JSON data for each online_sellers dropdown on Google product pages. These links would give you access to the **[raw data](https://www.google.com/shopping/product/13101501755961091744/plusbox/104823487?gl=br&hl=pt-br&sourceid=chrome&ie=UTF-8&prds=cid:13101501755961091744,cs:1,eto:16660138260552178762_0,pid:161884199083751359,rsk:PC_289061582183793313&fmt=json&ved=0ahUKEwi54Zv6kuWEAxXb8gIHHe25A-AQhxoIMg)** for further analysis. Would including these URLs be helpful for your use case? Let me know what you think!

**Comment by martin-serpapi** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061432?view=List)

**Comment by kagermanov27** [comment]
We have released this feature.

- The `offer_id` parameter is now supported for Google Product API. 
- `offer_id`, `offer_link`, and `serpapi_offer_link` fields can be found in `sellers_results`->`online_sellers` to traverse to the `X more offers` dropdown menu.

Before:
![image](https://github.com/serpapi/public-roadmap/assets/73674035/7b80cc5c-b120-4a04-9d4f-099d9ace667a)

After:
![image](https://github.com/serpapi/public-roadmap/assets/73674035/e0d4af30-eec7-430e-a31e-b3a88e20e38f)

![image](https://github.com/serpapi/public-roadmap/assets/73674035/1d5502ed-1838-4001-8194-36f7ee66bf5c)
