### ISSUE TITLE
[Google Search API] `answer_box` -> `images` not parsed for some mobile searches

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1467]
<img width="1146" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/75944b37-055e-4153-b11d-9030b3eaaae7">

[Playground](https://serpapi.com/playground?q=Medieval+Torture+Methods&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client+votes+site+ie+oe+pws+ibp+source)
[Inspect](https://serpapi.com/searches/65f05624f26ac61aaddf6636/inspect)

**Comment by ilyazub** [comment]
`answer_box.images` are extracted into `inline_images` for the search above.

![image](https://github.com/serpapi/public-roadmap/assets/282605/d1d99bed-3e5b-4a7a-ba09-635cb5bbdf1c)
(ref: https://serpapi.com/searches/65f05624f26ac61aaddf6636/inspect)

**Comment by kagermanov27** [comment]
Answer box `images` are parsed correctly now:

Before:
<img width="1470" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/9cda7155-c1c8-4080-8d8b-d77d900685b3">

After:

<img width="1470" alt="314159318-6af2d065-b9e5-4a70-93d2-f2a18e53bd51 copy" src="https://github.com/serpapi/public-roadmap/assets/73674035/340d8e68-ebbf-42c0-a52f-252dfe736365">


Also, the answer box images were parsed in `inline_images`. It is prevented now:

Before:

<img width="1470" alt="before-1" src="https://github.com/serpapi/public-roadmap/assets/73674035/07ef8fae-132d-472d-94e8-494e9dae6e31">

After:

<img width="1470" alt="Pasted Graphic 2 copy" src="https://github.com/serpapi/public-roadmap/assets/73674035/d79344a8-9e33-48ad-85db-75b816252156">
