### ISSUE TITLE
[Google Search API] `recipes` not parsed for some mobile searches

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1469]
<img width="732" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/d1ab3699-cc8b-4fa7-9de8-10394bd20d1b">

[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client+votes+site+ie+oe+pws+ibp+source)
[Inspect](https://serpapi.com/searches/65f058bad04d6daf1aca9d99/inspect)

**Comment by zyc9012** [comment]
Not parsed for some desktop searches as well.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/83465184-ad8a-480a-9139-1a093020cfe2)

[Inspect](https://serpapi.com/searches/6669478334ff95846e283923/inspect)

**Comment by btaunt** [comment]
We now properly parse `recipes_results` for newer `desktop` and `mobile` layouts:

<img width="912" alt="Screenshot 2024-08-29 at 10 52 56 AM" src="https://github.com/user-attachments/assets/e5b01437-a6d9-446d-9f1c-67fc50def45c">
<img width="709" alt="Screenshot 2024-08-29 at 10 54 10 AM" src="https://github.com/user-attachments/assets/86e9728a-4343-422e-9f0a-ba636d27d5ff">

[Playground](https://serpapi.com/playground?q=latte&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client+votes+site+ie+oe+pws+ibp+source+ijn+rlz)
