### ISSUE TITLE
[Google Search API] `inline_videos` not parsed for some mobile searches

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1470]
<img width="732" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/e8aeb8eb-d970-4b26-b75a-599058300b5a">

[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client+votes+site+ie+oe+pws+ibp+source)
[Inspect](https://serpapi.com/searches/65f058bad04d6daf1aca9d99/inspect)

**Comment by zyc9012** [comment]
Fixed incomplete parsing of inline images

Before (4 items)

![image](https://github.com/serpapi/public-roadmap/assets/3034310/1322ef06-23d5-4a2a-834d-55630de1eacd)


After (7 items)

![image](https://github.com/serpapi/public-roadmap/assets/3034310/c3512ffe-c9cf-4c30-ae15-288c398b32d3)
