### ISSUE TITLE
[Google Play Product API] Scrape full date and time of the review

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1473]
One of our users requested that we scrape the date and time of the review (currently, we're scraping only the date). I'm not sure if this is possible with the endpoint we're using, but we might explore the possibility. The customer also shared some more information in the Intercom thread.

Current state:
![image](https://github.com/serpapi/public-roadmap/assets/28161162/ecd67e5e-e297-42c7-b392-27e69a8e36ef)

[Playground](https://serpapi.com/playground?engine=google_play_product&product_id=com.google.android.youtube&gl=us&store=apps&all_reviews=true&platform=phone&sort_by=1) | [Inspect](https://serpapi.com/searches/65f15384f21801dd1a2e267b/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000058606)

**Comment by xavimb** [comment]
Any news about this? Dealing with strings instead of dates makes my work much harder, and the information is available in the HTML response.

**Comment by marm123** [comment]
Hi @xavimb, thank you for reaching out. We're actively working on this feature, and there is a pull request already linked to close it. It will be implemented after reviews are completed, and we'll let you know once it's done.

**Comment by xavimb** [comment]
@marm123 That's great! 🙌 Do you know if this will be a breaking change? Or will there be a new parameter with the full timestamp?

**Comment by tanys123** [comment]
We have added a new field `iso_date`, this change has been reflected in our [documentation](https://serpapi.com/google-play-product-reviews).

<img width="336" alt="Screenshot 2024-03-22 at 12 55 20 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/227e7617-a23b-4895-81a3-b49a20e1f912">
