### ISSUE TITLE
[Google Play Product API] Empty results returned for some valid searches with `"all_reviews": "true"`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1474]
One of our users reported that some searches return no results when paginating with the `next_page_token`. I've been able to recreate the issue.

No results:
<img width="1669" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/45a12237-ad01-43ed-a628-190202c7cf78">

Correct results with the same parameters:
<img width="1668" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/536701f2-7d4c-4b35-933a-8835b1b0a7c0">

[Playground](https://serpapi.com/playground?engine=google_play_product&product_id=in.amazon.mShop.android.shopping&gl=in&hl=en&store=apps&all_reviews=true&platform=phone&sort_by=2&num=199&next_page_token=Co4BCosBMCxUSU1FU1RBTVAgIjIwMjQtMDMtMTAgMTQ6MzE6MjYuNzk2Mjc3KzAwIiw3MzA2OTA3MTE2LCJodHRwOi8vbWFya2V0LmFuZHJvaWQuY29tL2RldGFpbHM_aWQ9djI6aW4uYW1hem9uLm1TaG9wLmFuZHJvaWQuc2hvcHBpbmc6MSIsMSxmYWxzZQ&no_cache=true)
[Inspect - correct results](https://serpapi.com/searches/65f165ef303eb16962dfde67/inspect) | [Inspect - no results](https://serpapi.com/searches/65f16646116a5547c6f36e2f/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061030?view=List)

**Comment by snehasinghoshin** [comment]
Hi, any updates on above? This is a blocker for us.

**Comment by marm123** [comment]
Hi @snehasinghoshin, thank you for reaching out!

We don't have any updates regarding this issue yet. We'll post an update as soon as this is fixed.

Thank you for your patience, and feel free to reach out at contact@serpapi.com.

**Comment by marm123** [comment]
I only now noticed that this is a duplicate of https://github.com/serpapi/public-roadmap/issues/1169

@snehasinghoshin, the issue should be resolved now. Please contact us at contact@serpapi.com if you encounter any further issues. I'm closing this thread as completed.
