### ISSUE TITLE
[Google Maps API] Scrape the `gcid` value

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1475]
One of our users requested us to scrape `gcid` value. It's similar to the `type` we're already scraping, but it's formatted in a specific way and not language-dependent.

`gcid` in HTML (likely available in other places too):
<img width="1458" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/334ff915-fafa-49cb-a4dc-f490d397d59d">

[Playground](https://serpapi.com/playground?engine=google_maps&q=Coffee&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&place_id=ChIJ9cZGKadZwokRMcfI_Q5jg_g&type=search) | [Inspect](https://serpapi.com/searches/65f17e9429d17715ad863ad2/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061033?view=List)

**Comment by marm123** [comment]
Changing it to `queued` as our high-volume customer is asking for an update.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061033?view=List)
[Customer](https://serpapi.com/admin/users/60c313b766d81f35e73f7aec)

**Comment by hartator** [comment]
Are we sure `gcid` means global catalog identifier? I can't think a reference online about this. It seems unlikely.

**Comment by marm123** [comment]
Yes, you are right @hartator. It's most likely not a global catalog identifier, as it's Amazon-related. My mistake. However, I can't find any relevant reference. I'll try to dig deeper tomorrow, but will change the title to be less confusing.

**Comment by hartator** [comment]
Yes, maybe we should keep `type` in the name to match the rest of the JSON as it's already using `type` for similar data.

Maybe `type_id`, `type_ids`, or `standardized_type`?
