### ISSUE TITLE
[Google Trends API] Allow users to use the "Include low search volume regions" option

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1480]
One of our users requested the Google Trends API feature. For the `GEO_MAP` search on Google Trends, there is an option to include low search volume regions. Currently, we don't support this option.

Google Trends default results:
<img width="892" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/89ad437a-81ff-4554-bd7c-df2e3b0a5e9f">

Results with low search volume regions included:
<img width="913" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/edc9ba58-2bf7-401e-8d9c-6bde0c217ddb">

[Playground](https://serpapi.com/playground?engine=google_trends&q=Football%2C+Basketball%2C+Golf&data_type=GEO_MAP) | [Inspect](https://serpapi.com/searches/65f313ee24e88e416847417a/inspect) | [Google Trends](https://trends.google.com/trends/explore?date=now%201-d&q=Football,Basketball,Golf&hl=en)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061128?view=List)

**Comment by sonika-serpapi** [comment]
Another customer requested this
[Front](https://app.frontapp.com/open/cnv_1c53fhb0?key=JpYo4qsr4vDw1XX_95Qr8gkj3bu8wPFJ)

**Comment by tanys123** [comment]
We only have to add a new parameter and append `includeLowSearchVolumeGeos` parameter to the payload.

Usual request:
<img width="551" alt="Screenshot 2024-08-08 at 1 49 53 PM" src="https://github.com/user-attachments/assets/595d6273-9377-458b-b751-e70c6da26d6e">

Request that include low search volume regions:
<img width="558" alt="Screenshot 2024-08-08 at 1 49 58 PM" src="https://github.com/user-attachments/assets/d2abeb0c-9aa1-4514-8ebe-0e5f8785b6f0">

**Comment by Ovi** [comment]
We now have option to include low search volume geos:

<img width="1728" alt="Screenshot 2024-11-05 at 1 41 06 PM" src="https://github.com/user-attachments/assets/bf826f58-c81a-4b2e-9af2-0adedf4b3f47">

[Playground](https://serpapi.com/playground?engine=google_trends&q=Football%2C+Basketball%2C+Golf&data_type=GEO_MAP&include_low_search_volume=true) | [Documentation](https://serpapi.com/google-trends-api#api-examples-compared-breakdown-by-region-q-football-basketball-golf-data-type-geo-map-and-include-low-search-volume-true)
