### ISSUE TITLE
[Google Maps Contributor API] `snippet` not Parsed 

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1481]
A user commented on https://github.com/serpapi/public-roadmap/issues/1478 that we are not currently parsing the `snippet` for Google Maps Contributor API queries.

It seems to be missing from both the JSON and the `raw_html_file`. This seems to be affecting all requests to this API, including our Playground example.

<img width="1415" alt="Screenshot 2024-03-14 at 1 33 07 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/7a802e2e-5407-4649-8bda-1adc8696cca6">

[Playground](https://serpapi.com/playground?engine=google_maps_contributor_reviews&contributor_id=109736708296406538146&gl=us&hl=en) | [inspector](https://serpapi.com/searches/65f35eb8fa8675ff878d78d0/inspect)

**Comment by hilmanski** [comment]
A customer reported this issue as well.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061281?view=List)

**Comment by zyc9012** [comment]
@fundix Thank you for your report, it's fixed.
