### ISSUE TITLE
[Google Flights API] Support multiple airports

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1483]
A user requested to support search for multiple airports on Google Flights API

It's possible to do on Google Flights website
![CleanShot 2024-03-18 at 06 16 13](https://github.com/serpapi/public-roadmap/assets/4522467/0fd09f38-7a2d-4c1c-af7e-7edf50afe01d)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061250?view=List)

**Comment by zyc9012** [comment]
We've released the support for specifying multiple airports

Now you can specify multiple airports by separating them with a comma. For example, `CDG,ORY,/m/04jpl`. This applies to both `departure_id` and `arrival_id`.
