### ISSUE TITLE
[Google Patents Details API] Scrape family ID for a patent

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1484]
A customer wants to scrape a family ID from a Google patent.

While this information is not available on the UI, users share the endpoint they're able to use to collect this data.

```
import requests
from bs4 import BeautifulSoup

patent_number = "US9789384B1"
url = " https://patents.google.com/xhr/result?id=patent/%s/en&exp= "% patent_number

response = requests.get(url)

soup = BeautifulSoup(response.content, 'html.parser')
family_number = soup.find(attrs={"itemprop": "family"}).get_text(strip=True).split('Family')[1]

print("FAMILY:", family_number)
```

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060391?view=List)

**Comment by zyc9012** [comment]
Before: No family id

After:

![image](https://github.com/serpapi/public-roadmap/assets/3034310/a55c148c-a0a0-446c-8949-001929b7a8fc)
