### ISSUE TITLE
[Google Maps API] Scrape `address` of GPS-based searches

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1485]
Google allows to get some information, specifically `address` in GPS-based search (GPS coordinates as `q` parameter). However, we're not scraping the `address`, but provide these coordinates as a value:

<img width="1669" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/94dd538c-8509-4629-a542-afef2c3a9c4a">

This is odd, considering that for regular searches, we're returning the correct address (perhaps not taken from the highlighted place):
<img width="1669" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/d5e52da5-2214-4b30-b85e-c055252c37b5">

One of our customers requested this.

[Playground - GPS-based](https://serpapi.com/playground?engine=google_maps&q=41.40338%2C+2.17403&hl=en&type=search) | [Inspect - GPS-based](https://serpapi.com/searches/65f8152c0ead41c624c38be8/inspect)
[Playground - regular ](https://serpapi.com/playground?engine=google_maps&q=Empire+State+Building&hl=en&type=search)| [Inspect - regular](https://serpapi.com/searches/65f8154fa3f4ef5250b66715/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061278?view=List)

**Comment by arunzone** [comment]
@marm123 Thanks for listening to our feedback and taking action on it.
Wondering when we can expect it to be addressed?

**Comment by tanys123** [comment]
We have released a fix to the issue.
<img width="1237" alt="Screenshot 2024-04-01 at 11 10 43 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/f9684823-77b9-42a6-9efb-e75b25dad692">
