### ISSUE TITLE
[Google Flights API] Support outbound arrival time and return arrival time

### ISSUE THREAD

**Issue by jho406** [serpapi/public-roadmap#1487]
Currently the Google flights API support `outbound_times` and `return_times`. Both are structured as a two-number string, each number represents the beginning of an hour. It seems like these two-number strings represent the **departure** times of both Outbound and Return flights.

 It would be great it can support the **arrival** times too.

For example: this option is available on google flights:

For Outbound flights
<img width="499" alt="Screenshot 2024-03-19 at 1 06 51 PM" src="https://github.com/serpapi/public-roadmap/assets/57284/abc5e7bb-e74f-44ee-9373-0400bf38667c">

and Return flights

<img width="547" alt="Screenshot 2024-03-19 at 1 07 06 PM" src="https://github.com/serpapi/public-roadmap/assets/57284/d59b21e7-eb19-478e-8faf-2a1b1327d8e6">

**Comment by tanys123** [comment]
Thanks @jho406 for the suggestion 👍. We could add 2 new parameters (e.g. Outbound Arrival and Return Arrival).

**Comment by zyc9012** [comment]
We've released the support for this.

Now you can specify four numbers in `outbound_times` and `return_times`. E.g. `2,7,3,8`, with the first two being departure time range and last two bing arrival time range.

Check out [Documentation](https://serpapi.com/google-flights-api#api-parameters-advanced-filters-outbound-times) for more examples.
