### ISSUE TITLE
[Google Hotel Property Details API] API returns empty results

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1491]
A user reported that our Google Hotel Property Details API has not been working since today.
Currently, the example from the playground is not returning results either.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061464?view=List) | [Playground](https://serpapi.com/playground?engine=google_hotels&q=Bali+Resorts+hotel&gl=us&hl=en&currency=USD&check_in_date=2024-03-21&check_out_date=2024-03-22&adults=2&property_token=ChcIp6zKtZ6Zu8L-ARoKL20vMGM0MHhmbRAB&no_cache=true&highlight=featured_prices) | [Inspect sample](https://serpapi.com/searches/65fb6dcdd5b1c5e321be1739/inspect)

**Comment by hilmanski** [comment]
Another report on this issue.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061467?view=List)

**Comment by tanys123** [comment]
We have fixed the issue, it is currently returning the data as usual.

<img width="1257" alt="Screenshot 2024-03-21 at 12 52 18 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/23364e5a-45f7-4c57-9c92-968f82e15a9d">
