### ISSUE TITLE
[Google Maps API] Missing review's text on place result

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1492]
A high-volume customer reported that we're missing the review's text/snippet on `most_relevant`on a `place_result` on Google Maps API.

![CleanShot 2024-03-21 at 07 25 26](https://github.com/serpapi/public-roadmap/assets/4522467/e6f909df-a128-4023-a0ce-e31f2ea9e295)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/unassigned/conversation/102910000061459?view=List) | [Playground](https://serpapi.com/playground?engine=google_maps&q=bitter+melon+toronto&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&type=search) | [Inspect](https://serpapi.com/searches/65fa94598ccee03685a14bce/inspect)

**Comment by kagermanov27** [comment]
We have released a fix for this.
The `description` fields of reviews are now extracted for this layout:

Before:
<img width="1153" alt="maps-old" src="https://github.com/serpapi/public-roadmap/assets/73674035/6e36b4b9-7bc8-4f27-97c8-5284314d1169">

After:
<img width="1153" alt="maps-new" src="https://github.com/serpapi/public-roadmap/assets/73674035/1a2ebad1-e46a-4fa1-845c-37f15d8c389b">
