### ISSUE TITLE
[DuckDuckGo API] Search return an empty result

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1494]
A potential customer reported this issue during testing SerpApi:
DuckDuckGo returned an empty result.

![CleanShot 2024-03-21 at 10 37 56](https://github.com/serpapi/public-roadmap/assets/4522467/ea10cdfe-5be2-436f-9f27-3ad6b6685483)

[Inspect](https://serpapi.com/searches/65fabf9aa5ad6da1c2189c3a/inspect) | [Playground: successful now](https://serpapi.com/playground?engine=duckduckgo&q=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD756&kl=us-en) 

*Currently, the displayed layout seems weird as well: 
![CleanShot 2024-03-21 at 10 40 18](https://github.com/serpapi/public-roadmap/assets/4522467/fa9823f6-3f95-43cf-8f17-fdc3060712f5)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061470?view=List)

**Comment by aciddjus** [comment]
Let's add a validator for checking if HTML contains `DDG.deep.anomalyDetectionBlock`.
