### ISSUE TITLE
[Google Search API] Inline images not parsed

### ISSUE THREAD

**Issue by godzkh** [serpapi/public-roadmap#1498]
https://serpapi.com/playground?q=Antelope+Valley+Poppy+Reserve&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+votes+as_qdr+stick+highlight+lr+safe+google_domain+si+form+filter+as_epq+client

<img width="1677" alt="image" src="https://github.com/serpapi/public-roadmap/assets/10443630/608c389d-8449-4db2-a835-1469b8d89ce1">

This query has image onebox, but the serp result does not have inline_images.

**Comment by godzkh** [comment]
Any update on this bug? Thanks a lot.

**Comment by djsegal** [comment]
@godzkh, the update addressing the issue with the inline images not being parsed correctly is now live. We're optimistic this enhancement will provide a smoother experience with our service. Should you encounter any further issues, don't hesitate to reach out. Your ongoing support and usage of our platform are greatly appreciated

**Comment by godzkh** [comment]
Thanks a lot! :)
