### ISSUE TITLE
[Apple App Store API] Adjust `review_date` documentation

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1499]
One of our customers noted that our documentation is unclear, as it indicates that we can scrape the time of the review, where, in fact, we're only scraping the date:

Documentation:
<img width="1245" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/4593aa69-2e35-4507-99aa-75d393b32bdd">

Actual results:
<img width="1670" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/8ac6a142-e044-4e98-8d0f-a896a331db0c">

[Playground](https://serpapi.com/playground?engine=apple_reviews&product_id=534220544) | [Documentation](https://serpapi.com/apple-reviews#api-examples-json-structure-overview)

**Comment by ocvit** [comment]
Docs have been updated.

<img width="1189" alt="Screenshot 2024-08-28 at 17 05 54" src="https://github.com/user-attachments/assets/eaa2fb69-6192-41d1-8a6c-aa406c4ff6cb">
