### ISSUE TITLE
[Google Trends Trending Now] Searches with `frequency=realtime` and `cat` failing sometimes

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1500]
A user reported that searches are failing when `frequency=realtime` and `cat` parameters are provided in the request. I was able to reproduce it in our playground after executing a few requests with `no_cache=true`.

![image](https://github.com/serpapi/public-roadmap/assets/144151895/d7028d85-c394-4a29-95a1-84a9c64daed6)

[Playground](https://serpapi.com/playground?engine=google_trends_trending_now&frequency=realtime&geo=US&hl=en&cat=t&no_cache=true) | [Inspect](https://serpapi.com/searches/6601a4b18cd878a1ab24ad7c/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061930?view=List)

**Comment by hartator** [comment]
We've released a fix for this.

This should work now without having to retry manually the request. 👍
