### ISSUE TITLE
[Google Health Insurance API] All requests fail

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1501]
Currently, valid requests sent to the Google Health Insurance API seem to fail.

<img width="1414" alt="Screenshot 2024-03-25 at 1 01 23 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/d249d868-05bd-4db2-b924-c89bf853cb70">

[Playground 1](https://serpapi.com/playground?engine=google_health_insurance&provider_id=/g/11fhjcx8yt) | [Playground 2](https://serpapi.com/playground?engine=google_health_insurance&provider_id=/g/11g1z34nf9) | [Playground 3 ](https://serpapi.com/playground?engine=google_health_insurance&provider_id=%2Fg%2F11g1z34nf9)

[Inspector 1](https://serpapi.com/searches/6601d65af8f5f7e2e833aa22/inspect) | [Inspector 2](https://serpapi.com/searches/6601d645f716eed1035b36f1/inspect) [Inspector 3](https://serpapi.com/searches/6601d5b3c47d3cebe261b71d/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061968?view=List)

**Comment by djsegal** [comment]
Were you able to get `google_health_insurance_url` to work? I was getting the following response from Google:

<img width="1600" alt="Screenshot 2024-03-25 at 10 37 55 PM" src="https://github.com/serpapi/public-roadmap/assets/3156114/1ecb71f5-4b80-4303-a70d-4415e9717db7">

**Comment by schaferyan** [comment]
Thanks, @djsegal. After further investigation, it appears Google may have discontinued this feature. I haven't been able to get `google_health_insurance_url` to work. I also can't find a knowledge graph that currently has the health insurance URL.

**Comment by schaferyan** [comment]
Given that it's on Google's side, I'm closing this issue for now. We can reopen it if Google re-enables support for this feature.

**Comment by hilmanski** [comment]
Related to https://github.com/serpapi/SerpApi/pull/4687

**Comment by hartator** [comment]
Added a deprecation warning in https://github.com/serpapi/SerpApi/pull/4687: https://serpapi.com/google-health-insurance-api.
