### ISSUE TITLE
[Youtube Video API] Scrape Youtube video subtitles/captions

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1502]
A user asked if we could scrape the subtitles/caption from a YouTube video.

Based on my investigation, I believe it's possible:

![CleanShot 2024-03-26 at 08 52 35](https://github.com/serpapi/public-roadmap/assets/4522467/d9c84932-c386-4c71-813e-237235a05423)

![CleanShot 2024-03-26 at 08 53 14](https://github.com/serpapi/public-roadmap/assets/4522467/5f4cf263-e9a5-4f6c-ad21-a219d6b46cdf)

We may need to add a separate engine for this. But I can see that it can be useful for some companies to get this data.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000061915?view=List)

**Comment by hartator** [comment]
It's too outside of our mission.

**Comment by hilmanski** [comment]
Another user asked about this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069861?view=List)

**Comment by hilmanski** [comment]
A customer is interested in this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069403?view=List)

**Comment by hilmanski** [comment]
I'll share the video transcript new API information to these users.
