### ISSUE TITLE
[Google Flight API] Support multi city search

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1503]
A user asked if we can perform a "multi city" search on our Google Flight API.

This feature is supported by Google Flight search.
![CleanShot 2024-03-26 at 12 57 32@2x](https://github.com/serpapi/public-roadmap/assets/4522467/f5a181b2-97b6-402e-bd9c-45cafba73167)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062026?view=List)

**Comment by marm123** [comment]
A user requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067039)

**Comment by corear** [comment]
Is this not going to be implemented anytime soon?

**Comment by marm123** [comment]
Hi @corear, thank you for reaching out. Unfortunately, I can't share any ETA for when the feature will be implemented. However, I'll bump this in our queue and change the status to `queued`. We'll get back to you once it's finished.

**Comment by stedelmanto1** [comment]
Thanks for finally queueing this! Really needing this functionality

**Comment by stedelmanto1** [comment]
Hi- just wanted to add that for the multi city a key requirement is to be able to add multiple flights (ex: SFO->EWR, EWR->IAH, IAH->ORD), not just a two destination itinerary (ex: SFO->EWR, EWR->IAH). Google flights supports this functionality with the + button when in multi city search mode.

**Comment by hilmanski** [comment]
A customer requested for this feature.

[Front](https://app.frontapp.com/open/msg_2esrny58?key=4X50hIyVmJQedEbDUaMa7zG6TbapAcI3)

**Comment by vuemix** [comment]
We are the customer that recently requested the feature. From google's end, the only key difference between one-way, round-trip, and multi-city is what Serp calls 'type'. Multi-city is type 3. The high-level problem is Serp's API is designed around single departure and arrival ID whereas Google Flight (and every other Flight API I know of e.g. Duffel, Amadeus, TravelPort, etc.) use arrays. Google Flight's native API request is organized roughly like below regardless of type:

{
     type: 1/2/3,
     cabin: <cabin type>,
     passengers: <passenger counts>,
     price-range: <range>,
     route: [ { origin: <code>,
                    destination: <code>,
                    departure-date: <date>,
                    timeofday: <timecode>,
                    stops: <stopcode>,
                    include-airlines:
                    exclude-airlines:
                    ...
                  },  
                  { origin: <code>,
                    destination: <code>,
                    timeofday: <timecode>,
                    ...
                   },
                  ...
                ]
}

which not only has an array of origin/dest but pulls in many of the filters on a per-segment basis.  The departure_token / booking_token would likely be similar except there would be multiple departure_token steps as the desired segments get selected for each leg of the itinerary.

**Comment by zyc9012** [comment]
@vuemix Thanks for your information. We were aware of the multi-city option when we designed this API. We didn't make the request to be an array because we wanted users to get started with it more easily.

We are now working on this and will allow users to send arrays for multi-city flights.

**Comment by zyc9012** [comment]
We've released the multi-city support. Please refer to https://serpapi.com/google-flights-api#api-parameters-advanced-google-flights-parameters-multi-city-json for documentation.

[Example Playground](https://serpapi.com/playground?engine=google_flights&gl=us&hl=en&currency=USD&type=3&travel_class=1&multi_city_json=%5B%7B%22departure_id%22%3A%22CDG%22%2C%22arrival_id%22%3A%22NRT%22%2C%22date%22%3A%222024-08-20%22%7D%2C%7B%22departure_id%22%3A%22NRT%22%2C%22arrival_id%22%3A%22LAX%2CSEA%22%2C%22date%22%3A%222024-08-27%22%7D%2C%7B%22departure_id%22%3A%22LAX%2CSEA%22%2C%22arrival_id%22%3A%22AUS%22%2C%22date%22%3A%222024-09-03%22%2C%22times%22%3A%228%2C18%2C9%2C23%22%7D%5D)

![image](https://github.com/user-attachments/assets/aeedca5f-4541-4ff9-9bfa-9661c23be4b0)

**Comment by hilmanski** [comment]
Thank you very much, @zyc9012 !

**Comment by stedelmanto1** [comment]
Amazing!! Thank you very much!
