### ISSUE TITLE
[Baidu Search API] Missing `snippet` 

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1505]
A user reported that Baidu search responses seem to be missing the `snippet`.

<img width="1100" alt="Screenshot 2024-03-26 at 3 31 49 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/9583831e-cf2b-46a4-8ec4-585e8b47b145">

[Inspector](https://serpapi.com/searches/66034a7c66440a073cda1b51/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062121?view=List) | [Playground](https://serpapi.com/playground?engine=baidu&q=Coffee)

**Comment by zyc9012** [comment]
We've released a fix for this.

`snippet` is showing again.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/f6e41712-851f-4fca-aa34-51489805dca3)
