### ISSUE TITLE
[Google Maps Reviews API] Get exact date / iso date of the review

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1508]
A high-volume customer requested that we scrape the actual review time. Not just "a week ago" or so.

I can see the timestamp data is available at the request as well.

![CleanShot 2024-03-27 at 11 44 17](https://github.com/serpapi/public-roadmap/assets/4522467/2b0974f3-48b1-4c14-8579-068ea7814687)

We can put it as iso_date like what we did in the Google Play Product API: https://github.com/serpapi/public-roadmap/issues/1473

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000061465?view=List)

**Comment by zyc9012** [comment]
Unfortunately, the precise timestamp is not present in the endpoint we use. We may support this once we switch to a new endpoint.
