### ISSUE TITLE
[Google Images Searches] Suggested searches are missing

### ISSUE THREAD

**Issue by hartator** [serpapi/public-roadmap#151]
Suggested searches have started missing from our Google Images Search API:

![image](https://user-images.githubusercontent.com/307597/169409677-212ec7a9-3370-4850-8cba-902192d2548d.png)

Playground: https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=isch
Search: https://serpapi.com/searches/6286af861988e59da0b6d05b/inspect
Intercom: https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000025328

Should have looked something like this according to our documentation:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/307597/169409871-cb4de0ef-fd8d-4d5c-99d7-61fa2d9da1be.png">

Ref: https://serpapi.com/images-results

**Comment by aciddjus** [comment]
Resolved in: https://github.com/serpapi/SerpApi/pull/2830
