### ISSUE TITLE
[Apple App Store Reviews API] Explore the possibility of adding the `iso_date` in the JSON response

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1512]
One of our customers requested us to scrape the `iso_date` in the Apple App Store Reviews API, similar to how we implemented it in https://github.com/serpapi/public-roadmap/issues/1473
However, I'm unsure if the endpoint we're using allows us to do that, or if it's not the case similar to Google Maps Reviews API (https://github.com/serpapi/public-roadmap/issues/1508)
It is also related to the following thread https://github.com/serpapi/public-roadmap/issues/1499 as it's implied that we might potentially have a way to extract the exact `review_date` in our Documentation.

![image](https://github.com/serpapi/public-roadmap/assets/28161162/b6781a8f-7d3a-437b-acdc-b783d25adbb2)

We can explore this and potentially implement it in the future or close the thread if it's not applicable to this API.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000058606?view=List)

**Comment by ocvit** [comment]
Apple Product Reviews API provides `review_date` in a plain text format only, so we can close this feature request as not planned.

Docs have been updated.

<img width="1189" alt="Screenshot 2024-08-28 at 17 05 54" src="https://github.com/user-attachments/assets/a6ca9fea-ea50-4942-b204-d6e7df1a8a2e">

**Comment by ocvit** [comment]
Apple Product Reviews API provides `review_date` in a plain text format only, so we can close this feature request as not planned.

Docs have been updated.

<img width="1189" alt="Screenshot 2024-08-28 at 17 05 54" src="https://github.com/user-attachments/assets/aafa8bdb-b683-47c1-a06d-b7566914e038">
