### ISSUE TITLE
[Google Search API] Local news are not scraped in `top_stories` section on `mobile`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1513]
While checking for `top_stories`, I've noticed that some of them are missing on the `mobile`.

Based on the `desktop` response, the Local news section, should be scraped into the `top_stories` block of the JSON response:
<img width="1669" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/31feca23-1f2d-4abc-b5e3-289e5e4852cd">

However, this is not scraped at all on the `mobile`:
<img width="1669" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/b28bb8e7-2de1-453d-ae9f-ff40dae5fbbe">

Given our recent issues with `top_stories` and the fact that our high-volume users rely on this information, and it's incomplete, I'm marking it as prioritized.

[Playground](https://serpapi.com/playground?q=Live+news&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile) | [Inspect](https://serpapi.com/searches/660516001baebbdd998fd662/inspect)

**Comment by zyc9012** [comment]
We've released the support for the "Local News" block, it's now served as `local_news`. Visit [Documentation](https://serpapi.com/local-news) for more information.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/2b2fe38b-ec3d-43ae-9f7e-b1f66639c3e6)
