### ISSUE TITLE
[Google Search API] Only ~2 Organic Results Returned 

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1516]
A user provided a few examples of searches that only return a few results, though they should return more.

While it's normal to return a varying number of `organic_results` (i.e 8 or 9 instead of 10), especially on the first page, these searches only provide 1 or 2 results.

The examples used `num=100` and `device=mobile`. However, other searches may be affected as well. I was unable to replicate it on my side, even retrying the user's searches many times with `no_cache=true`.

<img width="964" alt="Screenshot 2024-03-28 at 2 51 58 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/67f5b5bd-96c0-4662-8150-6cccd1af7474">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062351?view=List) | [Playground](https://serpapi.com/playground?q=best+sports+betting+sites&location=United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client) | [Search Inspector 1](https://serpapi.com/searches/6605d8d3a3f4ef0b6063548d/inspect) | [Search Inspector 2](https://serpapi.com/searches/6605d885f55d77aa03d1a8ff/inspect)

**Comment by hartator** [comment]
I think this is the expected JSON as the HTML returned by Google does contain not that many results. Probably because it's mobile and the new infinite scrolling.

**Comment by schaferyan** [comment]
@hartator do you think there might be a way to avoid this behavior from Google? So far it only seems to affect a handful of queries, and retrying with `no_cache=true` should be fine as a workaround.  But if this becomes more common it will be very inconvenient for some of our customers.

**Comment by hartator** [comment]
> [Search Inspector 1](https://serpapi.com/searches/6605d8d3a3f4ef0b6063548d/inspect) | [Search Inspector 2](https://serpapi.com/searches/6605d885f55d77aa03d1a8ff/inspect)

These 2 look valid; it's just Google having more rich results than the usual.

Google is slowly phasing out `num` parameter in favor of infinite scrolling otherwise.
