### ISSUE TITLE
[Google Maps Reviews API] Scrape `place_info`

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1517]
To fix #1515, which effectively disabled the Google Maps Reviews API entirely, we needed to use a different endpoint. However, so far we are unable to scrape the `place_info` using this endpoint. A few customers requested we re-enable support for scraping the `place_info` key, as it is important for their use case.

[Intercom 1](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062418?view=List) | [Intercom 2](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000062398?view=List) | [Inspector](https://serpapi.com/searches/6606af2ece87f8f453d56cb6/inspect)

**Comment by schaferyan** [comment]
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062422?view=List)

**Comment by marm123** [comment]
Another customer reported it:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062549?view=List)

**Comment by schaferyan** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062585?view=List)

**Comment by marm123** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062699?view=List)

**Comment by hilmanski** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062757?view=List)

**Comment by martin-serpapi** [comment]
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062880?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062659?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062882?view=List)

**Comment by maucherOnline** [comment]
Any update on this? This issue broke a core feature of our app overnight. Customers are begging us to turn it back on again and we don't know what to tell them.

**Comment by zyc9012** [comment]
We've released a fixed for this. `place_info` has been restored.

Please note that from now on, `place_info` will only be returned from the first page results. Pagination requests (with `next_page_token` set) won't have `place_info`.

**Comment by maucherOnline** [comment]
Lifesaver!
