### ISSUE TITLE
[Yandex Video API] Video data is empty

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1519]
A customer reported that our Yandex Video API only returns position information.

![CleanShot 2024-04-01 at 07 52 05](https://github.com/serpapi/public-roadmap/assets/4522467/834411a3-3b6a-4731-94be-ae3945a32c68)

[Inspect](https://serpapi.com/searches/6609f6ca0a90c7df4891ac1e/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062516?view=List)

**Comment by aciddjus** [comment]
This issue has been resolved.

In addition to again extracting all of the results, we are now also parsing `channel` data.

![image](https://github.com/serpapi/public-roadmap/assets/6929257/f60237ea-a9f2-47ee-8109-be212d49283d)

-----------

[Playground link](https://serpapi.com/playground?engine=yandex_videos&text=Coffee&no_cache=true)
