### ISSUE TITLE
[Google Images API] Most of the fields for `images_results` entries are missing in the response for the first page of results

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1522]
Only the `position`, `thumbnail`, `original` and `is_product` fields are returned in the response from our Google Images API for the first page of results:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/46d76026-3262-4707-a172-a324a7389a95)

[Playground](https://serpapi.com/playground?engine=google_images&q=Coffee&gl=us&hl=en&no_cache=true) | [Inspect](https://serpapi.com/searches/660be1fab5961e3866795fa9/inspect)

The results from the second page seem to contain all the fields except `is_product`:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/0841f59b-de54-44c9-8607-6f7e185da944)

[Playground](https://serpapi.com/playground?engine=google_images&q=Coffee&gl=us&hl=en&ijn=1&no_cache=true) | [Inspect](https://serpapi.com/searches/660be29e2bc7d8a52cfbcdaa/inspect)

**Comment by aciddjus** [comment]
This issue has been resolved.

We are again extracting full `images_results` on both desktop and mobile.

<img width="1250" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/5a85a398-466c-44ad-bca9-92b14564fa1b">

-------------

[Playground](https://serpapi.com/playground?engine=google_images&q=Coffee&gl=us&hl=en&device=desktop&no_cache=true)
