### ISSUE TITLE
[Google Images API] Support `uds` for `Suggested searches`

### ISSUE THREAD

**Issue by aciddjus** [serpapi/public-roadmap#1523]
Google could be deprecating `chips` parameter and has started using a combination of `uds` and `udm` parameters to achieve the same outcome. 

![image](https://github.com/serpapi/public-roadmap/assets/6929257/0c0a0f39-26c4-4d11-a226-329fcf6fa65b)

----------------

[Documentation](https://serpapi.com/google-images-api#api-examples-json-structure-overview) | [Playground](https://serpapi.com/playground?engine=google_images&q=Coffee&gl=us&hl=en&device=desktop&no_cache=true) | [Inspect](https://serpapi.com/searches/660c06aac504e915179cf647/inspect)

**Comment by kagermanov27** [comment]
We have released a fix for this issue. We now support `uds` parameter as well. It has the same use case as `chips` parameter. The majority of the search results from Google Images contain `uds` parameter.

Before:

![image](https://github.com/serpapi/public-roadmap/assets/73674035/a05f6335-1739-4c1e-ab6f-ff21d851b145)

After:

![image](https://github.com/serpapi/public-roadmap/assets/73674035/0203b13d-97b3-468c-9950-09dfc7deee3d)

You can find more details in the [documentation example](https://serpapi.com/google-images-api#api-examples-results-for-apple-iphone-with-uds-suggested-search).
