### ISSUE TITLE
[Google Flights API] Support Multi-City Search

### ISSUE THREAD

**Issue by corear** [serpapi/public-roadmap#1526]
It would be great to have the option to perform multi-city searches as a 3rd search type 
<img width="1053" alt="image" src="https://github.com/serpapi/public-roadmap/assets/15691029/0b0f8c62-9762-4449-9518-ff1049e293ad">

**Comment by hilmanski** [comment]
Thanks @corear . We already opened a feature request for this here: https://github.com/serpapi/public-roadmap/issues/1503
