### ISSUE TITLE
[Google Trends API] All Searches Failing

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1535]
A user reported that currently all searches seem to be failing for the Google Trends API:

<img width="1081" alt="Screenshot 2024-04-10 at 2 01 49 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/5762e5f1-da57-4939-a203-9725ab8697b1">
<img width="1421" alt="Screenshot 2024-04-10 at 2 20 30 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/471dedd7-a439-4047-a270-62820f0d897e">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000063386?view=List) | [Playground](https://serpapi.com/playground?engine=google_trends&q=Coffee&data_type=RELATED_QUERIES) | [Inspector](https://serpapi.com/searches/6616fcae1baebb2d758ef999/inspect)

**Comment by schaferyan** [comment]
This should be fixed now

**Comment by Freaky** [comment]
![1535-fix](https://github.com/serpapi/public-roadmap/assets/58758/59c58b34-3f90-42c6-8b9b-e66fb7471571)
