### ISSUE TITLE
[Google Images API] Add support for `imgar` parameter

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1536]
A customer reported that the `tbs=iar:[s|w|t|p]` does not work for filtering the results from the Google Images API by Aspect Ratio. I was able to reproduce it in the Playground:

<img width="1427" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/46d92ba6-e23a-4fcf-b31a-455f431d9498">

[Playground](https://serpapi.com/playground?engine=google_images&q=Coffee&gl=us&hl=en&tbs=iar%3As) | [Inspect](https://serpapi.com/searches/661791481baebba1d5f10edc/inspect)

The parameter doesn't seem to work in Google either. Below is an example with the value of `google_images_url` from the previous response:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/e2b2b28a-2ef8-495c-a963-0eeb192dd213)

[Google Images](https://www.google.com/search?q=Coffee&oq=Coffee&hl=en&gl=us&tbm=isch&tbs=iar:s)

However, using `imgar=[s|w|t|p]` works for filtering images by their Aspect Ratio in Google:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/ef395fbc-bb85-4a70-b1fe-16383baa8748)

[Google Images](https://www.google.com/search?as_q=Coffee&imgar=s&udm=2)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062074?view=List)

**Comment by btaunt** [comment]
We now support the `imgar` parameter for Google Images API.

- [Playground Example (square setting)](https://serpapi.com/playground?engine=google_images&q=Coffee&gl=us&hl=en&imgar=s&newPara=chips+related_content_id)
- [Playground Example (old `tbs:iar` forwarding)](https://serpapi.com/playground?engine=google_images&q=Coffee&gl=us&hl=en&tbs=iar%3As&newPara=chips+related_content_id)
- [Documentation](https://serpapi.com/google-images-api#api-examples-results-for-coffee-with-set-imgar-aspect-ratio-square)

## Extras
- Previous searches using the deprecated `tbs=iar:[s|w|t|p]` will still work, by forwarding through the new `imgar`
