### ISSUE TITLE
[Google Search API] Website missing in `knowledge_graph`

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1540]
A high-volume customer reported that the website is missing in the `knowledge_graph` in the response from our Google Search API. I was able to reproduce it in the Playground:

<img width="1413" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/5f6694d8-47a0-46e5-8b04-474b5cabca8a">

[Playground](https://serpapi.com/playground?q=Pho+95+Noodle+House+1401+S+Federal+Blvd&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/661800b52c6878e770cb60b0/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000063450?view=List)

**Comment by btaunt** [comment]
This has been resolved. We now parse this instance of the `website` button link inside the `knowledge_graph`:

<img width="617" alt="Screenshot 2024-04-11 at 3 13 03 PM" src="https://github.com/serpapi/public-roadmap/assets/137819397/3b582172-1790-444a-8bc0-870e43c620ed">

[Playground Example](https://serpapi.com/playground?q=Pho+95+Noodle+House+1401+S+Federal+Blvd&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+source+votes+site+ie+oe+pws+ibp)
