### ISSUE TITLE
[Google Search API] `organic_results` -> `latest_news` not extracted for some searches

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1541]
![image](https://github.com/serpapi/public-roadmap/assets/73674035/76a4ca23-5a34-4577-ac04-39d22f6c8a23)

[Playground](https://serpapi.com/playground?device=mobile&engine=google&gl=us&google_domain=google.com&hl=en&location=Austin%2C+Texas%2C+United+States&q=NFL)
[Inspect](https://serpapi.com/searches/66180f1610d744cb0d751051/inspect)

The desktop counterpart is successfully parsing:
<img width="1453" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/30f5bb95-bd64-4e1f-8e34-6aaa268be799">

Also, `organic_results` -> `latest_news` is not documented.

**Comment by Alaa-abdulridha** [comment]
`latest_news` in the `organic_results` wasn't extracted (on mobile).

With this fix, we're successfully extracting the `latest_news` into the `organic_results` (on mobile).

**Before (Production with the issue):** 
![image](https://github.com/serpapi/public-roadmap/assets/53356539/3ec7d491-1da7-4490-9040-e501358b89ea)

**After (Development - fixed):**

![image](https://github.com/serpapi/public-roadmap/assets/53356539/8a9c1db9-3372-452a-87a7-2bd42dc0491f)
