### ISSUE TITLE
[Bing Shopping API] Include `filters` field in the response

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1545]
A high volume customer requested that we include a `filters` field in the response of our Bing Shopping API. Currently this is not available:

<img width="1365" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/9fa3e8ae-e988-426a-9320-5f6e7dc2c13d">

[Playground](https://serpapi.com/playground?engine=bing_shopping&q=Coffee&mkt=en-us) | [Inspect](https://serpapi.com/searches/661d147d3944b08d85f9a6e8/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000063545?view=List)

**Comment by Ovi** [comment]
We now parse filters and filtered results.

<img width="1728" alt="Screenshot 2024-10-06 at 9 23 00 PM" src="https://github.com/user-attachments/assets/77ca0eaf-474f-4058-986a-c27f216ce576">

[Playground](https://serpapi.com/playground?engine=bing_shopping&q=Coffee&mkt=en-us)


<img width="1716" alt="Screenshot 2024-10-06 at 9 24 14 PM" src="https://github.com/user-attachments/assets/ea4f719d-bdce-48fd-a3d4-5ad478259bfe">

[Playground (with filter selected)](https://serpapi.com/playground?engine=bing_shopping&q=Coffee&mkt=en-us&filters=gsfilter%253A%2522MzA4NDMyODMzMixCYXNpYywwPTMzMzY3NDM3ODcsVHwxNjY2MTAxNTU0LEZ8Mzk3Nzc4NzkxMSxGfDE2NDQ4NzI3OTEsRnwyMDE1OTE1MTM0LEZ8MTY2Mjg3OTEzNixGfDM5OTU4NTg2MTYsRnwxODkxMzU4OTA4LEZ8MzIyMzgxOTIzMyxGfDgxMjAyODEzNCxGfDM4MjUxMTEzNzEsRnwyODI1MzE4NzcwLEZ8MTExMzYyNDE2MCxGfDMwODU5NDc5NTQsRnw1NjgxMjEwNTEsRnw7%2522%2Bscenario%253A%252215%2522&device=desktop&no_cache=true)
