### ISSUE TITLE
[Google Search API] live label in Top Stories is missing

### ISSUE THREAD

**Issue by githubfan21** [serpapi/public-roadmap#1546]
- json feed used to have an identifier in top_stories items for "live", it is no longer there. It stopped in March 23
- this is a critical identifier 
- example: https://serpapi.com/playground?q=trump+trial&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&newPara=ie+oe+pws+ibp+kgmid

![image](https://github.com/serpapi/public-roadmap/assets/15785331/88527c8e-4c64-49e6-9ae9-3ec02eb13eed)

this is what it used to be
![image](https://github.com/serpapi/public-roadmap/assets/15785331/80f21fc5-b3cf-4143-8b10-67a331bc309d)

**Comment by tanys123** [comment]
We have deployed a fix to the issue

<img width="1171" alt="Screenshot 2024-04-16 at 8 28 56 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/5c39dabd-0489-46db-94a6-9b1ceb6899b5">
