### ISSUE TITLE
[Google Play Product API] Scrape the Number of Reviews for Each Rating

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1547]
For Google Play products, the number of reviews with each rating is displayed in the mouse tooltip when hovering over the graph. A customer requested we scrape this information. It appears to be available in the HTML.

<img width="1321" alt="Screenshot 2024-04-15 at 2 23 18 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/46ec22a7-1d6c-4799-882f-bea8676d221a">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000063650?view=List) | [Google Play](https://play.google.com/store/apps/details?id=com.reverylab.pocketkado.prod) | [Playground](https://serpapi.com/playground?engine=google_play_product&product_id=com.google.android.youtube&gl=us&store=apps&platform=phone&sort_by=1)

**Comment by ilyazub** [comment]
Let's structure the output similarly to our other APIs.

```json
{
  "reviews_results": {
    "rating": [
      {
        "stars": 1,
        "count": 87
      },
      {
        "stars": 2,
        "count": 90
      },
      {
        "stars": 3,
        "count": 432
      },
      {
        "stars": 4,
        "count": 1102
      },
      {
        "stars": 5,
        "count": 6677
      }
    ],
  }
}
```

Google Product ([documentation](https://serpapi.com/google-product-api))

![image](https://github.com/serpapi/public-roadmap/assets/282605/3cde06e7-70ce-4fb4-9d47-cee47cae7b5f)
(ref: https://serpapi.com/playground?engine=google_product&product_id=4887235756540435899&gl=us&hl=en)

Walmart Product ([documentation](https://serpapi.com/walmart-product-api))

![image](https://github.com/serpapi/public-roadmap/assets/282605/b47aad63-c477-4a84-b58f-68512c250953)

(ref: https://serpapi.com/playground?engine=walmart_product&product_id=1123329439)

**Comment by ilyazub** [comment]
> Let's structure the output similarly to our other APIs.
> 
> ```json
> {
>   "reviews_results": {
>     "rating": [
>       {
>         "stars": 1,
>         "count": 87
>       },
>       {
>         "stars": 2,
>         "count": 90
>       },
>       {
>         "stars": 3,
>         "count": 432
>       },
>       {
>         "stars": 4,
>         "count": 1102
>       },
>       {
>         "stars": 5,
>         "count": 6677
>       }
>     ],
>   }
> }
> ```

My mistake, we already have top-level `reviews` in [our Google Play Product API](https://serpapi.com/google-play-product-api). We will keep `reviews` for backwards-compatibility and we'll add top-level `ratings` to the response. I'm sorry about the confusion.

![image](https://github.com/serpapi/public-roadmap/assets/282605/7fbdfde7-75e7-44d8-bb1c-817a1b3e8b8e)
(ref: https://serpapi.com/google-play-product-api)

```ruby
{
  # [...]
  "ratings": [
    # Hashes
  ],
  "reviews": [
    # Review hashes
  ]
  # [...]
}
```

**Comment by ishiharaf** [comment]
@schaferyan This feature is working on production 😺

![image](https://github.com/serpapi/public-roadmap/assets/13112082/dc417898-9718-4e58-a161-03ad663e18ce)

Examples:
- [Playground with Ratings/Reviews](https://serpapi.com/playground?engine=google_play_product&product_id=com.google.android.youtube&gl=us&store=apps&platform=phone&sort_by=1)
- [Playground with no Ratings/Reviews (no errors)](https://serpapi.com/playground?engine=google_play_product&product_id=com.starlight.mobile.app.fixt.vendor&gl=us&store=apps&platform=phone&sort_by=1)
