### ISSUE TITLE
[Google Search API] Scrape Flight Status Answer Box

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1548]
Some Google searches for flight information include a flight status answer box. A user has requested we scrape this.

![2024-04-15 17_15_52-Greenshot image editor](https://github.com/serpapi/public-roadmap/assets/30915304/717790b7-2402-440d-9f3d-d51ffab459b1)
<img width="1401" alt="Screenshot 2024-04-15 at 2 12 36 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/3911560b-e9bb-49ca-9b4a-6ba15dfdd865">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000063666?view=List) | [Playground 1](https://serpapi.com/playground?q=UA160&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client) | [Playground 2](https://serpapi.com/playground?q=flight+austin+to+la&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client) | [Search Inspector 1](https://serpapi.com/searches/661d9ebe0f9866ea969f0cf1/inspect) | [Search Inspector 2](https://serpapi.com/searches/661d9724f0adfb382314dade/inspect)

**Comment by vax-sa** [comment]
+1 Would love to see this supported as well.

**Comment by hilmanski** [comment]
A high-volume customer requested this feature as well. 

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000065733?view=List)

**Comment by schaferyan** [comment]
Changed from freezer to queued since a high volume customer requested it

**Comment by kagermanov27** [comment]
We have deployed a solution for this issue:

<img width="1349" alt="image" src="https://github.com/user-attachments/assets/b7026a40-7f69-4589-acd4-f66d8682d890">

We weren't able to recreate the second layout in the issue successfully. The first layout can be accessed at `answer_box`.
