### ISSUE TITLE
[Google Scholar API][Documentation] Clarify max value of `num` parameter

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1549]
A customer reached out to ask what the maximum value for `num` is with the Google Scholar API. They had trouble finding this in our documentation.

While we currently state that `num` is limited to 20, there might be a way to word this that would make it easier to find. For example, instead of 

>Parameter defines the maximum number of results to return, limited to 20. (e.g., 10 (default) returns 10 results, 20 returns 20 results).

We could write:

>Parameter defines the maximum number of results to return (e.g., 10 (default) returns 10 results, 20 returns 20 results). The maximum value Google Scholar supports for `num` is 20.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000063672?view=List)

**Comment by Ovi** [comment]
Updated documentation for clarity.

[Documentation](https://serpapi.com/google-scholar-api#api-parameters-pagination-num)

<img width="359" alt="image" src="https://github.com/user-attachments/assets/e564cd9b-b1bd-4d93-84c5-98d2e19875c2">
