### ISSUE TITLE
[Google Finance API] Error when adding window at Currency searches

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1551]
A user reported that upon searching currency data with window parameter it shows an error. I'm able to replicate this.

It should return the data just fine: https://www.google.com/finance/quote/EUR-ARS?hl=en&window=5D

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000063760?view=List) | [Inspect](https://serpapi.com/searches/661f5228969c0863ebfaac77/inspect) | [Playground Link](https://serpapi.com/playground?engine=google_finance&hl=en&q=EUR-ARS&window=5D)

**Comment by aciddjus** [comment]
The issue is that the query has a `-` sign instead of a `:` sign. And we are not properly handling queries with `-` sign when using `window` parameter.

**Comment by aciddjus** [comment]
This issue has been resolved.

Using `window` parameter now works with all queries.

<img width="1372" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/b0a68a18-5091-4572-a452-3890fb16be53">


-----------

[Playground](https://serpapi.com/playground?engine=google_finance&q=EUR-ARS&hl=en&window=5D)
