### ISSUE TITLE
[Google News API] Wrong thumbnail URL in the response when using a `story_token`

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1556]
A user reported that a wrong thumbnail URL is returned in the response when using a `story_token`. I was able to reproduce it in the Playground.

<img width="1434" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/e3dc6a06-b387-480c-b006-e1101fde67fe">

[Playground](https://serpapi.com/playground?engine=google_news&gl=us&story_token=CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lXb3B5OEN4SGZfVlpaRVc5bTB5Z0FQAQ) | [Inspect](https://serpapi.com/searches/662133dea74fe02c6121220b/inspect)

If I change the URL to https://news.google.com/api/attachments instead of https://news.google.com/apiapi/attachments an image is returned successfully.

[Inspect](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000063854?view=List)

**Comment by aciddjus** [comment]
This issue has been resolved.

We are now extracting the correct thumbnail URL and have fixed thumbnails not loading in HTML.

![image](https://github.com/serpapi/public-roadmap/assets/6929257/b3456db9-4a32-41c6-808e-64368bdb3bb9)


---------

[Playground](https://serpapi.com/playground?engine=google_news&gl=us&story_token=CAAqNggKIjBDQklTSGpvSmMzUnZjbmt0TXpZd1NoRUtEd2lXb3B5OEN4SGZfVlpaRVc5bTB5Z0FQAQ)
