### ISSUE TITLE
[Google Search API] Wrong `website` URL in Knowledge Graph

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1557]
A high volume customer reported that for some searches we are returning a Google URL for the telephone number as the value of the `website` key in the knowledge graph, instead of the expected URL for the company website. According to the user, this affects about 20% of their searches.

I was only able to replicate this behavior for locations in the UK. I tried several searches for locations in the US and couldn't find any examples of this issue.

<img width="1403" alt="Screenshot 2024-04-18 at 4 57 49 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/5404ac60-5959-4273-b674-bf7b6c9b16a9">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000063891?view=List) | [Search Inspector](https://serpapi.com/searches/662186f8eb690f36b538fcac/inspect) | [Playground 1](https://serpapi.com/playground?q=Young+LDN%2C+228+Westbourne+Grove%2C+London%2C+W11+2RH&location=United+Kingdom&google_domain=google.co.uk&gl=uk&hl=en&device=desktop&google_domain=google.co.uk&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client) | [Playground 2](https://serpapi.com/playground?q=mcdonalds+london+ruston+road&location=United+Kingdom&google_domain=google.co.uk&gl=uk&hl=en&device=desktop&no_cache=true&google_domain=google.co.uk&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client)

**Comment by aciddjus** [comment]
This issue has been resolved.

We are again extracting the correct `website` URL.

<img width="991" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/ff0b6c01-ee31-429c-a0d6-8d9b500adf60">


---------

[Playground](https://serpapi.com/playground?q=Young+LDN%2C+228+Westbourne+Grove%2C+London%2C+W11+2RH&location=United+Kingdom&google_domain=google.co.uk&gl=uk&hl=en&device=desktop&google_domain=google.co.uk)
