### ISSUE TITLE
[Home Depot Product API] Provide Availability Status for Out-of-Stock Items

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1558]
A potential high-volume customer requested that we include the availability status in the response from our Home Depot Product API for out-of-stock items.

<img width="1391" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/9768dc3a-5dc5-4355-a48f-2ae3c65251eb">

[Home Depot](https://www.homedepot.com/p/GE-23-7-cu-ft-French-Door-Refrigerator-in-Fingerprint-Resistant-Stainless-Standard-Depth-ENERGY-STAR-GFE24JYKFS/319240166)

This is currently not available in the response from our Home Depot API:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/246b5ac7-2183-4c58-95b9-6acf9be5392a)

[Playground](https://serpapi.com/playground?engine=home_depot_product&product_id=304177386&delivery_zip=94016) | [Inspect](https://serpapi.com/searches/66227e6ae815afc51fc3d87d/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000063859?view=List)

**Comment by schaferyan** [comment]
A customer also noted that the availability element in our prettified HTML doesn't seem to match what is on the Home Depot page:

![home_depot_screenshot](https://github.com/serpapi/public-roadmap/assets/30915304/9e69fc48-062a-4e56-bd28-9f14ed824cb9)
![home_depot_screenshot2](https://github.com/serpapi/public-roadmap/assets/30915304/a5e928a0-c9a8-4dbe-8c34-814204d74460)

Intercom

**Comment by schaferyan** [comment]
I met with the potential customer mentioned above. They are interested in an Enterprise Plan with us if we can support this.

**Comment by kagermanov27** [comment]
We have released a fix for this issue. We can parse and serve when an item is out of stock at the desired store, but still have fulfillment options now.

Before:

<img width="1467" alt="before" src="https://github.com/serpapi/public-roadmap/assets/73674035/961463dd-832a-4313-b28c-8a3b65a97e44">

After:

<img width="1164" alt="after" src="https://github.com/serpapi/public-roadmap/assets/73674035/a794ffce-ebee-4509-a844-b0acc8285a17">

We have fixed missing `fulfillment` keys for several other layouts.

The absence of the `fulfillment` key is an indicator for an out-of-stock item.
