### ISSUE TITLE
[Google Search API] Hourly Temperature Does Not Reflect the Selected Scale in Weather Answer Box

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1561]
An enterprise customer reported that when searching for temperatures in Celsius, we still seem to be scraping the hourly temperatures from the weather answer box in Fahrenheit.

The other fields are correctly provided in Celsius.

<img width="1414" alt="Screenshot 2024-04-19 at 2 55 20 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/7496eb01-4cfc-40f0-b447-2c64981a0628">

[Search Inspector](https://serpapi.com/searches/6622d90dada54b9b5379a716/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000063986?view=List) | [Playground](https://serpapi.com/playground?q=temperature+austin+celsius&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client)

**Comment by zyc9012** [comment]
We've released a fix for this.

The temperature in `hourly_forecase` is consistent with the unit displayed.

Celsius:

![image](https://github.com/serpapi/public-roadmap/assets/3034310/a673903e-8102-4272-8e08-5e3c5e690399)


Fahrenheit:

![image](https://github.com/serpapi/public-roadmap/assets/3034310/0db8cf84-9439-4b0f-b3c6-30b9f1915485)
