### ISSUE TITLE
[Walmart Product API] Slow response time

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1562]
A high-volume customer reported that yesterday, there was an issue (a lot of errors) with the Walmart Product API. Recently, they reported it's back but much slower than it supposed to be.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000064019?view=List) | [Walmart Product API status page](https://serpapi.com/status/walmart_product)

**Comment by martin-serpapi** [comment]
I'm re-opening the issue as the customer contacted us and reported that their searches are failing again. I've checked their search history and can confirm it.

**Comment by marm123** [comment]
Reopening, as the issue still persists.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000064019?view=List) | [Inspect](https://serpapi.com/admin/searches?user_id=6356a877fe41d026d66e8c90)

**Comment by zyc9012** [comment]
We've released a fix for this.

The API is now stable.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/7e23955b-1680-4909-b278-db3068a0729e)
