### ISSUE TITLE
[Bing Search API] Scrape Events Results

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1563]
A user reached out regarding ticket price information in the events results from search engines. This information is available for some events results in the Bing search engine. However, we don't provide this data in the response from our Bing Search API:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/8cff8210-d950-4bae-9248-7bf6db915563)

[Playground](https://serpapi.com/playground?engine=bing&q=concerts+in+chicago&location=Chicago%2C+Illinois%2C+United+States&mkt=en-us) | [Inspector](https://serpapi.com/searches/66275f23ef7ddaf4961b6fe3/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000064089?view=List)

**Comment by aciddjus** [comment]
[Google documentation for reference](https://serpapi.com/events-results)

------------------

TODO:

- [ ] Add parser to extract results on desktop and mobile
- [ ] Add xray
- [ ] Add tests for desktop and mobile
- [ ] Add documentation
- [ ] Confirm that the solution works using different localization

**Comment by mikemorcerf** [comment]
This ticket is completed:
[Playground Example](https://serpapi.com/playground?engine=bing&q=rock+concerts+in+nyc)

![Screenshot 2024-09-25 at 6 46 35 PM](https://github.com/user-attachments/assets/3cdf5321-9225-4958-9d54-15d82b01eef2)

---

[Documentation for Bing Events Results API](https://serpapi.com/bing-events-results)

![Screenshot 2024-09-25 at 6 48 16 PM](https://github.com/user-attachments/assets/a27fb42d-792d-4cf7-ab08-7bf211aab075)
