### ISSUE TITLE
[Yandex search API] Missing "Реклама" text on displayed link

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1565]
A high-volume customer reported that we're missing the "Реклама" text on displayed link, which is previously there.

![CleanShot 2024-04-24 at 11 45 13](https://github.com/serpapi/public-roadmap/assets/4522467/348521c0-728d-4a43-a1e7-74e6f8b02516)

[Playground link](https://serpapi.com/playground?engine=yandex&text=Цена+на+промышленные+джойстики+Производитель&yandex_domain=yandex.com&lang=ru&lr=1) | [Searches](https://serpapi.com/searches/66288020aa6c95885f791f65/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000064207?view=List)

**Comment by aciddjus** [comment]
This issue has been resolved.

We are again extracting `ads_results` results.

<img width="1863" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/6bbe41b1-8b52-4080-a64e-3510278ee311">

<img width="1863" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/45312074-8da6-46b5-927e-cf843121788d">


-------------

[Playground](https://serpapi.com/playground?engine=yandex&text=%D0%A6%D0%B5%D0%BD%D0%B0+%D0%BD%D0%B0+%D0%BF%D1%80%D0%BE%D0%BC%D1%8B%D1%88%D0%BB%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5+%D0%B4%D0%B6%D0%BE%D0%B9%D1%81%D1%82%D0%B8%D0%BA%D0%B8+%D0%9F%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C&yandex_domain=yandex.com&lang=ru&lr=1)
