### ISSUE TITLE
[Ebay Search API] Support filtering products located in different countries

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1571]
Ebay allows filtering results by the location of given products. This is done with the `_salic` and `LH_LocatedIn` parameters, where the first one defines the country code of a location. The second parameter needs to be included, and the value looks to always be `1`, so it's likely a condition specifying if the filter should be applied or not. 

It's a request from one of our high-volume customers

Search for products located in the United States:
![image](https://github.com/serpapi/public-roadmap/assets/28161162/0a78d294-0e67-4731-bb8e-1476460b61b8)

Search for products located in Australia:
![image](https://github.com/serpapi/public-roadmap/assets/28161162/0b0f877f-b5dc-4478-abf5-6f1cc776dcb6)

Search for products located in Burkina Faso:
<img width="1401" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/3ef3aa4a-ca8f-4148-8d45-316147f3172b">

[Playground](https://serpapi.com/playground?engine=ebay&_nkw=Coffee) | [Inspect](https://serpapi.com/searches/662a135849ecdb59d52af465/inspect) | [Ebay](https://www.ebay.com/sch/i.html?_nkw=Coffee&_salic=1&LH_LocatedIn=1)
[Intercom](https://serpapi.com/admin/users?email=procurement%40cobwebs.com&full_name=&phone=&stripe_customer=&button=)

**Comment by btaunt** [comment]
This feature has been added. We now allow location (country) based searches using the `_salic` parameter:

<img src="https://github.com/serpapi/public-roadmap/assets/137819397/7698e2ad-148b-4057-b598-73555a21ad26" width="400px">

<img width="682" alt="Screenshot 2024-05-03 at 11 08 10 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/981d443f-71ac-4662-8d94-ad0759529bd6">

## References

- Playground example: [here](https://serpapi.com/playground?engine=ebay&_nkw=Coffee&_salic=104&no_cache=true)
- New documentation section: [here](https://serpapi.com/ebay-organic-results#api-examples-example-results-with--salic-2-location-canada)
- Documentation list of all available locations: [here](https://serpapi.com/ebay-location-options)
