### ISSUE TITLE
[Google Search API] `rich_snippet` missing for some entries in `organic_results`

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1574]
A user reported that the `rich_snippet` is missing for some entries in `organic_results`. I was able to reproduce it in the Playground:

<img width="1332" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/f399fd9b-1484-4e0d-8eda-386677069e8c">

[Playground](https://serpapi.com/playground?q=proofratings+(reviews+%7C+capterra)&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/662b6b21ea144207a207b5ae/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000064369?view=List)

**Comment by dm-sheremetiev** [comment]
Actually as I see it happens for the first element but this first element are crucial for me because it represents an element that I find.

![image](https://github.com/serpapi/public-roadmap/assets/99361776/9ca05fbc-a7a1-4fdf-b65d-5c09c675a018)

**Comment by marm123** [comment]
User followed up on this, as this is crucial for their business.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000064369?view=List)

**Comment by tanys123** [comment]
We have fixed the issue and it is now included in the result


<img width="1217" alt="Screenshot 2024-05-03 at 1 32 25 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/42ec1860-3c0f-4f4b-bb78-ffe35d1b44da">
