### ISSUE TITLE
[Account] Auto-renew was not working

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1577]
A customer reported that their auto-renew wasn't working. They had to manually renew their plan.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000064444?view=List) | [User Inspector](https://serpapi.com/admin/users/64a8ef7937014c7eaf6e4d1c)

**Comment by schaferyan** [comment]
Another customer reported this:

[Front](https://app.frontapp.com/open/msg_2fxbxg2k?key=r6XXpbFTVhPrAvkRboJEGXYSqWc7dlbq)

**Comment by hilmanski** [comment]
Another customer reported this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070361?view=List)

**Comment by hilmanski** [comment]
Shared a note from Ryan: "It's possible this is related to the Team feature, as the user who exceeded the quota is not the account owner."

**Comment by hilmanski** [comment]
I've updated the status since this problem occurred multiple times for customers.

**Comment by zyc9012** [comment]
We've released a fix for this. Team members can now trigger auto-renewal successfully.

**Comment by hilmanski** [comment]
Thanks, @zyc9012, I'll follow up with the customers.

**Comment by hilmanski** [comment]
I didn't follow up with [this customer](https://app.frontapp.com/open/cnv_1b9xffj0?key=lN2RvNYtGAU5tjPxBWY_J7aVqTLaUrOy), since it looks like they are a single owner of an account (not a team). This issue is addressed here on the private repo: https://github.com/serpapi/SerpApi/issues/4946
