### ISSUE TITLE
[Google Search News Results API] News are not parsed in the JSON response

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1579]
A high-volume customer reported that they are not getting all `news_results` in the JSON response. I've been able to recreate the issue:

<img width="1670" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/6fdd119a-d3bc-4a78-9e55-04f5cd1d78b6">

[Playground](https://serpapi.com/playground?q=%E5%93%88%E9%A9%AC%E6%96%AF+%E6%B3%95%E5%A1%94%E8%B5%AB&gl=cn&hl=zh-cn&tbm=nws&num=10&device=desktop) | [Inspect](https://serpapi.com/searches/662f3151e815afed699bc483/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000064478?view=List)

**Comment by Alaa-abdulridha** [comment]
This issue has been fixed. All news results now being parsed:

Before applying the fix (Production):

![image](https://github.com/serpapi/public-roadmap/assets/53356539/d80865c6-5233-44fe-b0d2-830b04ac193e)

After applying the fix (Production):

![image](https://github.com/serpapi/public-roadmap/assets/53356539/07ae2793-bc2d-4055-b186-ff1cfd3a037a)
