### ISSUE TITLE
[Google Play Store API] Search Returns No Results

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#158]
It seems that Play Store has changed its search results page's design. No results is returned in our response.

[The Playground](https://serpapi.com/playground?engine=google_play&q=line&gl=us&hl=en&store=apps) | [The Inspect](https://serpapi.com/searches/62945e3dcace96acfae7ccfe/inspect)

<img width="941" alt="playstore" src="https://user-images.githubusercontent.com/64849049/170928498-cf336f33-d165-4a83-82fc-447fa40ae968.png">

**Comment by aciddjus** [comment]
@dimitryzub Yes, a complete redesign of all the pages.

**Comment by aciddjus** [comment]
First I'm going to work on [Google Play Product API](https://serpapi.com/google-play-product-api).

**Comment by hartator** [comment]
Another Intercom thread: https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/conversation/102910000025545

**Comment by hartator** [comment]
Another Intercom thread: https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000025670

**Comment by aliayar** [comment]
Another Intercom thread https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000025789

**Comment by aliayar** [comment]
Another intercom thread: https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000025893

**Comment by aliayar** [comment]
Another Intercom thread: 102910000026070

**Comment by aliayar** [comment]
Another Intercom thread: 102910000026152

**Comment by aciddjus** [comment]
We have fully updated our Google Play Store API to support the new Play Store design.

**Comment by aliayar** [comment]
I will update the users! 👍
