### ISSUE TITLE
[Google Search API] Different results for the same query

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1580]
One of our customers reported that they are getting slightly different results for the same query. I'm not sure if we can do anything with that, as we can't control what Google returns, but maybe there is some underlying issue.

1st search (7 results):
<img width="1333" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/d36e4d02-c4f5-4b4f-b5d8-544f935efeeb">

2nd search (same parameters, 9 results):
<img width="1348" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/252f8989-29fe-4311-b591-05703abe4cc2">

[Playground](https://serpapi.com/playground?q=goltogel&location=South+Jakarta%2C+Jakarta%2C+Indonesia&google_domain=google.co.id&gl=id&hl=id&device=desktop&no_cache=true) | [Inspect 1](https://serpapi.com/searches/662f0e4717f9238721cccdc4/inspect) | [Inspect 2](https://serpapi.com/searches/662f1589a5ad6d67a00bf495/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000064383?view=List)

**Comment by dsojevic** [comment]
The behaviour we're seeing here is, unfortunately, entirely out of our control.

It appears to be much more prominent for queries that would generally return very small result sets and is not dependent on IP/etc.

Here is an example of the same search query (identical URL used to search) returning two sets of results from my computer (static IP):

**Search 1:** 3 results
![image](https://github.com/user-attachments/assets/45468159-fd07-4727-beb0-0c0cb475716a)

**Search 2:** 9 results
![image](https://github.com/user-attachments/assets/5c0723cc-bf84-44f8-9745-3f8842d1facb)
