### ISSUE TITLE
[DuckDuckGo Search API] Empty results when using start parameter

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1584]
A customer reported that our DuckDuckGo search API is not working properly. I believe the issue appears when using `start` parameter.

Here is what our playground shows:
![CleanShot 2024-05-01 at 11 03 10](https://github.com/serpapi/public-roadmap/assets/4522467/6d71b3c2-db75-490f-80a8-f821371b940c)

This might be related to this issue: https://github.com/serpapi/public-roadmap/issues/1297

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000064622?view=List) | [Inspect](https://serpapi.com/searches/6631ac542236e2aa4f8ca339/inspect) | [Playground](https://serpapi.com/playground?engine=duckduckgo&q=turnip%2Bdiet&kl=us-en&safe=-1&df=y&start=25)

**Comment by Alaa-abdulridha** [comment]
This issue has been fixed now, and results are returned as usual.

Before fix (Production):

![image](https://github.com/serpapi/public-roadmap/assets/53356539/8d6a899f-75a8-40ed-9cb4-c626045816f9)

After fix (Production):


![image](https://github.com/serpapi/public-roadmap/assets/53356539/85e61c89-b57c-484c-828c-afdc33f79ff8)
