### ISSUE TITLE
[Google Finance Api] Error when add paramter window to the request.

### ISSUE THREAD

**Issue by mybess00** [serpapi/public-roadmap#1586]
When the `window` parameter is added to the request, an error is returned: `Google Finance has not returned any results for this query`.

The data should be returned well like this:: [https://www.google.com/finance/quote/BRL-EUR?window=5D](https://www.google.com/finance/quote/BRL-EUR?window=5D)

[Playground Example](https://serpapi.com/playground?engine=google_finance&q=BRL-EUR&window=5D)

**Comment by schaferyan** [comment]
Thanks for the issue @mybess00!

You are correct, we don't seem to be processing the `window` parameter correctly. Here is another example:

<img width="1132" alt="Screenshot 2024-05-02 at 11 31 20 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/a91d32df-5bf3-4aef-9fef-1242a5ee6777">

<img width="1400" alt="Screenshot 2024-05-02 at 11 31 12 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/914b9593-03b8-4fdb-80a0-e7226d288127">

[Search Inspector 1](https://serpapi.com/searches/6633dbbce13508ff2f534b24/inspect) |  [Search Inspector 2](https://serpapi.com/searches/6633dbdbd3aba2e4d722ab9e/inspect) | [Playground](https://serpapi.com/playground?engine=google_finance&q=INDEXDJX%3A+.DJI&hl=en&window=MAX&no_cache=true)
