### ISSUE TITLE
[Bing Search API] Include organic results state in the response

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1587]
An Enterprise customer requested that we include the organic results state in the response from our Bing Search API. Currently, this information is not available:

<img width="1335" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/b40936e5-e3d7-46f0-bbe4-f14cc404d7fd">

[Playground](https://serpapi.com/playground?engine=bing&q=nab+plyaffs&location=Austin%2C+TX%2C+Texas%2C+United+States&mkt=en-us&device=desktop&no_cache=true) | [Inspect](https://serpapi.com/searches/6633da451c450aaad97a8d22/inspect) 

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000064844?view=List)

**Comment by btaunt** [comment]
This feature has been added.

We now include the `organic_results_state` within the `search_information`:

- [Playground link](https://serpapi.com/playground?engine=bing&q=nab+plyaffs&location=Austin%2C+TX%2C+Texas%2C+United+States&mkt=en-us&device=desktop&no_cache=true)
- [Documentation](https://serpapi.com/bing-organic-results#api-examples-organic-results-state)
