### ISSUE TITLE
[Google Maps Reviews API] Get last modified Iso date of the review

### ISSUE THREAD

**Issue by pacifistes** [serpapi/public-roadmap#1588]
Hello,

The addition of the ISO date in issue #1508 has been quite useful for obtaining an accurate date on reviews. However, when trying to fetch the latest reviews sorted by 'newest' to avoid scraping all reviews, we encounter a problem as the reviews are sorted by the date of the last modification. Referring back to the image in issue #1508, we can see that the last modification date is also shown (timestamp framed in green).

![317116741-2b0974f3-48b1-4c14-8579-068ea7814687](https://github.com/serpapi/public-roadmap/assets/14248987/e1d83e94-2038-4733-b993-c4d72948ddd6)

Would it be possible to include this field also ?

Thank you for considering this enhancement.

**Comment by zyc9012** [comment]
We've released the support for this. The reviews now have `iso_date_of_last_edit`.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/e8257b76-691e-4cda-9bfb-e3cf8d96b46d)
