### ISSUE TITLE
[Google Search API] Places from Maps are not Parsed

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#159]
The places Google adds to Google search results are not parsed and returned.

[The Playground](https://serpapi.com/playground?q=forno+pizza&location=Milan%2C+Lombardy%2C+Italy&google_domain=google.it&gl=it&hl=it) | [The Inspect](https://serpapi.com/searches/6294dbe8b5961e1dd33f9ca5/inspect)

<img width="946" alt="searchmaps" src="https://user-images.githubusercontent.com/64849049/171118755-a7dd81c8-96c5-4971-b342-6c6e86f670cc.png">

**Comment by r3vit** [comment]
+1 for this one!

Thank you @aliayar for opening this Issue.

We are using SerpApi for an internal strategic tool and the quality of that informations are essential.
