### ISSUE TITLE
[Youtube Video API] No comments on the response

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1591]
Yesterday, I tried to fetch comments on our [Youtube Video API ](https://serpapi.com/youtube-video-api) with no results.

I've tried to add `comments_next_page_token` , `comments_sorting_token.token` to `next_page_token`.

[Related Intercom conversation](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060586?view=List) | [Playground](https://serpapi.com/playground?engine=youtube_video&v=vFcS080VYQ0&next_page_token=Eg0SC3ZGY1MwODBWWVEwGAYyJSIRIgt2RmNTMDgwVllRMDAAeAJCEGNvbW1lbnRzLXNlY3Rpb24%253D) | [Inspect](https://serpapi.com/searches/66356ebec56d93be7884baff/inspect)

**Comment by zyc9012** [comment]
We've deployed a fix for this. Now comments and replies are back.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/86519e9b-4844-4768-a46d-c62064a1c8e7)
