### ISSUE TITLE
[Google Search API] Scrape new sponsored (ads) format

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1594]
I saw a new sponsored format on the Google search result, that's currently not available on the response:
![CleanShot 2024-05-09 at 09 21 59](https://github.com/serpapi/public-roadmap/assets/4522467/476817e2-f40d-4ba5-9385-1e218f206b8c)
* This screenshot is taken from our playground.

[Playground](https://serpapi.com/playground?q=hotels+in+dusseldorf&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source) | [Inspect](https://serpapi.com/searches/663c24bad04d6d7f28794173/inspect)

**Comment by Alaa-abdulridha** [comment]
This issue now Has been resolved:


Before (Production):
![image](https://github.com/serpapi/public-roadmap/assets/53356539/1d32ba0d-1226-44d0-a7e0-1a80781d5904)


After (Production):

![image](https://github.com/serpapi/public-roadmap/assets/53356539/4a461a52-30a8-4eae-8c71-76a92bdbeb59)

**Comment by hilmanski** [comment]
Thank you very much @Alaa-abdulridha for working on this and for the update.
