### ISSUE TITLE
[Google Light Search API] Add Knowledge Graph parser

### ISSUE THREAD

**Issue by aciddjus** [serpapi/public-roadmap#1597]
Let's extract the `Knowledge Graph` on all devices.

<img width="694" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/095e3452-c385-4071-b46c-79e8acd31f72">

------------

[Playground](https://serpapi.com/playground?engine=google_light&q=apple&gl=us&hl=en&google_domain=google.com) | [Inspect](https://serpapi.com/searches/663cc85911c8814918aa8213/inspect) | [Google Search API documentation reference](https://serpapi.com/knowledge-graph)

**Comment by zyc9012** [comment]
We've released the support for knowledge graph.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/96d1cf02-fb01-46e0-94b6-519f45089fa4)
