### ISSUE TITLE
[Google Light Search API] Add Related Questions (People also ask) parser

### ISSUE THREAD

**Issue by aciddjus** [serpapi/public-roadmap#1598]
Let's extract the `Related Questions` on all devices.

<img width="694" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/b8419b3c-6b98-4ccf-81a0-1a6868943fa2">

------------

[Playground](https://serpapi.com/playground?engine=google_light&q=apple&gl=us&hl=en&google_domain=google.com) | [Inspect](https://serpapi.com/searches/663cc85911c8814918aa8213/inspect) | [Google Search API documentation reference](https://serpapi.com/related-questions)

**Comment by tanys123** [comment]
We have deployed Google Light Search's Related Questions. Checkout the [documentation](https://serpapi.com/google-light-related-questions).

<img width="1273" alt="Screenshot 2024-05-28 at 1 45 33 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/1a57347c-d652-4fdc-be10-1576a63f64d2">


If you are looking for faster response time without sacrificing the comprehensive data, feel free to try out [Google Light Search](https://serpapi.com/playground?engine=google_light)
<img width="994" alt="Screenshot 2024-05-28 at 1 46 27 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/d0159a0e-6907-4773-88c3-858560ed2a30">
