### ISSUE TITLE
[Google Light Search API] Add Related Searches parser

### ISSUE THREAD

**Issue by aciddjus** [serpapi/public-roadmap#1599]
Let's extract the `Related Searches` on all devices.

<img width="694" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/373629f1-319c-4d8e-99cf-a7fa36feea21">

------------

[Playground](https://serpapi.com/playground?engine=google_light&q=apple&gl=us&hl=en&google_domain=google.com) | [Inspect](https://serpapi.com/searches/663cc85911c8814918aa8213/inspect) | [Google Search API documentation reference](https://serpapi.com/related-searches)

**Comment by btaunt** [comment]
This feature has been added.

- [Playground Link (Desktop)](https://serpapi.com/playground?engine=google_light&q=apple+inc&gl=us&hl=en&device=desktop&no_cache=true)
- [Playground Link (Mobile)](https://serpapi.com/playground?engine=google_light&q=apple+inc&gl=us&hl=en&device=mobile&no_cache=true)
- [Documentation](https://serpapi.com/google-light-related-searches)
