### ISSUE TITLE
[Google Light Search API] Add Top Stories parser

### ISSUE THREAD

**Issue by aciddjus** [serpapi/public-roadmap#1600]
Let's extract the `Top Stories` on all devices.

<img width="694" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/87902c16-0550-49c5-8338-d5b5a67afbc5">

------------

[Playground](https://serpapi.com/playground?engine=google_light&q=apple&gl=us&hl=en&google_domain=google.com) | [Inspect](https://serpapi.com/searches/663cc85911c8814918aa8213/inspect) | [Google Search API documentation reference](https://serpapi.com/top-stories)

**Comment by btaunt** [comment]
This feature as been added.

We now parse the `top_stories` section for Google Light API:

- [Playground Link](https://serpapi.com/playground?engine=google_light&q=openai+&gl=us&hl=en&device=desktop&no_cache=true)
- [Documentation](https://serpapi.com/google-light-top-stories)
