### ISSUE TITLE
[Google Search API] Support `answer_box` on mobile in specific queries `organic_results` 

### ISSUE THREAD

**Issue by vax-sa** [serpapi/public-roadmap#1601]
Bug repro steps and comparison of mobile vs. desktop:
* Use a simple query using google like "Michael Jackson birth place"
* Use device parameter "desktop".
* Notice the `answer_box` is parsed correctly for "desktop".
* Repeat the same query with device selected as "mobile"

Bug: Notice that `answer_box` is not provided when using "mobile" as the device.

**Comment by marm123** [comment]
Hi @vax-sa, thank you for opening an issue! Using your example, I've been able to get the `answer_box` for the `mobile` search in Google Search API. Please take a look below:

[Playground](https://serpapi.com/playground?q=Michael+Jackson+birth+place&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile)
<img width="1671" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/329b1e99-2bf6-4a2c-9f55-12a50664476e">

Please note that not all results return `answer_box` in the response, and you'll likely need to play with parameters, such as location or localization, to get the same results you see in your regular mobile search.

Feel free to reach out to contact@serpapi.com if you have any further questions. We'll be happy to assist.

**Comment by vax-sa** [comment]
Interesting. I see. As you pointed out, when a location is not provided, the results look very different. When I provide a location like Austin, Texas, United States, then it looks more like what you presented.

However, the results also then take significantly longer to arrive (2 seconds instead of 0.7 seconds) so I do not want or need to provide a location for a query that is not location dependent. See: https://serpapi.com/playground?q=Michael+Jackson+birth+place&gl=us&hl=en&device=mobile

So I believe this is still an issue. I can understand it might not be one you want the team to spend time on, but it is hampering the ability to use it reliably where the browser does not provide a location. I also say this because many google search queries take a longer time to get back when a location is provided and we want to get results with the lowest possible latency.
![image](https://github.com/serpapi/public-roadmap/assets/137828132/a383e7db-5221-49f2-be07-7ce2ca47ee47)

Here are the different times it takes to get the results without and with the location which is why I do not want to provide a location:
![image](https://github.com/serpapi/public-roadmap/assets/137828132/38ea0621-8a75-44d9-bca5-9ed0257b79ea)

**Comment by vax-sa** [comment]
Just responded to the issue that was closed:
https://github.com/serpapi/public-roadmap/issues/1601

**Comment by marm123** [comment]
Hi @vax-sa, yes, you are correct. The `answer_box` should also be available for the search you shared, as visible on the HTML. I'm sorry for not noticing it earlier. I'm opening this thread and labeling it for our team to look into it.

**Comment by aciddjus** [comment]
This issue has been fixed.

We are now properly extracting the `answer_box`.

<img width="1049" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/b6050f21-d3fd-4ab9-a307-f75aed91b06d">


---------------

[Playground](https://serpapi.com/playground?q=Michael+Jackson+birth+place&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile)
