### ISSUE TITLE
[Google Search API] Scrape the URL from weather answer box results

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1602]
A high-volume customer requested that we scrape the URL returned from Google in weather answer box results.

<img width="1268" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/22db6993-9914-44b9-8973-6ad352e4c8bd">

[Google Search](https://www.google.com/search?q=san+francisco+weather&oq=san+francisco+weat&gs_lcrp=EgZjaHJvbWUqBwgAEAAYgAQyBwgAEAAYgAQyBggBEEUYOTIHCAIQABiABDIHCAMQABiABDIHCAQQABiABDIHCAUQABiABDIHCAYQABiABDIHCAcQABiABDIHCAgQABiABDIHCAkQABiABKgCALACAA&sourceid=chrome&ie=UTF-8)

This data is currently not available in the response from our Google Search API:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/fd57bd44-9b9b-43f4-9f5f-0361568ee21d)

[Playground](https://serpapi.com/playground?q=San+Francisco+weather&location=San+Francisco%2C+California%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client) | [Inspect](https://serpapi.com/searches/663de191e0ded49d0807a288/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000065456?view=List)

**Comment by hilmanski** [comment]
The customer followed up recently.

**Comment by Alaa-abdulridha** [comment]
This issue now has been ressolved.

Before scraping the URL from the weather answer box:

![image](https://github.com/serpapi/public-roadmap/assets/53356539/1f058066-f0ce-4eb8-afdd-b7c94477a0fa)



After scraping the URL from the weather answer box:

![image](https://github.com/serpapi/public-roadmap/assets/53356539/dd0046d7-d302-47a8-803a-c5809bec3d43)
