### ISSUE TITLE
[Google Search API] Scrape event status for `sports_results`

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1604]
A user requested that we scrape the event status for `sports_results`. Currently, we're not providing this data in the response from our Google Search API:

<img width="1410" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/9891adc8-8386-4795-ba1f-a07e2bb73f6f">

[Playground](https://serpapi.com/playground?q=wimbledon+2023+scores&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client) | [Inspect](https://serpapi.com/searches/66433c905c560621bb8a1cf9/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000064076?view=List)

**Comment by alexbarron** [comment]
We received a request for something similar to this. Specifically, scraping the live status of how many minutes have elapsed/are remaining in a game.

![image](https://github.com/serpapi/public-roadmap/assets/9811728/ec47f14a-35cb-4737-8ff4-98fd4a165d1a)

![live-sports](https://github.com/serpapi/public-roadmap/assets/9811728/efd77d36-22a2-4335-a14c-4b186761be02)

I've included a Playground link below, but to properly reproduce this, you need to find a live game. The game included in the search below will be over by the time anyone sees this. You can check [Fotmob](https://www.fotmob.com/) to see if there's a football match ongoing somewhere in the world in a league they cover. Then search for those two teams in Google to see if Google returns live results for that match.

[Playground](https://serpapi.com/playground?q=daegu+fc++vs+incheon+united&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068424?view=List)

**Comment by ocvit** [comment]
Feature has been released.

Now we grab event `status` for `tennis` and `game_spotlight.in_game_time` for soccer live games.

<img width="1209" alt="Screenshot 2024-09-27 at 09 56 16" src="https://github.com/user-attachments/assets/febd8089-d929-4efe-89d1-ed3487491ad5">

--------

(no live soccer games right now to double check, will update ASAP)

**Comment by alexbarron** [comment]
Thanks @ocvit . I found a live game to test with. Looks good to me:

![image](https://github.com/user-attachments/assets/c7ee8bed-6cb2-4dc8-a87d-66ec089f704e)

Here's a [Playground](https://serpapi.com/playground?q=qingdao+red+lions+guangzhou+fc&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&newPara=as_sitesearch+chips) link to the game. This will finish in a little over an hour from now.

If you miss that one, you can find more ongoing games here: https://www.fotmob.com/?show=ongoing

**Comment by alexbarron** [comment]
For other CSEs, I've notified both customers who requested this.

**Comment by ocvit** [comment]
Mobile layout works as well.

<img width="1338" alt="Screenshot 2024-09-27 at 15 14 52" src="https://github.com/user-attachments/assets/bb98d12a-f7fb-4c49-b7eb-d6192c8ac6af">
