### ISSUE TITLE
[Google Flights API] Support Airline Codes that Include a Number

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1606]
A user requested that we support filtering using 2-character airline codes where one of the characters is a number.

Currently, both characters in the airline code need to be letters to pass validation.

Specifically, the users tried to filter results for Wizz Air, an airline whose code appears to be `W6` , `W4`, or `W9` depending on the region.

I'm a little bit confused about how IATA codes work though. At first when I tried searching [IATA](https://www.iata.org/en/publications/directories/code-search/) for Wizz Air, W6, and W4, I didn't get any relevant results.

However, an IATA code for Wizz Air can be found here:

https://www.iata.org/en/programs/safety/audit/iosa/registry/?search=Wizz%20Air&ordering=Relevance

I also verified that Wizz Air is sometimes an option when using Google Flights directly.

<img width="854" alt="Screenshot 2024-05-15 at 4 06 13 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/64414b3b-0f46-4e4e-a643-5f4f2908fa0d">
<img width="1406" alt="Screenshot 2024-05-15 at 4 01 49 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/4a8a0a46-b179-46f2-9872-092f80701f64">
<img width="1288" alt="Screenshot 2024-05-15 at 4 00 48 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/b13bcb9c-4a72-4348-a802-7ea613624474">

[Google Flights](https://www.google.com/travel/flights/search?tfs=CBwQAhowEgoyMDI0LTA1LTMxMgJXNDICVzZqDAgDEggvbS8wOTV3X3IMCAMSCC9tLzA0anBsQAFIAXABggELCP___________wGYAQI) | [Playground](https://serpapi.com/playground?engine=google_flights&departure_id=BUD&arrival_id=LTN&gl=us&hl=en&currency=USD&outbound_date=2024-05-16&return_date=2024-05-22&include_airlines=W6) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000065836?view=List)

**Comment by zyc9012** [comment]
We've released a fix for this. `exclude_airlines` and `include_airlines` now support specifying code containing digits.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/a7b41fd5-de10-44bf-9644-48edee81c035)
