### ISSUE TITLE
[Google Light Search API] Scrape answer box

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1607]
Currently, our HTML already shows the answer box. Maybe we can parse it since many AI search engine companies can find this helpful.

![CleanShot 2024-05-16 at 07 13 18](https://github.com/serpapi/public-roadmap/assets/4522467/49ec0e98-815e-4070-9257-8831bb390454)

[Playground](https://serpapi.com/playground?engine=google_light&q=what+is+square+root+of+4&gl=us&hl=en)

**Comment by btaunt** [comment]
Although not covering every possible answer box "type" yet, we now support:

- organic result
- weather
- time
- population
- calculator result
- flight duration
- dictionary (targeting single definition views)

Further details can be found in the [new documentation for answer box](https://serpapi.com/google-light-answer-box).
