### ISSUE TITLE
[Google Light Search API] Scrape featured snippet

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1608]
Our HTML displayed the featured snippets; we may also parse this in our response since it can be useful for AI search engines.

![CleanShot 2024-05-16 at 07 25 21](https://github.com/serpapi/public-roadmap/assets/4522467/3cd18da4-c948-46c9-8bb5-be35a273c415)

[Playground](https://serpapi.com/playground?engine=google_light&q=what+is+openai&gl=us&hl=en)

**Comment by zyc9012** [comment]
This is answer box as well. (type=`organic_result`)

**Comment by btaunt** [comment]
This is now available and found under Answer Box elements: `answer_box: organic_result` 

Further details can be found in the [new documentation for answer box](https://serpapi.com/google-light-answer-box).
