### ISSUE TITLE
[Google Search API] Movie names wrongly parsed inside `knowledge_graph.movies_playing`

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1610]
A customer reported that the movie names inside `knowledge_graph.movies_playing` are not parsed correctly. I was able to reproduce it in the Playground:

<img width="1421" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/bdbd3f14-22f2-4c3a-99bc-173e246c0811">

[Playground](https://serpapi.com/playground?q=movies+playing+in+Austin&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/664731e8d036a79447ead68e/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000064146?view=List)

**Comment by zyc9012** [comment]
We've released a fix for this. The names are now properly parsed.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/4fb96b16-4d1a-4cd7-b10d-ede9ed86d270)
