### ISSUE TITLE
[Google Search] Bug with "place_sites"

### ISSUE THREAD

**Issue by RedBillyOne** [serpapi/public-roadmap#1612]
Hi,

Your JSON return an empty "Place_sites" tag even if there is not "local places" on SERP

Example https://serpapi.com/playground?q=Douleurs+trap%C3%A8zes&location=France&google_domain=google.fr&gl=fr&hl=fr&newPara=chips

Is it possible to return "place_sites" only if there is really a local places on SERP ?

![image](https://github.com/serpapi/public-roadmap/assets/152279883/011ae4dc-9119-4009-85bd-885fb7ef75ad)

**Comment by zyc9012** [comment]
Thanks for your report, we'll look into this.

**Comment by zyc9012** [comment]
We've released a fix for this. The block on the right is no longer parsed as `places_sites`.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/54ce0ca8-6445-469b-82cf-b0bfdfbfea95)
