### ISSUE TITLE
[Google Light Search API] Some elements are mis-parsed as Top stories 

### ISSUE THREAD

**Issue by tanys123** [serpapi/public-roadmap#1613]
<img width="1068" alt="Screenshot 2024-05-20 at 12 22 10 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/fee5bca3-c14a-452e-ab82-2db6c49cc20c">

[Playground](https://serpapi.com/playground?engine=google_light&q=dark+tv+series+episodes&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/664ad553654a8cb30f6fd2ad/inspect)

**Comment by aciddjus** [comment]
Here is another example:

<img width="1596" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/3bf36cd9-7aad-4f51-945b-23a33f850215">

[Playground](https://serpapi.com/playground?engine=google_light&q=Coffee&gl=us&hl=en&no_cache=true&google_domain=google.com) | [Inspect](https://serpapi.com/searches/664b34d55f22032de735d3e6/inspect)

**Comment by btaunt** [comment]
Another example, this one places the `top_stories` within the `knowledge_graph` and again on its own:

<img width="780" alt="Screenshot 2024-05-23 at 9 43 15 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/2bcc6044-df37-431a-8e38-5239b8cdb336">


[Playground](https://serpapi.com/playground?engine=google_light&q=nhl+news&gl=us&hl=en&no_cache=true) | [Inspect](https://serpapi.com/searches/664f47d536e6a925a1af9103/inspect)

**Comment by btaunt** [comment]
This has been fixed by refactoring our Google Light Top Stories parser. The documentation has also been updated with an interactive demo example.

- [Playground Example](https://serpapi.com/playground?engine=google_light&q=nhl+news&gl=us&hl=en&device=desktop&no_cache=true)
- [Documentation](https://serpapi.com/google-light-top-stories)
