### ISSUE TITLE
[Google News API] Thumbnail images not displayed in the Playground

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1616]
The thumbnail images are not displayed correctly in the response from our Google News API in the Playground:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/d8dc466b-8b94-44fa-9def-bc546909c626)

[Playground](https://serpapi.com/playground?engine=google_news&q=coffee&gl=us) | [Inspect](https://serpapi.com/searches/664c8402e135086da4acd84a/inspect)

The actual thumbnail URLs seem to be correct:

[Example thumbnail URL](https://news.google.com/api/attachments/CC8iK0NnNXllazVHUTI5bGJGOXJTMU16VFJDM0FSaVRBaWdCTWdZZE1JanNuUVU)

**Comment by zyc9012** [comment]
We've released a fix for this. The images are displaying now.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/d62b5ae1-3b23-434d-86c4-45868f2aae42)
