### ISSUE TITLE
[Google Search API] `total_results` returned but not displayed in HTML

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1617]
One of our Enterprise Customers reported that they are getting an inaccurate number of `total_results` returned. This is likely due to how Google serves results and the fact they are showing a different number of results returned that what we can actually get from that search query, but the information is missing on the HTML file:

<img width="1671" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/5369c3e2-3df8-467f-8925-82f91b410b6b">

It's especially weird that Google usually showed millions or thousands of results found (like in the example above), but the customer only got information about 68 `total_results`, which was still inaccurate.

Customer's search:
<img width="1326" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/c71fec19-6062-4021-b537-cf18f507e307">

[Playground](https://serpapi.com/playground?q=%22Jane+Doe%22+AND+(linkedin+AND+developer+AND+SaaS+AND+London+AND+Job+AND+Salary)&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/664cb7f2af5af1332df5f80b/inspect) | [Customer's Inspect](https://serpapi.com/searches/664ca065116a55bd75ccb0a0/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000066146?view=List)

**Comment by aciddjus** [comment]
The results are still on the page, but Google has started hiding them by default.

If you inspect the page, search for the HTML item with classes `pZvJc jf0C1c`, and remove the `display: none;` CSS property, results will show up on the page.

Also, I'm getting a similarly low number of results for the customer's query on live Google search, so I don't see the issue with the number being incorrect.

![image](https://github.com/serpapi/public-roadmap/assets/6929257/25aac62e-d2ce-4120-9ea4-92a3d3ac4229)

**Comment by aciddjus** [comment]
Thanks, @marm123. We can still fix hidden results in the HTML and show them by default. I'll open a quick PR.

> The odd thing about the query from the customer was that it showed 68 total_results when there were 15 in fact. Usually, Google showed millions or thousands of results on the first page, and 68 looked oddly specific and weird when there were no 68 results, but 15 only. But overall I agree that while this is kinda odd, it's just Google not showing the correct number of results as usual.

Yeah, it's indeed unusual, but it is far from the first time that Google has served an incorrect number of results.

**Comment by aciddjus** [comment]
This issue has been resolved.

We are now showing `total_results` and `time_taken_displayed` in HTML.

![image](https://github.com/serpapi/public-roadmap/assets/6929257/7cf780ad-d302-4d05-b2a1-bd9da85156bc)


-------------

Playground
