### ISSUE TITLE
[Playground] Some icons are misplaced and not rendered correctly

### ISSUE THREAD

**Issue by aciddjus** [serpapi/public-roadmap#162]
In Chrome, Some duo-tone icons are not rendered correctly and the arrow icons from dropdown inputs are missplaced.

<img width="646" alt="image" src="https://user-images.githubusercontent.com/6929257/171170811-88205906-6088-4864-99a1-d41bfa189a9f.png">

Can someone confirm this?

**Comment by aciddjus** [comment]
Thanks, @dimitryzub. I started having this issue on Friday, just in Chrome.

**Comment by aciddjus** [comment]
@dimitryzub Latest beta: `Version 103.0.5060.24 (Official Build) beta (64-bit)`

**Comment by dimitryzub** [comment]
@aciddjus Possibly that's the issue. Both Brave and Chrome on my machine using version: `102.x.xxxx.xx`.

- Chrome: `Version 102.0.5005.63 (Official Build) (64-bit)` 
- Brave: `Version: 102.0.5005.61 (Official Build)  (64-bit)`

**Comment by hartator** [comment]
Not issue on my regular Chrome (`Version 101.0.4951.64 (Official Build) (arm64)`):

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/307597/171329020-7e94bbfe-b682-4a52-8b11-521b831200ca.png">

I do have the same issue in Chrome Canary (`Version 104.0.5095.0 (Official Build) canary (arm64)`):

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/307597/171329181-a12b599d-d6de-4c49-9028-7d4e0125c96b.png">

<img width="1451" alt="image" src="https://user-images.githubusercontent.com/307597/171329369-360daf75-9c4a-44f5-b161-43bc1f793c7d.png">

**Comment by ilyazub** [comment]
I'd rather not fix Canary-related issues. Chrome Canary and Firefox Developer are unstable.

**Comment by aciddjus** [comment]
Fixed in: `Version 104.0.5112.29 (Official Build) beta (64-bit)`

![image](https://user-images.githubusercontent.com/6929257/176873898-679093e7-d3a0-40b0-863a-f98fb62ab5b4.png)

**Comment by aciddjus** [comment]
This issue should be resolved in the latest version of Chrome.
