### ISSUE TITLE
[Google Maps API] `type=place` search returns no results with a valid `data` parameter

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1625]
A customer reported that our Google Maps API does not return results when they use a `data` parameter extracted directly from the URL in the Google Maps engine. I was able to reproduce it.

Executing a request using our Google Maps API with the `data` parameter provided by the customer - `!4m16!1m9!3m8!1s0x46b54bd53dd429dd:0xf026259b7dbd3925!2z0KDQvtGB0LPQtdC-0LvQvtCz0LjRjw!8m2!3d55.6570083!4d37.5577278!9m1!1b1!16s%2Fg%2F11r925q2y!3m5!1s0x46b54bd53dd429dd:0xf026259b7dbd3925!8m2!3d55.6570083!4d37.5577278!16s%2Fg%2F11r925q2y`:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/8e8f2558-b56a-42ab-ab78-0610bae84766)

[Playground](https://serpapi.com/playground?engine=google_maps&google_domain=google.ru&hl=ru&data=!4m16!1m9!3m8!1s0x46b54bd53dd429dd%3A0xf026259b7dbd3925!2z0KDQvtGB0LPQtdC-0LvQvtCz0LjRjw!8m2!3d55.6570083!4d37.5577278!9m1!1b1!16s%252Fg%252F11r925q2y!3m5!1s0x46b54bd53dd429dd%3A0xf026259b7dbd3925!8m2!3d55.6570083!4d37.5577278!16s%252Fg%252F11r925q2y&type=place&no_cache=true) | [Inspect](https://serpapi.com/searches/66507de3a4be104be6e56444/inspect)

However, a place result is returned in Google Maps when opening the `google_maps_url` link from the response above, which contains the same `data` paraemter:

![image](https://github.com/serpapi/public-roadmap/assets/144151895/4c131ef6-5de8-49c3-ba87-7df9827c7691)

[Google Maps](https://www.google.ru/maps/place/data=!4m16!1m9!3m8!1s0x46b54bd53dd429dd:0xf026259b7dbd3925!2z0KDQvtGB0LPQtdC-0LvQvtCz0LjRjw!8m2!3d55.6570083!4d37.5577278!9m1!1b1!16s%2Fg%2F11r925q2y!3m5!1s0x46b54bd53dd429dd:0xf026259b7dbd3925!8m2!3d55.6570083!4d37.5577278!16s%2Fg%2F11r925q2y?hl=ru) 

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000065862?view=List)

**Comment by aciddjus** [comment]
Thanks, @martin-serpapi 

That is not a valid `data` parameter. Per our [documentationion](https://serpapi.com/google-maps-api#api-parameters-advanced-google-maps-parameters-data), `data` parameter should be contracted in the following sequence:

```
!4m5!3m4!1s + data_id + !8m2!3d + latitude + !4d + longitude
```

That translates to:

```
!4m5!3m4!1s0x46b54bd53dd429dd:0xf026259b7dbd3925!8m2!3d55.6570083!4d37.5577278
```

------------------

[Playground](https://serpapi.com/playground?engine=google_maps&google_domain=google.ru&hl=ru&data=!4m5!3m4!1s0x46b54bd53dd429dd%3A0xf026259b7dbd3925!8m2!3d55.6570083!4d37.5577278&type=place&no_cache=true) | [Inspect](https://serpapi.com/searches/665493882ff4210b9b26815d/inspect)

**Comment by marm123** [comment]
Thanks for looking into it, @aciddjus!

I think the main issue here is that the data parameter Martin shared in the example, although not created in the way described in our documentation, works directly in Google Maps but doesn't work with our API. 

Do you think we can potentially support a different `data` format than the one described in the documentation?

**Comment by aciddjus** [comment]
Thanks, @marm123 

I think I understand the problem. Coping the complete `data` parameter of a place should already work:

[Google Maps link](https://www.google.ru/maps/place/%D0%A0%D0%BE%D1%81%D0%B3%D0%B5%D0%BE%D0%BB%D0%BE%D0%B3%D0%B8%D1%8F/@55.6294071,37.5694512,11z/data=!4m6!3m5!1s0x46b54bd53dd429dd:0xf026259b7dbd3925!8m2!3d55.6570083!4d37.5577278!16s%2Fg%2F11r925q2y?hl=ru&entry=ttu)

[Playground](https://serpapi.com/playground?engine=google_maps&google_domain=google.ru&hl=ru&data=!4m6!3m5!1s0x46b54bd53dd429dd%3A0xf026259b7dbd3925!8m2!3d55.6570083!4d37.5577278!16s%252Fg%252F11r925q2y&type=place&no_cache=true) with full `data` parameter

-------------

The problem starts when you are on Google Maps, and after visiting one place, you click on another. In my example, I clicked [this town](https://www.google.ru/maps/place/%D0%A1%D0%BE%D0%BB%D0%BE%D1%81%D0%BB%D0%BE%D0%B2%D0%BE,+%D0%9C%D0%BE%D1%81%D0%BA%D0%BE%D0%B2%D1%81%D0%BA%D0%B0%D1%8F+%D0%BE%D0%B1%D0%BB.,+%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F/@55.6959441,37.1326288,15z/data=!3m1!4b1!4m14!1m7!3m6!1s0x46b54bd53dd429dd:0xf026259b7dbd3925!2z0KDQvtGB0LPQtdC-0LvQvtCz0LjRjw!8m2!3d55.6570083!4d37.5577278!16s%2Fg%2F11r925q2y!3m5!1s0x46b55a5a72e3e52f:0xc87750bc121a9f52!8m2!3d55.6995987!4d37.1481532!16s%2Fg%2F12z655f6t?hl=ru&entry=ttu)

If we extract the `data` parameter from this search:

`!3m1!4b1!4m14!1m7!3m6!1s0x46b54bd53dd429dd:0xf026259b7dbd3925!2z0KDQvtGB0LPQtdC-0LvQvtCz0LjRjw!8m2!3d55.6570083!4d37.5577278!16s%2Fg%2F11r925q2y!3m5!1s0x46b55a5a72e3e52f:0xc87750bc121a9f52!8m2!3d55.6995987!4d37.1481532!16s%2Fg%2F12z655f6t`

You can see that it contains two sets of `data` required parameters

First:
`data_id: 0x46b54bd53dd429dd:0xf026259b7dbd3925`
`latitude: 55.6570083`
`longitude: 37.5577278`

[Playground](https://serpapi.com/playground?engine=google_maps&google_domain=google.ru&hl=ru&data=!4m5!3m4!1s0x46b54bd53dd429dd%3A0xf026259b7dbd3925!8m2!3d55.6570083!4d37.5577278&type=place&no_cache=true)

Second:
`data_id: 0x46b55a5a72e3e52f:0xc87750bc121a9f52`
`latitude: 55.6995987`
`longitude: 37.1481532`

[Playground](https://serpapi.com/playground?engine=google_maps&google_domain=google.ru&hl=ru&data=!4m5!3m4!1s0x46b55a5a72e3e52f%3A0xc87750bc121a9f52!8m2!3d55.6995987!4d37.1481532&type=place&no_cache=true)

------------------

So, the first data set is residue from your previous search, and the last data set is from your current search (I wasn't able to reproduce the user's case, where both sets are the same). This doesn't happen every time, and I don't quite understand the reason (it could be a bug in async URL construction on the Google Maps side, or it serves some real purpose).

I'm not sure why the redirect is not working properly on our side in these cases. But as a workaround, I would suggest opening a new browser tab or window, searching for a place and getting a "clean" URL.
