### ISSUE TITLE
[Yandex API] Slow response times and failed queries

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1626]
We received a report of very slow response times for Yandex and some are responding with 503 errors.

![image](https://github.com/serpapi/public-roadmap/assets/9811728/c979e789-2bd4-4e4f-87eb-455c63febfc7)

Appears to have started yesterday.

![image](https://github.com/serpapi/public-roadmap/assets/9811728/e2813d5f-06cd-4304-86d8-0b8f794d4b21)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000065862?view=List) | [Yandex Status](https://serpapi.com/status/yandex)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067405?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067411?view=List)
