### ISSUE TITLE
[Google Knowledge Graph API] Scrape the pricing information

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1631]
A user requested that the pricing information be scraped from our knowledge graph.

![image](https://github.com/serpapi/public-roadmap/assets/4522467/4ea13ca4-1b9e-4912-8774-c352bab4079b)

*I can't remember if we've supported this in the past or if it's just a new feature to implement.

[Playground](https://serpapi.com/playground?q=post+1917&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000066905?view=List)

**Comment by aciddjus** [comment]
@ocvit Make sure to update the `status` badge of the issue to `completed`. Thank you.
