### ISSUE TITLE
[serpapi_link API response] Wrong hl value

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1632]
A high-volume customer reported a bug in our `serpapi_link` response. Sometimes, it shows hl=en-US, which causes an error when the customer is redirected to it. It should be `hl=en`

![CleanShot 2024-05-28 at 07 09 28](https://github.com/serpapi/public-roadmap/assets/4522467/a46351da-771c-47cc-ab6e-aac23ea75efd)

[Update]
- I believe it was only found on the knowledge_graph
- I noticed upon searching on the codebase that `hl=en-US` is all over the documentation sample.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/admin/6755014/conversation/102910000066945) | [Inspect sample](https://serpapi.com/searches/257628f010527fff/66543effe815af7b7c93fef4.json)

**Comment by zyc9012** [comment]
Dup of https://github.com/serpapi/public-roadmap/issues/1553
