### ISSUE TITLE
[Yelp Place API] Search return Internal server error 500

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1633]
A customer reported that they received internal server error [500] upon searching for a place. We display `"error":
"Yelp Place hasn't returned any results for this query.` when the ID is invalid. So, there is another problem.

The `place_id` is from this response [playground search](https://serpapi.com/playground?engine=yelp&find_desc=Maji+Curry&find_loc=Toronto%2C+Ontario%2C+Canada)
![CleanShot 2024-05-28 at 07 21 58](https://github.com/serpapi/public-roadmap/assets/4522467/862bfaab-2ec1-4ebc-83e4-f2652a45cc9e)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067007?view=List) | [Playground](https://serpapi.com/playground?engine=yelp_place&place_id=dO7BhSsYGDEbHJXiKtBmHQ) | [Inspect](https://serpapi.com/searches/66551480ef7dda727ac62712/inspect)

**Comment by zyc9012** [comment]
We've released a fix for this. It's now returning correct results.
![image](https://github.com/serpapi/public-roadmap/assets/3034310/e6d88a0e-1485-4e9f-a4b5-d77050b2dd2a)
