### ISSUE TITLE
[Google Search API] Information Missing from `immersive_products`

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1634]
A customer reported we aren't parsing all of the information from `immersive_products`.

Specifically, they noted we aren't scraping the availability/delivery field many of these elements included, but we also don't seem to be scraping ratings or review counts.

<img width="1413" alt="Screenshot 2024-05-28 at 9 09 44 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/1d7271ee-d476-4cda-b5c5-368ff62978f4">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067047?view=List) | [Playground](https://serpapi.com/playground?q=seltzer+water&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source) | [Search Inspector](https://serpapi.com/searches/6655f6d3116a553141117815/inspect)

**Comment by zyc9012** [comment]
We've released a fix for this. `rating` and `reviews` have been fixed. `location`, `delivery` and `returns` have been added.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/bd14b4d1-5d96-4f33-bcd0-7208e78775fc)
