### ISSUE TITLE
[Yelp Place API] Scrape multiple business hours

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1635]
A customer reported that we didn't scrape a complete place's business hour when there were multiple values available: 
![CleanShot 2024-05-29 at 12 47 00@2x](https://github.com/serpapi/public-roadmap/assets/4522467/8911070e-3141-4928-84d6-ac1894d77fa6)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067007?view=List) | [Playground](https://serpapi.com/playground?engine=yelp_place&place_id=886-new-york) | [Inspect](https://serpapi.com/searches/6656b2c6ca968f22c17313ba/inspect)

**Comment by Alaa-abdulridha** [comment]
This issue now has been resolved.

Before resolving it (Production):

![image](https://github.com/serpapi/public-roadmap/assets/53356539/f54c79ac-4f63-4e44-8e15-bf56e7e52b84)


After resolving it (Production):

![image](https://github.com/serpapi/public-roadmap/assets/53356539/922bb1ae-17ce-4481-adf1-41b8592246fc)
