### ISSUE TITLE
[Yelp Place API] Scraping correct categories

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1636]
Currently, we scrape the `people also search for` section into the `categories` key, which should be separated.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067007?view=List) | [Playground](https://serpapi.com/playground?engine=yelp_place&place_id=886-new-york) | [Inspect](https://serpapi.com/searches/6656b2c6ca968f22c17313ba/inspect)

**Comment by zyc9012** [comment]
We've released a fix for this. No more extra categories are scraped.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/01ab0562-0889-461a-9de7-e38741ad7f40)
