### ISSUE TITLE
[Home Depot Product API] Extract stock, bay, and aisle numbers

### ISSUE THREAD

**Issue by aciddjus** [serpapi/public-roadmap#1637]
Support scraping Home Depot's stock number, bay, and aisle numbers. 

![image](https://github.com/serpapi/public-roadmap/assets/6929257/647ae324-3bf9-4fc1-8f5b-0c719dd57f12)

----------------

[Home Depot link](https://www.homedepot.com/p/Carlon-1-Gang-14-cu-in-PVC-Old-Work-Electrical-Switch-and-Outlet-Box-B114RB/100404027) | [Playground](https://serpapi.com/playground?engine=home_depot_product&product_id=100404027&delivery_zip=92553&store_id=616)

**Comment by tanys123** [comment]
We have made a new release that adds `quantity` to all fulfillment options. To get the **stock** in store, you should retrieve the `quantity` from Store Pickup option.

<img width="1065" alt="Screenshot 2024-07-11 at 11 12 33 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/75e3c667-46f5-455e-a4be-9e8c4749bb98">
