### ISSUE TITLE
[User Dashboard | Searches] Searches Archive Gives Error on Certain Pages

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#164]
User with 619dd80aea1442c1a89abffc reported that they get 500 internal error when they try to visit certain pages of their search archives on serpapi.com/searches

Page 20:

![image](https://user-images.githubusercontent.com/64849049/171379634-0445b952-d3f9-464f-aa46-367795ea2dfe.png)

Page 21

![image](https://user-images.githubusercontent.com/64849049/171379725-2cd70067-cad0-41b7-9759-c4832873089f.png)

Page 22

![image](https://user-images.githubusercontent.com/64849049/171379815-482d26bb-f5ae-4c96-addb-789612e420df.png)

Page 23

![image](https://user-images.githubusercontent.com/64849049/171380370-f51754fc-dd96-49b7-808c-50e3ac17cd5c.png)

This is very weird one.

**Comment by aciddjus** [comment]
Is this now fixed here: https://github.com/serpapi/SerpApi/pull/2814#issuecomment-1144994510? @ilyazub @ritu1337

**Comment by ritu1337** [comment]
> Is this now fixed here: [serpapi/SerpApi#2814 (comment)](https://github.com/serpapi/SerpApi/pull/2814#issuecomment-1144994510)? @ilyazub @ritu1337

Yes it should be fixed, I went through 30 pages of the customer's searches without problem.
