### ISSUE TITLE
[Yelp Places API] Scrape open state information

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1640]
Currently we're not scraping the information. One of our high-volume customers requested this.

Yelp:
| Temporarily closed | Permanently Closed | 
| :---: | :---: |
| <img width="1369" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/b8c23abb-eaab-4a7b-8553-514adc2c5a35"> | <img width="1367" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/f3a4ae51-bb45-40b9-9dca-56328b1516af"> | 

Our API:
| Temporarily closed | Permanently Closed | 
| :---: | :---: |
| <img width="1671" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/3b609ba0-2297-4dd5-b301-f00ff380a2d4"> | <img width="1671" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/0e4c428f-20a7-42c5-9bc3-fa33875f4459"> | 

Temporarily closed:
[Playground](https://serpapi.com/playground?engine=yelp_place&place_id=gap-mississauga-4) | [Inspect](https://serpapi.com/searches/665795af66d81f2d708715ca/inspect) | [Yelp](https://www.yelp.com/biz/gap-mississauga-4)
Permanently closed:
[Playground](https://serpapi.com/playground?engine=yelp_place&place_id=thats-yogurt-milpitas) | [Inspect](https://serpapi.com/searches/6657921bce87f8f3e11fe6a0/inspect) | [Yelp](https://www.yelp.com/biz/thats-yogurt-milpitas)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000067007?view=List)

**Comment by marm123** [comment]
The customer confirmed that scraping the information as `business_alert` works for them.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067007)

**Comment by tanys123** [comment]
We have added `business_alert` to Yelp Place API. You have to enable it by passing `business_alert=true` in the parameter. More details in the [documentation](https://serpapi.com/yelp-place#api-examples-business-alert-example).

<img width="1455" alt="Screenshot 2024-08-01 at 8 16 27 AM" src="https://github.com/user-attachments/assets/0af44ab9-f146-4b69-857f-f279029b4031">
