### ISSUE TITLE
[Google Lens Image Source API] Default Playground Example is Broken (Again)

### ISSUE THREAD

**Issue by btaunt** [serpapi/public-roadmap#1642]
This issue was originally reported in https://github.com/serpapi/public-roadmap/issues/1576 which was then patched with https://github.com/serpapi/SerpApi/pull/4828 but the new page token seems to be returning empty results again:

<img width="1374" alt="Screenshot 2024-05-30 at 10 27 19 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/c7d92f47-eb56-479c-8a51-cf18aff78ac7">

As mentioned in the first PR fix, maybe we need to be clever and think of a way to more dynamically avoid swapping tokens constantly?

---

[Playground Link](https://serpapi.com/playground?engine=google_lens_image_sources&page_token=MTNhYzhmMWItNTZkMS00YjNjLWI3MWEtMTAyMjZkNTIxOTM1&no_cache=true)

**Comment by ishiharaf** [comment]
@btaunt It's working fine in production now. Regarding your comment below the screenshot, please see the PR notes and feel free to comment about it.

![image](https://github.com/user-attachments/assets/9a4faba1-6a4b-4423-982f-046930a9c47c)

**Comment by btaunt** [comment]
Thanks for the updates @ishiharaf!

Makes sense. The overhead of changing the `token` manually seems low compared to the alternatives you mention in the PR. 👍
