### ISSUE TITLE
[Google Search API] Return `video` label in `top_stories`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1644]
One of our users requested us to return the `video` label for the `top_stories` marked as such:

No indication that these `top_stories` are videos in the response:
<img width="1670" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/27c8b969-ddca-4c03-a4e7-54ef43faba24">

[Playground](https://serpapi.com/playground?q=trump+video&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) I [Inspect](https://serpapi.com/searches/6659d713303eb1a5d388e005/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067234?view=List)

**Comment by ocvit** [comment]
Feature has been released.

Now `top_stories` include `video` label if applicable.

<img width="1336" alt="Screenshot 2024-06-11 at 18 58 45" src="https://github.com/serpapi/public-roadmap/assets/13473505/36c3be31-2a7a-426e-99e8-f984f592537e">
