### ISSUE TITLE
[Google Flight API] Issues with airline filtering

### ISSUE THREAD

**Issue by corear** [serpapi/public-roadmap#1645]
Two issues I've just noticed when adding both `include_airlines` and `exclude_airlines` parameters to Google Flight API requests:

1. Adding any of the 3 suggested alliances resulted in the following error being shown and the search not executing:
```
{
"error":
"`include_airlines`: "ONEWORLD" is not a 2-character IATA code consisting of either two uppercase letters or one uppercase letter and one digit."
}
```
2. Adding any airline to the filter looks for flights with ONLY that airline, not flights apart of their ecosystem (for example, a search for Delta flights on Google Flights returns some results mixed in with Air France flights, while applying that same filter on the playground would return 0 flights)
Google Flights:
<img width="1052" alt="image" src="https://github.com/serpapi/public-roadmap/assets/15691029/11de1c98-09f6-435c-9030-a996c2def4cd">
SerpApi Playground:
<img width="1587" alt="image" src="https://github.com/serpapi/public-roadmap/assets/15691029/9b4580fe-5869-4497-8901-d214aa2e2086">

**Comment by zyc9012** [comment]
Thank you for your report @corear. We are looking into it.

**Comment by marm123** [comment]
Thank you for opening the thread @corear ! While we're still investigating the first issue you reported, it looks like in the 2nd issue you used an incorrect IATA code for Delta. According to [Airline and Airport Code Search](https://www.iata.org/en/publications/directories/code-search?airline.search=Delta), the correct code is `DL`, not `DA`. Please check the screenshot below:
<img width="1089" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/dc17ce03-ce2c-4c4d-9afb-13834b49aedf">

Checking the Playground with DL, it looks like there are results returned for these parameters, similar to how Google Flights displays them:

Playground:
<img width="1670" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/2452974b-ce2f-42ef-ab26-1544f1129c2d">

Google Flights:
<img width="1534" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/065313ab-9f83-456d-af34-8eedf9e32359">

Let me know if that solves the 2nd issue.

**Comment by corear** [comment]
@marm123 Thanks for the quick response! I tried to use "Delta" in the second screenshot because nothing was returning for "DL", but it looks like results are returning today for each airline code, so no worries on the 2nd issue!

**Comment by zyc9012** [comment]
We've released a fix for this.

Now using alliances `STAR_ALLIANCE`, `SKYTEAM` and `ONEWORLD` won't show error.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/1dc96891-77b4-4103-8a8d-77f67946ce79)
