### ISSUE TITLE
Google Shopping API returns the same products on every page

### ISSUE THREAD

**Issue by miro-scalewest** [serpapi/public-roadmap#1646]
Playing with Google Shopping API and found that for most searches, it returns the same products even though I change the start position. I can't reproduce it at the playground, but using my API key, seems to be reproducable every time.

<img width="1705" alt="image" src="https://github.com/serpapi/public-roadmap/assets/91669570/0be8ae16-5829-4326-822e-bc759825cf4a">

<img width="1710" alt="image" src="https://github.com/serpapi/public-roadmap/assets/91669570/74feb423-2de5-4576-9bcd-2f4a2bc07073">

**Comment by kagermanov27** [comment]
@miro-scalewest I have tried to recreate the problem but wasn't able to. I have observed a problem with the request URL you have shared in the images though. An ampersand (`&`) is missing between the query parameter and the start parameter:

![image](https://github.com/serpapi/public-roadmap/assets/73674035/cc1aeb35-163a-4c1d-94a1-edcc1310c68e)

Thank you for your feedback. We would be grateful if you let us know if adding an ampersand resolves your problem.

**Comment by kagermanov27** [comment]
@miro-scalewest I have tried to recreate the problem but wasn't able to. I have observed a problem with the request URL you have shared in the images though. An ampersand (`&`) is missing between the query parameter and the start parameter:

![image](https://github.com/serpapi/public-roadmap/assets/73674035/cc1aeb35-163a-4c1d-94a1-edcc1310c68e)

Using space between the query parameter and the `start` parameter is causing the `start` parameter to be nullified:

<img width="1709" alt="start" src="https://github.com/serpapi/public-roadmap/assets/73674035/c10fdaed-6e9e-4bac-aa65-25491c8cf5b6">

[Example Playground Link](https://serpapi.com/playground?engine=google_shopping&q=Red+dress+size+&+start=10&num=5&no_cache=true&newPara=stick+lr+as_qdr)

Thank you for your feedback. We would be grateful if you let us know if adding an ampersand resolves your problem.

**Comment by kagermanov27** [comment]
@miro-scalewest I have tried to recreate the problem but wasn't able to. I have observed a problem with the request URL you have shared in the images though. An ampersand (`&`) is missing between the query parameter and the start parameter:

![image](https://github.com/serpapi/public-roadmap/assets/73674035/cc1aeb35-163a-4c1d-94a1-edcc1310c68e)

Using space between the query parameter and the `start` parameter is causing the `start` parameter to be nullified:

<img width="1709" alt="start" src="https://github.com/serpapi/public-roadmap/assets/73674035/c10fdaed-6e9e-4bac-aa65-25491c8cf5b6">

[Example Playground Link](https://serpapi.com/playground?engine=google_shopping&q=Red+dress+size+&+start=10&num=5&no_cache=true&newPara=stick+lr+as_qdr)

Thank you for your feedback. We would be grateful if you let us know if adding an ampersand resolves your problem.

**Comment by miro-scalewest** [comment]
Yes, the space seems to cause the problem. Thanks.
