### ISSUE TITLE
[Google Ads Transparency Center API] Scraping destination URL

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1648]
A user requested scraping the destination URL on Google Ads transparency.

*It seems like it's available only for image ads (We need to go to /creative first by clicking one of the image). For example https://adstransparency.google.com/advertiser/AR12768503566994243585/creative/CR04816933881208897537?region=anywhere&format=IMAGE -

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067261?view=List)

**Comment by tanys123** [comment]
We have deployed a new update that adds `details_link`.
<img width="631" alt="Screenshot 2024-07-09 at 12 15 50 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/c1c2d2ff-9f79-4c7b-8d00-106a3c579b95">

The link lead to ad details in Google Ads Transparency Center
<img width="1461" alt="Screenshot 2024-07-09 at 12 16 41 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/5f42cb33-7fbe-40cf-8d2c-1fab4aa766c5">

**Comment by hilmanski** [comment]
Thank you very much, @tanys123 !
