### ISSUE TITLE
SUPER URGENT: TOP STORIES completely gone from json feeds - PLEASE fix ASAP

### ISSUE THREAD

**Issue by githubfan21** [serpapi/public-roadmap#165]
the majority of feeds now have no top stories 
only link to google top stories
this is happenning for the majority of runs 

https://serpapi.com/searches/6297a2c05119a64132539624/inspect

![image](https://user-images.githubusercontent.com/15785331/171468143-5f64fe33-77f6-4bff-b2ae-31b450431816.png)

"search_information":
{
"query_displayed":
"chicago shooting"
},
"top_stories_link":
"https://www.google.com/search?q=chicago+shooting&oq=chicago+shooting&uule=w+CAIQICIeQ2hpY2FnbyxJbGxpbm9pcyxVbml0ZWQgU3RhdGVz&sourceid=chrome-mobile&ie=UTF-8&tbm=nws&story=GjwSOk11bHRpcGxlIG1hc3Mgc2hvb3RpbmdzIHJlcG9ydGVkIG92ZXIgTWVtb3JpYWwgRGF5IHdlZWtlbmQyMQonm43Bg4LAqM1PyeXJ67774OCWAfGZm4ijlNSRgAGq35q3yqDv178BEKfiqbQFGAVYAQ&fcs=AF650RIv2UkmaS4gs18kIlGNu-b4daj55A&sa=X&ved=2ahUKEwi5yLK55Iz4AhVDRjABHQ5CB0wQ1-YGegQIShAD",
"top_stories_serpapi_link":
"https://serpapi.com/search.json?device=mobile&engine=google&gl=us&google_domain=google.com&hl=en&location=Chicago%2CIllinois%2CUnited+States&q=chicago+shooting&tbm=nws&uule=w+CAIQICIeQ2hpY2FnbyxJbGxpbm9pcyxVbml0ZWQgU3RhdGVz",
"organic_results":
[
{

**Comment by githubfan21** [comment]
it seems this started 5-7 days ago

**Comment by ritu1337** [comment]
@githubfan21 Thank you so much for reporting this issue - Top Stories on mobile should be working now.
![image](https://user-images.githubusercontent.com/12263752/171517020-edb915e3-a9e8-4c87-8862-302b65b84126.png)
![image](https://user-images.githubusercontent.com/12263752/171517033-2b8d47e1-59ac-4f2c-ba05-6056db21d171.png)
