### ISSUE TITLE
[Ebay Search API] Support filtering the results by condition

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1651]
A user requested to be able to filter the results from the Ebay Search API by condition:

<img width="1429" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/42ed5871-5954-469d-8c5f-73a9ac8ee2bb">

[Playground](https://serpapi.com/playground?engine=ebay&_nkw=Playstation+5&ebay_domain=ebay.com) | [Inspect](https://serpapi.com/searches/665ecd5b3d6919cacddc9b95/inspect)

This is available in the actual Ebay search engine with the `LH_ItemCondition` parameter:

<img width="1217" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/7d89bf71-ce2a-4dad-b568-5bacc527f95b">

[Ebay Search](https://www.ebay.com/sch/i.html?_from=R40&_nkw=playstation+5&_sacat=0&rt=nc&LH_ItemCondition=3000)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067404?view=List)

**Comment by ocvit** [comment]
Feature has been released.

Now you can specify item condition(s) via new `LH_ItemCondition` search param.

<img width="1518" alt="Screenshot 2024-09-30 at 10 38 51" src="https://github.com/user-attachments/assets/4eec50bf-a035-413c-8f50-c8d31180649e">
