### ISSUE TITLE
[Google Images API] Allow searches with `filetype:` operator

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1652]
One of our users asked to filter images by file type. This is supported in Google by using the `filetype:x` operator, where the `x` is the image extension (`png`, `jpg`, etc.)

In the past, we've implemented a validator that disallowed using certain `filetype:` values in https://github.com/serpapi/SerpApi/pull/3278, and suggested using `tbs` with the `ift=x` value. This seems to no longer work, and the `filetype:` is the correct approach.

EDIT. It looks like the `tbs=ift:x` is supported as opposed to the `tbs=ift=x` as suggested in the error message. However, I believe we should still allow `filetype` searches, or at least update the error message to `ift:x` instead of `ift=x`.

How to set the filetype search in Advanced Search for Google Images:
![image](https://github.com/serpapi/public-roadmap/assets/28161162/c2b09716-ba91-4f07-9841-af6827b8ab3e)

The result of the above:
<img width="1280" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/eab587ba-c693-45ba-b8b8-ca7339df7142">

Our Playground:
<img width="1670" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/6f04ffec-1181-4e8d-b6df-fd32ed4ffd0a">

[Playground](https://serpapi.com/playground?engine=google_images&q=Coffee+filetype%3Apng&gl=us&hl=en) | [Google Search](https://www.google.com/search?as_st=y&as_q=Coffee&as_epq=&as_oq=&as_eq=&imgar=&imgcolor=&imgtype=&cr=&as_sitesearch=&as_filetype=png&tbs=&udm=2)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067407?view=List)

**Comment by andypple83** [comment]
We've updated our [Google Images API document](https://serpapi.com/google-images-api#api-examples-results-for-coffee-with-tbs-ift-webp-find-images-in-webp-format) page. Please use `tbs=ift:filetype` to find images in the format that you prefer.
