### ISSUE TITLE
[Google Search API] Places_sites wording missing

### ISSUE THREAD

**Issue by RedBillyOne** [serpapi/public-roadmap#1653]
Hi,

The JSON code returns exactly the same term "places_sites" whether it is a "Product Sites" (sites de produits) block or a "Place Sites" (sites de lieux) block, see screenshot below.

Case 1 
![image](https://github.com/serpapi/public-roadmap/assets/152279883/a838e6e0-e2e0-45e1-acce-a473d2cf1c0c)

https://serpapi.com/playground?q=achat+nike+force+one&location=France&google_domain=google.fr&gl=fr&hl=fr&newPara=chips

Case 2
![image](https://github.com/serpapi/public-roadmap/assets/152279883/1ea1d9d9-acbb-4066-8e11-2d9736511efb)

https://serpapi.com/playground?q=formation+imprimerie&location=France&google_domain=google.fr&gl=fr&hl=fr&newPara=chips

 is it possible to return something specific to a block like the name?

It would be good to have for case 1 "Sites de produits" and case 2 "Sites de lieux" in a value of a parameter i.e name:"sites de produits"

Regards.

**Comment by tanys123** [comment]
Thanks @RedBillyOne for mentioning the issue to us 👍. We have deployed a fix to this.

<img width="1094" alt="Screenshot 2024-06-13 at 9 52 05 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/417fd86f-b30c-4f5d-b78a-954f25191d96">
