### ISSUE TITLE
[Google Search API] Company `subsidiaries` are mixed up

### ISSUE THREAD

**Issue by ocvit** [serpapi/public-roadmap#1654]
When company subsidiaries are grabbed from both - carousel and knowledge graph - `subsidiaries` array includes strings and hashes at the same time. Also, in case of `Apple subsidiaries` query, `More` string should be ignored.

<img width="1630" alt="Screenshot 2024-06-05 at 13 59 38" src="https://github.com/serpapi/public-roadmap/assets/13473505/b69a87ea-6f62-45e6-8090-fef83d5a6fa8">

[Playground](https://serpapi.com/playground?q=Apple+subsidiaries&location=United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/665fffb5925641329566f749/inspect)

**Comment by ocvit** [comment]
Consecutive requests using the same query returned different subsidiaries in a knowledge graph - with `MORE` and `51 more` at the end. In these cases, problem is not present with a correct array of hashes. Looks like something is wrong with `More` specifically.

**Comment by ocvit** [comment]
Affected [HTML](https://serpapi.com/searches/ec24bdde98b7c921/665fffb5925641329566f749.html) and [JSON](https://serpapi.com/searches/ec24bdde98b7c921/665fffb5925641329566f749.json)

**Comment by zyc9012** [comment]
> Affected [HTML](https://serpapi.com/searches/ec24bdde98b7c921/665fffb5925641329566f749.html) and [JSON](https://serpapi.com/searches/ec24bdde98b7c921/665fffb5925641329566f749.json)

Let's just provide the inspector link in the first message.

e.g.

[Playground](https://serpapi.com/playground?q=Apple+subsidiaries&location=United+States&gl=us&hl=en)
[Inspect](https://serpapi.com/searches/665fffb5925641329566f749/inspect)

**Comment by ocvit** [comment]
The fix has been released.

`subsidiaries` field (and other facts with `· <more suffix>`) in conjunction with the top carousel is parsed correctly now.

<img width="1373" alt="Screenshot 2024-06-10 at 19 20 01" src="https://github.com/serpapi/public-roadmap/assets/13473505/a3ad0d57-1161-4d29-98ba-c0cbe7c509eb">
