### ISSUE TITLE
[Google Sports Results API] Fetch KGMID of stadium name

### ISSUE THREAD

**Issue by Morgadoooo** [serpapi/public-roadmap#1655]
Hi,

I was wondering if it would be possible to retrieve some more information on the sport results.

Let say for example that I want to query a football (⚽) match like so 
![image](https://github.com/serpapi/public-roadmap/assets/57522029/49538319-74b4-4c0d-b6f6-7c7c12815a7b)

We see that some information are displayed on the search response and are giving us the Stadium name, and I was wondering if retrieving the Knowledge graph id of this information could be done. I don't know if it's possible or not but might be cool to have the possibility to do so since we might have multiple stadiums with the same name might be interesting to be able to differentiate them using the kgmid

**Comment by Morgadoooo** [comment]
Wondering if it is possible since the stadium name generally is a like in which the google stick is provided it might be doable but I'm not sure if this "link" is retrieved on your side when doing the query.

**Comment by andypple83** [comment]
Thanks @Morgadoooo for raising this. I'm happy to help.

We can provide some kgmid for sport teams and stadium for some search results. E.g, there are some KGMIDs for this search:

![Screenshot 2024-06-06 at 17 44 44](https://github.com/serpapi/public-roadmap/assets/99160364/1cd3c4f6-03a4-40e4-8484-df5cbbe09e2e)

![Screenshot 2024-06-06 at 17 45 04](https://github.com/serpapi/public-roadmap/assets/99160364/e54411b0-fa31-4941-b432-4db786f3c953)

The `Saint Mary's Stadium` has `/g/11c47_dkwv` KGMID. 

I'll add these KGMID results into our search results. Will notify you when we released.

Happy scraping!

**Comment by andypple83** [comment]
We've released the fix. The KGMID will be available for the stadium and teams. 

![Screenshot 2024-06-14 at 12 06 13](https://github.com/serpapi/public-roadmap/assets/99160364/701deed4-7033-44f6-977f-3835c659d192)

Feel free to open up more issues when you need our help.

**Comment by Morgadoooo** [comment]
Awesome news! Thanks for the work
