### ISSUE TITLE
[Google Finance API] Scrape `Income Statement` from different periods

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1660]
A user requested that we scrape the `Income Statement` from different periods. This is available in Google Finance by selecting a different period:

<img width="1262" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/7a648d65-19ab-4f31-8f71-f2b7c26d6bbc">

[Google Finance](https://www.google.com/finance/quote/GOOGL:NASDAQ?hl=en)

<img width="1282" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/2f26cfe3-ad2d-4693-b0ec-7d4910d058b5">

[Google Finance](https://www.google.com/finance/quote/GOOGL:NASDAQ?hl=en)

Currently, we only provide the latest statement in the response from our Google Finance API:

<img width="1369" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/3f734590-e091-4198-b576-e2df6867a963">

[Playground](https://serpapi.com/playground?engine=google_finance&q=GOOGL%3ANASDAQ) | [Inspect](https://serpapi.com/searches/6662d4e19bddf7c95a1a989a/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067590?view=List)

**Comment by alexbarron** [comment]
Received another request for this.

[Front](https://app.frontapp.com/open/msg_2ekqlmak?key=S-7H4J5i5UPxSthx3-nZO_cywM7w9KQt)

**Comment by alexbarron** [comment]
Received another request:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070093?view=List)

**Comment by alexbarron** [comment]
A request from a potential customer:

[Front](https://app.frontapp.com/open/cnv_1cn6rzoc?key=PMTvMAyqboxyj7h2kzjDGWIiS23yX3an)

**Comment by ocvit** [comment]
Feature has been released.

Now we fetch all available quarterly and annual data.

<img width="1260" alt="Screenshot 2024-09-18 at 10 44 50" src="https://github.com/user-attachments/assets/e92f391e-bef4-46db-b647-101f9ea38b15">
