### ISSUE TITLE
[Google Maps API] Add `opens_date` support

### ISSUE THREAD

**Issue by timlewfaire** [serpapi/public-roadmap#1663]
The Google Search API recently started surfacing `business_opens_date` in the Knowledge Graph results (`Opens July 15th` in the screenshot)
<img width="1129" alt="Screenshot 2024-06-07 at 12 19 58 PM" src="https://github.com/serpapi/public-roadmap/assets/50117637/18580564-9e94-4098-9d71-22428302a2b3">

It looks like this should show up in the Google Maps API too, but right now it isn't. Can this be added too?
<img width="858" alt="Screenshot 2024-06-07 at 12 16 14 PM" src="https://github.com/serpapi/public-roadmap/assets/50117637/57609e5a-1227-41c1-a102-1e48d5dfb680">

**Comment by hartator** [comment]
Thanks for the report @timlewfaire. Will do! [Playground reproduction](https://serpapi.com/playground?engine=google_maps&q=lagree+plus+in+toronto&ll=%4051.2538%2C-85.3232%2C14z&hl=en&type=search).

**Comment by Alaa-abdulridha** [comment]
This issue now has been resolved.

Before fixing the issue (production):

![image](https://github.com/serpapi/public-roadmap/assets/53356539/561f5683-aeb2-4b26-bd86-0e3a0ae741ab)


After fixing the issue (Production):

![image](https://github.com/serpapi/public-roadmap/assets/53356539/cecf8148-38f9-4342-b7ce-9a276a7ed651)

**Comment by timlewfaire** [comment]
Thank you!!!

**Comment by timlewfaire** [comment]
Hi! I wanted to see if it would be possible for this field to be added to the `local_results` in addition to the `place_results`? For example, in the sandbox
1. `lagree plus in toronto` returns a json with `place_results` and the `opens_date` field
2. `lagree in toronto` is more general returns a json with `local_results` instead without the new `opens_date` field
