### ISSUE TITLE
[Google Maps API] Provide rating distribution of a place

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1666]
A user requested to scrape the rating distribution of a place on our Google Maps API. The information is available on the HTML element.

![CleanShot 2024-06-10 at 09 15 37@2x](https://github.com/serpapi/public-roadmap/assets/4522467/bdc1e7db-28de-457c-9800-31a7e89d39b5)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000067612?view=List)

**Comment by schaferyan** [comment]
Similar to https://github.com/serpapi/public-roadmap/issues/1547

**Comment by aciddjus** [comment]
Yes, we can extract this information and structure it like we do in [some other APIs](https://github.com/serpapi/public-roadmap/issues/1547#issuecomment-2074851077).

![image](https://github.com/serpapi/public-roadmap/assets/6929257/d4eaba07-391b-467c-9f53-6a14d7cee7fb)

**Comment by Ovi** [comment]
We are now showing rating distribution as `rating_summary`

<img width="1728" alt="355833088-3892e948-03f6-4423-b290-21c9d9c99744" src="https://github.com/user-attachments/assets/1d7f334f-d2ed-49f9-b38f-777c8d900f66">

[Playground](https://serpapi.com/playground?engine=google_maps&q=Grace+Street+Coffee+%26+Desserts&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&type=search)
