### ISSUE TITLE
[Google Search API] Things to know is mis-parsed as answer_box

### ISSUE THREAD

**Issue by zyc9012** [serpapi/public-roadmap#1669]
![image](https://github.com/serpapi/public-roadmap/assets/3034310/23b24ebd-3227-49a8-8932-f00487a979ad)

[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=chips+as_qdr+highlight+stick+lr+safe+google_domain+si+form+filter+as_epq+client+source+votes+site+ie+oe+pws+ibp)
[Inspect](https://serpapi.com/searches/6666a7afc573d51a742e8b8a/inspect)

**Comment by ocvit** [comment]
Fix has been released.

`things_to_know` are parsed correctly now, faulty `answer_box` not present.

<img width="1353" alt="Screenshot 2024-06-14 at 11 07 19" src="https://github.com/serpapi/public-roadmap/assets/13473505/091cf979-b8fe-4cac-9f79-0a3a8feb0b1c">
