### ISSUE TITLE
[Google Search API] Missing sport results in some layouts

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#1670]
Sports results are missing with tablet and mobile layout

![Screenshot 2024-06-10 at 16 03 54](https://github.com/serpapi/public-roadmap/assets/99160364/eedb5484-c167-40e4-a8d9-4fed69cb912d)

![Screenshot 2024-06-10 at 16 04 02](https://github.com/serpapi/public-roadmap/assets/99160364/10e381be-5eef-4763-bdb1-1451780dc914)

![Screenshot 2024-06-10 at 17 34 33](https://github.com/serpapi/public-roadmap/assets/99160364/df6e47ca-b597-408b-b402-36dba871d172)

[Playground](https://serpapi.com/playground?q=town+vs+North+Texas&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client) | [Inspect mobile](https://serpapi.com/searches/6666c1329c84acf0e15ff91c/inspect) | [Inspect tablet](https://serpapi.com/searches/6666d75d7f8361fd7761187b/inspect) | [Inspect destop new layout](https://serpapi.com/searches/6666d72a0a90c7dccf48ea38/inspect)

**Comment by ocvit** [comment]
Another variant of new desktop layout. Missing matches and standings.

<img width="1421" alt="Screenshot 2024-11-14 at 15 24 21" src="https://github.com/user-attachments/assets/e536ed92-595c-464e-836d-e9319806ef5a">

[Playground](https://serpapi.com/playground?q=barcelona+fc&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+source+ijn+ie+oe+pws+ibp+rlz) | [Inspect](https://serpapi.com/searches/6735f8d6b691a76177cc5da8/inspect)

-------------

<img width="1473" alt="Screenshot 2024-11-14 at 15 27 09" src="https://github.com/user-attachments/assets/74f5369b-cd35-4604-8416-061c1ad884e1">

[Playground](https://serpapi.com/playground?q=iraq+football+team&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+source+ijn+ie+oe+pws+ibp+rlz) | [Inspect](https://serpapi.com/searches/6735fa98e9b691040ec9a51f/inspect)

**Comment by ocvit** [comment]
I'm converting this issue to a bug as it happens with all major football teams via `X football team` query now.

**Comment by ocvit** [comment]
Fix has been released.

New layouts are parsed correctly now.

<img width="1233" alt="Screenshot 2024-12-11 at 09 22 14" src="https://github.com/user-attachments/assets/d33948b9-c6af-4939-b204-ba169b295306">
