### ISSUE TITLE
[Google Search API] `short_videos` parsed as `places_sites`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1672]
<img width="1710" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/eb6ff663-e6d8-4d12-ac15-ee22b3897abb">

[Playground](https://serpapi.com/playground?q=Coffee&device=mobile&google_domain=google.com&newPara=source+votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ijn+ie+oe+pws+ibp)
[Inspect](https://serpapi.com/searches/66674a49437af24c3ed8a65b/inspect)

**Comment by zyc9012** [comment]
We've released a fix for this. Short videos are parsed correctly.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/4eab873d-2594-42d7-b5b0-26ade173f6c5)
