### ISSUE TITLE
[Google Search API] `extensions` not fully parsed in inline `shopping_results` 

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1674]
![image](https://github.com/serpapi/public-roadmap/assets/73674035/ee6472d9-0759-4ed8-911c-f16413a6e68a)

[Playground](https://serpapi.com/playground?q=jeans+buy&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&highlight=shopping_results&google_domain=google.com&newPara=source+votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ijn+ie+oe+pws+ibp)
[Inspect](https://serpapi.com/searches/6667414f66d81f705d7c6204/inspect)

**Comment by Alaa-abdulridha** [comment]
This issue has been fixed.

pre-fix (production):
![image](https://github.com/serpapi/public-roadmap/assets/53356539/1b63adaf-d639-449a-8486-f7de09a26ebc)


after-fix (production):

![image](https://github.com/serpapi/public-roadmap/assets/53356539/ccbefa2d-507f-462c-8f87-c82ed8f30768)
