### ISSUE TITLE
[Google Search API] `source` has excerpt text in `discussions_and_forums` 

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1675]
![image](https://github.com/serpapi/public-roadmap/assets/73674035/1d22bc94-54b1-40f5-8941-f349ebcb54a9)

[Playground](https://serpapi.com/playground?q=best+magnesium+supplement&location=Austin%2C+TX%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&highlight=discussions_and_forums&google_domain=google.com&newPara=source+votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ijn+ie+oe+pws+ibp)
[Inspect](https://serpapi.com/searches/66674c8f9b6472c6a98627d2/inspect)

**Comment by tanys123** [comment]
We have deployed a fix to the issue. At the same time we added `extensions`, we now provide more information than before 🎉 . Feel free to checkout the [documentation](https://serpapi.com/google-discussions-forums).

<img width="1362" alt="Screenshot 2024-06-13 at 9 32 46 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/94b7ac0b-91c0-40b0-bee2-e1c0c42f99a4">
