### ISSUE TITLE
[Google Maps API] Error when using `br` as `hl`

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1678]
A high-volume customer reported that using `hl:br` on Google Maps returned an error. I can replicate the issue. It's also true for other query.

```
"error":
"We couldn't get valid results for this search. Please try again later.
```

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/unassigned/conversation/102910000067754?view=List) | [Playground](https://serpapi.com/playground?engine=google_maps&google_domain=google.com&hl=br&q=ZARA&type=search) | [Inspect](https://serpapi.com/searches/6668b843a3f4ef10b0613494/inspect)

**Comment by btaunt** [comment]
This has been updated. We have updated the Google Maps`hl` parameter values to match the [officially supported languages](http://localhost:3000/google-maps-languages).

- [SerpApi Google Maps Languages documentation page](https://serpapi.com/google-maps-languages)
