### ISSUE TITLE
[Bing Search API] `description` is not scraped for `ads`

### ISSUE THREAD

**Issue by zyc9012** [serpapi/public-roadmap#1679]
![image](https://github.com/serpapi/public-roadmap/assets/3034310/8b9f76b1-884f-4a99-8350-3fbb91d46831)

[Playground](https://serpapi.com/playground?engine=bing&q=Coffee)
[Inspect](https://serpapi.com/searches/66694cc3c640d2665d1ba03c/inspect)

**Comment by ocvit** [comment]
Fix has been released.

`description` parsing is fixed. Beside that, parsing of multiple `details` as `details_list` is added.

<img width="1498" alt="Screenshot 2024-07-03 at 08 14 43" src="https://github.com/serpapi/public-roadmap/assets/13473505/9ce0f434-4cd2-4a28-adff-c4453836ab5a">
