### ISSUE TITLE
[Yahoo Search API] `title` is not scraped in `local_results`

### ISSUE THREAD

**Issue by zyc9012** [serpapi/public-roadmap#1680]
![image](https://github.com/serpapi/public-roadmap/assets/3034310/c990e372-ff18-44d1-a405-897530bf1891)

[Playground](https://serpapi.com/playground?engine=yahoo&p=Coffee)
[Inspect](https://serpapi.com/searches/666952f42c0844398d8974a5/inspect)

**Comment by ocvit** [comment]
Follow-up after detailed investigation.

We're missing out not only `title` but whole bunch of other things as well. Yahoo changed their `local_results` layout in both desktop and mobile versions.

Beside that, `gps_coordinates` extraction has been broken all this time, providing non-normalized data and only for the first business, e.g.:
```
[{"latitude": "40.78343","longitude": "-73.97946%3B"},null,null,null,null]
```

That's gonna be big PR.

**Comment by ocvit** [comment]
Fix has been released.

All recent changes in Yahoo layouts have been addressed.

Desktop:
<img width="1316" alt="Screenshot 2024-07-12 at 17 10 53" src="https://github.com/user-attachments/assets/1d52d49f-d309-41de-bccc-6419b687cc78">

Mobile:
<img width="1189" alt="Screenshot 2024-07-12 at 17 12 23" src="https://github.com/user-attachments/assets/7ea17841-9ec9-4d25-bfa7-977df943c979">
