### ISSUE TITLE
[Google Search API] Scrape different `labels` for `top_stories`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1681]
This is pretty much the same request as in https://github.com/serpapi/public-roadmap/issues/1644 (thank you @ocvit for implementing the feature!), but the user let us know that there are also different `labels` we can return. Currently, they are returned as `video: true`, although they are not really videos. 

Maybe we can return something like `lable: video` or `label: interview`? I'm not sure if that's possible though?

<img width="1671" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/d525a459-b99e-45cb-b0f9-3134b2dd0677">

[Playground](https://serpapi.com/playground?q=General+election+2024&location=London+TV+Region%2C+England%2C+United+Kingdom&google_domain=google.co.uk&gl=uk&hl=en&device=desktop) | [Inspect](https://serpapi.com/searches/666994df8e02e4a4483c416d/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067234)

**Comment by ocvit** [comment]
Oh, we can return normalized strings instead, like `{..., label: "interview" / "by the numbers"}`. So it will be more generic.

**Comment by ocvit** [comment]
Fix has been released.

Labels are generic now.

<img width="1324" alt="Screenshot 2024-06-14 at 15 37 59" src="https://github.com/serpapi/public-roadmap/assets/13473505/529b5935-c1a6-4b9b-b3a9-fab099e0c1f1">
