### ISSUE TITLE
[Bing Shopping API] Price fields are not extracted anymore

### ISSUE THREAD

**Issue by hartator** [serpapi/public-roadmap#1682]
Our Bing Shopping API doesn't seem to extract any of price fields anymore for some searches:

![CleanShot 2024-06-12 at 18 55 57@2x](https://github.com/serpapi/public-roadmap/assets/307597/2e893fd6-32cd-4595-a4e0-678596c3ffd0)

I can't reproduce on the playground unfortunately, but here's a search with the issue: https://serpapi.com/searches/666a30d2d5a5313e1b91aa8f/inspect

**Comment by aciddjus** [comment]
We have fixed this issue. The `price` field is now extracted for all searches.

![image](https://github.com/serpapi/public-roadmap/assets/6929257/15cbe4f2-3b41-4291-a357-f27a1d2230b0)


----------------

[Playground](https://serpapi.com/playground?engine=bing_shopping&q=Coffee&device=desktop&no_cache=true)
