### ISSUE TITLE
[Bing Place API] Add support

### ISSUE THREAD

**Issue by spirie** [serpapi/public-roadmap#1683]
Do you plan to add Bing Places api, the same as Google GMBs?

**Comment by hartator** [comment]
Thanks for the report @spirie. 👍

![CleanShot 2024-06-14 at 18 26 59@2x](https://github.com/serpapi/public-roadmap/assets/307597/7aab02f0-dfae-4272-8bbf-05461c6900cc)

Do you mean that page?

![CleanShot 2024-06-14 at 18 28 21@2x](https://github.com/serpapi/public-roadmap/assets/307597/ad068a93-9e65-4246-9459-7e42ef770ea2)

Or that page? Or both?

**Comment by spirie** [comment]
Hi @hartator - the second image, direct searching. I know you have Local Pack availability already

**Comment by spirie** [comment]
Specifically looking to be able to scrape the following URL type:

https://www.bing.com/maps?ss=ypid.YN1029x15776547173627203799

Exactly how GMB Profiles are checked

**Comment by hartator** [comment]
Thanks @spirie. We'll add this to our roadmap!

**Comment by hilmanski** [comment]
Hi @spirie, we have implemented the Bing Maps API.
Documentation: https://serpapi.com/bing-maps-api
Live example: https://serpapi.com/playground?engine=bing_maps&q=Coffee&cp=30.307989~-97.749943

Please let us know if you have any feedback.

P.S. Thank you, @tanys123 and everyone who's working on it :)

**Comment by tanys123** [comment]
Thanks @hilmanski 👍

**Comment by spirie** [comment]
Great work guys. Thanks for implementing

**Comment by spirie** [comment]
@hilmanski @tanys123 The only issue I can spot is there is no language specifier.

Sometimes I can get results returned in Czech or German rather than specifying English results/langugage

**Comment by spirie** [comment]
Adding **&setLang=**en-GB to the fetch URL seems to work

Fetching a result in Dutch:
https://www.bing.com/maps/localoverlaybfpr?filters=MapCardType%3A%22details%22+direction_partner%3A%22maps%22+local_ypid%3A%22YN1029x7948950500478976342%22&first=0&count=30**&setLang=nl**

Same result in English:
https://www.bing.com/maps/localoverlaybfpr?filters=MapCardType%3A%22details%22+direction_partner%3A%22maps%22+local_ypid%3A%22YN1029x7948950500478976342%22&first=0&count=30**&setLang=en-GB**

**Comment by NateSkiles** [comment]
@spirie Thank you for the additional feedback! I've opened a new issue for this: [[Bing Place API] Add setLang parameter](https://github.com/serpapi/public-roadmap/issues/1948), please feel free to add additional comments if needed.
