### ISSUE TITLE
[Google Shopping API] Size labels are missing in JSON output

### ISSUE THREAD

**Issue by miro-scalewest** [serpapi/public-roadmap#1687]
Hi, 
I can't really use the size properties, because there are no labels of the actual size, when returned in JSON format. However, thare are labels in the Html variant.

<img width="488" alt="image" src="https://github.com/serpapi/public-roadmap/assets/91669570/ffc534c2-4fce-44b6-ac50-5e11c3a960ad">

<img width="472" alt="image" src="https://github.com/serpapi/public-roadmap/assets/91669570/574a0f7d-0efc-42af-89e9-50c115e2dad5">

**Comment by hilmanski** [comment]
Hi @miro-scalewest thank you for opening an issue. Can you please send us the query sample for your search or a sample link from our [playground](https://serpapi.com/playground?engine=google_shopping), so we can investigate this? Thank you very much for your report!

**Comment by miro-scalewest** [comment]
Here is a sample query:
https://serpapi.com/playground?engine=google_shopping&q=black+shoes+male&location=United+States&gl=us&hl=en

**Comment by tanys123** [comment]
Thanks @miro-scalewest for reporting the issue. We have identified the issue and will let you know once it is fixed.

**Comment by tanys123** [comment]
@miro-scalewest We have fixed the issue, you can try again on your side.

<img width="1047" alt="Screenshot 2024-06-18 at 9 01 48 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/8ca9921a-f286-405b-9d46-369dd37c869f">
