### ISSUE TITLE
[Google Search API] Include position and visibility for `short_videos` results on `mobile`

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1688]
A customer requested that we include the position in the results for `short_videos` entries the response from our Google Search API on `mobile`.

They also noted that only the first 4 results are visible in the UI and you need click on "More short videos" to retrieve the rest. They wanted this visibility information to be included as well.

![image](https://github.com/serpapi/public-roadmap/assets/144151895/14194a87-2630-4112-8ca6-fef3cc8fba94)

[Playground](https://serpapi.com/playground?q=energy+drinks&location=Houston%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&google_domain=google.com&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source) | [Inspect](https://serpapi.com/searches/667000bfedb0349a3ccd1c47/inspect)

[Front](https://app.frontapp.com/inboxes/teams/10643996/inbox/open/102874812700)

**Comment by Ovi** [comment]
[Intercom](https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/conversation/102910000067047#part_id=comment-102910000067047-21909783042)

**Comment by Ovi** [comment]
We now include `position` in `short_videos`

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/e67b864d-fbc5-4234-8b25-01578776bf58">

[Playground](https://serpapi.com/playground?q=khaby+videos&location=Houston%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&google_domain=google.com)
