### ISSUE TITLE
[Bing Search API] Include if business is permanently closed

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1690]
We received a report that we aren't scraping the "Permanently Closed" indicator for businesses appearing under `knowledge_graph` in Bing Search.

![image](https://github.com/serpapi/public-roadmap/assets/9811728/34739b1a-d4bc-4019-96fb-1bc68618bddc)

[Playground](https://serpapi.com/playground?engine=bing&q=sharpshooters+usa) | [Bing Search](http://www.bing.com/search?q=sharpshooters+usa&form=QBLH&sp=-1&ghc=1&lq=0&pq=sharpshooters+usa&sc=11-17&qs=n&sk=&cvid=ECBC4B9A9B31408C989AB794AEFCB00C&ghsh=0&ghacc=0&ghpl=)

[Front](https://app.frontapp.com/open/cnv_1ba14mcc)

**Comment by hilmanski** [comment]
Hi @alexbarron, I think you've shared the wrong Front link.

**Comment by zyc9012** [comment]
We've released support for this. For this kind of business, we now return `permanently_closed: true`.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/623b18ec-bc82-4831-ab9e-04955cb914d0)
