### ISSUE TITLE
[Google Maps API] Scrape `Events` section for `place` results

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1691]
A high volume customer requested that we scrape the `Events` section for place results. Currently this data is not available in the response from our Google Maps API.

<img width="1431" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/4dbdc7db-ecf9-45d2-893f-6e59f23a6057">

[Playground](https://serpapi.com/playground?engine=google_maps&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&place_id=ChIJhRwB-yFawokR5Phil-QQ3zM&type=search&no_cache=true) | [Inspect](https://serpapi.com/searches/6671581cdc02f1fd96242859/inspect)

[Front](https://app.frontapp.com/inboxes/teams/10643996/inbox/open/102972798044)

**Comment by ocvit** [comment]
Feature has been released.

`place_results` now include `events` list.

<img width="1371" alt="Screenshot 2024-08-22 at 18 22 13" src="https://github.com/user-attachments/assets/29c95a4c-3680-4151-b154-ffe5e41f5bb7">
