### ISSUE TITLE
[Google Ads Transparency Center API] No results returned for a `text` search

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1693]
A user reported that Google Ads Transparency Center API doesn't return results for a `text` search, but there are results in the actual Google Ads Transparency Center for the same search query. I was able to reproduce it in the Playground.

![image](https://github.com/serpapi/public-roadmap/assets/144151895/ef327bb4-8ea8-4182-ab6f-d10b8b75387c)

[Playground](https://serpapi.com/playground?engine=google_ads_transparency_center&text=Janssen+Cosmetics&region=2276&start_date=20240319&end_date=20240619) | [Inspect](https://serpapi.com/searches/6672a51624e88e579751f456/inspect)

![image](https://github.com/serpapi/public-roadmap/assets/144151895/5dc917bc-624c-4808-b153-4c87aa4b9f27)

[Google Ads Transparency Center](https://adstransparency.google.com/?region=DE&start-date=2024-03-19&end-date=2024-06-19&domain=Janssen+Cosmetics)

[Front](https://app.frontapp.com/inboxes/teams/10643996/inbox/open/103019358876)

**Comment by tanys123** [comment]
We have fixed the issue. The same search reported is now returning the results.

<img width="1277" alt="Screenshot 2024-06-21 at 2 12 49 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/4f03342a-0c2e-4844-9c45-d447cad20267">

**Comment by Tom-Cedric** [comment]
Thank you @tanys123 and @martin-serpapi!
