### ISSUE TITLE
[Google Search API] Old price present together with new price in Shopping Results

### ISSUE THREAD

**Issue by tanys123** [serpapi/public-roadmap#1697]
![image](https://github.com/serpapi/public-roadmap/assets/10222402/aed33c4a-98bb-4a3f-a54c-e91d7adc3f8a)

[Playground](https://serpapi.com/playground?q=tv+buy&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile) | [Inspect](https://serpapi.com/searches/6673e598ce87f8fa10fc957d/inspect)

**Comment by ocvit** [comment]
Fix has been released.

No more collisions between current `price` and `old_price`.

<img width="1652" alt="Screenshot 2024-06-26 at 16 02 10" src="https://github.com/serpapi/public-roadmap/assets/13473505/5e79d1ec-7b46-4e5c-aa8d-e886022afda4">
