### ISSUE TITLE
[Google Search API] `shipping` is not parsed in Shopping Results

### ISSUE THREAD

**Issue by tanys123** [serpapi/public-roadmap#1698]
![image](https://github.com/serpapi/public-roadmap/assets/10222402/6ffe5174-3f84-432e-97bd-7cb7d9fdbc47)

[Playground](https://serpapi.com/playground?q=toy+buy&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true) | [Inspect](https://serpapi.com/searches/6673e62f47ccf184cd6adbe8/inspect)

**Comment by ocvit** [comment]
Fix has been released.

`shipping` is populated correctly now.

<img width="1649" alt="Screenshot 2024-06-25 at 15 13 35" src="https://github.com/serpapi/public-roadmap/assets/13473505/572c4d6d-fad4-4cb4-bb83-35d82e912003">
