### ISSUE TITLE
[Google Search API] Reviews link is scraped as `website`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1701]
One of our customers reported that the issue with the Reviews link is scraped in the `website` endpoint. This is a similar issue to https://github.com/serpapi/public-roadmap/issues/1575 and was reported by the same customer.

It's difficult to recreate, as the Reviews button is rarely returned in the results, but when it is, it's mixed up.

<img width="1336" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/2b279953-8cae-4c21-87c9-2ba8617dd0a7">

[Inspect](https://serpapi.com/searches/6673b1edfdca3e406db8c362/inspect) | [Front](https://app.frontapp.com/open/cnv_1b97rxi4)

**Comment by marm123** [comment]
More examples from the customer for easier evaluation:

[Inspect 1](https://serpapi.com/searches/6673b2309c84ace66bf61642/inspect)
[Inspect 2](https://serpapi.com/searches/6673aca6797ac60169c0159c/inspect)
[Inspect 3](https://serpapi.com/searches/6673b628d737d792172e08a0/inspect)
[Inspect 4](https://serpapi.com/searches/6673af01ce87f8f968462a0c/inspect)
[Inspect 5](https://serpapi.com/searches/6673b37dfe41d0197295dcd4/inspect)
[Inspect 6](https://serpapi.com/searches/6673b135797ac60169c0177d/inspect)
[Inspect 7](https://serpapi.com/searches/6673b07e5119a63a1d50a8bb/inspect)
[Inspect 8](https://serpapi.com/searches/6673b54fc7ad415c412d4a23/inspect)
[Inspect 9](https://serpapi.com/searches/6673b062969c08108ad7fa73/inspect)
[Inspect 10](https://serpapi.com/searches/6673b6592c68787d8faa0b75/inspect)
[Inspect 11](https://serpapi.com/searches/6673b049359e99ec44e69e10/inspect)

**Comment by tanys123** [comment]
We have fixed the issue, `website` is now parse correctly. We also parse `reviews` link when it is present.

<img width="1120" alt="Screenshot 2024-06-27 at 2 30 09 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/b3fad8a8-9f79-41ea-843f-c423e0ae5eb3">
