### ISSUE TITLE
[Google Ads Transparency Center API] No Results for a Valid `advertiser_id`

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1702]
A customer reported our Google Ads Transparency Center API isn't returning any results for a specific `advertiser_id`.  I've verified the `advertiser_id` is valid and replicated the issue in the Playground.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068037?view=List) | [Search Inspector](https://serpapi.com/searches/66747ad41d986e625beacfe6/inspect) | [Google Ads Transparency Center](https://adstransparency.google.com/advertiser/AR06228624073023291393?region=US) | [Playground](https://serpapi.com/playground?engine=google_ads_transparency_center&advertiser_id=AR06228624073023291393&region=2840)

**Comment by tanys123** [comment]
Duplicated https://github.com/serpapi/public-roadmap/issues/1419

The ads content is age-restricted, it required login to view them. 

<img width="1138" alt="Screenshot 2024-06-21 at 8 47 34 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/73f501ef-3936-419c-b004-c19f798c9c18">
