### ISSUE TITLE
[Google Search API] Knowledge Panel Links

### ISSUE THREAD

**Issue by githubfan21** [serpapi/public-roadmap#1706]
For people searches (donald trump, joe biden, etc) Google displays a knowledge graph with some news stories

Currently the knowledge graph has the tabs and the inline images but not the links to the pages

example: https://serpapi.com/searches/c5a2bb78d2fd1c6a/6675cab93e86acae543ea7c8.html
![image](https://github.com/serpapi/public-roadmap/assets/15785331/6be76e45-3404-4918-b14c-f5d3ac01fbfe)

https://serpapi.com/searches/a1b093fa7ad4c86f/6675d482ca968f591620dce8.html
![image](https://github.com/serpapi/public-roadmap/assets/15785331/3ed59b6d-4aae-48e8-85b9-e5cd2bede1b9)

is there a way to get those links as well

**Comment by hilmanski** [comment]
Hi, thank you very much for your report. We'll investigate this.

**Comment by githubfan21** [comment]
any updates?

**Comment by btaunt** [comment]
Hey @githubfan21 

There is an open PR that just needs final review before we can merge the changes. I will keep this ticket updated and let you know once it is live 👍

**Comment by btaunt** [comment]
This has been updated. We now properly parse Google's new, alternate layout knowledge graph elements.

- [Playground Example](https://serpapi.com/playground?q=steve+jobs&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=source+votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ijn+ie+oe+pws+ibp)
- [Updated Documentation Example](https://serpapi.com/knowledge-graph#api-examples-results-for-jessica-alba)

cc. @githubfan21
