### ISSUE TITLE
[DuckDuckGo API] Scrape the news tab

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1710]
A user requested that the news tab section from DuckDuckGo be scraped.

![CleanShot 2024-06-22 at 08 05 03@2x](https://github.com/serpapi/public-roadmap/assets/4522467/917438f4-ff2c-4e61-a299-d1570cb278fc)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000068068) | [DuckDuckGo news tab sample](https://duckduckgo.com/?q=vessel+underreport&kl=ca-e&iar=news&ia=news)

**Comment by kagermanov27** [comment]
Our DuckDuckdgo News API is live and can be accessed via `engine=duckduckgo_news` parameter.

<img width="1709" alt="image" src="https://github.com/user-attachments/assets/b777f309-b61a-4d7e-9349-cc3088b7e697">

[Documentation](https://serpapi.com/duckduckgo-news-api)
[Playground](https://serpapi.com/playground?engine=duckduckgo_news&q=apple&kl=us-en&highlight=news_results)

**Comment by hilmanski** [comment]
Thank you very much, @kagermanov27 !
