### ISSUE TITLE
[Google Image API] ijn parameter is not working

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1712]
I accidentally found a comment that says ijn parameter is removed. So far, I can't use the ijn on the playground [Playground test 1](https://serpapi.com/playground?engine=google_images&q=Coffee&gl=us&hl=en&ijn=1&newPara=chips) | [Playground test 2](https://serpapi.com/playground?engine=google_images&q=Coffee+sugar&gl=us&hl=en&ijn=100&newPara=chips) | [Inspect sample](https://serpapi.com/searches/667929e7224db13cd7c51a30/inspect)

[Reddit reference](https://www.reddit.com/r/webscraping/comments/1dl4038/how_to_scrape_google_images_search/)

**Comment by Freaky** [comment]
Thanks, @hilmanski.

A fix for this has now been deployed, and searches using the `ijn` parameter should work again as expected.

**Comment by Freaky** [comment]
Reopening as the parameter no longer works.

**Comment by Freaky** [comment]
The `ijn` parameter should now work again.

Additionally a regression for the original fix (#1725) has also been corrected and all supported fields should be accessible once more.
