### ISSUE TITLE
[Google Local API] New type of `price` not parsed

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1714]
![image](https://github.com/serpapi/public-roadmap/assets/73674035/8d11871a-627f-44e1-83d0-6c5407aa291b)

[Playground](https://serpapi.com/playground?engine=google_local&q=Coffee&location=London%2C+England%2C+United+Kingdom&google_domain=google.co.uk&gl=uk&hl=en&highlight=discover_more_places)
[Inspect](https://serpapi.com/searches/6679c826f26ac6d3d5a2b65f/inspect)

**Comment by ocvit** [comment]
Fix has been released.

Parsing of price ranges has been fixed for many currencies.

<img width="1464" alt="Screenshot 2024-10-31 at 12 46 21" src="https://github.com/user-attachments/assets/e9ca5c13-16a4-473b-8380-ad20e9d331df">
