### ISSUE TITLE
[Bing Search API] `thumbnail` of dynamic keys in `knowledge_graph` are missing protocol

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1718]
![image](https://github.com/serpapi/public-roadmap/assets/73674035/dcf4f045-e591-4a9c-b35a-32fee9be8f93)

[Playground](https://serpapi.com/playground?device=desktop&engine=bing&q=Coffee)
[Inspect](https://serpapi.com/searches/667a8b2c8ccee018212fa82b/inspect)

**Comment by ocvit** [comment]
Probably related: https://github.com/serpapi/public-roadmap/issues/1686

**Comment by kagermanov27** [comment]
>Probably related: https://github.com/serpapi/public-roadmap/issues/1686

@ocvit, different root causes as the parsers are not reused within each other.

**Comment by ocvit** [comment]
Fix has been released.

Thumbnail links have correct format now.

<img width="1435" alt="Screenshot 2024-12-13 at 11 03 24" src="https://github.com/user-attachments/assets/3978f929-4b8a-42b5-8ac8-87bd14bf3440" />
