### ISSUE TITLE
[Bing Search API] Mistakenly parsed `lists` in `knowledge_graph`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1719]
![image](https://github.com/serpapi/public-roadmap/assets/73674035/72927e88-4593-49ab-9eb6-eb82366c4d6a)

[Playground](https://serpapi.com/playground?device=desktop&engine=bing&q=Steve+Jobs)
[Inspect](https://serpapi.com/searches/667a8d1ac999038fd7a46a52/inspect)

`knowledge_graph` -> `lists` contain elements from dynamic keys `compare`, and `explore_more`.

**Comment by btaunt** [comment]
This has been fixed. We no longer incorrectly double parse `compare` and `explore_more` values into `lists`.

- [Playground](https://serpapi.com/playground?device=desktop&engine=bing&q=Steve+Jobs)
