### ISSUE TITLE
[Bing Images API] `thumbnail` of `related_searches` missing

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1720]
![image](https://github.com/serpapi/public-roadmap/assets/73674035/2d713987-a5c4-486c-8d66-62f51da147e3)

[Playground](https://serpapi.com/playground?device=desktop&engine=bing_images&q=coffee)
[Inspect](https://serpapi.com/searches/667a9ca447ccf1ac1f0c100e/inspect)

**Comment by btaunt** [comment]
This has now been updated to properly parse the thumbnail URL:

- [Playground](https://serpapi.com/playground?engine=bing_images&q=coffee&device=desktop)
