### ISSUE TITLE
[Google Ads Transparency Center] `image` is not scraped for some results

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1721]
One of our users reported that we're sometimes not scraping `image` for certain ads. I've been able to recreate the issue:

<img width="1670" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/d44603b6-178c-4a64-a842-f47351ed5868">

[Playground](https://serpapi.com/playground?engine=google_ads_transparency_center&advertiser_id=AR04878410153298231297&region=2203) | [Inspect](https://serpapi.com/searches/667ace555119a642c42f601f/inspect)
[Front](https://app.frontapp.com/open/cnv_1bfpuwik)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Front](https://app.frontapp.com/open/cnv_1bhejrj0?key=vB-NzvYZ76AxESJZ_gPtb1ViwCQX552N) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068204?view=List)

**Comment by ocvit** [comment]
Blank spots on the grid are not images, they are iframes (embedded HTMLs) that are loaded via separate JS files, links to which we save in `ad_creatives.[].link` fields. So there are 2 concerns:

1. We tend not to make additional requests.
2. The embedded HTML can have any kind of structure with any number of images (if any).

I don't think we can support it using current approach.

**Comment by tanys123** [comment]
As @ocvit mentioned, we are not able to support it currently. However, we provided a workaround in a [blog post](https://serpapi.com/blog/retrieving-a-direct-media-link-from-the-google-ads-transparency-center-api). Feel free to check it out to see if it works with your workflows.

**Comment by marm123** [comment]
Thanks @ocvit and @tanys123. I'll close it as not planned.
