### ISSUE TITLE
[Google Maps API] Results Not Scraped

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1722]
Two users reported our Google Maps API is currently returning the "Google hasn't returned any results for this query," error for searches where results are visible in the HTML.

After investigating, it appears all Google Maps API searches with `type=search` are currently returning a "fully empty" response. Searches with `type=place` appear to work as expected.

<img width="1410" alt="Screenshot 2024-06-25 at 1 09 56 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/1a09e3f3-ee96-4974-87aa-d762fbd7427d">

[Playground](https://serpapi.com/playground?engine=google_maps&q=Coffee&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&type=search&no_cache=true) | [Inspector](https://serpapi.com/searches/667a41d12ff42132c070d429/inspect) | [Intercom 1](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068155?view=List) | [Intercom 2](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068156?view=List)

**Comment by NateSkiles** [comment]
I found adding the `start=0` parameter seems to be a workaround to this at the moment.

Example:
Without start: [link](https://serpapi.com/playground?engine=google_maps&q=QD%27s+Bar&ll=%4045.5219888%2C-122.7029788%2C14z&hl=en&type=search)

With start: [link](https://serpapi.com/playground?engine=google_maps&q=QD%27s+Bar&ll=%4045.5219888%2C-122.7029788%2C14z&hl=en&type=search&start=0)

**Comment by schaferyan** [comment]
Another user reported this. In their case using `start=0` isn't an option, as this requires the `ll` parameter. They don't have the GPS coordinates as they are using our Google Maps API to get those:

[Front](https://app.frontapp.com/open/msg_2efyjqvw?key=TmVtu_NBTgRBx8tzxm-r9wfdh0ZMzvv-)

**Comment by dragonkhoi** [comment]
The start=0 helped with some of our queries, but it still is not working for some other queries. It is not returning anything. 
![image](https://github.com/serpapi/public-roadmap/assets/16108916/b3e6c7f4-261a-4e7a-9e75-67653f411d58)

**Comment by schaferyan** [comment]
Thank you @dragonkhoi!

Here is the Search Inspector link for that search:

[Inspector ](https://serpapi.com/searches/667b3d1f0574f56d8668d916/inspect)

**Comment by hilmanski** [comment]
Additional sample from the user: [Inspect](https://serpapi.com/searches/667b600f5f220337074241db/inspect)

**Comment by schaferyan** [comment]
Freezing this for now, since Google rolled back to the old layout. It looks like @zyc9012 has a fix ready to go should Google re-deploy the new layout.

**Comment by zyc9012** [comment]
We've released a fix for this. Though Google has rolled back the layout, this fix ensures that Google Maps API will still work if Google brings the new layout back.
