### ISSUE TITLE
[Google News API] `snippet` field missing in the response

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1723]
A user reported that the `snippet` field is missing for `news_results` entries in the response from our Google News API. I was able to reproduce it in the Playground.

<img width="1422" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/c605be11-1bfd-4b4a-95a4-f0258f237912">

[Playground](https://serpapi.com/playground?engine=google_news&q=pizza&gl=us) | [Inspect](https://serpapi.com/searches/667c0196925641c3bac4bd2b/inspect)

The `snippet` field is included in the `JSON structure overview` and the examples in our Google News API documentation:

[Google News API documentation](https://serpapi.com/google-news-api)

[Front](https://app.frontapp.com/open/cnv_1bfr2dgc?key=J_ya0LhWhKcBYEiHmRYdn8facR69ZYsR) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068147?view=List)

**Comment by martin-serpapi** [comment]
Another user reported this:

[Front](https://app.frontapp.com/open/cnv_1bjnunbw?key=1hEaDyuhJfmJqSIrTeAcBVSnFsGeNgnH) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068289?view=List)

**Comment by Ovi** [comment]
> Google doesn't seem to return `snippet` anymore in their HTML.

I’ve checked multiple examples, and it seems that Google is indeed no longer returning `snippet` in the HTML.

**Comment by hartator** [comment]
@Ovi make sure to close the GitHub issue. Thank you!
