### ISSUE TITLE
[Google Images API] Missing Information in Paginated Searches 

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1725]
A customer reported we aren't scraping the `original`, `original_width`, or `original_height` in Google Images API searches where `ijn` > 0.

I confirmed this in the Playground. I also noticed the `related_content_id` and `serpapi_related_content_link` seem to be missing in paginated searches as well.

<img width="1410" alt="Screenshot 2024-06-26 at 9 33 28 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/19f52be0-519e-4721-b913-5e9e1d09ba87">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068185?view=List) | [Inspector](https://serpapi.com/searches/667c3fe82ff4217bf7faf6c2/inspect) | [Playground](https://serpapi.com/playground?engine=google_images&q=Coffee&gl=us&hl=en&ijn=1)

**Comment by hilmanski** [comment]
A user reported this issue.

[Front](https://app.frontapp.com/open/cnv_1bh5svoc?key=JHscOOHOpzwFYmiHkmA-GVRaT0evjFIM)

**Comment by Expectimax** [comment]
yes, I have the same issue. A quick fix would be lovely otherwise, the API is basically not usable at the moment.

**Comment by Freaky** [comment]
A fix has been deployed and the missing fields should now be available on all pages once more:

![1725-fix](https://github.com/serpapi/public-roadmap/assets/58758/438952bb-fe4a-46fd-8e05-ec4427e6de5b)

Additionally a regression in the original fix for #1712, where the `ijn` parameter itself was no longer effective, has also been corrected.

Thanks for your patience @Expectimax, and anyone else waiting on this.
