### ISSUE TITLE
High res images on Google Lens search and Google Shopping API

### ISSUE THREAD

**Issue by Techsetter** [serpapi/public-roadmap#1726]
Could we please get high res images instead of the low-res thumbnails?

**Comment by schaferyan** [comment]
Unfortunately, it's not possible to provide the higher resolution images in the Google Shopping API responses, as Google doesn't provide access these in Google Shopping results. To get higher resolution images corresponding to Google Shopping results you can extract the `product_id` and use it to query our Google Product API. The images are available in Google Product API responses in the `product_results.media` array. 

For Google Lens, can you provide an example of accessing higher resolution images via a Google Lens search in the browser? My current impression is that Google Lens only provides thumbnails and a link to the webpage where the original image is found. Unfortunately, if Google Lens doesn't provide higher resolution images there is nowhere for us to scrape them from.

**Comment by schaferyan** [comment]
@Techsetter I'm closing this for now since I'm not aware of Google providing high res images in shopping or lens results. Feel free to reopen it if you have an example!
