### ISSUE TITLE
[Google Maps API] `opens_date` in `local_results`

### ISSUE THREAD

**Issue by timlewfaire** [serpapi/public-roadmap#1727]
Following up from https://github.com/serpapi/public-roadmap/issues/1663#issuecomment-2187244743 :

I wanted to see if it would be possible for this field to be added to the `local_results` in addition to the `place_results`? For example, in the sandbox

1. "lagree plus in toronto" returns a json with `place_results` and the `opens_date` field
2. "lagree in toronto" is more general returns a json with `local_results` instead without the new `opens_date` field

Thanks!
Tim

**Comment by schaferyan** [comment]
Thanks for the issue, @timlewfaire. Can you share an example of a local results page where this field is visible? It looks like it only appears in place results.

Unfortunately, if Google only includes this field in place results, there is no way for us to include it in local results.

**Comment by timlewfaire** [comment]
Ah got it--wasn't sure if it would be available in local results as well, but thank you for the confirmation that it isn't!

**Comment by schaferyan** [comment]
Thanks for understanding, Tim! If you do see it in local results via your browser, don't hesitate to share an example as we aim to scrape all of the available information.

**Comment by schaferyan** [comment]
Thanks for understanding, Tim! If you do see it in local results via your browser, don't hesitate to share an example as we aim to scrape all of the available information.
