### ISSUE TITLE
[Bing Search API] Expanded `sitelinks` parsed as `inline`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1728]
![image](https://github.com/serpapi/public-roadmap/assets/73674035/b9f97df2-3ef1-43c9-bad1-00c7cb029f7a)

[Playground](https://serpapi.com/playground?engine=bing&q=Coffee&newPara=form)
[Inspect](https://serpapi.com/searches/667c8a7ed5a531a8fe3b1435/inspect)

**Comment by btaunt** [comment]
This has been fixed. We no longer incorrectly parse `:sitelinks > :expanded` as `inline` on these newer card layouts.
