### ISSUE TITLE
[Google Image API] Update on filter parameters

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1729]
A user reported that `il:cl` is not working to filter images at our Google Image API. 

Upon testing directly on the Google side, it seems that Google replaced the il with the sur parameter instead. Let's update our documentation and blog post accordingly.

[Google Image API docs](https://serpapi.com/google-images-api#api-examples-results-for-coffee-with-tbs-il-cl-creative-commons-licenses) | [Blog Post by @marm123 ](https://serpapi.com/blog/filtering-google-images-and-google-videos-results/)  | [Video at YouTube min 2:50](https://www.youtube.com/watch?v=Y8RmgLb7ra0&t=4s)

[Playground sample with sur](https://serpapi.com/playground?engine=google_images&q=paris+street+view&gl=us&hl=en&tbs=sur%3Acl&newPara=chips) | [Playground sample with il](https://serpapi.com/playground?engine=google_images&q=paris+street+view&gl=us&hl=en&tbs=il%3Acl&newPara=chips)

**Comment by andypple83** [comment]
I created a [new issue](https://github.com/serpapi/public-roadmap/issues/1854) to improve our Google Image API.

**Comment by andypple83** [comment]
We've updated [Google Image API docs](https://serpapi.com/google-images-api#api-examples-results-for-coffee-with-tbs-il-cl-creative-commons-licenses), [blog posts](https://serpapi.com/blog/filtering-google-images-and-google-videos-results/), and [videos](https://www.youtube.com/watch?v=Y8RmgLb7ra0&t=4s).
