### ISSUE TITLE
[Google Search API] Scrape price level information from the `knowledge_graph`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1730]
One of our customers requested us to scrape the price level information from the `knowledge_graph`. It looks like we're scraping this for certain results, but in the `type` field. I believe the price level should be a separate field:

price level extracted in the `type` field:
<img width="1669" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/ef267377-fe81-4aa2-958d-6e4040c83967">

`type` scraped without the price level information (price level is not scraped at all):
<img width="1670" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/0b6c64a5-f3f8-408e-b50f-b3fc71bf4b25">

[Playground](https://serpapi.com/playground?q=ECK+Restaurant+Bratislava&device=desktop) | [Inspect](https://serpapi.com/searches/667d74075b54ef8f1275ebc9/inspect)
[Front](https://app.frontapp.com/open/cnv_1bhkc3mk)

**Comment by tanys123** [comment]
We have deployed a fix to the above issue, now `price` is extracted correctly. In addition, Google added price distribution to Knowledge Graph, we parse it in `price_details`. Check out the [documentation](https://serpapi.com/knowledge-graph#api-examples-price-details-for-nami-nori) for more details.

<img width="714" alt="Screenshot 2024-07-16 at 10 19 55 AM" src="https://github.com/user-attachments/assets/a1ce5141-fc4c-4203-bfcb-c4b1d4abaf02">
