### ISSUE TITLE
[Google News API] Support `hl` parameter

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1731]
It looks like the new.google.com supports the `hl` parameter, which affects the output. One of our users reported that they are not getting the correct results:

Search for `gl=id` from our Playground:
<img width="1673" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/23424a30-fb33-44ee-a041-e8ceb0547750">

Results from Google News with `hl=en-ID` (consistent with results from the Playground):
<img width="1313" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/0b9f4f42-c363-42e8-9954-4f0a267267da">

Results from Google News with `hl=id`:
<img width="1322" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/adbe643c-32c0-4dce-86fd-7f01e564d16d">

[Playground](https://serpapi.com/playground?engine=google_news&q=IHSG&gl=id&newPara=hl) I [Inspect](https://serpapi.com/searches/667d6e85224db10c00d50c71/inspect)
[Google News (`hl=en-ID`)](https://news.google.com/search?q=IHSG&gl=ID&hl=en-ID&ceid=ID:en) | [Google News (`hl=id`)](https://news.google.com/search?q=IHSG&gl=ID&hl=id&ceid=ID:id)

**Comment by Ovi** [comment]
We now support `hl` parameter in Google News API

<img width="1728" alt="Screenshot 2024-09-03 at 5 30 12 PM" src="https://github.com/user-attachments/assets/acdfcd91-1563-436f-92ef-dbde922c57cd">

[Playground - AR](https://serpapi.com/playground?engine=google_news&gl=us&hl=ar&hl=ar)
