### ISSUE TITLE
[Google Flights API] `booking_request ` redirects to the provider default search instead of specific result

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1732]
One of our users reported that they are not getting expected search results when accessing the `booking_request` from booking options. I've checked and was able to recreate the issue:

Playground search:
<img width="1668" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/6fcac16f-59b8-405a-9b57-679ea0319d5b">

The page that's returned when accessing the `booking_request`:
<img width="1665" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/dc342eb4-1bec-4f48-9dff-e3abbe06e154">

The same search in Google Flights:
<img width="1576" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/9a74a003-3ca4-468b-907b-ec3408f707a4">

Correct page when accessing the booking option directly:
<img width="1451" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/f4e5ceaf-c8d5-4a3b-9a5c-c1010b7f98c9">

[Playground](https://serpapi.com/playground?engine=google_flights&departure_id=JFK&arrival_id=AUS&gl=us&hl=en&currency=USD&outbound_date=2024-06-28&return_date=2024-07-04&booking_token=WyJDalJJYTJkMU1tWnJMVEpLTVVGQlEwRmlWbWRDUnkwdExTMHRMUzB0TFhscFltSmtPVUZCUVVGQlIxbzVaMDB3U1hrMmVUSkJFZ2hFVERJM01qVWpNUm9MQ05mcEFoQUNHZ05WVTBRNEhIRFg2UUk9IixbWyJKRksiLCIyMDI0LTA2LTI4IiwiQVVTIixudWxsLCJETCIsIjEyMzMiXV0sW1siQVVTIiwiMjAyNC0wNy0wNCIsIkpGSyIsbnVsbCwiREwiLCIyNzI1Il1dXQ%3D%3D) | [Inspect](https://serpapi.com/searches/667d80d9351764b64d0bd397/inspect) | [`booking_request` link](https://www.delta.com/flight-search/search?cabin=BASIC-ECONOMY&amp;paxCount=1&amp;price=462.95&amp;tripType=roundTrip&amp;exitCountry=US&amp;currencyCd=USD&amp;fareBasis=KA0OA0BQ:UA0NA0BQ&amp;vendorRedirectFlag=true&amp;vendorID=Google&amp;itinSegment%5B0%5D=0:E:JFK:AUS:DL:1233:JUN:28:2024:06P&amp;itinSegment%5B1%5D=1:E:AUS:JFK:DL:2725:JUL:04:2024:03P&amp;numOfSegments=2&amp;mkcpgn=MS_GFSR_DESK_DOM_TR_DL_140414_GFSDESK_US)
[Direct Google Flights search](https://www.google.com/travel/flights/booking?tfs=CBwQAhpAEgoyMDI0LTA2LTI4IiAKA0pGSxIKMjAyNC0wNi0yOBoDQVVTKgJETDIEMTIzM2oHCAESA0pGS3IHCAESA0FVUxpAEgoyMDI0LTA3LTA0IiAKA0FVUxIKMjAyNC0wNy0wNBoDSkZLKgJETDIEMjcyNWoHCAESA0FVU3IHCAESA0pGS0ABSAFwAYIBCwj___________8BmAEB&tfu=CnBDalJJU0hwNVJXMWxkazF5Y1d0QlNFdG5TRUZDUnkwdExTMHRMUzB0ZDJaaVoyOHhNMEZCUVVGQlIxbzVaMVZCVDB4R2FIbEJFZ2hFVERJM01qVWpNUm9MQ05mcEFoQUNHZ05WVTBRNEhIRFg2UUk9EgIIACIDCgEw&hl=en&gl=us&curr=USD) | [Direct Booking option link](https://www.delta.com/complete-purchase/trip-summary?cartId=965d2ac5-a02c-4c59-91a1-c29ea9557bd1&cacheKeySuffix=dbeb93be-9a4d-43e4-a467-18a02ae3c6b5&app=sl-sho&itinSegment%5B0%5D=0:E:JFK:AUS:DL:1233:JUN:28:2024:06P&mkcpgn=MS_GFSR_DESK_DOM_TR_DL_140414_GFSDESK_US&itinSegment%5B1%5D=1:E:AUS:JFK:DL:2725:JUL:04:2024:03P&paxCount=1&currencyCd=USD&numOfSegments=2&cabin=BASIC-ECONOMY&exitCountry=US&vendorID=Google&vendorRedirectFlag=true&tripType=roundTrip&fareBasis=KA0OA0BQ:UA0NA0BQ&price=462.95&vendorReferrerUrl=https:%2F%2Fwww.google.com%2F)
[Front](https://app.frontapp.com/open/cnv_1bh9ec9o)

**Comment by zyc9012** [comment]
I did another search ([Inpsect](https://serpapi.com/searches/667e2b231baebb1e98842913/inspect)), and the links were redirected to the purchase page correctly.

The second and third options in @marm123's [Inspect](https://serpapi.com/searches/667d80d9351764b64d0bd397/inspect) also redirect to the purchase page.

So I don't think we can fix it on our side. It's more of an issue on Google's side.

**Comment by arcrank** [comment]
I am talking about the POST request. But as you said thankfully I am unblocked as converting the params from post to get yields a valid GET link.

**Comment by hartator** [comment]
> I am talking about the POST request. But as you said thankfully I am unblocked as converting the params from post to get yields a valid GET link.

Can you share an example of what you mean? Thanks!

All the Google links seem to be already regular GET requests. I don't unfortunately think that we be able to scrape the checkout page of the actual airline if that's what you meant.
