### ISSUE TITLE
[Google Search API] Missing open/close on Top Sights results

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#1734]
Google returns open/close info in their top sights

![Screenshot 2024-06-28 at 15 48 02](https://github.com/serpapi/public-roadmap/assets/99160364/f5054e4b-9075-4f51-baaf-3d3f97d27149)

[Playground](https://serpapi.com/playground?q=top+sights+paris&gl=us&hl=en&device=mobile&no_cache=true&highlight=popular_destinations&google_domain=google.com&newPara=source+votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ijn+ie+oe+pws+ibp) | [Inspect](https://serpapi.com/searches/667e5bce0574f52b9d30c365/inspect)

**Comment by aciddjus** [comment]
Thanks, @andypple83. Please add a `type` badge when opening an issue.

**Comment by btaunt** [comment]
This has been updated. We now parse both the `open_state` and `hours` values (if present).
