### ISSUE TITLE
[Bing Search API] Incorrect `title` for knowledge graph for new layout

### ISSUE THREAD

**Issue by btaunt** [serpapi/public-roadmap#1736]
We currently parse the wrong element for `title` when Bing renders the "newer" knowledge graph layout:

<img width="722" alt="Screenshot 2024-06-28 at 1 58 27 PM" src="https://github.com/serpapi/public-roadmap/assets/137819397/7e592d81-e58c-468f-9849-3b81915a8f56">

- [Inspect](https://serpapi.com/searches/667ef9c94055aac296cbdd17/inspect)
- [Playground (might be inconsistent)](https://serpapi.com/playground?engine=bing&q=steve+jobs&no_cache=true&newPara=form)

Found with @schaferyan

**Comment by zyc9012** [comment]
We've released a fixed for this. `title` is now correctly scraped.

![image](https://github.com/serpapi/public-roadmap/assets/3034310/1045f265-68f0-4c67-a67e-7c7cd00cdad5)
