### ISSUE TITLE
[Bing Search API] Knowledge graph `description` is incorrectly scraped in some cases

### ISSUE THREAD

**Issue by zyc9012** [serpapi/public-roadmap#1738]
![image](https://github.com/serpapi/public-roadmap/assets/3034310/42db0026-c08e-464b-a1f6-f94fb9b5abd2)

[Playground](https://serpapi.com/playground?engine=bing&q=black+myth+wukong)
[Inspect](https://serpapi.com/searches/6682350e10d744c114628d6b/inspect)
[Inspect 2](https://serpapi.com/searches/66822ab237014c28e3f49835/inspect)

**Comment by tanys123** [comment]
We have deployed a fix to the issue.

<img width="1451" alt="Screenshot 2024-07-04 at 10 10 10 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/97602eee-2d67-4731-a556-a6e741cca585">

**Comment by aciddjus** [comment]
Thanks @tanys123. Make sure to change the status of the issue to `completed`.
