### ISSUE TITLE
[Bing Search API] `items` is not scraped for `inline_videos`

### ISSUE THREAD

**Issue by zyc9012** [serpapi/public-roadmap#1739]
![image](https://github.com/serpapi/public-roadmap/assets/3034310/0aea08d7-c285-4c16-a5d0-451e28cb0a94)

[Playground](https://serpapi.com/playground?engine=bing&q=%E6%9C%89%E5%93%AA%E4%BA%9B%E7%A5%9B%E6%B9%BF%E7%9A%84%E6%96%B9%E6%B3%95&location=China&mkt=zh-cn&no_cache=true)
[Inspect](https://serpapi.com/searches/66823979a5ad6d1fc5c653b8/inspect)

**Comment by Alaa-abdulridha** [comment]
Before fixing the issue (Production):

![image](https://github.com/user-attachments/assets/001e5791-3743-433a-bea4-49ec68026575)


After fixing the issue (Production):

![image](https://github.com/user-attachments/assets/50c02e14-57fb-466a-8435-f71e72202faa)
