### ISSUE TITLE
[Google Search API] Date and Source Parsed into Title in Top Stories

### ISSUE THREAD

**Issue by githubfan21** [serpapi/public-roadmap#1741]
JSON is saving the date field as the title in Top Stories
it happens every here and there

https://serpapi.com/searches/1555480712dd15f3/6684075295bf926528c52da6.html

![image](https://github.com/serpapi/public-roadmap/assets/15785331/afbc8414-b801-4c41-9ef8-c549f6a56916)
![image](https://github.com/serpapi/public-roadmap/assets/15785331/be9f1efe-04bd-45e6-9ca6-8ce81fa72333)

**Comment by schaferyan** [comment]
Thanks for the issue @githubfan21 !

[Search Inspector](https://serpapi.com/searches/6684075295bf926528c52da6/inspect)

**Comment by tanys123** [comment]
Thanks @githubfan21 for reporting the issue. `title` is now getting the correct value.

<img width="1138" alt="Screenshot 2024-07-04 at 10 03 32 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/7fc60d75-a15c-477b-900a-373afd6728ce">
