### ISSUE TITLE
 Issue with SERP Job Listing Endpoint - Missing Apply Options

### ISSUE THREAD

**Issue by nadeemsupport** [serpapi/public-roadmap#1742]
I am encountering an issue with the SERP job listing endpoint. When I request job listings, the apply options are not being returned. Can you please investigate whether there is an issue with the SERP endpoint?

Thank you for your assistance.

**Comment by schaferyan** [comment]
Duplicate of https://github.com/serpapi/public-roadmap/issues/1259

**Comment by schaferyan** [comment]
Duplicate of https://github.com/serpapi/public-roadmap/issues/1259
