### ISSUE TITLE
[Google Search API] Scrape Google trains answer box

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#1744]
A user requested that the Trains Answer Box be scrapped from the Google Search API, similarly to the `google_flights` answer box.

![Screenshot 2024-07-03 at 3 32 07 PM](https://github.com/serpapi/public-roadmap/assets/78574304/9dd43d10-fa68-4cf7-98aa-f63e4b89b502)

[Front](https://app.frontapp.com/open/cnv_1blyvtng?key=4X50hIyVmJQedEbDUaMa7zG6TbapAcI3) | [Playground](https://serpapi.com/playground?q=Book+train+from+Boston+to+Washington+D.C.+on+2024-07-25&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&newPara=chips+highlight+stick+lr+as_qdr+as_qdr%255C+as_qdr%5C) | [Google Search Sample](https://www.google.com/search?q=Book+train+from+Boston+to+Washington+D.C.+on+2024-07-25&oq=Book+train+from+Boston+to+Washington+D.C.+on+2024-07-25&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM&hl=en&gl=us&sourceid=chrome&ie=UTF-8)

**Comment by vuemix** [comment]
Let us know if there are any details that would help implement this feature. At the moment we are scraping this ourselves from the serp HTML response. All of the relevant data appears to be in the gws-wiz-serp data. So far I have seen two distinct formats. I'm not sure of your process for extracting the information but I can detail my extraction procedure if expedites native serp support.

**Comment by Ovi** [comment]
We now parse train answer box as `transport_options` type:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/e21d59c5-1b12-4cd3-b668-2a7d16b18a4d">

[Playground](https://serpapi.com/playground?q=Book+train+from+Boston+to+Washington+D.C.+on+2024-10-25&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com) | [Documentation](https://serpapi.com/direct-answer-box-api#api-examples-transport-options-answer-box)
