### ISSUE TITLE
[Google Search API] `recent_earthquakes` type `answer_box` has wrong `type`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1745]
<img width="1696" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/83a1c60e-e327-4504-8106-e9b58c81ae01">

[Playground](https://serpapi.com/playground?q=earthquake&highlight=answer_box&google_domain=google.com&newPara=source+votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ijn+ie+oe+pws+ibp)
[Inspect](https://serpapi.com/searches/6687e024aef26458637ff680/inspect)

The `type` key should be `recent_earthquakes` instead of `unknown`.

**Comment by aciddjus** [comment]
Thank you, @ocvit 👍 

Make sure to follow steps 12 and 13 from our [documentation page](https://github.com/serpapi/SerpApi?tab=readme-ov-file#contributing-and-deploying).

**Comment by ocvit** [comment]
Fix has been released.

`type` field in `answer_box` for public alerts is parsed correctly now.

<img width="1165" alt="Screenshot 2024-07-09 at 13 11 24" src="https://github.com/serpapi/public-roadmap/assets/13473505/9f131adf-bce3-4530-a324-d5632fb3896f">
