### ISSUE TITLE
[Google Search API] `currency_converter` type `answer_box` is missing `chart`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1748]
<img width="1696" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/a632ff3f-ae60-452e-8170-7e1652a22584">

[Playground](https://serpapi.com/playground?q=How+much+is+100+euros+in+us+dollars%3F&gl=us&hl=en&highlight=answer_box&google_domain=google.com&newPara=source+votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ijn+ie+oe+pws+ibp)
[Inspect](https://serpapi.com/searches/6687ddd596f5d7d8d9fc2ea6/inspect)

**Comment by kagermanov27** [comment]
The issue has been resolved. We scrape `answer_box` -> `chart` again.

Before:

![image](https://github.com/serpapi/public-roadmap/assets/73674035/18df1462-2154-49ef-b0a9-a0e4b39a14ef)

After:

<img width="1709" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/dd7b7414-500f-425d-b01f-dd9359b77040">

**Comment by aciddjus** [comment]
Thanks, @kagermanov27 👍 

Please update the `status` badge to `completed` in the future so the issue shows on our [Release Notes](https://serpapi.com/release-notes) page.
