### ISSUE TITLE
[Google Search API] `weather_results` type `answer_box` is missing fields for `mobile` searches

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#1749]
<img width="1696" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/99a3ac01-dc05-4940-9608-bcd5a84662a2">

The `forecast` key is missing the last 4 days even though it is shown in the HTML.
The `hourly_forecast` key is missing completely.

[Playground](https://serpapi.com/playground?device=mobile&engine=google&gl=us&google_domain=google.com&hl=en&q=What%27s+the+weather+in+Dallas%3F)
[Inspect](https://serpapi.com/searches/6687dc0596f5d7d97e4a6909/inspect)

**Comment by ocvit** [comment]
Fix has been released.

Forecasts are full now.

<img width="1302" alt="Screenshot 2024-07-22 at 16 15 48" src="https://github.com/user-attachments/assets/e567a320-2232-46c2-aced-894b48f664b5">
