### ISSUE TITLE
[Google Search API] Scrape Google bus answer box

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#1750]
A user requested that the Bus Answer Box be scrapped from the Google Search API, similar to the `google_flights` answer box.

![Screenshot 2024-07-05 at 11 15 46 AM](https://github.com/serpapi/public-roadmap/assets/78574304/f8be610d-8b74-447a-aac9-35529c5b357d)

This request is similar to #1744, but for busses.

[Front](https://app.frontapp.com/open/cnv_1bn8ui3g?key=D9gOcKVmOnJwpfjOoko_hM_8n4pC1QQd) | [Playground](https://serpapi.com/playground?q=bus+schedule+portland+to+seattle&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&newPara=chips+highlight+stick+lr+as_qdr+as_qdr%25255C+as_qdr%255C+as_qdr%2525255C+as_qdr%5C) | [Google Search](https://www.google.com/search?q=bus+schedule+portland+to+seattle&sca_esv=891eb93c4edd4a1c&sca_upv=1&ei=ODiIZtOOApmnuvQP4cG8-AY&ved=0ahUKEwjTitTewJCHAxWZk44IHeEgD28Q4dUDCA8&uact=5&oq=bus+schedule+portland+to+seattle&gs_lp=Egxnd3Mtd2l6LXNlcnAiIGJ1cyBzY2hlZHVsZSBwb3J0bGFuZCB0byBzZWF0dGxlMgoQABiwAxjWBBhHMgoQABiwAxjWBBhHMgoQABiwAxjWBBhHMgoQABiwAxjWBBhHMgoQABiwAxjWBBhHMgoQABiwAxjWBBhHMgoQABiwAxjWBBhHMgoQABiwAxjWBBhHSLkFUABYAHABeAGQAQCYAQCgAQCqAQC4AQPIAQCYAgGgAgWYAwCIBgGQBgiSBwExoAcA&sclient=gws-wiz-serp)

**Comment by Ovi** [comment]
<img width="1720" alt="image" src="https://github.com/user-attachments/assets/3cd3fd03-751b-4d85-a330-5cab140e127c">
