### ISSUE TITLE
[Walmart Product API] Scrape Price from Variant Swatches 

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1751]
Some variant swatches in Walmart Product pages include a price. We're not currently parsing that information. It also doesn't appear in our raw HTML, so it may be related to the specific endpoint we are using.

A current customer (and potential Enterprise Customer) requested that we scrape this information.

<img width="1412" alt="Screenshot 2024-07-05 at 1 12 18 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/d1865ef2-b7e3-4d63-8726-4718b3655114">

[Playground](https://serpapi.com/playground?engine=walmart_product&product_id=2KJKP58OOESO) |[ Inspector](https://serpapi.com/searches/66884f52c90e0a86daa9f469/inspect) | [Front](https://app.frontapp.com/inboxes/teams/folders/22722140/open/103716819676)

**Comment by andypple83** [comment]
We've released the fix. The prices should be available for all variant swatches.

![Screenshot 2024-08-07 at 20 36 02](https://github.com/user-attachments/assets/2b58bc4c-2e23-4274-805c-c7961dc07655)
