### ISSUE TITLE
[Walmart Search API] Parse "Free Shipping" When Available

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1757]
Walmart search results sometimes include a "free shipping" field. A customer requested that we parse this.

<img width="1407" alt="Screenshot 2024-07-08 at 11 39 43 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/83491173-4ce8-4edd-8fba-162f6445617a">

<br>. 

[Front](https://app.frontapp.com/open/msg_2ewq87x8?key=BDHzIKFfke2tQFEWaB0pIk5AyHRLdcHd) | [Playground](https://serpapi.com/playground?engine=walmart&query=kids+acoustic+guitar) | [Walmart ](https://www.walmart.com/search?q=kids%20acoustic%20guitar)

**Comment by btaunt** [comment]
This feature has been updated. We now parse both `free_shipping`, `free_shipping_with_walmart_plus` and `shipping_price` if applicable.

```
"free_shipping": true || false,
"free_shipping_with_walmart_plus": true || false,
"shipping_price": 9.98,
```

[Playground](https://serpapi.com/playground?engine=walmart&query=kids+acoustic+guitar) | [Updated Docs](https://serpapi.com/walmart-organic-results)
