### ISSUE TITLE
[Google Local API] Missing `extensions` and `links`

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1759]
According to our Google Local Results API documentation, we should be returning `extensions` and `links`, but these aren't being scraped and returned. Is this a gap on our side or did Google make these unavailable?

[Playground](https://serpapi.com/playground?engine=google_local&q=pubs+in+new+york+ny)

![image](https://github.com/serpapi/public-roadmap/assets/9811728/c0bcf63a-9b70-4abc-8966-d06d53543816)

[Google Local Result Docs](https://serpapi.com/local-results)

![image](https://github.com/serpapi/public-roadmap/assets/9811728/82fee00b-3266-4a94-b704-29953c3f8374)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068413?view=List)

**Comment by aciddjus** [comment]
That search does not contain links or extensions for us to extract. The only information missing is the `price` ([open issues](https://github.com/serpapi/public-roadmap/issues/1714)).

Example search with links: [Playground](https://serpapi.com/playground?engine=google_local&q=mcdonalds)

I couldn't find a search where an HTML contains what we define as an extension.

**Comment by alexbarron** [comment]
Thanks @aciddjus. That's very helpful. So long story short, this is expected behavior.

Also, I proposed to the customer that they use the Google Maps API which returns the `website` field which they confirmed solves their issue anyway.

 I'll go ahead and close this in that case.

**Comment by alexbarron** [comment]
> @alexbarron Yes, this is expected behavior.
> 
> PS: Make sure to close these types of issues as "Close as not planned"

Good catch. I hit the "Close with comment" button and it defaulted to that. I'll look out for that next time.
