### ISSUE TITLE
[Google Search API] Map Pack Shows up and Disappears

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#176]
Map pack initially shows up in the results page and then disappears with an "Oops! Something went wrong." error.

[The Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true) | [The Inspect](https://serpapi.com/searches/62ac3525f716ee1f8e783e8c/inspect)

https://user-images.githubusercontent.com/64849049/174255144-7e607a0a-cbd7-4af1-92f5-1574783d0f73.mp4

User submission:

https://www.loom.com/share/4189c1a2920f4eea89336b197d7e2821

User notes: **_it should be in the results as it is a key part of many of our clients ranking strategies_**

**Comment by kagermanov27** [comment]
Just sharing insights:
This problem is not reproducible in development environment.
The actual js error that causes the problem is below:
![actual_error](https://user-images.githubusercontent.com/73674035/174587473-364b2735-a902-4f86-93e9-5c5077a66c11.png)

**Comment by ilyazub** [comment]
@kagermanov27 Thank you for investigation :+1: 

When a request to `maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate?` is blocked, error isn't shown:

![image](https://user-images.githubusercontent.com/282605/174646356-e3dc86cd-d753-4ada-8f1a-2f1b104296c6.png)


Request that fails:

```
$ curl 'https://maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate?1shttps%3A%2F%2Fserpapi.com%2Fsearches%2F2102535987165381%2F62ac3525f716ee1f8e783e8c.xray&2sgoogle-maps-lite&7m1&1e11&callback=_xdc_._d37xjc&client=google-maps-lite&token=116171' \
  -H 'authority: maps.googleapis.com' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'referer: https://serpapi.com/' \
  -H 'sec-fetch-dest: script' \
  -H 'sec-fetch-mode: no-cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36' \
  --compressed
/**/_xdc_._d37xjc && _xdc_._d37xjc( [0,0,0,null,null,[3,null,"Google Maps JavaScript API error: UnauthorizedURLForClientIdMapError\nhttps://developers.google.com/maps/documentation/javascript/error-messages#unauthorized-url-for-client-id-map-error"]] )
```

Parameters differ on the correct request:

```
$ curl 'https://maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate?1shttps%3A%2F%2Fwww.google.com%2Fsearch&2sgoogle-maps-lite&7m1&1e0&callback=_xdc_._qkfqxx&client=google-maps-lite&token=54716' \
  -H 'authority: maps.googleapis.com' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'referer: https://www.google.com/' \
  -H 'sec-fetch-dest: script' \
  -H 'sec-fetch-mode: no-cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'sec-gpc: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36' \
  --compressed
/**/_xdc_._qkfqxx && _xdc_._qkfqxx( [1,null,0,null,null,[1]] )
```

**Comment by kagermanov27** [comment]
@ilyazub , is there a way we can recreate it like it is happening on production or should we make a riskless fix with html manipulation?

**Comment by hartator** [comment]
The correct map flashes before the error:

https://user-images.githubusercontent.com/307597/174682204-f2f84fcc-6537-4715-a34d-aaffa01e7028.mov

Maybe there is a way to just block the JS code that display the error. You can't interact with the map anyway.
