### ISSUE TITLE
[Google Search API] Missing `sports_results` for football/soccer

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1763]
We're currently not scraping recent football/soccer results from Google. According to our [documentation](https://serpapi.com/sports-results#api-examples-team-sports-results-soccer-american-football-basketball-hockey-baseball-cricket), we should be scraping these.

[Playground](https://serpapi.com/playground?q=lafc+results&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)

![image](https://github.com/serpapi/public-roadmap/assets/9811728/5b14bcfa-6bfc-4a12-bd1c-ed1d28fcbf6c)

I tried baseball and Google returned a different layout that we do scrape.

[Playground](https://serpapi.com/playground?q=sf+giants+results&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)

![image](https://github.com/serpapi/public-roadmap/assets/9811728/8e40bcf8-4921-4813-ab94-1b04636c7d1b)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068461?view=List)

**Comment by ocvit** [comment]
Found another variation: [Inspect](https://serpapi.com/searches/66914498f55d77d9da297315/inspect)

This issue should be re-opened for now.

**Comment by ocvit** [comment]
Fix has been released.

Recent football games are described in `sports_results` as intended.

<img width="1438" alt="Screenshot 2024-07-17 at 11 32 08" src="https://github.com/user-attachments/assets/3d7f186b-ae81-46f6-b438-c771cf6b4652">
