### ISSUE TITLE
[Google Shopping API] High error rate

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#1766]
A customer reached out, letting us know they are seeing requests take anywhere from 15-40 seconds. I am currently seeing high error rates for the Google Shopping API (>60%).

![Screenshot 2024-07-11 at 12 18 52 PM](https://github.com/user-attachments/assets/129eb0bd-8696-4943-a0c7-30df699b38c7)

[Playground Example](https://serpapi.com/playground?engine=google_shopping&q=furniture&gl=us&hl=en&device=desktop&no_cache=true) | [Search Inspect](https://serpapi.com/searches/669025b396f5d7372871209f/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068497?view=List)

**Comment by kevincheungs** [comment]
Just as an update, all our calls are now getting a 503 error response after about 90 seconds.

http://serpapi.com/search?tbm=shop&engine=google&api_key={key}&q=bamboo fountain

{
    "search_metadata": {
        "id": "66903539f05eb89606d18148",
        "status": "Error",
        "json_endpoint": "https://serpapi.com/searches/3a4e2de58ad0b0d2/66903539f05eb89606d18148.json",
        "created_at": "2024-07-11 19:40:41 UTC",
        "processed_at": "2024-07-11 19:40:41 UTC",
        "google_shopping_url": "https://www.google.com/search?tbm=shop&q=%26%2398%3B%26%2397%3B%26%23109%3B%26%2398%3B%26%23111%3B%26%23111%3B%26%2332%3B%26%23102%3B%26%23111%3B%26%23117%3B%26%23110%3B%26%23116%3B%26%2397%3B%26%23105%3B%26%23110%3B&hl=en&gl=us",
        "total_time_taken": 90.05
    },
    "search_parameters": {
        "engine": "google_shopping",
        "q": "bamboo fountain",
        "google_domain": "google.com",
        "hl": "en",
        "gl": "us",
        "device": "desktop"
    },
    "error": "We couldn't get valid results for this search. Please try again later."
}

**Comment by kagermanov27** [comment]
Re-ponening until confirming that the problem has been resolved.

**Comment by InfiniteCodeMonkeys** [comment]
It's fast failing now and not returning any results.

**Comment by anukamanghwani** [comment]
Having the same problem.

**Comment by schaferyan** [comment]
Another customer reached out about this:

[Front](https://app.frontapp.com/open/msg_2f3nd5y4?key=LM0uCAXQ7qH0Vo-QCjEF4jZRAT9nDOWa)

**Comment by schaferyan** [comment]
A high volume customer reported this as well:

[Front](https://app.frontapp.com/open/msg_2f3iyyak?key=6SxDBH1GezwBdAGAs6bIB7fnSBIHVvR3)

**Comment by NateSkiles** [comment]
Due to a layout change on the Google Shopping page, the Google Shopping API is regularly returning empty results for searches using the `gl=us` search parameter.

We have opened a separate issue for this, which can be found here: https://github.com/serpapi/public-roadmap/issues/1767

**Comment by aciddjus** [comment]
We have fixed this issue.

![image](https://github.com/user-attachments/assets/227025a0-eb98-4d7d-9fa5-313cf2547fd8)


[API status](https://serpapi.com/status/google_shopping)

----------



Resolved in: https://github.com/serpapi/SerpApi/pull/5040 and https://github.com/serpapi/SerpApi/pull/5047
