### ISSUE TITLE
[Google Shopping API] API returning empty results

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#1767]
Due to a layout change on the Google Shopping page, the Google Shopping API is regularly returning empty results for searches using `gl=us`.

![Screenshot 2024-07-11 at 1 58 11 PM](https://github.com/user-attachments/assets/72fee0e7-84e5-411b-86b5-cdb880832108)

Testing with other country parameters seems to be unaffected at this time:

![Screenshot 2024-07-11 at 1 59 23 PM](https://github.com/user-attachments/assets/ee392b1e-cf92-47c9-aa45-405b24e3ab7f)

[Playground](https://serpapi.com/playground?engine=google_shopping&q=furniture&gl=us&hl=en&device=desktop&no_cache=true) | [Insepct](https://serpapi.com/searches/669042e0fdca3ec6dafe4c38/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068497?view=List)

**Comment by JustZakary** [comment]
https://blog.google/products/shopping/google-tools-summer-sales-2024/

It appears Google announced these updates a couple weeks ago and is now phasing them into production.

**Comment by chrisrosner** [comment]
Is this something that customers can or should mitigate themselves?

**Comment by chrisrosner** [comment]
> https://blog.google/products/shopping/google-tools-summer-sales-2024/
> 
> It appears Google announced these updates a couple weeks ago and is now phasing them into production.

@JustZakary I didn't see any mention of the 'gl' parameter in that release, am I missing it?

**Comment by schaferyan** [comment]
> Is this something that customers can or should mitigate themselves?

We are working to develop a fix for this. In the meantime, customers may be able to avoid this issue by using a `gl` parameter other than `us`.

> @JustZakary I didn't see any mention of the 'gl' parameter in that release, am I missing it?

The issue most likely not about the `gl` parameter directly. My guess is that these updates have only ben released in the US so far. Indicating a county other than US using the `gl` parameter may help to avoid the new layout and therefore avoid the errors.

**Comment by NateSkiles** [comment]
Another user reached out regarding this issue:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068508?view=List)

**Comment by hilmanski** [comment]
Another customer reached out to us.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068509?view=List)

**Comment by hilmanski** [comment]
Another customer reached out regarding this issue.

[Front](https://app.frontapp.com/open/msg_2f47pj18?key=BualytGoWnGmJNZ3ocdSYUvgduKMvleR)

**Comment by marm123** [comment]
Another user reported it:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068516?view=List)

**Comment by marm123** [comment]
Two more users reached out about this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068519?view=List) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068487?view=List)

**Comment by martin-serpapi** [comment]
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068530?view=List)

**Comment by aciddjus** [comment]
Thank you, everyone, for your patience and understanding. We apologize for the inconvenience and are working as fast as possible to update our parsers to support the new `gl=us` layout.

In the meantime, we have released a patch that will return an alternative mobile layout when the `gl=us` parameter is used.

<img width="1645" alt="image" src="https://github.com/user-attachments/assets/41185fd7-6a31-40d0-af72-d7fdb6e0cef4">

----------

[Playground](https://serpapi.com/playground?engine=google_shopping&q=furniture&gl=us&hl=en&device=desktop&no_cache=true)

**Comment by i8ramin** [comment]
Thank you for the quick patch. It looks like these are mobile results, and so the image thumbnails are coming back very very small (ie, https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTt88PN2g55XA97H1tRDx8PaRzIUq-Rgn0xJJv8y4l8jwRFWN_b_vOmj6LtIaHe0XsHu5wnYom_HenTl-B4UsbFoJO8fBdHrot_ltwuzw&usqp=CAE) ... do anyone know if there is a way to modify the thumbnails to get the larger size?

**Comment by alexbarron** [comment]
Thanks for the patch. We're seeing some queries return `shopping_results` where some results include the full data set and others are missing things like `product_id`, `rating`, `reviews`, etc.

![image](https://github.com/user-attachments/assets/889353ba-d7a2-4428-b711-f2f1bbb7f9ee)

[Playground](https://serpapi.com/playground?engine=google_shopping&q=cloud+sofa&location=United+States&gl=us&hl=en)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068511?view=List)

**Comment by schaferyan** [comment]
Another customer with this issue:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068541?view=List)

**Comment by jeremytmack** [comment]
Are there any updates or ETA on this situation? We have a platform thats been down and we cannot leverage the mobile solution you currently have in place due to the low-fidelity images.

**Comment by kagermanov27** [comment]
We have deployed a fix for this:

Before:
![image](https://github.com/user-attachments/assets/8f723079-58e9-49e6-b53a-f8ebf37d4d53)


After:
![image](https://github.com/user-attachments/assets/32ef8bd9-36b2-4bcc-a28f-77a37eed0b2a)

We are not closing the issue to see if the solution applies to all the queries. We would be grateful if you let us know.

**Comment by InfiniteCodeMonkeys** [comment]
Working as expected for us, but will keep testing throughout the day.

**Comment by bbwilson** [comment]
My testing shows this is working correctly. Thanks,

**Comment by marm123** [comment]
One of our customers reported a strange issue where no results are returned for some searches, but looking at the page layout, it seems that the issue might potentially be with Google itself? @tanys123 @kagermanov27 do you think these are relevant to this thread or should this be a separate issue or not issue at all on our side?

[Inspect 1](https://serpapi.com/searches/669a1bbefa8675442190bc2c/inspect) | [Inspect 2](https://serpapi.com/searches/669a1bbe5c560665fdd9f9e6/inspect) | [Inspect 3](https://serpapi.com/searches/669a1bbeaef26428246924bf/inspect) | [Inspect 4](https://serpapi.com/searches/669a1bbe9b64729d57058956/inspect) | [Inspect 5](https://serpapi.com/searches/669a1bbe116a5535db8c40a2/inspect) | [Inspect 6](https://serpapi.com/searches/669a1bbe87a0eecefffdde47/inspect)

**Comment by kagermanov27** [comment]
>One of our customers reported a strange issue where no results are returned for some searches, but looking at the page layout, it seems that the issue might potentially be with Google itself? @tanys123 @kagermanov27 do you think these are relevant to this thread or should this be a separate issue or not issue at all on our side?

We have deployed another fix for this. New server errors are now passed in favor of searches with results.
