### ISSUE TITLE
[Google News API] Missing `menu_links` and `sub_menu_links`

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#1769]
We're currently not scrapping the `menu_links` or `sub_menu_links` from the Google News API. I found this while trying to assist a user looking to query the Google News API using a `topic_token`, which can typically be found in the `menu_links` or `sub_menu_links` results (per our [documentation](https://serpapi.com/google-news-api#api-examples-example-with-search-query-q-pizza)). 

[Playground](https://serpapi.com/playground?engine=google_news&q=sports&gl=us&no_cache=true) | [Inspect](https://serpapi.com/searches/66907d680ead41d63e9e4752/inspect)
![Screenshot 2024-07-11 at 5 01 05 PM](https://github.com/user-attachments/assets/2ac80d0a-58d8-4367-a3ad-5456bdbde23e)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068504?view=List)

**Comment by aciddjus** [comment]
We have fixed this issue.

<img width="2058" alt="image" src="https://github.com/user-attachments/assets/e2819d84-f853-4bef-b927-5c3f43dd215e">


-----------------

[Playground](https://serpapi.com/playground?engine=google_news&q=sports&gl=us&no_cache=true)
