### ISSUE TITLE
[Google Play Product API] `reviews` value is incorrect

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1772]
For some searches, the `reviews` value is returned incorrectly. It looks like the issue is with the fact, that some languages use comma as a decimal separator. The results are returned correctly if the period is used as a decimal separator. One of our high-volume customers reported this.

Incorrect `reviews`:
<img width="1670" alt="image" src="https://github.com/user-attachments/assets/0c1f702f-8232-4bf9-82de-3037f9100f55">

Correct `reviews`:
<img width="1669" alt="image" src="https://github.com/user-attachments/assets/eb4573f5-ea3b-4d6b-8588-4ef1eb14b0c9">

[Playground](https://serpapi.com/playground?engine=google_play_product&product_id=com.einnovation.temu&hl=no&store=apps&platform=phone&sort_by=1) | [Inspect](https://serpapi.com/searches/6694ce10dc02f13b8b8ee57a/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068609?view=List)

**Comment by NateSkiles** [comment]
While looking into another customer, I found the number of reviews returned is incorrect for most languages(that I tested) that aren't English.

Searching 'Facebook' without an `hl` parameter returns `149000000` reviews:

![image](https://github.com/user-attachments/assets/c3f90940-f31f-4331-a6dd-ae5d74711c10)

Playground example:
https://serpapi.com/playground?engine=google_play&q=facebook&gl=us

However, searching with Spanish (`hl=es`), we get `149` reviews:

![image](https://github.com/user-attachments/assets/7bd5c7bd-f3ab-4de6-a6dc-c7c8b693631b)

Playground example:
https://serpapi.com/playground?engine=google_play&q=facebook&gl=us&hl=es

I tested with a few other languages (besides English) and found they all returned `149`.

[Playground `hl=ar`](https://serpapi.com/playground?engine=google_play&q=facebook&gl=us&hl=ar)
[Playground `hl=it`](https://serpapi.com/playground?engine=google_play&q=facebook&gl=us&hl=it)
[Playground `hl=pl`](https://serpapi.com/playground?engine=google_play&q=facebook&gl=us&hl=pl)

Unsure if this would be a separate issue, I'm happy to open a new one if needed.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069051?view=List)

**Comment by marm123** [comment]
Our high-volume customer who reported the issue followed up to inquire about this, as this is a crucial issue for their business. Changing the status to prioritized because of that.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069540?view=List)

**Comment by kagermanov27** [comment]
We have integrated a general solution for this problem and problems alike in other engines.

Before:

![image](https://github.com/user-attachments/assets/95a26519-fcf2-4504-9878-0da36e1be432)

After:

![image](https://github.com/user-attachments/assets/0ef7b3c8-b4b5-4876-b2bc-1ba12db18f8d)
