### ISSUE TITLE
[Google Maps Reviews API] Missing `user` object for reviews

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1774]
A customer reported that we're not scraping reviews user data and returning it in the `user` object.

![image](https://github.com/user-attachments/assets/4600bf28-8bdd-4f9e-8333-1efdd1ccb6a4)

[Playground](https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x89c259af336b3341%3A0xa4969e07ce3108de&hl=en)

Expected `user` object:

![image](https://github.com/user-attachments/assets/1be6bb16-2bc3-4059-a5b6-3f52f59f3164)

[Documentation](https://serpapi.com/google-maps-reviews-api)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068642?view=List)

**Comment by alexbarron** [comment]
One more report

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068646?view=List)

**Comment by marm123** [comment]
Two more users reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068656?view=List) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068657?view=List)

Changing to queued

**Comment by marm123** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068660?view=List)

Changing to prioritized due to how many users reported it.

**Comment by NateSkiles** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068670?view=List)

**Comment by schaferyan** [comment]
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068609?view=List)

**Comment by Freaky** [comment]
A fix for this has been deployed and the `user` object should now be fully populated:

![1774-fix](https://github.com/user-attachments/assets/3c1a167b-681c-4368-ba0a-0726b5d79117)
