### ISSUE TITLE
[Google Search API] Stats `tables` in `sports_results` are incorrectly parsed

### ISSUE THREAD

**Issue by ocvit** [serpapi/public-roadmap#1775]
Stats tables in `sports_results` have incorrectly parsed (duplicated) values. Plus, some columns are missing (yellow/red cards).

<img width="1072" alt="Screenshot 2024-07-16 at 17 22 08" src="https://github.com/user-attachments/assets/4cf8a0e4-6e94-439a-8217-6d6bd63d4c50">

[Playground](https://serpapi.com/playground?q=luis+diaz&gl=uk&hl=en&device=mobile&google_domain=google.com&newPara=chips+highlight+stick+lr+as_qdr+source+votes+site+safe+google_domain+si+form+filter+as_epq+client+ijn+ie+oe+pws+ibp) | [Inspect](https://serpapi.com/searches/669681d51c450a0a6498cc1e/inspect)

**Comment by ocvit** [comment]
Fix has been released.

Stats table is parsed correctly now.

<img width="1443" alt="Screenshot 2024-07-30 at 17 08 06" src="https://github.com/user-attachments/assets/5dc3b4bb-14c1-4cd1-b3af-658f96049923">

**Comment by aciddjus** [comment]
Same comment as in: https://github.com/serpapi/public-roadmap/issues/1745#issuecomment-2217200160 and https://github.com/serpapi/public-roadmap/issues/1631#issuecomment-2255476984
