### ISSUE TITLE
[Google Search API] Missing `sports_results` for football player

### ISSUE THREAD

**Issue by ocvit** [serpapi/public-roadmap#1776]
If there is no stats `tables` player `title`/`team` fields are not populated as well, leaving `sports_results` blank/not present.

<img width="1138" alt="Screenshot 2024-07-16 at 17 34 17" src="https://github.com/user-attachments/assets/432a9085-f41d-444c-8bd5-58c21a2733e3">

[Playground](https://serpapi.com/playground?q=luis+diaz&gl=us&hl=en&device=mobile&google_domain=google.com&newPara=chips+highlight+stick+lr+as_qdr+source+votes+site+safe+google_domain+si+form+filter+as_epq+client+ijn+ie+oe+pws+ibp) | [Inspect](https://serpapi.com/searches/669681bfd036a7fec6a309b5/inspect)

**Comment by ocvit** [comment]
Might be related to: https://github.com/serpapi/public-roadmap/issues/1775

**Comment by ocvit** [comment]
Fix has been released.

Stats table is parsed correctly now.

<img width="1443" alt="Screenshot 2024-07-30 at 17 08 06" src="https://github.com/user-attachments/assets/ffa15d5c-c8c6-485c-99ad-319100963e55">

**Comment by aciddjus** [comment]
Same comment as in: https://github.com/serpapi/public-roadmap/issues/1745#issuecomment-2217200160 and https://github.com/serpapi/public-roadmap/issues/1631#issuecomment-2255476984
