### ISSUE TITLE
[Google Search API] Missing `sports_results` for new `mobile` football game layout

### ISSUE THREAD

**Issue by ocvit** [serpapi/public-roadmap#1778]
As a continuation of https://github.com/serpapi/public-roadmap/issues/1763

Some games have substantially different layout on `mobile`, with additional game stats and key moments redesign.

<img width="2256" alt="new_old_mobile" src="https://github.com/user-attachments/assets/cc6891d7-bb82-4ea0-9cd2-795510403d69">

As a result, `sports_results` are not included.

[Playground](https://serpapi.com/playground?device=mobile&engine=google&gl=us&google_domain=google.com&hl=en&location=Austin%2C+Texas%2C+United+States&q=santos+fc+vs+ituano) | [Inspect](https://serpapi.com/searches/669780854055aad3c25b30b1/inspect)

**Comment by btaunt** [comment]
This has been updated and the new mobile layout is now supported.

- [Playground](https://serpapi.com/playground?device=mobile&engine=google&gl=us&google_domain=google.com&hl=en&location=Austin%2C+Texas%2C+United+States&q=santos+fc+vs+ituano)

<img width="684" alt="Screenshot 2024-07-18 at 3 15 50 PM" src="https://github.com/user-attachments/assets/c10300a2-5ea2-4ef9-9f43-0bdffe078462">
