### ISSUE TITLE
[Google About This Result API] Missing social links and snippet data messy

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1779]
We received a report that we're not scraping the social links included under `about_the_source.in_their_own_words` and `about_the_source.author`. 

The snippet text is also dumping all the text together in a messy way and not separating out the different parts the way Google has formatted it. E.g: `AuthorMalcolm GladwellCanadian journalist and author. MoreMalcolm Timothy Gladwell CM is a Canadian journalist...`

![image](https://github.com/user-attachments/assets/eafa627d-f95d-4eb6-985f-811f05071125)

![image](https://github.com/user-attachments/assets/6412d1d8-87f7-48db-8088-f9d8172ae39d)

[Playground](https://serpapi.com/playground?engine=google_about_this_result&q=About+https%3A%2F%2Fwww.newyorker.com%2Fmagazine%2F2022%2F11%2F07%2Fwas-jack-welch-the-greatest-ceo-of-his-day-or-the-worst)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000066945?view=List)

**Comment by aciddjus** [comment]
We have fixed this issue.

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/b1f72f54-eef6-4bfa-97ff-68962e401e0f">
