### ISSUE TITLE
[Google Maps Photos API] Add image category

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#1781]
A user requested that we add a categories array to the photo object returned by the Google Maps Photos API.

Example:
```json
"photos": [
    {
      "thumbnail": "thumnail_url",
      "image": "image_url",
      "photo_meta_serpapi_link": "photo_meta_serpapi_link",
      "categories": [
        {
          "title": "category_title",
          "id": "category_id"
        }
        ...
      ]
    },
    ...
  ]
```

Currently, we return an array of categories with titles and IDs, but there is no association between individual photos and their respective categories.

While the user can use the `category_id` to return photo results for a given category, this can provide duplicates across multiple categories without specifying which photo belonged to which category.

[Playground](https://serpapi.com/playground?engine=google_maps_photos&data_id=0x89c259af336b3341%3A0xa4969e07ce3108de&hl=en)

![Screenshot 2024-07-17 at 11 35 35 AM](https://github.com/user-attachments/assets/a721bd6e-636f-4c30-8a69-7a887acfa826)

I believe this to be a Google Limitation as I could not find a reference to a photo's categories, only the categories provided for a given `data_id`.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068490?view=List)

**Comment by aciddjus** [comment]
Unfortunately, Google does not provide this information, so we won't be able to support it.
