### ISSUE TITLE
[Google Maps API] `username` is missing from the `most_relevent` results

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1782]
A customer reported we're not scraping the `username` for reviews in `most_relevant` anymore. This could be related to the [recent issue with the Google Maps Reviews API](https://github.com/serpapi/public-roadmap/issues/1647), in which we were not scraping the `name` field for reviews. 

<img width="1421" alt="Screenshot 2024-07-17 at 3 00 54 PM" src="https://github.com/user-attachments/assets/e9ad345b-c2b1-4634-8371-bc30f1ef6e8e">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068715?view=List) | [Playground](https://serpapi.com/playground?engine=google_maps&q=Coffee&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&place_id=ChIJ1X3dvldYwokRyajPtakhQLk&type=search) | [Search Inspector](https://serpapi.com/searches/66983e36e93ff416359fe79e/inspect)

**Comment by aciddjus** [comment]
We have fixed this issue.

![image](https://github.com/user-attachments/assets/361d431d-4c3c-4ebf-8f4f-50c1708c0238)
