### ISSUE TITLE
[Google Maps Reviews API] `place_id` returns broken Google Maps URL

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#1787]
A customer reached out with an issue accessing the `google_maps_url` when querying the Google Maps Reviews API using a `place_id`. The URL returned when passing a `place_id` parameter does not work; however, when a `data_id` parameter, the URL returned does work.

Example Location: [Playground](https://serpapi.com/playground?engine=google_maps&q=Oregon+Zoo&hl=en&type=search)

Using the `place_id` ([Playground](https://serpapi.com/playground?engine=google_maps_reviews&hl=en&place_id=ChIJBbhWuC4KlVQRJvzdnrAg5-c)): `ChIJBbhWuC4KlVQRJvzdnrAg5-c`

The `google_maps_reviews_url` returns: 
- https://www.google.com/maps/place/data=!4m7!3m6!1s!5m2!4m1!1i2!9m1!1b1?hl=en&gl=

![image](https://github.com/user-attachments/assets/e9052680-cfc6-4b03-b5a4-85d6e12656e0)

Using the `data_id` ([Playground](https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x54950a2eb856b805%3A0xe7e720b09eddfc26&hl=en)): `0x54950a2eb856b805:0xe7e720b09eddfc26`

The `google_maps_reviews_url` returns: 
- https://www.google.com/maps/place/data=!4m7!3m6!1s0x54950a2eb856b805:0xe7e720b09eddfc26!5m2!4m1!1i2!9m1!1b1?hl=en&gl=

![image](https://github.com/user-attachments/assets/fac448ef-9700-4691-af77-53912c7485f0)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068789?view=List)

**Comment by zyc9012** [comment]
We've released a fix for this. `google_maps_reviews_url` now returns correct URL.

![image](https://github.com/user-attachments/assets/8e638e64-fcd8-4f56-9137-d2669f8b15ec)
