### ISSUE TITLE
[Google Images API] Include `reviews_original` field

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#1793]
When we parse `9k+` to number, the result will be `9000`

![Screenshot 2024-07-22 at 16 10 54](https://github.com/user-attachments/assets/de8e7d9a-0461-439a-af01-c0bffd85c66e)

[Playground](https://serpapi.com/playground?engine=google_images&q=Coffee&gl=us&hl=en&no_cache=true&newPara=chips) | [Inspect](https://serpapi.com/searches/669e22c166d81f50ee7a4603/inspect)

**Comment by aciddjus** [comment]
The best we can do here is to add another field, `reviews_original`, and extract it as `reviews_original: "9k+"`.
There is no way to know the exact number of reviews just from "9k+" string.

**Comment by btaunt** [comment]
The new field `reviews_originals` is parsed for both Google Images API and instances of Google Search API:

- [Playground (Google Images API)](https://serpapi.com/playground?engine=google_images&q=Coffee&gl=us&hl=en&no_cache=true&newPara=chips)
- [Playground (Google Search API)](https://serpapi.com/playground?q=top+sights+paris&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=chips+highlight+stick+lr+as_qdr+source+votes+site+safe+google_domain+si+form+filter+as_epq+client+ijn+ie+oe+pws+ibp)

---

- [Documentation: Google Images API](https://serpapi.com/google-images-shopping-results)
- [Documentation: Google Search API](https://serpapi.com/inline-shopping#api-examples-results-for-top-sights-paris)
