### ISSUE TITLE
[Bing Shopping API] Scrape Product Link From Bing Results

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#1795]
A customer reached out asking if we can scrape the actual product link from the BING Shopping API.

Bing makes external product links available. See Example: https://www.bing.com/shop?q=Coffee

We don't current scrape the external product links in our Bing Shopping API like we do on Google Shopping API. 

Currently, we only scrape the bing.com product link for the product: 
![Screenshot 2024-07-22 at 11 12 43 AM](https://github.com/user-attachments/assets/4df1d9ac-1399-4661-8227-0860bb35b747)

We don't scrape this:
![Screenshot 2024-07-22 at 11 22 47 AM](https://github.com/user-attachments/assets/e0e2a9db-14a4-44a6-b65a-abf6747aba18)

[Playground](https://serpapi.com/playground?engine=bing_shopping&q=Coffee)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068858?view=List)

**Comment by Ovi** [comment]
We now scrape `external_link` from products

<img width="1728" alt="Untitled" src="https://github.com/user-attachments/assets/33c74f72-d5d1-4f2b-b71d-6115d6a418b2">

[Playground](https://serpapi.com/playground?engine=bing_shopping&q=Coffee)

**Comment by KBCG** [comment]
@Ovi @sonika-serpapi @sonika-serpapi @hartator @paigebutler  -- hello, we are need of this but also for the Advertisement results. We do not have that for in_ads results  
<img width="1492" alt="Screenshot 2024-11-26 at 18 06 35" src="https://github.com/user-attachments/assets/35557d3d-b967-41d0-8de6-042e54cb07c0">

**Comment by NateSkiles** [comment]
@KBCG Thank you for reaching out about this! I've gone ahead and opened a feature request for this here:

#2177
