### ISSUE TITLE
[eBay API] Scrape "shipping to" zip code and allow setting zip

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1797]
eBay detects the location of where a search is coming from and uses it to estimate shipping costs. We currently don't scrape the zip code used to calculate the estimated shipping. We do scrape the shipping cost estimate.

eBay will use the IP of the proxy handling the request to set this information, but it appears including the `_stpos` param allows you to override that and set whatever zip code you want.

`https://www.ebay.com/sch/i.html?_from=R40&_trksid=p2334524.m570.l1313&_nkw=bose+headphones&_sacat=0&_stpos=94404&_osacat=0&_fcid=1`

![image](https://github.com/user-attachments/assets/c59603c7-9be6-4a1f-aae0-11e4e193ea15)

[Playground](https://serpapi.com/playground?engine=ebay&_nkw=bose+headphones)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068849?view=List)

**Comment by aciddjus** [comment]
Yes, we can add the `_stpos` parameter to be able to add the zip code.

**Comment by ocvit** [comment]
Feature has been released.

Now you can set ZIP (postal) code for results filtering.

<img width="1414" alt="Screenshot 2024-07-29 at 12 48 11" src="https://github.com/user-attachments/assets/2341edc8-0578-4372-be50-4fb62154f086">

**Comment by kunanyi** [comment]
This works for US based searches, but what if the Post/Zip code was for a different country?

**Comment by hilmanski** [comment]
Hi @kunanyi, thank you for your question. 
Do you have any sample search ID where it doesn't worm for other countries? Thanks!

**Comment by alexbarron** [comment]
> This works for US based searches, but what if the Post/Zip code was for a different country?

This works for other countries as well. For example:

**UK:** https://serpapi.com/playground?engine=ebay&_nkw=Coffee&ebay_domain=ebay.co.uk&_stpos=cb28dt&_stpos=cb28dt&newPara=_stpos

**Italy:** https://serpapi.com/playground?engine=ebay&_nkw=espresso&ebay_domain=ebay.it&_stpos=40125&_stpos=40125&newPara=_stpos

**Australia:** https://serpapi.com/playground?engine=ebay&_nkw=coffee&ebay_domain=ebay.com.au&_stpos=2055&_stpos=2055&newPara=_stpos

As my colleague Hilman asked, please let us know if you have any sample queries for countries that don't work.
