### ISSUE TITLE
[Google Search API] Missing phone result in local pack results

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#1800]
We're missing `phone` result in local pack results.

![Screenshot 2024-07-24 at 17 33 52](https://github.com/user-attachments/assets/6d4512d3-1fa1-4fa0-bb5f-695979ebef99)

[Playground](https://serpapi.com/playground?q=Diagnostic+Labs&location=Wesley+Chapel%2C+Florida%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=source+votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ijn+ie+oe+pws+ibp) | [Inspect](https://serpapi.com/searches/66a0d845edb034474b666d44/inspect)

**Comment by aciddjus** [comment]
Thank you, @Ovi 👍

Make sure to fallow steps 12. and 13. from [our wiki](https://github.com/serpapi/SerpApi?tab=readme-ov-file#contributing-and-deploying).

**Comment by Ovi** [comment]
We're now parsing `phone` result in local pack results.

<img width="1728" alt="Screenshot 2024-07-30 at 5 21 17 PM" src="https://github.com/user-attachments/assets/2ad259ae-eeeb-42e9-a82a-e9906c21bde8">

[Playground](https://serpapi.com/playground?q=Diagnostic+Labs&location=Wesley+Chapel%2C+Florida%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=source+votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ijn+ie+oe+pws+ibp)
