### ISSUE TITLE
[DuckDuckGo Search API] `safe` parameter does not work

### ISSUE THREAD

**Issue by mohamedScikitLearn** [serpapi/public-roadmap#1805]
I want to integrate Duckduckgosearch, but it seems that the safe

`"search_parameters":
{
"engine":
"duckduckgo",
"q":
"adultmovies xxx ",
"kl":
"us-en",
"safe":
"1"
},`

**Comment by Freaky** [comment]
It does look like this engine is fixed on Moderate safe search mode.  It appears the parameter has been replaced by DuckDuckGo - inspecting a search from a browser picks up these differences between the modes:

- Strict: `p=1&exlsexp=b&litexp=c`
- Moderate: `ex=-1&exlsexp=b&litexp=b&videxp=a`
- Off: `ex=-2&exlsexp=a&litexp=a`

**Comment by mohamedScikitLearn** [comment]
Making `safe` with `p=1&exlsexp=b&litexp=c` does not work on serpapi either.

**Comment by Krugloff** [comment]
It's working now.

<img width="1449" alt="image" src="https://github.com/user-attachments/assets/79555195-ec69-44e2-b93f-69e6cc2df70b">

**Comment by sonika-serpapi** [comment]
@mohamedScikitLearn Tagging you for visibility. Our engineers have implemented a fix. Please feel free to reach out for any questions or concerns.
