### ISSUE TITLE
[Ebay Search API] Support filtering the results by `Buying Format`

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1806]
A user requested that we support filtering the results from the Ebay Search API by `Buying Format`:

<img width="1358" alt="image" src="https://github.com/user-attachments/assets/5ac39182-b64f-40f7-9ce2-afd3efc60dec">

[Playground](https://serpapi.com/playground?engine=ebay&_nkw=Coffee) | [Inspect](https://serpapi.com/searches/66a735580b506295cfc09f8a/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069021?view=List)

**Comment by btaunt** [comment]
This feature has been added. eBay queries can now be filtered via `buying_format`:

<img width="349" alt="Screenshot 2024-08-21 at 12 21 26 PM" src="https://github.com/user-attachments/assets/8e2e5f08-832d-4ac9-abcb-b48b3be83b40">

---

Example of search set with "Auction" `buying_format`: [Playground](https://serpapi.com/playground?engine=ebay&_nkw=Coffee&buying_format=Auction)
