### ISSUE TITLE
[Google Flights API] Wrong price returned in the response

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1807]
A high-volume customer reported that our Google Flights API returns incorrect price for some flights in the response. I was able to reproduce it.

<img width="1351" alt="image" src="https://github.com/user-attachments/assets/19fc0ae7-77a2-4c1a-a7f0-d39a2eaa5db6">

[Playground](https://serpapi.com/playground?engine=google_flights&departure_id=BKK&arrival_id=HKT&gl=us&hl=en&currency=USD&type=2&outbound_date=2024-07-30&travel_class=1&show_hidden=true&adults=1&children=0&infants_in_seat=0&infants_on_lap=0&stops=3&no_cache=true) | [Inspect](https://serpapi.com/searches/66a76c48fe41d06d7d1c7db9/inspect)

The actual Google Flights engine returns a different price for flight `TG 217`:

<img width="1306" alt="image" src="https://github.com/user-attachments/assets/e5f35b34-b306-468b-ab36-7293ff9487a0">

[Google Flights](https://www.google.com/travel/flights?hl=en&gl=us&curr=USD&q=Flights+to+HKT+from+BKK+on+2024-07-30+one-way)

Below is another example with flight `TG 289`:

![image](https://github.com/user-attachments/assets/9649200c-e3b2-4b77-bb49-ad7e0dbf8cc9)

[Playground](https://serpapi.com/playground?engine=google_flights&departure_id=BKK&arrival_id=HKT&gl=us&hl=en&currency=USD&type=2&outbound_date=2024-07-30&travel_class=1&show_hidden=true&adults=1&children=0&infants_in_seat=0&infants_on_lap=0&stops=3&no_cache=true) | [Inspect](https://serpapi.com/searches/66a76c48fe41d06d7d1c7db9/inspect)

<img width="1342" alt="image" src="https://github.com/user-attachments/assets/81920565-0004-4a2e-bdd1-b8864d0bc2f1">

[Google Flights](https://www.google.com/travel/flights?hl=en&gl=us&curr=USD&q=Flights+to+HKT+from+BKK+on+2024-07-30+one-way)

Both our Playground and Google Flights requests were executed at the same time.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069035?view=List)

**Comment by zyc9012** [comment]
We've release a fix for this. Now the prices are the same.

SerpApi result:

![image](https://github.com/user-attachments/assets/44a96778-a889-4bc2-8a21-ae1af64e819a)


Google page:

![image](https://github.com/user-attachments/assets/bbd1ef24-0f2e-4c82-8e2c-04309b1e11ba)

**Comment by robert-baldwin** [comment]
I noticed a difference in price and the number of flight results today. Following the link from the SerpApi result also showed different prices.

Google Flights:
<img width="1893" height="987" alt="Image" src="https://github.com/user-attachments/assets/7ab1ebe6-7545-4205-9985-b6996dc4b862" />

SerpApi Playground:
<img width="1893" height="987" alt="Image" src="https://github.com/user-attachments/assets/3a16d910-dfa6-48f1-8a51-a484944753d2" />

**Comment by marm123** [comment]
I just noticed the issue was resolved in a different thread! In any case, feel free to reach out with any questions or concerns.
