### ISSUE TITLE
[Yandex Knowledge Graph API] Missing `knowledge_graph`

### ISSUE THREAD

**Issue by Ovi** [serpapi/public-roadmap#1808]
**Related to #690**

An issue was reported that we are not seeing the Knowledge Graph in Yandex search results. It appears when we omit the `lr` parameter, we can see the Knowledge Graph in the HTML, but it is not parsed in the JSON.

To address this, we can:
- Add an "Unspecified" value in the "Geographic Location" (`lr`) dropdown.
- Update our parser to accommodate the new Knowledge Graph layout.

<img width="1728" alt="Screenshot 2024-07-30 at 3 37 09 PM" src="https://github.com/user-attachments/assets/f58b5821-9992-4050-bc9a-53089ba12acc">

Playground link with `lr=null` is not possible as it was done using code, however, we can use any arbitrary number which is not a valid `lr` value to reproduce this: [Playground](https://serpapi.com/playground?engine=yandex&text=How+i+met+your+mother&yandex_domain=yandex.com&lang=en&lr=1000000&no_cache=true) | [Inspect](https://serpapi.com/searches/66a8c6f5033e94f82ab5c4c2/inspect)

**Comment by Krugloff** [comment]
https://serpapi.com/playground?engine=yandex&text=%D0%A0%D0%B8%D1%87%D0%B0%D1%80%D0%B4+%D0%A4%D0%B5%D0%B9%D0%BD%D0%BC%D0%B0%D0%BD+%D0%B4%D0%B0%D1%82%D0%B0+%D1%80%D0%BE%D0%B6%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F&yandex_domain=yandex.com&lang=en&lr=1&no_cache=true

Here’s another example: In my experience, Yandex tends to generate knowledge graphs primarily for queries in Russian.

**Comment by Krugloff** [comment]
@aciddjus @Ovi Should we add an "Unspecified" option to the "Geographic Location" (`lr`) dropdown for reasons beyond just the knowledge graph? I’m planning to scrape the new knowledge graph in conjunction with issue #690, which is currently marked as `queued`. I can separate this issue into two if you'd prefer.

**Comment by Krugloff** [comment]
<img width="1449" alt="image" src="https://github.com/user-attachments/assets/70121ae7-e113-42d5-938f-48eb42df75a1" />

It's done.
