### ISSUE TITLE
[Google Jobs API] Provide prettified HTML output for paginated pages

### ISSUE THREAD

**Issue by Freaky** [serpapi/public-roadmap#1809]
Paginated pages on the Google Jobs API are now extracted from a length-delimited data file that includes a mixture of JSON, data URLs, and a HTML fragment, which is currently displayed verbatim in the Playground:

![image](https://github.com/user-attachments/assets/5dfedfc2-789a-45f0-8d6a-fbc60bd613ef)

We should generate a prettified version that simulates a normal web view as we do with other engines.

Ref: https://github.com/serpapi/public-roadmap/issues/1798#issuecomment-2257881197.

**Comment by aciddjus** [comment]
We have fixed this issue and are now returning the prettified version of the HTML when pagination is used.

![image](https://github.com/user-attachments/assets/6bda329e-7397-46a8-bb44-a3ae8e9b0257)
