### ISSUE TITLE
[Google Knowledge Graph API] Scrape merchant review count and rating

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#1815]
A user reached out and requesting the ability to scrape the reviews from the `knowledge_graph` for `"entity_type":
"companies, chains, shopping_merchant",`. Though, I think it might just be tied to `shopping_merchant`.

When searching for a Merchant/Company, if no local results are returned, the Knowledge Graph shows information about the merchant, including a review count and rating.

[Playground](https://serpapi.com/playground?q=madewell&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)
![image](https://github.com/user-attachments/assets/244a031e-8d2a-4f13-b050-ea9059da41c6)

Google Link:
https://www.google.com/search?q=madewell&oq=madewell&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM&hl=en&gl=us&sourceid=chrome&ie=UTF-8

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068996?view=List)

**Comment by ocvit** [comment]
Feature has been released.

Added `rating` and `review_count` for chain stores.

<img width="1538" alt="Screenshot 2024-08-16 at 10 36 44" src="https://github.com/user-attachments/assets/bda2825f-565d-412f-9b8c-6155984fcaac">
