### ISSUE TITLE
[Google Local Services API] Support new categories of Google Local Service query

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#1818]
A user reached out with a request to scrape results for Chiropractor Services on Google Local Services API
![Screenshot 2024-07-30 at 4 38 28 PM](https://github.com/user-attachments/assets/20a6be57-db65-418f-af1d-2529abe3b0ef)

Currently, we support categories listed [here](https://serpapi.com/google-local-services-queries). 

More categories have been added to the dropdown at [https://www.google.com/localservices/prolist?src=1&slp=QAFSBAgCIAA%3D&scp=Ci14Y2F0On...](https://www.google.com/localservices/prolist?src=1&slp=QAFSBAgCIAA%3D&scp=Ci14Y2F0OnNlcnZpY2VfYXJlYV9idXNpbmVzc19jaGlyb3ByYWN0b3I6ZW4tVVMSGBoSCS8DzKCZtUSGEXrVadRLRptdOJnRPhoVQ2hpcm9wcmFjdGljIFNlcnZpY2VzKhVDaGlyb3ByYWN0aWMgU2VydmljZXM%3D&q=Chiropractic%20Services&ved=0CBEQ2MAHahcKEwj47ZHO9s-HAxUAAAAAHQAAAAAQAg)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069081?view=List)

**Comment by sonika-serpapi** [comment]
Another customer requested this
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069894?view=List)

**Comment by sonika-serpapi** [comment]
Another customer reached out about the "Painting" category

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070628?view=List)

**Comment by hilmanski** [comment]
Each county probably has a different list.

![CleanShot 2024-09-26 at 11 05 08](https://github.com/user-attachments/assets/5b0d2e66-b19f-4edc-a7cd-a1ddd4783368)

https://support.google.com/localservices/answer/6224841?hl=en&co=GENIE.CountryCode%3DUS&sjid=11145714287521506857-AP

**Comment by hilmanski** [comment]
We've added the additional list to Google Local services: https://serpapi.com/google-local-services-queries

Example:
- [Chiropractor](https://serpapi.com/playground?engine=google_local_services&q=chiropractor&data_cid=6745062158417646970&hl=en)
- [Painting](https://serpapi.com/playground?engine=google_local_services&q=painter&data_cid=6745062158417646970&hl=en)
