### ISSUE TITLE
[Google Flights API] Scrape departure and arrival cities

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1819]
A user requested that we scrape the departure and arrival cities:

<img width="1439" alt="image" src="https://github.com/user-attachments/assets/3aa996ba-f0ff-41de-b913-9df7c494db25">

[Playground](https://serpapi.com/playground?engine=google_flights&departure_id=CDG&arrival_id=AUS&gl=us&hl=en&currency=USD&outbound_date=2024-08-01&return_date=2024-08-07) | [Inspect](https://serpapi.com/searches/66aa0bdd9c449d151c417008/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069095?view=List)

**Comment by Ovi** [comment]
We now scrape departure and arrival city/airport details as `airports`

<img width="1728" alt="Screenshot 2024-09-06 at 11 52 00 AM" src="https://github.com/user-attachments/assets/90a006f1-4467-4444-ab8f-a74a3899b098">

[Playground](https://serpapi.com/playground?engine=google_flights&departure_id=CDG&arrival_id=AUS&gl=us&hl=en&currency=USD&outbound_date=2024-10-01&return_date=2024-10-07&no_cache=true) | [Documentation](https://serpapi.com/google-flights-airports)
