### ISSUE TITLE
[Google Trends API] Some searches are failing

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1823]
A user reported that some of their searches are failing. It looks like due to the current performance of our Google Trends API.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069229?view=List) | [Status page](https://serpapi.com/status/google_trends)

**Comment by hilmanski** [comment]
Update: Our engineers found the issue and have implemented a fix (Thank you @tanys123 !). Let's monitor this for an hour before closing the issue.

**Comment by schaferyan** [comment]
Thank you @hilmanski, @tanys123. I'm closing this as it seems to be okay now.

**Comment by schaferyan** [comment]
Reopening as it actually looks like response times / success rates are improved but still not back to normal

**Comment by sonika-serpapi** [comment]
This customer reported issues: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069260?view=List)

**Comment by schaferyan** [comment]
Another user reported slow response times and failed searches with the Google Trends API:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069285?view=List)

**Comment by schaferyan** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069290?view=List)

**Comment by hilmanski** [comment]
A user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069293?view=List)

**Comment by hilmanski** [comment]
We currently see this problem re-occurring. We'll investigate and share any updates soon.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069918?view=List)

**Comment by marm123** [comment]
This has been reported by one of our users today.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070132?view=List)

Looks like the API is pretty much down at the moment:
<img width="1298" alt="image" src="https://github.com/user-attachments/assets/787e54c2-3473-433c-9862-b7c21323513b">

**Comment by alexbarron** [comment]
Another report:

[Front](https://app.frontapp.com/open/cnv_1cxhtuho?key=YpqtD-j-GAynpQLfhxjlu_lWtNxokrJJ)

**Comment by tanys123** [comment]
We apologized for the issue. The fix has been deployed, it should now back to normal.

<img width="1132" alt="Screenshot 2024-09-09 at 8 02 53 PM" src="https://github.com/user-attachments/assets/dd443ea5-ce3b-403a-a187-464b5cbd8e62">
