### ISSUE TITLE
[Google Search API] `inline_images` is missing for some searches

### ISSUE THREAD

**Issue by zyc9012** [serpapi/public-roadmap#1824]
![image](https://github.com/user-attachments/assets/2cf863a2-c9bf-427a-8743-2d2c8140d77a)

[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=source+votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ijn+ie+oe+pws+ibp)
[Inspect](https://serpapi.com/searches/66b1c8cbea1442e8a740049f/inspect)

**Comment by Alaa-abdulridha** [comment]
This issue now has been resolved.

Before resolving the issue (Production):
![image](https://github.com/user-attachments/assets/18ccee3e-dd58-463b-9e51-b3eaf57a08f3)


After resolving the issue (Production):

![image](https://github.com/user-attachments/assets/34784f1f-533d-4d03-9e5a-247697c4b55f)

![image](https://github.com/user-attachments/assets/b4d1efe4-a9b5-4eab-b623-78e83c1b192d)
