### ISSUE TITLE
[Google Jobs API] Provide `detected_extensions` in consistent order

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1825]
A user requested that we provide the items in the `detected_extensions` object in consistent order. Currently, the order is different between jobs:

<img width="1373" alt="image" src="https://github.com/user-attachments/assets/ae99f342-c2bc-4495-ae93-d8d36cc5d49f">
<img width="1430" alt="image" src="https://github.com/user-attachments/assets/d69e9a99-303a-4d15-b270-d16769aa8fdf">

[Playground](https://serpapi.com/playground?engine=google_jobs&q=software+engineer) | [Inspect](https://serpapi.com/searches/66b1df49a74fe0a653be03ae/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069219?view=List)

**Comment by andypple83** [comment]
We've released the fix. The `detected_exteionsions` should be in consistent order.

![Screenshot 2024-09-10 at 15 49 53](https://github.com/user-attachments/assets/63a0167e-9fb5-4e27-9b43-d3d969e8a4f1)
