### ISSUE TITLE
[Google Trends API] Google trending now page had changed

### ISSUE THREAD

**Issue by Ganfeng0668** [serpapi/public-roadmap#1828]
![Snipaste_2024-08-07_09-47-32](https://github.com/user-attachments/assets/ac0c902d-2348-4a45-9ee2-a856809593fe)
Will you develop a new API to accommodate the new data?

**Comment by tanys123** [comment]
Hi @Ganfeng0668, thanks for reporting the issue 👍 . We will look into this new changes. If there is any update, we will update it here.

**Comment by githubfan21** [comment]
please make sure that this new way doesn't disable what's working now. I believe Google will slowly block other ways of getting trends so it is important to be able to crawl this

**Comment by martin-serpapi** [comment]
Thank you for the feedback, @githubfan21 .

**Comment by martin-serpapi** [comment]
Another user requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070231?view=List)

**Comment by alexbarron** [comment]
Another request:

[Intercom](https://app.frontapp.com/open/cnv_1ddo0s64?key=ygXK59vuwaspBZiavWyZQJK6yAxPGG_Y)

**Comment by tanys123** [comment]
We have made an update to Google Trends Trending Now API. It's now parsing the latest layout from Google ([Documentation](https://serpapi.com/google-trends-trending-now)). It is backward compatible, meaning your existing code that request `daily/realtime` would still work.

<img width="1395" alt="Screenshot 2024-10-14 at 8 33 08 AM" src="https://github.com/user-attachments/assets/4a4ada9c-a6ac-4572-b698-0702d1a02aad">

**Comment by alexbarron** [comment]
Thank you @tanys123!

@Ganfeng0668, tagging you just to ensure you see this update. Please let us know if we can help with anything else.

**Comment by githubfan21** [comment]
@tanys123 why i don't see the same crenshot you have
this is what I see
![image](https://github.com/user-attachments/assets/521e0e94-91ae-41fd-81f9-6aa3a6c89064)

**Comment by githubfan21** [comment]
can you please include the value `"status":active` if active label appear on the trend
![image](https://github.com/user-attachments/assets/467adb4e-633d-4431-a00e-36b1f2e2b47a)
![image](https://github.com/user-attachments/assets/b0109015-3220-4eb3-a593-f7c6774e5aad)
