### ISSUE TITLE
[Google Flights API] Booking token is missing

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1832]
It looks like the booking_token is missing from the response.

[Playground](https://serpapi.com/playground?engine=google_flights&departure_id=CGK&arrival_id=AUS&gl=us&hl=en&currency=USD&outbound_date=2024-08-13&return_date=2024-08-19) | [Inspect](https://serpapi.com/searches/66b95e812bab900b25267c02/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069391?view=List)

**Comment by marm123** [comment]
For round trips, the `booking_token` is only available after you select and search for the departure flight with the `departure_token`. For example, this is the initial call, including `departure_token`:

[Initial call](https://serpapi.com/playground?engine=google_flights&departure_id=CGK&arrival_id=AUS&gl=us&hl=en&currency=USD&outbound_date=2024-08-13&return_date=2024-08-19)
<img width="1670" alt="image" src="https://github.com/user-attachments/assets/413e5479-9ee9-4e57-8d4d-35dc16f5c4a3">

And then, after you make the 2nd API calls with the `departure_token`, you get the `booking_token`:

[Departure flight:
](https://serpapi.com/playground?engine=google_flights&departure_id=CGK&arrival_id=AUS&gl=us&hl=en&currency=USD&outbound_date=2024-08-13&return_date=2024-08-19&departure_token=WyJDalJJVUdWQmFIUmZia0pTZHpoQmNFSjFkM2RDUnkwdExTMHRMUzB0ZDJWaWMyc3lOMEZCUVVGQlIyRTFjRWhOUm05b2FrTkJFZzlPU0Rnek5ueFZRVFo4VlVFeU9Ua2FDd2lJa3drUUFob0RWVk5FT0J4d2lKTUoiLFtbIkNHSyIsIjIwMjQtMDgtMTMiLCJOUlQiLG51bGwsIk5IIiwiODM2Il0sWyJOUlQiLCIyMDI0LTA4LTEzIiwiSUFIIixudWxsLCJVQSIsIjYiXSxbIklBSCIsIjIwMjQtMDgtMTMiLCJBVVMiLG51bGwsIlVBIiwiMjk5Il1dXQ%3D%3D)<img width="1669" alt="image" src="https://github.com/user-attachments/assets/25d7df55-5009-4a58-bfd5-490dc0183756">

For one-way flights, you get the `booking_token` right away:

[One-way flight:
](https://serpapi.com/playground?engine=google_flights&departure_id=CGK&arrival_id=AUS&gl=us&hl=en&currency=USD&type=2&outbound_date=2024-08-13)<img width="1670" alt="image" src="https://github.com/user-attachments/assets/0d9a2f02-5354-4638-a339-95f80e7b14c4">

I'm closing this as it seems there is no issue. Feel free to reopen if I missed something.

**Comment by hilmanski** [comment]
Thank you so much, @marm123. I missed that. It might be a good idea to add this on the documentation.
