### ISSUE TITLE
[Bing News API] Searches for mainland China with `mkt=zh-cn` or `cc=CN` failing

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1834]
A customer reported their searches to the Bing News API including `mkt=zh-cn` have been failing after running for 90+ seconds. Running the same search in actual Bing News redirects the user immediately to the main Bing search page. It seems like Bing News has dropped support for mainland China.

The same behavior is seen when setting `cc=CN`.

[Playground with mkt](https://serpapi.com/playground?engine=bing_news&q=beijing&mkt=zh-cn)

Bing News with `mkt=zh-cn`: https://www.bing.com/news/search?q=beijing&mkt=zh-cn

![image](https://github.com/user-attachments/assets/92be6131-4142-4362-9996-90af75a07541)

[Playground with cc](https://serpapi.com/playground?engine=bing_news&q=beijing&cc=CN)

Bing News with `cc=CN`: https://www.bing.com/news/search?q=beijing&cc=CN

![image](https://github.com/user-attachments/assets/9bb94cbf-98f3-4351-9112-c0065f9a0928)

Setting one's country to China in Bing settings also causes all Bing News links to redirect to main Bing search.

![image](https://github.com/user-attachments/assets/a152888c-896e-4e0f-9a77-55ebecbf84a2)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069429?view=List)

**Comment by zyc9012** [comment]
Seems true. Confirmed using Chinese IP.

There's no "News" on the headers anymore.

![image](https://github.com/user-attachments/assets/813be10e-ae1e-4928-89a8-df8131b67d4c)

**Comment by aciddjus** [comment]
Let's update the supported values for these parameters, then.

**Comment by aciddjus** [comment]
Thanks, @andypple83 👍 
Don't forget to [update the issue](https://github.com/serpapi/SerpApi?tab=readme-ov-file#contributing-and-deploying).

**Comment by andypple83** [comment]
Thanks @aciddjus for reminding this.

We've updated our Bing News API parameter configuration. Head to our [Bing News Playground](https://serpapi.com/playground?engine=bing_news&q=Coffee) to see latest supported countries and Market codes.

![Screenshot 2024-10-23 at 16 46 44](https://github.com/user-attachments/assets/bf77cf2c-093f-462f-bf93-2b87f9cb5449)
