### ISSUE TITLE
[Google Search API - Local Pack Result] Missing local map results

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#1836]
We're missing local map results when searching with Google Search

![Screenshot 2024-08-13 at 16 03 48](https://github.com/user-attachments/assets/8ed48881-8505-4699-b9cc-6ca41a705c5d)

[Playground](https://serpapi.com/playground?q=1+birger+jarlsgatan+stockholm+sweden&location=Sweden&google_domain=google.se&gl=se&hl=sv&device=mobile&no_cache=true) | [Inspect](https://serpapi.com/searches/66bb21515235f6240b2944dd/inspect)

**Comment by Alaa-abdulridha** [comment]
This issue has been resolved:

Before fixing the issue (Production):
![image](https://github.com/user-attachments/assets/c236a44c-2272-4005-9772-396538e5cd4f)

After fixing the issue (Production):

![image](https://github.com/user-attachments/assets/f1539765-6f65-43b2-9867-73fe9dd883f1)
