### ISSUE TITLE
[Google Shopping API] Increased response times

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1837]
We've been seeing increased response times for the Google Shopping API since roughly 15:00 UTC August 12. These peaked for several hours between 10-17s per request. These have now settled down around 6-8s per request, but this is still 2-3x than normal.

https://serpapi.com/status/google_shopping

![image](https://github.com/user-attachments/assets/b0af7c90-8901-4c1f-89a7-b5a24e45a37c)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069357?view=List)
[Intercom 2](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069452?view=List)

**Comment by marm123** [comment]
Thanks @alexbarron. Adding the customer who reported this initially:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069449?view=List)

**Comment by NateSkiles** [comment]
Another customer reached out with this issue:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069470?view=List)

**Comment by sonika-serpapi** [comment]
Another customer reached out for this issue

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068510?view=List)

**Comment by hilmanski** [comment]
A customer reported this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069512?view=List)

**Comment by InfiniteCodeMonkeys** [comment]
Hey guys, any movement on this? We still have response times above 20secs with ludicrous speed.

**Comment by tanys123** [comment]
Hi @InfiniteCodeMonkeys, we are working to adapt to the new layout change. As there are new sections introduced in the new layout, we are taking some time to design the API response. We'll let you know once it is deploy, thank you for your patient!

**Comment by tanys123** [comment]
We have deployed new changes to address the response times (mainly for searches in `US` region), you should notice faster response time on your end 🎉 . It is a new layout from Google, but we've tried our best to keep the JSON structure consistent. Please let us know if you encounter any issue 🙏 

Example with Ludicrous Speed:
<img width="1467" alt="Screenshot 2024-08-16 at 2 15 23 PM" src="https://github.com/user-attachments/assets/06e90190-7c83-4c62-84d8-96f5d0c82151">
<img width="1465" alt="Screenshot 2024-08-16 at 2 16 01 PM" src="https://github.com/user-attachments/assets/58c42d33-9d0e-46b4-9ba9-0ec421261f47">
<img width="1462" alt="Screenshot 2024-08-16 at 2 16 37 PM" src="https://github.com/user-attachments/assets/4e7d853b-f2c5-416b-b6e7-f8fb70b5b38b">

**Comment by fawazransari** [comment]
Hi, It looks like the new changes doesn't include the product link on results page. There's a `product_link` which is pointing to google shopping product page but not to the original source link

**Comment by marm123** [comment]
Hi @fawazransari, thanks for mentioning that! Unfortunately, it looks like the link is no longer provided by Google in the new layout. Please check this thread: https://github.com/serpapi/public-roadmap/issues/1845

I'll open a separate feature request to scrape a direct link with our Google Product API, as this is possible, but we'll no longer be able to provide the direct link with Google Shopping API.

I'm very sorry for the inconvenience.

**Comment by marm123** [comment]
@fawazransari, here is the feature request to scrape a direct link on Google Product API: https://github.com/serpapi/public-roadmap/issues/1845

**Comment by InfiniteCodeMonkeys** [comment]
Hey is there a reason for changing link in shopping_results to product_link? Would it be possible to revert that change?

**Comment by marm123** [comment]
On top of what @alexbarron mentioned, I want to also note that the `link` endpoint has not been replaced with the `product_link`. The `product_link` was always returned along with the `link`, but unfortunately, Google no longer returns the latter.

We prioritized the feature to introduce the direct `link` in the Google Product API. While this will require you to adjust the way you're extracting the `link` value now, it seems like the only viable way to get the information you were getting with the old Google Shopping layout. I'm very sorry for the inconvenience.

**Comment by InfiniteCodeMonkeys** [comment]
Thanks for the clarification

**Comment by fawazransari** [comment]
If I understand it correctly, we'll have to make another serp call on Google Product API to get the `link` for all the products on Google Shopping results? Is there a possibility we can avoid that and get the `link` directly

**Comment by alexbarron** [comment]
> If I understand it correctly, we'll have to make another serp call on Google Product API to get the `link` for all the products on Google Shopping results? Is there a possibility we can avoid that and get the `link` directly

That is correct. Unfortunately, this is out of our control due to the layout changes Google released to their Google Shopping results. More about this is available in this tread: https://github.com/serpapi/public-roadmap/issues/1845

I understand it's not an ideal solution. Since it's not possible to scrape this link anymore from Google Shopping results, we have to scrape it from Google Product pages which requires additional requests.

**Comment by sonika-serpapi** [comment]
Customers have reached out asking for a better solution than making so many more requests to the Google Product API to get the direct link.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069561?view=List)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069560?view=List)

**Comment by tanys123** [comment]
We have made a new release that adds `link` to Google Shopping API. You have to enable it by passing `direct_link=true`. Feel free to try it out and feedback to us.

<img width="1458" alt="Screenshot 2024-08-29 at 9 01 52 PM" src="https://github.com/user-attachments/assets/586cb8e3-a28d-4eb7-934d-6b8a2e8788c7">

**Comment by tanys123** [comment]
After the release ([new layout release](https://github.com/serpapi/public-roadmap/issues/1837#issuecomment-2292898661)), the response time has consistently improved compared to before. We also made another release to restore product's `link` that was no longer available in the new layout. I am closing this thread as completed. Feel free to send feedback to us.

<img width="1106" alt="Screenshot 2024-08-30 at 9 50 55 AM" src="https://github.com/user-attachments/assets/1eb6a4b7-6ba5-479b-bba9-16cda4c8cdea">

[status page](https://serpapi.com/status/google_shopping)

**Comment by hartator** [comment]
![CleanShot 2024-08-30 at 17 51 08@2x](https://github.com/user-attachments/assets/1da53009-fd61-43c2-ae5c-8abb993c1c9a)

Really like that screenshot. Good job @tanys123. 👍
