### ISSUE TITLE
[Yelp Search API] Increased response time and failed requests

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#1838]
The customer that reported #1835 followed up with examples of failed requests, but as they were using the Yelp engine and not Yelp Place, I've opened this issue separately.

I tried to recreate the failures the user received in the playground, but was unable.

`"error": "We couldn't get valid results for this search. Please try again later."`

Search Inspector:
* [Search 1](https://serpapi.com/searches/66bb814ac05eb564deb76aef/inspect)
* [Search 2](https://serpapi.com/searches/66bb834a1b4e349d06a10301/inspect)
* [Search 3](https://serpapi.com/searches/66bb86d2a9210b4d186a7229/inspect)

![image](https://github.com/user-attachments/assets/846c41c0-7304-4996-b45a-e6e8433cdb15)

In addition to these searches, I'm seeing an increase in failed requests and response times starting yesterday (8/12) on the Yelp engine:
* https://serpapi.com/status/yelp
![image](https://github.com/user-attachments/assets/8b7744e1-b461-4041-80ce-12f96c119d71)

[Front](https://app.frontapp.com/open/cnv_1ch9tvfg?key=wd8013JJahcja5tKIdUaJMhSu4b06Gau)

**Comment by alexbarron** [comment]
Another report here:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069549?view=List)

**Comment by tanys123** [comment]
We have deployed a new update to Yelp Search API to address the slow response. We've seen faster response time but we will keep monitoring.

<img width="1469" alt="Screenshot 2024-08-16 at 8 17 31 PM" src="https://github.com/user-attachments/assets/02ea3c5a-850b-4328-8413-c52840111498">

**Comment by tanys123** [comment]
The response time has remained consistently faster since the deployment. We're closing this, but feel free to reach out to us if you encounter any issue.

<img width="1127" alt="Screenshot 2024-08-19 at 10 46 42 AM" src="https://github.com/user-attachments/assets/304897bd-c1ce-4d97-80f7-699fcec91962">
