### ISSUE TITLE
[Account API] Clarify confusing documentation

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1839]
Together with @paigebutler we discovered that our Account API suggests that using it will consume search credits, while in fact, the API is free of charge and no search credits will be deducted. While this was not reported as an issue by any of our customers, it can still potentially prevent them from using the API if they think they might lose search credits they'd rather spend on other APIs.

Current state:
<img width="588" alt="image" src="https://github.com/user-attachments/assets/d3a00885-2820-46b2-9b8d-65ad469da316">

Potential update:
<img width="620" alt="image" src="https://github.com/user-attachments/assets/b184b788-8fff-4c39-b1f0-b045c13d424a">

[Documentation](https://serpapi.com/account-api)

**Comment by Ovi** [comment]
The documentation has been updated accordingly

<img width="583" alt="screenshot" src="https://github.com/user-attachments/assets/26571ff9-f0cf-4970-be7c-791f98720afd">
