### ISSUE TITLE
[Supported Google Languages] Add `he` as a supported Google language

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1841]
In 1989, the ISO code for Hebrew changed from `iw` to `he`. Google currently supports both `iw` and `he`, but we only support `iw`.

`iw` is actually deprecated according to the ISO standards: https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes#cite_note-coverpage-4

![image](https://github.com/user-attachments/assets/18be6e62-c2aa-4136-9d28-4f7f30c41202)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069501?view=List)

**Comment by fadupla** [comment]
Thank you !

**Comment by Ovi** [comment]
We now support `he` as a valid `hl` parameter

<img width="343" alt="image" src="https://github.com/user-attachments/assets/33bcf172-752c-4eca-86d1-cd412bfaf837">
