### ISSUE TITLE
[Google Search API] `ads` results `reviews` and `rating` not parsed for some searches

### ISSUE THREAD

**Issue by btaunt** [serpapi/public-roadmap#1843]
We are not parsing `rating` or `reviews` under `ads` for some searches:

<img width="714" alt="Screenshot 2024-08-15 at 1 51 07 PM" src="https://github.com/user-attachments/assets/5dc2b9bc-eca7-4a5f-bfbd-8068211fd7c8">
<img width="900" alt="Screenshot 2024-08-15 at 2 11 38 PM" src="https://github.com/user-attachments/assets/31caefa6-8d5f-4510-bffc-7849d80f6e45">

---

- [Playground](https://serpapi.com/playground?q=walmart&location=New+York%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client+votes+site+ie+oe+pws+ibp+source+ijn+rlz) | [Inspect](https://serpapi.com/searches/66be44b7e1d1adee8a2d4346/inspect)

**Comment by Ovi** [comment]
We now parse `reviews` and `rating`

<img width="1728" alt="Screenshot 2024-09-17 at 12 40 35 PM" src="https://github.com/user-attachments/assets/567ab0cb-a746-4ae6-b424-f95f155744fa">

[Playground](https://serpapi.com/playground?q=Macys&location=New+York%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true&google_domain=google.com)
