### ISSUE TITLE
[Google Shopping API] Searches with `gl=us` and `hl` different than `en` are timing out

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1844]
One of our customers reported that searches with `hl` different than `en` are not working. I was able to reproduce this error when the `gl` is set to `us`, as with any other `gl` value, everything seems ok.

<img width="1669" alt="image" src="https://github.com/user-attachments/assets/a99c4cc3-a00f-4263-91ef-36887e5708a8">

[Playground](https://serpapi.com/playground?engine=google_shopping&q=Coffee&gl=us&hl=nl) | [Inspect](https://serpapi.com/searches/66bf07e5f410448b22791e3b/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069541?view=List)

**Comment by aciddjus** [comment]
[Live page](https://www.google.com/search?udm=28&q=%26%2367%3B%26%23111%3B%26%23102%3B%26%23102%3B%26%23101%3B%26%23101%3B&hl=nl&gl=us) returns empty results.

**Comment by hartator** [comment]
> [Live page](https://www.google.com/search?udm=28&q=%26%2367%3B%26%23111%3B%26%23102%3B%26%23102%3B%26%23101%3B%26%23101%3B&hl=nl&gl=us) returns empty results.

Direct browser seems to work on mine:

![CleanShot 2024-08-23 at 06 14 56@2x](https://github.com/user-attachments/assets/4dc56f9f-6c5c-440d-bd72-d2f2b88268ee)

But, [playground](https://serpapi.com/playground?engine=google_shopping&q=Coffee&gl=us&hl=nl) does process forever:

![CleanShot 2024-08-23 at 06 16 54@2x](https://github.com/user-attachments/assets/065ca418-f6b2-49a4-98c1-f682c1a17a2f)

**Comment by tanys123** [comment]
We have deployed a fix for the issue. Searches with `gl=us` and `hl` other than `en` are returning results. Do note that searches other than `hl=en` is displaying old layout, but our JSON structure will remain consistent regardless.

<img width="1384" alt="Screenshot 2024-09-03 at 9 38 14 AM" src="https://github.com/user-attachments/assets/140f885c-cdb8-4ce1-b1f1-ce7951ccb22f">
