### ISSUE TITLE
[Google Shopping API] Scrape favicons for sellers on Google Shopping

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1847]
Google Shopping now displays favicons for sellers. We aren't scraping these yet.

![image](https://github.com/user-attachments/assets/cc230fcf-ddb8-4795-aafc-4311bf4f235f)

![image](https://github.com/user-attachments/assets/4fc18f54-ffbe-4781-83a7-a15db37f55d0)

[Playground](https://serpapi.com/playground?engine=google_shopping&q=Coffee)

[Front](https://app.frontapp.com/open/cnv_1bznnrrw?key=nkOQCsxu1rzzG1xmcwEJ1aUMzmlP285H)

**Comment by vicyankoff** [comment]
@Ovi any update on when this feature will be added to the API results? Thanks!

**Comment by alexbarron** [comment]
> @Ovi any update on when this feature will be added to the API results? Thanks!

Hi @vicyankoff , I can tell you it is actively being worked on, but I don't have an exact ETA just yet. Hopefully soon.

Thank you for your patience!

**Comment by Ovi** [comment]
We are now scrapping favicon for sellers on Google Shopping as `source_icon`

<img width="1728" alt="Screenshot 2024-09-06 at 10 49 34 AM" src="https://github.com/user-attachments/assets/32f54d96-e1d9-436e-8391-d23430b21cc8">
