### ISSUE TITLE
[Google Shopping API] Missing `thumbnail` for `inline_shopping_results`

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1848]
Our docs state that we should be returning `thumbnail` for results within `inline_shopping_results`, but that field is missing in actual responses.

[Playground](https://serpapi.com/playground?engine=google_shopping&q=patio+furniture&location=United+States&gl=us&hl=en)

![image](https://github.com/user-attachments/assets/906dd4cf-cd21-42de-aae4-c8a0d6465a75)

[Docs](https://serpapi.com/google-shopping-api#api-examples-json-structure-overview)

![image](https://github.com/user-attachments/assets/17b2a0b3-586b-4138-83fe-6ab5c7e9d00b)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069555?view=List)

**Comment by btaunt** [comment]
This has been resolved. We now properly parse the `thumbnail`, along with fixing a minor issue with `price` and `extracted_price`:

### BEFORE
![image](https://github.com/user-attachments/assets/8ab175bc-2305-4a34-a633-d10965332530)

### AFTER
![image](https://github.com/user-attachments/assets/f1276d9d-4312-48ce-9801-316ba30d18ab)

---

[Playground example](https://serpapi.com/playground?engine=google_shopping&q=iphone+12&no_cache=true) | [Inspect](https://serpapi.com/searches/66c7429acc2987d901a4ece7/inspect)

**Comment by alexbarron** [comment]
Thank you @btaunt !
