### ISSUE TITLE
new google trends

### ISSUE THREAD

**Issue by githubfan21** [serpapi/public-roadmap#1850]
Google Trends has changed a lot recently
- can you scrape https://trends.google.com/trending?geo=US&hours=4&status=active&sort=search-volume
- 4 parameters geo,hours,status,sort
- don't drop the existing trends of daily and realtime.

**Comment by tanys123** [comment]
Thanks @githubfan21 for reporting. We already have the same [issue](https://github.com/serpapi/public-roadmap/issues/1828) reported. We will keep in mind not to drop the existing functionalities from the engine.

**Comment by githubfan21** [comment]
it seems the issue is closed, any updates on the new google trends page

**Comment by NateSkiles** [comment]
@githubfan21 Hi there, issue #1828 is still open. There are no updates on this issue at this time, but please feel free to subscribe to the issues to be notified of future updates.
