### ISSUE TITLE
[Google Shopping API] Fix Pagination Parameters and Clarify Documentation

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1858]
A potential Enterprise Customer reached out to ask for clarification on the pagination for the Google Shopping API.

The `num` parameter currently seems to be ignored for US searches. If it's not possible to fix this, we should note this in the documentation and disable it in the Playground.

Also, our documentation now states that for searches in the US, `start` should be incremented by 10. This seems to be accurate but could use further clarification since 40 results are returned per page.

Here is a suggestion for what the revised documentation could look like:

<img width="829" alt="Screenshot 2024-08-20 at 4 13 34 PM" src="https://github.com/user-attachments/assets/dcadb803-f097-42a0-9add-fed5ed3476a0">

[Front ](https://app.frontapp.com/open/msg_2h1nvd24?key=nkOQCsxu1rzzG1xmcwEJ1aUMzmlP285H)| [Documentation](https://serpapi.com/google-shopping-api) | [Playground](https://serpapi.com/playground?engine=google_shopping&q=Coffee)

**Comment by schaferyan** [comment]
The customer also noted that the `serpapi_pagination.next` URL also seems to have a value of `start=20` on the first page. 

I experimented in the playground and saw some strange behavior for `serpapi_pagination`. It seemed to increment by 20 for the first several pages, then stopped changing (the same `start` value was suggested to be used again).

**Comment by hilmanski** [comment]
The user shared another example of another weird behavior related to Google Shopping's pagination.

- pagination.next value showed a plain Google link
- serpapi_pagination showed the current link

![2e45b9cb0121c864f617c88b93eccbbe7386a130](https://github.com/user-attachments/assets/0b936300-2342-4da2-8bae-8061211ebeba)


[Inspect](https://serpapi.com/searches/66c5646576079d293e6999f9/inspect)

**Comment by hilmanski** [comment]
A customer reported a similar bug in their search.

[Inspect](https://serpapi.com/searches/66db804db57db84685944cc7/inspect)

**Comment by sonika-serpapi** [comment]
A customer reached out about this: https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069512?view=List

**Comment by sharjeelm** [comment]
@Krugloff Any estimate on the completion of this issue

**Comment by sonika-serpapi** [comment]
@sharjeelm Thank you for your question. The documentation changes have been made as part of the PR linked to this roadmap issue: https://github.com/serpapi/SerpApi/pull/5229. It's difficult to provide an ETA, but the other parts of this issue have been marked in progress and are still being worked on.

**Comment by sharjeelm** [comment]
@sonika-serpapi Sorry to ping again shortly on this but I have a product build upon Google Shopping API section of SERP API and major section of that product is failing due to pagination issue. I hope you understand my stance as if you can prioritize the fixing of this issue

**Comment by martin-serpapi** [comment]
Thank you for following up with us @sharjeelm ! I'm really sorry for the inconvenience this is causing. There is a PR linked to this issue which is currently under review. Unfortunately, I cannot provide an ETA for when it will be merged. However, this issue has been labeled as prioritized and our engineers will try to merge the PR as soon as possible.

**Comment by sharjeelm** [comment]
@martin-serpapi @sonika-serpapi Can I please get update on this . As our product is blocked due to pagination issue. If this can take longer I fear we will have to migrate to zenserp .

**Comment by marm123** [comment]
Hi @sharjeelm, thanks for reaching out.

We're still working on the pull request review. While I can't share the exact ETA, I hope this will be resolved sometime this week.

@Krugloff can you perhaps share more details or when we can potentially expect the PR to be merged?

**Comment by tanys123** [comment]
Hi @sharjeelm, we are actively working on this issue. To further understand, I would like to discuss further to see if our latest solution could help. Could you please share more details about it? If you prefer, feel free to email me at terry@serpapi.com.

**Comment by sharjeelm** [comment]
Thanks a lot for update @Krugloff

**Comment by Krugloff** [comment]
@sharjeelm We've completed the Google Shopping pagination for the new layout. I recommend using it via the `serpapi_pagination.next` parameter. I hope it will work well for your needs, but please don’t hesitate to reach out if you encounter any issues!

<img width="1449" alt="Screenshot 2024-10-28 at 16 03 36" src="https://github.com/user-attachments/assets/eb5060ed-d61e-46c4-94ea-d2057b934e9c">

**Comment by sharjeelm** [comment]
One thing to note it always takes a difference of 10 in next
and then next=20 while giving 40 products

**Comment by schaferyan** [comment]
Thank you @sharjeelm. Yes, this is now how the `start` parameter now works on Google's side. We understand it's not intuitive, which is why we recommend using `serpapi_pagination.next` instead of incrementing `start` directly.

**Comment by sharjeelm** [comment]
@schaferyan @Krugloff Can you please clarify one more thing how I can make sure that google shopping search API will always provide response as per new version of google shopping as I was unable to see any parameter in google shopping search api to do so .

**Comment by sharjeelm** [comment]
Sorry to ping again Can you please clarify one more thing how I can make
sure that google shopping search API will always provide response as per
new version of google shopping as I was unable to see any parameter in
google shopping search api to do so .

**Comment by martin-serpapi** [comment]
Hi @sharjeelm , thank you for your follow-up question. 

Unfortunately, we don't support a parameter with our Google Shopping API that will force it to use the new layout for all of your searches. This depends on the actual Google Shopping engine and we don't have control over it. Whether results using the new layout are returned for your search depends on the location you used for it.

Google has released the new shopping layout in the US, and a few other countries. You can view a list of the countries supporting the new layout in our [Google Shopping API documentation](https://serpapi.com/google-shopping-api).

Searches for these locations will return results using the new shopping layout.

I hope this makes sense. If you have any follow-up questions, please let me know.

**Comment by sharjeelm** [comment]
I am trying only for US still getting old version data
