### ISSUE TITLE
[Google Related Questions API] Searches with `next_page_token` return no results

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1865]
One of our customers noted that the Google Related questions API seems to be down. We should look into this and see if the `next_page_token` has been replaced with a different value.

Output with valid `next_page_token`:
<img width="1670" alt="image" src="https://github.com/user-attachments/assets/108985e6-1a1c-4ac7-8e9c-d4e492531d8b">

[Playground - Google Search API](https://serpapi.com/playground?q=best+phones&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Inspect - Google Search API](https://serpapi.com/searches/66c8653421e77b3c9fc11a9b/inspect)
[Playground - Google Related Questions API](https://serpapi.com/playground?engine=google_related_questions&next_page_token=eyJvbnMiOiIxMDA0MSIsImZjIjoiRW9zQkNreEJTa2M1U210UVlqUmpRbUV3WTJkV1IwVndZVFZKYTA1MWQwdDZla1ZmUkRreVRuTndSRzl5WmtJNExYZFVWUzEwZG0weFkzQjZVMFZvYVdkTVVVTktkMmhvVVZNNWJFdzRjMmN4RWhkT1YxaEpXbkZIY0VaZmVXczFUbTlRYlRWSFp6SlJZeG9pUVVaWWNrVmpjVFpvWW1wUVUzRTFPVFZpV2pCQlNHeEhkR05zYUU1WmN6RXlRUSIsImZjdiI6IjMiLCJlaSI6Ik5XWElacUdwRl95azVOb1BtNUdnMlFjIiwicWMiOiJDZ3RpWlhOMElIQm9iMjVsY3hBQWZRRENGejgiLCJxdWVzdGlvbiI6IldoYXQgaXMgdGhlICMxIGJlc3QgcGhvbmU%2FIiwibGsiOiJHaGwzYUdGMElHbHpJSFJvWlNBak1TQmlaWE4wSUhCb2IyNWwiLCJicyI6ImMtT3k0WklLejBnc1VjZ3NWaWpKU0ZWUU5sUklTaTB1VVNqSXlNOUx0WmM0a21Va0xTVlpqa3NCVndpWFduaEdabktHUW1KUktsaTZKTDlBd2RBQW9xUTRON0dvQkt5dTJGNWllcjJSdXBScU9UR0t1UUs0VkNDbVF1MUVXQWpVb2xDU21KMnFrSmRmYmkteGxNTklWVXE1bkxCU3JpQXVWYkF2a1cwMlJsYWNWSlNZbHdKMFpvT0RrWnFVU2prUmFnVVlBUSIsImlkIjoiZmNfMSJ9)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069740)

**Comment by martin-serpapi** [comment]
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069870?view=List)

**Comment by aciddjus** [comment]
We have fixed this issue.

<img width="1513" alt="image" src="https://github.com/user-attachments/assets/4cbce3d5-ac2b-44f4-afcf-2bab96cf436e">
