### ISSUE TITLE
Phone number validation not implemented properly

### ISSUE THREAD

**Issue by imtiazali1466** [serpapi/public-roadmap#1867]
![Screenshot 2024-08-24 102528](https://github.com/user-attachments/assets/fe2e70b1-1925-4b8d-b04b-bf03b660392d)
After putting the phone number as shown in placeholder now return Invalid phone number
03XX XXXXXXX

**Comment by hilmanski** [comment]
We apologize for the issue. Feel free to reach out at contact(at)serpapi(dot)com. We'll activate your account manually.
