### ISSUE TITLE
[Yelp Place API] Miss rating information

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1869]
A high-volume customer reported that we missed the rating in the Yelp Place API response.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069788?view=List) | [Playground](https://serpapi.com/playground?engine=yelp_place&place_id=arabica-brooklyn) | [Inspect](https://serpapi.com/searches/66cbec0df3622a130c47fde7/inspect)

**Comment by sonika-serpapi** [comment]
A high-volume customer requested to expedite this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069850?view=List)

**Comment by schaferyan** [comment]
I just want to add for clarity that the customer @sonika-serpapi mentioned above is the same customer who initially reported the issue.

**Comment by aciddjus** [comment]
We have fixed the issue. The rating is now being extracted.

![image](https://github.com/user-attachments/assets/41fed6a9-95ff-4499-87ca-5bf19176151c)
