### ISSUE TITLE
[Google Hotels API] Missing `total_results` in `search_information`

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1871]
A customer reported we're not returning `total_results` in `search_information` as documented in the Google Hotels API docs. The HTML preview on our side is also missing this information, but actual Google Hotels will display the number of hotels matching the search criteria.

[Documentation](https://serpapi.com/google-hotels-api) shows we support this:

![image](https://github.com/user-attachments/assets/c5d2d905-bbc4-4cf3-8c35-ed2db7a817c0)

[Playground](https://serpapi.com/playground?engine=google_hotels&q=liverpool+uk+hotels&gl=us&hl=en&currency=USD&check_in_date=2024-09-01&check_out_date=2024-09-08) example shows we're missing this field both in the JSON and HTML:

![image](https://github.com/user-attachments/assets/44c501e6-7451-48f4-b764-8dafce9ede6a)

[Actual Google Hotels](https://www.google.com/travel/search?q=liverpool%20uk%20hotels&qs=CAEgASgAOA1IAA&ved=0CAAQ5JsGahgKEwiYx8D3yJKIAxUAAAAAHQAAAAAQxQE&ts=CAESCgoCCAMKAggDEAAaNwoZEhUKCC9tLzA0bGg2OglMaXZlcnBvb2waABIaEhQKBwjoDxAJGAESBwjoDxAJGAgYBzICCAEqCQoFOgNHQlAaAA&ap=MAE) displays the total results:

![image](https://github.com/user-attachments/assets/16768dc9-016b-4174-b7e4-7509b7a182e1)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069801?view=List)

**Comment by Alaa-abdulridha** [comment]
This issue now has been resolved.

Before resolving the issue (Production):
![image](https://github.com/user-attachments/assets/7ec1e115-21e4-4de3-95fc-81e807702a75)


After resolving the issue (Production):

![image](https://github.com/user-attachments/assets/adb2bd01-8e55-4a5d-9968-42110cd248ac)
