### ISSUE TITLE
[Naver Search API] `organic_results` not returned in the response

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1873]
A customer reported that they receive an error when trying to access `organic_results` in the response. I was able to reproduce it in the Playground:

<img width="1430" alt="image" src="https://github.com/user-attachments/assets/007ddc96-c30d-49e1-b07a-a55d9335b85b">

[Playground](https://serpapi.com/playground?engine=naver&query=Coffee&where=nexearch&no_cache=true) | [Inspect](https://serpapi.com/searches/66cdc921f963e7c1503609f7/inspect)

When performing a search using the `where=web` parameter an `organic_results_state=Fully empty` and `error=Naver hasn't returned any results for this query.` is returned in the response:

![image](https://github.com/user-attachments/assets/48c60cc6-7dd2-4e98-b578-c687309edd29)

[Playground](https://serpapi.com/playground?engine=naver&query=Coffee&where=web) | [Inspect](https://serpapi.com/searches/66cdc93406f4f209ee67be29/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069832?view=List)

**Comment by Alaa-abdulridha** [comment]
This issue has been resolved:

Organic_results after resolving the issue (Production):

![image](https://github.com/user-attachments/assets/cc0b8144-e386-4e22-bf06-711e61fa5b14)
