### ISSUE TITLE
[Google Search API] Missing support for China in `cr` parameter

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1874]
A customer asked about using `countryCN` in the `cr` parameter. We currently do not accept requests including `countryCN` in the `cr` param.

[Playground](https://serpapi.com/playground?q=Coffee&hl=en&cr=countryJP%7CcountryCN&newPara=as_sitesearch)

![image](https://github.com/user-attachments/assets/ff12cd97-6901-4820-a6e9-402f7131e88d)

According to Google's docs, `countryCN` is valid, but our list of supported countries doesn't include China.

![image](https://github.com/user-attachments/assets/132cd634-4142-4ec7-8223-592b3649bbb6)

[Google List](https://developers.google.com/custom-search/docs/json_api_reference#countryCollections)
[Our List](https://serpapi.com/google-cr-countries)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069840?view=List)

**Comment by zyc9012** [comment]
We've released a fix for this. The following missing values for the `cr` parameter has been added.

```
countryAQ
countryAW
countryBB
countryBM
countryBV
countryIO
countryKY
countryCN
countryCX
countryCC
countryKM
countryCD
countryTP
countryGQ
countryER
countrySZ
countryEU
countryFK
countryFO
countryFX
countryGF
countryPF
countryTF
countryGD
countryGU
countryGN
countryGW
countryHM
countryVA
countryIR
countryLR
countryMO
countryMH
countryMQ
countryMR
countryYT
countryMC
countryAN
countryNC
countryNF
countryKP
countryMP
countryPW
countryPN
countryRE
countryST
countryCS
countryGS
countryKN
countryLC
countryPM
countrySD
countrySJ
countrySY
countryTC
countryTV
countryUM
countryWF
countryEH
countryYE
countryYU
```

Please see https://serpapi.com/google-cr-countries for details.

**Comment by aciddjus** [comment]
Thanks, @zyc9012 👍 

Make sure to update the `status` badge to `completed`.
