### ISSUE TITLE
[Google Search API] Top Carousel is not extracted

### ISSUE THREAD

**Issue by ilyazub** [serpapi/public-roadmap#1877]
One of the Google top carousel layouts is not extracted.

<img width="1728" alt="b61d8fd700145b45549ec4f1b0f157d76f6b6b85" src="https://github.com/user-attachments/assets/41412c87-eca8-405f-9635-1d71f9d9416d">

[Search Inspect](https://serpapi.com/searches/66ceec626a5dd3ba7e257bbb/inspect) | [Playground](https://serpapi.com/playground?q=John+Wick+actors&location=United+States&gl=us&hl=en)

_Originally noticed by @dsojevic ([ref](https://github.com/serpapi/code-challenge/blob/e5b2ab0d827827c8747e87a79d6d400ddaaf6542/README.md?plain=1#L159)). 👍_

**Comment by dsojevic** [comment]
Was going through some of my fixtures and found another instance of the top carousel/grid missing:
![image](https://github.com/user-attachments/assets/a82e5fa9-55ed-43dd-a355-facd0550f14b)

[HTML](https://serpapi.com/searches/f6ac6f10bb13cd67/66d694456273fbb073759575.html) | [JSON](https://serpapi.com/searches/f6ac6f10bb13cd67/66d694456273fbb073759575.json) | [Playground](https://serpapi.com/playground?q=%D0%9F%D1%96%D1%81%D0%BD%D1%96+%D0%91%D1%83%D0%BC%D0%B1%D0%BE%D0%BA%D1%81&location=Kyiv%2C+Kyiv+city%2C+Ukraine&google_domain=google.com.ua&gl=ua&hl=uk&device=desktop)

**Comment by hilmanski** [comment]
Thank you very much for your additional report! @dsojevic

**Comment by Alaa-abdulridha** [comment]
This issue had been resolved.

Before resolving the issue (production):

![image](https://github.com/user-attachments/assets/1fc7defb-df05-43ef-8606-a3da896b953d)



After resolving the issue (production):

![image](https://github.com/user-attachments/assets/71302cb7-e76a-47dd-a962-c7184286baf8)
