### ISSUE TITLE
[Google Maps API] Local Results start indexed at position 2 when Google autocorrects query

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#1880]
A customer reported an issue where they see `local_results` returning the first result in position 2.

Example shared by them: https://serpapi.com/playground?engine=google_maps&q=rolloff+dumpster&ll=%4033.49948773767679%2C-112.08133797232044%2C12z&hl=en&type=search

I was able to reproduce and root cause it, and found out that this seems to happen when google auto corrects a query and displays a message on top, in this case - "Showing results for roll off dumpster. Search instead for rolloff dumpster". Google added a space between "roll" and "off".

Results for query: "rolloff dumpster" - This starts indexed at 2
https://serpapi.com/playground?engine=google_maps&q=rolloff+dumpster&ll=%4033.49948773767679%2C-112.08133797232044%2C12z&hl=en&type=search

![Screenshot 2024-08-29 at 1 35 01 PM](https://github.com/user-attachments/assets/8c13537c-f257-4b4a-b8f2-f23e4f0f2150)

All the results are still returned, it's the numbering which is incorrect I believe.

Results for query: "roll off dumpster" - This starts indexed at 1
https://serpapi.com/playground?engine=google_maps&q=roll+off+dumpster&ll=%4033.49948773767679%2C-112.08133797232044%2C12z&hl=en&type=search

![Screenshot 2024-08-29 at 1 35 40 PM](https://github.com/user-attachments/assets/33db093d-e914-4508-bbb5-ec3fa3136367)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069919?view=List)

**Comment by Ovi** [comment]
The issue of local results start at position 2 has been fixed

<img width="1728" alt="Screenshot 2024-09-06 at 11 33 35 AM" src="https://github.com/user-attachments/assets/b46abb0a-bd9e-4426-8eec-c5835ba7c93e">


[Playground](https://serpapi.com/playground?engine=google_maps&q=rolloff+dumpster&ll=%4033.49948773767679%2C-112.08133797232044%2C12z&hl=en&type=search)
