### ISSUE TITLE
[Yelp Reviews API] All requests returning 500 error

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#1882]
A customer reached out, reporting all of their Yelp review searches are failing. The reviews API appears to be the only affected engine at this time.

The searches are returning 'success', so I'm not seeing any indication of the issue on the status page:
![image](https://github.com/user-attachments/assets/616937c3-d738-44ed-bfbd-b412f8e2312e)

However, all requests to the Yelp Reviews API are returning the following error:
```json
{
  "error":
  "Failed to retrieve data, an error encountered on the request to https://www.yelp.com."
}
```

![image](https://github.com/user-attachments/assets/d5bbb820-b997-4417-8a7d-4b33234a185e)

[Playground](https://serpapi.com/playground?engine=yelp_reviews&place_id=MGzro82Fi4LYvc86acoONQ&no_cache=true) | [Inspect](https://serpapi.com/searches/66d232822b5fa736913600f7/inspect)

[Front](https://app.frontapp.com/inboxes/teams/folders/22722140/open/106287869468)

**Comment by coconnor999** [comment]
Confirmed for us as well, getting :
  "error": "Failed to retrieve data, an error encountered on the request to https://www.yelp.com."

This can easily be reproduced using the sample curl code found in the SerpAPI Yelp Review API docs at https://serpapi.com/yelp-reviews-api#api-examples-example-with-place-id-4ofmtrd7pspzix5pndkig-for-mozart-s-coffee-roasters

**Comment by hilmanski** [comment]
Thank you very much for your report @coconnor999 , we'll investigate it and share an update with you here.

**Comment by coconnor999** [comment]
👍

Thanks!

**Comment by zyc9012** [comment]
We've released a fix for this. The API is back to normal.

The `num` parameter has changed - Now the maximum value is `49` instead of `50`.

![image](https://github.com/user-attachments/assets/eaad9d3d-735d-40b0-acde-9a2381b7b006)

**Comment by hilmanski** [comment]
Hi, @coconnor999 , tagging you for visibility. Please let us know if you are still receiving the error. Thank you very much for your patience.

**Comment by coconnor999** [comment]
All good, thanks again!
