### ISSUE TITLE
[Google Shopping API] Searches failing with `gl=ca`

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#1883]
A user reached out reporting that Google Shopping API searches are failing when the country parameter is set to `ca`. I've been able to reproduce this:

![image](https://github.com/user-attachments/assets/53d08c66-a936-4eba-a0fe-7d39ea0d5232)

[Playground](https://serpapi.com/playground?engine=google_shopping&q=Coffee&gl=ca) | [Inspect](https://serpapi.com/searches/66d23a79e1c2764b3f35b7bf/inspect)

The [status page](https://serpapi.com/status/google_shopping) is showing a slight decrease in success rate:

![image](https://github.com/user-attachments/assets/302844a9-7775-4842-aadd-911aea2170d9)

It appears this is currently only affecting searches with `gl=ca`, I have successfully tested the following country parameters:
* `us`
* `uk`
* `tr`

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069942?view=List)

**Comment by schaferyan** [comment]
Another customer reported this:

[Front](https://app.frontapp.com/open/msg_2hfzrbx8?key=AW-GmJjmRlMmBGHe61Yi7Fqfr0lamoRM)

**Comment by Freaky** [comment]
Seems `gl=au` is also having difficulties.
