### ISSUE TITLE
[Google Jobs API] Inconsistent result

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1884]
A customer reported a search showing an empty result with a cookies banner.
![CleanShot 2024-09-02 at 07 39 00](https://github.com/user-attachments/assets/c1fc5bd8-faaa-4bcb-9b8d-26bbde67148b)

However, I'm able to get the result upon retrying.

Failed search: [Inspect](https://serpapi.com/searches/66d46bc1fcd69effb5d30216/inspect)
Successful search: [Inspect](https://serpapi.com/searches/66d4fa81d72128ec4d33fb20/inspect) | [Playground](https://serpapi.com/playground?engine=google_jobs&q=Senior+Full+Stack+Software+Engineer&gl=us&hl=en&chips=date_posted%3Aweek&ltype=1&newPara=next_page_token)

**Comment by aciddjus** [comment]
Thanks, @andypple83 👍 
Don't forget to follow steps 12. and 13. from [wiki](https://github.com/serpapi/SerpApi?tab=readme-ov-file#contributing-and-deploying).

**Comment by andypple83** [comment]
We've released the fix for this. Head to [Playground](https://serpapi.com/playground?engine=google_jobs&q=Senior+Full+Stack+Software+Engineer&gl=us&hl=en&chips=date_posted%3Aweek&ltype=1&newPara=next_page_token) to check the results.
