### ISSUE TITLE
[Google Scholar API] Scrape truncated abstract (snippet)

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1886]
A user reported that we're not scraping the complete snippet (on a truncated abstract with a "show more" button).

![CleanShot 2024-09-02 at 08 00 48](https://github.com/user-attachments/assets/cece31a5-7287-4b71-900c-7bbfe39e1213)

Upon investigating, I'm able to see the full text on the HTML page.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069948?view=List) | [Inspect](https://serpapi.com/playground?engine=google_scholar&q=A+review+on+recent+technological+breakthroughs+in+anaerobic+digestion+of+organic+biowaste+for+biogas+generation%3A+Challenges+towards+sustainable+development+goals&hl=en) | [Playground](https://serpapi.com/playground?engine=google_scholar&q=A+review+on+recent+technological+breakthroughs+in+anaerobic+digestion+of+organic+biowaste+for+biogas+generation%3A+Challenges+towards+sustainable+development+goals&hl=en)

**Comment by ocvit** [comment]
Fix has been released.

Now we grab full abstract snippet if it's available.

<img width="1244" alt="Screenshot 2024-09-05 at 11 35 10" src="https://github.com/user-attachments/assets/a4970bbf-42f9-4763-b3e3-6c1273fe08b9">
