### ISSUE TITLE
[Google Search API] AI overview answer scraped as answer_box

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1887]
A user reported that we're currently returning the AI Overview as `answer_box.`

![CleanShot 2024-09-02 at 09 13 03@2x](https://github.com/user-attachments/assets/1c9bb6e8-9e59-4042-9248-d4b2325f8512)

While we're at it, let's make sure that the actual snippet (answer box) is returned correctly as well.

[Intercom](https://app.frontapp.com/open/cnv_1ctztkm4?key=kpBqRK6RBhG31vvlUXmtyFgNktVLRdsI) | [Inspect](https://serpapi.com/searches/66d50f14059caf3f3fc2df66/inspect)

**Comment by schaferyan** [comment]
Related to https://github.com/serpapi/public-roadmap/issues/1622.

**Comment by marm123** [comment]
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070056?view=List)
