### ISSUE TITLE
[Google Shopping API] Support `direct_link` parameter for `gl` other than `us`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1888]
Google started rolling out new layout to different markets. We have to adjust the `direct_link` parameter to work with `gl` parameters other than `us`.

Canadian search:
<img width="1668" alt="image" src="https://github.com/user-attachments/assets/5f97c83d-323b-4404-a3c6-69217f1f6c7e">

Australian search:
<img width="1669" alt="image" src="https://github.com/user-attachments/assets/abd1d1c7-05d3-47e0-a2e0-dc90fd0aa4b8">

[Playground - Canada](https://serpapi.com/playground?engine=google_shopping&q=Coffee&gl=ca&hl=en&device=desktop) | [Inspect - Canada](https://serpapi.com/searches/66d567ada882783555dc9cff/inspect)
[Playground - Australia](https://serpapi.com/playground?engine=google_shopping&q=Coffee&gl=au&hl=en&device=desktop) | [Inspect - Australia](https://serpapi.com/searches/66d5692ffab2736fa5213460/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069942?view=List)

**Comment by tanys123** [comment]
We have released a new version that supports `direct_link` for countries that are being directed to new layout, such as Canada, and Australia.

<img width="1386" alt="Screenshot 2024-09-03 at 9 32 41 AM" src="https://github.com/user-attachments/assets/066f4dcc-5b9d-4ba5-8930-8906300f2737">
<img width="1371" alt="Screenshot 2024-09-03 at 9 31 26 AM" src="https://github.com/user-attachments/assets/ab717cd8-cac7-43a9-878f-ff35f7c08ec6">
