### ISSUE TITLE
[Google Product API] Products with no reviews get review data assigned from "Related items"

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1890]
A customer reported products on Google Product that have no reviews yet are being assigned review data from the first product under "Related items". We're returning this in `product_results` in the `reviews` and `rating` fields. 

The customer encountered the issue on Google Product India with `gl=in`. I've also reproduced the issue with `gl=us` and `gl=uk`.

[Playground US](https://serpapi.com/playground?engine=google_product&product_id=1945432764539993472&gl=us&hl=en)

![image](https://github.com/user-attachments/assets/fa21f915-c5e5-4d12-90a9-c1918669414b)

[Playground UK](https://serpapi.com/playground?engine=google_product&product_id=14062548612077156581&location=United+Kingdom&google_domain=google.co.uk&gl=uk&hl=en)

![image](https://github.com/user-attachments/assets/db20e91f-57d8-4a0c-b9b8-d321642b89c2)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069976?view=List)

**Comment by Ovi** [comment]
The issue has been fixed

[Playground](https://serpapi.com/playground?engine=google_product&product_id=1945432764539993472&gl=us&hl=en)
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/ef050217-ba53-4f4b-ae9d-5c70929ab661">
