### ISSUE TITLE
[Google Search API] `knowledge_graph.people_also_search_for` Not Parsed Consistently

### ISSUE THREAD

**Issue by RedBillyOne** [serpapi/public-roadmap#1891]
Hi,

SerpAPI return parameter "places_sites" instead of "Knowledge_Graph" 

GOOD
For the block "Les internautes recherchent aussi" (cf. screenshot below) SerpAPI return a parameter "Knowledge_graph" (and it's fine)
https://serpapi.com/playground?q=Jeux+olympique&location=France&google_domain=google.fr&gl=fr&hl=fr&newPara=chips+&udm=14
![image](https://github.com/user-attachments/assets/7666f870-852a-4908-9ce7-cd53b17f94d6)

BAD (ERROR)
But SerpAPI return for the same block "Les internautes recherchent aussi" a parameter "Places_sites" in this case below
https://serpapi.com/playground?q=jo+2024&location=France&google_domain=google.fr&gl=fr&hl=fr&newPara=chips+&udm=14
![image](https://github.com/user-attachments/assets/4d1fee96-6646-453e-ad05-49a2f14141f5)

Is it possible to standardize the naming (put "knowledge_graph" in both cases)

Regards

**Comment by schaferyan** [comment]
Thanks for the issue @RedBillyOne ! Can you share the `search_metadata.id` for a the search where that block is parsed into `places_sites`?

When I open these Playground links on my side, it actually looks like both return the `knowledge_graph`, but the first example entirely misses parsing `les_internautes_recherchent_aussi`, whereas the second example parses it as a subsection of the `knowledge_graph`, in `knowledge_graph.les_internautes_recherchent_aussi`.

[With knowledge_graph.les_internautes_recherchent_aussi](https://serpapi.com/searches/66d5f0d518787db12199c520/inspect) | [Without knowledge_graph.les_internautes_recherchent_aussi](https://serpapi.com/searches/66d5f0d372f7166340778fc5/inspect)

**Comment by RedBillyOne** [comment]
Hi,

Danw, I can't reproduce this issue either (maybe it was a temporary error).

Regards


________________________________
De : Ryan Schafer ***@***.***>
Envoyé : lundi 2 septembre 2024 19:31
À : serpapi/public-roadmap ***@***.***>
Cc : RedBillyOne ***@***.***>; Mention ***@***.***>
Objet : Re: [serpapi/public-roadmap] [Google Search API] Places_sites instead of Knowledge_Graph (Issue #1891)


Thanks for the issue @RedBillyOne<https://github.com/RedBillyOne> ! Can you share the search_metadata.id for a the search where that block is parsed into places_sites?

When I open these Playground links on my side, it actually looks like both return the knowledge_graph, but the first example entirely misses parsing les_internautes_recherchent_aussi, whereas the second example parses it as a subsection of the knowledge_graph, in knowledge_graph.les_internautes_recherchent_aussi.

With knowledge_graph.les_internautes_recherchent_aussi<https://serpapi.com/searches/66d5f0d518787db12199c520/inspect> | Without knowledge_graph.les_internautes_recherchent_aussi<https://serpapi.com/searches/66d5f0d372f7166340778fc5/inspect>

**Comment by schaferyan** [comment]
Thanks @RedBillyOne! If you encounter it again, be sure to let us know.

Also, even if parsing that block into `places_sites` was a one time error, there is still some inconsistent parsing of this block, as it wasn't parsed at all in one of the searches I tried.

**Comment by schaferyan** [comment]
I've been able to reproduce the block being parsed sometimes into `places_sites` and sometimes into `knowledge_graph.people_also_search_for` with a search in English:

[Inspector (`knowledge_graph.people_also_search_for`)](https://serpapi.com/searches/66d6101348c429a60a9bf4dc/inspect) | [Inspector (`places_sites`)](https://serpapi.com/searches/66d60f62690121aebcd47351/inspect)

Inspector

**Comment by ocvit** [comment]
Fix has been released.

`knowledge_graph.people_also_search_for` is parsed correctly now. No misparsed `places_sites` as well.

<img width="1345" alt="Screenshot 2024-09-19 at 11 19 47" src="https://github.com/user-attachments/assets/9505efa9-41cf-4808-b49a-c0293f137fae">
