### ISSUE TITLE
[Google Shopping API] Google no longer seems to return nearby_shopping_results

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#1895]
In our Google Shopping Nearby Results API, we mention using the `nearby_shopping_results` response field to get the relevant nearby results. However, this field no longer appears in the response. 
<img width="1109" alt="Screenshot 2024-09-03 at 2 59 30 PM" src="https://github.com/user-attachments/assets/63fbe20e-d41b-4696-8d83-ff9ccc84dd3b">

Example playground search: https://serpapi.com/playground?engine=google_shopping&q=PS5&location=Abilene%2C+Texas%2C+United+States&gl=us&hl=en&tbs=local_avail%3A1&direct_link=true&no_cache=true
<img width="1261" alt="Screenshot 2024-09-03 at 2 55 00 PM" src="https://github.com/user-attachments/assets/530bb560-f427-4f1d-8234-9ea67bbd9e98">

Either we should update the documentation to reflect that the results are simply in the `shopping_results` part of the response, or perhaps we need to check if something has changed on Google's end with this parameter which requires us a fix on our end. 

Another thing I noticed is that Google seems to expect the keyword "Nearby" in the query to show results near the location provided. This may be related to this issue as well. The layout for this seems changed as well. We do not seem to be scraping the "Places" part of the page.

Example: https://serpapi.com/playground?engine=google_shopping&q=PS5+nearby&location=Abilene%2C+Texas%2C+United+States&gl=us&hl=en&tbs=local_avail%3A1&direct_link=true&no_cache=true

<img width="1291" alt="Screenshot 2024-09-03 at 2 57 25 PM" src="https://github.com/user-attachments/assets/a89a2aa9-d0da-4eaa-a873-bc56f9a29717">

**Comment by Ovi** [comment]
Google has introduced a new layout for [Google Shopping](https://serpapi.com/google-shopping-new-layout). As part of this update, the `nearby_shopping_results` feature has been deprecated. The rollout is underway, with some countries already using the new layout while others continue to rely on the previous version.

**Comment by Ovi** [comment]
Deprecation notice is now shown on the documentation page:

<img width="582" alt="image" src="https://github.com/user-attachments/assets/9e18659a-c306-41e0-bc05-2ced1f3d61a4" />
