### ISSUE TITLE
[Google Finance Markets API] Filter market trends by county

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1896]
While exploring our [Google Finance Markets](https://serpapi.com/google-finance-markets), I found out that the filter results are different based on search location.

Here is my default result (from Indonesia) - [link](https://www.google.com/finance/markets/gainers?hl=en)
![CleanShot 2024-09-04 at 06 18 01@2x](https://github.com/user-attachments/assets/5d953b9e-df63-497f-9b3a-fc65c699f3a4)

From America (using VPN) - [link](https://www.google.com/finance/markets/gainers?hl=en)
![CleanShot 2024-09-04 at 06 18 36@2x](https://github.com/user-attachments/assets/866eaaed-c5dd-4728-a3f8-531666a561f1)

Google Finance site supports region filters by using `gl` parameter, for example: https://www.google.com/finance/markets/gainers?hl=en&gl=es

We possibly can add a new parameter on our Google Finance Markets API.

**Comment by hilmanski** [comment]
A user reached out yesterday asking about the possibility of filtering stocks only for the Saudi Market. This might help.

[Front](https://app.frontapp.com/open/msg_2hhf0tjw?key=PMTvMAyqboxyj7h2kzjDGWIiS23yX3an)

**Comment by aciddjus** [comment]
We have added support for `gl` country parameter.

<img width="1452" alt="image" src="https://github.com/user-attachments/assets/e4ac26b7-3315-49c2-a5b4-2238af73caba">

----------

[Playground](https://serpapi.com/playground?engine=google_finance_markets&trend=gainers&gl=sa&no_cache=true)
