### ISSUE TITLE
[Google Finance API] Empty results for stocks with numerical ticker and setting `window` param

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1898]
While helping a customer with another issue, I noticed that if you try to set a date range for historical stock price data using the `window` param for a stock with a numerical ticker, the search comes back empty.

My first thought is it was a regional issue, but I've reproduced it across 3 stock markets that use numerical tickers. I've yet to find a letter-based ticker that reproduces the issue.

No `window` param set returns normally for stock `0005:HKG`

[Playground](https://serpapi.com/playground?engine=google_finance&q=0005%3AHKG)

![image](https://github.com/user-attachments/assets/7fed6add-0946-45e7-a932-3e12955837b3)

Setting `window` to `5D` breaks the search:

[Playground](https://serpapi.com/playground?engine=google_finance&q=0005%3AHKG&window=5D)

![image](https://github.com/user-attachments/assets/dea86b43-2827-4af7-add7-0169fb818779)

Filtering to `5D` on Google Finance works as expected:

[Actual Google Finance](https://www.google.com/finance/quote/0005:HKG?window=5D)

![image](https://github.com/user-attachments/assets/6d93b5d5-8759-4296-b8a5-dc2308dfdb81)

Here are some additional examples from stock markets in Saudi Arabia and Japan that use numerical stock tickers:

https://serpapi.com/playground?engine=google_finance&q=4142%3ATADAWUL
https://serpapi.com/playground?engine=google_finance&q=4142%3ATADAWUL&window=5D

https://serpapi.com/playground?engine=google_finance&q=7201%3ATYO&window=5D
https://serpapi.com/playground?engine=google_finance&q=7201%3ATYO

Finally for reference, stock markets with letter-based tickers continue to work fine with `window` set. I tried with stocks in the US, UK, Australia, and Italy. For example:

[Playground](https://serpapi.com/playground?engine=google_finance&q=RR%3ALON&window=5D)

![image](https://github.com/user-attachments/assets/88b85d5e-64c6-4d16-ae78-217fb2610f8f)

**Comment by schaferyan** [comment]
A customer reported this: 

[Front](https://app.frontapp.com/open/msg_2hk35bz0?key=PMTvMAyqboxyj7h2kzjDGWIiS23yX3an)

**Comment by aciddjus** [comment]
We have fixed this issue. Our Google Finance API will now return results for stocks with numerical values.

<img width="1501" alt="image" src="https://github.com/user-attachments/assets/e066b389-d6bb-4c78-9785-4e80c16365a6">
