### ISSUE TITLE
[Google Shopping API] Support `direct_link` for all `gl` values

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1900]
We currently only support the use of the `direct_link` if the `gl` parameter indicates a country where the new layout has been rolled out, and we've added support. If any other value is provided for `gl`, we return an error:  "Error: `direct_link` is not supported for selected `gl=dk` country."

Since we will be adding support for each country as Google switches to the new layout there, it would be easier for customers who use many different `gl` values if we can just ignore `direct_link` on our side in cases where it's not supported yet. This would prevent the customer from having to update their code each time we add support for the new layout and `direct_link` parameter in an additional country, as it would allow them to just have `direct_link` set to true for all countries.

<img width="1315" alt="Screenshot 2024-09-04 at 10 39 01 AM" src="https://github.com/user-attachments/assets/7856286e-730c-4584-970c-00d3893a5e0c">

A customer explicitly requested this:

[Front](https://app.frontapp.com/open/msg_2hjubazg?key=AW-GmJjmRlMmBGHe61Yi7Fqfr0lamoRM)

**Comment by tanys123** [comment]
We have made a new release that allow you to search with `direct_link` enabled for any country. With this, you aren't going to get error when you use `direct_link` for non-supported country and your searches will automatically include `link` when the country switches to new layout.

<img width="1462" alt="Screenshot 2024-09-06 at 1 46 37 PM" src="https://github.com/user-attachments/assets/669dbdb7-c557-4e90-8720-07df03d16739">
