### ISSUE TITLE
[Google Search API] local_results display `sponsored` text as title

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1903]
A customer reported that we display `sponsored` text as the title in one of our `local_results > places` response.

![CleanShot 2024-09-05 at 10 26 38](https://github.com/user-attachments/assets/46c87719-f9e2-4a77-9499-d75e35d842d4)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070052?view=List) | [Inspect](https://serpapi.com/searches/66d8d5b9544c49ef43197dea/inspect)

**Comment by Alaa-abdulridha** [comment]
This issue has been resolved,

Before fixing the issue (Production):
![image](https://github.com/user-attachments/assets/f4665e0d-bf34-4cdc-8dcd-2a1d0b266d10)



After fixing the issue (Production):

![image](https://github.com/user-attachments/assets/c624effc-bfac-42a5-b8ef-388254532f40)
