### ISSUE TITLE
[Apple Product API]  `information` is missing `address`, `telephone`, and `email` fields

### ISSUE THREAD

**Issue by chrstphrfrtn** [serpapi/public-roadmap#1906]
The below search with DE localization omits the `address`, `telephone`, and `email` fields from the `information` section.  All other fields on the page are returned properly except these three.
```
{
  "search_metadata": {
    "id": "66ddeb387e1d1f2a9bd617a2",
    "status": "Success",
    "json_endpoint": "https://serpapi.com/searches/cc90e1e87a70a234/66ddeb387e1d1f2a9bd617a2.json",
    "created_at": "2024-09-08 18:21:44 UTC",
    "processed_at": "2024-09-08 18:21:44 UTC",
    "apple_product_url": "https://apps.apple.com/de/app/id951937596",
    "raw_html_file": "https://serpapi.com/searches/cc90e1e87a70a234/66ddeb387e1d1f2a9bd617a2.html",
    "prettify_html_file": "https://serpapi.com/searches/cc90e1e87a70a234/66ddeb387e1d1f2a9bd617a2.prettify",
    "total_time_taken": 1.82
  },
```

Here is screenshot of the App Store pay displaying the missing fields:
![image](https://github.com/user-attachments/assets/672e2909-f09b-485b-8965-48682c85d840)

**Comment by hilmanski** [comment]
Thank you very much, @chrstphrfrtn, for your report. We'll investigate this and let you know once we have an update.

[Inspect](https://serpapi.com/searches/66ddeb387e1d1f2a9bd617a2/inspect)

**Comment by Ovi** [comment]
We now parse additional information:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/43994c3a-60e2-400b-a733-44180a45a256">

[Playground](https://serpapi.com/playground?engine=apple_product&product_id=951937596&type=app&country=de&no_cache=true)

**Comment by hilmanski** [comment]
Thank you very much, @Ovi.

Hi @chrstphrfrt, I'm tagging you for visibility. Thank you again for your report, and please let us know if you need anything else.

**Comment by chrstphrfrtn** [comment]
Thanks!!!
