### ISSUE TITLE
[UI][Documentation] The sidebar navigation is missing certain links

### ISSUE THREAD

**Issue by Krugloff** [serpapi/public-roadmap#1909]
After some time I can't quite understand where these links are coming from or why they're needed.

https://serpapi.com/google-local-services-queries
https://serpapi.com/google-local-services-job-types

![image](https://github.com/user-attachments/assets/e6602765-0e12-4c0b-8c20-37ea286977c9)
![image](https://github.com/user-attachments/assets/c2144f66-83b9-4e24-a676-6635f686455d)

**Comment by hilmanski** [comment]
They are needed for Google Local Services API: https://serpapi.com/google-local-services-api and can be accessed from the documentation.
