### ISSUE TITLE
The sidebar navigation scrolls to the top

### ISSUE THREAD

**Issue by Krugloff** [serpapi/public-roadmap#1910]
The sidebar navigation scrolls to the top on each page, requiring you to manually scroll down to the next section.

https://serpapi.com/search-api

![scroll](https://github.com/user-attachments/assets/809ad6fa-09dc-4d5e-8eae-5dc962f45ac0)

**Comment by hilmanski** [comment]
Duplication of https://github.com/serpapi/SerpApi/issues/4143
