### ISSUE TITLE
[UI][Root Page] The test search will fail for accounts with an unverified phone number

### ISSUE THREAD

**Issue by Krugloff** [serpapi/public-roadmap#1911]
The test search will fail if you're signed in with a confirmed email but an unverified phone number.

![Monosnap screencast 2024-09-03 23-33-54](https://github.com/user-attachments/assets/4fda34b0-fb11-4c66-a936-d9fc09456e6c)

**Comment by hartator** [comment]
Is the error correct though?

**Comment by Krugloff** [comment]
> Just saw your recording, took a minute to load. This is our intended behavior as before it's using ReCaptcha to block you for making too many searches.

@hartator Sorry, I’ll try to find something better than GIFs.

I don’t think it’s correct flow that signed-in users (even with unverified phone numbers) have fewer privileges than random guests. In my view, the experience (on this page) should be consistent for all users, regardless of their sign-in status.

It might improve once issue https://github.com/serpapi/public-roadmap/issues/1912 is resolved
