### ISSUE TITLE
[UI][Xray] The X-ray feature is a cool addition, but it occasionally fails to work without any obvious reason.

### ISSUE THREAD

**Issue by Krugloff** [serpapi/public-roadmap#1915]
I really like the X-ray feature; it’s a cool, impressive addition that’s quite comfortable to use. Unfortunately, it sometimes doesn’t work as expected or doesn't work altogether, which can turn it from a "wow" feature into a "broken cool thing.

+ The YouTube playground lacks any "xrays".
https://serpapi.com/playground?engine=youtube&search_query=Coffee

+ I can "xray" on the "title" and "snippet," but not on the "favicon" or "link."
https://serpapi.com/playground?engine=duckduckgo&q=Apple&kl=us-en
![image](https://github.com/user-attachments/assets/58c4aadd-087a-4b4e-92a9-d83d862cde93)

+ The border is only visible around the icon, but I expected it to encompass the entire link.
https://serpapi.com/playground?engine=yahoo&p=Coffee
![image](https://github.com/user-attachments/assets/86b3f354-a3bb-4249-a7bf-1426bff49634)

**Comment by hartator** [comment]
We can break down this one even further to one issue per X-Ray not working issue.
