### ISSUE TITLE
[Yahoo Search API] There's an answer box that hasn’t been scraped.

### ISSUE THREAD

**Issue by Krugloff** [serpapi/public-roadmap#1918]
[Playground](https://serpapi.com/playground?engine=yahoo&p=Richard+Feynman+date+of+birth)

<img width="1453" alt="Screenshot 2024-09-09 at 17 00 17" src="https://github.com/user-attachments/assets/f10c0e97-2f4c-49bb-9a80-e04f5b32d56b">

Related #796

**Comment by Ovi** [comment]
We now scrape this answer box:

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/7efd412f-154f-4e15-a430-c6b508774f05" />

[Playground](https://serpapi.com/playground?engine=yahoo&p=Richard+Feynman+date+of+birth)
