### ISSUE TITLE
[Google Maps Reviews API] Change default reviews returned from 10 to 8

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#1924]
Google Maps is now returning 8 reviews by default in the initial query instead of 10. This was reported by a potential customer and I've reproduced it with a few queries.

[Playground](https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x89c259aa4c38ca75%3A0x88ca3d6ff537d876&hl=en)

![image](https://github.com/user-attachments/assets/1994b2f4-beab-437c-9113-d99e065074d7)

[Documentation](https://serpapi.com/google-maps-reviews-api#api-parameters-pagination-num)

![image](https://github.com/user-attachments/assets/b0291cfe-a774-4e02-aed3-abb9279f3a59)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070087?view=List)

Related: https://github.com/serpapi/public-roadmap/issues/1590

**Comment by marm123** [comment]
I just tested it on around ~60 different businesses and can confirm that the first page always returns 8 results, and the second page returns 10 results if no `num` parameter is used. It's important to note in the documentation to make sure we don't update it in a way that indicates that every page returns 8 results by default, as it's the case only with the first one.

**Comment by Krugloff** [comment]
The [documentation](https://serpapi.com/google-maps-reviews-api#api-parameters-pagination-num) has been updated.

<img width="913" alt="image" src="https://github.com/user-attachments/assets/fe281fef-a778-428f-b306-4e0c84ef32fc">
