### ISSUE TITLE
[Google Product API] Product results returns inccorrect review count and rating

### ISSUE THREAD

**Issue by ctg5** [serpapi/public-roadmap#1926]
In some instances, the google shopping engine returns ratings/reviews for products even when those products don't have any reviews. It looks like in these instances, you're pulling the first review from the related products and dropping it in as the review for the main product. 

![Product Ratings Issue](https://github.com/user-attachments/assets/9fad6a2f-85d4-4b6e-9720-6a5fbc8b3f48)

I now have a database with maybe hundreds (hopefully not thousands) of erroneous data points. Yikes! 

Let me know if you need more examples. I suspect I can find them. 

Thanks!

**Comment by NateSkiles** [comment]
@ctg5 Thank you for bringing this to our attention!

I tested this a bit further, it appears that for products without reviews, review count and rating are pulled from the first `related_products` element.

![image](https://github.com/user-attachments/assets/fdc0647c-9c04-4805-bf5a-ac4f778c8053)

Playground Example:
* https://serpapi.com/playground?engine=google_product&product_id=16684109691328811459&gl=us&hl=en
* https://serpapi.com/playground?engine=google_product&product_id=14238502641929934915&gl=us&hl=en

If reviews do exist on the product, the correct rating is scraped:
![image](https://github.com/user-attachments/assets/4b570ed0-a891-435d-9513-fc9c8017fe1a)

**Comment by NateSkiles** [comment]
This is a duplicate issue, please see: #1890

**Comment by NateSkiles** [comment]
@ctg5 I wanted to follow up and let you know that this issue has been resolved, in case you missed it in the original issue.

Please let us know if you have any questions!
