### ISSUE TITLE
[Accounts] Filtering by minute not working with the `start` and `end` date parameters in the `API Absolute Numbers` report

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1929]
A high-volume customer requested to be able to filter the `API Absolute Numbers` report to get the actual number of searches within a specific billing period. However, providing a minute value with the `start` and `end` date parameters in the `API Absolute Numbers` report doesn't seem to be working:

`start=2024-09-10 12:00` & `end=2024-09-10`

<img width="1425" alt="image" src="https://github.com/user-attachments/assets/d446ee93-c875-437d-8257-53bb56e4cf86">

[API Absolute Numbers](https://serpapi.com/searches/reports?start=2024-09-10%2012:00&end=2024-09-10)

`start=2024-09-10 12:01` & `end=2024-09-10`

<img width="1436" alt="image" src="https://github.com/user-attachments/assets/a4adc8b3-ac91-483f-885c-a2bffb305c54">

[API Absolute Numbers](https://serpapi.com/searches/reports?start=2024-09-10%2012:01&end=2024-09-10)

All of the searches above were executed between `2024-09-10 12:37:15 UTC` and `2024-09-10 12:57:53 UTC`:

[Search 1](https://serpapi.com/searches/66e03d7bfc40bf7517a63621/inspect) | [Search 2](https://serpapi.com/searches/66e03d85740bdb12e4e931bf/inspect) | [Search 3](https://serpapi.com/searches/66e041c15f9778bb597e2fc3/inspect) | [Search 4](https://serpapi.com/searches/66e041dae1d1ad9ccd6ba1f5/inspect) | [Search 5](https://serpapi.com/searches/66e042513c863d370025361b/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070189?view=List)

**Comment by hartator** [comment]
This is not something we plan to support.
