### ISSUE TITLE
[Yelp Search API] All Searches Timing Out and/or Failing

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#1938]
All searches via our Yelp API currently seems to be timing out and/or failing.

<img width="950" alt="Screenshot 2024-09-11 at 3 48 53 PM" src="https://github.com/user-attachments/assets/41a5ada5-d388-4f7f-b401-ac92a7d664f7">

A customer reported this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070247?view=List)

**Comment by NateSkiles** [comment]
Another user reached out reporting this issue:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070302?view=List)

**Comment by mlemberg-hfs** [comment]
we are stilling have this issue as well, is somebody going to look at fixing it? The API uptime is 88% now...the yelp search is half the reason we are subscribed

**Comment by tanys123** [comment]
@mlemberg-hfs Sorry for the issue, we are already looking into it. Yelp implemented DataDome into their search endpoint, which might require us to have substantial changes to how we retrieve the data. We are actively working on a viable solution and will update you once we find a fix.

**Comment by tanys123** [comment]
We have deployed a potential fix to Yelp API. For the past 2 hours, searches have been successfully returning results. However, it looks like Yelp has been adding layers of validations to traffics, so we are not sure if the solution will stick. We will continue to monitor the situation closely.

<img width="1114" alt="Screenshot 2024-09-17 at 11 15 05 AM" src="https://github.com/user-attachments/assets/bc4c03fe-3cd5-4892-b431-a4b9ea73edb8">

**Comment by tanys123** [comment]
Closing this, we have seen stable performance so far.

<img width="1108" alt="Screenshot 2024-10-11 at 2 44 42 PM" src="https://github.com/user-attachments/assets/c49f51bb-ed2d-4614-b8be-d12c2d83a273">
