### ISSUE TITLE
[eBay Domains] Switch the country name and ebay domain  label

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1939]
A user reported that the `country` and the `ebay domain` labels are misplaced on the table.

[Ebay Domains page](https://serpapi.com/ebay-domains)
![CleanShot 2024-09-12 at 10 15 37](https://github.com/user-attachments/assets/3388d5ae-a510-48c8-8756-87170aa81de4)

[Front](https://app.frontapp.com/open/cnv_1czm2y58?key=4ad1z_HVu6xiuCnHJr_zA1YSGnd2mwH2)

**Comment by aciddjus** [comment]
Thanks, @hilmanski 👍 
Don't forget to follow steps 12. and 13. from [wiki](https://github.com/serpapi/SerpApi?tab=readme-ov-file#contributing-and-deploying).

**Comment by hilmanski** [comment]
Thank you @aciddjus for the reminder.

The labels are now in the correct order:
![CleanShot 2024-10-02 at 09 40 11](https://github.com/user-attachments/assets/3dc16410-f927-4177-a74c-376f7e5fe5be)
