### ISSUE TITLE
[Google Search API] Answer Box is not scraping images

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#194]
![thumbnails_in_answer_box](https://user-images.githubusercontent.com/73674035/176101492-8aa32b49-c5d9-432d-bc8e-c62d491b081d.png)

[Playground](https://serpapi.com/playground?q=who+is+napoleon+bonaparte%3F+wikipedia&location=United+States&gl=us&hl=en&no_cache=true&newPara=stick+highlight+lr+async+as_qdr)
[Inspect](https://serpapi.com/searches/62ba935a1baebb8acc799d39/inspect)

**Comment by dimitryzub** [comment]
@kagermanov27 Interesting. On my part the results are being parsed correctly after following the URL you provided or it's not correct?

Example: 

![image](https://user-images.githubusercontent.com/78694043/178480048-6d75d97f-d0a9-45d4-8c0f-19b00553114f.png)

**Comment by aciddjus** [comment]
The issue is that those should not be extracted as `inline_images` but as part of the `answer_box`, I think.

**Comment by dimitryzub** [comment]
@aciddjus Got it, makes sense 👍
