### ISSUE TITLE
[Google Short Videos API] `short_videos` not being parsed

### ISSUE THREAD

**Issue by Ovi** [serpapi/public-roadmap#1942]
Most of the times `short_videos` are not being parsed.

<img width="1414" alt="image" src="https://github.com/user-attachments/assets/93cd07f4-52c2-4946-92d2-0e2a1a400191">

[Inspect - Successful](https://serpapi.com/searches/66e2d7e06ad3c9c280e4d6bf/inspect)

---

<img width="1412" alt="image" src="https://github.com/user-attachments/assets/903ac191-0221-429b-a90d-5c89730c7071">

[Inspect - Failed](https://serpapi.com/searches/66e2d77a3585391ff9123a2e/inspect)

[Playground](https://serpapi.com/playground?q=energy+drink+videos&location=Houston%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com)

**Comment by btaunt** [comment]
We now parse these additional mobile layouts for `short_videos`:

<img width="844" alt="Screenshot 2024-09-20 at 9 47 54 AM" src="https://github.com/user-attachments/assets/13683b75-8d46-4205-af56-77392b59120e">

---

[Playground](https://serpapi.com/playground?q=energy+drink+videos&location=Houston%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client+votes+site+ie+oe+pws+ibp+source+ijn+rlz)
