### ISSUE TITLE
[Google Maps API] Booking Options are not scraped

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#1943]
A customer reached out that Booking Options are not scraped with the Google Maps API.
<img width="533" alt="image (2)" src="https://github.com/user-attachments/assets/8f74812c-6184-4bbc-8195-d3d2af629e61">

<img width="548" alt="image (1)" src="https://github.com/user-attachments/assets/37f2fbc1-d15a-4b1e-ac45-4fc0b9e4ec96">

[Playground link 1 - google search](https://serpapi.com/playground?q=Big+Bus+tours+london&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&newPara=chips+highlight+stick+lr+as_qdr)
[Playground link 2 - google maps search](https://serpapi.com/playground?engine=google_maps&q=Big+Bus+tours+london&hl=en&type=search)
[Playground link 3 - place_id search](https://serpapi.com/playground?engine=google_maps&q=Big+Bus+tours+london&hl=en&place_id=ChIJDQR-DiEFdkgRArsxMCL5YCc&type=search)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070273?view=List)

**Comment by Alaa-abdulridha** [comment]
This issue now has been resolved:

Before resolving it ( google search ):

![image](https://github.com/user-attachments/assets/5e685efb-54f6-4820-baf5-6122eabe5bbf)


After resolving it ( google search ):

![image](https://github.com/user-attachments/assets/7a862f80-a93a-4093-9c2b-d916101b2eec)

---

Before resolving it ( Google Maps ):
![image](https://github.com/user-attachments/assets/e3dbb719-a263-4760-b47c-67cf8e5d20fa)


After resolving it ( Google Maps ):

![image](https://github.com/user-attachments/assets/25cad91c-e8a7-47f1-965b-78bdd36695ff)
