### ISSUE TITLE
[Walmart Product API] Searches produce Internal Server Error [500]

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1944]
One of our high-volume customers reported that they are getting Internal Sever Error for searches with Walmart Product API. I was able to recreate the issue with all `product_ids` I tested:

<img width="1669" alt="image" src="https://github.com/user-attachments/assets/2b95bba8-a4f3-4f32-9bf4-0d5219266c79">

[Playground](https://serpapi.com/playground?engine=walmart_product&product_id=5AAZEXRE9SFK) | [Playground](https://serpapi.com/playground?engine=walmart_product&product_id=10306807)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070286?view=List)

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070291?view=List)

**Comment by martin-serpapi** [comment]
Searches with `500 - Internal Server Error` are marked as successful and are deducted from the search credits quota:

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/71b8d31b-38bd-4dc7-8af7-7a1465e4c971">

![image](https://github.com/user-attachments/assets/37c034b7-07f6-4f0f-b036-44b2f60f91b9)

[Inspector](https://serpapi.com/searches/66e464ac707fd3b99c3d2071/inspect)

**Comment by marm123** [comment]
Another high-volume customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070426?view=List)

**Comment by tanys123** [comment]
We have deployed a fix for the issue. The issue should now be resolved.

The search provided is now returning results.
<img width="1374" alt="Screenshot 2024-09-20 at 10 41 47 AM" src="https://github.com/user-attachments/assets/d8b0b86d-0954-401c-ae78-51b0015f9634">
