### ISSUE TITLE
[Google Search API] AI Overview references position

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1951]
A user asked if the references index matched the position of the order of the actual result.

Upon testing, I can see it's unclear whether the `references` are in order.
![CleanShot 2024-09-16 at 06 51 56](https://github.com/user-attachments/assets/b8437365-b221-40e7-8613-1c3ea8e7daee)

For this sample [inspect](https://serpapi.com/searches/66e7642f7658574ac41cd500/inspect), the top two website results we see on the result are placed at the 7th and 8th ranking. 

I think this is important for some customers who want to see the top-ranking website in the AI overview for specific keywords.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070000?view=List)

**Comment by zyc9012** [comment]
We've released the fix for this. The reference order is identical to the ones displayed in the HTML.

![image](https://github.com/user-attachments/assets/4d11ca88-b693-4a17-9d4f-5294b59b5baf)
