### ISSUE TITLE
[Google Maps API] Get individual Review results page

### ISSUE THREAD

**Issue by spirie** [serpapi/public-roadmap#1952]
Hi

Please could you make it possible to get the review detail from a specific review?

Example: 

https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1sChZDSUhNMG9nS0VJQ0FnSUREanY3alR3EAE!2m1!1s0x0:0x860ff2724888ac7e!3m1!1s2@1:CIHM0ogKEICAgIDDjv7jTw%7CCgwI3tnUsAYQiPrPiwM%7C?entry=tts&g_ep=EgoyMDI0MDkxMS4wKgBIAVAD

**Comment by marm123** [comment]
Hi @spirie! Thanks for opening the issue. You can already get all the details included on the page you shared with our [Google Maps Reviews API](https://serpapi.com/google-maps-reviews-api). Additionally, you can also get a list of individual reviews posted by a specific person with our [Google Maps Contributor Reviews API](https://serpapi.com/google-maps-contributor-reviews-api).

Can you specify what additional information you'd need from the page you shared that is unavailable through our Google Maps Reviews API or your use case for such API?

**Comment by spirie** [comment]
Hi @marm123 

You're totally right here. I was trying to find out which reviews were no longer active so I can mark them in my system. I have found a way to do it now - we already get all reviews for a profile, so it works to remove those it can no longer find.
