### ISSUE TITLE
[Ebay Search API] Add support for `List` layout view

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#1953]
A high-volume customer requested that we provide `seller` information in the response. For some searches, a grid view is returned in the response and the seller information is not available:

![image](https://github.com/user-attachments/assets/8de1d5c1-aa3f-4313-bcd8-e40bc36353c7)

[Playground](https://serpapi.com/playground?engine=ebay&_nkw=adidas) | [Inspect](https://serpapi.com/searches/66e8592bc1c8dd64d7008f3d/inspect)

When the results are displayed in a `List` view, the `seller` information is available:

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/bfb3093a-3c07-473a-bbd6-b57028508a15">

[eBay](https://www.ebay.com/sch/i.html?_nkw=adidas&_dmd=1&rt=nc)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070337?view=List)

**Comment by btaunt** [comment]
We now support a new parameter to set the view format (`_dmd`)

<img width="329" alt="Screenshot 2024-09-20 at 11 48 44 AM" src="https://github.com/user-attachments/assets/9671887d-0b80-4602-b580-45850ed94f17">
<img width="506" alt="Screenshot 2024-09-20 at 11 49 00 AM" src="https://github.com/user-attachments/assets/e4cb0aa1-1e28-4859-be6e-d94f967c7765">

---

[Playground (List)](https://serpapi.com/playground?engine=ebay&_nkw=ps1+classic&_dmd=1&no_cache=true) | [Playground (Grid)](https://serpapi.com/playground?engine=ebay&_nkw=ps1+classic&_dmd=2&no_cache=true)
