### ISSUE TITLE
[Google Shopping API] Return actual link in `inline_shopping_results`

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#1954]
A customer requested we return the link directly to the product's website for items listed in the `inline_shopping_results`.

Currently, we only return the Google tracking link:
<img width="1652" alt="image" src="https://github.com/user-attachments/assets/09e48099-e689-4d5f-932b-8da6c4a5a623">

These typically begin: `https://www.google.com/aclk?...`

Looking at the HTML of the Google Shopping Page, it looks like the link to the product's website is included, but we are only scraping the tracking link:

<img width="1548" alt="image" src="https://github.com/user-attachments/assets/99037a76-c83f-4d29-b37e-69258dd15755">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069664?view=List)

**Comment by zyc9012** [comment]
We've released a fix for this. Now we scrape direct links for desktop searches.

![image](https://github.com/user-attachments/assets/c92e84a5-73be-43b3-aa64-a2441f47ac39)
