### ISSUE TITLE
[Google Shopping API] Amazon source_icon link is not valid

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1955]
A potential customer reported that the link on `source_icon` is not valid. It looks like it only happened to the Amazon icons that has `.gif` extension.

Related to: https://github.com/serpapi/public-roadmap/issues/1847
[Inspect](https://serpapi.com/searches/66e8efd8be324fda43d0485e/inspect) | [Front](https://app.frontapp.com/open/cnv_1bznnrrw?key=nkOQCsxu1rzzG1xmcwEJ1aUMzmlP285H)

**Comment by zyc9012** [comment]
The icon currently scraped is a placeholder. Real image data is inside javascript.

**Comment by sonika-serpapi** [comment]
More details on this from the same potential customer: They noticed invalid urls for the `source_icon` for many other brands. Pretty much anytime this url ends with a .gif it's guaranteed to be an invalid url. They have noticed this issue happening for Target, Walmart and Carhart. And they think that there's many other stores affected as well. Sometimes the url for these stores ends in a .png and those urls are valid.

**Comment by hilmanski** [comment]
I'm unsure if this is related, but upon checking the Google Jobs thumbnail issue https://github.com/serpapi/public-roadmap/issues/1810 , I noticed that the unavailable images are also in .gif format.

**Comment by zyc9012** [comment]
We've released a fix for this. Now icons are in correct format.

![image](https://github.com/user-attachments/assets/4e214b09-e939-4f62-9aca-0de87792d487)

![image](https://github.com/user-attachments/assets/bc67b177-7704-482b-bb2c-244a20ec07d5)
