### ISSUE TITLE
[Yahoo Search API] Parse "Flight" answer box

### ISSUE THREAD

**Issue by Ovi** [serpapi/public-roadmap#1956]
We currently do not scrape "flight" answer box

<img width="903" alt="Screenshot 2024-09-17 at 3 40 10 PM" src="https://github.com/user-attachments/assets/74c9a262-5f54-45c6-8d18-537b279cf8a1">

[Playground](https://serpapi.com/playground?engine=yahoo&p=UA160&device=desktop&no_cache=true)

**Comment by dsojevic** [comment]
We now parse the Flight Status answer box:
<img width="941" alt="image" src="https://github.com/user-attachments/assets/89919ce5-23b0-4ce3-802c-9db13bde1a16">
