### ISSUE TITLE
[DuckDuckGo API] I can X-Ray on the "title" and "snippet," but not on the "favicon" or "link"

### ISSUE THREAD

**Issue by Krugloff** [serpapi/public-roadmap#1962]
https://serpapi.com/playground?engine=duckduckgo&q=Apple&kl=us-en

![image](https://github.com/user-attachments/assets/20068260-569b-48b7-964f-a35913ff7298)

**Comment by dsojevic** [comment]
We now appropriately mark the elements for "favicon" and "link" in the x-ray:
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/1aaa1e1c-d433-42b9-8be9-5bb453396037">
