### ISSUE TITLE
[Yahoo API] The X-Ray border is only visible around the icon

### ISSUE THREAD

**Issue by Krugloff** [serpapi/public-roadmap#1963]
I expected it to encompass the entire link.

https://serpapi.com/playground?engine=yahoo&p=Coffee

![image](https://github.com/user-attachments/assets/02104cf6-3e22-4737-9c55-1999e8158e12)

**Comment by dsojevic** [comment]
The x-ray now encompasses the full button for the links.

![image](https://github.com/user-attachments/assets/6b4204c6-fe94-4c59-83ab-74c874d5db37)
