### ISSUE TITLE
[Google Search API] Organic result that contains video is not parse

### ISSUE THREAD

**Issue by tanys123** [serpapi/public-roadmap#1970]
Organic result with video is not parse on mobile.

<img width="1299" alt="Screenshot 2024-09-20 at 9 42 51 AM" src="https://github.com/user-attachments/assets/b88e57fb-16df-4778-bbff-5e669f990791">

[Playground](https://serpapi.com/playground?q=how+are+school+capital+budgets+funded&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&filter=0&device=mobile&no_cache=true&newPara=chips+highlight+stick+lr+as_qdr+as_qdr%2525255C+as_qdr%25255C+as_qdr%252525255C+as_qdr%255C) | [Inspect](https://serpapi.com/searches/66ecd3dc5a461af347d7978f/inspect)

**Comment by Ovi** [comment]
We now parse results which contain videos:
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/55aabec7-5397-40f3-9a85-2baea4b00365">

[Playground](https://serpapi.com/playground?q=how+are+school+capital+budgets+funded&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&filter=0&device=mobile&no_cache=true)
