### ISSUE TITLE
[Google Short Videos API] `short_videos` are being parsed incorrectly

### ISSUE THREAD

**Issue by Ovi** [serpapi/public-roadmap#1971]
Latest post section is being parsed as `short_videos`

Related to #1942

<img width="1728" alt="Screenshot 2024-09-20 at 8 12 44 PM" src="https://github.com/user-attachments/assets/0de5fcc6-1bf4-4d60-ad77-0fc1242be91d">

[Playground](https://serpapi.com/playground?q=khaby&location=Houston%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com) | [Inspect](https://serpapi.com/searches/66ed9060c97e35852e9efc97/inspect)

[Another Inspect](https://serpapi.com/searches/66e2d77a3585391ff9123a2e/inspect)

**Comment by btaunt** [comment]
We no longer parse sections containing items such as `latest_posts` under `short_videos`.

[Playground](https://serpapi.com/playground?q=khaby&location=Houston%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=as_sitesearch+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client+votes+site+ie+oe+pws+ibp+source+rlz+ijn)
