### ISSUE TITLE
[Google Finance API] Missing `graph` result for stock market indices

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1975]
A customer reported that that `graph` information is missing when using Google Finance API. I'm able to replicate this on our playground.

[Front](https://app.frontapp.com/open/cnv_1cn6rzoc?key=PMTvMAyqboxyj7h2kzjDGWIiS23yX3an) | [Inspect](https://serpapi.com/searches/66f0c396b7d31d5eb316f79b/inspect) | [Playground](https://serpapi.com/playground?engine=google_finance&q=.DJI%3AINDEXDJX)

Upon investigating, I noticed a pattern where the `graph` is missing when using a ticker name with a dot sign or just the fact that they are `major stock market indices`, which may be using a different layout name somewhere in the HTML.

- [.IXIC:INDEXNASDAQ](https://serpapi.com/playground?engine=google_finance&q=.IXIC%3AINDEXNASDAQ)
- [S&P 500](https://serpapi.com/playground?engine=google_finance&q=.INX%3AINDEXSP)

**Comment by tanys123** [comment]
We have deployed a fix for the issue. Graph is return for the given example.
<img width="1267" alt="Screenshot 2024-09-24 at 10 25 35 AM" src="https://github.com/user-attachments/assets/4b6b7767-3d35-44f4-85fa-94a28aa1ea3e">
