### ISSUE TITLE
[Google Search API] Places sites result is not correct

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#1978]
In a new Google response layout, we scrape wrong places_sites node.

![Screenshot 2024-09-23 at 21 14 46](https://github.com/user-attachments/assets/1120e899-f43d-44a0-8727-97fcae4e1295)

[Playground](https://serpapi.com/playground?q=Elon+Musk&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&google_domain=google.com&newPara=as_sitesearch+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client+votes+site+ie+oe+pws+ibp+source+rlz+ijn) | [elon_musk.html](https://github.com/user-attachments/files/17098916/elon_musk.html.zip)

**Comment by btaunt** [comment]
As I mentioned in https://github.com/serpapi/SerpApi/pull/5296, I believe this will be indirectly fixed with https://github.com/serpapi/SerpApi/pull/5295 (@andypple83 )

**Comment by btaunt** [comment]
This now seems to be resolved with your latest changes here: https://github.com/serpapi/SerpApi/pull/5295 (testing directly against the `elon_musk.html` file provided) cc. @andypple83
