### ISSUE TITLE
[Documentation] Google Answer Box `people_also_search_for` key is not documented

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#198]
![pasf](https://user-images.githubusercontent.com/73674035/176114991-bc7ef2c5-f032-4913-98a8-0bbe159bafcc.png)

[Playground](https://serpapi.com/playground?q=Who+is+the+president+of+Ukraine%3F&gl=us&hl=en&device=desktop&no_cache=true&newPara=stick+highlight+lr+async+as_qdr)
[Inspect](https://serpapi.com/searches/62baa7a6f26ac626113e18ac/inspect)

**Comment by aciddjus** [comment]
This issue has been resolved.

<img width="1362" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/5a7e0740-704c-4278-9b25-6f941c4cabdd">

----------------

[Playground](https://serpapi.com/playground?q=Who+is+the+president+of+Ukraine%3F&gl=us&hl=en&device=desktop&no_cache=true)

Resolved in: https://github.com/serpapi/SerpApi/pull/2584
