### ISSUE TITLE
[Google Search API] `rich_snippet` no longer contains correct `detected_extensions`

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#1980]
A user reported that since the last few days `rich_snippet` is no longer scraped correctly - specifically, `detected_extensions` misses the rating and reviews (which is available now in a different format in the snippet displayed on google).

I investigated this, and found that the format has changed:
**Past**: 
<img width="322" alt="Screenshot 2024-09-23 at 10 49 36 AM" src="https://github.com/user-attachments/assets/8f2d0ae0-92ef-45cf-8b09-88869d4a2d01">

Scraped as:
<img width="535" alt="Screenshot 2024-09-23 at 10 44 52 AM" src="https://github.com/user-attachments/assets/ef82f1ec-9ebe-48dc-85a7-8618e88c47c6">

**Current**: 
<img width="298" alt="Screenshot 2024-09-23 at 10 49 43 AM" src="https://github.com/user-attachments/assets/4947b722-389f-4be2-943b-8be61cc5d299">

Scraped as:
<img width="546" alt="Screenshot 2024-09-23 at 10 45 10 AM" src="https://github.com/user-attachments/assets/777b8ce2-b9c4-4753-be66-fe3a02dcefef">

[Inspect - Old Format](https://serpapi.com/searches/66e8c683cc2987bf589bfcf0/inspect)
[Inspect - New Format](https://serpapi.com/searches/66f0af83e9245611686f5ac0/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070552?view=List)

**Comment by sonika-serpapi** [comment]
A high volume customer reached out about this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071069?view=List)

**Comment by hilmanski** [comment]
The customer reached out again asking about this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/unassigned/conversation/102910000071469?view=List)

**Comment by tanys123** [comment]
We have deploy a fix to the issue, it is now returning `rating` and `reviews` and `price_range` when available.

<img width="1161" alt="Screenshot 2024-10-25 at 12 42 44 PM" src="https://github.com/user-attachments/assets/a1051ca7-2ad6-4810-a1db-b3673a99f850">
