### ISSUE TITLE
[Google Search API] Add support for "Find results on"

### ISSUE THREAD

**Issue by spirie** [serpapi/public-roadmap#1985]
Looking fro support to be added for the "Find results on" box one some queries in a Google Search. 

The current Google Search API doesnt parse this box at the moment

Example playground:
https://serpapi.com/playground?q=Cleaner+Edinburgh&location=Edinburgh%2C+Scotland%2C+United+Kingdom&google_domain=google.co.uk&gl=uk&hl=en

Box in question:
![Screenshot 2024-09-24 170607](https://github.com/user-attachments/assets/9a00054b-a726-4374-a842-5d67dd3ccd12)

**Comment by NateSkiles** [comment]
Thanks @spirie! We'll look into this further.

**Comment by btaunt** [comment]
We now parse the `find_results_on` content in the Google Search API:

<img width="920" alt="Screenshot 2024-09-27 at 9 32 24 AM" src="https://github.com/user-attachments/assets/41963738-5376-421d-9e06-a0eec425ebf9">

---

[Playground](https://serpapi.com/playground?q=Cleaner+Edinburgh&location=Edinburgh%2C+Scotland%2C+United+Kingdom&google_domain=google.co.uk&gl=uk&hl=en&google_domain=google.co.uk&newPara=chips+as_sitesearch+votes+site+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+rlz+ijn) | [Documentation](https://serpapi.com/find-results-on)

**Comment by sonika-serpapi** [comment]
@spirie I'm tagging you for visibility. Thank you again for your report, and please let us know if you need anything else.

**Comment by spirie** [comment]
> @spirie I'm tagging you for visibility. Thank you again for your report, and please let us know if you need anything else.

Thanks! I will give it a go!
