### ISSUE TITLE
[Google AI Overview API] No AI Overview generated sporadically

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#1990]
A couple customers reached out on #1622 reporting queries that had previously returned AI Overviews are now returning an error:

```json
"ai_overview": {
    "error": "Can't generate an AI overview right now. Try again later."
},
```

![image](https://github.com/user-attachments/assets/d7f9c7fc-f4de-43db-b610-44834d4f32e5)

This query returns an AI Overview in Google:

![image](https://github.com/user-attachments/assets/47519647-3bf7-4518-9999-4365883ba960)

[Google Search](https://www.google.com/search?q=How+does+the+Fast+Food+company+Wendy%27s+excel+on+vegetarian+options+in+United+States%3F&sca_esv=5ac10ce223656a07&sca_upv=1&sxsrf=ADLYWIJ2dHxHTYQyGSarc53YbO4Th80GGA%3A1727299157041&source=hp&ei=VX70Zj6eyZDyD6KegJgO&iflsig=AL9hbdgAAAAAZvSMZRS_GrGDqKiMRjyGE4RSJje_-dNS&ved=0ahUKEwj-_rHlgt-IAxWeJEQIHSIPAOMQ4dUDCBc&uact=5&oq=How+does+the+Fast+Food+company+Wendy%27s+excel+on+vegetarian+options+in+United+States%3F&gs_lp=Egdnd3Mtd2l6IlRIb3cgZG9lcyB0aGUgRmFzdCBGb29kIGNvbXBhbnkgV2VuZHkncyBleGNlbCBvbiB2ZWdldGFyaWFuIG9wdGlvbnMgaW4gVW5pdGVkIFN0YXRlcz9IAFAAWABwAHgAkAEAmAEAoAEAqgEAuAEDyAEA-AEC-AEBmAIAoAIAmAMAkgcAoAcA&sclient=gws-wiz)

This only appears to be affecting specific queries, as `q=drop+shipping` still works ([playground](https://serpapi.com/playground?q=drop+shipping&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true&newPara=chips)):

![image](https://github.com/user-attachments/assets/ae0501e1-039c-4462-aea0-82ccef4604e4)

[Playground 1](https://serpapi.com/playground?q=How+does+the+Fast+Food+company+Wendys+excel+on+vegetarian+options+in+United+States%3F&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&newPara=chips) | [Playground 2](https://serpapi.com/playground?q=How+does+the+Sportswear+company+Nike+fall+short+on+sneaker+in+United+States%3F&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&newPara=chips) | [Documentation](https://serpapi.com/ai-overview)

[Search Inspect 1](https://serpapi.com/searches/66f47e1529e6fb0303b53769/inspect) | [Search Inspect 2](https://serpapi.com/searches/66f47b467ebde5ce2f40125c/inspect)

**Comment by sonika-serpapi** [comment]
A potential customer reached out about this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071367?view=List)

**Comment by zyc9012** [comment]
We've implemented a standalone engine for this case. Instead of returning an error, we now return `page_token` and `serpapi_link` for fetching the AI Overview result. For example.

```
  "ai_overview": {
    "page_token": "rWmjgXictZPdkqI4FMcv90nWvWBUtO0e7SpqKiBqHL8ifuENhRADgnwFjHo377JPtU-zAdtunXFqZ6t2U6UkOTkn55xf_t_-9N3A--u3P5w0jehrtcoYq5AwJD6uWOG-atJTYFW3oU8Ty_mSZT6WmKAAiKACTbRanO2unw06Ux93O-dBZ5GZq6m_VuSZ3e2I69WwRHwpoyXHl3BQOh2kp5JFJbGEXSlmm5d1loDu-Ox5BzRxrHY5BGGpuFEyNibFO57QcUerRpX_eb8_tfmiQis4MOZaRYsmSdzw-119WMH0uTKumnt-BPziQB9TRSFIKWYQKHeHyPtpBchAA0QuVj3-U6dFCAigcnHyEDgYTfXO3wJva9nKo80vt0IA2nc5kHzr0ZB5o9vNB4nLBIEuT6RRbF0uQXmQBgTD99JYTwTN9pGMv2rsh9gRIHsw0VbH2zo_Ku8vd65FVKCgqk14X8XqJuGfWjWheZeVWUsMO3F9uNTMZrpqiu3M7kCViaNa92W3mKJPBUGLviOktwihGwf2aD0-U1YZVOTalR7qQagW3VAJICJ51BcFfXROyXMnIPR4fWTA8t6OinJ6-YbFG6Nf3bSrw_KjXD5RYE6PqPBqzvuaD5g3VB0C4HAMQIacnkZ6jTk3tYsAyAO6LrsgBF8BWDPl5ulAcrmjcXlQKsD8hbGhvFKZChB_RQh4edSCHIJyXhAaMvWOXlHoP4z5T_Zl8ABXV1_EZXdAengab2akpZ2yaLJbOGc0vuIK95t_JTnrf0HqckHGb0iVx0hvBMkdVtz-JsiQC_KC1NMLQd4htaD6htS6QQp_GakMGnq7_AgpF-QeyFyQOdJ5gRTp3yP9rwRZkMWXz706sx35HruqlkeeU4u9ujwD09MzEeOTZcv0qCUc-3afvkZJSD4Zrv0q1_vpyS7FUi9kgh1iKqQOFrQoTFLKsJkI_IFEZnASRq6Hha3p-wJ1uFEIA4EG2PRwIriBMA_cFNuClpoppl9Kez8JJdF8YYd4pKvePGUG7O_Ugb8sPwf-4uwaT9vjYVSvRb10arx8Xs2i3uzZH_WV5SrIlL4xaTlKH4VqbwyDhOygbY1OmaqjxdA9U9dtmed2f6e7x3lnvWZav564IjvPxvt6013TcmO8Ao0BMpA8D7F23srrGvDnNivyopLeXWTQ6SxbC1SilmlgepDqm-Zn88ls1uubzab21CwMWXSQan8DmsQweA",
    "serpapi_link": "https://serpapi.com/search.json?engine=google_ai_overview&page_token=rWmjgXictZPdkqI4FMcv90nWvWBUtO0e7SpqKiBqHL8ifuENhRADgnwFjHo377JPtU-zAdtunXFqZ6t2U6UkOTkn55xf_t_-9N3A--u3P5w0jehrtcoYq5AwJD6uWOG-atJTYFW3oU8Ty_mSZT6WmKAAiKACTbRanO2unw06Ux93O-dBZ5GZq6m_VuSZ3e2I69WwRHwpoyXHl3BQOh2kp5JFJbGEXSlmm5d1loDu-Ox5BzRxrHY5BGGpuFEyNibFO57QcUerRpX_eb8_tfmiQis4MOZaRYsmSdzw-119WMH0uTKumnt-BPziQB9TRSFIKWYQKHeHyPtpBchAA0QuVj3-U6dFCAigcnHyEDgYTfXO3wJva9nKo80vt0IA2nc5kHzr0ZB5o9vNB4nLBIEuT6RRbF0uQXmQBgTD99JYTwTN9pGMv2rsh9gRIHsw0VbH2zo_Ku8vd65FVKCgqk14X8XqJuGfWjWheZeVWUsMO3F9uNTMZrpqiu3M7kCViaNa92W3mKJPBUGLviOktwihGwf2aD0-U1YZVOTalR7qQagW3VAJICJ51BcFfXROyXMnIPR4fWTA8t6OinJ6-YbFG6Nf3bSrw_KjXD5RYE6PqPBqzvuaD5g3VB0C4HAMQIacnkZ6jTk3tYsAyAO6LrsgBF8BWDPl5ulAcrmjcXlQKsD8hbGhvFKZChB_RQh4edSCHIJyXhAaMvWOXlHoP4z5T_Zl8ABXV1_EZXdAengab2akpZ2yaLJbOGc0vuIK95t_JTnrf0HqckHGb0iVx0hvBMkdVtz-JsiQC_KC1NMLQd4htaD6htS6QQp_GakMGnq7_AgpF-QeyFyQOdJ5gRTp3yP9rwRZkMWXz706sx35HruqlkeeU4u9ujwD09MzEeOTZcv0qCUc-3afvkZJSD4Zrv0q1_vpyS7FUi9kgh1iKqQOFrQoTFLKsJkI_IFEZnASRq6Hha3p-wJ1uFEIA4EG2PRwIriBMA_cFNuClpoppl9Kez8JJdF8YYd4pKvePGUG7O_Ugb8sPwf-4uwaT9vjYVSvRb10arx8Xs2i3uzZH_WV5SrIlL4xaTlKH4VqbwyDhOygbY1OmaqjxdA9U9dtmed2f6e7x3lnvWZav564IjvPxvt6013TcmO8Ao0BMpA8D7F23srrGvDnNivyopLeXWTQ6SxbC1SilmlgepDqm-Zn88ls1uubzab21CwMWXSQan8DmsQweA"
  }
```

Please see https://serpapi.com/ai-overview#api-examples-example-with-an-extra-request-required for details.

**Comment by migsterrrrr** [comment]
> We've implemented a standalone engine for this case. Instead of returning an error, we now return `page_token` and `serpapi_link` for fetching the AI Overview result. For example.
> 
> ```
>   "ai_overview": {
>     "page_token": "rWmjgXictZPdkqI4FMcv90nWvWBUtO0e7SpqKiBqHL8ifuENhRADgnwFjHo377JPtU-zAdtunXFqZ6t2U6UkOTkn55xf_t_-9N3A--u3P5w0jehrtcoYq5AwJD6uWOG-atJTYFW3oU8Ty_mSZT6WmKAAiKACTbRanO2unw06Ux93O-dBZ5GZq6m_VuSZ3e2I69WwRHwpoyXHl3BQOh2kp5JFJbGEXSlmm5d1loDu-Ox5BzRxrHY5BGGpuFEyNibFO57QcUerRpX_eb8_tfmiQis4MOZaRYsmSdzw-119WMH0uTKumnt-BPziQB9TRSFIKWYQKHeHyPtpBchAA0QuVj3-U6dFCAigcnHyEDgYTfXO3wJva9nKo80vt0IA2nc5kHzr0ZB5o9vNB4nLBIEuT6RRbF0uQXmQBgTD99JYTwTN9pGMv2rsh9gRIHsw0VbH2zo_Ku8vd65FVKCgqk14X8XqJuGfWjWheZeVWUsMO3F9uNTMZrpqiu3M7kCViaNa92W3mKJPBUGLviOktwihGwf2aD0-U1YZVOTalR7qQagW3VAJICJ51BcFfXROyXMnIPR4fWTA8t6OinJ6-YbFG6Nf3bSrw_KjXD5RYE6PqPBqzvuaD5g3VB0C4HAMQIacnkZ6jTk3tYsAyAO6LrsgBF8BWDPl5ulAcrmjcXlQKsD8hbGhvFKZChB_RQh4edSCHIJyXhAaMvWOXlHoP4z5T_Zl8ABXV1_EZXdAengab2akpZ2yaLJbOGc0vuIK95t_JTnrf0HqckHGb0iVx0hvBMkdVtz-JsiQC_KC1NMLQd4htaD6htS6QQp_GakMGnq7_AgpF-QeyFyQOdJ5gRTp3yP9rwRZkMWXz706sx35HruqlkeeU4u9ujwD09MzEeOTZcv0qCUc-3afvkZJSD4Zrv0q1_vpyS7FUi9kgh1iKqQOFrQoTFLKsJkI_IFEZnASRq6Hha3p-wJ1uFEIA4EG2PRwIriBMA_cFNuClpoppl9Kez8JJdF8YYd4pKvePGUG7O_Ugb8sPwf-4uwaT9vjYVSvRb10arx8Xs2i3uzZH_WV5SrIlL4xaTlKH4VqbwyDhOygbY1OmaqjxdA9U9dtmed2f6e7x3lnvWZav564IjvPxvt6013TcmO8Ao0BMpA8D7F23srrGvDnNivyopLeXWTQ6SxbC1SilmlgepDqm-Zn88ls1uubzab21CwMWXSQan8DmsQweA",
>     "serpapi_link": "https://serpapi.com/search.json?engine=google_ai_overview&page_token=rWmjgXictZPdkqI4FMcv90nWvWBUtO0e7SpqKiBqHL8ifuENhRADgnwFjHo377JPtU-zAdtunXFqZ6t2U6UkOTkn55xf_t_-9N3A--u3P5w0jehrtcoYq5AwJD6uWOG-atJTYFW3oU8Ty_mSZT6WmKAAiKACTbRanO2unw06Ux93O-dBZ5GZq6m_VuSZ3e2I69WwRHwpoyXHl3BQOh2kp5JFJbGEXSlmm5d1loDu-Ox5BzRxrHY5BGGpuFEyNibFO57QcUerRpX_eb8_tfmiQis4MOZaRYsmSdzw-119WMH0uTKumnt-BPziQB9TRSFIKWYQKHeHyPtpBchAA0QuVj3-U6dFCAigcnHyEDgYTfXO3wJva9nKo80vt0IA2nc5kHzr0ZB5o9vNB4nLBIEuT6RRbF0uQXmQBgTD99JYTwTN9pGMv2rsh9gRIHsw0VbH2zo_Ku8vd65FVKCgqk14X8XqJuGfWjWheZeVWUsMO3F9uNTMZrpqiu3M7kCViaNa92W3mKJPBUGLviOktwihGwf2aD0-U1YZVOTalR7qQagW3VAJICJ51BcFfXROyXMnIPR4fWTA8t6OinJ6-YbFG6Nf3bSrw_KjXD5RYE6PqPBqzvuaD5g3VB0C4HAMQIacnkZ6jTk3tYsAyAO6LrsgBF8BWDPl5ulAcrmjcXlQKsD8hbGhvFKZChB_RQh4edSCHIJyXhAaMvWOXlHoP4z5T_Zl8ABXV1_EZXdAengab2akpZ2yaLJbOGc0vuIK95t_JTnrf0HqckHGb0iVx0hvBMkdVtz-JsiQC_KC1NMLQd4htaD6htS6QQp_GakMGnq7_AgpF-QeyFyQOdJ5gRTp3yP9rwRZkMWXz706sx35HruqlkeeU4u9ujwD09MzEeOTZcv0qCUc-3afvkZJSD4Zrv0q1_vpyS7FUi9kgh1iKqQOFrQoTFLKsJkI_IFEZnASRq6Hha3p-wJ1uFEIA4EG2PRwIriBMA_cFNuClpoppl9Kez8JJdF8YYd4pKvePGUG7O_Ugb8sPwf-4uwaT9vjYVSvRb10arx8Xs2i3uzZH_WV5SrIlL4xaTlKH4VqbwyDhOygbY1OmaqjxdA9U9dtmed2f6e7x3lnvWZav564IjvPxvt6013TcmO8Ao0BMpA8D7F23srrGvDnNivyopLeXWTQ6SxbC1SilmlgepDqm-Zn88ls1uubzab21CwMWXSQan8DmsQweA"
>   }
> ```
> 
> Please see https://serpapi.com/ai-overview#api-examples-example-with-an-extra-request-required for details.

Was just testing the new standalone endpoint and it isn't returning the snippet right now? 

```"search_information": {
            "ai_overview_state": "Fully empty"
        },
        "error": "Google hasn't returned any results for this query."
    }```

When querying the standalone endpoint will that live scrape again? In other words, is it worth trying the same token a few times? Thanks

**Comment by marm123** [comment]
Thank you for reaching out, @migsterrrrr. Can you confirm you've used the `page_token`/`serpapi_link` for the AI Overview information immediately after performing a Google Search API call? The token is valid for around 4 minutes, so it should be used right away, otherwise, it expires:
<img width="576" alt="image" src="https://github.com/user-attachments/assets/a6c85f82-bee6-45ad-8ed6-c402f65fe44f">

>When querying the standalone endpoint will that live scrape again? In other words, is it worth trying the same token a few times?

Unfortunately, if you're not getting results from the `page_token`, it's likely already expired and can't be used anymore. You'll need to perform a new Google Search API call to generate a new `page_token` for the AI Overview.

**Comment by migsterrrrr** [comment]
> Thank you for reaching out, @migsterrrrr. Can you confirm you've used the `page_token`/`serpapi_link` for the AI Overview information immediately after performing a Google Search API call? The token is valid for around 4 minutes, so it should be used right away, otherwise, it expires: <img alt="image" width="576" src="https://private-user-images.githubusercontent.com/28161162/381489859-a6c85f82-bee6-45ad-8ed6-c402f65fe44f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDI1NDEsIm5iZiI6MTczMDMwMjI0MSwicGF0aCI6Ii8yODE2MTE2Mi8zODE0ODk4NTktYTZjODVmODItYmVlNi00NWFkLThlZDYtYzQwMmY2NWZlNDRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDE1MzA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5N2JjNDA0ZDRmM2E5NjA5NDkyNDRlZmU4NWZiNzQ3ZjAzMTNlMDdlNGEyZjIwMmIzNDU4Mzk2YWM0MjVmOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HWQYAymRZS1Sr7oNmb52EM5qi2v9ObNb15Kyp-US-XM">
> 
> > When querying the standalone endpoint will that live scrape again? In other words, is it worth trying the same token a few times?
> 
> Unfortunately, if you're not getting results from the `page_token`, it's likely already expired and can't be used anymore. You'll need to perform a new Google Search API call to generate a new `page_token` for the AI Overview.

@marm123 Bartek you are a legend! Thank you...I think it's even more embarrassing - I didn't set up my API call properly. WOW, it works. This is soo magic! I'm buzzing

One question: Can I force the  `"page_token":` to show every time instead of the actual snippet in the first API call? I'd prefer it that way even if it's two credits. It's mainly a Bubble (no-code) limitation as I have to initialise API calls, and if the JSON is unpredictable that makes things difficult for me. Either way, loving this and thank you

**Comment by marm123** [comment]
@migsterrrrr can you reach out to contact@serpapi.com or via chat widget at serpapi.com, so our Customer Success team can help you troubleshoot the issue, and try to find a root cause? We'll be happy to assist.
