### ISSUE TITLE
[Google Search API] We scraped ads result as an organic_result for .co.jp domain

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1991]
A high-volume customer reported that we scraped the ads result under organic_result.

![CleanShot 2024-09-26 at 12 42 08@2x](https://github.com/user-attachments/assets/41540eea-1d27-4cc9-b85f-b8050d72be3d)

Public links: [Playground](https://serpapi.com/playground?q=%E3%81%8A%E9%87%91%E5%80%9F%E3%82%8A%E3%82%8B&location=Tokyo%2C+Tokyo%2C+Japan&google_domain=google.co.jp&gl=jp&hl=ja&num=100&device=mobile&google_domain=google.co.jp&newPara=chips+as_sitesearch+votes+site+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source) 

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070637?view=List) | [Inspect](https://serpapi.com/searches/66f4e523a505f7008b1446db/inspect)

**Comment by btaunt** [comment]
This has been updated. We no longer incorrectly parse `ads` items under `organic_results`.

[Playground](https://serpapi.com/playground?q=%E3%81%8A%E9%87%91%E5%80%9F%E3%82%8A%E3%82%8B&location=Tokyo%2C+Tokyo%2C+Japan&google_domain=google.co.jp&gl=jp&hl=ja&num=100&device=mobile&google_domain=google.co.jp&newPara=chips+as_sitesearch+votes+site+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+rlz+ijn)
