### ISSUE TITLE
[Google Scholar API] Only first section of snippet is scraped

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1995]
We don't scrape the full snippet of a search.

![CleanShot 2024-09-30 at 07 06 22](https://github.com/user-attachments/assets/600014eb-2672-4eaa-9af1-0d7b8bd37fba)

Public links: [Playground](https://serpapi.com/playground?engine=google_scholar&q=Ambient+temperature+affects+the+composition+of+the+vaginal+microbiome+and+temperature+sensitive+vaginal+microbes+influence+assisted+reproductive+technology+&hl=en&newPara=device)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/admin/6755014/conversation/102910000069948) | [Search Inspect](https://serpapi.com/searches/66f9dcbbdda9d9d380cb836b/inspect)

**Comment by NateSkiles** [comment]
A user reached out about this issue:

[Front](https://app.frontapp.com/open/cnv_1d8sm4rg?key=KertHc-0YZ2Z33dVryvQXeuOM_POl65E)

**Comment by Alaa-abdulridha** [comment]
This issue has been resolved:

Before fixing the issue (Production):

![image](https://github.com/user-attachments/assets/9e450a21-d861-40ef-9c08-8a9dd2076066)


After fixing the issue (Production):

![image](https://github.com/user-attachments/assets/2d7721b9-776c-4032-b583-d7ceaf78f07b)
