### ISSUE TITLE
[Google Jobs API] Missing posted_at information

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#1996]
A customer reported that we currently don't scrape the `posted_at` information on our Google Jobs API.

![CleanShot 2024-09-30 at 08 47 48](https://github.com/user-attachments/assets/5c869cf5-6c01-4656-852b-508f04627ed7)

Public links: [Playground 1](https://serpapi.com/playground?chips=date_posted%3Aweek&engine=google_jobs&gl=us&google_domain=google.com&hl=en&ltype=1&q=senior+frontend+engineer)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070706?view=List) | [Search Inspect](https://serpapi.com/searches/66f80fdc207c88ba02e2ccbd/inspect)

**Comment by hilmanski** [comment]
A high-volume customer reported this issue.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070723?view=List)

**Comment by hilmanski** [comment]
Beside of missing the `posted_at` information specifically, I think we're also missing the detected_extensions when the results look like this:

![CleanShot 2024-09-30 at 14 32 20](https://github.com/user-attachments/assets/9109cad2-aa53-44b7-b784-4d0146d3e501)

[Inspect](https://serpapi.com/searches/66fa458b7ef9fa3bcc3ce653/inspect)

**Comment by marm123** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000068389?view=List)

**Comment by alexbarron** [comment]
Users notified. Added the label.
