### ISSUE TITLE
[Yandex Search API] Results from API are different than via regular search

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#1997]
One of our users reported that they are not getting the same results via SerpApi as they are through regular Yandex searches. I've discovered that the `yandex_url` contains the `rstr` parameter, which is always the negative of the `lr` ([ref](https://github.com/serpapi/SerpApi/blob/63562f04058476f94a76e2e29bee2ef281ae139a/app/models/search/yandex/parameters.rb#L54)). I'm not exactly sure what this parameter does, but after removing it, the results are the same as through regular search:

Results with the `rstr` parameter:
![image](https://github.com/user-attachments/assets/d6fb1e08-b3f2-417c-902f-87b8904a7643)

Results with no `rstr` parameter (very similar to the ones the user gets with multiple pages of results):
<img width="1277" alt="image" src="https://github.com/user-attachments/assets/6185f105-9872-4d4f-b08d-2f695102e0ab">

Public links: [Playground](https://serpapi.com/playground?engine=yandex&text=host%3Avinhide.org&yandex_domain=yandex.ru&lr=2)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070715?view=List) | [Search Inspect](https://serpapi.com/searches/66fa6b18ee677fa2fec3983f/inspect)

**Comment by hilmanski** [comment]
Another customer reported this issue.

Expected result:
<img width="1270" alt="1a16ce35e1dff0ef5d12f4ccd9dc4869685289c9" src="https://github.com/user-attachments/assets/da4f06bb-7cb1-4706-aa94-9d5d1b7e9918">

received this instead:
![58a26ef8ec2c1dc0cfdcd87ce0b79b9ff08494b6](https://github.com/user-attachments/assets/ead12bd7-2ab7-4558-aced-470d09447854)

I've tried to switch using different regions, but unfortunately, I can't replicate the original result. Based on the screenshot, customer using `lr=10553`, which is not available on our supported location.

Public links:
Internal links: [Front](https://app.frontapp.com/open/cnv_1d995ov0?key=e6ywY_ij-28wScXbPz9y9_7Q1JbMuhpt) | [Inspect](https://serpapi.com/searches/66fb7b97b57db8b767740f53/inspect) | [Inspect with lr 84](https://serpapi.com/searches/66fb7b8821e77b07f2b1198e/inspect)

**Comment by ocvit** [comment]
According to multiple russian sources ([1](https://journal.topvisor.com/ru/seo-kitchen/technical-regions-in-yandex/), [2](https://topvisor.com/ru/support/rankings/mismatch/yandex/#rstr), [3](https://a-parser.com/docs/parsers/se-yandex)):

- `lr` - selects search results relevant to specified region
- `rstr` - selects search results that include specified region in text snippets/titles on the page

These are 2 different filter strategies, but we set `rstr` each time `lr` is filled  - that's incorrect.

Also, according to this support [thread](https://a-parser.com/threads/4898/) of A-Parser (our competitor), region based search in Yandex depends not only on `lr`/`rstr`, but also `yp` and `yandex_gid` that we don't use at all.

**Comment by marm123** [comment]
Thanks @ocvit, that makes sense. It's probably because of that we're getting weird locations despite setting the `lr` parameter, right? Here is the `lr` set to Moscow, and the language to Russian, but the results are for the New York location:

<img width="1668" alt="image" src="https://github.com/user-attachments/assets/fc58c020-52d6-4c65-b3d7-8f3503ffd4f5">

**Comment by ocvit** [comment]
These results are for Moscow. Location in the footer is detected from IP address you make the request from. In some cases, it may affect the search results, but not in this specific example. At this moment, I'm not sure is it possible to fully override it, experimenting with cookies.

Talking about `rstr` - we should extract it into a separate optional checkbox.

**Comment by marm123** [comment]
Oh, ok. Thanks for explaining @ocvit!

**Comment by ocvit** [comment]
Fix has been released.

`rstr` param is an optional filter now.

<img width="1302" alt="Screenshot 2024-10-07 at 11 08 57" src="https://github.com/user-attachments/assets/ad535eed-8a52-4605-bf8d-6daa1b9f65e7">
