### ISSUE TITLE
[Google Trends API] Include marker for incomplete data within a range

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#1999]
A high volume customer requested we include whether a given data point has partial or incomplete data. 

This is currently shown in the Google Trends UI:

![image](https://github.com/user-attachments/assets/d645def9-d075-4fcb-808c-5b2d909b36a0)

Currently, we do not indicate whether the data is partial or not:

![image](https://github.com/user-attachments/assets/d944bb51-c6e1-4273-b6e4-e03e4afb81a2)

This is typically always the latest data point. As a solution, we could add a boolean attribute to the element if it is incomplete.

Example:

```json
{
  "date": "Sep 29 – Oct 5, 2024",
  "timestamp": "1727568000",
  "partial_data": true,
  "values": [
    {
      "query": "Coffee",
      "value": "99",
      "extracted_value": 99
    }
  ]
}

```

[Playground](https://serpapi.com/playground?engine=google_trends&q=Coffee&date=today+5-y) | [Google Tends Search](https://trends.google.com/trends/explore?date=today%205-y&geo=US&q=coffee&hl=en) | [Documentation](https://serpapi.com/google-trends-api)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070743?view=List)

**Comment by btaunt** [comment]
We now parse this information under `partial_data`:

<img width="191" alt="Screenshot 2024-10-01 at 11 20 08 AM" src="https://github.com/user-attachments/assets/31552b0b-0495-47d0-9a5a-01500061339e">

---

[Playground](https://serpapi.com/playground?engine=google_trends&q=adidas&newPara=hl)
