### ISSUE TITLE
[Google Local Services API] Scrape bookings nearby

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#2001]
A user requested we add the "x bookings nearby" text from Google Local Services.

<img width="1346" alt="image" src="https://github.com/user-attachments/assets/92b1fca5-da7b-429a-a1de-65a71a653d76">

[Playground](https://serpapi.com/playground?engine=google_local_services&q=plumber&data_cid=14414772292044717666) | [Google](https://www.google.com/localservices/prolist?g2lbs=AOHF13l96Bb9DtFtdNK_14CntWYNXzRkWujEoMn2qrd_3-YP3za4aU3EPZHg94sDwM6CXJGqpjGMgGnB7ZOsp8jxZXMkDIjJZg%3D%3D&hl=en-US&gl=us&cs=1&ssta=1&src=1&gsas=1&sa=X&slp=QAFSBAgCIAA%3D&scp=Cih4Y2F0OnNlcnZpY2VfYXJlYV9idXNpbmVzc19wbHVtYmVyOmVuLVVTEksSEgk7CD_TpU_CiRFi_nfhBo8LyBoSCTsIP9OlT8KJEWL-d-EGjwvIIgtOZXcgWW9yayBOWSoUDWdcIBgVTfa80x3bhmMYJR87EtQaCFBsdW1iaW5nKghQbHVtYmluZ0oVChMI5JGUl9btiAMVbgytBh2zahdv&q=Plumbing%20near%20New%20York%20NY&ved=0CAAQ2MAHahgKEwiQuqHH1u2IAxUAAAAAHQAAAAAQzwE&spp=ElYKEQjZ-oAJEKuntrEJGJrgvrMJEih4Y2F0OnNlcnZpY2VfYXJlYV9idXNpbmVzc19wbHVtYmVyOmVuLVVTQhMI5pnt-9btiAMVX87CBB28_whlSARQAQ) | [Documentation](https://serpapi.com/google-local-services-api)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070773?view=List)

**Comment by NateSkiles** [comment]
@ocvit I'm seeing this in the Google link still:

![image](https://github.com/user-attachments/assets/e7b92feb-1b3d-4447-894f-6e9c7df2ee02)

I'm not sure if the link provided in the playground for Google services should work, but running the query I get the following returned:

```json
"google_local_services_url": "https://www.google.com/_/AdsHomeservicesConsumerUi/data/batchexecute?hl=en"
```

But navigating to that link returns:

![image](https://github.com/user-attachments/assets/18e94b16-07aa-4731-9494-b27be4c8fa7e)

I thought this might be expected due to how we scrape the Google Local Services page, but please let me know if not and I can create a separate issue for that.

**Comment by ocvit** [comment]
I found that Local Services API is very sensitive to IP from which you access the page.

Results for U.S.-based `data_cid`:

<img width="1318" alt="Screenshot 2024-10-04 at 17 51 52" src="https://github.com/user-attachments/assets/81ac08c5-dbc5-4ef9-82c1-8dc95f46a2d0">

---

Results for Canada-based `data_cid`:

<img width="1318" alt="Screenshot 2024-10-04 at 17 56 34" src="https://github.com/user-attachments/assets/6fb72c28-fb61-4687-a9af-2e6e97ccff0e">

---

We do not match `data_cid` to proxy location, so we can get empty results pretty easily:

<img width="1217" alt="Screenshot 2024-10-04 at 17 29 15" src="https://github.com/user-attachments/assets/7ae42d32-f6d0-4675-9f84-ce47be93b70c">

---

Talking about `X bookings nearby` - I couldn't generate a page with this field even once:

<img width="1275" alt="Screenshot 2024-10-04 at 16 54 28" src="https://github.com/user-attachments/assets/b6cbee54-d4f4-4557-8599-988e1efa61d7">

---

There are too many variables here. Basically, with current approach we can't guarantee that data we fetch is valid, i.e. it's not just hidden by incorrect proxy that we use. `X bookings nearby` is a whole another layer of randomness.

I'm curious is there a way to override country-by-IP detection with some additional search param.

**Comment by NateSkiles** [comment]
@ocvit Thanks for looking into this! I will add the freezer tag on this for now, as this appears to be much more complicated than I initially assumed.

**Comment by ocvit** [comment]
Feature has been released.

`bookings_nearby` field is fetched now + it is correctly rendered in Playground preview.

<img width="1318" alt="Screenshot 2024-10-10 at 12 46 38" src="https://github.com/user-attachments/assets/da4f7951-cc0f-4e96-b62d-6a6dcbe92e61">
