### ISSUE TITLE
[Google Scholar API] Incorrect number of results returned when filtered by date

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#2002]
When including the parameters `as_ylo` (from year) and `as_yhi` (to year), I'm seeing a discrepancy between the number of results returned in `search_information.total_results` and what is shown on Google Scholar.

### Playground

![image](https://github.com/user-attachments/assets/ca224bec-f570-433d-9aab-5bc42c06e0de)

* Total results: 2270000
* [Playground](https://serpapi.com/playground?engine=google_scholar&q=artificial+intelligence+-book&as_ylo=2020&as_yhi=2023&hl=en&start=0&num=20&no_cache=true)

### Google

![image](https://github.com/user-attachments/assets/ca9a884f-c2c8-41fd-aa25-8ed2adf37ce5)

* Total Results: 2,280,000
* [Google Link](https://scholar.google.com/scholar?q=artificial+intelligence+-book&hl=en&start=0&num=21&as_ylo=2020&as_yhi=2023)

### Playground
![image](https://github.com/user-attachments/assets/008816a3-bb17-423d-b0f3-c07e2ae525ba)

* Total Results:
[* Playground](https://serpapi.com/playground?engine=google_scholar&q=artificial+intelligence+-book&as_ylo=2017&as_yhi=2024&hl=en&start=0&num=20&no_cache=true) | Google

### Google

![image](https://github.com/user-attachments/assets/9321e440-18db-4b7e-8f9e-e473c53c05ac)

* Total Results: 37,100
* [Google Link](https://scholar.google.com/scholar?q=artificial+intelligence+-book&hl=en&start=0&num=21&as_ylo=2017&as_yhi=2024)

I've verified that without the date range filters, the total results match:

<img width="1623" alt="image" src="https://github.com/user-attachments/assets/c99dc563-fcbc-4fb2-86fb-d8133e9300e1">

It's also a bit odd that there are so many more results for 2020-2023 than 2017-2024, but I'm seeing the same thing in Google Scholar.

[Documentation](https://serpapi.com/google-scholar-api)

[Front](https://app.frontapp.com/open/cnv_1d8sm4rg?key=KertHc-0YZ2Z33dVryvQXeuOM_POl65E)

**Comment by andypple83** [comment]
Thanks, @NateSkiles, for your detailed information. The total results number is from Google Scholar, based on Google Scholar's algorithm. If you visit the Google Scholar page, you will receive a different estimated total number of results for different searches. 

I checked our Google Scholar API, SerpApi scrapes the correct "total_number" from Google Scholar page. 

Let me know if you have more questions!
