### ISSUE TITLE
[Bing Search API] Missing organic results

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#2005]
Organic results and Ads results are mixed.

![Screenshot 2024-10-03 at 16 11 14](https://github.com/user-attachments/assets/87a42a26-6c23-4073-9d36-b84eafed8789)

There are many organic results from Bing HTML response. But we only parse 2 results in organic results, other organic results are in `ads` node.

Public links: [Playground 1](https://serpapi.com/playground?engine=bing&q=Coffee)| [Documentation](https://serpapi.com/bing-search-api)

Internal links:  [Search Inspect 1 (](http://localhost:3000/playground?engine=bing&q=Coffee)under your dashboard > "Your Searches" > select one search)

**Comment by aciddjus** [comment]
@andypple83 The inspect link points to `localhost`

Also, these are all ads. Bing really returns only 2-3 organic results for this search.

![image](https://github.com/user-attachments/assets/8cfe4b59-c6d4-44a5-b8bc-b32355b8e238)
