### ISSUE TITLE
[Google Search API] Missing Streetview image result in Local Pack result

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#2009]
Missing streetview image result

![Screenshot 2024-10-04 at 12 25 35](https://github.com/user-attachments/assets/f4ecfc66-8d3d-4496-931a-63bf181a3498)

Streetview is available in HTML file. We missed this field in our result with the latest Google layout.

Public links: [Playground 1(mobile)](https://serpapi.com/playground?q=40+Avenue+B%2C+New+York%2C+NY+10009%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=as_sitesearch+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client+votes+site+ie+oe+pws+ibp+source+rlz+ijn) | [Playground 2(Desktop)](https://serpapi.com/playground?q=40+Avenue+B%2C+New+York%2C+NY+10009%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true&google_domain=google.com&newPara=as_sitesearch+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client+votes+site+ie+oe+pws+ibp+source+rlz+ijn) | [Documentation](https://serpapi.com/local-pack#api-examples-results-for-specific-addresses)

Internal links: [Search Inspect 1](https://serpapi.com/searches/66ff7b9bb6e4db8d51cd2a78/inspect) (under your dashboard > "Your Searches" > select one search) | [Search Inspect 2](https://serpapi.com/searches/66ff7cc456f97060c2366e7f/inspect)

**Comment by Ovi** [comment]
We're now parsing streetview image:
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/95bf1d65-2b87-4ff6-a72b-bd4b9c9a5192">

[Playground 1(mobile)](https://serpapi.com/playground?q=40+Avenue+B%2C+New+York%2C+NY+10009%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com) | [Playground 2(Desktop)](https://serpapi.com/playground?q=40+Avenue+B%2C+New+York%2C+NY+10009%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true&google_domain=google.com) | [Documentation](https://serpapi.com/local-pack#api-examples-results-for-specific-addresses)
