### ISSUE TITLE
[Naver API] Only returning `inline_videos_results` for some queries

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#2010]
Some Naver queries that show many results in the HTML are only returning `inline_videos_results` in the JSON. Most queries appear to be working normally. I've provided two Playground links below that demonstrate the issue.

![image](https://github.com/user-attachments/assets/2580a431-23da-4f30-a39a-4acc0962698b)

Public links: [Playground 2](https://serpapi.com/playground?engine=naver&query=%EB%94%B8%EA%B8%B0+%EB%B3%91%ED%95%B4%EC%B6%A9+%EC%A2%85%EB%A5%98+%EB%B0%8F+%EC%98%88%EB%B0%A9%EB%B2%95) | [Playground 2](https://serpapi.com/playground?engine=naver&query=Coffee%EC%B9%B4%ED%91%B8%EC%B9%98%EB%85%B8+%EB%A7%8C%EB%93%9C%EB%8A%94+%EB%B0%A9%EB%B2%95) (Also returns empty `shopping_results`) | [Documentation](https://serpapi.com/naver-search-api)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070866?view=List) | [Search Inspect 1](https://serpapi.com/searches/66ffc73275f9741784c0ff33/inspect)| [Search Inspect 2](https://serpapi.com/searches/66ffbf67e45f336ff96eea7f/inspect)

**Comment by Alaa-abdulridha** [comment]
This issue has been fixed:

Before fixing the issue (Production):

![image](https://github.com/user-attachments/assets/a24a3b3c-4a51-449c-b4f8-05af8a641238)


After fixing the issue (Production):

![image](https://github.com/user-attachments/assets/f30dc05e-2da4-4cef-8516-917ad165487c)
