### ISSUE TITLE
[Google Search API] Title missing with "place_sites" 

### ISSUE THREAD

**Issue by RedBillyOne** [serpapi/public-roadmap#2011]
Hi,

Serapi don't return anymore the title in block "Sites de lieux" (places_sites) see screenshot below. Is it a bug or title is not available ?

![image](https://github.com/user-attachments/assets/b8a40135-44c6-4ece-b617-2e04ae8d5956)

https://serpapi.com/playground?q=fleuriste+paris+16&location=France&google_domain=google.fr&gl=fr&hl=fr

Regards

**Comment by hilmanski** [comment]
Thank you very much for your report @RedBillyOne. I believe it's a valid bug. We'll investigate and fix the issue. We'll let you know once we have an update on this.

[inspect](https://serpapi.com/searches/67030eaa64f11d1e4b7dbac0/inspect)

**Comment by RedBillyOne** [comment]
@tanys123 Thanks,

but note that you have the same problem below (missing title in JSON with breadcrumb) 

![image](https://github.com/user-attachments/assets/f05d5362-1e24-4ca0-95e3-db93e9381033)

https://serpapi.com/playground?device=desktop&engine=google&gl=fr&google_domain=google.fr&hl=fr&location=France&q=golfeur+fran%C3%A7ais

Is it possible to fix this one too ?

Regards

**Comment by zyc9012** [comment]
Thank you @RedBillyOne. I've created a separate issue for that: https://github.com/serpapi/public-roadmap/issues/2012

**Comment by tanys123** [comment]
Thanks @RedBillyOne for reporting. We have fixed the `title`.

<img width="1410" alt="Screenshot 2024-10-07 at 9 23 17 PM" src="https://github.com/user-attachments/assets/07383de6-815a-45a8-8a4a-fc3f47a5a1cb">

**Comment by RedBillyOne** [comment]
I confirm. Thanks
