### ISSUE TITLE
[Google Search API] Missing Jersey Google domain `google.je` and country code `je`

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#2013]
An Enterprise customer reported we're currently missing Jersey under supported Google domains and `gl` country code values.

We should add `google.je` as a supported value for `google_domain`.

And add `je` as a supported value for `gl`.

Public links: [Google's List of Supported Domains](https://www.google.com/supported_domains) | [Google's List of Country Codes](https://developers.google.com/public-data/docs/canonical/countries_csv) | [Our Google Domain Documentation](https://serpapi.com/google-domains) | [Our GL Country Code Documentation](https://serpapi.com/google-countries)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070839?view=List)

**Comment by btaunt** [comment]
We now support both of the following via Google Search API: 

- `google_domain`: `google.je`
- `gl`: `je`

[Example Playground](https://serpapi.com/playground?q=Coffee&google_domain=google.je&gl=je&hl=en&google_domain=google.je&newPara=chips+as_sitesearch+votes+site+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz)
