### ISSUE TITLE
[All APIs] Deprecation/removal policy

### ISSUE THREAD

**Issue by dsojevic** [serpapi/public-roadmap#2015]
There are currently a handful of deprecation notices throughout the API documentation; an example of one current notice:

> **Deprecated**
> The Inline Products API will soon be deprecated, and the results will be served in Immersive Products API. You may head over to the documentation to get the latest view of the API response.

_via https://serpapi.com/inline-products_

There are a couple of issues with this current style of notice:
1. The feature/functionality is actually **currently deprecated** instead of "soon be deprecated"; I believe the message to intend to convey "soon be removed" instead as a deprecated feature may still remain available for years to come.
2. There is no mention of when "soon" is; many consumers of an API will either leave these types of changes until the last minute or until it "bites them" at the time of removal, so to speak.

I suggest that we outline and enforce _(where able)_ a Deprecation/Removal policy to improve Developer Experience (DX).

Below is an example deprecation/removal schedule with notes -- exact timeframes and numbers given are arbitrary at this stage, but generally the longer the notice period, the better.

## Example Schedule

| Day # | Status | Notes |
| - | - | - |
| 00 | **Deprecated** | Feature/API is still generally available but will be removed by a certain date or if unable to indicate an exact time, indicate the volatility of it so that it is known. It should also indicate what the replacement is or if there is no replacement. For the purposes of the remaining items, assume it is a deprecation & removal fully within our control.<br><br>At this point, for any users that are using a specific API that has a deprecation, we can also email and/or mark in the dashboard the fact that there is a new deprecation / upcoming removal. |
| 60 | **Soft Removal** | Feature/API has been removed from the response by default, but may be explicitly requested with a parameter or header. It allows existing consumers to continue to use it with minimal disruption while they handle a larger move to the suggested replacement (if any).<br><br>This can be restricted to accounts that existed at the time of soft removal so that new accounts have no effective access to it at this point. The notice should be updated to reflect the new state and to indicate the full removal date. |
| 90 | **Full Removal: Grace Period** | This would mark the official "full removal" of the feature/API. In practice, many consumers relying on a feature/API won't have actioned it by this stage, so we can give them a grace period in which they _should_ become very much aware that they need to action it immediately.<br><br>This can be achieved by throwing HTTP errors at an increasing rate as the time passes. For example.<br><br>* **Day 1:** 1% of requests with the param/header present for the deprecated feature fail with a HTTP error + message indicating the removal.<br>* **Day 2:** 2% fail<br>* **Day 3:** 5% fail<br>* **Day 4:** 10% fail<br>* ...<br>* **Day 10:** 75% fail<br>* ... |
| 100 | **Full Removal: Gone** | Feature/API is fully removed from the API. At this stage, the consumer will likely have actioned the change. |

**Comment by sonika-serpapi** [comment]
I like the idea of ideally standardizing this. 

Just a thought - I am trying to understand a bit more- when do we deprecate an API or a part of it? The feasibility of implementing this depends on whether we are have to deprecate something when Google or another search engine deprecates it. If that is the case, how would we know the number of days we can keep it active or a fixed date when it will be removed? In that case, it would depend on the particular search engine.

**Comment by dsojevic** [comment]
> Just a thought - I am trying to understand a bit more- when do we deprecate an API or a part of it? The feasibility of implementing this depends on whether we are have to deprecate something when Google or another search engine deprecates it. If that is the case, how would we know the number of days we can keep it active or a fixed date when it will be removed? In that case, it would depend on the particular search engine.

This is completely correct, @sonika-serpapi!

So to expand a bit further; there are going to be two main types of deprecations/removals -- planned and unplanned.

## Planned

Planned deprecations/removals will be the type that we have fully in our control and will likely be for things such as adjusting the structure of an API response (or even the route to the API as a whole).

An example of such is the [Inline Products Deprecation](https://serpapi.com/inline-products) where the same data is generally available, but it is being moved to a different location; in this case, to the [Immersive Products API](https://serpapi.com/immersive-result).

In planned deprecations, we have near full control over the deprecation/removal schedules and can adhere to whatever schedule we desire.

Obviously an unplanned deprecation/removal that impacts a feature with a previously planned deprecation/removal would cause our own schedule to be changed/move to the same approach for an unplanned deprecation/removal.

## Unplanned

Unplanned deprecations/removals covers the scenario you mentioned where another search engine, such as Google, deprecates and/or removes something that one of our endpoints is reliant on.

Depending on the search engine, they may themselves deprecate something before removal; if they do and they indicate a period of availability, we can adjust our own deprecation around that while still being explicit to our consumers that the ultimate timeline for removal is not within our control.

If they don't indicate a period of availability and have a "will be gone soon" style message, our messaging to our consumers could be along the lines of "This feature has been deprecated by <the upstream provider> and they have not outlined a removal timeline." then suggesting how else they can achieve it, if at all. The wording in the example isn't great, but it should give you the gist of the message.

For these cases, we could enter a truncated removal schedule where a **Soft Removal** begins on day 5 and then **Full Removal: Grace Period** begins on day 10 _(day numbers are examples)_. We would also attempt to notify any consumers of that API prior to the soft removal that they will need to adjust their usage with priority.

If the search engine does a full removal of something we're reliant on without any prior notice, we would likely just indicate as such in our own documentation but marking it as "Removed" (with the reason/explanation) for a while before outright removing it from the documentation.

**Comment by zyc9012** [comment]
Thanks for the detailed explanation of the deprecation policy, @dsojevic!

I think the hard problem for us is that when we want to deprecate an API or a part of a response, we can't figure out who is using it, as we return the full response containing multiple API results. For example, Google Search API returns Ads Results, Answer Box, Inline Products, Immersive Products, etc., at once. We don't know if users are depending on a certain field, which makes it difficult to accurately notify users of the deprecation. Though we have deprecation notes in the documentation, we've never removed them if I remember correctly.

> If the search engine does a full removal of something we're reliant on without any prior notice, we would likely just indicate as such in our own documentation but marking it as "Removed" (with the reason/explanation) for a while before outright removing it from the documentation.

Yes. And this is the majority of cases we faced. Things just changed without notice. Like our [Google Shopping API New Layout](https://serpapi.com/google-shopping-api)

**Comment by hartator** [comment]
What are the situations a well-thought API should deprecate anything?

If the JSON fields are poorly named, structured, or miss-organized on our side, I believe it's superior to avoid making a mistake like this in the first place or at least to own the mistake without disturbing API use.

If the JSON fields have to change because of a big layout change, disappearance of that type of results, or something else on the engine side, I can't really see how we can plan for it as it's outside of our control.

**Comment by dsojevic** [comment]
> What are the situations a well-thought API should deprecate anything?

I'll give some examples which SerpApi might be more likely to see than an API of another that relies purely on data/functionality within their control. In our case, I would wager that most items would be as a result of trying to maintain backwards compatibility for consumers so we don't disturb API use.

1. Minor layout changes that result in additional data that make existing attribute naming less consistent or more ambiguous:
    - Actual example: Weather answer box has a single `time` attribute for `hourly_forecast` items that is a combination of day + time, whereas `precipitation_forecast` has items with separate `day` and `time` attributes (and no combined item)
    - In the event that the hourly forecast was now able to have separate `day` and `time` attributes itself, it may necessitate deprecating the `time` attribute on hourly forecast (as it is inconsistent with other items in the same API) to later change it's value to the expected time-only type
2. Minor layout changes that change data in a way that would result in different fields:
    - Contrived example: A rich result type includes a singular review for an item (and has for years) and then is changed to include multiple reviews rendering the `review` attribute itself more ambiguous
    - A new `reviews` array attribute would likely be added to handle this, but then the original `review` item may become ambiguous and it may only make sense to support for a relatively short period of time.
3. Minor layout changes that add larger amounts of data that would result in new, previously unknown, structures as the most appropriate API response:
    - Actual example: the dictionary answer box results are changed to include additional context and information that make the current structure/data segmentation returned less valuable
    - To maximise value from the new answer box results, it would likely make sense to deprecate the older answer box attributes as they don't map accurately to what is displayed
4. Major structural changes that combine or split data:
    - Contrived example: Example Store has a product search page and a stock search page with overlap in products returned, but otherwise returning different associated data (e.g. pricing + purchase options on one, stock counts and locations on another the other). Example Store then merges these into a single search page that returns both sets of results.
    - We can still support both search + stock pages on our API and return the same data, but it would add maintenance overhead to do so long term; deprecating (and removing these) these in favour of a single API on our side may make sense.

> If the JSON fields are poorly named, structured, or miss-organized on our side, I believe it's superior to avoid making a mistake like this in the first place or at least to own the mistake without disturbing API use.

Owning the mistake and minimising disturbance of existing API consumers is the ultimate goal, however there's the additional consideration of not adding unnecessary cognitive overhead to _new API consumers_ by having behaviour/fields that are only in the documentation for backwards compatibility.

For example, the [Google Inline Products API](https://serpapi.com/inline-products) deprecation encourages users to use the Immersive Products API; this makes sense for existing users who were using the API (in the general sense, not necessarily the specific Products API results) but it serves little value to new users who should be using the recommended API instead.

> If the JSON fields have to change because of a big layout change, disappearance of that type of results, or something else on the engine side, I can't really see how we can plan for it as it's outside of our control.

With changes out of our control that have a larger impact, I think it can be segmented into two types:

1. **Immediate removal; abrupt disappearance of results**
    - A deprecation schedule here won't matter because there's no actual period of deprecation, it's an outright removal
    - In this case; there's not much that can be done outside of displaying a notice (ideally only to current API consumers as it won't impact new consumers)
2.  **Announced removal; disappearance of results at an unknown date/time**
    - An "indeterminate" deprecation schedule here can still be useful as you can help condition consumers to act on deprecations sooner so they're less likely to be impacted by the data loss when it occurs.
   - Displaying a notice here is ideal and, again, ideally only to current consumers
 
In both of these instances, we could better target notifications for deprecations and removals to consumers if there is significant adoption of this:
https://github.com/serpapi/SerpApi/issues/5262

I'm not across how often support sees anything related to deprecations and removals, but the main goals of a policy/schedule would be to:
- Encourage consumers to reduce/end reliance on any deprecated items where feasible
- Reduce maintenance on deprecated items that add overhead to an API (either processing or developmental)
- Reduce the number of consumers that are _unknowingly_ impacted by a deprecation/removal, e.g. an attribute disappears and they don't realise they're impacted until weeks/months later (or ever)

Deprecation policies/schedules are also more prevalent in versioned APIs where you can still maintain that backwards compatibility for consumers while not making documentation and responses overly verbose, ambiguous, or confusing for new consumers.

Though ultimately if we're not hearing of new or existing consumers querying about any of this often enough, it's not worth prioritising until we do.

Hope the extra context helps, @hartator

**Comment by hartator** [comment]
> For example, the [Google Inline Products API](https://serpapi.com/inline-products) deprecation encourages users to use the Immersive Products API; this makes sense for existing users who were using the API (in the general sense, not necessarily the specific Products API results) but it serves little value to new users who should be using the recommended API instead.

The actual thread is a little confusing, but I think Google Inline Products is just being removed by Google, but all of that seems still our speculation according to our comment: https://github.com/serpapi/SerpApi/pull/4273#issuecomment-1889063096 ? So, it might or might not come back? This situation is pretty hard to navigate and understand.

**Comment by aciddjus** [comment]
> I think the hard problem for us is that when we want to deprecate an API or a part of a response, we can't figure out who is using it, as we return the full response containing multiple API results. For example, Google Search API returns Ads Results, Answer Box, Inline Products, Immersive Products, etc., at once. We don't know if users are depending on a certain field, which makes it difficult to accurately notify users of the deprecation. Though we have deprecation notes in the documentation, we've never removed them if I remember correctly.

Hopefully, the `only_fields (WIP)` feature will become popular enough over time to give us better insight into what parts of JSON customers are using.

**Comment by Krugloff** [comment]
A standard policy would be valuable, even for scenarios where we have limited control. Currently, it seems we aren't actively gathering experiences around these cases.

For instance, having a checklist or clear steps for parameter deprecation (e.g., as noted in issue [#1324](https://github.com/serpapi/public-roadmap/issues/1324)) could prevent developers from creating independent processes each time. Relying on solutions like "remove this from documentation, then wait a month" doesn’t feel robust, as it introduces significant reliance on human oversight.

I guess even a single wiki [article]([Checklist for adding a new API](https://github.com/serpapi/SerpApi/wiki/Checklist-for-adding-a-new-API)) outlining possible solutions could significantly improve the deprecation process.

**Comment by hartator** [comment]
Our current policy is we don't depreciate things on our side.

My reasoning is I really really hate when an API changes something on me. And they need a very very good reason to do so. I never thought "Ooo, this is sweet, a new data format to learn and to update code against". Them changing framework internally, changing their mind on naming or structures and even if it's objectively better naming or structure (it's usually really not) discard the time I spend understanding their previous work and having my own code matches their previous implementation. This is very very bad engineering.

The devils is in the details. The 2 real examples from above (`inline_products` and `ps` param) are fair speculations that they are indeed a depreciation, but these 2 are not on our side, may actually come back tomorrow even if it's a 1% chance, and we can only give our best guesstimations to our customers. I am obviously not in love with that and I would rather a very beautiful and very detailed timeline of what's happening to share with our customers, but it's absurd to think we can control the roadmap of Google or DuckDuckGo - outside of us acquiring them.

**Comment by dsojevic** [comment]
> Our current policy is we don't depreciate things on our side.

No deprecations (i.e. backwards-compatible changes only) is a perfectly fine policy, especially given that we're not a versioned API.

Regarding 3rd-party changes that are out of our control, I would wager that every customer would understand that it's not our "fault" when associated APIs disappear, have different information, etc. so any reputational risk from that type of sudden deprecation/removal is near nil.

**Comment by Krugloff** [comment]
> The devils is in the details.

It seems like we already have a deprecation policy (even we don't depreciate things on our side). However, much of this information is scattered across GitHub issues and PRs. I suggest creating a wiki that consolidates existing use cases, examples, and exceptions. This would streamline future work and make the process more efficient. For example, we could include the work done when transitioning to the new Google page infinite scrolls and the deprecation of the unsupported `num` parameter.

**Comment by hartator** [comment]
Maybe the issue is with the word deprecation? What about naming all of these legacy instead of deprecated?

Deprecated seems intentional whereas legacy just happens. Which is closer definition of what's actually happening. That `inline_product` seems legacy now, but saying it's deprecated seems it's something we have done our side. Legacy also implies it's supported to the "best effort" we can do which it's the case, but it may not work anymore and be completely gone. It's also more acceptable to have a legacy feature coming back than a deprecated one.

Couple of IRL examples:

```
Legacy inline_product JSON

inline_product seems to have been retired by Google and may not work anymore. We recommend to rely on x from now on.
```

```
Legacy ps param

The ps param seems to have being retired by Ebay and is not working anymore. We recommend to use these params for pagination from now on.
```

We still have to rely on each engineer best judgment on a case-per-case basis to determine what is happening, make recommendation, and update documentation to highlight this seems legact. I am still very against a blanket required policy or checklists for these.

**Comment by marm123** [comment]
One of our customers pointed out that they got confused by the `deprecated` wording on the `next_page_token` documentation for Google Maps Reviews API. They thought that Google had deprecated the parameter, but it's still available with our API.

<img width="821" alt="image" src="https://github.com/user-attachments/assets/0ac0d2ec-f42b-4d5d-bb47-0010efb9348f">

However, in this case, maybe the issue is with wording, and we should be more clear that because Google deprecated the parameter, it's also no longer available with our API.

[Front](https://app.frontapp.com/open/cnv_1dw8cfoc?key=LDoDTAJVxbYJ7YfYp2oUnI1GCzkR_WUL) | [Documentation](https://app.frontapp.com/open/cnv_1dw8cfoc?key=LDoDTAJVxbYJ7YfYp2oUnI1GCzkR_WUL)
