### ISSUE TITLE
[Bing Search API] Scraping `generic events information` is not working

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#2016]
Upon testing, it looks like we're missing the events results when searching for a generic term like "events in ${city}

![CleanShot 2024-10-10 at 10 27 01](https://github.com/user-attachments/assets/37f3d4f3-d8a9-40c4-9d5a-9e30f8c91979)

Public links: [Playground 1](https://serpapi.com/playground?engine=bing&q=events+in+austin) | [Inspect](https://serpapi.com/searches/67073b57b4e8d6890a72f5d1/inspect)

Related issue: https://github.com/serpapi/public-roadmap/issues/1563

**Comment by mikemorcerf** [comment]
This design is new. I worked on [Bing Search API - Create Parser to scrape Bing Events Results](https://github.com/serpapi/SerpApi/pull/5284) using the same query, and the result box was different.
I'm aware now this box result could also be used for other types of queries, such as [samsung subsidiaries](https://github.com/serpapi/public-roadmap/issues/1977)
The problem with changing the name would be having to reach out to [clients already using this feature](https://github.com/serpapi/public-roadmap/issues/1563) with `events_results` and decide on a more general name that would make more sense.

**Comment by mikemorcerf** [comment]
This issue is solved. Now Bing Search API can scrape `generic events information`.
