### ISSUE TITLE
[Google Product Result API] Missing `title`, `reviews`, and `rating`

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#2018]
Results from the Google Product Results API are missing the following attributes:
* `title`
* `reviews`
* `rating`

![image](https://github.com/user-attachments/assets/7ce9cef2-8c0f-4b76-8158-b0cf53b439a0)

![image](https://github.com/user-attachments/assets/ccfb65f8-45eb-432e-94ff-a93bd6a37847)

[Playground](https://serpapi.com/playground?q=dyson+v8&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+as_sitesearch+highlight+stick+lr+as_qdr+votes+site+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+rlz+ijn) | [Playground](https://serpapi.com/playground?q=AW3423DW&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+as_sitesearch+highlight+stick+lr+as_qdr+votes+site+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+rlz+ijn) | [Documentation](https://serpapi.com/product-result)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071062?view=List) | [Search Inspect](https://serpapi.com/searches/67083a5c59f911b4f5fd8b46/inspect) | [Search Inspect](https://serpapi.com/searches/67083c67eda5f5bda451bd29/inspect)

**Comment by btaunt** [comment]
We now properly parse the `product_result`: `title`, `reviews` and `rating` for these newer Google layouts.

[Playground example 1](https://serpapi.com/playground?q=dyson+v8&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+as_sitesearch+highlight+stick+lr+as_qdr+votes+site+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+rlz+ijn)
[Playground example 2](https://serpapi.com/playground?q=AW3423DW&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+as_sitesearch+highlight+stick+lr+as_qdr+votes+site+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+rlz+ijn)
