### ISSUE TITLE
[Yelp Place API] - Not returning results all of a sudden

### ISSUE THREAD

**Issue by mattirvin** [serpapi/public-roadmap#2020]
Yelp place api was previously returning accurate results but now returns responses for all places with valid place urls like this:

{
  "search_metadata": {
    "id": "67086e02e92456ed1b988c78",
    "status": "Success",
    "json_endpoint": "https://serpapi.com/searches/713cd05830242dbb/67086e02e92456ed1b988c78.json",
    "created_at": "2024-10-11 00:14:58 UTC",
    "processed_at": "2024-10-11 00:14:58 UTC",
    "yelp_place_url": "https://www.yelp.com/biz/9FXjedQeFtjb18s0xD2wgA",
    "raw_html_file": "https://serpapi.com/searches/713cd05830242dbb/67086e02e92456ed1b988c78.html",
    "total_time_taken": 3.85
  },
  "search_parameters": {
    "engine": "yelp_place",
    "place_id": "9FXjedQeFtjb18s0xD2wgA"
  },
  "search_information": {
    "place_results_state": "Fully empty"
  },
  "error": "Yelp Place hasn't returned any results for this query."
}

or this:

{
  "search_metadata": {
    "id": "67086e0272e5c4224141aadc",
    "status": "Success",
    "json_endpoint": "https://serpapi.com/searches/499e7e0327208bee/67086e0272e5c4224141aadc.json",
    "created_at": "2024-10-11 00:14:58 UTC",
    "processed_at": "2024-10-11 00:14:58 UTC",
    "yelp_place_url": "https://www.yelp.com/biz/1xuHBe3Tk-kKFM4gBPHSRQ",
    "raw_html_file": "https://serpapi.com/searches/499e7e0327208bee/67086e0272e5c4224141aadc.html",
    "total_time_taken": 2.18
  },
  "search_parameters": {
    "engine": "yelp_place",
    "place_id": "1xuHBe3Tk-kKFM4gBPHSRQ"
  },
  "place_results": {
    "logo": "https://s3-media0.fl.yelpcdn.com/businessregularlogo/eg_RvrH1vmWy-ZhNpNPLSg/ms.jpg"
  }
}

**Comment by hilmanski** [comment]
Thank you very much, @mattirvin for your report. We apologize for this issue. We'll investigate this further then let you know once we have a fix.

Context for SerpApi team:
The results were displayed on the view but not on our response
![CleanShot 2024-10-11 at 08 59 54](https://github.com/user-attachments/assets/69dbab09-a7b2-4565-a396-836e6cfbb782)


[Inspect 1](https://serpapi.com/searches/67086e02e92456ed1b988c78/inspect) |  [Inspect2](https://serpapi.com/searches/67086e0272e5c4224141aadc/inspect)

**Comment by tanys123** [comment]
Thanks @mattirvin for reporting the issue 👍. We have deployed a fix, it is now returning results. Please try it out with your query and feel free to reach out to us if you have other quesiton.

<img width="1382" alt="Screenshot 2024-10-11 at 9 05 59 PM" src="https://github.com/user-attachments/assets/fb58957e-7735-4433-b05a-9584834dfad6">
