### ISSUE TITLE
[Google Trends API] Export to csv is not working

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#2025]
A customer reported that using `csv=true` returns empty results for their Google Trends search. I can see that the results is available on Google Trends website: https://trends.google.com/trends/explore?date=today%205-y&geo=JP&q=Coffee&hl=ja

Public links: [Playground](https://serpapi.com/playground?engine=google_trends&q=Coffee&hl=ja&geo=JP&data_type=TIMESERIES&tz=420&date=today+5-y&hl=ja&newPara=hl)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071118?view=List) | [Search Inspect](https://serpapi.com/searches/670b3b6e708e2e1b5a443bd2/inspect)

**Comment by tanys123** [comment]
We have deployed a fix to the issue.

<img width="1295" alt="Screenshot 2024-10-15 at 12 58 57 PM" src="https://github.com/user-attachments/assets/d979b587-bbb4-437f-9074-519b0c9e7768">
