### ISSUE TITLE
[Google Search API] Scrape word limitation message

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#2029]
A high-volume customer requested that we scrape the word limitation message Google Search shows when including more than 32 keywords in the search query. We currently don't provide this information in the response from our Google Search API:

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/41b509d2-30fc-4908-9f0e-0a3d4f833e19">

[Playground](https://serpapi.com/playground?q=river+glass+shadow+journey+eclipse+dream+tower+flame+whisper+breeze+canyon+rhythm+ocean+lantern+thunderstone+forest+echo+bridge+dusk+sapphire+mirror+frost+ember+cloud+wanderer+flame+orchid+sandstorm+pearl+twilight+starfire+crystal+tide+raven+wildfire+harmony+moonstone+cascade&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&newPara=chips) | [Inspect](https://serpapi.com/searches/670d421d4677bf2b987432e0/inspect)

[Front](https://app.frontapp.com/open/cnv_1csyfuu4?key=5eug94LZL50xhlTxeDWMRV6ECTlGwzRD)

**Comment by btaunt** [comment]
We now parse this information as:

- `word_limitation`
- `query_words_ignored_from`

This data is rendered under the existing `search_information`:

<img width="866" alt="Screenshot 2024-10-24 at 3 40 53 PM" src="https://github.com/user-attachments/assets/b80472b7-de94-481d-815c-6dddc29d8981">

---

[Playground Example](https://serpapi.com/playground?q=river+glass+sunshine+shadow+journey+eclipse+dream+tower+flame+whisper+breeze+canyon+rhythm+ocean+lantern+thunderstone+forest+echo+bridge+dusk+sapphire+mirror+frost+ember+cloud+wanderer+flame+orchid+sandstorm+pearl+twilight+starfire+crystal+tide+raven+wildfire+harmony+moonstone+cascade&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=chips+as_sitesearch+votes+site+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz)
