### ISSUE TITLE
[Google Search API] Weather Answer Box is missing Detailed Temperature Data

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#203]
![temp](https://user-images.githubusercontent.com/73674035/177176783-39af822a-a09b-4198-b401-46670bafd7b6.png)

[Inspect](https://serpapi.com/searches/62c2fbe61d986edddb76ec4b/inspect)
[Playground](https://serpapi.com/playground?q=What%27s+the+weather+in+Dallas%3F&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&newPara=stick+highlight+lr+async+as_qdr)

The graph seems to contain detailed information throughout different time frames about temperatures.

**Comment by kagermanov27** [comment]
![svg](https://user-images.githubusercontent.com/73674035/177305437-658ec5f5-debb-4236-b8c2-91ba9e548f35.png)
This element is being loaded by a secondary call. If someone can trigger the page to load the items without further calls, take the issue. I tried and failed.

**Comment by ilyazub** [comment]
> This element is being loaded by a secondary call. If someone can trigger the page to load the items without further calls, take the issue. I tried and failed.

The parent node moves this SVG on click on different days.

https://user-images.githubusercontent.com/282605/195520678-6255723c-4896-4970-8cd4-abbdf9f3ef55.mp4

All of the data is in the `google.pmc.wobnm.wobhl`.

![image](https://user-images.githubusercontent.com/282605/195525644-043c9f82-de3f-405f-8de9-717e4d624b00.png)

It's in inline JavaScript.

![image](https://user-images.githubusercontent.com/282605/195525763-022c7357-ce20-4ba4-86a1-81ce7e44d6c9.png)

**Comment by aciddjus** [comment]
Resolved in: https://github.com/serpapi/SerpApi/pull/3797, https://github.com/serpapi/SerpApi/pull/2876 and https://github.com/serpapi/SerpApi/pull/2875
