### ISSUE TITLE
[DuckDuckGo Search API] Empty results on a valid search

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#2031]
A high-volume customer reported we returned an empty result on a valid search.

![CleanShot 2024-10-15 at 08 40 39@2x](https://github.com/user-attachments/assets/563975b2-78a8-497e-be3e-84cb4f3cce75)

I can't replicate the issue on the playground.

Public links: [Playground 1](https://serpapi.com/playground?engine=duckduckgo&kl=us-en&q=towed+car+site%3Ahttps%3A%2F%2Flapuente.org%2F)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071173?view=List) | [Search Inspect](https://serpapi.com/searches/670da6dc8de63c39ed318b51/inspect)

**Comment by tdalwayson** [comment]
We've been successfully performing this same search type (site:domain + search terms) for over a year using both Duck Duck Go and Google APIs. We are currently still performing this same search type successfully using Google API. The DuckDuckGo issue is very recent, I was able to locate successful DDG searches from earlier today (search ID: 670d66e431030013f94c9c32). If you perform a site search directly using the DDG search engine, results are returned successfully.

**Comment by hilmanski** [comment]
Thank you very much for your additional context, @tdalwayson. We'll investigate this issue.

**Comment by hilmanski** [comment]
Another high-volume customer reported this issue.

[Inspect](https://serpapi.com/searches/670f103021b01bf523d59e40/inspect)

**Comment by Freaky** [comment]
A fix for this has been deployed and is being monitored.  Response times are somewhat elevated - work is ongoing to improve this..

**Comment by Freaky** [comment]
DuckDuckGo Search API response times have returned to normal.

![2031-ddg-response-times](https://github.com/user-attachments/assets/43438ed7-1823-464a-9b92-a6d07d2df5e0)
