### ISSUE TITLE
[Google Maps API] Scrape order online options link for place result

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#2033]
We scrape the order online link for Google Maps search `local_results` (related: https://github.com/serpapi/public-roadmap/issues/897), but not when the results are a single business as `place_results`.

Actual Google Maps:

![image](https://github.com/user-attachments/assets/3ecfc271-1446-4bc5-b837-487a49a0a1db)

Our result:

![image](https://github.com/user-attachments/assets/7ab4bd74-8bdc-4450-8e3b-aaa2e31a2d9a)

Public links: [Playground 1](https://serpapi.com/playground?engine=google_maps&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&place_id=ChIJzUb1UkRbW0gRdlt9Ge2ZwwI&type=place) | [Google Maps](https://www.google.com/maps/place/Pizza+Planet+2/@52.629518,-8.6657801,17z/data=!3m1!4b1!4m6!3m5!1s0x485b5b4452f546cd:0x2c399ed197d5b76!8m2!3d52.629518!4d-8.6657801!16s%2Fg%2F1hc7n5gff?hl=en&entry=ttu&g_ep=EgoyMDI0MTAwOS4wIKXMDSoASAFQAw%3D%3D)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071188?view=List) | [Inspect](https://serpapi.com/searches/670e4d1281bab78cc8c357ee/inspect)

**Comment by btaunt** [comment]
I'm not sure I am able to replicate this (unless I am misunderstanding). The Playground example provided has the `order_online_link` under `place_results`:

```
"order_online_link": "https://food.google.com/chooseprovider?restaurantId=/g/1hc7n5gff&g2lbs=AOHF13kZ0YbwZ4iaezQQyGL2CfMOcfRBrnUTCICrDQmN0Bg0ILkW7YygChy0_1fTpLT7ybPrFEIuE6oTKsVN9kujNqYkTrL5eQ%3D%3D&hl=en-US&gl=us&fo_m=MfohQo559jFvMUOzJVpjPL1YMfZ3bInYwBDuMfaXTPp5KXh-&utm_source=tactile&gei=e-oPZ4b7L-WMwbkP4_OhqAQ&ei=e-oPZ4b7L-WMwbkP4_OhqAQ&fo_s=OA,SOE&opi=79508299&foub=mcpp",
```

[JSON Endpoint](https://serpapi.com/searches/943bcfacf1243db2/670fea7954163d8e034c3134.json)

cc. @alexbarron

**Comment by alexbarron** [comment]
> I'm not sure I am able to replicate this (unless I am misunderstanding). The Playground example provided has the `order_online_link` under `place_results`:
> 
> ```
> "order_online_link": "https://food.google.com/chooseprovider?restaurantId=/g/1hc7n5gff&g2lbs=AOHF13kZ0YbwZ4iaezQQyGL2CfMOcfRBrnUTCICrDQmN0Bg0ILkW7YygChy0_1fTpLT7ybPrFEIuE6oTKsVN9kujNqYkTrL5eQ%3D%3D&hl=en-US&gl=us&fo_m=MfohQo559jFvMUOzJVpjPL1YMfZ3bInYwBDuMfaXTPp5KXh-&utm_source=tactile&gei=e-oPZ4b7L-WMwbkP4_OhqAQ&ei=e-oPZ4b7L-WMwbkP4_OhqAQ&fo_s=OA,SOE&opi=79508299&foub=mcpp",
> ```
> 
> [JSON Endpoint](https://serpapi.com/searches/943bcfacf1243db2/670fea7954163d8e034c3134.json)
> 
> cc. @alexbarron

@btaunt Thanks for looking into this. I also can't reproduce it anymore.

Here's the inspect link for the search where I encountered the issue: https://serpapi.com/searches/670e4d1281bab78cc8c357ee/inspect

Anything jump out there as being different than our more recent attempts?

**Comment by alexbarron** [comment]
@btaunt Yeah perhaps it was just a blip. I'll close this for now, but we'll reopen it if we come across the issue again. Thank you for your investigation.

No need to follow up with customers since this only came up while I was investigating a customer's request for the Google Food link contents the Order Online button takes you to.
