### ISSUE TITLE
[Google Food API] Scrape food delivery and pickup/collection options page

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#2034]
We currently scrape the order link from Google Food search results. This takes the user to a Google Food order options page with external links to food ordering platforms. We currently don't scrape the contents of this page.

Collection/pickup options:

![image](https://github.com/user-attachments/assets/b47638ee-15ae-4021-ab41-f977a75702b6)

Delivery options:

![image](https://github.com/user-attachments/assets/e799073a-9f05-4887-b0e4-824588bead66)

Our Google Food search results:

![image](https://github.com/user-attachments/assets/0acc279d-d0cd-4fa1-b428-bce7604d4a4c)

Public links: [Google Food Search Results Playground](https://serpapi.com/playground?engine=google_food&q=pizza+planet+2&gl=us&hl=en) | [Google Food Order Options](https://food.google.com/chooseprovider?restaurantId=/g/1hc7n5gff&g2lbs=AOHF13lgRw_Ru76SSf300LMJPnYRo3x3PydcGPGCGrh55FWtTqCktlYSrqt1dN_cEmp0foZ20DVL3zuKalO0WK1vlzcaeDxquw%3D%3D&hl=en-GB&gl=uk&fo_m=MfohQo559jFvMUOzJVpjPL1YMfZ3bInYwBDuMfaXTPp5KXh-&gei=P00OZ-7WItmJ7NYP0dPayQY&ei=P00OZ-7WItmJ7NYP0dPayQY&opi=79508299&foub=mcpp&sei=Cb2GdWHTnYG1Ee__NQ4I8is6&utm_campaign&utm_source=tactile&addressId&orderType=1&partnerId&fulfillmentTime&menuSearchQuery&cartId&fo_s=OA&dineInLocationId)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071188?view=List) | [Related PR 1](https://github.com/serpapi/public-roadmap/issues/2033) | [Related PR 2](https://github.com/serpapi/public-roadmap/issues/890)

**Comment by dsojevic** [comment]
Closing this as Not Planned as the Google Food service has been ended: https://github.com/serpapi/public-roadmap/issues/2186
