### ISSUE TITLE
[Google Shopping API] Issues with `price`, `extracted_price` and `source` fields for `inline_shopping_results` items

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#2037]
An Enterprise customer reported that the `price` field in the response from our Google Shopping API is not formatted correctly when the item is discounted. They also reported that the `extracted_price` is missing and the `source` field is not capitalized as in the actual HTML.

I was able to reproduce it in the Playground:

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/ab45c236-985f-490e-8ce9-a1f00d5aefce">

[Playground](https://serpapi.com/playground?engine=google_shopping&q=loveseat+sofa&gl=us&hl=en&direct_link=true&device=desktop&no_cache=true&direct_link=true&newPara=direct_link) | [Inspect](https://serpapi.com/searches/670fef7ab6ed337b4ea6f3b3/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071240?view=List)

**Comment by raju249** [comment]
Hey @martin-serpapi - How can I work on this issue?

Would love to contribute with my experience in SERP APIs. Have worked on Shein Search, Shein Product and bunch of other APIs for Google jobs, search, play store, etc.

**Comment by btaunt** [comment]
This has been updated. We now properly parse `price` and `extracted` price when discounts are present.

As for capitalizing `source`: this change was made in a previous PR. To avoid breaking existing custom code we have opted to leave it set in lowercase.

[Playground Example](https://serpapi.com/playground?engine=google_shopping&q=loveseat+sofa&gl=us&hl=en&direct_link=true&device=desktop&no_cache=true&direct_link=true&newPara=direct_link)
