### ISSUE TITLE
[Google Trends Trending Now API] Scrape trend's `status`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#2038]
One of our users requested us to scrape the `status` of the trend. I've encountered only `Active` or no status at all.

![image](https://github.com/user-attachments/assets/915c8084-56c0-4951-8ee6-944b56b87420)

Public links: [Playground](https://serpapi.com/playground?engine=google_trends_trending_now&geo=US&hl=en) | [Google Trends Trending Now](https://trends.google.com/trending)

Requested by @githubfan21 in https://github.com/serpapi/public-roadmap/issues/1828#issuecomment-2417412240

**Comment by githubfan21** [comment]
Is there an ETA to have this added to json?

**Comment by sonika-serpapi** [comment]
> Is there an ETA to have this added to json?

@githubfan21 Unfortunately, it is difficult to provide an exact ETA. Our team will work on this and we will reach out to you once this has been implemented. Thank you for your patience meanwhile.

**Comment by tanys123** [comment]
Hi @githubfan21, You can already determine if a trending search is active by checking if the `end_timestamp` is absent. If the `end_timestamp` is present, the search is no longer active; otherwise, it remains active.

We will still be adding `active` field to the JSON for easier interpretation. The changes are currently under review.

**Comment by tanys123** [comment]
We have deployed an update to Google Trends Trending Now API, which adds `active` to the result. Find out more in the [documentation](https://serpapi.com/google-trends-trending-now).

<img width="1351" alt="Screenshot 2024-11-07 at 2 46 37 PM" src="https://github.com/user-attachments/assets/c0c96574-e47b-4569-b030-d5746a109c84">

**Comment by sonika-serpapi** [comment]
@githubfan21 Tagging you for visibility. We have implemented this feature. Feel free to check it out and reach out to us for any questions or concerns.
