### ISSUE TITLE
[Google Trends Trending Now API] Support filtering by status

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#2039]
One of our users requested us to scrape results based on the `status` (`Active` or not)

![image](https://github.com/user-attachments/assets/fa479567-480b-4adf-94e5-62c0f6757e73)

Public links: [Google Trends Trending Now](https://trends.google.com/trending?status=active)

Requested by @githubfan21 in https://github.com/serpapi/public-roadmap/issues/1828#issuecomment-2417412240

**Comment by tanys123** [comment]
Hi @githubfan21, we are adding `active` field to the JSON (as [mentioned](https://github.com/serpapi/public-roadmap/issues/2038#issuecomment-2421682972)). At the meantime, you can find all the active trending search by checking if `end_timestamp` is absent. All the data is return in single request, so you can just do the filtering on your end. This is also how the Google Trends' Trending Now page works.

**Comment by marm123** [comment]
Hi @githubfan21, I'm tagging you to let you know that we introduced a new `active` attribute in the Google Trends Trending API response. You can now filter your results on your end by differentiating `active=true` from `active=false`
