### ISSUE TITLE
[Google Search API] Missing hours on knowledge graph

### ISSUE THREAD

**Issue by dsojevic** [serpapi/public-roadmap#2041]
Searches with a location knowledge graph that have hours present will return `raw_hours` with the expected value and an empty `hours` hash (unexpected)

## Example 1
![image](https://github.com/user-attachments/assets/f41148be-9ed2-4c35-89c7-2dfce18416e6)

Hours are available in a modal (alongside supplementary hours for "Zoo Events" in this example):
![image](https://github.com/user-attachments/assets/a15daf43-5453-49f9-9013-4306fcc4264f)

## Example 2
![image](https://github.com/user-attachments/assets/1b6b001c-e680-491b-9deb-dc06b087a464)

Hours are available inline:
![image](https://github.com/user-attachments/assets/5d275e23-449b-4cc2-9119-070c172cbbd8)

Public links: [Playground 1](https://serpapi.com/playground?q=melbourne+zoo&location=Melbourne%2C+Victoria%2C+Australia&google_domain=google.com.au&gl=au&hl=en) | [Playground 2](https://serpapi.com/playground?q=Epoch+Coffee+far+west&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)

Internal links: [Search Inspect 1](https://serpapi.com/searches/67105f498b7ba7ad75c2e621/inspect) | [Search Inspect 2](https://serpapi.com/searches/6710615559f91177c83b32ff/inspect)

**Comment by raju249** [comment]
Hi team, I am interested and would like to contribute to the SerpApi codebase. How can I best move forward? 

I have experience in SERP APIs in general and have worked on Shein search and other google serp Apis in the past.

**Comment by marm123** [comment]
Hi, @raju249, thanks for reaching out. Unfortunately, this issue must be resolved internally, as the code is not open-source. Feel free to share your thoughts and suggestions if you feel like it!

If you'd like to contribute directly to one of our respos, feel free to explore our [public repositories](https://github.com/orgs/serpapi/repositories?q=visibility%3Apublic+archived%3Afalse). Perhaps you can find something that can be improved. 

Thank you very much!

**Comment by raju249** [comment]
Thanks for the reply @marm123 

I was thinking to apply for a job at SerpApi. I think I fit the fullstack role at SerpApi. wdyt? I found https://github.com/serpapi/code-challenge in your repos. I think I can solve the problem described in the code challenge.

**Comment by marm123** [comment]
Sure @raju249, you can see all of our job openings on our [careers page](https://serpapi.com/careers). Feel free to check them out and apply at careers@serpapi.com.

If you have any questions or concerns about SerpApi, feel free to reach us out at contact@serpapi.com. We'll be happy to answer your questions. Let's not continue the offtopic discussion here, as this thread is about a specific bug.

Thank you.

**Comment by NateSkiles** [comment]
A high-volume customer reported this issue:

[Front](https://app.frontapp.com/open/cnv_1dhv7f6k?key=eEqUtcf3S6kdOY3VLKjvDN4cwCvv0kV0)

**Comment by Ovi** [comment]
We're now parsing `hours` correctly:
<img width="1723" alt="image" src="https://github.com/user-attachments/assets/615fc584-c231-45a0-9940-9fc4a6d16495">

Public links: [Playground 1](https://serpapi.com/playground?q=melbourne+zoo&location=Melbourne%2C+Victoria%2C+Australia&google_domain=google.com.au&gl=au&hl=en) | [Playground 2](https://serpapi.com/playground?q=Epoch+Coffee+far+west&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)

**Comment by ishiharaf** [comment]
@Ovi We're getting a new error related to the changes from this PR: https://serpapi.airbrake.io/projects/179926/groups/3919086784011396781/notices/3919086793419182672?tab=notice-detail
