### ISSUE TITLE
[Google Shopping API] Scrape Google Tracking Link for Inline Results

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#2049]
The `inline_results` in Google Shopping responses have a Google domain tracking URL, which when opened resolves to the product direct link. 
<br>

<img width="1065" alt="Screenshot 2024-10-22 at 4 00 00 PM" src="https://github.com/user-attachments/assets/80dc3ea0-51e4-4dcb-9453-e78959b71960">
<br><br>

 We used to return this link in the `link` field, but following a [customer's request](https://github.com/serpapi/public-roadmap/issues/1954) we now instead return the product direct link in `link`. The customer who requested that has requested that we additionally provide the Google tracking link again. 
<br>

<img width="1324" alt="Screenshot 2024-10-22 at 4 02 12 PM" src="https://github.com/user-attachments/assets/abba0cbe-c9f2-488d-aac4-99000076ea71">
<br><br>

Public links: [Playground 1](https://serpapi.com/playground?engine=google_shopping&q=iPhone&location=Seattle%2C+Washington%2C+United+States&gl=us&hl=en&no_cache=true) | [Playground 2](https://serpapi.com/playground?engine=google_shopping&q=iPhone&gl=us&hl=en&direct_link=true&device=desktop&no_cache=true) | [Documentation](https://serpapi.com/inline-shopping-results)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071398?view=List) | [Search Inspect 1](https://serpapi.com/searches/67182c09f922f6414869f66a/inspect)  | [Search Inspect 2](https://serpapi.com/searches/671824168a7c09ed2150d5be/inspect)

**Comment by schaferyan** [comment]
The customer mentioned they'd also like to get a Google tracking URL for `shopping_results`. I let them know this may not be possible since no such URL seems to be available when viewing the new Google Shopping layout in the browser.

**Comment by KBCG** [comment]
@schaferyan  thank you. This is cruclal for us so anything that can be done and fast would be great!

**Comment by KBCG** [comment]
@schaferyan  Ryan-- do you have a potential ETA when this will be in production?  Appreciate it a lot!

**Comment by schaferyan** [comment]
Thanks for following up @KBCG, we don't have an ETA on this but I can tell you that a solution has been implemented and this is currently in the review process. We'll follow up when it's ready. Thanks for your patience in the meantime!

**Comment by btaunt** [comment]
We now parse the `tracking_link` alongside our existing `link` for `inline_shopping_results`:

<img width="1194" alt="Screenshot 2024-10-26 at 4 01 16 PM" src="https://github.com/user-attachments/assets/2e701c45-088e-4474-a7d1-47f6054b29dc">

---

[Playground Example](https://serpapi.com/playground?engine=google_shopping&q=ipad&gl=us&hl=en&no_cache=true&newPara=direct_link) | [Updated Docs](https://serpapi.com/inline-shopping-results#api-examples-results-for-q-iphone)

cc. @schaferyan @KBCG

**Comment by hilmanski** [comment]
Hi @btaunt,

I haven't been able to retrieve the `tracking_link`. 

[Inspect](https://serpapi.com/searches/671ebe854300ce1f9963c3c2/inspect) | [Inspect](https://serpapi.com/searches/671ebf61a251046ad7639456/inspect)

**Comment by hilmanski** [comment]
Hi, @KBCG, tagging you for visibility.

**Comment by KBCG** [comment]
@hilmanski  @schaferyan  @btaunt  thank you all  for the quick respond
