### ISSUE TITLE
Share cache between team members

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#2050]
A potential Enterprise customer reached out with a request to implement a shared cache between team members' accounts.

Currently a cached request is served if it is made by the same account which made it before (ie: requests in cache are linked based on account (User's ID, not on the team). Every team member has their own cache.

Can we implement a common cache for the team?

Internal links: [Front](https://app.frontapp.com/open/cnv_1cbgf5ng?key=CuXkJqGxt1U7jCfy-qn-qBYOAR3Gn-Rp)

**Comment by hartator** [comment]
I am closing this because it will be surprising to be served a search from another user.

Maybe recommend to the customer to use a cache system on their side?

**Comment by sanj-directbooker** [comment]
> I am closing this because it will be surprising to be served a search from another user.

This is a valid view.  However, I'd counter that this should be mechanism that's pretty advanced and configured at the level of the account.  Make simple things simple, but complex things *possible.

**Comment by hartator** [comment]
Yes, our cache system is pretty basic. 

It is possible indeed, but it seems a little outside of our mission, here at SerpApi. Advanced caching mechanism seems very CDN-y and outside of our mission to map search data in a reliable, comprehensive, and super easy API.

The goal of our current caching is to avoid obvious mistakes - like trying the exact same searches 1,000 times -, avoid accidental duplicates, and provide speed up when a system has some race condition issues.
