### ISSUE TITLE
Plan cancellation email not sent to customer

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#2053]
A customer reported that they did not receive plan cancellation emails. 
Their plan was cancelled by us upon request.

They mentioned that this makes it hard to track whether the plan was successfully cancelled or not.

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071425?view=List)

**Comment by hilmanski** [comment]
It's maybe related to this issue https://github.com/serpapi/SerpApi/issues/4845#issuecomment-2401156384

**Comment by sonika-serpapi** [comment]
> It's maybe related to this issue [serpapi/SerpApi#4845 (comment)](https://github.com/serpapi/SerpApi/issues/4845#issuecomment-2401156384)

Yes @hilmanski, thank you, I read through the thread there and I have mentioned it there too.

**Comment by ishiharaf** [comment]
This has been fixed for manually cancelled plans. Users should now receive an email like the one below:

![image](https://github.com/user-attachments/assets/956bf351-bbd3-4f13-8410-19e566a84ac8)
