### ISSUE TITLE
[Google Shopping API] Failed search for `gl=jp` (Japan)

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#2065]
A high-volume customer reached out that searches using `gl=jp` on Google Shopping API are failing.

Public links: [Playground 1](https://serpapi.com/playground?engine=google_shopping&q=new+balance+Mercari&gl=jp&newPara=direct_link) | [Playground 2](https://serpapi.com/playground?engine=google_shopping&q=9060+new+balance+%E3%83%A1%E3%83%AB%E3%82%AB%E3%83%AA+-+Mercari&gl=jp&hl=en&device=desktop&newPara=direct_link)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071535?view=List) | [Inspect](https://serpapi.com/searches/671ee939a5aae9ca3067e065/inspect)

Upon testing, my searches are stuck in `processing`
[Inspect](https://serpapi.com/searches/671ef72dc0028ed75c4ec9ed/inspect)  | [Inspect](https://serpapi.com/searches/671ef6adef60cb4dfe828cc3/inspect)

**Comment by tanys123** [comment]
We have deploy a fix to the issue. Results are returning for `gl=jp`.

<img width="1462" alt="Screenshot 2024-10-29 at 3 04 24 PM" src="https://github.com/user-attachments/assets/0d6e5dff-e9fa-4582-9b5b-1a8714583950">

**Comment by 0xShin0221** [comment]
Thanks @hilmanski @tanys123

**Comment by hilmanski** [comment]
You're very welcome, @0xShin0221 ! 

Have a great day!
