### ISSUE TITLE
[Google Shopping API] Missing direct links when paginating

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#2067]
When setting the `start` parameter with `direct_link=true`, the `link` attribute is not returned for shopping results.

<img width="1640" alt="image" src="https://github.com/user-attachments/assets/591203a1-3b70-4608-a1ac-c48ef05c53de">

[Playground (with start)](https://serpapi.com/playground?engine=google_shopping&q=coffee&gl=us&hl=en&direct_link=true&start=0&device=desktop&no_cache=true)

<img width="1650" alt="image" src="https://github.com/user-attachments/assets/4247d878-cbec-4d81-8c9e-fcb81e68c846">

[Playground (without start)](https://serpapi.com/playground?engine=google_shopping&q=coffee&gl=us&hl=en&direct_link=true&device=desktop&no_cache=true)

It appears that the `filters` array is also missing when including a `start` parameter.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071398?view=List)

**Comment by schaferyan** [comment]
Thank you @NateSkiles. Though this is likely due to changes on Google's side, I don't think Google is rolling out another new layout already. This appears to be related to the use of the `start` parameter.

Note that the examples above are not exactly the same, as the one with no link present includes `num=30` and `start=0`. 

After testing in the Playground, it appears that searches with `start` are always missing the `link` fields. Searches without `start` seem to work as expected.

[Playground (with `start`)](https://serpapi.com/playground?engine=google_shopping&q=coffee&gl=us&hl=en&direct_link=true&start=0&device=desktop&no_cache=true)
[Playground (without `start`)](https://serpapi.com/playground?engine=google_shopping&q=coffee&gl=us&hl=en&direct_link=true&device=desktop&no_cache=true)

**Comment by schaferyan** [comment]
@Krugloff is it possible this is related to the fix for https://github.com/serpapi/public-roadmap/issues/1858?

**Comment by KBCG** [comment]
@schaferyan  I just tried running without the start parameter and it returned the link

**Comment by schaferyan** [comment]
@KBCG good to hear. Yes, it does seem to return the `link` when omitting `start`. I hope it's a viable workaround for you while we look into this further!

**Comment by alexbarron** [comment]
Customer noted this is a high priority issue for them:

[Front](https://app.frontapp.com/open/cnv_1bznnrrw?key=nkOQCsxu1rzzG1xmcwEJ1aUMzmlP285H)

**Comment by Krugloff** [comment]
@schaferyan 

> is it possible this is related to the fix for https://github.com/serpapi/public-roadmap/issues/1858?

I'm afraid so, since we're using the new layout :(

**Comment by Krugloff** [comment]
Direct links have been restored.

<img width="1450" alt="image" src="https://github.com/user-attachments/assets/ac0f9583-2d92-47b0-b62b-c8225ea687c8">

**Comment by KBCG** [comment]
Hi @Krugloff @alexbarron @schaferyan @NateSkiles  -- Looks like the issue is still happening. We are getting mixed results when omitting the start parameter. We are not getting any results when start parameters is present.

**Comment by NateSkiles** [comment]
Hi @KBCG, thanks for reaching out! Can you provide the search ID for a recent search where you observed this?

After testing this a bit, I haven't yet been able to reproduce this issue.

Without `start`:

https://serpapi.com/playground?engine=google_shopping&q=Coffee&direct_link=true&no_cache=true&direct_link=true&newPara=direct_link

With `start`:

https://serpapi.com/playground?engine=google_shopping&q=Coffee&direct_link=true&start=10&no_cache=true&direct_link=true&newPara=direct_link

**Comment by NateSkiles** [comment]
@KBCG Gotcha, thank you for that context. As I mentioned above, I'm not able to reproduce this with or without the `start` parameter, seen below:

![image](https://github.com/user-attachments/assets/aefc96ee-7db1-4b1a-8c89-3ff873efdb5a)

https://serpapi.com/playground?engine=google_shopping&q=Playstation+5&direct_link=true&no_cache=true&direct_link=true&newPara=direct_link

---

Can you please share the search ID of a search where you have observed this behavior? It can be found at https://serpapi.com/searches or in the `search_metadata` block of the JSON response.

**Comment by Krugloff** [comment]
@KBCG @NateSkiles A new [issue](https://github.com/serpapi/public-roadmap/issues/1889) has been opened. It’s not related to the start parameter.

**Comment by NateSkiles** [comment]
Agreed, @Krugloff. I haven't been able to reproduce this, its likely the new issue we are investigating, as that has been popping up sporadically over the past week.
