### ISSUE TITLE
[Google Search API] `rich_snippet` is not scraped

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#2071]
One of our high-volume customers reported that we're not scraping the `rich_snippet`, which we did before:

<img width="1671" alt="image" src="https://github.com/user-attachments/assets/750b05e1-9fb8-4438-a789-190d167e3277">

This is the same bug as the one reported and fixed a while ago: https://github.com/serpapi/public-roadmap/issues/1332

Public links: [Playground 1](https://serpapi.com/playground?q=site%3Alinkedin.com%2F+John+Doe+IT&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Playground 2 ](https://serpapi.com/playground?q=site%3Alinkedin.com%2F+John+Doe+architect&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)

Internal links: [Front](https://app.frontapp.com/open/cnv_1dnswr8c?key=M73zGZmC9NErmXYhjgpBuRe2saHfE9dF) | [Search Inspect 1](https://serpapi.com/searches/6720ea55c76a223d6a49d8fc/inspect) | [Search Inspect 2](https://serpapi.com/searches/6720e9ad1adaf415180bb2ef/inspect)

**Comment by btaunt** [comment]
We now properly parse the `rich_snippet` with this new layout change for `organic_results`:

<img width="743" alt="Screenshot 2024-10-30 at 12 51 15 PM" src="https://github.com/user-attachments/assets/6efaf838-9e3f-4218-9501-4479cd69c77a">

---

[Playground](https://serpapi.com/playground?q=site%3Alinkedin.com%2F+John+Doe+IT&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_sitesearch+votes+site+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz)
