### ISSUE TITLE
[Google Search API] Scrape menu highlights

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#2073]
A customer requested to scrape the menu highlights shown for some searches recently on Google. 

Example: https://www.google.com/search?q=cote+miami&sourceid=chrome&ie=UTF-8

<img width="1148" alt="Screenshot 2024-10-29 at 3 51 40 PM" src="https://github.com/user-attachments/assets/ca95f77b-58df-4f33-8db0-10de0204fd4f">

In playground: https://serpapi.com/playground?q=cote+miami&location=San+Francisco+Bay+Area%2C+California%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+as_sitesearch+highlight+stick+lr+as_qdr+votes+site+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+rlz+ijn+interval
<img width="1262" alt="Screenshot 2024-10-29 at 3 54 52 PM" src="https://github.com/user-attachments/assets/1cdcd0c2-f208-4b87-b3eb-329373b2f85a">

Only available with some requests in some locations. Example: it did not show up when the location was Austin, Texas but showed up when the location was San Francisco Bay Area.

Public links: 
[Playground - With menu highlights](https://serpapi.com/playground?q=cote+miami&location=San+Francisco+Bay+Area%2C+California%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+as_sitesearch+highlight+stick+lr+as_qdr+votes+site+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+rlz+ijn+interval) 
[Playground - Without menu highlights](https://serpapi.com/playground?q=cote+miami&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+as_sitesearch+highlight+stick+lr+as_qdr+votes+site+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+rlz+ijn+interval) 
[Github Link With User Request](https://github.com/serpapi/public-roadmap/issues/1771)

Internal Links:
[Search Inspect - With menu highlights](https://serpapi.com/searches/672167ae2b5fa72ea6c54024/inspect)
[Search Inspect - Without menu highlights](https://serpapi.com/searches/6721661b9872174e09993e45/inspect)

**Comment by Alaa-abdulridha** [comment]
This issue now has been resolved:

Before fixing the issue (Production):

![image](https://github.com/user-attachments/assets/52eed778-7411-421e-9a4e-cebbaf2cb980)

After fixing the issue (Production):

![image](https://github.com/user-attachments/assets/0fe83176-f57e-4412-b1d5-d8b4bf0f9dd1)

**Comment by sonika-serpapi** [comment]
@SimonFernsR Thank you for requesting this feature. We now scrape the menu highlights.
