### ISSUE TITLE
[Google Search API] Scrape `Vehicles for sale` ads results

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#2076]
A high-volume customer requested that we scrape `Vehicles for sale` ads results. Currently we're not scraping this information:

<img width="1435" alt="image" src="https://github.com/user-attachments/assets/3b924fee-9078-4107-9c5f-00bfc599036f">

[Playground](https://serpapi.com/playground?q=2019+suvs+for+sale&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true) | [Inspect](https://serpapi.com/searches/6722678b6de1e4f67b87aa0f/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071635?view=List)

**Comment by btaunt** [comment]
We now parse `vehicles_for_sale` under the existing `ads` for Google Search API:

<img width="483" alt="Screenshot 2024-11-05 at 11 43 07 AM" src="https://github.com/user-attachments/assets/796371cb-9022-413b-a85e-dfee294f1444">

---

[Playground](https://serpapi.com/playground?q=2019+suvs+for+sale&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_sitesearch+votes+site+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz+interval) | [Documentation](https://serpapi.com/google-ads#api-examples-results-for-2019-suvs-for-sale)
