### ISSUE TITLE
[Google Shopping API] Broken serpapi_product_api link

### ISSUE THREAD

**Issue by Krugloff** [serpapi/public-roadmap#2078]
The `serpapi_product_api` includes a link that doesn't function correctly if the request includes a `start` parameter.

<img width="1454" alt="image" src="https://github.com/user-attachments/assets/f407bf6d-fc41-426e-a075-3366a95ca150">

This occurs because the `start` parameter is being copied to a different engine, leading to unexpected behavior (`google_product`).

```
require 'net/http'
require 'uri'
require 'oj'

api_key = ENV["API_KEY"]
query = ARGV[0] # "coffee"
DOMAIN = "http://localhost:3000"

url = "#{DOMAIN}/search.json?device=desktop&engine=google_shopping&gl=us&google_domain=google.com&hl=en&q=#{query}&start=10"

uri = "#{url}&api_key=#{api_key}&no_cache=true"
json = Oj.load(Net::HTTP.get(URI(uri)))

serpapi_product_api = json["shopping_results"].first["serpapi_product_api"]

uri = "#{serpapi_product_api}&api_key=#{api_key}&no_cache=true"
product = Oj.load(Net::HTTP.get(URI(uri)))

puts product 

# API_KEY=9... bundle exec ruby ./scripts/shopping/serpapi_product_api.rb iphone
# {"error"=>"`start` parameter can only be used with `offers`."}
```

Public links: [Playground 1](http://serpapi.com/playground?engine=google_shopping&q=coffee&gl=us&hl=en&direct_link=true&start=10&no_cache=true)

Internal links: [Search Inspect 1](https://serpapi.com/searches/6724040298721799073ff037/inspect)

**Comment by Ovi** [comment]
This is fixed, the `serpapi_product_api` link does not include `start` parameter.
