### ISSUE TITLE
[Google AI Overview API] List is empty for some results

### ISSUE THREAD

**Issue by zyc9012** [serpapi/public-roadmap#2081]
![image](https://github.com/user-attachments/assets/19536eaf-7a84-41a0-9650-95d7414a19a6)

Internal links: [Search Inspect](https://serpapi.com/searches/6724761cfc183da77025fb6c/inspect)

**Comment by StirnaK** [comment]
+1

**Comment by martin-serpapi** [comment]
A customer reported this:

[Front](https://app.frontapp.com/open/cnv_1dqs35gc?key=u3njoUAGG-hD-mYIkuSdatLW6pqWXLKo)

**Comment by zyc9012** [comment]
We've deployed a fix for this. Lists and references are properly parsed now.

![image](https://github.com/user-attachments/assets/1591e98f-3324-4f64-b23b-cdd5b9f8e0ec)
