### ISSUE TITLE
[Google Related Questions API] Scraping answer (snippet) in a table format

### ISSUE THREAD

**Issue by RedBillyOne** [serpapi/public-roadmap#2083]
Hi,

In this search 
https://serpapi.com/playground?device=desktop&engine=google_related_questions&google_domain=google.com&next_page_token=eyJvbnMiOiIxMDA0MSIsImZjIjoiRW9zQkNreEJTa2M1U210UFlqWlFlV1JRZW1SWWRuTmpkbmN6ZFV0amIwcDNVWGxyTW1FNWNWUnVkMWxCYjJwRlFVWTVlamRQWTFocE5qQjJkMFYxWm5WU2VtcFZWRVZ5ZFdGc1JWUkVSa3hHRWhkR1ZsbHVXamxoTTBaeVpXZHdkRkZRZVZvM1RuTkJUUm9pUVVaWWNrVmpiMHRuZEZCRGNYVmFVVWcxVlMxWlRsTlZRbEYzYUVVMVMwcEtadyIsImZjdiI6IjMiLCJlaSI6IkZWWW5aOWEzRnJlZ3B0UVB5WjdOc0FNIiwicWMiOiJDaHQwWVdsc2JHVWdjSEp2ZEdqRHFITmxjeUJ0WVcxdFlXbHlaWE1RQkJnQmZZODRMVDgiLCJxdWVzdGlvbiI6IkNvbW1lbnQgY2hvaXNpciBzYSB0YWlsbGUgZGUgcHJvdGjDqHNlIG1hbW1haXJlID8iLCJsayI6IkdpNWpiMjF0Wlc1MElHTm9iMmx6YVhJZ2MyRWdkR0ZwYkd4bElHUmxJSEJ5YjNSb1pYTmxJRzFoYlcxaGFYSmwiLCJicyI6ImM1V1FzVTdEUUF5RzZYcFR4eXJUanpLMEN3aE8zU3RVZFdUZ0VaekU2QTdsNG5DLXFGS2ZocEgzNkx1MEN3X0F5R1VJSUFZUWkyWExfLWZmdG5IbWRpc2hjSmRRT19IcUk1U1F5TGN0bzJIMFVaSTd2aW9qVUFqa0kyT3plSl9ibS1LNl9wUGpiNWdSczM0WU9MY1ZLaGtiazc0ZGN1RGswMWhNVnZvSmFUWTdWWFpkMk9kX28tYmVsTk5wUGFseVJMTWNPbFRTZFp4d2gtTUx0bm4tRzlteXVLeF9LUEdscEZGWm0ycmFfX2Z2TlBrWlYwLTVKVEhsUVp2RmVXZVhSYmwzbEtELXdLZ2lreVk4U2d4UUowUGJ3R1BQRkZjWDg5a0giLCJpZCI6ImZjX0ZWWW5aOWEzRnJlZ3B0UVB5WjdOc0FNXzEifQ%3D%3D

![image](https://github.com/user-attachments/assets/e41c1bc7-f482-4ba2-a503-c5e414d8c78e)

There isn't answer (only question) But in Google Search Results Pages we've got a table in the answer

![image](https://github.com/user-attachments/assets/66212875-bcba-47ed-a930-d02edd8ebfd1)

Is it possible to solve this issue ?

Regards.

**Comment by hilmanski** [comment]
Hi, @RedBillyOne , thank you very much for your report. 
We'll investigate this and provide support for the table's format answer.

*Internal notes
It looks like we're not scraping the answer when it's in a table format.

![CleanShot 2024-11-04 at 05 23 34](https://github.com/user-attachments/assets/224fe34b-6759-4aea-b957-19b1ca1ee31a)

[Google Search](https://www.google.com/search?q=athlete+height&oq=athlete+height&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM&hl=en&gl=us&sourceid=chrome&ie=UTF-8) |  [Playground](https://serpapi.com/playground?q=athlete+height&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_sitesearch+votes+site+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz+interval) |  [Inspect](https://serpapi.com/searches/6727e9b5e10f0aa338186657/inspect)

Customer's sample:
[Inspect](https://serpapi.com/searches/6727e915a5aae91787602029/inspect) | [playground](https://serpapi.com/playground?engine=google_related_questions&next_page_token=eyJvbnMiOiIxMDA0MSIsImZjIjoiRW9zQkNreEJTa2M1U210UFlqWlFlV1JRZW1SWWRuTmpkbmN6ZFV0amIwcDNVWGxyTW1FNWNWUnVkMWxCYjJwRlFVWTVlamRQWTFocE5qQjJkMFYxWm5WU2VtcFZWRVZ5ZFdGc1JWUkVSa3hHRWhkR1ZsbHVXamxoTTBaeVpXZHdkRkZRZVZvM1RuTkJUUm9pUVVaWWNrVmpiMHRuZEZCRGNYVmFVVWcxVlMxWlRsTlZRbEYzYUVVMVMwcEtadyIsImZjdiI6IjMiLCJlaSI6IkZWWW5aOWEzRnJlZ3B0UVB5WjdOc0FNIiwicWMiOiJDaHQwWVdsc2JHVWdjSEp2ZEdqRHFITmxjeUJ0WVcxdFlXbHlaWE1RQkJnQmZZODRMVDgiLCJxdWVzdGlvbiI6IkNvbW1lbnQgY2hvaXNpciBzYSB0YWlsbGUgZGUgcHJvdGjDqHNlIG1hbW1haXJlID8iLCJsayI6IkdpNWpiMjF0Wlc1MElHTm9iMmx6YVhJZ2MyRWdkR0ZwYkd4bElHUmxJSEJ5YjNSb1pYTmxJRzFoYlcxaGFYSmwiLCJicyI6ImM1V1FzVTdEUUF5RzZYcFR4eXJUanpLMEN3aE8zU3RVZFdUZ0VaekU2QTdsNG5DLXFGS2ZocEgzNkx1MEN3X0F5R1VJSUFZUWkyWExfLWZmdG5IbWRpc2hjSmRRT19IcUk1U1F5TGN0bzJIMFVaSTd2aW9qVUFqa0kyT3plSl9ibS1LNl9wUGpiNWdSczM0WU9MY1ZLaGtiazc0ZGN1RGswMWhNVnZvSmFUWTdWWFpkMk9kX28tYmVsTk5wUGFseVJMTWNPbFRTZFp4d2gtTUx0bm4tRzlteXVLeF9LUEdscEZGWm0ycmFfX2Z2TlBrWlYwLTVKVEhsUVp2RmVXZVhSYmwzbEtELXdLZ2lreVk4U2d4UUowUGJ3R1BQRkZjWDg5a0giLCJpZCI6ImZjX0ZWWW5aOWEzRnJlZ3B0UVB5WjdOc0FNXzEifQ%3D%3D)

**Comment by hilmanski** [comment]
Hi, @RedBillyOne , our colleague, @tanys123, has implemented a fix for this issue. Thank you very much for your request.

You can see a working example here: [playground](https://serpapi.com/playground?engine=google_related_questions&next_page_token=eyJvbnMiOiIxMDA0MSIsImZjIjoiRW9zQkNreEJTa2M1U210UFlqWlFlV1JRZW1SWWRuTmpkbmN6ZFV0amIwcDNVWGxyTW1FNWNWUnVkMWxCYjJwRlFVWTVlamRQWTFocE5qQjJkMFYxWm5WU2VtcFZWRVZ5ZFdGc1JWUkVSa3hHRWhkR1ZsbHVXamxoTTBaeVpXZHdkRkZRZVZvM1RuTkJUUm9pUVVaWWNrVmpiMHRuZEZCRGNYVmFVVWcxVlMxWlRsTlZRbEYzYUVVMVMwcEtadyIsImZjdiI6IjMiLCJlaSI6IkZWWW5aOWEzRnJlZ3B0UVB5WjdOc0FNIiwicWMiOiJDaHQwWVdsc2JHVWdjSEp2ZEdqRHFITmxjeUJ0WVcxdFlXbHlaWE1RQkJnQmZZODRMVDgiLCJxdWVzdGlvbiI6IkNvbW1lbnQgY2hvaXNpciBzYSB0YWlsbGUgZGUgcHJvdGjDqHNlIG1hbW1haXJlID8iLCJsayI6IkdpNWpiMjF0Wlc1MElHTm9iMmx6YVhJZ2MyRWdkR0ZwYkd4bElHUmxJSEJ5YjNSb1pYTmxJRzFoYlcxaGFYSmwiLCJicyI6ImM1V1FzVTdEUUF5RzZYcFR4eXJUanpLMEN3aE8zU3RVZFdUZ0VaekU2QTdsNG5DLXFGS2ZocEgzNkx1MEN3X0F5R1VJSUFZUWkyWExfLWZmdG5IbWRpc2hjSmRRT19IcUk1U1F5TGN0bzJIMFVaSTd2aW9qVUFqa0kyT3plSl9ibS1LNl9wUGpiNWdSczM0WU9MY1ZLaGtiazc0ZGN1RGswMWhNVnZvSmFUWTdWWFpkMk9kX28tYmVsTk5wUGFseVJMTWNPbFRTZFp4d2gtTUx0bm4tRzlteXVLeF9LUEdscEZGWm0ycmFfX2Z2TlBrWlYwLTVKVEhsUVp2RmVXZVhSYmwzbEtELXdLZ2lreVk4U2d4UUowUGJ3R1BQRkZjWDg5a0giLCJpZCI6ImZjX0ZWWW5aOWEzRnJlZ3B0UVB5WjdOc0FNXzEifQ%3D%3D)

**Comment by tanys123** [comment]
Thanks @hilmanski! For anyone interested, feel free to checkout the [documentation](https://serpapi.com/related-questions#api-examples-example-table-results-for-athlete-height).

<img width="1291" alt="Screenshot 2024-11-13 at 1 06 22 PM" src="https://github.com/user-attachments/assets/92d7a531-2f0d-473b-b452-0f427a60a6d5">
