### ISSUE TITLE
[Google Search API] Scraping public figure section

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#2084]
A high-volume customer is interested in scraping the public-figure section on Google Search.

<img width="840" alt="image" src="https://github.com/user-attachments/assets/c2a707e3-7118-4c06-873c-f1d431bc00a6">

Public links: [Playground](https://serpapi.com/playground?q=Entity+optimization+-+Majestic+Livestream+jason+barnard&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_sitesearch+votes+site+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz+interval)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000066945?view=List) | [Search Inspect](https://serpapi.com/searches/6727fb255bb6a2a2f8b21066/inspect)

**Comment by marm123** [comment]
@hilmanski remember to include screenshots indicating the request. Playground query doesn't produce the block you're referring to for me, and the Inspect might expire.

**Comment by hilmanski** [comment]
Thanks for the reminder!

**Comment by btaunt** [comment]
We now parse this information under `complementary_results`:

<img width="770" alt="Screenshot 2024-11-08 at 10 16 27 AM" src="https://github.com/user-attachments/assets/a513b8c2-9169-47ad-bf74-151b1add30e9">
<img width="757" alt="Screenshot 2024-11-08 at 10 17 12 AM" src="https://github.com/user-attachments/assets/47938968-1161-484d-aec3-7e2dba3f6469">

---

- [Playground Desktop](https://serpapi.com/playground?q=Entity+optimization+-+Majestic+Livestream+jason+barnard&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_sitesearch+votes+site+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz+interval)
- [Playground Mobile](https://serpapi.com/playground?q=Entity+optimization+-+Majestic+Livestream+jason+barnard&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_sitesearch+votes+site+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz+interval)
