### ISSUE TITLE
[Google Search API] qdr:m rich snippet missing

### ISSUE THREAD

**Issue by RedBillyOne** [serpapi/public-roadmap#2092]
Hi,

When we do a search with qdr:m there is not Rich Snippet above top 1
https://www.google.fr/search?q=taille+proth%C3%A8ses+mammaires&oq=taille+proth%C3%A8ses+mammaires&uule=w+CAIQICIGRnJhbmNl&hl=fr&gl=fr&tbs=qdr:m&sourceid=chrome&ie=UTF-8

![image](https://github.com/user-attachments/assets/912d6178-34ff-454e-991c-be227335cdb4)

But when we use, in the same search, the URL in your parameter "google_url" (https://www.google.fr/search?q=taille+proth%C3%A8ses+mammaires&oq=taille+proth%C3%A8ses+mammaires&uule=w+CAIQICIGRnJhbmNl&hl=fr&gl=fr&tbs=qdr:m&sourceid=chrome&ie=UTF-8)
there is a rich snippet above  TOP 1

![image](https://github.com/user-attachments/assets/d26b5919-45e1-4e34-9460-f66bff0c9a59)

Is possible to have in your API (JSON) the same result that there is in your "google_url" parameter ?

Regards

Note : if we force Pays  :France we've got the rich snippet (perhaps is your API that don't take into account the country) ?

![image](https://github.com/user-attachments/assets/cae02787-0c54-47b9-8b4a-755599fa11a6)

**Comment by marm123** [comment]
Hi @RedBillyOne, thank you for reporting the issue.

I've run a similar query on our Playground, and it looks like the `answer_box` was returned correctly:
<img width="1676" alt="image" src="https://github.com/user-attachments/assets/59a8d7cb-132e-4c0f-beba-35bf5859ffd8">
[Playground](https://serpapi.com/playground?q=taille+proth%C3%A8ses+mammaires&location=France&google_domain=google.fr&gl=fr&hl=fr&tbs=qdr%3Am&google_domain=google.fr)

Providing a very broad `location` such as "France" might result in an irrelevant output, as different areas of France might yield different results. I recommend using a more narrow location, such as `"Paris, Paris, Ile-de-France, France"`, or any other French city you'd like, as this might improve the consistency of your output.

Feel free to contact us at contact@serpapi.com or via the chat widget at serpapi.com if you'd like to discuss this further. Of course, feel free to open additional issues if you find new bugs.
