### ISSUE TITLE
[Google Search API]  Title don't display

### ISSUE THREAD

**Issue by RedBillyOne** [serpapi/public-roadmap#2098]
Hi,

![image](https://github.com/user-attachments/assets/ed42ce0c-ec97-4168-bdbb-488b7e76490f)

For answer_box with Table, the content of the title tag is wrong. In the screenshot below, title must be "Prothèses mammaires : choisir la taille idéale pour un résultat...." et non "considérations médicales"

The datetime (il y a 3 jours) is also missing in the JSON.

[Playground 1](https://serpapi.com/playground?device=desktop&engine=google&gl=fr&google_domain=google.fr&hl=fr&location=France&q=taille+implant+mammaire&tbs=qdr%3Am)

Do you know if it's possible to solve this issue ?

Regards

**Comment by hilmanski** [comment]
Hi, @RedBillyOne 

Thank you very much for your report. Based on the documentation, we usually get the first section as the title: https://serpapi.com/direct-answer-box-api#api-examples-organic-result-answer-box-type-3. I can see that we're missing the website title here. We'll investigate this and see what's the best way to approach this.

Sample for SerpApi team:
[Playground](https://serpapi.com/playground?q=paper+size&gl=us&hl=en&tbs=qdr%3Am&device=desktop&google_domain=google.com&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_sitesearch+votes+site+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz+interval) | [Inspect](https://serpapi.com/searches/672aaf73cb33d0e4b1956b88/inspect)

**Comment by RedBillyOne** [comment]
Your actual title (the first section )  should be the description ;-)

**Comment by btaunt** [comment]
This has been updated. We now parse the correct `title` and include `description` as well (if available)

<img width="724" alt="Screenshot 2024-11-14 at 4 04 45 PM" src="https://github.com/user-attachments/assets/97d069ec-e739-4c75-91d1-d6eb26b02703">

---

[Playground](https://serpapi.com/playground?q=taille+implant+mammaire&location=France&google_domain=google.fr&gl=fr&hl=fr&tbs=qdr%3Am&device=desktop&google_domain=google.fr&newPara=chips+highlight+stick+lr+as_qdr+safe+google_domain+si+form+filter+as_sitesearch+votes+site+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz+interval) | [Updated Documentation](https://serpapi.com/direct-answer-box-api#api-examples-organic-result-answer-box-type-3)

**Comment by marm123** [comment]
@RedBillyOne tagging for visibility

**Comment by RedBillyOne** [comment]
Yes, I confirm it's solve.
