### ISSUE TITLE
[Google Food API] No response obtained for searches

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#2107]
A customer reported that they are not seeing a response to queries sent to our Google Food API.
This is seen is multiple ways:

Playground queries stuck on this state:
![Screenshot 2024-11-07 at 4 32 39 PM](https://github.com/user-attachments/assets/af5858f2-bd2d-4804-8ff4-0d2fa6abe343)

and leading to:
![Screenshot 2024-11-07 at 4 34 27 PM](https://github.com/user-attachments/assets/789f62fd-8e8c-4fcb-88e7-3ae6ec58b2be)

In the customer's case, it routed to Google Search instead:
![Screenshot 2024-11-07 at 4 33 15 PM](https://github.com/user-attachments/assets/8c7bd53f-604b-454a-88a8-ea43bbc48d3d)

status page shows high response times:
https://serpapi.com/status/google_food
![Screenshot 2024-11-07 at 4 36 26 PM](https://github.com/user-attachments/assets/15cb3940-153f-40ff-ad85-20289f2f2d4c)

Public links: [Playground 1](https://serpapi.com/playground?engine=google_food&q=Coffee&gl=us&hl=en)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071924?view=List) | [Search Inspect 1](https://serpapi.com/searches/672d419acc298738a0e2ffa2/inspect) | [Search Inspect 2](https://serpapi.com/searches/672d5a6952a04e326e4c0d4b/inspect)

**Comment by hilmanski** [comment]
A customer reported this.

[Intercom](https://app.frontapp.com/open/cnv_1dtb18ws?key=oV7S8DwIFXretf12VSb8JyP_swgEgcHG)

**Comment by sonika-serpapi** [comment]
The customer Hilman mentioned above reached out again. I'm changing the status to prioritized because this API is unusable, and is affecting the customers' workflows. 

Also, it looks like food.google.com is deprecated perhaps - since it just leads to google.com. We probably can't support the API if google does not have an option to access this on their end, but this needs some investigating.

**Comment by schaferyan** [comment]
I can confirm that Google has discontinued the food.google.com endpoint. They will now redirect users who click the "Order" button to relevant third party platforms or restaurant websites instead.

Unfortunately, that means we will no longer be able to provide the Google Food API, as there is nothing for us to scrape.

[Reference](https://help.zuppler.com/support/solutions/articles/47001267250-google-end-to-end-e2e-food-ordering-transition-google-redirect-updated-guidelines-for-partners)

**Comment by dsojevic** [comment]
A notice has been added to the documentation and our Google Food API will no longer accept new searches.

![image](https://github.com/user-attachments/assets/56ad7a6a-8c2c-4082-83d9-c2998f2c3539)
