### ISSUE TITLE
[Google Flights API] High response times for queries

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#2109]
A customer reported they are noticing high response time consistently for queries to the Google Flights API, which is impacting their workflow quite a bit. 

This can be seen on our status graph: https://serpapi.com/status/google_flights
![Screenshot 2024-11-08 at 12 50 27 PM](https://github.com/user-attachments/assets/59fc7be8-a261-4df3-a10c-53a370dd92eb)

Public links: [Playground 1](https://serpapi.com/playground?engine=google_flights&departure_id=CDG&arrival_id=AUS&gl=us&hl=en&currency=USD&outbound_date=2024-11-09&return_date=2024-11-15)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071958?view=List) | [Search Inspect 1](https://serpapi.com/searches/672e758dee468264de3d7289/inspect)

**Comment by zyc9012** [comment]
We've deployed a fix for the high response time. It's now normal.

![image](https://github.com/user-attachments/assets/38a86809-e71c-4a88-80cc-dcecf04282d7)

It's worth noting that our default response (~1.5 secs per search) could sometimes have fewer items than what you would get in the browser.

To make up for that, we introduced a new parameter - `deep_search`. Set it to `true` to enable "slow" search (~4.5 secs per search). The items returned will be identical to the actual search in the browser.
