### ISSUE TITLE
[Google Trends Trending Now] Update supported locations

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#2113]
A user reported that we returned an error for a certain search on Google Trends Trending Now.

![CleanShot 2024-11-11 at 11 24 43](https://github.com/user-attachments/assets/a5bd8f20-a53f-4b12-837a-d9ad75638129)

After investigating, it looks like we need to update our supported locations for this API.
https://serpapi.com/google-trends-trending-now-locations.

Test on Google Trends Trending Now says "Location Not Supported":
https://trends.google.com/trending?geo=SC

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071985?view=List) | [Inspect](https://serpapi.com/searches/6730510166d995279e97dcea/inspect)

**Comment by Ovi** [comment]
Our supported locations for **Google Trends Trending Now** is updated:
https://serpapi.com/google-trends-trending-now-locations
