### ISSUE TITLE
[DuckDuckGo Search API] Success rate is decreasing

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#2117]
A high-volume customer reported that our DuckDuckGo is having some issues.

![CleanShot 2024-11-12 at 09 14 33](https://github.com/user-attachments/assets/250dccd8-2db7-4235-9b70-5908ce28d843)

Public links: [DuckDuckGo status](https://serpapi.com/status/duckduckgo)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072067?view=List) | [Sample Inspect](https://serpapi.com/searches/6732acad7e1d1fb10f8d4e2a/inspect) | [Sample Inspect from user](https://serpapi.com/searches/6732abe55ed3cacdd31268b1/inspect)

**Comment by alexbarron** [comment]
Looks like this eventually normalized, but performance is bad again today both for response times and success rates.

Screenshots are for the worst hour of each metric.

![image](https://github.com/user-attachments/assets/91c7556d-7069-49d2-80b1-89eb2f2d8a1e)
![image](https://github.com/user-attachments/assets/97a70bd0-db3f-4108-b700-dd50e1a37a7a)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072992?view=List)

**Comment by alexbarron** [comment]
Re-prioritizing this as `queued` since success rates have normalized. The underlying issue was not fully identified so leaving this open for investigation.

![image](https://github.com/user-attachments/assets/b7080595-4e6a-4084-9fa7-26ae7d7a8fc5)

**Comment by hartator** [comment]
Closing this now as we are back to the same baseline performance as before for DuckDuckGo:

![CleanShot 2024-12-19 at 17 51 47@2x](https://github.com/user-attachments/assets/e82a7573-627b-4673-95d9-4fcf69292a43)
