### ISSUE TITLE
[Google Search API] Table is not scraped for AI Overview results

### ISSUE THREAD

**Issue by zyc9012** [serpapi/public-roadmap#2118]
![image](https://github.com/user-attachments/assets/1628bc05-b119-4eba-8136-c1b8e84cd705)

![image](https://github.com/user-attachments/assets/18fa58e5-edcc-4c8f-a04b-dd861c146d29)

Public links: [Playground](https://serpapi.com/playground?q=is+coffee+good+for+health&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=chips+as_sitesearch+highlight+stick+lr+as_qdr+votes+site+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+rlz+ijn+interval)

Internal links: [Search Inspect](https://serpapi.com/searches/6732d2b463a844c972db41bb/inspect)

**Comment by hilmanski** [comment]
A high-volume customer reported this.

[Search Inspect](https://serpapi.com/searches/67610984b76dc736ed06986e/inspect)

**Comment by zyc9012** [comment]
We've released the support for tables.

![20241223_201031](https://github.com/user-attachments/assets/1133f913-bca8-4ff1-b5d3-044a8d2b8d52)
