### ISSUE TITLE
[Home Depot API] Update filter options 

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#2119]
Based on our [documentation](http://localhost:3000/home-depot-search-api), we support these values for sorting Home Depot Canada
```
It can be set to:
priceSaving: Top Sellers,
price-asc: Price Low to High,
price-desc: Price High to Low,
reviewAvgRating: Top Rated,
relevance: Recommended (Default)
```

Upon testing on the Home Depot site `topSeller` is not an option anymore.

![CleanShot 2024-11-12 at 16 13 29](https://github.com/user-attachments/assets/d155d567-da59-4626-8806-a8a2cdfe4607)

Which leads to an error for this search.

[Playground](https://serpapi.com/playground?engine=home_depot&q=Coffee&country=ca&sort=priceSaving) | [Inspect](https://serpapi.com/searches/6733102964f11d273d11956f/inspect)

**Comment by ishiharaf** [comment]
`priceSaving` has been deprecated and is no longer working. Attempting to use it will return a validation error:

![image](https://github.com/user-attachments/assets/9b1847e2-c69c-44b8-aa4e-f3872f8cb236)
![image](https://github.com/user-attachments/assets/9cdaffa7-1a54-4b0b-a546-f76ea0e20238)

The documentation has been updated accordingly 😺
