### ISSUE TITLE
[Google News API] Scrape lower resolution thumbnail

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#2120]
A customer reached out requesting to scrape the lower resolution thumbnail available via Google news for each result in the API response. We don't currently scrape this. Currently, we only scrape the full resolution image.

<img width="1115" alt="Screenshot 2024-11-12 at 12 17 05 PM" src="https://github.com/user-attachments/assets/84a798ff-d151-4dc8-9911-878083a9fe58">

HTML with the lower resolution thumbnail: [Inspect HTML](https://serpapi.com/searches/da98af53384835fa/6733a7c19936883ab63ecd6b.html)

Currently we scrape only the full resolution image as the thumbnail:
<img width="1300" alt="Screenshot 2024-11-12 at 1 04 20 PM" src="https://github.com/user-attachments/assets/bc9c6d0f-98ee-4be8-9d3e-deed070551c7">

Public links: [Playground](https://serpapi.com/playground?engine=google_news&q=coffee&gl=us&hl=en)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072097?view=List) | [Search Inspect 1](https://serpapi.com/searches/6733a7c19936883ab63ecd6b/inspect)

**Comment by ocvit** [comment]
Feature has been released.

Now we grab `thumbnail_small` alongside with regular `thumbnail`.

<img width="1331" alt="Screenshot 2024-11-21 at 10 58 31" src="https://github.com/user-attachments/assets/84ab6502-8dbc-4c91-bd35-2194bf6e20d4">
