### ISSUE TITLE
[Google Search API] Missing football's team standing information

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#2121]
A high-volume customer reported that we're missing a team's information (which is part of the query) on the standings results. This information is available on the knowledge graph (right-panel).

Here, for example, when searching for Barcelona, the table will start with Real Madrid
![CleanShot 2024-11-13 at 12 34 36](https://github.com/user-attachments/assets/d248f3b5-6467-405c-a9f8-89c642abf289)

So, is when searching Real Madrid, it'll skip the 2nd position.

![CleanShot 2024-11-13 at 12 37 55](https://github.com/user-attachments/assets/30413119-f9c8-4247-964a-881572017612)

Public links: [Playground 1](https://serpapi.com/playground?q=barcelona+matches&location=United+States&gl=us&hl=en&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_sitesearch+votes+site+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz+interval+size+color+maxPrice) 

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072103?view=List) | [Search Inspect 1](https://serpapi.com/searches/67342bff9e38e5aa4f5e5021/inspect)

**Comment by ocvit** [comment]
Fix has been released.

We don't miss highlighted team in the standings table anymore.

<img width="1382" alt="Screenshot 2024-11-15 at 13 00 33" src="https://github.com/user-attachments/assets/b16646e0-8510-4096-893d-17bb89bc1f4e">
