### ISSUE TITLE
[Google Search API] Scrape coordinates from `answer_box`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#2123]
While helping one of our users with a different issue, I noticed that we're not scraping GPS Coordinates from `answer_box`.

![image](https://github.com/user-attachments/assets/2b603be9-42d6-4cfe-a624-b273c830c1e9)

Public links: [Playground 1](https://serpapi.com/playground?q=Heathrow%2C+London+coordinates&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Playground 2](https://serpapi.com/playground?q=Empire+State+Building+coordinates&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)

Internal links: [Search Inspect 1](https://serpapi.com/searches/673607e9e924566c7587153c/inspect) | [Search Inspect 2](https://serpapi.com/searches/67360cd981bab7957b541197/inspect)

**Comment by ocvit** [comment]
Fix has been released.

`answer_box.answer` and `answer_box.webfacts[].snippet` capture GPS coordinates now.

<img width="1527" alt="Screenshot 2024-12-18 at 11 30 07" src="https://github.com/user-attachments/assets/279dcc3b-b40b-4d75-9123-10ee8e71ea46" />
