### ISSUE TITLE
[Google Search API] First Showtimes Result Parsed as Answer Box

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#2146]
A potential Enterprise customer reported the first result in the `showtimes`block is being parsed as an empty answer box with `"type":"showtimes_for_[movie title]"`

<img width="1021" alt="Screenshot 2024-11-18 at 12 06 47 PM" src="https://github.com/user-attachments/assets/72626384-ea2f-43c1-b420-62621156a22d">
<img width="1334" alt="Screenshot 2024-11-18 at 12 08 53 PM" src="https://github.com/user-attachments/assets/8f757180-c3e6-4fa6-808e-065840744c8a">

I was able to replicate it in the Playground. The information seems to be parsed correctly in `showtimes`, there is just an errant `answer_box` block returned in addition to this.

I've followed up with the customer to determine how we should prioritize this, as the information is available via the `showtimes` key.

Public links: [Playground 1](https://serpapi.com/playground?q=regal+gateway&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+as_sitesearch+highlight+stick+lr+as_qdr+votes+site+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+rlz+ijn+interval+as_dt) | [Playground 2](https://serpapi.com/playground?q=moody+gardens&location=Melbourne%2CFlorida%2CUnited+States&gl=us&hl=en&device=desktop&google_domain=google.com&newPara=chips+as_sitesearch+highlight+stick+lr+as_qdr+votes+site+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+rlz+ijn+interval+as_dt) | 

Internal links: [Front](https://app.frontapp.com/open/cnv_1dwgbly4?key=AxZZ79lcXKfek4EmBW-yNsoKJ0HGfVu7) | [Search Inspect 1](https://serpapi.com/searches/673895dfbb64acd95726096f/inspect)  | [Search Inspect 2](https://serpapi.com/searches/673b9eb8cb33d0d082d549da/inspect)

**Comment by NateSkiles** [comment]
The customer let us know this is a critical issue for them, as they use `type` extensively.

Updating to prioritized.
