### ISSUE TITLE
[All APIs] Increased response times

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#2153]
A high-volume customer reported seeing responses from around 2.5 seconds to 10 seconds from the Google Light API.

The average response time is currently at 2.67s, spiking around 12:00 PM PST.

![image](https://github.com/user-attachments/assets/bd21fddf-d5d4-4719-b15c-a081f0cf9f6b)

https://serpapi.com/status/

Searches:
* https://serpapi.com/searches/673d14a052a04ebe1aee3e40/inspect (8.20s)
* https://serpapi.com/searches/673d147ae92456b049477a01/inspect (4.62s)
* https://serpapi.com/searches/673d146e8a7c09673fea61c9/inspect (5.38s)
* https://serpapi.com/searches/673d146975f9744b68372c32/inspect (7.09)

[Front](https://app.frontapp.com/open/cnv_1dx11tgc?key=jkndcsKNBJ91B8rfrC3NW-4pIJsUnyG5)

**Comment by NateSkiles** [comment]
Another high-volume customer reported this:

[Front](https://app.frontapp.com/open/cnv_1dx4hn6k?key=rxhJpakHwW_paBC0sUXiyOH8McKNqodg)

**Comment by marm123** [comment]
The response times have improved since, and have been stable. Closing this for now.
