### ISSUE TITLE
[Billing Information page] 500 Internal Server Error loading Billing Information/Credit Card page

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#2156]
A customer reported encountering a 500 Internal Server Error while accessing the Billing Information/Credit Card page.

![image](https://github.com/user-attachments/assets/0ae595a0-7778-452e-a3f1-e5acc7552878)

Checking their Stripe history, I see their credit card was previously removed from Stripe. This may not have synced on our end.

Internal links: [Front](https://app.frontapp.com/open/cnv_1dx7pjbw?key=4u6X33UxQrhtMlZIRpOyCsIS_FTX6-lo) | [User Inspector](https://serpapi.com/admin/users/6529171d2c6878d8c1757791) | [Stripe Card Deletion Event](https://dashboard.stripe.com/events/evt_1OMTAPJ3XtdHEnmQ3dZ9iHcF)

**Comment by hilmanski** [comment]
The customer followed up.

**Comment by ishiharaf** [comment]
We've fixed the issue and added support for Chinese Tax ID.

![image](https://github.com/user-attachments/assets/8b2eeaa9-851c-4bca-bb2f-9043f1f163c9)

The customer should be able to see his billing information page now.
