### ISSUE TITLE
[Google Shopping API] Scrape higher resolution thumbnail

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#2160]
A customer reached out requesting to scrape the higher resolution thumbnail available via Google Shopping for each result in the API response. We don't currently scrape this. Currently, we only provide the compressed webp instead of the full size image.

**Thumbnail we provide in the results:**
https://serpapi.com/searches/673e5a3e0197dd7ff7fff5b6/images/6ca1c0071b7063f2123ee265b6fe8ddee23814a671edfd0e9818eb0ce18b7d92ff6698a16a56115f.webp
<img width="956" alt="Screenshot 2024-11-20 at 5 01 53 PM" src="https://github.com/user-attachments/assets/6ec85687-6040-4b88-88b8-b32ec812dcd0">

In the response, it is a webp file:
<img width="1351" alt="Screenshot 2024-11-20 at 5 05 01 PM" src="https://github.com/user-attachments/assets/8c458bfd-e928-43d2-9f10-650cadb52e8d">

**Higher resolution thumbnail available on Google Shopping:**
<img width="1344" alt="Screenshot 2024-11-20 at 2 11 42 PM" src="https://github.com/user-attachments/assets/749e67e7-e9b0-4706-9b08-3dc92f5e2124">

Public links: [Playground 1](https://serpapi.com/playground?engine=google_shopping&q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&newPara=direct_link) 

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072348?view=List) | [Search Inspect 1](https://serpapi.com/searches/673e5a3e0197dd7ff7fff5b6/inspect)

**Comment by tanys123** [comment]
Inline shopping results don't have the same high-resolution image as the shopping results. Nevertheless, we found a slightly better version of the same image. We have deployed this update, please try it out and let us know if you have any question.

Old:
![old](https://github.com/user-attachments/assets/97e783fa-589e-49ee-886f-e3da322bad10)

New:
![new](https://github.com/user-attachments/assets/bc84e238-35a2-4353-b762-e60c0c9fa1ac)
