### ISSUE TITLE
[Google Search API] Empty result in `immersive_products`

### ISSUE THREAD

**Issue by zyc9012** [serpapi/public-roadmap#2163]
![20241122_102945](https://github.com/user-attachments/assets/3fee3927-5f55-4c10-93d3-66ca29580766)

For results in the carousel, the first some were correct, but the rest were empty.

Public links: [Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+as_sitesearch+highlight+stick+lr+as_qdr+votes+site+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+rlz+ijn+interval)

Internal links: [Search Inspect](https://serpapi.com/searches/673feb420f1a33969e0da8c6/inspect)

**Comment by Krugloff** [comment]
<img width="1448" alt="image" src="https://github.com/user-attachments/assets/792b69e6-453e-433d-9722-d6f838db3fdf">


All elements are present for now.
