### ISSUE TITLE
Phone number change.

### ISSUE THREAD

**Issue by CBOK-tablet** [serpapi/public-roadmap#2165]
Change phone number to 269-264-2633.
One sentence description.

Screenshot with red annotations.

Details about the bug, sample code, more screenshots, and other relevant information.

Public links: Playground 1 | Playground 2 | Documentation

Internal links: Intercom | Search Inspect 1 (under your dashboard > "Your Searches" > select one search) | Search Inspect 2

**Comment by marm123** [comment]
Hi @CBOK-tablet, thanks for reaching out. Can you reach out to our support team using the chat widget at serpapi.com or through email at contact@serpapi.com? We'll be happy to assist you with the phone verification.

Meanwhile, I redacted your message so that your phone number is not public.
