### ISSUE TITLE
[Google Flights API] Allow airport groups or multiple airports departing or arriving for google flights api.

### ISSUE THREAD

**Issue by robcampbell08105** [serpapi/public-roadmap#2167]
One sentence description.
I'd like to be able to use a airport group like WAS or PHI to get all local airports.

Screenshot with red annotations.
![image](https://github.com/user-attachments/assets/3745ec5d-1d74-49b5-8d6e-a99f4977ba1b)

Details about the feature, sample code, more screenshots, and other relevant information.
I would like to get all surrounding flights rather than making multiple calls. I'd like to use WAS rather than DCA & IAD & BWI. Or if I could add multiple departing airports, that would be even better.

Public links: Playground 1 | Playground 2 | Documentation

Internal links: Intercom | Search Inspect 1 (under your dashboard > "Your Searches" > select one search) | Search Inspect 2

**Comment by hilmanski** [comment]
Thank you very much for your request. We do have a way to search with multiple places using `multi_city_json`:
https://serpapi.com/google-flights-api#api-parameters-advanced-google-flights-parameters-multi-city-json

Please let me know if this works for you.

**Comment by zyc9012** [comment]
@robcampbell08105 To specify multiple departing airports, simply provide a comma-separated list. e.g. Set `departure_id` as `DCA,IAD,BWI`

**Comment by schaferyan** [comment]
Thanks @robcampbell08105 ! I'm closing this, since we already support specifying multiple departing airports. Feel free to reach out to contact@serpapi.com if you have any followup questions about how this can be achieved.

**Comment by schaferyan** [comment]
Thanks @robcampbell08105 ! I'm closing this, since we already support specifying multiple departing airports. Feel free to reach out to contact@serpapi.com if you have any followup questions about how this can be achieved.
