### ISSUE TITLE
[Google Search API] Scrape videos results

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#2168]
An enterprise customer requested to scrape the videos results on basic search results.

![CleanShot 2024-11-25 at 07 20 59](https://github.com/user-attachments/assets/8711ba62-88a0-4053-bf40-402848b4e013)

Public links: [Playground 1](https://serpapi.com/playground?q=charlie+bit+my+finger&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_sitesearch+votes+site+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz+interval+size+color+maxPrice)

Internal links: [Front](https://app.frontapp.com/open/cnv_1dhv7f6k?key=eEqUtcf3S6kdOY3VLKjvDN4cwCvv0kV0) | [Inspect](https://serpapi.com/searches/6743b4ba4d52b83b943281af/inspect)

**Comment by Krugloff** [comment]
<img width="1446" alt="image" src="https://github.com/user-attachments/assets/08dfedab-6768-49a8-88d1-7d29d066765c">

It's now available.
