### ISSUE TITLE
[Google Search Engine Results API] Understanding the output of AI Overview block 

### ISSUE THREAD

**Issue by haiwen-li** [serpapi/public-roadmap#2169]
Hi I'm using google search engine results API to collect search results for some queries and I'm trying to understand the appearance of the AI Overview block in the output.

When I started scraping in early October, I noticed there were three cases (1) no AI Overview included in the output (2) an AI Overview block is included, but saying "can't generated AI Overview right now, please try again later" (3) an AI overview block with valid responses is included in the output. 
At that moment, does scenario (2) mean that there IS an AI Overview for that query, but due to scraping issues the error message instead of the valid response is shown?

I noticed a recent change that a page token link is returned in the AI Overview block. Is this an equivalent case as the old error message one or does it mean something else? 

Does it mean that whenever there is an AI overview output in the search result of a query (whether it is an error message, a page token link, or a valid response), that search query has an AI Overview response when we perform searching in Google?

Thank you!

**Comment by hilmanski** [comment]
Hi @haiwen-li,

Thank you very much for your questions. I'll be happy to clarify.

Sometimes, Google requires an additional request to scrape the AI overview, so in that case, we need to send the `page_token`. Reference: https://serpapi.com/ai-overview

Sample case when the answer is available directly:
![CleanShot 2024-11-25 at 12 21 32](https://github.com/user-attachments/assets/8ee5feb6-243f-45c3-baae-82e6d57345e0)

Sample case where additional request needed:
![CleanShot 2024-11-25 at 12 22 20](https://github.com/user-attachments/assets/08083ec6-1de5-4204-9294-2cebce305354)

This is indeed the solution for case no. 2

If you have any other questions, feel free to contact us at contact@serpapi.com or through our chat widget on the website.
