### ISSUE TITLE
[Google Shopping API] Extract list of thumbnails

### ISSUE THREAD

**Issue by tanys123** [serpapi/public-roadmap#2172]
There are more than one thumbnails showing when hover the item
<img width="269" alt="Screenshot 2024-11-26 at 3 43 40 PM" src="https://github.com/user-attachments/assets/2b843b57-b4c5-40c3-8e49-8f99c744414a">

This is also available in the mobile
<img width="176" alt="Screenshot 2024-11-26 at 3 43 51 PM" src="https://github.com/user-attachments/assets/1f22863c-a10b-4c01-b38c-d5df010200bc">

We can extract the list of thumbnails as `thumbnails`

Public links: [Playground](https://serpapi.com/playground?engine=google_shopping&q=Coffee)

Internal links: [Inspect](https://serpapi.com/searches/67457cbc0197dd994c2e8995/inspect)

**Comment by Alaa-abdulridha** [comment]
This issue has been resolved:

Before fixing the issue (production):

![image](https://github.com/user-attachments/assets/a8cd1469-d276-4363-8b05-d52af319a3a8)


After fixing the issue (Production):

![image](https://github.com/user-attachments/assets/af66cc96-7c76-4de4-8b5b-281245ceb3d3)
