### ISSUE TITLE
[Google Lens Image Sources API] Playground examples in the documentation are broken

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#2175]
The documentation playground examples for Google Lens Image Source API are broken.

![Screenshot 2024-11-26 at 9 08 33 AM](https://github.com/user-attachments/assets/abbb22a2-a4db-4292-b0a8-b1834127a4e2)

Public links: [Playground 1](https://serpapi.com/playground?engine=google_lens_image_sources&page_token=MDYxZjE2ZGQtYzEzZC00N2RiLWEzMjctOWRlMjFjYWM0NjNl) | [Playground 2](https://serpapi.com/playground?engine=google_lens_image_sources&page_token=MjAwYjM2NzMtNTNmYi00NjZiLWE1OTgtNjIyMzkwMWVmZmNh) | [Documentation](https://serpapi.com/google-lens-image-sources-api)

**Comment by btaunt** [comment]
Past fix related: https://github.com/serpapi/SerpApi/pull/4828

**Comment by btaunt** [comment]
The `page_token` for both the default playground and documentation examples has been updated:

- [Playground](https://serpapi.com/playground?engine=google_lens_image_sources&no_cache=true)
- [Documentation](https://serpapi.com/google-lens-image-sources-api)
