### ISSUE TITLE
[New API] Scrape Meta Ads Library

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#2176]
A customer requested we scrape the Meta Ads Library:
https://www.facebook.com/ads/library

Example:
https://www.facebook.com/ads/library/?active_status=active&ad_type=all&country=US&is_targeted_country=false&media_type=all&q=business%20loans&search_type=keyword_unordered
<img width="1269" alt="Screenshot 2024-11-26 at 2 21 18 PM" src="https://github.com/user-attachments/assets/5fe986f8-2075-4902-87e7-6fab6a5ede77">

Internal links: [Front](https://app.frontapp.com/open/cnv_1dzqbnq4?key=SqDF_WfUQm1LS7bbwk-1l3S5S3kdcKNz)

**Comment by schaferyan** [comment]
I think this is a duplicate of https://github.com/serpapi/public-roadmap/issues/1205

**Comment by sonika-serpapi** [comment]
Closing as this is a duplicate.
