### ISSUE TITLE
[Bing Search API] Scrape `external_link` for `inline_ads_results`

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#2177]
A customer reached out requesting we scrape the `external_link` for `inline_ads_results` from the Bing Search API. We introduced the `external_link` for `shopping_results` in #1795. 

`inline_ads_results`:

<img width="1653" alt="image" src="https://github.com/user-attachments/assets/5ace411c-dd1c-4743-92b0-1fa49c12ed2e">

`shopping_results`:

<img width="1648" alt="image" src="https://github.com/user-attachments/assets/0e6d48ef-89f5-469b-9313-077587da3f55">

[Playground](https://serpapi.com/playground?engine=bing_shopping&q=Coffee)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000071398?view=List)

**Comment by KBCG** [comment]
@NateSkiles  Any updates on this?

**Comment by schaferyan** [comment]
@KBCG thanks for checking in. Unfortunately, we don't have an update for you at this time. We will be sure to let you know when this feature is implemented. Thanks for your patience in the meantime!

**Comment by Krugloff** [comment]
<img width="1456" alt="image" src="https://github.com/user-attachments/assets/345336f4-a8b3-4aa4-a883-c3ade6592f49">

It's now available.

**Comment by NateSkiles** [comment]
@KBCG Just wanted to ping you here for visibility. We are now scraping `external_link` for `inline_ads_results` on the Bing Search API.

Let us know if you have any questions!
