### ISSUE TITLE
[Google Search API] Ads duplicated in organic results in mobile results

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#2182]
Customer reported a query where `device=mobile` where the sponsored results appeared both in `ads` and `organic_results`. I've reproduced the issue with their query, but have not been able to reproduce it with other queries.

Sponsored results are correctly organized into `ads`.

![image](https://github.com/user-attachments/assets/2402df87-3d28-4519-bef9-9ea3ddd9ec2f)

But the same 4 sponsored results are duplicated in `organic_results`.

![image](https://github.com/user-attachments/assets/6f846528-17a1-4a1f-96fe-b76a953810e2)

The true top 4 organic results are pushed down to position 5 and beyond.

![image](https://github.com/user-attachments/assets/58dd7a12-eb0b-4c0c-b6f6-e8b9f44f9aa2)

When `device=desktop`, sponsored results are not put into `organic_results`.

![image](https://github.com/user-attachments/assets/adde82c8-527d-4370-949a-28ae0a54fc23)

Public links: [Playground 1](https://serpapi.com/playground?q=best+online+casino&location=sydney%2C+new+south+wales%2C+australia&google_domain=google.com.au&gl=au&hl=en&num=100&device=mobile&newPara=as_sitesearch+chips+as_qdr)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072605?view=List) | [Search Inspect 1](https://serpapi.com/searches/6733662f707fd3c2254033da/inspect)

**Comment by btaunt** [comment]
This has been fixed. We no longer incorrectly parse ads results under `organic_results`.

 [Playground](https://serpapi.com/playground?q=best+online+casino&location=sydney%2C+new+south+wales%2C+australia&google_domain=google.com.au&gl=au&hl=en&num=100&device=mobile&google_domain=google.com.au&newPara=as_sitesearch+chips+as_qdr+votes+site+stick+highlight+lr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz+interval)
