### ISSUE TITLE
[Google Search API] Some ad descriptions are not returned in JSON response

### ISSUE THREAD

**Issue by alexbarron** [serpapi/public-roadmap#2183]
A potential customer reported some searches where we display the ad descriptions in the HTML preview, but do not return `description` in the JSON response. The behavior is inconsistent where the same search will return some ad descriptions and omit others.

I was able to reproduce the issue:

![image](https://github.com/user-attachments/assets/5ef50a2c-9873-47f5-93a1-fede28d83be6)

![image](https://github.com/user-attachments/assets/a188af62-7725-41a1-8768-2d68364d0e85)

Public links: [Playground 1](https://serpapi.com/playground?q=digitalocean+alternatives&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&newPara=as_sitesearch+chips+as_qdr)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072609?view=List) | [Search Inspect 1](https://serpapi.com/searches/67489723207c8819885be27f/inspect) | [Search Inspect 2](https://serpapi.com/searches/6748991454163da9e40353e4/inspect) | [Search Inspect 3](https://serpapi.com/searches/67489ebe707fd3dc0d47d4dd/inspect)

**Comment by btaunt** [comment]
We now correctly parse the "new" element set for `description` content within Google Search `ads`.

- [Playground](https://serpapi.com/playground?q=digitalocean+alternatives&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&newPara=as_sitesearch+chips+as_qdr)

<img width="652" alt="Screenshot 2024-11-29 at 1 31 24 PM" src="https://github.com/user-attachments/assets/af114228-8d01-45b5-963e-36974e8f768f">
