### ISSUE TITLE
[Google Food API] Google Food is Deprecated by Google

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#2186]
As noted in https://github.com/serpapi/public-roadmap/issues/2107, Google has stopped offering the Google Food pages. 

<img width="1243" alt="Screenshot 2024-11-29 at 3 43 40 PM" src="https://github.com/user-attachments/assets/b4cfa731-f97b-4601-b4bb-92e36915d165">

<img width="1063" alt="Screenshot 2024-11-29 at 3 42 22 PM" src="https://github.com/user-attachments/assets/82565d31-d44f-4586-8c2e-095282ea549b">

Requests to food.google.com are redirected to google.com. Google has replaced E2E food ordering with a redirect model. Since we can't scrape something that isn't there, we should update our documentation to reflect this and remove Google Food from the Playground.

Public links: [Playground](https://serpapi.com/playground?engine=google_food&gl=us&hl=en&lat=30.267153&lng=-97.7430608&q=Coffee)  | [Reference](https://help.zuppler.com/support/solutions/articles/47001267250-google-end-to-end-e2e-food-ordering-transition-google-redirect-updated-guidelines-for-partners) | [Deprecated Google Food Endpoint](https://www.food.google.com/)

Internal links: [Search Inspect](https://serpapi.com/searches/674a27384a3fcf1721636736/inspect)

**Comment by dsojevic** [comment]
A notice has been added to the documentation and our Google Food API will no longer accept new searches.

![image](https://github.com/user-attachments/assets/34764770-dd46-419a-a345-eea368952e4c)
