### ISSUE TITLE
[Google Images API] Pagination Not Working

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#219]
Google Images API never returns `serpapi_pagination` key and `start` parameter is not working. If you also check the images from the first page and second page requested by start=100, you will notice that same images are shown by Google.

**First Page** [Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=isch&num=100&no_cache=true) | [Inspect](https://serpapi.com/searches/62cd74e01c450ab114408af8/inspect)

<img width="952" alt="images_page1" src="https://user-images.githubusercontent.com/64849049/178499579-4581cbd6-7ee5-4a50-b26f-b693a8223f7b.png">

**Second Page** [Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=isch&start=100&num=100&no_cache=true) | [Inspect](https://serpapi.com/searches/62cd7526fdca3e9b5f1414cb/inspect)

<img width="956" alt="images_page2" src="https://user-images.githubusercontent.com/64849049/178499993-76900d36-af48-4d22-9048-4581bc0b438b.png">

**Comment by tanys123** [comment]
@aliayar, for Images API we are using `ijn` instead of `num` and `start`. And we also do not know the total number of pages. User have to keep increasing the `ijn` until empt result response.

We have added UI enhancement to Playground
<img width="329" alt="Screenshot 2022-07-13 at 2 43 55 PM" src="https://user-images.githubusercontent.com/10222402/178669722-3938223a-c15d-4221-9403-191749f618b6.png">

**Comment by dimitryzub** [comment]
In addition to the @tanys123's response, here's a Python example using [SerpApi Python package](https://github.com/serpapi/google-search-results-python) and utilizing `ijn` parameter to extract all available images:

```python
from serpapi import GoogleSearch
from urllib.parse import (parse_qsl, urlsplit)

params = {
    "api_key": "...",           # your serpapi api key
    "engine": "google",         # search engine
    "q": "minecraft redstone",  # search query
    "gl": "us",                 # country of the search
    "hl": "en",                 # language
    "ijn": 0,                   # page number: 0 -> first page, 1 -> second...
    "tbm": "isch"               # image results
}

search = GoogleSearch(params)   # where data extraction happens

# to show the page number
page_num = 0

image_results = []

while True:
    results = search.get_dict() # JSON -> Python dictionary

    page_num += 1
    print(f"Current page: {page_num}")

    # checks for "Google hasn't returned any results for this query."
    if "error" not in results:
        for image in results.get("images_results", []):
            image_results.append(image["original"])

        # update (paginate) to the next page
        params["ijn"] += 1
    else:
        print(results["error"])
        break
```

**Comment by aliayar** [comment]
Sorry, long day. I felt like I was missing something. Turns out I have missed :)

**Comment by ilyazub** [comment]
The `serpapi_pagination` is missing for the Google Images API.

![image](https://github.com/serpapi/public-roadmap/assets/282605/be636c6e-d5e2-40ba-aded-75f3fe315644)

[Search Inspector](https://serpapi.com/searches/651ffb17c640d2d85e71a25f/inspect) | [Playground](https://serpapi.com/playground?engine=google_images&q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&ijn=2&ijn=2&newPara=ijn)
