### ISSUE TITLE
[Google Search API] items from `perspectives` are parsed into `top_stories`

### ISSUE THREAD

**Issue by sonika-serpapi** [serpapi/public-roadmap#2191]
A customer reported that some `perspectives` are parsed into `top_stories` incorrectly sometimes. 

When I investigated this, it seems like we are parsing the first few links from perspectives (or "What People are saying" section into `top_stories`, but there is no actual Top stories block in the search results. 

Perspectives parsed correctly:
<img width="1346" alt="Screenshot 2024-12-03 at 2 07 10 PM" src="https://github.com/user-attachments/assets/83a0d171-82ed-48f2-9db9-c12165855f8e">

first few results parsed into `top_stories` partially:
<img width="1348" alt="Screenshot 2024-12-03 at 2 07 00 PM" src="https://github.com/user-attachments/assets/8e6e039a-ac75-4f78-b345-bb47f93a260b">

Public links: [Playground](https://serpapi.com/playground?device=mobile&engine=google&gl=us&google_domain=google.com&hl=en&location=Chicago%2CIllinois%2CUnited+States&q=iPhone+17+Ultra) | [Documentation](https://serpapi.com/top-stories)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072741?view=List) | [Search Inspect 1](https://serpapi.com/searches/674f1e44b4b72dd53eb5fe91/inspect) | [Search Inspect 2](https://serpapi.com/searches/674f1d6ac76a22c12c74da4b/inspect)

**Comment by btaunt** [comment]
This has been resolved. We no longer incorrectly parse `perspectives` items under `top_stories`

[Playground](https://serpapi.com/playground?q=iPhone+17+Ultra&location=Chicago%2CIllinois%2CUnited+States&gl=us&hl=en&device=mobile&google_domain=google.com&newPara=as_sitesearch+chips+as_qdr+votes+site+stick+highlight+lr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz+interval)
