### ISSUE TITLE
[Google Shopping API] Remove `start` from `serpapi_product_api` URL

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#2194]
A customer reported the `serpapi_product_api` URLs provided for `shopping_results` in paginated Google Shopping API responses incorrectly include the `start` parameter:

<img width="1447" alt="Screenshot 2024-12-04 at 11 09 31 AM" src="https://github.com/user-attachments/assets/54c6480b-3c8d-47a8-a629-1a9755589000">

This results in an error, since `start` is not supported for the Google Product API, except with Online Sellers (`offers`):

<img width="1447" alt="Screenshot 2024-12-04 at 11 13 33 AM" src="https://github.com/user-attachments/assets/3495488f-161f-4133-abbd-adc9811b163c">

To resolve this we should stop appending `start` to the `serpapi_product_api` URL. In the meantime, users can work around this by removing the `start` parameter from the URL on their side before using it to send requsts to the Google Product API.

Public links: [Playground 1](https://serpapi.com/playground?engine=google_shopping&q=Coffee&gl=us&hl=en&start=10&device=desktop&newPara=direct_link) | [Playground 2](https://serpapi.com/playground?engine=google_product&product_id=16690555506933265193&gl=us&hl=en&start=10&device=desktop) 

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072786?view=List) | [Search Inspect 1](https://serpapi.com/searches/6750a8a1fcd69e5f068b1d34/inspect)

**Comment by zyc9012** [comment]
We've deployed a fix for this. `start` is excluded from `serpapi_product_api`

![image](https://github.com/user-attachments/assets/b6273b37-a620-475e-9b55-df16c54bdd77)
