### ISSUE TITLE
[Google Maps API] Extract price range

### ISSUE THREAD

**Issue by zyriab** [serpapi/public-roadmap#2197]
Currently, the field `price` only has the `$`, `$$`, `$$$`, ... value but never the `$10-20` one.

![image](https://github.com/user-attachments/assets/58e69fb2-d69b-4a09-a388-e9eb4083cd84)

In the above screenshot, the middle `price` will be present (as `"price": "$$$"`) but the top and bottom ones won't.
It would be great if these could be present as well, just as they are displayed by Google. :)

Here's the search ID: 67510d906a5dd3b8b81b07c4

Thanks and have a good one!

**Comment by hilmanski** [comment]
Hi @zyriab, thank you for your report. Can you please share the search ID of your search?

**Comment by hilmanski** [comment]
I think we can replicate this, so there's no need for the search ID. Again, thank you very much for your report.

Internal notes:
Right now, we're not scraping the price information when numbers exist.

[Inspect sample](https://serpapi.com/searches/675113c5d364b40e32ab4ae8/inspect)

**Comment by zyriab** [comment]
Hey thanks for the fast response, added it still (if I didn't mix it up with something else!)

**Comment by hilmanski** [comment]
Thank you very much!

**Comment by ishiharaf** [comment]
We've fixed the extraction of prices and price ranges.

![image](https://github.com/user-attachments/assets/0a52e269-4311-40fb-be4b-1f41561d844b)
[Playground](https://serpapi.com/playground?engine=google_maps&q=restaurants+in+brussels&ll=%4050.8398614%2C4.3360487%2C14z&hl=en&type=search&no_cache=true)

![image](https://github.com/user-attachments/assets/f24fb58b-93a1-4432-be6e-5fbb92e9afe2)
[Playground](https://serpapi.com/playground?engine=google_maps&q=restaurants+in+tokyo&ll=%4035.6437357%2C139.6834304%2C14z&hl=en&type=search&no_cache=true)

**Comment by zyriab** [comment]
Thank you very much, you rule!
