### ISSUE TITLE
[Google Images API] Missing attributes for paginated results

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#2199]
A user reported missing attributes when including the `ijn` parameter to paginate results.

Missing attributes:
* `source`
* `source_logo`
* `title`
* `link`
* `thumbnail`

### Without `ijn` parameter:

![image](https://github.com/user-attachments/assets/0a1b48d0-5a9c-41b9-8f53-57474730d48f)

[Playground](https://serpapi.com/playground?engine=google_images&q=playstation+5&gl=us&hl=en&filter=0&device=desktop&no_cache=true)

### With `ijn=1`:

![image](https://github.com/user-attachments/assets/76a2a36c-bab3-42bf-b0f5-c822be87e023)

[Playground](https://serpapi.com/playground?engine=google_images&q=playstation+5&gl=us&hl=en&filter=0&ijn=1&device=desktop&no_cache=true)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072830?view=List) | [Search Inspect 1](https://serpapi.com/searches/6751f6fad169150eaa077869/inspect) | [Search Inspect 2](https://serpapi.com/searches/6751f6ffbb64acd542627b57/inspect)

**Comment by hilmanski** [comment]
Hi @tanys123 , I think we're currently still missing the source_logo 

[Inspect](https://serpapi.com/searches/6757ce802da508f311018c64/inspect)

**Comment by tanys123** [comment]
> I think we're currently still missing the source_logo. I guess that's the expected behaviour?

Unfortunately yes, that data is missing from the endpoint we use. For the latest deployment, `source`, `title` and `link` are recovered.

<img width="1330" alt="Screenshot 2024-12-11 at 9 41 51 AM" src="https://github.com/user-attachments/assets/aaa75f6f-f48f-4491-b824-1d88c7378297">

**Comment by hilmanski** [comment]
Thanks, @tanys123 . Should we log this as a bug (only for the source_logo)?

**Comment by tanys123** [comment]
> Should we log this as a bug (only for the source_logo)?

I think we should if there are customers asking for it. Unfortunately there is nothing we can do until switch to the [new endpoint](https://github.com/serpapi/SerpApi/issues/5629).
