### ISSUE TITLE
[Google Search API] Information are missing from 'Related Searches' on mobile

### ISSUE THREAD

**Issue by tanys123** [serpapi/public-roadmap#2201]
Happening to multiple searches in mobile

<img width="1329" alt="Screenshot 2024-12-06 at 9 35 32 AM" src="https://github.com/user-attachments/assets/063f81d2-a85e-484d-97d4-16cb4cf5c762">

<img width="1217" alt="Screenshot 2024-12-06 at 9 37 21 AM" src="https://github.com/user-attachments/assets/34fb233d-cb43-4c19-8731-8e8cb8666631">

Public links: [Playground 1](https://serpapi.com/playground?q=Black+Myth+Wukong&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile) | [Playground 2](https://serpapi.com/playground?q=Apple+Juice&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile)

Internal links: [Inspect 1](https://serpapi.com/searches/6752549be92456ff107fd429/inspect) | [Inspect 2](https://serpapi.com/searches/675255427e1d1f753d13b924/inspect)

**Comment by btaunt** [comment]
We now properly parse all `related_searches` information for these newer UI layouts.

[Playground 1](https://serpapi.com/playground?q=Black+Myth+Wukong&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&google_domain=google.com&newPara=as_sitesearch+chips+as_qdr+votes+site+stick+highlight+lr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz+interval) | [Playground 2](https://serpapi.com/playground?q=Apple+Juice&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&google_domain=google.com&newPara=as_sitesearch+chips+as_qdr+votes+site+stick+highlight+lr+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+ijn+rlz+interval)

<img width="848" alt="Screenshot 2024-12-11 at 8 36 41 AM" src="https://github.com/user-attachments/assets/adfeef8d-811c-4b92-9d57-9f855b00bc29" />
