### ISSUE TITLE
[Google Flights API] A discrepancy on the API result with live result

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#2209]
A customer reported that our API shows a different result from the live result.

Google Flights Website
![image](https://github.com/user-attachments/assets/72207afe-108b-4a09-a720-95631263e388)

SerpApi response 
![image](https://github.com/user-attachments/assets/5b63bbb3-3496-4994-90c9-d1f1e32182e7)

Internal links: [Front](https://app.frontapp.com/open/cnv_1e1swq8s?key=pOu8f7pK3b2KvEzzMfqyoG-7MA9FzfbF) | [Search Inspect](https://serpapi.com/searches/67542c19707fd3a6072eb414/inspect)

**Comment by hilmanski** [comment]
I can replicate this issue. I'm using a VPN for the US. Differences: 
- lowest total price
- City name instead of airport code

![CleanShot 2024-12-09 at 09 28 53@2x](https://github.com/user-attachments/assets/cb861e8c-b8f9-4c5f-b03a-87e9b947bae3)

The price might be affected by the "Booking options" which are different.:
![CleanShot 2024-12-09 at 09 30 20@2x](https://github.com/user-attachments/assets/2cd24424-7013-47b0-9e61-7f6d8d884a6b)

**Comment by hartator** [comment]
I am not sure if this fixable as dynamic pricing for flights is very - dynamic.

In my experience in the US for Google Flights, I can look on my Iphone and on my MBP connected to same wifi and see different prices and even different route options for the same exact same trip.

**Comment by hartator** [comment]
Closing, but feel free to re-open if I am missing something.
