### ISSUE TITLE
[Google Shopping API] Product image links are incorrect

### ISSUE THREAD

**Issue by NateSkiles** [serpapi/public-roadmap#2211]
Two customers reported that image links from the Google Shopping API are returning not found on searches less than a month old:

```json
{
    "error": "Search not found."
}
```

![image](https://github.com/user-attachments/assets/8ee17a68-7833-4134-b0dd-5c19ec0121eb)

[Inspect](https://serpapi.com/searches/6755b9d89936883006d0df12/inspect)

![image](https://github.com/user-attachments/assets/e337fa28-2cea-4ee4-b45d-8343e2fa29fc)

[Image Link](https://serpapi.com/searches/6755b9d89936883006d0df12/images/067830757034501a1a406434f310f58e31a1f17885b94cfdee9cd7c8e1d3dcd2.webp)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072926?view=List) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000072902?view=List)

**Comment by hartator** [comment]
@tanys123 We have released a fix for this.
