### ISSUE TITLE
[Google AI Overview API] AI Overview JSON Internal Side Error

### ISSUE THREAD

**Issue by boomer3boom** [serpapi/public-roadmap#2213]
I have already read https://serpapi.com/google-ai-overview-api. I am accessing these tokens within 4mins and am using the following code as instructed:

```
params = {
        "engine": "google_ai_overview",
        "page_token": pg_token,
        "api_key": api_key
    }

search = GoogleSearch(params)
```

The result leads to a HTTP 500 error code. I went online SerpAPI website -> Your searches and viewed the JSON file from there. To which it returns a: 
<img width="361" alt="Screenshot 2024-12-10 at 10 32 03 am" src="https://github.com/user-attachments/assets/f20f2a12-27ca-44eb-9ca0-f4e300b39c80">

I also had a look at the HTML file which is returning somewhat useful information but JSON is obviously much more preferred.

**Comment by hilmanski** [comment]
Hi @boomer3boom,

I apologize for the issue you're facing. I'll be happy to help. Can you please share the search ID here? Your search ID is available at https://serpapi.com/searches. 

You can also contact us via chatbox for faster response or send the details via email to contact@serpapi.com for support.

**Comment by boomer3boom** [comment]
Hi, the search id is (copied directly from the website):
[6757a7e8d3a5674da790c7a0](https://serpapi.com/searches/6757a7e8d3a5674da790c7a0/inspect)

**Comment by hilmanski** [comment]
Thank you for sharing the search ID. Can you please clarify if the search was performed recently or if it was a day(s) ago?

**Comment by boomer3boom** [comment]
This search id I provided should be recently. But I preformed similar experiment and searches a few days ago as well.

**Comment by hilmanski** [comment]
Thank you very much. I can confirm that we currently have an issue with our Google AI Overview. Thank you very much for your report. We'll let you know once we have any update on this issue.

**Internal notes:**
I can replicate the 500 error for the AI overview result.
[Sample initial search](https://serpapi.com/searches/6757ae265edcfbbd7b316be7/inspect) | [Google AI Overview Search](https://serpapi.com/searches/6757ae424e3622bc8f23b816/inspect)

**Comment by zyc9012** [comment]
We've released a fix for this. Now the results are properly parsed.

![image](https://github.com/user-attachments/assets/9fd20a6f-e2a9-4e28-916d-3229f765d081)

**Comment by hilmanski** [comment]
Hi @boomer3boom tagging you for visibility. We apologize for the issue. You should be able to see the results from now on.

**Comment by boomer3boom** [comment]
Yup this works on my side as well, thanks!
