### ISSUE TITLE
Allow to provide callback in URL for `async=true` search

### ISSUE THREAD

**Issue by oaons** [serpapi/public-roadmap#2214]
Allow to provide callback URL and ping it once the request has finished processing on the server when async=true 

For example https://serpapi.com/search?q=serpapi&callback[method]=POST&callback[url]=https://my.server.com/serpapi-callback&callback[param]=7267&async=true

When an asynchronous request with callback is complete, SerpApi should "ping" the callback url, using the selected callback method, and passing the callback custom parameter as-is. Additionally include search_id / search_id_url in the callback request to be able easily retrieve result via [Search Archive API](https://serpapi.com/search-archive-api)

Public links:  [Documentation](https://serpapi.com/search-api)

**Comment by hilmanski** [comment]
Thank you very much for your feature request @oaons.

**Comment by hilmanski** [comment]
As a temporary solution, you can set up a queue to run a minute after your search, check the status of the search you just executed, and take any necessary actions. Or set up a CRON that run every minute to check for your searches. This solution will require you to store the searchID in your own database.

I hope this helps.

**Comment by hartator** [comment]
We don’t plan to provide callbacks (i.e., webhooks) for `async` searches.

All `async` searches should be completed in 10 minutes or less. Your app can reliably poll serpapi.com using the JSON endpoint to retrieve your search data after 10 minutes. Webhooks are typically provided for processes that take hours or days to complete. Which won't be the case for `async` searches.
