### ISSUE TITLE
[Google Scholar Author API] Need a line break for the description's text

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#2215]
I noticed that our response for the description field in the Google Scholar Author API is in one long string without a line break.

![CleanShot 2024-12-10 at 13 53 29](https://github.com/user-attachments/assets/2ba3e918-d5ff-4c62-b919-382dbc8f15ca)

Public links: [Playground 1](https://serpapi.com/playground?engine=google_scholar_author&author_id=EicYvbwAAAAJ&hl=en&view_op=view_citation&citation_id=EicYvbwAAAAJ%3AUeHWp8X0CEIC)

Internal links: [Search Inspect 1](https://serpapi.com/searches/6757d5543f30aff1875ba44d/inspect)

**Comment by btaunt** [comment]
It would most likely impact the current rendering for existing customers, but this would be much cleaner if we broke these down into individual sets, ie:

```
"context": "Little is known about lifetime prevalence or age of onset of DSM-IVdisorders",
"objective": "To estimate lifetime prevalence and age-of-onset distributions of DSM-IVdisorders in the recently completed National Comorbidity Survey Replication",
...
```

**Comment by hilmanski** [comment]
Is it possible to add `\n` after each DIV instead of separating them?
![CleanShot 2024-12-13 at 07 14 38](https://github.com/user-attachments/assets/e14f8f41-4128-4bc0-a400-4f11130f29a2)

**Comment by ishiharaf** [comment]
It's possible to add a newline after each string (it renders as `\n` in raw JSON). I agree that it would be nicer to to have those broken down into sections, but this would break the API for existing users 🤔

![image](https://github.com/user-attachments/assets/8962e74b-fd19-4b29-9eb1-0d89a23bd71a)

I'll test with more queries and open a PR.

**Comment by ishiharaf** [comment]
We've added a line break to the description field value.

Query with a line break and raw JSON:
![image](https://github.com/user-attachments/assets/e519276a-7310-481a-9aa0-a922e1f1fc05)
![image](https://github.com/user-attachments/assets/7cd4dbbc-938a-4f1f-9f8e-d7bad11e3a45)
[Playground](https://serpapi.com/playground?engine=google_scholar_author&author_id=EicYvbwAAAAJ&hl=en&view_op=view_citation&citation_id=EicYvbwAAAAJ%3AUeHWp8X0CEIC)

Query with no line break:
![image](https://github.com/user-attachments/assets/40837a6b-c999-40e6-b1ed-2874a63bd84e)
[Playground](https://serpapi.com/playground?engine=google_scholar_author&author_id=LSsXyncAAAAJ&hl=en&view_op=view_citation&citation_id=LSsXyncAAAAJ%3Ad3xjRt2Mi1YC&no_cache=true)

**Comment by hilmanski** [comment]
Thank you very much @ishiharaf for your update and your work!
