### ISSUE TITLE
[Yelp Search API] Slow response times and 503 errors

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#2217]
An Enterprise customer reported slow response times and 503 errors with the Yelp Search API. 

Our status graph confirms slower response times since November 18:

<img width="1129" alt="Screenshot 2024-12-10 at 11 39 41 AM" src="https://github.com/user-attachments/assets/7c02736b-7cfa-46fe-a44e-e53584472e68">

We fixed a similar issue in August. I'm opening a new issue, rather than reopening https://github.com/serpapi/public-roadmap/issues/1838 as it may have an unrelated cause.

Public links: [Playground 1](https://serpapi.com/playground?engine=yelp&find_desc=iHop&find_loc=Austin%2C+TX%2C+United+States&no_cache=true) | [Playground 2 ](https://serpapi.com/playground?engine=yelp&find_desc=fast+food&find_loc=Austin%2C+TX%2C+United+States)

Internal links: [Front ](https://app.frontapp.com/open/msg_2kunnxgc?key=wd8013JJahcja5tKIdUaJMhSu4b06Gau)| [Search Inspect 1 ](https://serpapi.com/searches/67589a41ac262a41f7e5b0bc/inspect)| [Search Inspect 2](https://serpapi.com/searches/67589a1dcf3bc93e9970863d/inspect)

**Comment by dsojevic** [comment]
@schaferyan, I deployed a fix and response times should now be fairly close to what they were prior to the issue.

**Comment by hilmanski** [comment]
Thank you @dsojevic. Let's monitor for some time before informing the customer.

**Comment by dsojevic** [comment]
> Thank you @dsojevic. Let's monitor for some time before informing the customer.

@hilmanski, looks like it has been quite stable since the fix was put in place:
![CleanShot 2024-12-13 at 23 55 20](https://github.com/user-attachments/assets/0b302cc4-bbee-4d6f-bbf7-b61ff707c723)

**Comment by hilmanski** [comment]
Thanks, @dsojevic . I've reached out to the customer.
