### ISSUE TITLE
[Google Search API] Improve Consistency of `answer_box.type` Across Different Locales

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#2223]
Currently, as noted in https://github.com/serpapi/public-roadmap/issues/352#issuecomment-1321882170 we often return a different `answer_box.type` depending on the locale of a search. A customer requested we standardize this and return the `type` in English regardless of the locale. This is important for their use case.

<img width="1462" alt="Screenshot 2024-12-11 at 2 31 23 PM" src="https://github.com/user-attachments/assets/601ae6e6-a049-43e0-a612-933bea3129ef" />
<img width="1458" alt="Screenshot 2024-12-11 at 2 34 06 PM" src="https://github.com/user-attachments/assets/06c156b7-fb43-4c18-a5e6-f69bdd9813ea" />

I've informed the customer that in many cases this is beyond our control, as we sometimes need to parse the answer box dynamically and return the text provided by Google as the `type`.

However, for some of the answer box types the customer listed (translation results, calculator results etc.), we already have specific parsing logic. For these, it seems potentially possible to provide a standardized `type`.

Public links: [Playground 1](https://serpapi.com/playground?q=5%2B3&location=Austin%2C+Texas%2C+United+States&gl=us&hl=hy&google_domain=google.com) | [Playground 2](https://serpapi.com/playground?q=Translate+%22I+went+to+the+store%22+to+spanish&location=Austin%2C+Texas%2C+United+States&gl=us&hl=hy)
Internal links: [Front](https://app.frontapp.com/open/msg_2kx0iin0?key=fh3EM2ezZmXjkVKOA9LvHo_sgZ8xRAQ6) | [Inspector](https://serpapi.com/searches/675a133b8f148af2930df40e/inspect)

**Comment by btaunt** [comment]
This has been updated. We how parse the static types: `calculator_result` and `translation_result` 

[Playground 1](https://serpapi.com/playground?q=5%2B3&location=Austin%2C+Texas%2C+United+States&gl=us&hl=hy&google_domain=google.com) | [Playground 2](https://serpapi.com/playground?q=Translate+%22I+went+to+the+store%22+to+spanish&location=Austin%2C+Texas%2C+United+States&gl=us&hl=hy) | [Documentation](https://serpapi.com/direct-answer-box-api#api-examples-translation-answer-box)
