### ISSUE TITLE
[Google Scholar API] Publications in Arabic not parsed correctly.

### ISSUE THREAD

**Issue by paholg** [serpapi/public-roadmap#2225]
Publications in Arabic are not parsed correctly.

See this example; a paper from 2007 is returned in Arabic from Google Scholar. But SerpApi populates the publication with the author list, and doesn't populate the authors field at all. It's a little bit hard to see because the HTML renders the text right to left, whereas it's left-to-right in the JSON. But notice the ellipses on the first grey text in the HTML; this matches the ellipses on the publication field in the JSON.

![2024-12-12_09 39 00-s](https://github.com/user-attachments/assets/ffb2d3ee-2ef7-4e94-95b0-6067962d485c)

Public links: [Playground Link](https://serpapi.com/playground?engine=google_scholar_author&author_id=Pe3ZNkMAAAAJ&hl=en&sort=pubdate&num=100)

**Comment by hilmanski** [comment]
Thank you very much, @paholg, for reporting this issue. We'll make sure to update you on this thread.

[Inspect](https://serpapi.com/searches/675b6eaff09cbcaa72e60cdd/inspect)

**Comment by ishiharaf** [comment]
Thanks for reporting this issue @paholg. Please note this doesn't happen when the language is set to Arabic, so you can use it as a workaround until we fix it for other languages.

![image](https://github.com/user-attachments/assets/4cce20b5-243e-492a-8f32-43db2ea052e1)

[Playground Link](https://serpapi.com/playground?engine=google_scholar_author&author_id=Pe3ZNkMAAAAJ&hl=ar&sort=pubdate&num=100&no_cache=true)

**Comment by ishiharaf** [comment]
@paholg Parsing of publications in Arabic has been fixed.

![image](https://github.com/user-attachments/assets/ee0bc672-5617-40dc-85f6-86cca57196f6)
[Playground](https://serpapi.com/playground?engine=google_scholar_author&author_id=Pe3ZNkMAAAAJ&hl=en&sort=pubdate&num=100&no_cache=true)
