### ISSUE TITLE
Google Trends API Failing

### ISSUE THREAD

**Issue by CallumTeapeForbarr** [serpapi/public-roadmap#2227]
Hi team,

The google trends api seems to be falling over today with this log:

Any suggestions?

<img width="1185" alt="Screenshot 2024-12-13 at 2 57 19 PM" src="https://github.com/user-attachments/assets/7c1f8100-22eb-4578-beb7-5809d055fc04" />

**Comment by tanys123** [comment]
Hi @CallumTeapeForbarr, thanks for reporting the issue. We are aware of the recent drop of success rate on Google Trends and are actively working on it. There is already an [active thread](https://github.com/serpapi/public-roadmap/issues/2063) on this topic, please subscribed to it to stay updated on the issue. Thanks.
