### ISSUE TITLE
[Google Lens API] Sometimes Google Lens returned `no results for this query`

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#2236]
A customer reported that Google Lens often returns, "Google Lens hasn't returned any results for this query." Using no_cache=true sometimes can solve it. But I think we still need to investigate the root cause since I'm able to see the results directly on Google's side.

Internal links: [Front](https://app.frontapp.com/open/cnv_1e88bnh8?key=ruxOIjfaUCpoRBg37CFNa8vmFYFVd46i) | [Search Inspect 1](https://serpapi.com/searches/6760dca994185c1800d1317e/inspect)

It might be similar to this case: https://github.com/serpapi/public-roadmap/issues/1717

**Comment by cgmoffitt** [comment]
Hi, I am facing this same error. Here is an example response:

{
    "search_metadata": {
        "id": "6760f8f87d84dd21e90f4395",
        "status": "Success",
        "json_endpoint": "https://serpapi.com/searches/d30734b00c06c24f/6760f8f87d84dd21e90f4395.json",
        "created_at": "2024-12-17 04:07:20 UTC",
        "processed_at": "2024-12-17 04:07:20 UTC",
        "google_lens_url": "https://lens.google.com/uploadbyurl?url=https%3A%2F%2Firisai-generatedimages.s3.amazonaws.com%2F1734408419_fd98c537-1395-495d-9bca-6668d8618b5b.png",
        "raw_html_file": "https://serpapi.com/searches/d30734b00c06c24f/6760f8f87d84dd21e90f4395.html",
        "prettify_html_file": "https://serpapi.com/searches/d30734b00c06c24f/6760f8f87d84dd21e90f4395.prettify",
        "total_time_taken": 2.73
    },
    "search_parameters": {
        "engine": "google_lens",
        "url": "https://irisai-generatedimages.s3.amazonaws.com/1734408419_fd98c537-1395-495d-9bca-6668d8618b5b.png",
        "country": "US"
    },
    "search_information": {
        "images_results_state": "Fully empty"
    },
    "error": "Google Lens hasn't returned any results for this query."
}

**Comment by hilmanski** [comment]
Hi @cgmoffitt . Thank you very much for your report, and we apologize for this issue. We'll let you know in this thread once we have any updates.

**Comment by martin-serpapi** [comment]
A high-volume customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073139?view=List)

**Comment by hilmanski** [comment]
Another customer reported this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073223?view=List)

**Comment by andypple83** [comment]
I'm working on this issue. Will notify when I released the fix. Thanks

**Comment by marm123** [comment]
More examples from the customer @martin-serpapi  mentioned yesterday:

[Successful](https://serpapi.com/searches/6762a537d2420db31cbded16/inspect) | [Failed](https://serpapi.com/searches/6762a35872e8d46e02a45cf0/inspect) | [Failed](https://serpapi.com/searches/6762a356000454318deadcde/inspect)

**Comment by marm123** [comment]
We addressed the issue. Valid queries should now return results instead of an error message.

@cgmoffitt tagging for visibility.
