### ISSUE TITLE
[Google Search API] `references` missing in `ai_overview`

### ISSUE THREAD

**Issue by martin-serpapi** [serpapi/public-roadmap#2239]
A user reported that the `references` are missing in the `ai_overview` block. I was able to reproduce it in the Playground:

![image](https://github.com/user-attachments/assets/16e0706d-5e70-4b9b-a757-9b8bcb5fb09d)

[Playground](https://serpapi.com/playground?q=cc+vs+bcc&location=United+States&gl=us&hl=en&device=desktop&no_cache=true) | [Inspect](https://serpapi.com/searches/67615ae1b35809397d343ac7/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073196?view=List)

**Comment by zyc9012** [comment]
We've released a fix for this.

![20241224_085409](https://github.com/user-attachments/assets/fa84b985-7d8a-40e2-9d1d-63c4810a07e3)
