### ISSUE TITLE
[Google Search API] To display more info about clubs' fixtures in Sport API result (football)

### ISSUE THREAD

**Issue by wildan3105** [serpapi/public-roadmap#224]
Hi, I've been using serp API for the couple of weeks and I've thankful enough that you guys give developers a set of well-formed APIs from google in JSON format. In my case, I use google sport API to look for my favorite teams' upcoming fixtures. Currently, I've been using this request heavily:
```bash
POST https://serpapi.com/search?q=chelsea+fc+fixtures&api_key={{SERPAPI}}&location=indonesia
```

The results are great but there's something that definitely can be improved: provide **tournament** and **stadium** so it'll give comprehensive result of teams' fixtures. I've recorded the behaviors from the google here:

https://user-images.githubusercontent.com/7030099/179181181-2999c4d5-6fd5-476c-baa2-62cd6db349c5.mp4

So I hope you guys consider this request to add more fields (tournament and stadium) name along with the current results. Thank you!

**Comment by dimitryzub** [comment]
Hi @wildan3105 🙂 Thank you for adding an API feature request. 

It's currently in progress and we'll update you here and on Twitter, once it's done 🎯

**Comment by tanys123** [comment]
@wildan3105 We have deployed the update, you can verify it, make sure to pass `no_cache=true` to get new data. 

I think we are able to scrape more data on sport results. Let me know if u any new data you would need and I can try to find out.

**Comment by wildan3105** [comment]
> @wildan3105 We have deployed the update, you can verify it, make sure to pass `no_cache=true` to get new data. 
> 
> 
> 
> I think we are able to scrape more data on sport results. Let me know if u would need any more new data, I can try to find out.

Hey, thanks for the update! I've just tried it and found it worked! Awesome jobs 🙇🏻‍♂️ 
I'll update here later or create another issue once I need more data. For now, all is good ✌🏻

**Comment by wildan3105** [comment]
On the second thought though, if you guys can consistently provide the tournament info, that'd be very awesome! Because I saw sometimes you don't return that information (correct me if I'm wrong)
