### ISSUE TITLE
[Google Search API] Not parsing `references` and getting empty `list`s for AI Overview results

### ISSUE THREAD

**Issue by zyc9012** [serpapi/public-roadmap#2244]
![20241218_172530](https://github.com/user-attachments/assets/5e75ff38-1b23-4383-a1f5-1c8e894a05f3)

![20241218_172648](https://github.com/user-attachments/assets/ab2cfcad-200a-445e-b85e-d51f5f43b071)

Public links: [Playground](https://serpapi.com/playground?q=how+does+netlify+work&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=chips+as_sitesearch+highlight+stick+lr+as_qdr+votes+site+safe+google_domain+si+form+filter+as_epq+client+ie+oe+pws+ibp+source+rlz+ijn+interval)

Internal links: [Search Inspect](https://serpapi.com/searches/67629478cd2fc327ce63779b/inspect)

**Comment by martin-serpapi** [comment]
Related to #2239

**Comment by zyc9012** [comment]
We've released a fix for this.

![20241224_085341](https://github.com/user-attachments/assets/a5956452-e22d-46d2-aa4f-422315ea2aad)

![20241224_085409](https://github.com/user-attachments/assets/fa84b985-7d8a-40e2-9d1d-63c4810a07e3)
