### ISSUE TITLE
[Google Search API] Support key moments for organic results with videos

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#225]
![video](https://user-images.githubusercontent.com/73674035/179951252-61027fdd-cf98-4556-a2bb-60cb1523dfae.png)
[Inspect](https://serpapi.com/searches/62d7cc2de0ded4a6e7c0d369/inspect)
[Playground](https://serpapi.com/playground?q=mrbeast+videos&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true&newPara=stick+highlight+lr+async+as_qdr)

**Comment by aciddjus** [comment]
This issue has been resolved.

<img width="1574" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/39de31f5-554b-4448-9a0a-add01e2b5a99">

---------------

[Playground](https://serpapi.com/playground?q=coffee+videos&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true)

Resolved in: https://github.com/serpapi/SerpApi/pull/2409
