### ISSUE TITLE
[Google Search API] only ~10 results are returned despite `num=100` parameter has been specified 

### ISSUE THREAD

**Issue by oaons** [serpapi/public-roadmap#2251]
Google Search API , both json and html, return ~10 results for some particular keywords despite `num=100` parameter has been specified 

For example:
```
$ curl --get https://serpapi.com/search \
 -d engine="google" \
 -d q="julio+iglesias" \
 -d location="United+States" \
 -d hl="en" \
 -d gl="us" \
 -d google_domain="google.com" \
 -d num="100" \
 -d start="0" \
 -d output="json" \
 -d api_key="..." > julioiglesias.json

$ cat julioiglesias.json | jq '.organic_results | length'
9
```
In HTML also only about ~10 results can bee seen

There is pagination block both in HTML and json, so there are definitely more than 10 results
```
$ cat julioiglesias.json | jq '.pagination | length'
3
```

**Comment by hilmanski** [comment]
Hi @oaons,  

Thank you for your report and apologize for the issue. Can you please share the search ID? 

We have an open issue with this: https://github.com/serpapi/public-roadmap/issues/753. We'll reach out once we have any updates on this.

**Comment by oaons** [comment]
> Can you please share the search ID?

`serpapi-search-id: 6764da5bf4afd56bc97dba73`

**Comment by hilmanski** [comment]
Thank you very much for sharing the search ID. I really appreciate it. 

As a temporary solution, you can try our Google Lights API:
- Docs: https://serpapi.com/google-light-api
- Sample search: https://serpapi.com/playground?engine=google_light&q=julio+iglesias&gl=us&hl=en&num=100
