### ISSUE TITLE
[Google Search API] Broken List Parsing for some AI Overviews (AIO) Results

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#2261]
A high volume customer noted that list parsing seems to be broken in some AIO results.

![bc8f34f81ae5d4af6e1c3f5ef2c07209bfa9c73e](https://github.com/user-attachments/assets/16ed2381-dbb1-4b3b-99cc-d605e32376db)
![e73d153ad1aec550c555fbca913a627dc04e3839](https://github.com/user-attachments/assets/d7a55ede-8e91-41ad-95f4-6c0b7bfc381d)

The customer who reported this also suggested we return the AI Overviews in Markdown instead of parsing it out into JSON. They noted it could potentially be easier for us since AIO results don't follow a consistent format and seem to be in Markdown already. It would also be easier for the customer, as currently they have to translate the JSON back into Markdown. I've let them know this may be out of scope for us, but wanted to note it here in case it's something we can consider.

Internal links: [Front 1](https://app.frontapp.com/open/msg_2lc0zod8?key=jjOEQp8jV8K3Tx8MbHi8CH2ZiUM1ve2b) | [Front 2](https://app.frontapp.com/open/msg_2lc24vfg?key=v4K4bXJSa-brV6YvxpaW3xpgidmksYBj) | [Front 3](https://app.frontapp.com/open/msg_2lc403fg?key=__TBG5njHvdG2sMaaMJugtGPdRvw34dS) | [Search Inspect 1](https://serpapi.com/searches/6769a65a5951b03eb569aadb/inspect)  | [Search Inspect 2](https://serpapi.com/searches/6769a8288eeee6ee7cbeca9b/inspect)

**Comment by zyc9012** [comment]
We've released a fix for this.

![20241224_090308](https://github.com/user-attachments/assets/092f6e15-8030-408e-9585-dbf866bca00d)

![20241224_090157](https://github.com/user-attachments/assets/780375af-f3e4-4d63-af92-98c2f7a051e8)
