### ISSUE TITLE
[Google Scholar API] Scrape full `snippet`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#2268]
Currently, we're only scraping part of the snippet, even though we can see more of it in the regular search. The information seems to be available in the HTML. One of our users requested this.

Most of the `snippet` hidden behind "SHOW MORE":
<img width="1197" alt="image" src="https://github.com/user-attachments/assets/30a8a1e8-dedf-4858-848b-e362f85c192f" />

What we scrape:
<img width="1402" alt="image" src="https://github.com/user-attachments/assets/47d26a93-eca0-416a-a599-2d695d33f0fa" />

Full `snippet` available:
<img width="1393" alt="image" src="https://github.com/user-attachments/assets/beb90a86-ea7a-4d59-b934-4a4cf4ec7ff8" />

Details about the feature, sample code, more screenshots, and other relevant information.

Public links: [Playground](https://serpapi.com/playground?engine=google_scholar&q=AI+Governance+and+Ethics+Framework+for+Sustainable+AI+and+Sustainability&hl=en)

Internal links: [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073474?view=List) | [Search Inspect](https://serpapi.com/searches/676e5770b20bd8a690a4d609/inspect)

**Comment by btaunt** [comment]
We now parse the entire `snippet` under `organic_results` (when available)

[Playground](https://serpapi.com/playground?engine=google_scholar&q=AI+Governance+and+Ethics+Framework+for+Sustainable+AI+and+Sustainability&hl=en&no_cache=true)
