### ISSUE TITLE
[Google Search API] Top Stories is being parsed as Answer Box for some tablet searches

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#227]
![top_stories](https://user-images.githubusercontent.com/73674035/179952919-ae19e2f1-82f8-4b7f-b246-a4046fb69b31.png)
[Inspect](https://serpapi.com/searches/62d7cc707690dc2922ec1e9f/inspect)
[Playground](https://serpapi.com/playground?q=mrbeast+videos&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=tablet&no_cache=true&newPara=stick+highlight+lr+async+as_qdr)

**Comment by aciddjus** [comment]
This should be resolved in: https://github.com/serpapi/SerpApi/pull/3108
Please reopen if I'm mistaken.
