### ISSUE TITLE
[Google Image Search API] Pagination Issue: Limited to First 100 Images Despite 'ijn' Parameter Adjustment

### ISSUE THREAD

**Issue by ELERKSOSY** [serpapi/public-roadmap#2271]
Hello,

I’m facing an issue with the Google Image Search API. Pagination isn’t working, and it’s limited to showing only the first page (the first 100 images). No matter what value I input, it doesn’t display more than 100 images.

I’ve tried setting the ijn parameter to 2 or 3, but nothing changes.

**Comment by hilmanski** [comment]
Hi @ELERKSOSY 

Thank you very much for your report. Can you please share the search IDs of those searches? You can find your searches from this page: https://serpapi.com/searches

**Comment by ELERKSOSY** [comment]
Hi @hilmanski 

Thank you so much for your prompt feedback! Here are some search IDs with the same issue:
676fec0c6320cfa76064a14b
67718a7ec941c98269601f11
67718a6ac3f02ce22e5fe8f3

Please advice!

**Comment by hilmanski** [comment]
Thank you very much for the search IDs. It looks like they behave correctly. Just to clarify the `ijn` parameter works like the `start` parameter where it decides which `page` it starts. The total results are always 100. But it'll show the first 100, the 100-200 results, the 200-300 results, and so on.

**Comment by ELERKSOSY** [comment]
Perfect, thanks a lot

**Comment by martin-serpapi** [comment]
You're very welcome @ELERKSOSY ! If you need help with anything else, just let us know.
