### ISSUE TITLE
[Location API] The API is not working correctly

### ISSUE THREAD

**Issue by hilmanski** [serpapi/public-roadmap#2272]
A user reported that the Location API downloads the whole file when we access it. It also causes an error when we try to use the location dropdown field on the playground. I can confirm this behavior.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073525?view=List)

**Comment by dsojevic** [comment]
@hilmanski, a fix for this has been now deployed and the issue has been resolved.

**Comment by hilmanski** [comment]
Thank you very much @dsojevic
