### ISSUE TITLE
[Google Search API] Inline People Also Search For Blocks are not parsed

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#231]
![ipasf](https://user-images.githubusercontent.com/73674035/180001585-5cae399a-24ad-4c11-be1c-f4154d7dfb0f.png)
[Inspect](https://serpapi.com/searches/62d7cc707690dc2922ec1e9f/inspect)
[Playground](https://serpapi.com/playground?q=mrbeast+videos&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=tablet&no_cache=true&newPara=stick+highlight+lr+async+as_qdr)

Also the documentation around this block is weak. Another addition to the examples would be good.
According to the text within the [documentation](https://serpapi.com/inline-people-also-search-for), we are referring to these blocks and the ones in the examples interchangeably.

Here's an example from the same inspect above which is similar to the visual example on the documentation:
![ipasf2](https://user-images.githubusercontent.com/73674035/180006038-92c9b1df-44b3-4e23-be5e-d5e8e2f80d4f.png)

Here's another example which is also problematic similar to the visual example in documentation:
![pasf2](https://user-images.githubusercontent.com/73674035/180005036-087132f8-c5d4-48ec-adca-91fb5c67a1ed.png)
[Inspect](https://serpapi.com/searches/62d7d18b382427e91f12ebc5/inspect)
[Playground](https://serpapi.com/playground?engine=google&gl=us&google_domain=google.com&hl=en&location=Austin%2C+Texas%2C+United+States&no_cache=true&num=100&q=Coffee)

**Comment by kagermanov27** [comment]
@hartator @aciddjus @ilyazub @ritu1337 How should the ambiguity in here resolved?

**Comment by ilyazub** [comment]
> Here's another example which is also problematic similar to the visual example in documentation:
> ![pasf2](https://user-images.githubusercontent.com/73674035/180005036-087132f8-c5d4-48ec-adca-91fb5c67a1ed.png)

[`inline_people_also_search_for`](https://serpapi.com/inline-people-also-search-for#api-examples-results-for-elon-musk) were [`related_search_boxes`](https://serpapi.com/related-searches#api-examples-related-search-box-for-top-keyword) previously. That's the reason of the confusion.

**Comment by kagermanov27** [comment]
> [`inline_people_also_search_for`](https://serpapi.com/inline-people-also-search-for#api-examples-results-for-elon-musk) were [`related_search_boxes`](https://serpapi.com/related-searches#api-examples-related-search-box-for-top-keyword) previously. That's the reason of the confusion.

@ilyazub What's the way forward for these kinds of results now?

**Comment by kagermanov27** [comment]
The ambiguity in direction has been resolved in https://github.com/serpapi/SerpApi/pull/3545. We now have a better idea of how to proceed.
