### ISSUE TITLE
[New API] Support Youtube Video Page Results API

### ISSUE THREAD

**Issue by 808arc** [serpapi/public-roadmap#233]
Add the option to scrape full description (or emails from description + description text) on YouTube videos 
(currently, API getting only short of description from the search results) 

Hello, dear team of SERPapi! 
Im working right now on a bot that will allow automating the process of collecting data from YouTube videos with YouTube Search for my art project. SERPapi actually let me code bot quickly and without stress, but I stuck on one point. 

  Ideally, my bot should generate such data as: 
 - channel name
 - URL
 - full description from videos (with emails people leave for collaboration requests). 

Now it's generating: the channel name, URL, and just short descriptions. 
  
Why I need full description? 
It's because in my music sphere, people always leave their own emails for collaboration requests under their videos. 
Example: https://www.youtube.com/watch?v=-CSAIBTwbtU&ab_channel=jay4prod:

![image](https://user-images.githubusercontent.com/78694043/180239368-0a23aba3-cd49-4a6a-a0d4-a332b0da1af2.png)

(You may see how creator of the channel text in the description "send loops to ****@gmail.com")

___

There are tons of videos with requests like this that I want to analyze but without, at least, full description it's looking tricky.

 For sure, you can just implement a feature that will collect emails from description (video, not channel) and It's going to be also great, but knowing full description will let bot user to analyze who text in description "send" and who text "don't send" 
 
 
  Thank you for your work!

**Comment by kagermanov27** [comment]
Digging into the HTML reveals that to perform @808arc 's requests we need a new API to scrape Youtube Video Pages.

**Comment by dimitryzub** [comment]
@aliayar Do you remember someone with the same API request?

**Comment by aliayar** [comment]
Yeah, I have had a few requests about scraping video pages. One user, for example, was interested in Related Videos section. 

But as far as I know, most people rather use official Youtube API.

**Comment by 808arc** [comment]
@aliayar @kagermanov27 @dimitryzub thank you for providing feedback! I kindly appreciate it!

**Comment by dimitryzub** [comment]
@808arc In case you still need a DIY solution while we're working on proper API, we wrote two blog posts:

1. In Python: https://serpapi.com/blog/scrape-youtube-video-page-with-python/
2. In JavaScript: https://serpapi.com/blog/web-scraping-youtube-video-page-with-nodejs/
