### ISSUE TITLE
[Documentation] Add Anchors to Headers 

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#239]
Right now, it's not possible to link to a specific part of the documentation. 

### Reasons

If we write an answer/blog post/video and want to leave a link to something specific from the docs, it will be handy for the user also as it won't be necessary to read through everything to find the right info.

### Example 

As an example from the [`requests`](https://requests.readthedocs.io/en/latest/user/quickstart/) Python library:

![image](https://user-images.githubusercontent.com/78694043/180376542-709d240f-2534-4ae0-803b-a8c9bcf1c3b3.png)

Labeling as a `freezer` for now but feel free to remove it.

**Comment by hartator** [comment]
If we do this, maybe let's have GitHub approach for Readme-s. Where header anchor links are hidden and automated, and show up only on hover:

<img width="613" alt="image" src="https://user-images.githubusercontent.com/307597/180576416-9c32a913-d570-4972-b283-0545b9775d65.png">

Ref: https://github.com/pry/pry#installation
