### ISSUE TITLE
[Walmart Product API] Request Gets Stuck If Store_id Present

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#241]
Walmart Product API does get stuck if the API call includes a store_id in the request:

[The Playground](https://serpapi.com/playground?engine=walmart_product&product_id=305981154&store_id=2649) | [The Inspect](https://serpapi.com/searches/62de5d613bea7b015ac5f99b/inspect)

<img width="949" alt="walmart_store_id" src="https://user-images.githubusercontent.com/64849049/180742010-37ee3755-2961-4aee-8aef-dd36e7e44bc2.png">

**Comment by tanys123** [comment]
Block by Recaptcha when `stores` query param is added. I guess it is the security mechanism for new Walmart site when it detect unrecognized param. Also current `store` param will not work anymore, seems to be only set in session.

**Comment by aliayar** [comment]
How about adding an ability to add your location in the initial request so that Walmart assigns the closest store? It can work more like Google Maps. Is it possible you think @tanys123?

**Comment by marm123** [comment]
It looks like the issue reappeared. Searches are once again stuck when there are both `store_id` and `product_id` present in the search parameters.

![image](https://user-images.githubusercontent.com/28161162/199711454-2d614388-4b7e-4efe-819d-9c13ddfd169d.png)

<a href="https://serpapi.com/searches/6363a014c90e0a9b24ed3f0e/inspect">Inspect</a>
<a href="https://serpapi.com/searches/63639e24aa6c959e6a555ef4/inspect">Inspect</a>

**Comment by ilyazub** [comment]
Seems like this issue is resolved.
