### ISSUE TITLE
[Google Search API] Different Designs for Answer Box not Scraped

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#242]
There is a new design for the Answer Box which is shown for certain questions and it is not being scraped by us.

[The Playground](https://serpapi.com/playground?q=when+was+lockheed+corporation+founded&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [The Inspect](https://serpapi.com/searches/62e12598979054137de6d31f/inspect)

<img width="960" alt="new_answer_box" src="https://user-images.githubusercontent.com/64849049/181239768-c9ec8d72-5d50-4b14-a757-82851ebbfe4f.png">

On the other hand, this one is scraped as a knowledge panel but it looks more like an answer box.

[The Playground](https://serpapi.com/playground?q=U.S.+president+in+2017&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [The Inspect](https://serpapi.com/searches/62e126db2bc7d82f4b89120c/inspect)

<img width="950" alt="answer_box_or_kn" src="https://user-images.githubusercontent.com/64849049/181240736-295f4832-38bb-4937-9174-3b5246e854ef.png">

The last example is also scraped as in Knowledge Panel but it has a clear border separating it from the knowledge panel:

[The Playground](https://serpapi.com/playground?q=Founder+of+CNN&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [The Inspect](https://serpapi.com/searches/62e127c329d177d0a6091b7d/inspect)

<img width="958" alt="new_answer_box2" src="https://user-images.githubusercontent.com/64849049/181241872-08f62bce-90a4-4854-af95-a6a77d74921a.png">

Let me know if the second and the third examples should have their own issue. I can open a separate issue.

**Comment by kagermanov27** [comment]
![image](https://user-images.githubusercontent.com/73674035/181458337-2fa9476f-3460-4825-8b5d-7c5aa365ed4f.png)

@aliayar 
The parsing seems correct to me. I had a similar doubt about a year ago. But investigating into the html shows same kind of structure with knowledge graph. For example: `kg:/...` part within the data-attrid can be found on many examples of knowledge graph.
 In its normal form you can see such boxes under the knowledge graph. But for some searches knowledge graph is expanding itself.
 
You may find a similar example in documentation as well:
![kg_expanded](https://user-images.githubusercontent.com/73674035/181460503-495da5d1-2d7c-4478-ae9d-d93058d37bf7.png)

**Comment by aliayar** [comment]
Thank you for the explanation @kagermanov27. 

Some users have hard time with finding the corresponding element in the JSON file as it's main key is `"president_of_the_united_states_2017"`

**Nonetheless, the first answer box is still not scraped by SerpApi.**

**Comment by dimitryzub** [comment]
@aliayar On my part, the first example you provided is being parsed by us. Interesting 👀

![image](https://user-images.githubusercontent.com/78694043/181679207-1e796344-5a8b-4eb6-beea-89ac5a34897a.png)

____

> Some users have hard time with finding the corresponding element in the JSON file.

I think this is why _Show JSON path_ option is available in the Playground:

![11221](https://user-images.githubusercontent.com/78694043/181679482-25b1bded-f8d7-499a-b3df-acb39d1a1d2d.gif)

**Comment by aliayar** [comment]
>I think this is why Show JSON path option is available in the Playground:

I think user meant with a list of search terms, it can be hard to know what is the key when you automate this process.

>On my part, the first example you provided is being parsed by us.

Now, I see it, too. 

I am closing this one.

**Comment by ofirpress** [comment]
Hi @dimitryzub and @aliayar. 

I am the user that initially reported these issues. Thanks for fixing the issue with the Lockheed question so quickly!!

I still believe the issue with the other 2 questions has not been solved. Let me explain-

I want to write a function in python:
`
def answer_using_google(question):
  ...
  ...
  return answer
`

When I have an 'answer' in 'answer_box' its very easy to write this function.

But if the answer is in 'presidents_of_the_united_states_2017' one time and in 'founders' the other time, then there is no automatic way to parse this. I'm not asking you to put these answers into answer_box, as I understand that these things that google returns here are not actually answer boxes. I'm just asking for an entry in the returned JSON that will tell me where the correct answer is. So for the presidents example it might be "answer_in": "presidents_of_the_united_states_2017" and then in the CNN founders question it might be- "answer_in":  'founders' 

Does that explain it better?

Thanks so much

**Comment by dimitryzub** [comment]
@ofirpress Thank you for your clarifications 🙂

> But if the answer is in 'presidents_of_the_united_states_2017' one time and in 'founders' the other time, then there is no automatic way to parse this.

You can do it when there's no knowledge graph on the right (which provides more keys) is to iterate through  `knowledge_graph` keys and then dynamically assigning an extracted key to `knowledge_graph.dynamic_key`:

```python
for key in results["knowledge_graph"]:
    for result in results["knowledge_graph"][key]:
        print(result["name"])
```

Full example:

```python
from serpapi import GoogleSearch

params = {
    "api_key": "...",
    "engine": "google",
    "q": "U.S. president in 2017",
    "gl": "us",
    "hl": "en",
    "location": "Austin, Texas, United States"
}

search = GoogleSearch(params)
results = search.get_dict()

for key in results["knowledge_graph"]:
    print(key) # president_of_the_united_states_2017
    for result in results["knowledge_graph"][key]:
        print(result["name"])
```

Outputs:

```lang-none
president_of_the_united_states_2017
Donald Trump
Barack Obama
```

However, this approach will not work when there's more than 1 `dict` key.

____

What if to use `if` statement? Since we know the name of keys, we can just check for their existence, for example:

```python
if "president_of_the_united_states_2017" in results["knowledge_graph"]:
        for result in results["knowledge_graph"]["president_of_the_united_states_2017"]:
            print(result["name"])

if "founders" in results["knowledge_graph"]:
    for result in results["knowledge_graph"]["founders"]:
        print(result["name"])
```

Full example:

```python
from serpapi import GoogleSearch
import json

for query in ["U.S. president in 2017", "Founder of CNN"]:
    params = {
        "api_key": "...",
        "engine": "google",
        "q": query,
        "google_domain": "google.com",
        "gl": "us",
        "hl": "en",
        "location": "Austin, Texas, United States"
    }
    
    search = GoogleSearch(params)
    results = search.get_dict()
    
    if "president_of_the_united_states_2017" in results["knowledge_graph"]:
        for result in results["knowledge_graph"]["president_of_the_united_states_2017"]:
            print(result["name"])

    if "founders" in results["knowledge_graph"]:
        for result in results["knowledge_graph"]["founders"]:
            print(result["name"])
```

Outputs:

```lang-none
Donald Trump
Barack Obama

Ted Turner
Reese Schonfeld
```

Let me know if there is anything else I can help you with 🌞

**Comment by ilyazub** [comment]
SerpApi successfully scrapes these answer boxes. Closing this issue as resolved.

![image](https://github.com/serpapi/public-roadmap/assets/282605/46da6c81-ac8a-492b-8a96-841ba998ef72)
(ref: https://serpapi.com/playground?q=when+was+lockheed+corporation+founded&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)

![image](https://github.com/serpapi/public-roadmap/assets/282605/4b44a628-1f39-4501-86c0-7c72709a0f18)
(https://serpapi.com/playground?q=U.S.+president+in+2017&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)

![image](https://github.com/serpapi/public-roadmap/assets/282605/3c9c88d1-5439-41a4-a29c-2bae70304bd7)
(ref: https://serpapi.com/playground?q=Founder+of+CNN&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en)
