### ISSUE TITLE
[Google Sports Results API] Missing `stadium` in `game_spotlight` & `game_spotlight.teams.score.total` returns wrong values 

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#244]
We have recently added a support to parse `games.stadium` data (#224). 

However, a [Wildan S. Nahar](https://twitter.com/wildan3105/status/1552856708686290945) reported on Twitter that `stadium` data is not being parsed in `game_spotlight`.

### `game_spotlight`

❌ `stadium` data is not present.

![image](https://user-images.githubusercontent.com/78694043/181686812-95f0e64f-0c08-471c-87b3-de2a713e8b72.png)

### `games` 

✔`stadium` data is present.

![image](https://user-images.githubusercontent.com/78694043/181686874-4b08deb9-74cc-45ae-9722-a7ef4ff878ff.png)

#### Playground links

Boston Red Sox example: [Playground](https://serpapi.com/playground?q=Boston+Red+Sox&gl=us&hl=en&engine=google&google_domain=google.com&newPara=stick+highlight+lr+async+as_qdr+safe+engine+google_domain+si+form+filter) | [Inspect](https://serpapi.com/searches/62e3608094fb03c970c2b509/inspect) 

Toronto Blue Jays example: [Playground](https://serpapi.com/playground?q=Toronto+Blue+Jays&gl=us&hl=en&engine=google&google_domain=google.com&newPara=stick+highlight+lr+async+as_qdr+safe+engine+google_domain+si+form+filter) | [Inspect](https://serpapi.com/searches/62e3698fd5b1c5d83cc5971d/inspect)
____

📝A side note: `sports_results.game_spotlight.teams.score.total` seems not to be correct:

![image](https://user-images.githubusercontent.com/78694043/181687220-7e0eecbe-0ea6-467b-89ac-7a111c7bc811.png)

**Comment by wildan3105** [comment]
subscribing this

**Comment by dimitryzub** [comment]
@tanys123 When you have time and if possible, could you please a look? ❤

**Comment by wildan3105** [comment]
hi, any updates on this? thanks!

**Comment by dimitryzub** [comment]
Hi, @wildan3105 ✨

This issue is still in progress. I would say it's more than 50% done. We'll update you once it's done 🙂

**Comment by dimitryzub** [comment]
@wildan3105 The issue has been resolved 🙂
