### ISSUE TITLE
[Google Search API] "product_result" ratings ratios not ordered correctly

### ISSUE THREAD

**Issue by jan-koz** [serpapi/public-roadmap#245]
This snippet shows the bug.  Raiting of this iPhone is 4.6 which is correct, however under "user_reviews" section it says that there are 78% "star 1" raitings which is obviously a bug...

 "product_result": {
    "title": "Apple iPhone 13",
    "reviews": 8500,
    **"rating": 4.6,**
    "pricing": [
      {
        "price": "$0.00 now",
        "extracted_price": 0.0,
        "finance_option": "+$33.33 for 24 mo",
        "thumbnail": "https://serpapi.com/searches/62e3e84a2ff4219fa63c517f/images/99f71c3310838d2efa526d7d62adc26f0444400e9c667f7589e2e60e22f660451b3168af76461644.png",
        "name": "T-MobileApple iPhone 13 - Pink - 128GB (with 24 monthly payments)Free delivery·$0.00 now+$33.33 for 24 mo",
        "description": "Apple iPhone 13 - Pink - 128GB (with 24 monthly payments)"
      },
      {
        "price": "$829.00",
        "extracted_price": 829.0,
        "thumbnail": "https://serpapi.com/searches/62e3e84a2ff4219fa63c517f/images/99f71c3310838d2efa526d7d62adc26fde5bcf38224313d122c1b5ce31d5d39ae6b8d406db973b07.png",
        "name": "Amazon.comApple iPhone 13 (128 GB, Green) [Locked] + Carrier SubscriptionFree delivery·$829.00",
        "description": "Apple iPhone 13 (128 GB, Green) [Locked] + Carrier Subscription"
      },
      {
        "price": "$0.00 now",
        "extracted_price": 0.0,
        "finance_option": "+$33.34 for 24 mo",
        "thumbnail": "https://serpapi.com/searches/62e3e84a2ff4219fa63c517f/images/99f71c3310838d2efa526d7d62adc26f630ca9d3926b4e3f6f0769856c9029f011e9b0eae0077f36.png",
        "name": "Best BuyApple - iPhone 13 5G 128GB - Green (T-Mobile) - 24 monthly installmentsFree delivery·$0.00 now+$33.34 for 24 mo",
        "description": "Apple - iPhone 13 5G 128GB - Green (T-Mobile) - 24 monthly installments"
      },
      {
        "price": "$0.00 now",
        "extracted_price": 0.0,
        "finance_option": "+$24.99 for 36 mo",
        "thumbnail": "https://serpapi.com/searches/62e3e84a2ff4219fa63c517f/images/99f71c3310838d2efa526d7d62adc26fc10135b72db072906981da47aecd631de44008c728cabcf6.png",
        "name": "VerizonApple iPhone 13 256 GB in Starlight with installmentFree delivery·$0.00 now+$24.99 for 36 mo",
        "description": "Apple iPhone 13 256 GB in Starlight with installment"
      },
      {
        "price": "$829.99",
        "extracted_price": 829.99,
        "thumbnail": "https://serpapi.com/searches/62e3e84a2ff4219fa63c517f/images/99f71c3310838d2efa526d7d62adc26fbe4d0f2e8573dc9e46b7819d5a3f36e2e1622770e4437f4f.png",
        "name": "Cricket WirelessApple iPhone 13 128GBGB Midnight - Cricket - PrepaidFree delivery·$829.99",
        "description": "Apple iPhone 13 128GBGB Midnight - Cricket - Prepaid"
      }
    ],
    "manufacturer": {
      "name": "apple.com",
      "link": "https://www.apple.com/shop/buy-iphone/iphone-13"
    },
    "description": "Our most advanced dual‐camera system ever. An even brighter Oled display. A lightning‐fast chip that leaves the competition behind. A huge leap in battery life. SIM-free",
    "features": {
      "screen_size": "6.1″",
      "release_date": "September 2021",
      "display_resolution": "2532 x 1170",
      "storage_capacity": "128 GB, 256 GB, 512 GB"
    },
    "thumbnails": [
      "https://serpapi.com/searches/62e3e84a2ff4219fa63c517f/images/99f71c3310838d2ee4a6a5f09175fafb8cb27dd210a479662ceaa8fbec08caf5.webp",
      "https://serpapi.com/searches/62e3e84a2ff4219fa63c517f/images/99f71c3310838d2ee4a6a5f09175fafb8cb27dd210a47966fea64c0e739f61bc.webp",
      "https://serpapi.com/searches/62e3e84a2ff4219fa63c517f/images/99f71c3310838d2ee4a6a5f09175fafb8cb27dd210a47966b446abe060486a46.webp",
      "https://serpapi.com/searches/62e3e84a2ff4219fa63c517f/images/99f71c3310838d2ee4a6a5f09175fafb8cb27dd210a4796664120b3c4c2f15a0.webp",
      "https://serpapi.com/searches/62e3e84a2ff4219fa63c517f/images/99f71c3310838d2ee4a6a5f09175fafb8cb27dd210a47966589d7653005952cf.webp",
      "https://serpapi.com/searches/62e3e84a2ff4219fa63c517f/images/99f71c3310838d2ee4a6a5f09175fafb8cb27dd210a47966481d62bfcb8b7e01.webp",
      "https://serpapi.com/searches/62e3e84a2ff4219fa63c517f/images/99f71c3310838d2ee4a6a5f09175fafb8cb27dd210a47966ffc2da3b491f9e8f.webp",
      "https://serpapi.com/searches/62e3e84a2ff4219fa63c517f/images/99f71c3310838d2ee4a6a5f09175fafb8cb27dd210a479669b1835c51ba7be4c.webp"
    ],
    "reviews_results": {
      "user_reviews": {
        **"ratings": [
          {
            "stars": 1,
            "amount": "78%"
          },
          {
            "stars": 2,
            "amount": "13%"
          },
          {
            "stars": 3,
            "amount": "4%"
          },
          {
            "stars": 4,
            "amount": "3%"
          },
          {
            "stars": 5,
            "amount": "5%"
          }**
        ],
...

**Comment by dimitryzub** [comment]
Hi @jan-koz 👋 Thank you for reporting this! 

Could you please send us the search ID where you had this problem so we can inspect this bug and try to reproduce it? 

To find a search ID: 

![image](https://user-images.githubusercontent.com/78694043/182083616-3d291dca-e8ea-416e-8a0d-91c5807926a6.png)

Thank you 🌼

**Comment by jan-koz** [comment]
SearchID = 62e3ec7834ff951f9551c68c.
Although I encountered this problem in every search I have made, so I could place here anything ;) (eg. 62e3e84a2ff4219fa63c517f also has this problem...)

**Comment by dimitryzub** [comment]
@jan-koz Confirming this. The results is flipped:

|Expected result|Actual result|
|-|-|
|![image](https://user-images.githubusercontent.com/78694043/182115313-95e5dcc8-fe75-4eab-bf75-d40f26838554.png)|![image](https://user-images.githubusercontent.com/78694043/182114448-43b29c7c-05d0-4bbd-9724-8f39743953b7.png)|


![image](https://user-images.githubusercontent.com/78694043/182115457-e0f2125c-ffb7-4135-9069-5bedaf606cb3.png)


Same for Pixel 6 search query: [Playground link](https://serpapi.com/playground?q=pixel+6&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&engine=google&google_domain=google.com&newPara=stick+highlight+lr+async+as_qdr+safe+engine+google_domain+si+form+filter)

@kagermanov27, @tanys123, @andypple83 can you have a look? 👀

**Comment by jan-koz** [comment]
Could you please let me know whenever you fix the issue. It's quite crucial for me and I don't want to do a workaround for it

**Comment by dimitryzub** [comment]
@jan-koz Of course 💫

@tanys123 🧡

**Comment by kagermanov27** [comment]
@tanys123 Sorry for not assigning myself on time. I am close to a solution now.

**Comment by kagermanov27** [comment]
@jan-koz I have just updated the fix with the reviews I have taken. I expect it to be approved in less than a week.

**Comment by jan-koz** [comment]
Issue has not been solved. I don't know why You have closed it...

**Comment by kagermanov27** [comment]
@jan-koz Have you tried to do a `no_cache=true` search? I wasn't able to detect any problems.

**Comment by jan-koz** [comment]
I have just tried that and unfortunately it didn't work. This is my search id: 6304c27fa1b423e57632c68c , 6304c1fc2f542ed2962ceb1a. I don't know why no_cache=true is not shown in query params

**Comment by kagermanov27** [comment]
@jan-koz This is a separate issue that must've occurred while we are working on this. I have opened a separate issue in https://github.com/serpapi/public-roadmap/issues/271 and assigned myself. Working on it right away. Thank you for all the information.
