### ISSUE TITLE
[New API] Yandex Reverse Image Search

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#246]
We can add Yandex Reverse Image Search as a new API.

Search page:

<img width="957" alt="yandexreverse" src="https://user-images.githubusercontent.com/64849049/129537787-139facd7-8183-4e5c-b161-eb68374931e0.png">

Results page:

<img width="948" alt="yandexreverseresults" src="https://user-images.githubusercontent.com/64849049/129537937-c3332ce0-ce29-4341-a0b8-5274b29f2b4e.png">

**Comment by aliayar** [comment]
2 votes so far.

**Comment by dimitryzub** [comment]
@aliayar There are also SO questions about this topic (not sure if you're included this to votes count): https://stackoverflow.com/questions/73189292/how-to-use-search-by-imageurl-using-yandex-rest-api

**Comment by aliayar** [comment]
@dimitryzub I only counted those who asked directly to support about it.

**Comment by patugosavi** [comment]
Hello serpapi team,

I am mobile application developer. I am create search engine app. I have search all platform but best response show on yandex platform.  But when I am checking reverse search image on google. Showing wrong result on rotated image. And yandex show correct result. I am trying code of exif rotation but this is most of the apply on 90,180,270,360 and 0 degree. But any user can uploaded image in wrong angle then google show wrong result but yandex show correct result. Google also show problem on .tiff files. So please this is my humble request of accessing yandex reverse search imageurl api in serpapi platform.

**Comment by aciddjus** [comment]
We have added support for [Yandex Reverse Image](https://serpapi.com/yandex-reverse-image-api). You can now use [url](https://serpapi.com/yandex-images-api#api-parameters-yandex-reverse-image-parameters-url) parameter in our [Yandex Images API](https://serpapi.com/yandex-images-api) to do a reverse search.
