### ISSUE TITLE
[Google Search API] Desktop Results Returned Just After The Same Search Performed in Desktop then Mobile

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#251]
Google Search API returns the desktop layout and results when you first request a search in Desktop then change only the device param to request the same search with a mobile option. Not sure if the cache mechanism is not working properly in certain times.

The examples below show a Desktop result while device parameter is mobile:

[The Inspect](https://serpapi.com/searches/62ea3d00d3aba2fd56b407a6/inspect) | [The Inspect 2](https://serpapi.com/searches/62ea3d002bc7d8a1c64af2fc/inspect) | [The Inspect 3](https://serpapi.com/searches/62ea3d003e86acac7fad7d0b/inspect) |

<img width="714" alt="mobile_desktop" src="https://user-images.githubusercontent.com/64849049/182609348-346a9433-a225-4870-b1df-bc24850d8262.png">

I have tried to reproduce this on Playground and my IDE but I couldn't reproduce the bug in any way. Due to that, no Playground links.

IDE Efforts: [62ea696eaf630449f56780e3](https://serpapi.com/searches/62ea696eaf630449f56780e3/inspect) and [62ea697eaf63044a88f5bf9c](https://serpapi.com/searches/62ea697eaf63044a88f5bf9c/inspect)

The Playground Efforts: [62ea6d629c84ac5b90b743f1](https://serpapi.com/searches/62ea6d629c84ac5b90b743f1/inspect) and [62ea6d75c573d5ca534d4961](https://serpapi.com/searches/62ea6d75c573d5ca534d4961/inspect)

**Comment by aliayar** [comment]
When this bug happens, it also can't parse the organic results and return.

[Example 1](https://serpapi.com/searches/62ebbafbe0ded4b3b387acf3/inspect) | [Example 2](https://serpapi.com/searches/62ebbafb2ff421491223e0e7/inspect) | [Example 3](https://serpapi.com/searches/62ebbafb1988e5179f3d3290/inspect)

**Comment by ritu1337** [comment]
Fixed.
