### ISSUE TITLE
[Google Search API] `cached_page_link` started missing in organic results 

### ISSUE THREAD

**Issue by hartator** [serpapi/public-roadmap#256]
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/307597/183753985-6521f31c-4ed7-49d1-bc19-4b4a83027835.png">

`cached_page_link` started missing in organic results.

[Playground](https://serpapi.com/playground?q=Tea&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&engine=google&google_domain=google.com&newPara=stick+highlight+lr+async+as_qdr+safe+engine+google_domain+si+form) - [Inspect](https://serpapi.com/searches/62f2c24a9f55b354364fc3f8/inspect) - [Intercom](https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000028045)

**Comment by pbdrago** [comment]
Hi, has there been any progress made on this issue?

**Comment by ritu1337** [comment]
Hey @pbdrago,

The issue should be fixed now.
