### ISSUE TITLE
[Google Search API] Add "More about this page" link to API results

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#264]
Currently we are not extracting **More about this page** link from **About this result** page.

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/28161162/184873406-a20fb45f-6eba-4899-a3c7-015180c4f235.png">
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/28161162/184874065-4ca74642-9823-4aa3-b946-e4bcc56b12e7.png">

<a href="https://serpapi.com/playground?q=wordlift.io&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true">Playground</a>
<a href="https://www.google.com/search?q=wordlift.io&oq=wordlift.io&aqs=chrome..69i58j69i57j69i60l3.5057j0j9&sourceid=chrome&ie=UTF-8">Google Search Result</a>
<a href="https://www.google.com/search?q=About+https://wordlift.io/&tbm=ilp&ilps=ADNMCi2_wdaiZo26YhDduUrO2Vc0NXkDCg&ved=0CAUQv5AHahcKEwjI1LqU3835AhUAAAAAHQAAAAAQAg&biw=1440&bih=711&dpr=2">Google Search _More about this page_ Link</a>

**Comment by aciddjus** [comment]
Thanks, @marm123. Please include a playground and inspect links when opening an issue about a parser bug.

**Comment by marm123** [comment]
Thank you @aciddjus. I've added Playground, Google Search Result and Link to _More about this page_ that is to be extracted. Sorry for not including it in the first place.

**Comment by aciddjus** [comment]
> Thank you @aciddjus. I've added Playground, Google Search Result and Link to _More about this page_ that is to be extracted. Sorry for not including it in the first place.

No problem. Thanks for the update. 👍

**Comment by ritu1337** [comment]
Should be fixed now 👍
