### ISSUE TITLE
[Google Search API Mobile] Knowledge Graph Tabs to be Scraped

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#266]
Google added a several tabs to the mobile knowledge graph.

[The Playground](https://serpapi.com/playground?q=beskidzka+polana+grill&location=Warsaw%2C+Masovian+Voivodeship%2C+Poland&google_domain=google.pl&gl=pl&hl=pl&device=mobile&no_cache=true) | [The Inspect](https://serpapi.com/searches/62fc93bff21801e8a5cc8fed/inspect)

The Screenshot 1:

<img width="949" alt="mobile_knowledge2" src="https://user-images.githubusercontent.com/64849049/185146254-45d21bd4-0c8b-410c-8290-74baf67b688a.png">

The Screenshot 2:

![mobile_knowledge](https://user-images.githubusercontent.com/64849049/185146296-584af777-ca7e-446e-b946-5a2f9607bcf2.png)

**Comment by ilyazub** [comment]
Related to https://github.com/serpapi/public-roadmap/issues/497
