### ISSUE TITLE
[Google Knowledge Graph-Bug] Empty `sports_results` are served when there is another Knowledge Graph is present

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#267]
When Formula results appear in the search, there's also a `sport_results` key with the formula title. In this case: _Density_.

[Playground](https://serpapi.com/playground?q=what+is+the+formula+for+density&gl=us&hl=en&engine=google&google_domain=google.com&newPara=stick+highlight+lr+async+as_qdr+safe+engine+google_domain+si+form+filter) | [Inspect](https://serpapi.com/searches/62ff2294d737d704be7e62ea/inspect)

![image](https://user-images.githubusercontent.com/78694043/185551360-a4829215-418a-4139-85f2-552e643da525.png)

![image](https://user-images.githubusercontent.com/78694043/185551231-0c61b3eb-53cf-4993-b778-43990c7728d1.png)

@kagermanov27 could you confirm when you have time?

**Comment by kagermanov27** [comment]
Yes, this is something I forgot to open @dimitryzub . Thank you. But the naming isn't proper. It's empty `sports_results` that are popping up when various knowledge graph results are present.

**Comment by dimitryzub** [comment]
@kagermanov27 Thank you for renaming proprely 🧡
