### ISSUE TITLE
[Google Maps API] Add support for Google Maps directions

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#272]
We don't currently support directions for Google Maps.

It might be good to support various transportation options, departure address, arrival address, times, and perhaps additional stops addresses as API parameters. And our API can then return the different travel options and their details as JSON results.

Couple of suggestions:

![image](https://user-images.githubusercontent.com/28161162/186164150-6bfd757c-4290-4998-8342-9c570ddc239f.png)

<a href="https://serpapi.com/playground?engine=google_maps&q=From+Frankfurt+to+Berlin&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&type=search">Playground</a> | <a href="https://serpapi.com/searches/6304b4c4fdca3ee650bae393/inspect">Inspect</a>

**Comment by ilyazub** [comment]
As a workaround, the regular Google Search can be used. [Playground link](https://serpapi.com/playground?q=directions+from+frankfurt+to+berlin).

![image](https://user-images.githubusercontent.com/282605/195516792-807bde84-f63d-4893-b442-2bc606645316.png)

**Comment by aliayar** [comment]
[Another user](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040703?view=List) who asks for this feature.

**Comment by marm123** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000050081?view=List)

**Comment by marm123** [comment]
A customer asked if we have an API like this one.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000051340?view=List)
