### ISSUE TITLE
[Google Search API Mobile] Top Organic Result not Parsed and Returned in Response

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#273]
The **first organic result**[1] and **subsequent accordion menus**[2] is not parsed and returned in the SerpApi JSON response for certain search queries.

<img width="954" alt="google_mobile_branding" src="https://user-images.githubusercontent.com/64849049/186445447-7ff569c0-d2e8-4db2-a0a7-ea88ecba62fc.png">

[The Playground](https://serpapi.com/playground?q=branding&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&num=100&device=mobile) | [The Inspect](https://serpapi.com/searches/63062f8e1baebbda2186a49c/inspect)

**Comment by aciddjus** [comment]
It looks like this should be a part of a `knowledge_graph`, not `organic_results`

Here it is on desktop:

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/6929257/186452458-f58fc51a-2aef-4c36-8a08-3f281ebb669b.png">

**Comment by kagermanov27** [comment]
>It looks like this should be a part of a knowledge_graph, not organic_results

And definitely not sports results. Also related to:
https://github.com/serpapi/public-roadmap/issues/267

**Comment by aciddjus** [comment]
I'll make a quick fix to only address `organic_results` since the issue is urgent and we can fix `knowledge_graph` later.

<img width="831" alt="image" src="https://user-images.githubusercontent.com/6929257/186472231-83937b84-b6a3-4bae-a14c-abe6840b183a.png">
