### ISSUE TITLE
[Yelp Search API] Support Distinction between Sponsored Results and Ads Results

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#288]
![yelp](https://user-images.githubusercontent.com/73674035/187153786-0534720c-d516-454d-b221-2c4a098b6dbb.png)
[Inspect](https://serpapi.com/searches/630c6887660dbd2194f9a4db/inspect)
[Playground](https://serpapi.com/playground?engine=yelp&find_desc=Coffee&find_loc=Austin%2C+TX%2C+United+States&no_cache=true)

**Comment by aciddjus** [comment]
I couldn't find any other type of ad except `Sponsored`. Feel free to re-open if I missed it.

![image](https://github.com/serpapi/public-roadmap/assets/6929257/e55e35bf-93ff-4609-9b21-ce1bf059b4f3)

-------------

[Playground](https://serpapi.com/playground?engine=yelp&find_desc=Coffee&find_loc=Austin%2C+TX%2C+United+States&no_cache=true)
