### ISSUE TITLE
[Yahoo Search API] Add `knowledge_graph` results

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#296]
![yahoo_1](https://user-images.githubusercontent.com/73674035/187537833-2902dcb6-b5e6-4f73-8f58-a593b9556158.png)
[Playground](https://serpapi.com/playground?engine=yahoo&p=Coffee&pz=100&device=mobile&no_cache=true)
[Inspect](https://serpapi.com/searches/6347ed0de815af6ec83895d6/inspect)

Edit: I investigated and found that these were not `organic_results`

**Comment by ilyazub** [comment]
Also, there are no `total_results` in SerpApi JSON response.

![image](https://user-images.githubusercontent.com/282605/195526613-170ec49d-bf36-4f46-b2d9-3951d9ef46f1.png)

**Comment by aciddjus** [comment]
This issue has been resolved.

<img width="1519" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/28513bb0-d867-4864-ae19-91eff1eccc25">

---------------

[Playground](https://serpapi.com/playground?engine=yahoo&p=Coffee&device=mobile&no_cache=true)

Resolved in: https://github.com/serpapi/SerpApi/pull/3824
