### ISSUE TITLE
[Google Trends API] Data is shifted one day

### ISSUE THREAD

**Issue by hartator** [serpapi/public-roadmap#298]
On the "Past 30 days" timescale, data is shifted one day.

![image](https://user-images.githubusercontent.com/307597/187563575-56e455d2-dd4b-4774-a1fe-40feb7fbc6af.png)

[Search inspect](https://serpapi.com/searches/630e9faa29d177c558e941c6/inspect) - [Google Trends page](https://trends.google.com/trends/explore?date=today%201-m&geo=SG&q=amo) - [SerpApi playground reproduction](https://serpapi.com/playground?engine=google_trends&q=Coffee&geo=SG&date=today+1-m) - [Intercom original thread](https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/mentions/conversations/102910000029693)

**Comment by tanys123** [comment]
The actual issue is Google Trends show different data by which location the request is from.
https://github.com/serpapi/public-roadmap/issues/300#issuecomment-1236837924

**Comment by hartator** [comment]
> The actual issue is Google Trends show different data by which location the request is from. [#300 (comment)](https://github.com/serpapi/public-roadmap/issues/300#issuecomment-1236837924)

These two issues are actually separated. 

#300 is about the Google Trends data being different on different locations. This can be for various reasons outside of our control like you pointed. Sampling is indeed the most probable. 👍

#298 is just bug in our parser. The JSON numbers do match the HTML numbers. However, the extracted dates in the JSON doesn't match the corresponding pairings in the graph. JSON dates are consistently shifted one day in the future.
