### ISSUE TITLE
[Google Map Reviews API] Searches return corrupt results

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#299]
Some searches return corrupt results instead of regular pages with reviews or blank pages with no reviews.

Search returning corrupt results:
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/28161162/187625051-fb271f8e-0608-41da-ae7a-8aa4b528ea4e.png">

Search returning correct results for the same parameters:
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/28161162/187625376-203957b8-f4b8-4eab-b0dd-9c72e36301da.png">

Some inspect links with corrupt and correct results for the same parameters:
<a href="https://serpapi.com/searches/630e3377cca014b65e0abcd1/inspect">Inspect - corrupt</a> | <a href="https://serpapi.com/searches/630f1323c640d27bc72439dc/inspect">Inspect - correct</a>
<a href="https://serpapi.com/searches/630e6078d036a7f5acbcf527/inspect">Inspect - corrupt</a> | <a href="https://serpapi.com/searches/630f144d4d443da8be794916/inspect">Inspect - correct</a>
<a href="https://serpapi.com/searches/630d2980fe41d0b5d037ab26/inspect">Inspect - corrupt</a> | <a href="https://serpapi.com/searches/630f14c53e86acd81ba07bc0/inspect">Inspect - correct</a>

**Comment by ilyazub** [comment]
Is this related to the location parameters like `gl` and `hl`?

**Comment by marm123** [comment]
I'm sorry, I missed your question @ilyazub. I'm not sure if it's connected. Everything seems to work fine for most of the queries, but at one point the results users are getting are corrupt. I'm not sure if this might be connected to the specific next_page_token - data_id pair or something else. We have similar problem recently with one of our users:


<img width="1124" alt="image" src="https://user-images.githubusercontent.com/28161162/201835599-d5ae0df6-11d8-4745-b7e8-74d5ad9857aa.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/28161162/201835303-6b34db49-8af6-4a2c-a9a4-05bcb35ef265.png">


<a href="https://serpapi.com/searches/6372723d3944b08e5d3d6418/inspect">Inspect - corrupt page</a> | <a href="https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x480f4a766e82f6f7%3A0xd2d432e1ac590edf&hl=en&next_page_token=CAESB0VnTUl5a2c%3D">Playground - corrupt page</a>

**Comment by kagermanov27** [comment]
Closing this as it is probably resolved by itself or a tangent PR. Both of the playground examples work fine now.
