### ISSUE TITLE
[Google Events API] Allow users to filter results by the time of events using `htichips` parameter

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#305]
Currently, we are only displaying overall results for Google Events. We can use the htichips parameter to add the ability to look for Google Events for Today, Tomorrow, This Week, etc.

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/28161162/188415598-378623a7-f37f-409d-ad77-1c752bbea667.png">

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/28161162/188416451-64dec7a5-b278-4014-a213-b44419a640e7.png">

**Comment by scriptify** [comment]
This would be very useful! 🔥

**Comment by dimitryzub** [comment]
@scriptify We've just added a `htichips` parameter support:

![image](https://user-images.githubusercontent.com/78694043/195269059-c76ee435-03a6-4412-a076-c221f92528cd.png)

Let us know if anything works not as expected 👍

**Comment by scriptify** [comment]
Thanks a lot ♥ have a great day!
