### ISSUE TITLE
[Google Search API] `related_searches` not returned on Mobile version

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#309]
There is no `related_searches` key returned while scraping Google Search on mobile.

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/28161162/188858671-744f6eea-7215-4d86-93eb-58ec3397973c.png">

<a href="https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&newPara=chips+highlight+stick+lr+async+as_qdr">Playground</a> | <a href="https://serpapi.com/searches/631872ee437af26d2f8a024a/inspect">Inspect</a>

**Comment by marm123** [comment]
Opening this thread as the issue back once again:

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/28161162/218051263-92803e82-aef6-4ebf-98b1-1f0c17eb6236.png">

[Playground](https://serpapi.com/playground?q=Coffee&location=Greater+London%2C+England%2C+United+Kingdom&google_domain=google.co.uk&gl=uk&hl=en&device=mobile&newPara=chips+highlight+stick+lr+as_qdr) | [Inspect](https://serpapi.com/searches/63e609ea3bea7be13c655801/inspect)

**Comment by marm123** [comment]
"People also search for" us also missing from the JSON response. It's a bit confusing with the naming, as Illia pointed out. I'm unsure if this is extracted in the same block, but if not, I can create a separate issue. LMK

![image](https://user-images.githubusercontent.com/28161162/218055438-e25558d5-626b-41a4-9583-5e11d2b6f11c.png)

[Playground](https://serpapi.com/playground?q=Apple&location=Greater+London%2C+England%2C+United+Kingdom&google_domain=google.co.uk&gl=uk&hl=en&device=mobile&newPara=chips+highlight+stick+lr+as_qdr) | [Inspect](https://serpapi.com/searches/63e60b52fa86759d92681432/inspect)

**Comment by schaferyan** [comment]
I'm reopening this thread as a customer just reported having this issue again. I was unable to replicate it in our Playground, however.

![image](https://user-images.githubusercontent.com/30915304/219110685-364e0373-5132-4df5-b98b-2d54644bb027.png)
(search inspector)[https://serpapi.com/searches/63ed153ef2180110e929d8b5/inspect]

**Comment by aciddjus** [comment]
> I'm reopening this thread as a customer just reported having this issue again. I was unable to replicate it in our Playground, however. Also it may be subtly different - feel free to move to a new thread if necessary. It's hard for me to see what's going on without being able to read Japanese, but in the example in the `search_inspector` it looks like we are only scraping `query` and `link` from "People also Ask" and not any of the other keys we usually parse..
> 
> ![image](https://user-images.githubusercontent.com/30915304/219110685-364e0373-5132-4df5-b98b-2d54644bb027.png)
> 
> [search inspector](https://serpapi.com/searches/63ed153ef2180110e929d8b5/inspect)

Not 100% sure I understand the problem. There is nothing here except `query` and `link`, and we are extracting it.

<img width="1466" alt="image" src="https://user-images.githubusercontent.com/6929257/220080166-864e7d33-f5a4-4f40-b65e-7d27f1374cbd.png">

**Comment by marm123** [comment]
@aciddjus I believe the confusion comes from language differences in API results. The issue customer has is that the "People also ask" is extracted together with related searches, while in fact, it's not "People also ask" but "People also search for". Below is the conversation with a customer about their issue:

[Intercom conversation](https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000037120)

I'm closing this one as the issue is more if we should extract "People also search for" together with "Related Searches" in the same `related_searches` block of the JSON response or not, and this issue is about something else.
