### ISSUE TITLE
[New API] Google Trends Daily Search Trends

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#319]
Example URL: https://trends.google.com/trends/trendingsearches/daily?geo=US

![image](https://user-images.githubusercontent.com/78694043/189308929-02dad1b4-8afd-479a-a057-56f67c062ec7.png)

____

### The below section is to track the demand for this website.

User request(s):
- ...

Stackoverflow questions:

- ...

Other forums/websites:

- ...

Intercom threads:
- ...

**Comment by aciddjus** [comment]
This issue has been resolved.

<img width="1671" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/1edd7117-21f9-4f90-923d-1cebeea5ff6e">

-----------------

[Playground](https://serpapi.com/playground?engine=google_trends_trending_now&frequency=daily&geo=US&hl=en)

Resolved in: https://github.com/serpapi/SerpApi/pull/4031
