### ISSUE TITLE
[New API] Brave Search

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#322]
Example URL: https://search.brave.com/search?q=minecraft&source=web

![image](https://user-images.githubusercontent.com/78694043/189313491-a6ea2d7d-8086-4f3f-8fb1-fcfdeefb163b.png)

____

### The below section is to track the demand for this website.

User request(s):
- ...

Stackoverflow questions:

- ...

Other forums/websites:

- ...

Intercom threads:
- ...

**Comment by hilmanski** [comment]
Duplicate of https://github.com/serpapi/public-roadmap/issues/74
