### ISSUE TITLE
[Bing News API] No Results When Bing News Topics Used as a Search Query

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#335]
We've received a mention from our user that Bings News not returning any results.

## Problem

I've noticed that such behavior appears when using Bing News topics as keywords (screenshot below), our parser will returns `"error":"Bing News hasn't returned any results for this query."` 

There're a few keywords that have such behavior (each link leads to Inspect page):

- [top stories](https://serpapi.com/searches/6322e58e8e02e4b4aa34eea8/inspect)
- [sports](https://serpapi.com/searches/6322e88c351764bde231ec7a/inspect)
- [local](https://serpapi.com/searches/6322e9843c3fb2a10f7ee36f/inspect)
- [world](https://serpapi.com/searches/6322e9f24055aa271cb526bf/inspect)
- [entertainment](https://serpapi.com/searches/6322e8d84d443da49b3ee8ec/inspect)
- [science](https://serpapi.com/searches/6322e8bf2c6878c06e57a1fb/inspect)
- [technology](https://serpapi.com/searches/6322e8c91e803f53dd80579b/inspect)
- [politics](https://serpapi.com/searches/6322eaae2c0844efd6a10d5b/inspect)
- [business](https://serpapi.com/searches/6322eaf32ff421da6f6fda03/inspect)
- most likely something more..

Those examples are the topics of Bing News:

![image](https://user-images.githubusercontent.com/78694043/190363646-3bcf494e-dee8-4c7f-b0d7-1fedcaa61514.png)

## More Examples

![image](https://user-images.githubusercontent.com/78694043/190362108-51f1a209-cef2-49c5-9897-7e03f8d5f541.png)

[Playground](https://serpapi.com/playground?engine=bing_news&q=Local&cc=US) | [Inspect](https://serpapi.com/searches/6322e9843c3fb2a10f7ee36f/inspect) 

![image](https://user-images.githubusercontent.com/78694043/190365027-e69b3c13-29e5-4de1-a43a-57310dd6d112.png)

[Playground](https://serpapi.com/playground?engine=bing_news&q=world&cc=US) | [Inspect](https://serpapi.com/searches/6322e9f24055aa271cb526bf/inspect)

## Additional note

We're not extracting/showing in the playground "More news" section:

![image](https://user-images.githubusercontent.com/78694043/190364424-9b7eeb9c-1256-4a81-be42-58b2fa437969.png)

@andypple83 @aciddjus could you guys have a look when possible? 💛

**Comment by Krugloff** [comment]
The additional layout has now been parsed.

<img width="1448" alt="image" src="https://github.com/user-attachments/assets/7b9caa46-a77f-49db-860c-6694c768f9b0">
<img width="1450" alt="image" src="https://github.com/user-attachments/assets/6a023477-dffd-4c3c-9a83-48fb44495c21">
