### ISSUE TITLE
[Google Search API] Fix `answer_box` for Google Flights

### ISSUE THREAD

**Issue by timunderwood** [serpapi/public-roadmap#340]
API used to return the data for Google Flights as an answer_box, but has recently stopped coming through in the response. 

<img width="724" alt="Screen Shot 2022-09-15 at 5 38 28 AM" src="https://user-images.githubusercontent.com/11050123/190406006-dcd70ae0-600f-4c46-8c6f-9f2f586c378a.png">

**Comment by kagermanov27** [comment]
[Playground Link](https://serpapi.com/playground?q=Los+angeles+to+london+flights&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips)
[Inspect Link](https://serpapi.com/searches/632320ed2e7d6bf220c7e84a/inspect)
