### ISSUE TITLE
[Google Search API] Ads are not returned in Google Search

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#346]
We are receiving multiple reports that ads are not returned in our search results.

Here are some examples of what is returned versus what should be returned:

**1 SerpApi**

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/28161162/192464245-3ec089d3-c2a5-4ba5-aa91-92ec733c8142.png">

**2 Connection with Proxy**

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/28161162/192464149-7260f677-9eb9-4218-8157-bc05d9626a41.png">

**3 SerpApi**

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/28161162/192464379-73fc3677-b683-4ab4-afe9-774a50aeee08.png">

**4 Connection with Proxy**

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/28161162/192464479-249dea17-c9de-4de5-b573-19269af3262e.png">

<a href="https://serpapi.com/searches/6331b9190f9866c2da685c05/inspect">Weddings Warrington Inspect</a> | <a href="https://serpapi.com/searches/6331b919f26ac6be48b9ad2a/inspect">Weddings Portsmouth Inspect</a> | <a href="https://serpapi.com/searches/6331b91958762b2711d0f7b0/inspect">Weddings Nottingham Inspect</a>

**Comment by marm123** [comment]
Interestingly enough, using uule parameter helped with one of those searches. Not sure if this is a coincidence or a solution though.

<a href="https://serpapi.com/searches/6336d2209c84ac65cf70fcf4/inspect">Inspect - weddings warrington with ads</a>

**Comment by marm123** [comment]
We have another user reporting this issue.

<a href="https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000035637">Intercom conversation</a>

**Comment by hartator** [comment]
@marm123 Unfortunately, we can't guarantee Ads as part of the search results.

Google tries to display ads only for humans, and at the same time we can't guess which search should have ads. So, we can't automatically retry and, consequently, we can't support officially Ads.

The best you can offer is to refund search credits for these customers if they believe these searches should have ads.

**Comment by marm123** [comment]
Thank you, @hartator 👍

Do you think we should add a disclaimer for our Ad Results documentation pages stating that the results might not reflect what's presented by Google via regular search?

**Comment by ilyazub** [comment]
> Do you think we should add a disclaimer for our Ad Results documentation pages stating that the results might not reflect what's presented by Google via regular search?

[This FAQ answer](https://serpapi.com/faq/general/why-does-the-results-page-i-got-with-serpapi-look-different-than-when-i-manually-do-the-search-myself) can be also adjusted.

**Comment by hartator** [comment]
> Do you think we should add a disclaimer for our Ad Results documentation pages stating that the results might not reflect what's presented by Google via regular search?

> [This FAQ answer](https://serpapi.com/faq/general/why-does-the-results-page-i-got-with-serpapi-look-different-than-when-i-manually-do-the-search-myself) can be also adjusted.

Yes, that will be good to do both. 👍

**Comment by hilmanski** [comment]
Related to https://github.com/serpapi/SerpApi/issues/2336
