### ISSUE TITLE
[Walmart Product API] API calls doesn't return any response

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#349]
It looks like Walmart Product API is not working. Responses are not returned for most of the API calls.

<img width="660" alt="image" src="https://user-images.githubusercontent.com/28161162/193518834-a1303cf0-1ed7-4b77-8bb0-a1c9b71ef28b.png">

<a href="https://serpapi.com/playground?engine=walmart_product&product_id=520468661">Playground</a> | <a href="https://serpapi.com/searches/633a9d9aeb31eb391417d802/inspect">Inspect</a>
<a href="https://serpapi.com/playground?engine=walmart_product&product_id=1UMF2SZGI14D">Playground</a> | <a href="https://serpapi.com/searches/633a9dafa4be108f8a86f662/inspect">Inspect</a>

**Comment by aliayar** [comment]
This is probably due to the Crawlera Enterprise not being responsive. Users' other problem also arise from this problem.

Intercom Conversation IDs: 10291000003350 and 102910000033081.

**Comment by marm123** [comment]
Looks like the issue is present once again. Walmart Product API is stuck with almost every query. The API either produces 500 Internal errors or doesn't execute at all. There are some cases when, after 25-30 seconds, the response is available, but most of the time, it's not.

500 Internal Error:
<img width="1434" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/cfe8b302-19fc-4d64-8470-437c046c569d">

Query stuck:
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/510f9a72-e78d-42b0-bb4f-c51ec4ef1733">

[Playground - Internal Error](https://serpapi.com/playground?engine=walmart_product&product_id=14F8YD483N00) | [Inspect - Internal Error](https://serpapi.com/searches/64e874857f8361371a44d49a/inspect)
[Playground - Query stuck](https://serpapi.com/playground?engine=walmart_product&product_id=520468661&store_id=1542) | [Inspect - Query stuck](https://serpapi.com/searches/64e8750a79627ca3e86ddb85/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000047567?view=List)

**Comment by itszhengan** [comment]
Hi!

Today I ran into the same issue again. Would you please tell me when will this be resolved? Thanks!

**Comment by zyc9012** [comment]
Hi @itszhengan

We are still working on this, will let you know once it's stable ASAP.

**Comment by zyc9012** [comment]
@itszhengan Should be fixed. Kindly check on your side.
