### ISSUE TITLE
[Google Shopping API] Support Second Hand Condition Tags

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#35]
![shc](https://user-images.githubusercontent.com/73674035/149601902-54249ea6-57ed-4cc1-9030-862c898fb385.png)

[Inspect Link](https://serpapi.com/searches/61e217f9e4a23d315978e510/inspect)
[Playground Link](https://serpapi.com/playground?q=used+mechanical+keyboards&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=shop&no_cache=true&newPara=lr+async+as_qdr)

[Past Canny Link](https://serpapi.canny.io/admin/board/feature-requests/p/add-google-shopping-results-second-hand-condition-tags)

**Comment by dliver-more** [comment]
Is it possible to also add the used/second-hand tag for results from the individual product sellers?
<img width="889" alt="Screen Shot 2022-06-15 at 10 10 00 AM" src="https://user-images.githubusercontent.com/28791702/173862469-dd815cd8-4729-47f9-952b-88cc2bbf33cf.png">
