### ISSUE TITLE
[Knowledge Graph API] Need a way to load "View X+ more" results

### ISSUE THREAD

**Issue by sq-yuan** [serpapi/public-roadmap#353]
Right now, there's no way to expand the "View X+ more" link, we only returns a google link "people_also_search_for_link", but there's no way to issue another Serp request for that link, or parse the result for that link. 

![Screen Shot 2022-10-03 at 11 24 05 AM](https://user-images.githubusercontent.com/4009348/193653631-3b9d1011-c8aa-486a-8a5d-8c852f235acb.png)

**Comment by dimitryzub** [comment]
@sq-yuan Actually, we can do it with another request by using the `people_also_search_for_stick` value and passing it to `stick` parameter (hidden in the Playground by default):

![image](https://user-images.githubusercontent.com/78694043/193752828-466f1428-6d0a-4580-ac31-6d005958abbf.png)

A very simple Python code example to show the different lengths of `people_also_search_for` `list`:

```python
from serpapi import GoogleSearch
import os

params = {
    "api_key": os.getenv("API_KEY"),
    "engine": "google",
    "q": "apple",
    "google_domain": "google.com",
    "gl": "us",
    "hl": "en",
    "stick": None                                  # make a default value
}

search = GoogleSearch(params)
results = search.get_dict()                        # first request

print(f"search inpsect:https://serpapi.com/searches/{results['search_metadata']['id']}/inspect")
print(len(results["knowledge_graph"]["people_also_search_for"]))

people_also_search_for_stick = results["knowledge_graph"]["people_also_search_for_stick"]

if people_also_search_for_stick:
    params["stick"] = people_also_search_for_stick  # update default value
    
    results = search.get_dict()                     # second request
    
    print(f"search inpsect:https://serpapi.com/searches/{results['search_metadata']['id']}/inspect")
    print(len(results["knowledge_graph"]["people_also_search_for"]))
```

Outputs (have a look at URLs in the output):

```lang-none
search inpsect:https://serpapi.com/searches/633bd5b34d443d10f1ef7c7c/inspect
4
search inpsect:https://serpapi.com/searches/633bd7589d158610ea417554/inspect
23
```

Let me know if it doesn't make sense 🙂

**Comment by dimitryzub** [comment]
@sq-yuan Great 🙂 Glad it worked out for you.
