### ISSUE TITLE
[Google Reverse Image Search API] Searches do not return any results

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#369]
A lot of searches return no results recently. When trying to recreate a search query in Playground, the results are returned correctly.

1. Inspect page
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/28161162/195094446-5d794788-36c3-4d55-b499-32aaba80f1a4.png">

2. Playground page for the same image
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/28161162/195094742-77bcbcaf-bec8-4a41-9858-c44ab815ebed.png">

Couple of corrupt Inspect results with Playground counterparts
<a href="https://serpapi.com/searches/634560489c449d4ac001884d/inspect">Inspect - corrupt</a> | <a href="https://serpapi.com/playground?engine=google_reverse_image&location=United+States&image_url=https%3A%2F%2Fcrawler-search-images.s3.us-west-2.amazonaws.com%2F2022-09-30%2Fsource%2Ff084d620e330d13084e7f87d419050696409e14fb85682189a67cd3996c3fc6e.png&device=desktop&no_cache=true">Playground - correct</a>
<a href="https://serpapi.com/searches/63456048d5b1c511c9d40394/inspect">Inspect - corrupt</a> | <a href="https://serpapi.com/playground?engine=google_reverse_image&location=United+States&image_url=https%3A%2F%2Fcrawler-search-images.s3.us-west-2.amazonaws.com%2F2022-09-30%2Fsource%2F65f53c6bafc6aed311878427407f8b88c69e65f62caee57a59e6a49e3cec3e92.png&device=desktop&no_cache=true">Playground - correct</a>
<a href="https://serpapi.com/searches/63456048f0adfbf741eb1110/inspect">Inspect - corrupt</a> | <a href="https://serpapi.com/playground?engine=google_reverse_image&location=United+States&image_url=https%3A%2F%2Fcrawler-search-images.s3.us-west-2.amazonaws.com%2F2022-09-30%2Fsource%2F36523bc4416b1038a8cb3ef43933daacb5f694309ddd05c7b933e0693bac80a2.png&device=desktop&no_cache=true">Playground - correct</a>

**Comment by ilyazub** [comment]
> 1. Inspect page
> 
> <img alt="image" width="1081" src="https://user-images.githubusercontent.com/28161162/195094446-5d794788-36c3-4d55-b499-32aaba80f1a4.png">

Probably, non-US proxy was automatically picked in this specific case.

![image](https://user-images.githubusercontent.com/282605/201659661-e6805343-40a5-4ad2-b3e2-30f159301c6c.png)

**Comment by ilyazub** [comment]
Closing this issue as stale. Let's reopen it if customers encounter an issue with our [Google Lens Search API](https://serpapi.com/google-lens-api) or [Google Reverse Image Search API](https://serpapi.com/google-reverse-image).
