### ISSUE TITLE
[Bing/Baidu News API] Let's Make News Key Consistent 

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#372]
For all News engines, let's rename `organic_results` ->  `news_results` which contains news results. 

This way we user doesn't have to make additional logic in the code but rather use `news_results` for all news APIs which would make more sense and will be more expected.

Bing and Baidu news have `organic_results` key for news results. Is it how supposed to be?

|Bing|Baidu|
|-|-|
|![image](https://user-images.githubusercontent.com/78694043/195325782-cd92fff2-6c46-4744-8fe3-8a15958ddf0a.png)|![image](https://user-images.githubusercontent.com/78694043/195325598-09948888-c901-4739-bf43-a1f875b43f7a.png)|

While Google and Naver have `news_results` key for news results. Which is a more expected key for News API.

|Google|Naver|
|-|-|
|![image](https://user-images.githubusercontent.com/78694043/195326142-ec5b057a-141a-4d2a-acde-8dcacf65d2fc.png)|![image](https://user-images.githubusercontent.com/78694043/195326201-af997fac-9a22-4c38-80d1-b33117ff4c5d.png)|

**Comment by Krugloff** [comment]
This isn’t particularly useful as an issue, especially since we don’t have strict guidelines in place (as discussed with @zyc9012). Otherwise, it should be documented in a wiki or README file.
