### ISSUE TITLE
[New Bing API] Add Support for Bing Images Tab

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#373]
Extract Bing Images as we already doing with Google, Yahoo, Yandex, and so on.

Example URL: https://www.bing.com/images/search?q=cat

![image](https://user-images.githubusercontent.com/78694043/195327965-4f586016-1342-4326-8796-d0931f2ddf7a.png)

**Comment by schaferyan** [comment]
Closing this since we currently support Bing Images
