### ISSUE TITLE
[Google Search API] Support `Trending Videos` section in `mobile` searches

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#375]
![trendingvideos](https://user-images.githubusercontent.com/73674035/195348240-c205dad9-ac28-4bc1-b21d-ff8cfe1b2d79.png)

[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=tablet&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips)
[Inspect](https://serpapi.com/searches/6346b846d3aba2c23951fb03/inspect)

**Comment by aciddjus** [comment]
This has been resolved.

<img width="1434" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/551816c4-72b1-4253-aa40-5da30867b093">

--------------------

[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=tablet&no_cache=true&google_domain=google.com)
