### ISSUE TITLE
[Google Search API] Support stock and availability info in `organic_results` for `mobile`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#379]
![stock](https://user-images.githubusercontent.com/73674035/195355168-bc5da962-9b28-4d44-a0ea-49469b6c8195.png)

[Playground](https://serpapi.com/playground?q=PS5&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&num=100&device=mobile&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips)
[Inspect](https://serpapi.com/searches/6346bdc9a1b4239b0f732a95/inspect)

**Comment by aciddjus** [comment]
Closing this as I wasn't able to replicate the layout.
