### ISSUE TITLE
[Google Search API] Some `organic_results` are not parsed

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#382]
![missingorganic](https://user-images.githubusercontent.com/73674035/195366015-a136106f-4d6d-4c26-a55c-54324e8e54b1.png)

[Inspect](https://serpapi.com/searches/6346c9e3fe41d05cda45bf71/inspect)
[Playground](https://serpapi.com/playground?q=Starbucks&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&num=100&device=desktop&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips)

**Comment by ilyazub** [comment]
Related to or duplicate of https://github.com/serpapi/public-roadmap/issues/87?

**Comment by kagermanov27** [comment]
>Related to or duplicate of https://github.com/serpapi/public-roadmap/issues/87?

Most Probably. Closing it now.
