### ISSUE TITLE
[Google Search API] `related_questions` changed design and are missing

### ISSUE THREAD

**Issue by dethfire** [serpapi/public-roadmap#387]
All my API queries are returning without "related questions". If I use the demo on the homepage, it has "related questions" in the JSON.

Here is an example
https://serpapi.com/searches/b2bae660d63ad659/634712e8654a8c58e5daa05c.json

![F7D21099-272D-489D-962C-7F073A342146](https://user-images.githubusercontent.com/97758415/195430882-47803755-6ba6-47f6-840b-f45eea00d2d0.jpeg)

**Comment by hartator** [comment]
If you look into the [HTML](https://serpapi.com/searches/b2bae660d63ad659/634712e8654a8c58e5daa05c.html) of your JSON example, there is no related questions block for SerpApi to extract.

Sometimes it's a little random if a related questions block will show up for a query or not. As Google is probably testing if it's appropriate or not to show that block on a query per query basis. 

I am closing this, but feel free to re-open if you find an example where it's in the HTML but not in the JSON (there is no difference between our demos and the API results in term of actual processing).

**Comment by dethfire** [comment]
Hi, if the API demo and the API are the same, why are there different results? How do I get the API demo results? I am using the same parameters. I am processing several dozen keywords for PAA and last week they all provided PAA and now this week none of them do.

**Comment by hartator** [comment]
> Hi, if the API demo and the API are the same, why are there different results? How do I get the API demo results?

It's strictly the same API endpoint if you look at the AJAX call. It's just presented differently.

I am re-open this and marking it as urgent as it does appear Google just released a new look for their related question:

![image](https://user-images.githubusercontent.com/307597/195458558-0e3e9a31-42b1-435d-9f4c-d699aacb10af.png)

Ref: https://serpapi.com/searches/40d33ebafddbb8f8/63472803ce87f8e5662f672a.html

Post here other examples of that new design as it can be very helpful when working on a fix.

**Comment by dethfire** [comment]
Thanks! I was seeing that format before, but not now. Could be a test. I am trying many different keywords and can't get "related_questions" to surface even though they show in the demo json.

**Comment by dethfire** [comment]
If I leave the "num" parameter out of the API call I get the PAA related-questions again.
