### ISSUE TITLE
[Google Play Store API] Extract App Developer Name

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#388]
Right now we're not extracting  app developer name. This could be useful for data analysis. 

As a very simple question analysis example, such data could be used to answer "Which companies have the most presence share at app store?" 

![image](https://user-images.githubusercontent.com/78694043/195528601-c52686bd-c036-4496-93ca-ce9a69cd40a9.png)

After a few minutes of investigation, I saw that the developer name appears in the URL `id` parameter: `id=<domain>.<developer_name>`

A few examples:

```lang-none
id=com.whatsapp
id=com.instagram.android
id=com.zhiliaoapp.musically # = TikTok
id=com.netflix.mediaclient
id=com.qqlabs.minimalistlauncher
id=com.goodreads
id=com.babbel.mobile.android.en
id=jp.takoboto
id=com.amazon.mShop.android.shopping
id=fm.dice
id=net.daylio
```

**Comment by kagermanov27** [comment]
@dimitryzub,
This is called `Bundle Id`, and it is usually the reversed version of the website for the app. `author` part is already serving the developer.
[Apple App Store Scraper API Documentation](https://serpapi.com/apple-app-store#api-examples-json-structure-overview)
It was being served as a separate key in Apple App Store Scraper API, so it made sense to serve it. But in this case, if it is not helpful for serving other kinds of data, I don't think we should be extracting it.
@aciddjus What do you think?

**Comment by dimitryzub** [comment]
@kagermanov27 But I meant Google Play Store, not Apple App Store 🙂

**Comment by kagermanov27** [comment]
>but I meant Google Play Store, not Apple App Store 

Yes, I was simply pointing out its counterpart in Apple App Store, and why it was extracted there, and why it shouldn't be extracted here.

**Comment by aciddjus** [comment]
We don't necessarily know if these are developer names. They just seem to be website URL domains in reverse.

**Comment by dimitryzub** [comment]
I'm closing this issue for now per the comments above.
