### ISSUE TITLE
[New Google Scholar Author Articles API] Add Support for Extracting Individual Author Article

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#394]
We're currently not extracting data from individual Author Articles. 

Example Author Article URL: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=VxOmZDgAAAAJ&citation_for_view=VxOmZDgAAAAJ:u5HHmVD_uO8C

![image](https://user-images.githubusercontent.com/78694043/195777514-71b6a26d-4891-4215-8ebf-99b680e58ff5.png)

**Comment by aciddjus** [comment]
We already support this:

- [Playground](http://localhost:3000/playground?engine=google_scholar_author&author_id=EicYvbwAAAAJ&hl=en&view_op=view_citation&citation_id=VxOmZDgAAAAJ%3Au5HHmVD_uO8C)
- [Documentation](https://serpapi.com/google-scholar-author-citation)
