### ISSUE TITLE
[Google Play Books Store API] Typo in example JSON

### ISSUE THREAD

**Issue by chukhraiartur** [serpapi/public-roadmap#398]
There is a typo in the documentation example:

![typo](https://user-images.githubusercontent.com/81998012/195892485-02ad32c4-c271-4dcd-919f-64fe253465d8.png)

Current key name:

```python
"extansion": {
    # some data
},
```

Expected key name:

```python
"extension": {
    # some data
},
```

Link to Documentation: https://serpapi.com/google-play-books

**Comment by sebastianquek** [comment]
@chukhraiartur Thanks for raising this issue. Both the documentation and the actual output JSON have been updated to use the "extension" key.
