### ISSUE TITLE
[Google Search API] Missing Short Video Content

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#4]
One of our users reported that Google does not parse several elements from certain mobile results page. The differences here are that search device is mobile ad we are searching for videos of a darling of TikTok users: Charli D'amelio.

Missing elements in the results: (All numbered in the screenshot)

1- Video tags and their links
2- Youtube channel's link and a selection of videos
3- Short videos
4- People also search for (contents of this element is returned in related_searches key)
5- TikTok channel's link and a selection of videos
6- TikTik category link and a selection of videos
7- Broaden this search
8- Related searches (content of this element is not returned at all, returned content is from people also search for section)

The Playground:

https://serpapi.com/playground?q=charli+d%27amelio+videos&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile

The Inspect:

https://serpapi.com/searches/6213ce7f49ecdb4ebc4202ed/inspect

Screenshot:

<img width="789" alt="google_search_mobile_videos" src="https://user-images.githubusercontent.com/64849049/155093657-74f41801-d3b7-4826-88f6-5b918eb14a8c.png">

**Comment by githubfan21** [comment]
this is still missing, why is this ticket closed?
 
https://serpapi.com/searches/627a8f2ea4bb386db90c1d64/inspect

![image](https://user-images.githubusercontent.com/15785331/167708557-ac7125dc-71a0-4c8b-8720-7a37891b23db.png)

**Comment by ilyazub** [comment]
> this is still missing, why is this ticket closed?
> 
> https://serpapi.com/searches/627a8f2ea4bb386db90c1d64/inspect

@githubfan21 Thanks for reporting regression. Probably selectors gone updated again. We will fix it.
