### ISSUE TITLE
[New API] Add Yelp API

### ISSUE THREAD

**Issue by Mennaruuk** [serpapi/public-roadmap#40]
Welp, it seems like the only thing keeping SerpAPI from turning into a Super Saipan is Yelp!

But seriously, it would be nice to be able to scrape Yelp search results. Whether I like it or not, Yelp has the best combination of business names, reviews, and photos, and plenty of people trust what users on Yelp say. It’s a must for SerpAPI!

**Comment by aciddjus** [comment]
We have added the Yelp API.

- Documentation: https://serpapi.com/yelp-search-api
- Playground: https://serpapi.com/playground?engine=yelp

**Comment by Mennaruuk** [comment]
**THANK YOU!!!!** @aciddjus
