### ISSUE TITLE
[Walmart Product API] Returns empty results or errors for specific product IDs

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#42]
Walmart Product API returns empty results. Checked twice, those products return results but more than occasional hiccups preventing user completing their task.

`Product ID: 913713226`

**Inspect**: https://serpapi.com/searches/622117892236e2bcc473de66/inspect

```
{
  "search_metadata": {
    "id": "622117892236e2bcc473de66",
    "status": "Error",
    "json_endpoint": "https://serpapi.com/searches/d802734da53bc2d7/622117892236e2bcc473de66.json",
    "created_at": "2022-03-03 19:31:21 UTC",
    "processed_at": "2022-03-03 19:31:21 UTC",
    "walmart_product_url": "https://www.walmart.com/ip/913713226?selected=true",
    "total_time_taken": 450.98
  },
  "search_parameters": {
    "product_id": "913713226",
    "engine": "walmart_product",
    "device": "desktop"
  },
  "error": "We couldn't get valid results for this search. Please try again later. Set the no_cache parameter to true in order to force a retry."
}
```

The screenshot: 

<img width="743" alt="walmart_product_api" src="https://user-images.githubusercontent.com/64849049/157662461-f2bc2b03-58e4-4f9b-a53d-c10ee70f4fdf.png">

**The Playground**: https://serpapi.com/playground?engine=walmart_product&product_id=913713226

User also stated that they had problem with **994807896** but Playground seems fine:

https://serpapi.com/playground?engine=walmart_product&product_id=994807896

next.

**Comment by tanys123** [comment]
@ilyazub @aciddjus Is there a way for me to review the detail proxy log for this search? https://serpapi.com/searches/622117892236e2bcc473de66/inspect

**Comment by ritu1337** [comment]
> @ilyazub @aciddjus Is there a way for me to review the detail proxy log for this search? https://serpapi.com/searches/622117892236e2bcc473de66/inspect

Not yet but there could be with https://github.com/serpapi/SerpApi/pull/2589#issuecomment-1030744798 😉

**Comment by tanys123** [comment]
No longer able to reproduce this. Closing this for now. Feel free to re-open if similar issue occurs again.
