### ISSUE TITLE
On Google Search API, sometimes not all required results are displayed on the mobile device.

### ISSUE THREAD

**Issue by amonasterio** [serpapi/public-roadmap#421]
When I am doing a Google search with a mobile device and I **set 100 as the number of results**, with some queries SerpApi shows me 100 results but with others it shows me only 10. On desktop I don't have this problem.

![image](https://user-images.githubusercontent.com/14939565/196625494-1f66ac80-1cad-4ee4-96fb-0781e876fd59.png)
![image](https://user-images.githubusercontent.com/14939565/196625759-0079abce-f281-417f-9b81-2adc6cca687d.png)

**Query with 10 results**
https://serpapi.com/playground?q=sa+calobra&location=Spain&google_domain=google.es&gl=es&hl=es&num=100&device=mobile

**Query  with 100 results**
https://serpapi.com/playground?q=excursiones+en+mallorca&location=Spain&google_domain=google.es&gl=es&hl=es&num=100&device=mobile

**Comment by aciddjus** [comment]
Thanks for reporting the issue, @amonasterio.

It seems that this is the default behavior for this particular search query. If you try [the link](https://www.google.es/search?q=sa+calobra&oq=sa+calobra&uule=w+CAIQICIFU3BhaW4&hl=es&gl=es&num=100&sourceid=chrome-mobile&ie=UTF-8) on your phone it will return only up to 10 results. You can change other parameters, but as long as the query is "sa calobra" it will return only up to 10 results.

This is not the first time we are seeing this strange behavior from Google, where certain queries can only return up to 10 results. But there is nothing we can do from our side.
