### ISSUE TITLE
[Google Maps API] Place results are forced with `type` parameter set to search

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#425]
Even though there is a `type` parameter set for `search`, Google Maps API returns results for `type=place` for some API calls.

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/28161162/196879076-c9035799-71ff-4c2c-8440-e51bb2722422.png">

<a href="https://serpapi.com/playground?engine=google_maps&q=acoustics+in+Wuyishan+China&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&type=search">Playground</a> | <a href="https://serpapi.com/searches/634ff1a63bea7be9ee73ec6a/inspect">Inspect</a>

**Comment by aciddjus** [comment]
If you try searching `acoustics in Wuyishan China` on Google Maps directly it will also redirect to `place` as well. I think they do this redirect when there is only one result for the search query.

**Comment by marm123** [comment]
That is true @aciddjus, however, there is also an example, where Google Maps redirects to a specific `place` but using it with our API it doesn't force the `type` parameter to change from `search` to `place`.

Not sure which one of those is correct though and if both of them should be redirected to a specific `place` or none of them.

<a href="https://serpapi.com/searches/634ff17e3a218a0b9af6f7df/inspect">Inspect - acoustics in Ma'anshan China</a>

**Comment by aciddjus** [comment]
You're correct. There's some discussion about it [here](https://github.com/serpapi/SerpApi/issues/1769).

I think @ritu1337 might know a bit more about the issue.

**Comment by aciddjus** [comment]
We have fixed this issue.

<img width="2560" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/c66e3b56-5444-4f0c-af8e-11a97a144fc9">

----------------

[Playground](https://serpapi.com/playground?engine=google_maps&q=acoustics+in+Wuyishan+China&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&type=search)
