### ISSUE TITLE
[Apple Reviews API] Maximum Page Depth is limited to 10

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#43]
Apple Reviews Scraper API's maximum depth limit itself to maximum of 10 pages. It needs to be increased to real maximum of the search.
![ar](https://user-images.githubusercontent.com/73674035/157228253-07cc8c76-5dd7-4e41-99e5-629e7adca0cf.png)

**Comment by marm123** [comment]
Another customer is requesting this:

[Intercom](https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000036095)
