### ISSUE TITLE
[SerpApi Main Page] Blog button missing from navigation menu

### ISSUE THREAD

**Issue by chukhraiartur** [serpapi/public-roadmap#432]
When I go to the [main page](https://serpapi.com/) of the site, I run into a problem. The problem is that you have to scroll to the bottom of the page and find the __Blog__ element in the footer of the page:

![1](https://user-images.githubusercontent.com/81998012/197082412-e0cc498a-593e-4e68-a42b-dd03da971ad7.png)

On the [blogs page](https://serpapi.com/blog/) there is this item:

![2](https://user-images.githubusercontent.com/81998012/197082637-2c9a5788-59b4-4a5d-9c21-f30012986bde.png)

It will be difficult for new users to navigate if they want to look at some blog posts before directly using the API.  A new user may not even know about the existence of the Blog because there is no such button. That is, at the moment only those who are purposefully looking for it know about the Blog.

Therefore, I want to suggest that the __Blog__ item be added to the navigation menu.

Current navigation menu:

![3](https://user-images.githubusercontent.com/81998012/197083052-3d969cbd-da0b-486a-b14c-0c39c074c814.png)

Expected navigation menu:

![4](https://user-images.githubusercontent.com/81998012/197083450-0bcc65dc-e2dc-42ce-a19b-e601968bbfba.png)

Link to main page: https://serpapi.com/
Link to blogs page: https://serpapi.com/blog/

**Comment by hilmanski** [comment]
Discussed internally in this thread: https://github.com/serpapi/SerpApi/issues/4456
