### ISSUE TITLE
[Google Trends API] Add the `timestamp` key

### ISSUE THREAD

**Issue by chukhraiartur** [serpapi/public-roadmap#437]
For now, we can extract only the `date` key, which stores the time range. This range is difficult to standardize for the end user.

`timestemp` would be a lot more user-friendly if there's a need to create a time-series plot that will be updated on regular basis. For now, clients need to do it on their own which is not a straightforward process.

Examples below:

![02](https://user-images.githubusercontent.com/81998012/197204433-c4cae3ba-3127-4eaf-8719-a105a923fd2d.png)

Expected result:

![01](https://user-images.githubusercontent.com/81998012/197204418-f74784d3-e319-48dc-9948-d157f9175451.png)

Link to Documentation: https://serpapi.com/google-trends-api#api-examples-interest-over-time-chart-with-q-coffee-milk-bread-pasta-steak-and-data-type-timeseries

**Comment by dimitryzub** [comment]
@tanys123 Thank you 🧡

____

Posting this code for anyone who may stumble on this issue and how SerpApi could be used to create a chart:

```python
from serpapi import GoogleSearch
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

%matplotlib inline # used inside Jupyter Notebook

params = {
  "api_key": "<your serpapi API key>",
  "device": "desktop",
  "engine": "google_trends",
  "q": "minecraft,gta,roblox,skyrim,dota",
  "data_type": "TIMESERIES"
}

search = GoogleSearch(params)
results = search.get_dict()

timeseries = []

# extracting data
for result in results['interest_over_time']['timeline_data']:
    for value in result['values']:
        query = value['query']
        extracted_value = value['extracted_value']
        
        timeseries.append({
          'timestamp': result['timestamp'],
          'query': query,
          'extracted_value': extracted_value,
        })


# Plotting data
df = pd.DataFrame(data=timeseries)

sns.set(rc={"figure.figsize": (13, 5)})
palette = sns.color_palette("mako_r", 5)  # 5 is number of colors

ax = sns.lineplot(
    data=df,
    x="timestamp",
    y="extracted_value",
    hue="query",
    palette=palette,
    marker="o",
)

plt.legend(bbox_to_anchor=(1.01, 1), loc="upper left", borderaxespad=0)
ax.set(xticklabels=[])
ax.set(xlabel="")

plt.show()
```

|Google Trends|Resulted graph|
|-|-|
|![image](https://user-images.githubusercontent.com/78694043/198078687-51616562-9f97-4ffe-8e53-907a77a331bd.png)|![image](https://user-images.githubusercontent.com/78694043/198078595-b24b5b00-8660-4737-aacf-e5d9f7669643.png)|


When [`"date": "all"`](https://serpapi.com/google-trends-api#api-parameters-advanced-google-trends-parameters-date):

|Google Trends|Resulted Graph|
|-|-|
|![image](https://user-images.githubusercontent.com/78694043/198079143-a5b2339b-76e6-4b95-8e63-f248f8c49052.png)|![image](https://user-images.githubusercontent.com/78694043/198079176-b99abd02-8ec6-4860-a7bd-3a051e35b6a8.png)|
