### ISSUE TITLE
[New API] Google Finance Markets API

### ISSUE THREAD

**Issue by aciddjus** [serpapi/public-roadmap#438]
Link: https://www.google.com/finance/markets/most-active

![image](https://user-images.githubusercontent.com/6929257/197210444-9ab5b1e8-96ca-4c35-a906-a65a3c45be4a.png)

Related to: https://github.com/serpapi/public-roadmap/issues/75

**Comment by dimitryzub** [comment]
@aciddjus 💛

Seems like a duplicate of #317.

**Comment by aciddjus** [comment]
It is, I missed it. 👍
