### ISSUE TITLE
[Google Search API] Can not scrape local result

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#449]
![Screen Shot 2022-10-27 at 16 23 25](https://user-images.githubusercontent.com/99160364/198246691-8917ba52-ade6-40da-9aa9-08acae6dd0a2.png)

The local result is missing for this search

Inspect: https://serpapi.com/searches/635a4de9224db1bbe81258f5/inspect
Playground: https://serpapi.com/playground?q=market&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&newPara=stick

**Comment by andywaite** [comment]
I beleive this is the issue we're seeing.

We're seeing a lot of searches that have local pack, but the local results aren't being parsed and added to the structured JSON we get from SERPapi.

<img width="1554" alt="Screenshot 2022-11-08 at 11 44 33" src="https://user-images.githubusercontent.com/6773151/200555833-6dcd7963-fe19-4f86-9b2c-9b58a9fce6ca.png">

```
"search_metadata":
{

    "id": "636a4051e0ded4fb904fe2db",
    "status": "Success",
    "json_endpoint": "https://serpapi.com/searches/5104e1111084b2eb/636a4051e0ded4fb904fe2db.json",
    "created_at": "2022-11-08 11:41:05 UTC",
    "processed_at": "2022-11-08 11:41:05 UTC",
    "google_url": "https://www.google.com/search?q=pizza+wetzikon&oq=pizza+wetzikon&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM&hl=en&gl=us&sourceid=chrome&ie=UTF-8",
    "raw_html_file": "https://serpapi.com/searches/5104e1111084b2eb/636a4051e0ded4fb904fe2db.html",
    "total_time_taken": 1.03

}
```

**Comment by dimitryzub** [comment]
@andywaite the issue should be solved now. Could you confirm on your end?

Example ([playground link](https://serpapi.com/playground?q=pizza+wetzikon&location=United+States&gl=us&hl=en&device=desktop&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+stick%25252525252520highlight%25252525252520lr%25252525252520as_qdr%25252525252520safe%25252525252520google_domain%25252525252520si%25252525252520form%25252525252520filter%25252525252520chips+stick%252525252520highlight%252525252520lr%252525252520as_qdr%252525252520safe%252525252520google_domain%252525252520si%252525252520form%252525252520filter%252525252520chips+stick%2525252520highlight%2525252520lr%2525252520as_qdr%2525252520safe%2525252520google_domain%2525252520si%2525252520form%2525252520filter%2525252520chips+tbs+as_epq)): 

![google-local-results-example](https://user-images.githubusercontent.com/78694043/200791930-03e81abb-2f14-4a78-95c7-0e1552be1510.gif)

**Comment by andywaite** [comment]
Appears to be resolved, thanks
