### ISSUE TITLE
[Google Trends API] Sometimes Searches Return an `error`

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#450]
_Feel free to update the title to a more searchable one_.

Query on Google Trends: [audi,bmw,bentley,dodge,volvo](https://trends.google.com/trends/explore?date=all&geo=US&q=audi,bmw,bentley,dodge,volvo):

![image](https://user-images.githubusercontent.com/78694043/198279733-db6b2f07-7da1-48e7-a21d-74b2a55c0b01.png)

Our API returns `error`: `"Google Trends hasn't returned any results for this query."`:

![image](https://user-images.githubusercontent.com/78694043/198282521-58ae7c2e-c995-481f-aa24-2de253ec5bc8.png)

[Playground](https://serpapi.com/playground?engine=google_trends&q=audi%2Cbmw%2Cbentley%2Cdodge%2Cvolvo&data_type=TIMESERIES&date=today+12-m) | [Inspect](https://serpapi.com/searches/635a734fc640d2b4b6c2552b/inspect)

_____

Similar behavior in those queries among others (playground/inspect links):

- Playground [audi,bmw](https://serpapi.com/playground?engine=google_trends&q=audi%2Cbmw&data_type=TIMESERIES&date=today+12-m) / [Inspect](https://serpapi.com/searches/635a7482d036a7b152b7a2e0/inspect)
- Playground [London,Texas](https://serpapi.com/playground?engine=google_trends&q=London%2CTexas&data_type=TIMESERIES&date=today+12-m) / [Inspect](https://serpapi.com/playground?engine=google_trends&q=London%2CTexas&data_type=TIMESERIES&date=today+12-m)
-  Playground [pork,fork](https://serpapi.com/playground?engine=google_trends&q=pork%2Cfork&data_type=TIMESERIES&date=today+12-m) / [Inspect](https://serpapi.com/searches/635a757dc7ad41471aa5c155/inspect)
- Playground [pork](https://serpapi.com/playground?engine=google_trends&q=pork&data_type=TIMESERIES&date=today+12-m) / [Inspect](https://serpapi.com/searches/635a76af2d5b12c791041fc5/inspect)

**Comment by ilyazub** [comment]
It worked for me. Let's close this issue and re-open if problem occurred again.

![image](https://github.com/serpapi/public-roadmap/assets/282605/2daab071-b28f-4ef1-acf3-13f1cd08e90b)
(ref: https://serpapi.com/playground?engine=google_trends&q=audi%2Cbmw%2Cbentley%2Cdodge%2Cvolvo&geo=US&data_type=TIMESERIES&tz=420&date=all)
