### ISSUE TITLE
[Google Product Result API] Some detail pages are returning blank results in Google Product Result API

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#454]
Some detail pages for Google Product Results API are returning blank results, even though, while using a direct Google link from Google Shopping API `shopping_results`, we are able to get details of that product.

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/28161162/199208237-6b38bc49-d46d-4646-929a-ebc5696d190d.png">
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/28161162/199208474-4a3599c5-822b-4b04-97b5-1c616572bd78.png">

<a href="https://serpapi.com/playground?q=lego_60282&location=Germany&google_domain=google.de&gl=de&hl=en&safe=active&tbm=shop&num=25&device=desktop&safe=active&google_domain=google.de&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+stick%2525252520highlight%2525252520lr%2525252520as_qdr%2525252520safe%2525252520google_domain%2525252520si%2525252520form%2525252520filter%2525252520chips+stick%25252520highlight%25252520lr%25252520as_qdr%25252520safe%25252520google_domain%25252520si%25252520form%25252520filter%25252520chips+stick%252520highlight%252520lr%252520as_qdr%252520safe%252520google_domain%252520si%252520form%252520filter%252520chips">Playground - Google Shooping API</a> | <a href="https://serpapi.com/searches/6360ee8baf630496e29a97ce/inspect">Inspect - Google Shopping API</a>
<a href="https://serpapi.com/playground?engine=google_product&product_id=48014270659041820&location=Germany&google_domain=google.de&gl=de&hl=en&device=desktop">Playground - Google Product API product 1</a> | <a href="https://serpapi.com/searches/6360eef411c881341c965c0a/inspect">Inspect - Google Product API product 1</a> | <a href="https://www.google.de/shopping/product/1?gl=de&prds=pid:48014270659041820">Google details page product 1</a>
<a href="https://serpapi.com/playground?engine=google_product&product_id=5241485928906111355&location=Germany&google_domain=google.de&gl=de&hl=en&device=desktop">Playground - Google Product API product 2</a> | <a href="https://serpapi.com/searches/6360efeb94fb03e3cb02745c/inspect">Inspect - Google Product API product 2</a> | <a href="https://www.google.de/shopping/product/1?gl=de&prds=pid:5241485928906111355">Google details page product 2</a>

**Comment by ilyazub** [comment]
Related to
- https://github.com/serpapi/SerpApi/issues/3013
- https://github.com/serpapi/SerpApi/issues/2515
- https://github.com/serpapi/SerpApi/pull/2148
- https://github.com/serpapi/SerpApi/issues/2078#issuecomment-938097984
- https://github.com/serpapi/SerpApi/issues/2078#issuecomment-998143540

Supersedes https://github.com/serpapi/SerpApi/issues/476

**Comment by marm123** [comment]
<a href="https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000035751">Another user</a> is reporting the same issue:

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/28161162/205592033-2720df93-0a21-4b5e-a77b-556f54e47f13.png">

<a href="https://serpapi.com/playground?engine=google_product&product_id=7436603120339574321&location=Istanbul%2C+Istanbul%2C+Turkey&google_domain=google.com.tr&gl=tr&hl=tr&device=desktop">Playground - Google Product</a> | <a href="https://serpapi.com/searches/638dadb65f2203604b6f1f2d/inspect">Inspect - Google Product</a> | <a href="https://www.google.com.tr/shopping/product/7436603120339574321?sourceid=chrome&ie=UTF-8&uule=w+CAIQICIYSXN0YW5idWwsSXN0YW5idWwsVHVya2V5&hl=tr&gl=tr">Google link from Google Product</a>
<a href="https://serpapi.com/playground?q=playstation+5&location=Istanbul%2C+Istanbul%2C+Turkey&google_domain=google.com.tr&gl=tr&hl=tr&tbm=shop&device=desktop&no_cache=true">Playground - Google Shopping</a> | <a href="https://serpapi.com/searches/638dada88e02e4dab1e6a56d/inspect">Inspect - Google Shopping</a> | <a href="https://www.google.com.tr/shopping/product/1?gl=tr&prds=pid:7436603120339574321">Google link from Google Shopping</a>

**Comment by marm123** [comment]
[Another user](https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/conversation/102910000036042) with the same problem

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/28161162/208365857-eb2c1558-73c3-4ffd-9b04-036ac1da1bb1.png">

[Playground](https://serpapi.com/playground?engine=google_product&product_id=16300056194623728638&location=Dallas-Ft.+Worth%2C+TX%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop) | [Inspect](https://serpapi.com/searches/63a009ee969c085353d67cbf/inspect)
[Google direct link - doesn't work ](https://www.google.com/shopping/product/16300056194623728638?sourceid=chrome&ie=UTF-8&uule=w+CAIQICInRGFsbGFzLUZ0LiBXb3J0aCxUWCxUZXhhcyxVbml0ZWQgU3RhdGVz&hl=en&gl=us)| [Google direct link - works](https://www.google.com/shopping/product/1?gl=us&prds=pid:16300056194623728638)

**Comment by marm123** [comment]
[Another user](https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000026939) with this problem

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/28161162/211258035-5eb43a9f-b3bb-4662-9ada-3ccf8a560389.png">

[Playground](https://serpapi.com/playground?engine=google_product&product_id=3264039454169559017&location=Dallas-Ft.+Worth%2C+TX%2C+Texas%2C+United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/63b819df2bc7d8d81139692c/inspect)
[Google direct link - doesn't work ](https://www.google.com/shopping/product/3264039454169559017?sourceid=chrome&ie=UTF-8&uule=w+CAIQICInRGFsbGFzLUZ0LiBXb3J0aCxUWCxUZXhhcyxVbml0ZWQgU3RhdGVz&hl=en&gl=us)| [Google direct link - works](https://www.google.com/shopping/product/1?gl=us&prds=pid:3264039454169559017)

**Comment by martin-serpapi** [comment]
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000063136?view=List)

**Comment by ilyazub** [comment]
Our [Google Product API](https://serpapi.com/google-product-api) successfully scrapes these types of products. Closing this issue as resolved in serpapi/SerpApi#4070 (thanks @andypple83).

![image](https://github.com/serpapi/public-roadmap/assets/282605/b2258960-ebdd-4f30-bbb6-c83f1c1d2c83)
(ref: https://serpapi.com/playground?engine=google_product&product_id=1957333673749266253&location=United+States&gl=us&hl=en)

![image](https://github.com/serpapi/public-roadmap/assets/282605/43ec14de-5361-4f30-86a8-dbd773901f42)
(ref: https://www.google.com/shopping/product/1?uule=w+CAIQICINVW5pdGVkIFN0YXRlcw&gl=us&hl=en&prds=pid:1957333673749266253&sourceid=chrome&ie=UTF-8)
