### ISSUE TITLE
[Google Videos API] Key moments not parsed on mobile

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#457]
![km](https://user-images.githubusercontent.com/73674035/199224131-edfe7774-d394-4486-9b42-5294547ff107.png)
[Inspect](https://serpapi.com/searches/635f1b1ca1b423f738f60da8/inspect)
[Playground](https://serpapi.com/playground?q=Google+Stadia&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=vid&num=100&device=mobile&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+client)

**Comment by Ovi** [comment]
We now parse `key_moments` on mobile

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/0c7ec933-7c74-4f0a-b6fc-334829484318">

[Playground](https://serpapi.com/playground?q=Google+Stadia&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=vid&num=100&device=mobile&no_cache=true&google_domain=google.com)
