### ISSUE TITLE
[Google Search API] Add support to the `cr` parameter

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#459]
Currently, we are not supporting the `cr` parameter, which restricts Google to only displaying local results from a specific country. It works in combination with a country's Google domain. The structure for this parameter is `cr=countryXX`, where XX is a country code. More information about the `cr` parameter can be found under the following link:

<a href="https://support.google.com/websearch/thread/2597215/faq-how-to-get-global-local-and-eu-search-results?hl=en">[FAQ] How to get Global, Local and EU search results</a>

A couple of examples below:

1. Google search defaults to pages from the United Kingdom
https://www.google.co.uk/webhp?cr=countryUK%7CcountryGB
<a href="https://www.google.co.uk/search?q=Coffee&cr=countryUK%7CcountryGB&tbs=ctr%3AcountryUK%7CcountryGB&source=hp&ei=kyFiY_fZL7i8xc8PobCPqAk&iflsig=AJiK0e8AAAAAY2Ivo32kaaAdZKwNF_zShMEYpkdhGvhV&ved=0ahUKEwi37-TmgY_7AhU4XvEDHSHYA5UQ4dUDCAg&uact=5&oq=Coffee&gs_lp=Egdnd3Mtd2l6uAED-AEBMggQLhiABBjUAjIFEAAYgAQyCBAAGIAEGMkDMgUQABiABDILEC4YgAQYxwEYrwEyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABMICCxAuGIAEGMcBGNEDwgIOEC4YgAQYxwEY0QMY1ALCAgUQLhiABKgCAEijDVCGA1jgCnABeADIAQCQAQCYAVSgAccDqgEBNg&sclient=gws-wiz">Example</a>

2. Google search defaults to pages from Canada
https://www.google.ca/webhp?cr=countryCA
<a href="https://www.google.ca/search?q=Coffee&cr=countryCA&tbs=ctr%3AcountryCA&source=hp&ei=lCFiY5fqIPmCxc8P5tqIsAk&iflsig=AJiK0e8AAAAAY2IvpMXlyDvcAdXsuPqwyb9nyVtH0zmA&ved=0ahUKEwiXhJPngY_7AhV5QfEDHWYtApYQ4dUDCAg&uact=5&oq=Coffee&gs_lp=Egdnd3Mtd2l6uAED-AEBMgQQABhDMgcQABjJAxhDMgQQABhDMgQQABhDMgQQABhDMgQQABhDMgQQABhDMgQQABhDMgQQABhDMgQQABhDwgIHEC4Y1AIYQ8ICBBAuGENIywlQAFjiCHAAeADIAQCQAQCYAXGgAbIEqgEDNS4x&sclient=gws-wiz">Example</a>

3. Google search defaults to pages from Australia
https://www.google.com.au/webhp?cr=countryAU
<a href="https://www.google.com.au/search?q=Coffee&cr=countryAU&tbs=ctr%3AcountryAU&source=hp&ei=lSFiY7GUCoG8xc8PuqSlqAk&iflsig=AJiK0e8AAAAAY2IvpWXIiLsNe6x9kSa6oDM-MFfsQ_cR&ved=0ahUKEwjxsrnngY_7AhUBXvEDHTpSCZUQ4dUDCAg&uact=5&oq=Coffee&gs_lp=Egdnd3Mtd2l6uAED-AEBMggQLhiABBjUAjIFEAAYgAQyCBAAGIAEGMkDMgUQABiABDILEC4YgAQYxwEYrwEyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABMICCxAuGIAEGMcBGNEDwgIOEC4YgAQYxwEY0QMY1ALCAgUQLhiABEibCFAAWJoHcAB4AMgBAJABAJgBbqABrQSqAQM0LjI&sclient=gws-wiz">Example</a>

This can be added as an additional Localization parameter:
![image](https://user-images.githubusercontent.com/28161162/199433741-75a3e984-3b30-4436-bc30-638330a7e727.png)

**Comment by schaferyan** [comment]
An important note from #1095 is that with `cr` parameter` it is possible to include multiple countries. The customer I interacted with before opening that issue was specifically interested in being able to filter by multiple locations at once.

It makes sense to close that issue, I just wanted to make sure the request to include the option of filtering by multiple locations at once is included here, since that was a core concern of the customer I spoke to.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000049298?view=List)

**Comment by hilmanski** [comment]
Another customer requested this feature.   
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000044777?view=List)

**Comment by hilmanski** [comment]
Thank you, @zyc9012, for working on this.

I've reached out to the customer. 

@schaferyan could you confirm if the use case for the user you mentioned is also already covered? I haven't followed up with the other customer, as I'm not quite sure yet.

Here is an example searching with countryIn and countryDE I
https://serpapi.com/playground?q=LG+Phone&location=Maharashtra%2C+India&google_domain=google.co.in&gl=in&hl=en&cr=countryIN%7CcountryDE&tbm=nws&google_domain=google.co.in&newPara=votes+site+chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client

**Comment by schaferyan** [comment]
Thank you @hilmanski, I had trouble verifying this so I reached out to the customer and asked him to let us know if the solution covers his use case.
