### ISSUE TITLE
[Google Trends API] Support Searches without `q` parameter

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#464]
Search can be done without `q` parameter, only with:

- [ `cat` ](https://serpapi.com/google-trends-api#api-parameters-advanced-google-trends-parameters-cat)(category)
- [`date`](https://serpapi.com/google-trends-api#api-parameters-advanced-google-trends-parameters-date) (date range, defaults to past 12 months if not specified)
-  [`gprop`](https://serpapi.com/google-trends-api#api-parameters-advanced-google-trends-parameters-gprop) (property, defaults to Web Search)

Same as we did with YouTube Search API (#261)

Example Google Trends query without `q` parameter (category and date range): https://trends.google.com/trends/explore?cat=47&date=2019-01-01%202019-12-31:

![image](https://user-images.githubusercontent.com/78694043/199659871-90160b68-4ae7-4dc8-8188-068775daad57.png)

### Current Playground Behavior

![image](https://user-images.githubusercontent.com/78694043/199660140-9def09b9-a7d0-4790-8373-823ba340f901.png)

[Playground](https://serpapi.com/playground?engine=google_trends&cat=47&date=2019-01-01%25202019-12-31)

**Comment by schaferyan** [comment]
This was requested by a customer [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053407?view=List)

**Comment by satrajitrik** [comment]
Requesting this feature as well

**Comment by satrajitrik** [comment]
As a workaround, you can try `*` as search query with specific categories and dates. Yields decent results but it is not consistent with the Google trends results in website though

**Comment by hilmanski** [comment]
Another customer requested this feature.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000055279?view=List)

**Comment by marm123** [comment]
A potential Enterprise Customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000038698?view=List)

**Comment by hilmanski** [comment]
Another user requested this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061392?view=List)

**Comment by tanys123** [comment]
Using `*` in the `q` could be a temporary workaround.

**Actual Google Trends:**
<img width="1178" alt="Screenshot 2024-03-20 at 4 59 28 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/a48563ab-69e4-4ec8-8ddd-8b91f36dfd90">

<img width="1265" alt="Screenshot 2024-03-20 at 5 00 05 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/d269da70-117b-40c3-92dd-c7b06346fa7f">

<img width="1259" alt="Screenshot 2024-03-20 at 4 57 45 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/e1acc0dd-bd77-4a1f-944a-3b45d276010d">

[Playground](http://localhost:3000/playground?engine=google_trends&q=*&geo=US&data_type=RELATED_TOPICS&cat=25&date=today+1-m)

**Comment by martin-serpapi** [comment]
Another user requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061274?view=List)

**Comment by hilmanski** [comment]
Another user requested this:
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000063086?view=List)

**Comment by btaunt** [comment]
This feature has been added.

<img width="951" alt="Screenshot 2024-05-06 at 12 09 51 PM" src="https://github.com/serpapi/public-roadmap/assets/137819397/bd500b4e-5994-4a02-b494-99b35559dd82">


We now allow Google Trends searches to be made without a `q` parameter, so long as a category is selected. (**Note**: This only works for "Interest over time", "Related topics", and "Related queries" `data_type` parameters)

- [Playground Link](https://serpapi.com/playground?engine=google_trends&data_type=TIMESERIES&cat=319&no_cache=true&newPara=hl)
- [Documentation](https://serpapi.com/google-trends-api#api-examples-search-results-for-a-specified-category-with-no-query-provided)
