### ISSUE TITLE
[Google Search API] `rich_snippet` -> `top` parsed in `date`

### ISSUE THREAD

**Issue by BananaFig** [serpapi/public-roadmap#467]
Hi, 
I've noticed that recently (since 4'th on October) that some google results are returned with a date that is not actually a date.
for example:

"date":
![date worng2](https://user-images.githubusercontent.com/114980194/199731964-57f302ca-5c5f-4958-92be-80fdfa27aa6f.jpg)
![date worng](https://user-images.githubusercontent.com/114980194/199731992-40f924c6-faba-4463-b076-f2d714424595.jpg)

"by DE Georges-Abeyie 1983 Cited by 4"

I believe this is caused by scientific articles.

Would much appreciate adding a new field to indicate article citation, and not the "date" field.

Many thanks,
Maayan

**Comment by kagermanov27** [comment]
![date](https://user-images.githubusercontent.com/73674035/199745366-a6a47c3a-b587-4595-bf3a-840a8809619b.png)

[Playground](https://serpapi.com/playground?q=mousinhofilho%40gmail.com&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&num=100&device=desktop&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+client)
[Inspect](https://serpapi.com/searches/6363cd90ad7fa914b5b99803/inspect)

**Comment by kagermanov27** [comment]
As an addition to this issue, I have also opened another issue for another occurrence. You may follow it here:
https://github.com/serpapi/public-roadmap/issues/472
