### ISSUE TITLE
[Google Reverse Image Search] No `original` and `title` returned for `inline_images`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#470]
It appears that Google Reverse Image Search API no longer returns the `original` and `title` keys for `inline_images`.

**Current state:**
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/28161162/199949528-d7113597-943c-4c53-82cf-11f856a8e66b.png">

**Documentation:**
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/28161162/199949865-ea2f6ee5-3e09-44b2-ae0a-b324f64d8147.png">

<a href="https://serpapi.com/playground?engine=google_reverse_image&image_url=https%3A%2F%2Fi.imgur.com%2FHBrB8p0.png&device=desktop">Playground</a> | <a href="https://serpapi.com/searches/6364e6f35c105993003abf0c/inspect">Inspect</a>
<a href="https://serpapi.com/playground?engine=google_reverse_image&image_url=https%3A%2F%2Fwww.tastingtable.com%2Fimg%2Fgallery%2Fcoffee-brands-ranked-from-worst-to-best%2Fl-intro-1645231221.jpg&device=desktop">Playground</a> | <a href="https://serpapi.com/searches/6364e7f1ce87f8f467be9875/inspect">Inspect</a>
<a href="https://serpapi.com/playground?engine=google_reverse_image&image_url=https%3A%2F%2Fimage.cnbcfm.com%2Fapi%2Fv1%2Fimage%2F106991253-1639786378304-GettyImages-1185558312r.jpg%3Fv%3D1639786403&device=desktop">Playground</a> | <a href="https://serpapi.com/searches/6364e826e815af1c236a19af/inspect">Inspect</a>

**Comment by andypple83** [comment]
Google changed its search results. There is no original, title for some searches.

**Comment by andypple83** [comment]
Based on the comment above. I think we can close this issue. Thanks.
