### ISSUE TITLE
[Design] Some elements are misaligned vertically on Linux browsers

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#473]
![image](https://user-images.githubusercontent.com/73674035/200704274-6a93f1cc-aa44-4e01-b188-47c1b1f4e665.png)
P.S. I don't know if it's in all Linux Devices.

**Comment by ilyazub** [comment]
Please explain what buttons do you mean. I didn't understand it from the screenshot.

**Comment by hartator** [comment]
On Linux, we seem to have issues with vertical alignments of certain elements. I've noticed it on menu icons and on these labels as well.

Like if you zoom in on one of the labels in @kagermanov27's screenshot:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/307597/200700875-9da99fa2-0b8f-4896-ba9b-2a984238d609.png">

Compared to MacOS Chrome:

![image](https://user-images.githubusercontent.com/307597/200700952-62332d2e-3f47-48d9-aa82-9c4d531bf5ce.png)

**Comment by sebastianquek** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/577802/202628180-c9072bcd-5ed1-4990-a45e-350672f2d0b7.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/577802/202628200-29798c3a-6389-4b11-a0a2-dd1c555d34d5.png">

This has been resolved.

**Comment by ilyazub** [comment]
Btw, https://sizzy.co/ can be used for cross-browser development.

![image](https://user-images.githubusercontent.com/282605/202701855-c38d8096-2dc4-4fcd-8c1b-a0863f7cc44e.png)

It reminds me BrowserStack, that's used for testing.
