### ISSUE TITLE
[Google Search API] Timestamp links for videos are returned as hashed Google links instead of direct links.

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#475]
Links for videos with timestamps in `inline_videos` are returned as hashed Google links instead of direct links.

![image](https://user-images.githubusercontent.com/28161162/200298385-f409fd73-8257-46dd-b73b-3ab316f1a1a3.png)

<a href="https://serpapi.com/playground?q=cavapoo&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile">Playground</a> | <a href="https://serpapi.com/searches/6368e7009b64727497c44566/inspect">Inspect</a>

**Comment by marm123** [comment]
Might be connected to https://github.com/serpapi/public-roadmap/issues/474

**Comment by sebastianquek** [comment]
The links appear as actual YouTube links on desktop and sometimes appear as a fragment on mobile. The fragment opens a modal with the video embedded.
![image](https://user-images.githubusercontent.com/577802/200729469-f7cee241-a823-4086-9952-4146c5cd6c79.png)

[Desktop](https://serpapi.com/playground?q=cavapoo&location=Los+Angeles%2C+CA%2C+California%2C+United+States&gl=us&hl=en&device=desktop&highlight=inline_videos&newPara=highlight) vs [Mobile](https://serpapi.com/playground?q=cavapoo&location=Los+Angeles%2C+CA%2C+California%2C+United+States&gl=us&hl=en&device=mobile&highlight=inline_videos&newPara=highlight).

Loosely related to https://github.com/serpapi/public-roadmap/issues/402 though link extraction was not changed in that PR.

@aciddjus what are your thoughts on this? There is no apparent way to extract out the actual YouTube links for mobile searches.

**Comment by aciddjus** [comment]
This is only a problem on mobile if I'm correct?

----------------

We have the link to the video:

<img width="439" alt="image" src="https://user-images.githubusercontent.com/6929257/200839187-e36270fe-2ae8-4dc0-8046-c4d5c817e5b8.png">

What we now need is the timestamp in seconds

Take this link for example: `https://www.google.com#fpstate=ive&vld=cid:54ad9826,vid:VD_k95l_g4Y,st:5`

The timestamp is at the end: `st:5`. We just need to extract the number

---------------

Now we have the link and the timestamp

From there we can format the link to:

`inline_videos[index].link + &t= + timestamp + s`

https://m.youtube.com/watch?v=VD_k95l_g4Y&t=5s

**Comment by sebastianquek** [comment]
> This is only a problem on mobile if I'm correct?

From what I noticed, yes.

> From there we can format the link to:
> `inline_videos[index].link + &t= + timestamp + s`

This assumes that the video host relies on the `t` parameter to seek to the correct second though. Based on Google's docs [1][2], they only require that URLs are able to deep link to a point in the video based on the number of seconds from the start. Video hosts could possibly rely on a param (e.g. `?time=30`), a fragment `#t30` or a route `/30`.

[1] https://developers.google.com/search/blog/2021/07/new-way-key-moments
[2] https://developers.google.com/search/docs/appearance/structured-data/video#seek

**Comment by aciddjus** [comment]
Not sure I'm getting what you are saying. 

Checking links for seconds `st:5` and adding `&t=seconds` properly marks `key_moments` link.

In the documentation you linked I only see a reference to: `t=`

Can you add an example where this solution currently wouldn't work?

**Comment by sebastianquek** [comment]
The examples do mention the use of `t=`, but it's not a requirement. So sites other than YouTube could possibly rely on different approach instead.

e.g.
```
{
  "@context": "https://schema.org/",
  "@type": "VideoObject",
  "potentialAction" : {
    "@type": "SeekToAction",
    "target": "https://video.example.com/watch/videoID/{seconds}", // relies on a route
    "startOffset-input": "required name=seconds"
  }
)
```

**Comment by aciddjus** [comment]
Let's try to find an example with `key_moments` that isn't a YouTube video

**Comment by sebastianquek** [comment]
Here's an example with `key_moments` from a Dailymotion video: [Playground](https://serpapi.com/playground?q=pro+chef+site%3Adailymotion.com&gl=us&hl=en&device=mobile&highlight=inline_videos&newPara=highlight)

![image](https://user-images.githubusercontent.com/577802/201001735-566f2ee5-f60f-431b-8af6-2650474312a7.png)

Dailymotion uses `?start=`,
```
"potentialAction" :{
  "@type": "SeekToAction",
  "target":"https://www.dailymotion.com/video/x8b8yum?start={seek_to_second_number}",
  "startOffset-input": "required name=seek_to_second_number"
},
```
[Full schema](https://search.google.com/test/rich-results/result/r%2Fvideos?id=b2Po1TsEqy4DfBQV7qdyoA)

---

The links appear correctly for now, though Google may use the `#fpstate` approach for Dailymotion in future.

How about we do the following?
- If `#fpstate` exists in the link and YouTube is the source, create the link with `?t=seconds`
- Update tests to ensure the link does not point to a Google URL
- Add a test for Dailymotion to ensure the link does not point to a Google URL
  - This allows us to check in future if Google has decided to apply the modal approach for Dailymotion too
