### ISSUE TITLE
[Ebay Search API] Allow users to filter sold products

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#482]
We can allow users to search for sold items on eBay by adding an additional parameter. It can be extracted from the URL like in the screenshot below:

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/28161162/200515245-731f5d2a-c9fe-41b6-91ff-2bbaa3b6ef4e.png">

<a href="https://www.ebay.com/sch/i.html?_nkw=Playstation&_in_kw=1&_ex_kw=&_sacat=0&LH_Sold=1&_udlo=&_udhi=&_samilow=&_samihi=&_sadis=15&_stpos=&_sargn=-1%26saslc%3D1&_salic=1&_sop=12&_dmd=1&_ipg=60&_fsrp=1">eBay results</a>

**Comment by ethanwa** [comment]
Really hoping you guys can eventually get to this. I have a massive use case for it.
