### ISSUE TITLE
[Google Play Store API] Movies Pagination and see_more_token Feature Not Working

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#485]
Google Play Store API's pagination and see more token features are broken. 

The situation with Movies Pagination is that section see_more_token is not returned for movies, tv episodes and tv shows. This is the issue with U.S location. The returned `next_page_token` also does not work.

<img width="877" alt="play_store_next_page" src="https://user-images.githubusercontent.com/64849049/200606471-45401592-0f78-4ca8-970b-0582b1d3ec1d.png">

[The Playground](https://serpapi.com/playground?engine=google_play&q=good&gl=us&hl=en&store=movies&no_cache=true) | [The Inspect](https://serpapi.com/searches/636a7181aef26435d1d95198/inspect) | [Google Play Store](https://play.google.com/store/search?q=good&c=movies)

On the other hand on different locations, Brazil is the example here, Movies results are scroll loading instead of `see_more_token` way of horizontal scroll loading. While normal scroll loading may show up to 100 results on Play Store Brazil location, SerpApi returns less and next_page_token is not working.

<img width="883" alt="play_store_next_page_br" src="https://user-images.githubusercontent.com/64849049/200608414-57c752b0-e374-4a7c-84cc-c628e824889b.png">

[The Playround](https://serpapi.com/playground?engine=google_play&q=good&gl=br&hl=en&store=movies&no_cache=true) | [The Inspect](https://serpapi.com/searches/636a72a37690dc19aca8ba64/inspect) | [Play Store (needs to be visited via VPN)](https://play.google.com/store/search?q=good&c=movies)

The problem with Books search, it is similar to Movies search that desktop version can horizontally scroll load more products. This is not like pagination but more like section pagination as in how `see_more_token` token works. But `see_more_token` is not returned. The `next_page_token` is also not returned but I guess it is because this page only loads sections and paginates via `see_more_token`.

[The Playground](https://serpapi.com/playground?engine=google_play&q=good&gl=us&hl=en&store=books&no_cache=true) | [The Inspect](https://serpapi.com/searches/636a732d9c449df737b76b3a/inspect) | [Google Playstore](https://play.google.com/store/search?q=good&c=books)

<img width="892" alt="play_store_next_page_books" src="https://user-images.githubusercontent.com/64849049/200608454-398a820c-b20f-450f-9f74-90229a1d0592.png">

There is no change with the locations when it comes to books. The UI is similar for U.S and other countries.

**Comment by kagermanov27** [comment]
@aliayar 

---

>The situation with Movies Pagination is that section see_more_token is not returned for movies, tv episodes and tv shows. This is the issue with U.S location. The returned next_page_token also does not work.

I think I have found a way around for customers to get the data they want before we fix the issue.
If you take the `next_page_token` from the first page search of a movies search, and use that token with `store=apps` or `store=games` results in successful results:

[Inspect](https://serpapi.com/searches/636d6c39d036a7ff6318f5a5/inspect)
[Playground](https://serpapi.com/playground?engine=google_play&q=good&gl=us&hl=en&store=apps&next_page_token=Cgj6noGdAwIIFBAUGg-KAgwKBGdvb2QQBhgBIAE6DgoGCgRnb29kEAAYASAE&no_cache=true)

---

One other thing I am confused is that the difference between `see_more_token` and `next_page_token`.

The way we scrape `next_page_token` from first page results could be found here:
[Link to Responsible Part](https://github.com/serpapi/SerpApi/blob/7dea7e4f8bbb5bc61a01e7769723233ab16a5dd8/app/models/search/google_play/parser.rb#L61)

As you can see we are already extracting the first section's pagination link and serving it as `next_page_token`

Let me break down with an example:

[Example Playground Link](https://serpapi.com/playground?engine=google_play&q=good&gl=us&hl=en&store=movies&no_cache=true)
[Example Inspect Link](https://serpapi.com/searches/636d7120c573d5db6160e84f/inspect)
[Example HTML Link](https://serpapi.com/searches/636d7120c573d5db6160e84f.html)

As you can see the item we are searching is in 3 places and these are title blocks of each section:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/73674035/201213524-321c87c1-71b5-41a1-a526-53e131b028c1.png">

So the `next_page_token` we serve on first page results only serves the pagination for `Movies` in this case, and not `TV Shows` and `TV Episodes`. I have manually checked the `next_page_token` for these parts and they work with the method I described above.

@aciddjus , should refactor first page results to serve `next_page_token` in each `organic_results` section instead?

----


First part of this comment covers how to bypass `next_page_token` not working. We may even end up using this tweak to serve results. What do you think @aciddjus ?

When it comes to up to 100 results, I don't know if the recent changes on Google Play's endpoints still allow this. So

**Comment by kagermanov27** [comment]
>The problem with Books search, it is similar to Movies search that desktop version can horizontally scroll load more products. This is not like pagination but more like section pagination as in how see_more_token token works. But see_more_token is not returned. The next_page_token is also not returned but I guess it is because this page only loads sections and paginates via see_more_token.

@aliayar The reason we don't get `next_page_token` on books is because the pagination for the first section is returned and that section does not have any other results to paginate. I have checked the html and found the `next_page_token` for subsequent parts. They work with the bypass method I mentioned in the above comment.
<img width="818" alt="image" src="https://user-images.githubusercontent.com/73674035/201216236-a670a674-2239-476c-a603-17ca7897c10e.png">
