### ISSUE TITLE
[Google News Results API] `category` is not returned in JSON response

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#487]
According to our documentation, the `category` key can be returned for various news searches. However, it looks like either Google doesn't return this information anymore or the information is not parsed. If it's the former, we need to update the documentation to correctly reflect this change to not confuse customers.

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/28161162/200787784-4b32adf9-90e3-4cca-9799-b161d42fd8ef.png">
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/28161162/200788135-91e3160c-c12f-43e2-891e-b7758aacc80a.png">

<a href="https://serpapi.com/news-results">Documentation</a>
<a href="https://serpapi.com/playground?q=Trump+brushes+aside+environmental+concerns%2C+signs+2+executive&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=nws&device=desktop&newPara=stick+highlight">Playground</a> | <a href="https://serpapi.com/searches/636b6ddc37014c5e14cda7dc/inspect">Inspect</a>
<a href="https://serpapi.com/playground?q=Football&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=nws&device=desktop&newPara=stick+highlight">Playground</a> | <a href="https://serpapi.com/searches/636b6e639f55b3688afc0a25/inspect">Inspect</a>
<a href="https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=nws&device=desktop&newPara=stick+highlight">Playground</a> | <a href="https://serpapi.com/searches/636b67f1a74fe0a77cb28db3/inspect">Inspect</a>

**Comment by andypple83** [comment]
I can not find any search with `category` in google HTML results. There may be some old searches or some searches still return `categories`. I think the field `category` is optional and we can leave it there, don't need to change the document. 

Let me monitor this field, if it's disappeared for a few months, we can drop change the document.

**Comment by marm123** [comment]
Thanks, @andypple83 for looking into it! The reason I suspect that Google might not support the `category` anymore is that I found the news that was used for documentation and it no longer returns the `category` in our API. However, this could be due to the fact that Google might decategorize some news after they become irrelevant. Let's monitor as you suggested. I'm changing it to a freezer for now.

**Comment by andypple83** [comment]
Have  no `category` in google results until now. Keep monitoring.

**Comment by andypple83** [comment]
We didn't see any `category` in google results for more than 1 year. We've removed this field from our document.
