### ISSUE TITLE
[Google Trends API] Interest by Region not Returning any Results

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#489]
When Interest by Region option is chosen in Google Trends API, it does not return any results.

<img width="745" alt="trends_by_region" src="https://user-images.githubusercontent.com/64849049/201134709-72c03b61-1dc7-4918-b8df-9af2f9e2e879.png">

[The Playground](https://serpapi.com/playground?engine=google_trends&q=Justin+Bieber&geo=US&data_type=GEO_MAP_0&no_cache=true) | [The Inspect](https://serpapi.com/searches/636d16af11c88165a7274d25/inspect) | [Google Trends](https://trends.google.com/trends/explore?geo=US&q=justin%20bieber)

**Comment by marm123** [comment]
Another customer reporting the issue [102910000035433](https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000035433)

**Comment by marm123** [comment]
Another customer is asking for a fix:

[Intercom](https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000035678)

**Comment by marm123** [comment]
Another user reported inconsistency with Google Trends API searches.

[Intercom](https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000036084)

Two searches were performed with the same parameters within 3 minutes:

[API call - successful](https://serpapi.com/searches/63a0912614b245a0a0433c17/inspect)
[API call - empty results](https://serpapi.com/searches/63a091cb58762bfe6cd30790/inspect)

The biggest problem is that they are still counted as successful searches even thought they shouldn't be.

**Comment by robperkins4GH** [comment]
Hello -- @aliayar, I represent the development team of a potential enterprise customer who is deferring a subscription purchase based on the outcome of this issue. I just wanted to find out if there is a projected timeline for this ticket or if there is anything our team can do to support escalation and/or troubleshooting? We first reported the issue several months ago but have had a difficult time interpreting where it realistically stands on your internal roadmap.

If direct communication would be valuable, you can reach me at **rob.perkins@transcend.digital**. Thank you for any support or context you're able to provide here!

-Rob

**Comment by aciddjus** [comment]
Hi @robperkins4GH. I'm working on a fix and will open a PR by the end of the day. We expect to see it deployed to production sometime next week.
