### ISSUE TITLE
[Google Maps Review API] sort_by Highest Rating not Working Properly

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#49]
Google Maps Review API does not always sort by highest rated reviews first:

`data_id=0x3b080dafbed183bf:0x5951f316ba13a37e`

**The Playground**: https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x3b080dafbed183bf%3A0x5951f316ba13a37e&hl=en&sort_by=ratingHigh&no_cache=true

**The Inspect**: https://serpapi.com/searches/6229bd6f37b24ae465097169/inspect

![image](https://user-images.githubusercontent.com/64849049/157636854-5c41f8fe-a889-4856-91f7-b21660b50122.png)

**I have described it as not working properly because it outputs blank results when it does not and it tends to work for some places and not for others:**

The default on the Playground works for example:

`data_id=0x89c259a61c75684f:0x79d31adb123348d2`

**Playground**: https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x89c259a61c75684f%3A0x79d31adb123348d2&hl=en&sort_by=ratingHigh&no_cache=true

**Inspect**: https://serpapi.com/searches/6229c9c67690dcd0a6b5c112/inspect

`Another random example data_id=0x89c258ff0f7a7793:0xbedc0a7158ebea16`

**Playground**: https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x89c258ff0f7a7793%3A0xbedc0a7158ebea16&hl=en&sort_by=ratingHigh

This is working.

**next**.

**Comment by aciddjus** [comment]
> One of our users reached out to report that Google Maps Review API does not always sort by highest rated reviews first:
> 
> data_id=0x3b080dafbed183bf:0x5951f316ba13a37e
> 
> The Playground: https://serpapi.com/playground?engine=google_maps_reviews&data_id=0x3b080dafbed183bf%3A0x5951f316ba13a37e&hl=en&sort_by=ratingHigh&no_cache=true
> 
> The Inspect: https://serpapi.com/searches/6229bd6f37b24ae465097169/inspect
> 
> ![image](https://user-images.githubusercontent.com/64849049/157636854-5c41f8fe-a889-4856-91f7-b21660b50122.png)

There seems to be a problem with Google, and not on our side.

Here is the screenshot from the live search:

![Screenshot 2022-03-10 121432](https://user-images.githubusercontent.com/6929257/157651739-021c6450-90e3-4929-b69d-900b827f3c74.jpg)

You can check this yourself by following the next link and trying to sort by "Highest":

https://www.google.com/search?q=LuLu+International+Shopping+Malls+Private+Limited+Kochi&oq=LuLu+International+Shopping+Malls+Private+Limited+Kochi&aqs=chrome..69i57.215j0j7&sourceid=chrome&ie=UTF-8#lrd=0x3b080dafbed183bf:0x5951f316ba13a37e,1,,,

**Comment by aliayar** [comment]
I would never imagine Google Maps not working for a certain place with only certain filters.

Hats off to you @aciddjus. I will inform the user accordingly.
