### ISSUE TITLE
[Google Answer Box API] Incorrect and corrupted data returned in JSON response

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#493]
It appears that the `answer_box` data is incorrect. If you look closely, you can see that the `link` directs you to the Wikipedia page, while the original source for the data is different. The `snippet_highlighted_words` also returns all the information that is included in `hover_info` and additional reference to the Wikipedia page while it should only return highlighted words of the snippet

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/28161162/201364952-a1f80d5c-1426-4ee5-9305-7449ea8b5840.png">

<a href="https://serpapi.com/playground?q=Why+is+Queen+Consort+not+queen%3F&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop">Playground</a> | <a href="https://serpapi.com/searches/636e6174a5ad6d06a51258a6/inspect">Inspect</a>

**Comment by kagermanov27** [comment]
@marm123 I have split the issue into two for better integration. About This Result part is different part of the parser that requires another set of unit tests to be correctly implemented.
https://github.com/serpapi/public-roadmap/issues/508

**Comment by danieljannai21** [comment]
Hey, although the `link` field was corrected, the `title` field is still damaged :)

**Comment by kagermanov27** [comment]
@danieljannai21 I am personally grateful for your feedback. Let me work on a fix right away.

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/73674035/208370309-4d9e38e5-b890-4f86-8441-0a607c2fc603.png">

[Playground](https://serpapi.com/playground?q=Where+is+TRNC%3F&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq)
[Inspect](https://serpapi.com/searches/63a01125a5ad6da0a0d5d89e/inspect)
[Playground Mobile](https://serpapi.com/playground?q=Where+is+TRNC%3F&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq)
[Inspect Mobile](https://serpapi.com/searches/63a00cf77bea270f2af329a6/inspect)

**Comment by kagermanov27** [comment]
Closed by https://github.com/serpapi/SerpApi/pull/3440
