### ISSUE TITLE
[Reverse Image API] Google Reverse Image hasn't returned any results for this query.

### ISSUE THREAD

**Issue by chkn-io** [serpapi/public-roadmap#494]
Google reserve image display the same error even searching the default image included in the documentation.

**Comment by dimitryzub** [comment]
@chkn-io Yes, it seems that [Google Reverse Images has been replaced with Google Lens](https://twitter.com/ilyazub_/status/1591180737281396736). SerpApi engineers are currently looking into this problem. 

We'll update you once the issue is fixed 🙂 Sorry for the inconvenience.

**Comment by dimitryzub** [comment]
@chkn-io the [issue should be fixed now](https://github.com/serpapi/public-roadmap/issues/491), could you confirm on your end? 🙂
