### ISSUE TITLE
[Google Search API] Scrape filter pills from Google results

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#497]
Currently, we are not returning any data for information from filter pills. We can add separate sections in JSON response for each of them.

**1. Overview**
![image](https://user-images.githubusercontent.com/28161162/201654531-d20871fa-220e-4bd1-bcac-9a7f00bcbf5f.png)

**2. Songs**
![image](https://user-images.githubusercontent.com/28161162/201654569-cf0a3c0b-bc3e-4e7e-a140-9ba875a5ab49.png)

**3. Albums**
![image](https://user-images.githubusercontent.com/28161162/201654599-1af99ccb-951f-4262-8714-410f3553394a.png)

<a href="https://serpapi.com/playground?q=Jimmy+Hendrix&location=Austin%2C+TX%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true">Playground</a> | <a href="https://serpapi.com/searches/63722b4fd5a531290d881b7a/inspect">Inspect</a> | <a href="https://www.google.com/search?q=Jimmy+Hendrix&oq=Jimmy+Hendrix&uule=w+CAIQICIdQXVzdGluLFRYLFRleGFzLFVuaXRlZCBTdGF0ZXM&hl=en&gl=us&sourceid=chrome&ie=UTF-8#wptab=si:AC1wQDBMUUtGwa-ejEr0B5VqDiG2SAzY0P4H8jHZW0mA3k5Cx6orcBPjnQ5oJRfCZHqaSDZYI-7KLzoSRH8G9MVqttLb5ii_S6cS0bzfkU6dwf4ciOp1Ic8%3D">Google results</a>
<a href="https://serpapi.com/playground?q=Bob+Ross&location=Austin%2C+TX%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true">Playground</a> | <a href="https://serpapi.com/searches/63722df9629a01d87cf73a09/inspect">Inspect</a> | <a href="https://www.google.com/search?q=Bob+Ross&oq=Bob+Ross&uule=w+CAIQICIdQXVzdGluLFRYLFRleGFzLFVuaXRlZCBTdGF0ZXM&hl=en&gl=us&sourceid=chrome&ie=UTF-8">Google results</a>
<a href="https://serpapi.com/playground?q=Lionel+Messi&location=Austin%2C+TX%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true">Playground</a> | <a href="https://serpapi.com/searches/63722e2f36e6a9bf64a959a9/inspect">Inspect</a> | <a href="https://www.google.com/search?q=Lionel+Messi&oq=Lionel+Messi&uule=w+CAIQICIdQXVzdGluLFRYLFRleGFzLFVuaXRlZCBTdGF0ZXM&hl=en&gl=us&sourceid=chrome&ie=UTF-8">Google results</a>

**Comment by ilyazub** [comment]
Related to https://github.com/serpapi/public-roadmap/issues/266
