### ISSUE TITLE
[Google Answer Box API] No `answer_box` key returned for the specific type of `answer_box`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#499]
It looks like for the specific type of answer_box, no data is being returned:

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/28161162/201841629-41474f2c-e5e5-412e-ad58-6d521c81f4e6.png">

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/28161162/201841952-a7d5130b-20c7-4195-9e09-5a84042ea131.png">

<a href="https://serpapi.com/playground?q=20.4+miles%2F52+minutes+in+MPH&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop">Playground</a> | <a href="https://serpapi.com/searches/63732ccec573d594c18a2797/inspect">Inspect</a>

**Comment by ilyazub** [comment]
John Mueller (Google's Search Advocate) said it's a calculator result: https://mastodon.social/@johnmu/109358526247237572

![image](https://user-images.githubusercontent.com/282605/202704319-1bca9045-a9dd-44a4-82ad-b71599b99ed4.png)
