### ISSUE TITLE
[Google Jobs Listing API] Scrape Job highlights, Similar jobs and Company links. Fix `ratings` and `salaries` blocks

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#502]
Currently, we are not scraping **Job highlights** (we are only scraping Job descriptions), **Similar jobs** block, and **company links** (direct link page, more job results..., see web results...). It also appears that the `salaries` and `ratings` blocks are not returned even though they should be according to our documentation:

**1. Job highlights**
<img width="681" alt="image" src="https://user-images.githubusercontent.com/28161162/203010346-51404e3a-5f51-4dc7-a8f8-7119c9967b83.png">

**2. Similar jobs**
<img width="674" alt="image" src="https://user-images.githubusercontent.com/28161162/203010464-86c35a92-f84e-4297-9bf2-99aee507d123.png">

**3. Company links, issues with `salaries` and `ratings`**
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/28161162/203009102-d6c76a88-47e7-4219-860c-be47358c94ca.png">

<a href="https://serpapi.com/google-jobs-api">Documentation - Jobs API</a><a href="https://serpapi.com/google-jobs-listing-api">Documentation - Jobs Listing API</a>
<a href="https://serpapi.com/playground?engine=google_jobs&q=Developer&location=United+States&gl=us&hl=en&no_cache=true">Playground - Jobs API</a> | <a href="https://serpapi.com/searches/637b3b5b5b54ef9439b438b8/inspect">Inspect - Jobs API</a> | <a href="https://www.google.com/search?q=Developer&ibp=htl;jobs&uule=w+CAIQICINVW5pdGVkIFN0YXRlcw&hl=en&gl=us">Google direct link</a>
<a href="https://serpapi.com/playground?engine=google_jobs_listing&q=eyJqb2JfdGl0bGUiOiJBbmRyb2lkIERldmVsb3BlciIsImh0aWRvY2lkIjoiMFZsdHFIdmZ5Q29BQUFBQUFBQUFBQT09IiwidXVsZSI6IncrQ0FJUUlDSU5WVzVwZEdWa0lGTjBZWFJsY3ciLCJnbCI6InVzIiwiaGwiOiJlbiIsImZjIjoiRXZjQkNyY0JRVUYwVm14aVEyNXBUMnhCWDNKRmRrRXdaRUZvY0d4S1prOXBjbWswVmpGU1JHNWZXbmN4Ymw5SVdDMDFhbUZCWkZwcFoyeGpXR3d3ZUZwemRUTlVTVVJUUm5relpXcFROemhFVlVWelVESk5YMGN4VVVSMVdscE1XVE5yTTB4R2MwOU1ha1pQU0ZrNU5FWkxZVUpJV1VkaE5YTXRjSE5YTXpsNlVVTkZTMmR0WTBsdmFsY3RVVmRyU0VGeWFXVmtjVGN0TURGSGRqTnRhemRyYWxaVFowODBORWhSYzFGdlIwSXRNVlZwZGs0dFVsQjRPRWhORWhkWWFuUTNXVGhRY0Vwa2VYWnhkSE5RTlZsUFZtdEJPQm9pUVVSVmVVVkhaVWhaVDNOTVpVbEdZemh1ZEhZNWMzcDFSRlJPVFdsbWRtNUladyIsImZjdiI6IjMiLCJmY19pZCI6ImZjXzEiLCJhcHBseV9saW5rIjp7InRpdGxlIjoiLm5GZzJlYntmb250LXdlaWdodDo1MDB9LkJpNkRkY3tmb250LXdlaWdodDo1MDB9QXBwbHkgb24gSi4gSG9jayBQb29sIFBsYXN0ZXJpbmciLCJsaW5rIjoiaHR0cHM6Ly9qaG9ja3Bvb2xzLmNvbS93b3Jrc3ByZWFkL2pvYi9hbmRyb2lkLWRldmVsb3Blci1hdC1jb21wdW5uZWwtaW5jLXJlbW90ZS1iNzg5ZDVlN2JmNmU4NmUxamt0azFnaTNrbTQ4MmloM2Q4MDE%2FdXRtX2NhbXBhaWduPWdvb2dsZV9qb2JzX2FwcGx5XHUwMDI2dXRtX3NvdXJjZT1nb29nbGVfam9ic19hcHBseVx1MDAyNnV0bV9tZWRpdW09b3JnYW5pYyJ9fQ%3D%3D">Playground - Jobs Lising API</a> | <a href="637b3b9f37014cf3c477c0d5">Inspect - Jobs Listing API</a> | <a href="https://www.google.com/search?q=Android+Developer&ibp=htl;jobs&uule=w+CAIQICINVW5pdGVkIFN0YXRlcw#htidocid=0VltqHvfyCoAAAAAAAAAAA==">Google direct link</a>

**Comment by andypple83** [comment]
ref https://github.com/serpapi/public-roadmap/issues/370
