### ISSUE TITLE
[Google Search API | Related Questions API] next_page_token not Returning More Questions with Related Questions API

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#510]
For some of the questions, `next_page_token` does not return more questions with Related Questions API.

[The Playground for Google Search API](https://serpapi.com/playground?q=how+make+soup&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop) | [The Playground for Related Questions API](https://serpapi.com/playground?engine=google_related_questions&next_page_token=eyJvbnMiOiI4ODYiLCJmYyI6IkVzd0NDb3dDUVVGMFZteGlRVWs1UVhsWVZHeFJXVkZoUkRCdFlYcDVaM0JxTWtWMFJUbFNjMFJFUjB4b2VXZzNXRVZYTjJRNE5XWTNhbU5NUVhOdFYzTXlSMEZ3Ums5ckxXZFVVMU5uV1Zab1p6RnBkMDVsVERaUGVYVlVXbmQ0YVZoNFdsRmZNVU5zV25WVlN6UkpVR1JvVUVwbGVUTXdiWGh2TjFoRFEwOUVaSGgyV2xwYWR6SlNZVlZSTWtoUWVIcEhkVXRwYWtoVk1ERXRaSG8zWW5GaGR6RklkRUY1UTBOUlVrVmtTRUZSYlRKWFptWnVUWFo1TVc1UFZ6QXdkakp4V21Wck5HZzBWMEV0TWt4TlVYWlVTeko0UWtRNE9WbGxWbXROWHpCVlRGQlNNMkYyTW1kNU5FZGFaVFozWm10T2JUVmtNbTF2VkhORlkySkNjRlo0WDNaaldGTjJPRmN4T1RRdFNtazRPUklYV1hCS1gxazFURTVITm1KYU1YTlJVR2M0Y1U0dFFXc2FJa0ZFVlhsRlIyVmxjREJZUzI1bGMwdGpjM1E1V2poVVdqQndaV0ptVVZKblVrRSIsImZjdiI6IjMiLCJlaSI6IllwSl9ZNUxORzZiWjFzUVBnOHFOLUFrIiwicWMiOiJDZzFvYjNjZ2JXRnJaU0J6YjNWd0VBQjlzaDRkUHciLCJxdWVzdGlvbiI6IldoYXQgYXJlIHRoZSBpbmdyZWRpZW50cyB1c2VkIGluIG1ha2luZyBzb3Vwcz8iLCJsayI6ImM1UFNMYzlJTEZGSUxFcFZLTWxJVmNqTVN5OUtUY2xNelNzcFZpZ3RUazBCQ2lqa0ptWURoUldLODBzTGlnRSIsImJzIjoiYy1OUzUxSUt6MGdzVVVnc1NsVW95VWhWS0M1SkxTaFd5RTlUeUUzTXpzeExWeWpPTHkyd2xfZ2x5bVhNcFllaUVDaFpsSnFTbVpwWFVxeFFXcHlhQWhSQTFsTnNMX0VraTB1SlN4WkZrN0ZDU1dWQkt0aDhpTUYzTExpMHVkVEFhaEFHZ3N3QktnS3BVQ2hKQkxwSUlUMF9QOFZlWXBXOUFDTUEifQ%3D%3D) | [Google](https://www.google.com/search?q=how+make+soup)
[The Inspect for Google Search API](https://serpapi.com/searches/637f925dc9990354fa606d78/inspect) | No [Inspect for for Related Questions API](https://serpapi.com/playground?engine=google_related_questions&next_page_token=eyJvbnMiOiI4ODYiLCJmYyI6IkVzd0NDb3dDUVVGMFZteGlRVWs1UVhsWVZHeFJXVkZoUkRCdFlYcDVaM0JxTWtWMFJUbFNjMFJFUjB4b2VXZzNXRVZYTjJRNE5XWTNhbU5NUVhOdFYzTXlSMEZ3Ums5ckxXZFVVMU5uV1Zab1p6RnBkMDVsVERaUGVYVlVXbmQ0YVZoNFdsRmZNVU5zV25WVlN6UkpVR1JvVUVwbGVUTXdiWGh2TjFoRFEwOUVaSGgyV2xwYWR6SlNZVlZSTWtoUWVIcEhkVXRwYWtoVk1ERXRaSG8zWW5GaGR6RklkRUY1UTBOUlVrVmtTRUZSYlRKWFptWnVUWFo1TVc1UFZ6QXdkakp4V21Wck5HZzBWMEV0TWt4TlVYWlVTeko0UWtRNE9WbGxWbXROWHpCVlRGQlNNMkYyTW1kNU5FZGFaVFozWm10T2JUVmtNbTF2VkhORlkySkNjRlo0WDNaaldGTjJPRmN4T1RRdFNtazRPUklYV1hCS1gxazFURTVITm1KYU1YTlJVR2M0Y1U0dFFXc2FJa0ZFVlhsRlIyVmxjREJZUzI1bGMwdGpjM1E1V2poVVdqQndaV0ptVVZKblVrRSIsImZjdiI6IjMiLCJlaSI6IllwSl9ZNUxORzZiWjFzUVBnOHFOLUFrIiwicWMiOiJDZzFvYjNjZ2JXRnJaU0J6YjNWd0VBQjlzaDRkUHciLCJxdWVzdGlvbiI6IldoYXQgYXJlIHRoZSBpbmdyZWRpZW50cyB1c2VkIGluIG1ha2luZyBzb3Vwcz8iLCJsayI6ImM1UFNMYzlJTEZGSUxFcFZLTWxJVmNqTVN5OUtUY2xNelNzcFZpZ3RUazBCQ2lqa0ptWURoUldLODBzTGlnRSIsImJzIjoiYy1OUzUxSUt6MGdzVVVnc1NsVW95VWhWS0M1SkxTaFd5RTlUeUUzTXpzeExWeWpPTHkyd2xfZ2x5bVhNcFllaUVDaFpsSnFTbVpwWFVxeFFXcHlhQWhSQTFsTnNMX0VraTB1SlN4WkZrN0ZDU1dWQkt0aDhpTUYzTExpMHVkVEFhaEFHZ3N3QktnS3BVQ2hKQkxwSUlUMF9QOFZlWXBXOUFDTUEifQ%3D%3D) due to error.

Google Search API:

![related_questions](https://user-images.githubusercontent.com/64849049/203826443-35d27251-730a-4153-986a-f446411bcc0c.png)

Related Questions API:
![image](https://user-images.githubusercontent.com/64849049/203826313-540ab169-bfdc-4f7b-b1af-83c15b67b5e9.png)

**Comment by kagermanov27** [comment]
Just to clarify confusion:
Unrelated to https://github.com/serpapi/SerpApi/pull/3378
Just checked if relevant

**Comment by uysalibov** [comment]
@aliayar That was a my issue. When will fix this problem?

**Comment by aliayar** [comment]
Hi @uysalibov 

Can you please share an example with us?

**Comment by uysalibov** [comment]
@aliayar 
You can test with it "how make soup". SERP API hasn't returned any query for related question endpoint

**Comment by aliayar** [comment]
Thank you for the answer @uysalibov

It seems that this problem is more complicated than we initially expected. We will keep you updated here but I won't be able to share a timeline regarding when this will be resolved.

**Comment by kagermanov27** [comment]
@uysalibov I have created a Pull Request for it. It will be reviewed, and then implemented in a short time. I am grateful for your understanding.

**Comment by kagermanov27** [comment]
@uysalibov The problem should be resolved now. I am grateful for your patience and understanding.

**Comment by uysalibov** [comment]
It worked. Thanks
