### ISSUE TITLE
[Google Search API] Scrape `organic_results` in Mobile search in addition to calculator `answer_box`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#518]
Currently, we are only extracting results as they are initially presented by Google for Mobile search. The problem is that initial queries may return `answer_box` only and have `organic_results` hidden behind **Show all results** button

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/28161162/204511803-8587de21-ee19-438c-82f9-92cd0027c540.png">

<img width="904" alt="image" src="https://user-images.githubusercontent.com/28161162/204511999-f931615a-80b2-42f2-a22b-a689d0db774e.png">

<a href="https://serpapi.com/playground?q=18%2F6&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile">Playground</a> | <a href="https://serpapi.com/searches/6385e5762f542e463b804e5e/inspect">Inspect</a>
<a href="https://serpapi.com/playground?q=250%2F50&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile">Playground</a> | <a href="https://serpapi.com/searches/6385e69eaf63044b24b17a5e/inspect">Inspect</a>

**Comment by ilyazub** [comment]
Organic results are available after a redirect to the same URL with `aomd=1` parameter which we don't support yet.

|Without|With `aomd=1`|
|-|-|
|`https://www.google.com/search?q=250%2F50`|`https://www.google.com/search?q=250%2F50&aomd=1`|
|![image](https://user-images.githubusercontent.com/282605/204654527-7bc8ca8d-d52c-49c8-be40-387ef84d205a.png)|![image](https://user-images.githubusercontent.com/282605/204654464-a9f57cba-c1d0-4175-b6b4-2ea527fcd10c.png)|

**Comment by zyc9012** [comment]
Google doesn't seem to return this kind of layout anymore.
