### ISSUE TITLE
[Google Maps Places API] Parse Multiple Businesses from the Same Address Directory

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#521]
If a building has more than one business in it, Google Maps API and Maps Places API provides a directory for those businesses in the building. Google Maps API and Google Places API currently does not return those. This feature was requested first in Mar 5, 2021.

This can be seen in the screenshot and examples below:

![maps_directory](https://user-images.githubusercontent.com/64849049/204545784-7c101b7b-6cb8-4bf7-9c96-ea6cfab7d215.png)

[The Playground](https://serpapi.com/playground?engine=google_maps&ll=%4043.5245648%2C-5.6788437%2C17z&hl=en&data=!3m2!4b1!5s0xd367cf2341cf203%3A0xff57ba95c21017b6!4m5!3m4!1s0xd367ce519ff853f%3A0xaf5915a8666cb232!8m2!3d43.5245648!4d-5.6788437&type=place) | [The Inspect](https://serpapi.com/searches/63860c13d3aba2470c7480e2/inspect) | [Google Maps](https://www.google.com/maps/place/El+Corte+Ingl%C3%A9s/@43.5245648,-5.6788437,17z/data=!3m2!4b1!5s0xd367cf2341cf203:0xff57ba95c21017b6!4m5!3m4!1s0xd367ce519ff853f:0xaf5915a8666cb232!8m2!3d43.5245648!4d-5.6788437)

**Comment by aciddjus** [comment]
Looks like we can put this in the same category as https://github.com/serpapi/public-roadmap/issues/522
