### ISSUE TITLE
[Google Product API] Support People Also Bought Block

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#533]
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/73674035/205258729-9c7947b6-6a8d-44bf-8691-a276da23874e.png">

[Playground](https://serpapi.com/playground?engine=google_product&product_id=4887235756540435899&gl=us&hl=en&device=desktop&no_cache=true)
[Inspect](https://serpapi.com/searches/6389bfe0e4a23d66ffea2eda/inspect)

**Comment by aciddjus** [comment]
Closing this as I wasn't able to replicate the layout.
