### ISSUE TITLE
[Google Search API] (Preventive & Pro Active Bug Report) Endless Scrolling Added to Google Search

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#537]
Google started rolling out the endless scrolling for Google Search Results page.

https://searchengineland.com/google-brings-continuous-scroll-to-desktop-search-results-390004

So, when you search for a term, you get the page below from SerpApi:

![endless_scroll](https://user-images.githubusercontent.com/64849049/205928598-89de7d30-ddb5-498a-8eb9-b69a8979e18a.png)

[The Inspect](https://serpapi.com/searches/638f45c8797ac61e313c162a/inspect) | [The Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+TX%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true) | [Google](https://www.google.com/search?q=Coffee)

However, when you add `start=10`, it still moves to the second page:

[The Playground](https://serpapi.com/search.html?engine=google&q=Coffee&location=Austin%2C+Texas%2C+United+States&google_domain=google.com&gl=us&hl=en&device=desktop&api_key=3889a60517fb8eab08bbedf57cdaa89147208f4538e5b4857681a844991fc771) | [The Inspect](https://serpapi.com/searches/638f4b0caf5af12d968eaf24/inspect)

Eventually, we may end up with a bug in case Google decides to drop support for the pagination.

**Comment by marm123** [comment]
It appears that Google rolled out endless scrolling for the US permanently. However, I didn't notice that our services are affected by that change, but it's better to keep an eye on it. I've checked queries for multiple countries and only noticed that for the USA.

[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) vs [Google direct link](https://www.google.com/search?q=Coffee&oq=Coffee&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM&gl=us&sourceid=chrome&ie=UTF-8)

If we go to the 2nd page of results in our Playground, they match with results received after scrolling first ten results in a direct Google search:

[**2nd page from our Playground:**](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&start=10)
<img width="411" alt="image" src="https://user-images.githubusercontent.com/28161162/212922550-523fe0f3-c433-4ce2-a3e4-d59e291aa03c.png">

**Results from Google after scrolling the first ten results:**
<img width="668" alt="image" src="https://user-images.githubusercontent.com/28161162/212922946-5413943f-0745-4fe9-a2d9-d1f71b0806eb.png">

It is also worth noting that you get an endless scroll if you start from the 1st page on Google. If you copy the link from our Playground and start from the 2nd page, you will still get regular pagination at the bottom of your search results:

[**The 2nd page of Google results:**
](https://www.google.com/search?q=Coffee&oq=Coffee&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM&gl=us&start=10&sourceid=chrome&ie=UTF-8)
<img width="572" alt="image" src="https://user-images.githubusercontent.com/28161162/212923653-0989c2cb-0205-435a-912e-c19d94a4640d.png">

Our services are not yet impacted in a meaningful way (from what I was able to check), but we should surely be aware of the changes that Google implements.

[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/63c6a7f5a3f4ef895899e637/inspect) | [Google link](https://www.google.com/search?q=Coffee&oq=Coffee&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM&gl=us&sourceid=chrome&ie=UTF-8)

**Comment by aciddjus** [comment]
Closing this as it's not an issue.
