### ISSUE TITLE
[Google Search API] Support pixel ranking for search results

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#541]
Pixel ranking refers to the number of pixels between the website's position on the Search Engine Results Page and the top of the page. We can work on that as it was recently requested.

![image](https://user-images.githubusercontent.com/28161162/207288459-f6465c1b-4535-45d5-ba65-09f5a6554635.png)

Here are a couple of more materials to check the details:
[What is Pixel Ranking? Myposeo’s New SEO Ranking KPI](https://en.myposeo.com/blog/is-your-seo-ranking-accurate-enough-introducing-pixel-ranking/)
[Pixel Position and Visibility Distribution – Essential Metrics for Modern Rank Tracking](https://www.advancedwebranking.com/blog/pixel-ranking/)

**Comment by fadupla** [comment]
Hello @marm123 and @aciddjus, Do you by any chance have visibility on this addition please ? Thanks a lot ! Have a good day

**Comment by ilyazub** [comment]
Related to https://github.com/serpapi/public-roadmap/issues/113, which is work-in-progress.

**Comment by tanys123** [comment]
Duplicated https://github.com/serpapi/public-roadmap/issues/113
