### ISSUE TITLE
[Google Play Store API] Missing `see_more_token` in the `chart_options`

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#544]
`see_more_token` is missing in the `chart_options` key. Current output that we have:

```json
"chart_options":[
   {
      "text":"Top free",
      "value":"topselling_free"
   },
   {
      "text":"Top grossing",
      "value":"topgrossing"
   },
   {
      "text":"Top paid",
      "value":"topselling_paid"
   }
]
```

[Per docs, it should be there](https://serpapi.com/google-play-api#api-parameters-advanced-google-play-parameters-see-more-token):

![image](https://user-images.githubusercontent.com/78694043/208612071-d5957b89-ddd9-4f6b-9f56-34e047b1b378.png)

[Playgrond](https://serpapi.com/playground?engine=google_play&gl=us&hl=en&store=apps) | [Inspect](https://serpapi.com/searches/63a166b83824277cc89e700a/inspect)

**Comment by kagermanov27** [comment]
Already dealt with in https://github.com/serpapi/SerpApi/pull/3364

**Comment by aciddjus** [comment]
Closing this as resolved.
