### ISSUE TITLE
[Google Maps API] Allow users to search by `place_id`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#545]
Currently, we only allow searching for `type=place` using the `data` parameter, which requires `data_id`. However, there is an option to get the specific place results using `place_id`:

**`place_id` extracted in Google Maps API call**
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/28161162/208612307-d33bf6cb-a0f5-425c-9086-649d1120cf88.png">

**`place_id` used as a URL parameter for place search**
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/28161162/208611914-00ba5cd1-0c2a-4c87-826e-e60053da3b62.png">

[Playground](https://serpapi.com/playground?engine=google_maps&q=Coffee&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&type=search) | [Inspect](https://serpapi.com/searches/63a16584f716ee8723ac1df8/inspect) | [Google link using place_id](https://www.google.com/maps/place/?q=place_id:ChIJG3lW5ZhZwokRbbE3bvRnzb0)

**Comment by aliayar** [comment]
This will be celebrated for some of our users as we ask them to collect data_id first. Highly wanted feature.
