### ISSUE TITLE
[Google Trends API] Support "search topics" and "search queries"

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#546]
Currently, we don't support search topics and search queries:

![image](https://user-images.githubusercontent.com/78694043/208637221-987c1ac2-9572-454d-b84e-8e028c10b5ea.png)

Current  results:

![image](https://user-images.githubusercontent.com/78694043/208637364-46a4d12a-b571-4563-892d-83fb671352d0.png)

**Comment by aciddjus** [comment]
Thanks, @dimitryzub. Can you post a link to a live Google search where we can see these results?
I'm just getting `Related topics` and `Related queries`. I'm also wondering what is the difference between the two. 🤔

**Comment by aciddjus** [comment]
These results appear when the query is not provided: [Google Trends link
](https://trends.google.com/trends/explore?date=today%203-m&hl=en-US)
<img width="1182" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/3f5e3261-249e-4270-915f-1e1f0ca3cc86">

----------

They are the same as `Related topics` and `Related queries`

<img width="2369" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/9fe0f700-d2ef-4595-b3c9-6384c341e433">

[Playground](https://serpapi.com/playground?engine=google_trends&data_type=RELATED_TOPICS&cat=0&date=today%25203-m&no_cache=true)
