### ISSUE TITLE
[Google Play Product API] Scraping App Version and Other Details 

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#547]
Play Store API can scrape the data and the description which are shown with a modal when I click the arrow next to "**About This (Game|App) ->**" text.

App Page Arrow Link:

![app_version_1](https://user-images.githubusercontent.com/64849049/208925255-b8d96adb-616e-4e7b-bd24-78cee0c69eb7.png)

The Modal and the Data:

![app_version_2](https://user-images.githubusercontent.com/64849049/208925405-7cad4470-3fdd-460f-957d-06ae3f0fa353.png)

[The Playground](https://serpapi.com/playground?engine=google_play_product&product_id=com.IvanKovalov.quadline.android&gl=us&store=apps) | [The Inspect](https://serpapi.com/searches/63a31491d3aba2dba5d20ecf/inspect) | [Google Play Store](https://play.google.com/store/apps/details?id=com.IvanKovalov.quadline.android&hl=en&gl=US)

**Comment by aliayar** [comment]
Another user requested this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000048161?view=List)

**Comment by Krugloff** [comment]
We've now parsed the details for both games and apps.

<img width="1454" alt="image" src="https://github.com/user-attachments/assets/e6f886f4-8053-46ac-af7f-f357567b8c00">
