### ISSUE TITLE
[Google About This Results API] Returned data is inconsistent with what Google provides

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#551]
It appears that not all the About The Source results are parsed in JSON response:

Results from our API (only 2):
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/28161162/209874054-d75c5377-d2a3-44a5-8434-b207d47053d6.png">

Results from Google (10):
<img width="891" alt="image" src="https://user-images.githubusercontent.com/28161162/209874250-92072164-f2e0-4290-b7cd-1cdeb3e48d82.png">

[Playground - Google Search API](https://serpapi.com/playground?q=casinoscout.nl&location=Government+of+Amsterdam%2C+North+Holland%2C+Netherlands&google_domain=google.nl&gl=nl&hl=nl&device=desktop)
[Inspect - Google Search API](https://serpapi.com/searches/63acaffb607393758a7e04fa/inspect)
[Google link from Google Search API](https://www.google.nl/search?q=About+https://casinoscout.nl/&tbm=ilp&ilps=ADNMCi1gse719pLSI_w6hEMGvwP8H1XqdA)
[About this result JSON from Google Search API](https://serpapi.com/search.json?engine=google_about_this_result&ilps=ADNMCi1gse719pLSI_w6hEMGvwP8H1XqdA&q=About+https%3A%2F%2Fcasinoscout.nl%2F)

[Playground - Google About This Result API](https://serpapi.com/playground?engine=google_about_this_result&q=About+https%3A%2F%2Fcasinoscout.nl%2F&ilps=ADNMCi1gse719pLSI_w6hEMGvwP8H1XqdA&no_cache=true)
[Inspect - Google About This Result API](https://serpapi.com/searches/63acb46f2348845028e5ecd9/inspect)

**Comment by aciddjus** [comment]
It looks like it's domain related. After adding the ability to change the domain, we can get all the results:

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/6929257/209936187-e265063e-abc5-444f-b667-35b3177d8bb7.png">
