### ISSUE TITLE
[Google News API] Scrape direct link to thumbnail from News search

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#553]
Currently, instead of the direct link to the thumbnail on News search, we return the SerpApi link for it. I'm unsure if extracting the direct link is possible, but looking at our documentation, this was the case in the past.

**Current state**
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/28161162/210718364-149b44ab-0052-4c41-9ff0-a9966b86f1a3.png">

**Documentation**
<img width="861" alt="image" src="https://user-images.githubusercontent.com/28161162/210718576-c3d5bdfe-5d36-4e43-b5fa-d513101c3f2b.png">

[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=nws) | [Inspect](https://serpapi.com/searches/63b663402ff4210e92e2211c/inspect) | [Google link](https://www.google.com/search?q=Coffee&oq=Coffee&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM&hl=en&gl=us&tbm=nws&sourceid=chrome&ie=UTF-8) | [Documentation](https://serpapi.com/news-results)

**Comment by btaunt** [comment]
I believe this ticket was addressed with the changes made in https://github.com/serpapi/SerpApi/commit/105527382e059e6cc12026278fe742c4c61e7353

The updated documentation that reflects the `https://serpapi.com/searches...` URL structure can be seen:
https://serpapi.com/news-results

Closing issue for now.
