### ISSUE TITLE
[Google Trends API] Returning Empty Results Most of the Time

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#556]
Google Trends API returns empty results most of the time with search. 

However, I am not sure if Google Trends itself is working properly. Please refer to Google Trends link and additional screenshots to see it yourself.

![image](https://user-images.githubusercontent.com/64849049/211010210-4ab17106-4d5e-4267-b82c-f7fa5877786a.png)

[The Playground](https://serpapi.com/playground?engine=google_trends&q=Coffee&geo=US&no_cache=true) | [The Inspect](https://serpapi.com/searches/63b80f13aa6c954a51ad6c87/inspect) | [Google Trends](https://trends.google.com/trends/explore?geo=US&q=coffee)

Screenshots from the Google Trends itself:

Homepage:
![image](https://user-images.githubusercontent.com/64849049/211010663-a65f6317-695b-475d-b930-9556fc55f313.png)

Search:
![image](https://user-images.githubusercontent.com/64849049/211010825-8bff1618-73af-4d70-91ce-dee36a13628c.png)

**Comment by dimitryzub** [comment]
Related:
- https://github.com/serpapi/public-roadmap/issues/790

Possibly related:
- https://github.com/serpapi/public-roadmap/issues/561

**Comment by aliayar** [comment]
Currently, no data is returned from Google Trends. I will bump the tag to "urgent".

**Comment by ilyazub** [comment]
Hot-fixed in https://github.com/serpapi/SerpApi/pull/3746.

**Comment by schaferyan** [comment]
A [customer](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040109?view=List) is experiencing empty results from Google Trends again. Feel free to move to a new issue if applicable. Here are some `search_id`s they provided:

- [6443d44111c88172bd142a78](https://serpapi.com/searches/6443d44111c88172bd142a78/inspect)
- [64412d8333b23694b47de37c](https://serpapi.com/searches/64412d8333b23694b47de37c/inspect)
- [644128311c450a6adf473fd7](https://serpapi.com/searches/644128311c450a6adf473fd7/inspect)
- [6440ff052fe3024f156ac5de](https://serpapi.com/searches/6440ff052fe3024f156ac5de/inspect)
