### ISSUE TITLE
[Yahoo Shopping API] Incorrect `serpapi_pagination.next` URL when using page parameter

### ISSUE THREAD

**Issue by sebastianquek** [serpapi/public-roadmap#562]
# Problem
When setting the `page` parameter, the returned `serpapi_pagination.next` URL is incorrect. It somehow skips a page.

# Steps to replicate
## 1. Call Yahoo Shopping with  `page=1`
https://serpapi.com/playground?engine=yahoo_shopping&p=Coffee&min_price=3000&limit=8&page=1
```
"serpapi_pagination": {
  "current": 1,
  "next": "https://serpapi.com/search.json?device=desktop&engine=yahoo_shopping&limit=8&min_price=3000&p=Coffee&page=2&start=8",
  "other_pages": {
    "2": "https://serpapi.com/search.json?device=desktop&engine=yahoo_shopping&limit=8&min_price=3000&p=Coffee&page=2&start=8",
    "3": "https://serpapi.com/search.json?device=desktop&engine=yahoo_shopping&limit=8&min_price=3000&p=Coffee&page=3&start=16",
    "4": "https://serpapi.com/search.json?device=desktop&engine=yahoo_shopping&limit=8&min_price=3000&p=Coffee&page=4&start=24",
    "5": "https://serpapi.com/search.json?device=desktop&engine=yahoo_shopping&limit=8&min_price=3000&p=Coffee&page=5&start=32"
  }
}
```
![image](https://user-images.githubusercontent.com/577802/211737983-55403018-66b3-4413-a485-d3c7b8357d30.png)

## 2. Follow the `next` link
Based on `serpapi_pagination.next`, page 2 uses the following params: `limit=8&page=2&start=8`
https://serpapi.com/playground?engine=yahoo_shopping&p=Coffee&min_price=3000&start=8&limit=8&page=2

![image](https://user-images.githubusercontent.com/577802/211738161-f2c7d9c4-211e-45bd-863c-c216f4dda847.png)

However, the above is actually page 3. If `start` is not set, then the returned results are different:
https://serpapi.com/playground?engine=yahoo_shopping&p=Coffee&min_price=3000&limit=8&page=2

![image](https://user-images.githubusercontent.com/577802/211738647-f99e3e06-5ecc-4a21-9208-430e24dfbbe4.png)

This is verified by using `limit=24`:
https://serpapi.com/playground?engine=yahoo_shopping&p=Coffee&min_price=3000&limit=24

![image](https://user-images.githubusercontent.com/577802/211740041-49a05638-bdcf-4817-8f76-78069d892f89.png)

**Comment by aciddjus** [comment]
Closing this issue as I wasn't able to replicate it. Pagination works as expected.

**Comment by juncas2205-debug** [comment]
https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping

**Comment by Gsosa2703** [comment]
Hi @juncas2205-debug, 

Could you please share more details about your comment? We would be happy to assist.

**Comment by juncas2205-debug** [comment]
@Gsosa2703 Sorry for not understanding, I don't understand English very well. But I have a proposal for whoever can fix the APIs and bugs that were installed and recover my credentials. I will reward them with... A doc who...

**Comment by juncas2205-debug** [comment]
<img width="720" height="1612" alt="Image" src="https://github.com/user-attachments/assets/29ba9e80-5532-42c6-9b2f-64e7301e295b"
I have several apps like that, and they've taken over the domains from my Google account. They even installed static on my wireless network. I even have a copy of the file they used, but I don't know much about it and I can't fix it. 😓

**Comment by juncas2205-debug** [comment]
Speaking of that topic, because I have several files that I have no idea where they came from, for example this one, serpapi_pagination.next  Is someone sending them?
