### ISSUE TITLE
[Google Search API] `related_questions` of `organic_results` not parsed for some `mobile` searches

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#571]
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/73674035/212675263-5889f02a-8ce2-4bd1-8e7e-144e28926ead.png">

[Playground](https://serpapi.com/playground?q=Superhero+Movies&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&num=100&device=mobile&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq)
[Inspect](https://serpapi.com/searches/63c53ca0272aa5c2057f72ef/inspect)

**Comment by zyc9012** [comment]
With @kagermanov27, we decided to parse this block as `rich_snippet.bottom.questions` for now. We will deprecate it and switch to `related_questions` in the future.

**Comment by charliemmm** [comment]
Hi, rich snippet still does not parse the questions. While the data structure is there, the information under the key "questions" is still now available.

**Comment by zyc9012** [comment]
@charliemmm Thanks for reporting, it's fixed.
