### ISSUE TITLE
[Yahoo Search API] `snippet` parsed wrong for some `organic_results`

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#584]
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/73674035/212690081-a4a11ab4-d2ef-49a9-8a04-aba206812ae2.png">

[Playground](https://serpapi.com/playground?engine=yahoo&p=Coffee)
[Inspect](https://serpapi.com/searches/63c54ee5477c0e04c6481fbb/inspect)

**Comment by btaunt** [comment]
This ticket was indirectly resolved with the recent changes made in https://github.com/serpapi/SerpApi/pull/4550

Closing.
