### ISSUE TITLE
[Yelp Search API] `button` -> `link` of `organic_results` not parsed for some searches

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#585]
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/73674035/212707104-0174f357-2b1f-42c0-adb9-756117ad609b.png">

[Playground](https://serpapi.com/playground?engine=yelp&find_loc=Austin%2C+TX%2C+United+States)
[Inspect](https://serpapi.com/searches/63c564139f55b3753aa3826a/inspect)

**Comment by aciddjus** [comment]
We are not extracting the link because there isn't one. It's a `submit` button.

Example:

![image](https://github.com/serpapi/public-roadmap/assets/6929257/59fbb147-e051-455e-923f-e413a3555cb1)
