### ISSUE TITLE
[Google Search API] `link` and `gps_coordinates` not parsed for `local_map` for some `mobile` searches

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#590]
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/73674035/212898622-183dc62d-a6a7-45a3-a7cf-04d3e24619bc.png">

Details are present in raw HTML

[Playground](https://serpapi.com/playground?q=apple&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq)
[Inspect](https://serpapi.com/searches/63c6918f29d17786dc4fe58d/inspect)

**Comment by kagermanov27** [comment]
This kind of result is not showing any GPS or link in the HTML now. It was probably present within the inspect, and got lost over time.

**Comment by andypple83** [comment]
Google didn't return the GPS or link in the HTML now. I'll close this issue now. Thanks
