### ISSUE TITLE
[Google Finance API] Graph Item is not extracted

### ISSUE THREAD

**Issue by bmrhoads51** [serpapi/public-roadmap#599]
On Google Finance, the graph for a stock usually shows up in JSON as an item labeled 'graph', with the price and time every minute. Since yesterday, when I use the Google Finance API on stocks like AAPL, TLSA, AMZN, and META, there is no 'graph' item in the JSON file.  The search parameters are:
google_finance
AAPL:NASDAQ
en
desktop
And my most recent search ID is 63c84fd6b7b1cce391cbb912

**Comment by aciddjus** [comment]
Thank you for reporting the issue, @bmrhoads51 👍 

This should be resolved now.
