### ISSUE TITLE
[Google Shopping API] Extract source's direct link instead of Google's redirect link

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#600]
It looks like we are currently exporting Google's redirect link instead of the direct source's link:

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/28161162/213402481-6cb820d4-de35-4ff2-924e-415d94cfaed7.png">

[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=shop) | [Inspect](https://serpapi.com/searches/63c9097aaa6c95b47edbd245/inspect)

**Comment by rahulkumar501** [comment]
Hi @marm123, 
Thanks for creating the ticket.

I tried removing `https://www.google.com/url?url=` and url encoding the remaining part, but it was not helping. As explained by following example 

For Google URL -
https://www.google.com/url?url=https://www.kogan.com/au/buy/oppenheimer-cilio-figaroespresso-maker-ssteel-mirror-polished-wplane-bottom-o-105x22cm-6-cups-6539/&rct=j&q=&esrc=s&sa=U&ved=0ahUKEwiOjOrIndP8AhW-KlkFHbkdDbcQguUECHk&usg=AOvVaw0_k7oX0O7bBsUOen6y_oj5

has url =
https://www.kogan.com/au/buy/oppenheimer-cilio-figaroespresso-maker-ssteel-mirror-polished-wplane-bottom-o-105x22cm-6-cups-6539/&rct=j&q=&esrc=s&sa=U&ved=0ahUKEwiOjOrIndP8AhW-KlkFHbkdDbcQguUECHk&usg=AOvVaw0_k7oX0O7bBsUOen6y_oj5

Which is completely different than source url -
https://www.kogan.com/au/buy/oppenheimer-cilio-figaroespresso-maker-ssteel-mirror-polished-wplane-bottom-o-105x22cm-6-cups-6539/

There should some other way of getting the source url, could you please let me know?

**Comment by rahulkumar501** [comment]
Hello @marm123 and @kagermanov27 
Thanks for fixing the issue in google_shopping results. 

On further implementation, we have come across similar issue in `inline_shopping_results`.
Could you please look into it and do the same fix for it?
