### ISSUE TITLE
[Documentation] Update Reverse Image Search API examples to not include `title` and `original`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#602]
Google no longer returns `title` and `original` in the Reverse Image search results per https://github.com/serpapi/public-roadmap/issues/470

We should update our documentation accordingly to reflect this change not to confuse customers:

<img width="868" alt="image" src="https://user-images.githubusercontent.com/28161162/214023781-0ed8bfc9-6053-422b-aec4-d0f4752835b3.png">

[Documentation](https://serpapi.com/google-reverse-image)

**Comment by andypple83** [comment]
I found a way to get `original` and `title` so we don't need to remove these fields. Thanks @marm123
