### ISSUE TITLE
[Google Search API] Shopping Blocks not Parsed and Returned

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#604]
Some shopping blocks in the middle of the results are not parsed and returned.

![serpapi com_searches_e610cf292a057894_63cf8a2166d81f9c96108c93 html](https://user-images.githubusercontent.com/64849049/214237264-a413c6d6-b14b-47f6-b54e-aca157c821ce.png)

[The Playground](https://serpapi.com/playground?q=laptops&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [The Inspect](https://serpapi.com/searches/63cf8a2166d81f9c96108c93/inspect) | [Google](https://www.google.com/search?q=laptops)

**Comment by tanys123** [comment]
Related https://github.com/serpapi/public-roadmap/issues/592
