### ISSUE TITLE
[Google Search API] Knowledge Graph `see_results_about` not parsed correctly

### ISSUE THREAD

**Issue by gildamaurice** [serpapi/public-roadmap#607]
Example: search for Baharat https://serpapi.com/searches/21467b8366592ef9/63d15970359e995fc6a2d375.json 

The knowledge graph shows two "See results about" options: Baharat and Spice

I would expect SERP API to give the url for each option, but instead the JSON looks like this:
```json
"knowledge_graph": {
    "see_results_about": [
      {
        "name": "BaharatFoodFood",
        "image": "https://serpapi.com/searches/63d15970359e995fc6a2d375/images/eec664e608b4f5db97b79f409e902aafc7b8e32d391fc9375e60f482f9c6bd22089310a79d9d05396f9b0bf5ad083184.jpeg"
      },
      {
        "name": "SpiceTable sauceTable sauce",
        "image": "https://serpapi.com/searches/63d15970359e995fc6a2d375/images/eec664e608b4f5db97b79f409e902aafc7b8e32d391fc9375e60f482f9c6bd22684c0d04e4d93b59d5727a0907fa2213.jpeg"
      }
    ]
  }
```

I would expect for each option (Baharat, Spice) to get a direct link to each option

Thanks and keep up the good work!

**Comment by kagermanov27** [comment]
[Playground Link](https://serpapi.com/playground?q=baharat&location=Lisbon%2C+Lisbon%2C+Portugal&google_domain=google.pt&gl=uk&hl=en&no_cache=true&google_domain=google.pt&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+client+as_epq)
