### ISSUE TITLE
[Walmart Reviews API] No response

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#609]
[Inspect](https://serpapi.com/searches/63d26b0635176482a4ebd81e/inspect) | [Playground](https://serpapi.com/playground?engine=walmart_product_reviews&product_id=520468661)

More than 100 seconds on the request:

![image](https://user-images.githubusercontent.com/78694043/214830426-d284a1d4-8f84-447e-a16e-26c8f0e60411.png)

Our colleague also double-checked and confirmed it:

![image](https://user-images.githubusercontent.com/78694043/214831054-c24f4079-69a2-4ac4-a0cc-14f6ab1258c6.png)

**Comment by aciddjus** [comment]
It looks like the engine hasn't been working for a while now. With ~90% errors being `429 - too many requests`

<img width="677" alt="image" src="https://user-images.githubusercontent.com/6929257/214892476-345d7c5b-3199-49d1-84ee-154d5c2a1950.png">
