### ISSUE TITLE
[Documentation] Update Advisory to Avoid Location Parameter Outside US with Google Shopping, Product & Event APIs

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#610]
In many of our documentation pages and in a tooltip in the Playground we advise our user not to use the Location parameter outside the US with Google Shopping, Products and Events APIs. I checked with our colleague Bart, who agreed that this sentence may be outdated. Bart also noticed that this is included [many places](https://www.google.com/search?q=%22Avoid+utilizing+location+when+setting+the+location+outside+the+U.S.+when+using+Google+Shopping+and/or+Google+Product+API.%22&filter=0&dpr=2) in our documentation, including in [Google Reverse Image Documentation](https://serpapi.com/google-reverse-image), where it wouldn't be relevant regardless of it's accuracy. If Location parameter is now working for these APIs outside the US, we should update the description of the Location parameter in our Documentation and the Tooltip to avoid confusing users.  

![Screenshot 2023-01-27 085854](https://user-images.githubusercontent.com/30915304/215148007-10a2e994-8585-45a7-9d45-fa1990258a32.png)

![Screenshot 2023-01-27 090509](https://user-images.githubusercontent.com/30915304/215149322-3fd67a36-a227-4cff-a83e-f3400f9a727d.png)

[Playground (Google Shopping API)](https://serpapi.com/playground?engine=google_shopping&q=Coffee&location=Madrid%2C+Community+of+Madrid%2C+Spain&google_domain=google.es&gl=es&hl=es) | [Playground (Google Product API)](https://serpapi.com/playground?engine=google_product&product_id=10945277808144295788&location=Madrid%2C+Community+of+Madrid%2C+Spain&google_domain=google.es&gl=es&hl=es) | [Playground (Google Events API)](https://serpapi.com/playground?engine=google_events&q=Music&location=Warsaw%2C+Masovian+Voivodeship%2C+Poland)

**Comment by ilyazub** [comment]
Related to https://github.com/serpapi/public-roadmap/issues/454#issuecomment-1314108986

**Comment by aciddjus** [comment]
Resolved in https://github.com/serpapi/SerpApi/pull/3846
