### ISSUE TITLE
[Google Search API] related_searches[query] not Returned in Tablet Mode

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#614]
Google Search API does not return related searches > query key in tablet mode.

![tablet_related_searches](https://user-images.githubusercontent.com/64849049/215494307-d05180d2-65c4-4fc5-90a4-6b97e8e431a1.png)

[The Playground](https://serpapi.com/playground?q=coffee&location=Mexico+City%2C+Mexico+City%2C+Mexico&google_domain=google.com.mx&gl=mx&hl=es&num=100&device=tablet&no_cache=true) | [The Inspect](https://serpapi.com/searches/63d7c9122236e232f3d4ff34/inspect)

**Comment by tanys123** [comment]
Duplicated https://github.com/serpapi/public-roadmap/issues/613
