### ISSUE TITLE
Google Scholar API, No longer returning results after page 50

### ISSUE THREAD

**Issue by BriFarris** [serpapi/public-roadmap#620]
I am working on scraping google scholar and for some reason when I try to go past page 50 on google scholar api it no longer shows results with the error: "google hasn't returned any results for this query". I checked in the playground and it gave an internal server error shown in the attached image. However, the api works for all results up to page 50.

![image](https://user-images.githubusercontent.com/70967594/216431723-e1acfd6e-f95a-4a07-9ed4-eef80a71c977.png)

I've made sure to check google scholar and there are well over 50 pages to this search. Any help or suggestions would be appreciated!

**Comment by ritu1337** [comment]
Google Scholar shows `Server Error` when I manually click on the 50th page in Chrome, so I don't think it's related to SerpApi.
![CleanShot 2023-02-02 at 21 55 02@2x](https://user-images.githubusercontent.com/12263752/216447412-1ca4bb22-6fa9-4840-989b-99d1d0b4a63c.png)

<img width="1030" alt="CleanShot 2023-02-02 at 21 04 42@2x" src="https://user-images.githubusercontent.com/12263752/216437970-3a02cf45-7d77-44dc-9b7e-d9c10bedb50b.png">

**Comment by BriFarris** [comment]
![image](https://user-images.githubusercontent.com/70967594/216451290-cdba5c44-0b0c-4635-8b9c-71d2d3c2bf5c.png)
![image](https://user-images.githubusercontent.com/70967594/216451473-01ccef17-af56-4cfe-a34a-253e8aeb3d8b.png)
 
That is strange because google scholar currently works past page 50 for me. But it could just be a google scholar error.

**Comment by ritu1337** [comment]
Can you post the full URL?

**Comment by BriFarris** [comment]
Sure here you go!
![image](https://user-images.githubusercontent.com/70967594/216471292-f3484cc2-3fee-4c54-a1a8-1f51061d603a.png)

**Comment by ritu1337** [comment]
Thank you @BriFarris.

Your SerpApi search will work past the 50th page if you don't set `num=20`.

Working Playground link with your search recreated: https://serpapi.com/playground?engine=google_scholar&q=electrochemical+CO2+reduction&hl=en&start=500

**Comment by aciddjus** [comment]
Closing as not an issue.
