### ISSUE TITLE
[Google Search API] Missing inline `shopping_results`

### ISSUE THREAD

**Issue by tanys123** [serpapi/public-roadmap#621]
<img width="1918" alt="Screenshot 2023-02-03 at 7 27 33 PM" src="https://user-images.githubusercontent.com/10222402/216592750-6763b238-2c08-4ab1-8120-817c365a2ce9.png">

This ads section is not parsed.

[Playground](https://serpapi.com/playground?q=laptops&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq) | [Inspect](https://serpapi.com/searches/63dcebfbfdca3e045a78f90a/inspect)

**Comment by schaferyan** [comment]
A customer reported more missing `inline_shopping` results. They appear to be missing from the `raw_html` as well as from the JSON:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053836?view=List) | [Inspector](https://serpapi.com/searches/6556521ceb690ffba99f8a57/inspect) | [Inspector](https://serpapi.com/searches/6556533af0adfb6f9489c996/inspect) | [Google ](https://www.google.com/search?q=ashwagandha&oq=ashwagandha&uule=w+CAIQICIHQXVzdHJpYQ&hl=en&gl=at&sourceid=chrome&ie=UTF-8)

**Comment by kagermanov27** [comment]
We have released a fix for this.
The inline `shopping_results` field is now successfully parsed for this layout:

Before:
<img width="1143" alt="shop-old" src="https://github.com/serpapi/public-roadmap/assets/73674035/544a5a71-054b-4b6b-80f1-477a4a3393f7">

After:
<img width="1143" alt="shop-new" src="https://github.com/serpapi/public-roadmap/assets/73674035/0ab3b624-f4ad-4bc2-8eca-bb6b7d71f729">
