### ISSUE TITLE
[Google Scholar Author API] Update outdated `num` parameter in Docs and Playground 

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#622]
`num` parameter has been replaced with `pagesize` parameter for displaying articles amount per page.

In the Playground, `google_scholar_author_url` has a parameter `pagesize` as you can see below.

[Docs](https://serpapi.com/google-scholar-author-api) | [Playground](https://serpapi.com/playground?engine=google_scholar_author&author_id=_xwYD2sAAAAJ&hl=en&num=40)

![image](https://user-images.githubusercontent.com/78694043/216605773-c8cfdae5-9511-4c08-a9b1-1f0fb8ad9e62.png)

**Comment by aciddjus** [comment]
It hasn't been replaced. It was always `pagesize`. It's just named `num` on our side.

This is how we build the URL:

```ruby
{
  ...
  pagesize: num
  ...
}
```

The idea was to use the same naming across engines for parameters that do similar things (`q`, `num`, `start`, etc.). To build consistency across SerpApi.

But I think that was the wrong approach. It's more user-friendly just to be able to copy/paste URL from a website into a SerpApi.

On the other hand. If, for example, Google Scholar changes `pagesize` to `somethingelse`, users won't be able to use `pagesize` anymore and will have to transition to `somethingelse`. But with the current approach, we can just do that on the back-end and users will be able to continue using `num` parameter without changing their code.

**Comment by dimitryzub** [comment]
@aciddjus thank you for all clarifications. It seems I was just tired that day and did not notice that everything was okay :)

I'll close this issue for now then. Feel free to re-open.
