### ISSUE TITLE
[Google Search API] organic_results not parsed for some mobile queries

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#623]
A user complained that in about 3/5 of their searches with `device=mobile`, we are not parsing the `organic_results `even though they are present in the search results. They shared the example `search_id` I've linked to below. Even using the same parameters as they used in this search however, I was unable to replicate it in the Playground.

![image](https://user-images.githubusercontent.com/30915304/216678785-38af7677-f439-4595-a788-ad0b71f703b1.png)

[Search Inspector](https://serpapi.com/searches/63dd2eb42f542e1a3df79a8d/inspect) | [Playground (same params)](https://serpapi.com/playground?q=fasting+and+sleeping&gl=us&hl=en&device=mobile&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+client)

**Comment by tanys123** [comment]
It somehow downloaded the desktop version instead of the mobile. I am not able to replicate the issue either using the same User Agent and proxy. Also I have tried running around 1k+ searches and all the file downloaded correctly.

**Comment by aciddjus** [comment]
I was also trying to replicate this weekend unsuccessfully.

**Comment by ritu1337** [comment]
> It somehow downloaded the desktop version instead of the mobile. I am not able to replicate the issue either using the same User Agent and proxy. Also I have tried running around 1k+ searches and all the file downloaded correctly.

The OP's search user IP provider has fixed the issue on Friday, should be good now.
