### ISSUE TITLE
[New API] Support news.google.com

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#631]
Currently, we are scraping Google News results, which is something different than news.google.com:

[Direct link to news.google.com](https://news.google.com/home?hl=en-US&gl=US&ceid=US:en)

**Home:**
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/28161162/217459334-455a55ab-380f-4ad1-88ce-6188ddb01e03.png">

**U.S.:**
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/28161162/217459459-e14565e0-0ea3-4c9e-92c0-ea464771563f.png">

**World:**
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/28161162/217459523-30fbb0ca-b583-469f-977b-d3503eddbf11.png">

**Comment by aciddjus** [comment]
Related: https://github.com/serpapi/SerpApi/issues/707

**Comment by schaferyan** [comment]
Another request for this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000050435?view=List)

**Comment by jtoy** [comment]
I want this feature too, love it!

**Comment by marm123** [comment]
Another customer requested this:
[
Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/view/99173/conversation/102910000051175?view=List)

**Comment by CaptainPalawan** [comment]
I'd love to have this. I hope you find the time to let me work with this

**Comment by martin-serpapi** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053279?view=List)
