### ISSUE TITLE
[Google Events API] Incorrect `link` parsed in JSON response

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#633]
There is an issue with the event's `link` being the same as the `link` in `ticket_info`, as well as the `thumbnail` being extracted for the wrong event.

**1. Wrong `thumbnail` extracted:**
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/28161162/217507402-0f701ce2-7d76-48d8-ad2c-0dee91dff35a.png">

**2. Event's `link` is the same as `ticket_info` `link`:**
<img width="977" alt="image" src="https://user-images.githubusercontent.com/28161162/217507747-97ebbac2-d839-40f4-9089-d599e8a30541.png">
<img width="959" alt="image" src="https://user-images.githubusercontent.com/28161162/217508065-b7d4bd46-1dd1-465a-b7a1-e732f704d507.png">

[Playground](https://serpapi.com/playground?engine=google_events&q=Events+in+natick%2Cma) | [Inspect](https://serpapi.com/searches/63e37d8b2c08444b63c54777/inspect) | [Google Events page](https://www.google.com/search?q=Events+in+natick%2Cma&ibp=htl;events&hl=en)

Connected to https://github.com/serpapi/public-roadmap/issues/367

**Comment by kagermanov27** [comment]
I have reduced the scope of this issue to only links. Thumbnails will be dealt in https://github.com/serpapi/public-roadmap/issues/367
