### ISSUE TITLE
[Google Maps Local API] `ll` coordinates returns data from incorrect location after certain `start` page

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#636]
[Inspect](https://serpapi.com/searches/63e4c2b637014cebde2fd5c1/inspect) (incorrect `address` for all results) | [Inspect](https://serpapi.com/searches/63e4c2b34b91eb1e104a98ea/inspect) (correct `address` for all results) 

By incorrect location I mean `1603 Battleground Ave, Greensboro, NC 27408`, where the expected location is somewhere in `Roma RM, Italy`. 

This behavior happens after a certain page. In this particular example, when `start=170`. I'm not sure if it's an issue on our end.

![image](https://user-images.githubusercontent.com/78694043/217851606-80a348ac-be67-4625-a7a1-c28796b4781d.png)

Reported by @denisskopa 👍

**Comment by ilyazub** [comment]
Probably related to proxies that were used.

**Comment by dimitryzub** [comment]
@ilyazub @aciddjus

The new StackOverflow question seems to be related to this issue: https://stackoverflow.com/questions/75766500/why-does-google-maps-search-return-results-outside-the-bounds-of-the-zoom-level

**Comment by dsojevic** [comment]
Just confirming that this is still occurring, however, I've encountered a scenario where the page includes a mix of in-bounds results and out-of-bounds results which leads me to believe that this is an issue with Google Maps itself when you're reaching the ends of results.

![image](https://github.com/user-attachments/assets/7c53ea14-ce96-483a-a792-767c3ddc3a28)

**Mixed locations:** [Playground](https://serpapi.com/playground?engine=google_maps&q=Coffee&ll=%4041.8896533%2C12.491766%2C17.24z&hl=en&type=search&start=170) | [Inspect](https://serpapi.com/searches/672d87a098876d0c3302c745/inspect)

**Correct locations:** [Playground](https://serpapi.com/playground?engine=google_maps&q=Coffee&ll=%4041.8896533%2C12.491766%2C17.24z&hl=en&type=search&start=0) | [Inspect](https://serpapi.com/searches/672d88d48b84c429a9ec3ddb/inspect)

---

> Probably related to proxies that were used.

Given we're seeing mixed results, I'd be inclined to agree with this being the reason when you're at the end of the result set.

I suspect the only way to resolve this, or at least reduce the severity in difference of region for results shown, would be to try and match proxies with the `ll` parameter passed in, but I don't think it would be worth it or feasible.

**Comment by hilmanski** [comment]
Another customer complained about this issue.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000073423?view=List)
