### ISSUE TITLE
[Google Knowledge Graph API] Wrong elements are highlighted on Playground

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#64]
Past Canny Conversation:
>Ilya: Google Knowledge Graph highlights wrong elements on Playground. It should highlight the panel on the right instead of the entire page.
[Playground](https://serpapi.com/playground?q=Jos%C3%A9+Abreu&gl=us&hl=en&highlight=knowledge_graph) · [Search Inspect](https://serpapi.com/searches/61fbdecfc9de45dcfe235b70/inspect)
![image](https://user-images.githubusercontent.com/73674035/157677034-5a66615b-efae-4599-91c0-1c1fba52ccd4.png)

---

[Past Canny Link](https://forum.serpapi.com/bugs/p/google-knowledge-graph-highlights-wrong-elements-on-playground)

**Comment by andypple83** [comment]
I fixed this issue when parsing the knowledge type: https://github.com/serpapi/SerpApi/pull/2872/files#diff-9d8cc4aedbc42f8efac87a66c018a1f204cd28b3805758506ec93c303b6fb436R5
