### ISSUE TITLE
[Yandex Reverse Image API] Return "No matching images found" in JSON response

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#644]
Currently, we are only scraping results if they are present. However, we can also scrape information that "No matching images found" in "Other image sizes":

**We are scraping this:**
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/28161162/218709634-e170ee94-1d55-4971-8e03-e885385d82d0.png">

**We are not scraping this (no matching images found):**
![image](https://user-images.githubusercontent.com/28161162/218710517-ca37a648-7d06-420c-bf30-a07da281cf37.png)

[Playground](https://serpapi.com/playground?engine=yandex_images&url=https%3A%2F%2Favatars.mds.yandex.net%2Fget-images-cbir%2F2242116%2FPdICmp2bNI9gpQ63MAT3Bw9978%2Forig) | [Inspect](https://serpapi.com/searches/63eb61fe3944b04569719cb7/inspect) | [Yandex](https://yandex.com/images/search/?rpt=imageview&url=https%3A%2F%2Favatars.mds.yandex.net%2Fget-images-cbir%2F1636830%2FPdICmp2bNI9gpQ63MAT3Bw2171%2Forig&cbir_id=1636830%2FPdICmp2bNI9gpQ63MAT3Bw2171)

**Comment by kdomashnev** [comment]
scraping "No matching images found" would be very useful to check if the image exists in web or not
