### ISSUE TITLE
[Google Search API] New result for live events

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#645]
For live events, Google returns a new result for it.

![Screen Shot 2023-02-15 at 11 28 42](https://user-images.githubusercontent.com/99160364/218930604-d4a28384-6424-43d9-964b-850f0a86ae28.png)

[Playground](https://serpapi.com/playground?q=earthquake&location=Austin%252C+Texas%252C+United+States&gl=us&hl=en&google_domain=google.com) | [Inspect](https://serpapi.com/searches/63eb681ea5ad6d12020263a1/inspect)

**Comment by kagermanov27** [comment]
Just an insight here. I looked at Google when the second earthquake on the 6th of Feb hit. The results were different where the main earthquake near you was expanded, and there was an alert sign. So it is likely we might not be able to scrape it when the actual event happens. But might be worth implementing.
