### ISSUE TITLE
[Google Search API] Support `tbm=pts` parameter for patent searches

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#657]
Currently, we support Images, Local, News, Shopping, and Videos as the `tbm` parameters. We can also add Patents (pts), which are supported by Google:

<img width="390" alt="image" src="https://user-images.githubusercontent.com/28161162/220117680-fc0a84c4-5fcb-47d6-84ef-29bc7e5a89c4.png">
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/28161162/220117861-fd317839-d5b3-4109-94a1-62ca97bd92f9.png">

[Google link](https://www.google.com/search?q=google+patents&tbm=pts)

Related to https://github.com/serpapi/SerpApi/issues/536

**Comment by marm123** [comment]
Another customer requesting this

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000039148)

**Comment by ThomasKinkeldei** [comment]
Would be also very interested in this feature!

**Comment by mazzespazze** [comment]
I would also be very interested in this feature!

**Comment by marm123** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000043186)

**Comment by mazzespazze** [comment]
@marm123 do you know any timeline regarding this? 

And is there a work-around today with the link you provided? For example you have already a Google Scraper, is there a way to instruct the tbm on Google instead of SERP to still get a patent search? 

Thank you for any help.

**Comment by anna-feliz** [comment]
This would be a great feature, I really need it!

**Comment by marm123** [comment]
@mazzespazze Unfortunately, I can't give you an ETA for implementing this. There is also no workaround to use the `tbm=pts` in your regular Google Search API calls, as the data is scraped from the different parts of Google, which we do not currently support.

I'll see what I can do about implementing this.

**Comment by zyc9012** [comment]
There're two ways to search patents in Google, https://patents.google.com and https://www.google.com/search?tbm=pts. Which do you prefer? @ThomasKinkeldei @mazzespazze @anna-feliz

**Comment by ThomasKinkeldei** [comment]
I did not do a profound background check but it seems to me that https://patents.google.com/ deliver better results.

Von: tato ***@***.***
Gesendet: Dienstag, 4. Juli 2023 09:22
An: serpapi/public-roadmap ***@***.***>
Cc: Thomas Kinkeldei ***@***.***>; Mention ***@***.***>
Betreff: Re: [serpapi/public-roadmap] [Google Search API] Support `tbm=pts` parameter for patent searches (Issue #657)


There're two ways to search patents in Google, https://patents.google.com and https://www.google.com/search?tbm=pts. Which do you prefer? @ThomasKinkeldei<https://github.com/ThomasKinkeldei> @mazzespazze<https://github.com/mazzespazze> @anna-feliz<https://github.com/anna-feliz>

**Comment by mazzespazze** [comment]
@zyc9012 Agree with @ThomasKinkeldei. The site https://patents.google.com delivers better results. But they are also more informative. It shows assignee, inventor, and register. 
While on the standard Google search, even with the pts parameter, all that is missing.
