### ISSUE TITLE
[Google Search API] Extract "People also search for" into `inline_people_also_search_for` block of the JSON response

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#661]
This thread is to decide whether or not we should extract "People also search for" in the `inline_people_also_search_for` block, like we did before, or keep it with `related_searches`. On the one hand, the data looks very similar for both "People also search for" and "related searches", but on the other hand, they are presented by Google separately, so it makes sense to extract them as two different entities.

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/28161162/220650007-5477b119-c937-43f0-a237-6aa22adec53e.png">

[Playground](https://serpapi.com/playground?q=Apple&location=Greater+London%2C+England%2C+United+Kingdom&google_domain=google.co.uk&gl=uk&hl=en&device=mobile) | [Inspect](https://serpapi.com/searches/63f6255bce87f87b93ba3604/inspect)

Related issues:
https://github.com/serpapi/public-roadmap/issues/309
https://github.com/serpapi/public-roadmap/issues/638

**Comment by tanys123** [comment]
We have [WIP](https://github.com/serpapi/SerpApi/pull/3561) that merge both of them and give `block_position` so user can differentiate upper and lower block. There are the same content, separating them will like to have conflicts in the result.
