### ISSUE TITLE
[Google Product API] Scrape Specifications Block

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#664]
Google Product pages have a "Specifications" block, which we are not currently scraping:

![image](https://user-images.githubusercontent.com/30915304/221036236-75a0a4c9-a69e-420e-b220-0c16a924b6ff.png)
[Playground](https://serpapi.com/playground?engine=google_product&product_id=8942414643862033893&gl=us&hl=en)

**Comment by aciddjus** [comment]
This has been resolved.

![image](https://github.com/serpapi/public-roadmap/assets/6929257/d3187cb7-7997-4fd4-855e-c738b2ea23f3)

-------------

[Playground](https://serpapi.com/playground?engine=google_product&product_id=8942414643862033893&gl=us&hl=en)
