### ISSUE TITLE
[Google Maps API] Last Page of Results only Shown with Exact Start Parameter to Show Exactly 20 Results

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#669]
We recommend in our documentation and tooltip that users use multiples of 20 for the `start` parameter. However, other values seem to work. It seems that it some cases the user may only be able to get the last page of results by specifying a value for `start` that will show the last 20 results.

A user communicated that they cannot retrieve the last page of results using multiples of 20. For example for a search that returns 219 results, setting `start=200` will cause the search to return an empty result set. To get the last page they need to use `start=198`.

I'm not sure if we can change this on our side or not. In either case we should advise the documentation and tooltip to accurately describe how the `start` parameter is working.

![image](https://user-images.githubusercontent.com/30915304/221253131-6997d260-3e9c-4a4d-8560-48a224f9d8ca.png)
![image](https://user-images.githubusercontent.com/30915304/221254339-a228efaa-f29c-4151-b813-095472bedd91.png)

[Playground (start=198)](https://serpapi.com/playground?engine=google_maps&q=Grocery+stores&ll=%4040.7128%2C-74.0060%2C7z&hl=en&type=search&start=198) | [Playground (start=200)](https://serpapi.com/playground?engine=google_maps&q=Grocery+stores&ll=%4040.7128%2C-74.0060%2C7z&hl=en&type=search&start=200) | [Search Inspector(start=198)](https://serpapi.com/searches/63f8f4fdaef264ca8fc0fd12/inspect) | [Search Inspector (start=200)](https://serpapi.com/searches/63f8ee56a74fe0f2b69618ab/inspect)

**Comment by dsojevic** [comment]
The documentation was updated to make this behaviour clearer and to suggest a maximum number of pages to page through:
https://serpapi.com/google-maps-api#api-parameters-pagination-start
