### ISSUE TITLE
[General] Delete `serpapi_pagination`->`next_link` and `serpapi_pagination`->`previous_link` from JSON response

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#67]
Past Canny Conversation:
>Ilya: serpapi_pagination.next_link
 and serpapi_pagination.previous_link
 were deprecated two years ago and will be removed from the JSON response at the beginning of January 2022.
Instead, there are serpapi_pagination.next
 and serpapi_pagination.previous
 that point to the same URL.
![image](https://user-images.githubusercontent.com/73674035/157690722-2c9c4e52-7a3b-4506-81b7-c90fd0108564.png)
---
[Past Canny Link](https://forum.serpapi.com/feature-requests/p/delete-serpapipaginationnextlink-and-serpapipaginationpreviouslink-from-json-res)

**Comment by marm123** [comment]
One of our customers asked what the purpose of having both `next_link` and `next` is. I'm following up on that, as it might still confuse our users.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000062016?view=List)

**Comment by ilyazub** [comment]
`next` and `previous` are suggested to use. `next_link` and `previous_link` are deprecated but left in the response for backwards compatibility.

Closing this issue as we decided against a breaking change.

Ref: https://github.com/serpapi/SerpApi/issues/1656
