### ISSUE TITLE
[Documentation] Clarify Walmart "product_id" Parameter Documentation

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#671]
The Walmart Product API requires a `product_id` parameter. However the value supplied doesn't need to be the `product_id` of the product, it can also be the `us_item_id` or `upc`. Our documentation states that it is better to use the `us_item_id`, but the `product_id` returns faster - which seems to be contradictory. In addition, it seems that the product page will include review results only if the `us_item_id` is used - we should mention this in our documentation.
![image](https://user-images.githubusercontent.com/30915304/221301077-d85fd8f8-cdce-497d-8cc2-1d412e508798.png)

The Walmart Reviews API also has a `product_id` parameter, but it only accepts the `us_item_id`, passing the `product_id` will not return results. 
![image](https://user-images.githubusercontent.com/30915304/221301062-bd561676-0ce8-4792-9915-dc66053a3ae6.png)

In both cases, the naming is already confusing, but I suspect there is nothing we can do about this since it's on Walmart's end. However we can be more explicit in our documentation and tooltips to help users not to be confused. 

In the Walmart Product API documentation, we can clarify the benefits/drawbacks of supplying the `product_id` or the `us_item_id` as the value of the `product_id` parameter.

**Comment by ilyazub** [comment]
> `product_id` will not return results.

It's a bug or something changed on Walmart's end. `product_id` supposed to accept all of `upc`,  `product_id`, and `us_item_id` because Walmart responded with and accepted multiple product IDs previously.
