### ISSUE TITLE
[New API] Support Bing Shopping API

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#672]
We can add Bing Shopping as one of our APIs in the future.

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/28161162/221484237-eff61e7f-9af1-428f-b885-050e0d079f46.png">

[Bing Shopping](https://www.bing.com/shop?q=Coffee&qs=n&form=SHOPSB&sp=-1&lq=0&pq=coffe&sc=8-5&sk=&cvid=2F46AC9D81F84BC790C5957C3E68F1B3&ghsh=0&ghacc=0&ghpl=&setlang=pl&sid=3C75DBE707C9698D330CC96006DB68E3)

Moved to Public Roadmap from https://github.com/serpapi/SerpApi/issues/2083

**Comment by aliayar** [comment]
Another user requested this feature as ChatGPT may be used with Bing Shopping.

**Comment by SkapBlest** [comment]
Bing Shopping API would be absolutely fantastic 💪🏼🤩
