### ISSUE TITLE
[New API] Add Walmart Reviews API

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#68]
Past Canny Conversation:
>Ilya: Scrape Walmart Reviews with pagination.
![image](https://user-images.githubusercontent.com/73674035/157691409-46647668-1d2d-46ec-8b7b-911dcc1f27a6.png)

----

[Past Canny Link](https://forum.serpapi.com/feature-requests/p/add-walmart-reviews-api)

**Comment by andypple83** [comment]
Already scraped.

![Screen Shot 2022-08-08 at 15 33 26](https://user-images.githubusercontent.com/99160364/183375461-8e782817-c6ff-4c66-9461-35f5e3a2f52f.png)
