### ISSUE TITLE
[Google Search API] `knowledge_graph` Lyrics text treated as hash key instead of hash value

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#680]
`knowledge_graph` hash key contains lyrics text, rather than a `lyrics: <text>`: 

![image](https://user-images.githubusercontent.com/78694043/221772014-40b71498-dd0a-4c3a-9fc3-348a7aa3dbf1.png)

Also, `answer_box` is lyrics (not sure if it's correct), shouldn't it be in the `knowledge_graph`?

![image](https://user-images.githubusercontent.com/78694043/221772614-a3f08b2f-0fdb-45b0-a840-7b6f4ed0e9c1.png)

[Playground](https://serpapi.com/playground?q=pewdiepie+lasagna) | [Inspect](https://serpapi.com/searches/63fd9f082fe302c078a21856/inspect)

**Comment by aciddjus** [comment]
It was [always extracted](https://github.com/serpapi/SerpApi/pull/2149) as `answer_box`. It's not supposed to show in `knowledge_graph`.
