### ISSUE TITLE
[Google Jobs API] Search Results not Including 'Category' Chips

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#681]
Google Jobs API doesn't return "Category" chips currently. I am not sure if Google removed it completely or our parser has problem scraping it.

![jobs_cat](https://user-images.githubusercontent.com/64849049/221780462-78db9e75-d5f5-4dcc-8443-269769eaeea8.png)

[The Playground](https://serpapi.com/playground?engine=google_jobs&q=software+developer) | [The Inspect](https://serpapi.com/searches/63fd9bd21baebbed24a64f13/inspect) | [The Inspect (It works in this example)
](https://serpapi.com/searches/63f79afa969c08fc4e614459/inspect)

**Comment by tangsanshui** [comment]
Can other fields of ‘chips’ be used instead
For example: ‘title’ or ‘company type’ under chips

**Comment by andypple83** [comment]
@aliayar  I can not currently find any searches containing the `Category` chip from Google Job searches. Google may remove this. And our parser works correctly. 

@tangsanshui yes. you can use other chips like: `title`, `company type`... Please head to our [Google Jobs API](https://serpapi.com/google-jobs-api) document page for more information. Let us know if you have any questions. Thanks.

**Comment by andypple83** [comment]
I've checked Google Jobs results, and Google returns "chips" dynamically based on search keywords. Google returns "Company type" like the `category`:

```
...
{
      "type": "Company type",
      "param": "industry.id",
      "options": [
        {
          "text": "All"
        },
        {
          "text": "Staffing",
          "value": "/business/naics2007/5613"
        },
        {
          "text": "Consulting",
          "value": "/business/naics2007/5416"
        },
        {
          "text": "Education",
          "value": "/business/naics2007/61"
        },
        {
          "text": "Finance",
          "value": "/business/naics2007/52"
        },
        {
          "text": "Information",
          "value": "/business/naics2007/51"
        },
        {
          "text": "Manufacturing",
          "value": "/business/naics2007/31"
        },
        {
          "text": "Utilities",
          "value": "/business/naics2007/22"
        },
        {
          "text": "Engineering Services",
          "value": "/business/naics2007/5413"
        },
        {
          "text": "Retail",
          "value": "/business/naics2007/44"
        },
        {
          "text": "Construction",
          "value": "/business/naics2007/23"
        },
        {
          "text": "Foods & Beverages",
          "value": "/business/naics2007/311"
        },
        {
          "text": "Real Estate",
          "value": "/business/naics2007/53"
        },
        {
          "text": "Accommodation",
          "value": "/business/naics2007/721"
        },
        {
          "text": "Computer Services",
          "value": "/business/naics2007/5415"
        },
        {
          "text": "Mining",
          "value": "/business/naics2007/21"
        },
        {
          "text": "Travel",
          "value": "/business/naics2007/5615"
        },
        {
          "text": "Wholesale",
          "value": "/business/naics2007/42"
        }
      ]
    },
...
```

If you have any questions, feel free to reach out to us. Thanks.
