### ISSUE TITLE
[Zapier Integration] Set multiple search parameters

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#69]
Past Canny Conversation:
>Ilya:SerpApi integration in Zapier contains Action to get ranking in Google Search results.
Let's allow setting multiple search parameters (location, language, device, etc.) like in our Google Sheets add-on.

----

[Past Canny Link](https://forum.serpapi.com/feature-requests/p/set-multiple-search-parameters-in-zapier-integration)

**Comment by ilyazub** [comment]
@tanys123 The updated Zapier action still accepts only specific parameters. What if it'll accept a string (like in Google Sheets add-on), hash, or an array of tuples for parameters?

**Comment by tanys123** [comment]
@ilyazub I have updated the action to accept dictionary, which we can now give any parameters that can be accepted.

**Comment by ilyazub** [comment]
@tanys123, thanks I'll re-review it.

> BTW, should we make the integration public?

Zapier requires to have active beta users of Action before publishing.

**Comment by tanys123** [comment]
@ilyazub Feel free to reopen if you still need update on this
