### ISSUE TITLE
[Documentation]Yandex Knowledge Graph Documentation Example Needs Update 

### ISSUE THREAD

**Issue by paigebutler** [serpapi/public-roadmap#690]
In the Documentation, for the Yandex Knowledge Graph Documentation, "How I Met Your Mother" is used as the example. However, on Yandex, "How I Met Your Mother" no longer has a knowledge graph. Therefore, when you use the code integration in the documentation the result is blank (I have attached a screenshot.) A good update may be to change the documentation example to "friends" as that one still has a knowledge graph in Yandex.
<img width="806" alt="Screen Shot 2023-03-01 at 5 41 00 PM" src="https://user-images.githubusercontent.com/126518668/222488693-b49f35f1-5793-4b2d-9804-60f123b93f44.png">

**Comment by Ovi** [comment]
Seems like Yandex is not generating graph when `lr` param is present

**Comment by Krugloff** [comment]
@paigebutler Currently, the knowledge graph is not being parsed.

<img width="1455" alt="image" src="https://github.com/user-attachments/assets/acb30c8a-b3f3-499b-b830-4b3c83ac065f">

[Playground](https://serpapi.com/playground?engine=yandex&text=How+I+met+your+mother&yandex_domain=yandex.com&lang=en&lr=84)
[Inspect](https://serpapi.com/searches/6728df9fd910391a7d43c9fe/inspect)

**Comment by Krugloff** [comment]
The script referenced in the documentation should now function correctly.
