### ISSUE TITLE
[Google Shopping Api] New Top Features section

### ISSUE THREAD

**Issue by tanys123** [serpapi/public-roadmap#691]
<img width="1142" alt="Screenshot 2023-03-03 at 1 39 11 PM" src="https://user-images.githubusercontent.com/10222402/222640501-c72eafde-ad14-46bc-a200-5f6491c1852d.png">

Google shopping has this new section (Top features based on reviews) can be parsed.

[Playground](https://serpapi.com/playground?engine=google_shopping&q=nintendo+switch+game&newPara=lr+as_qdr)
[Inspect](https://serpapi.com/searches/63ef07b7681ebed058bc0beb/inspect)

**Comment by kagermanov27** [comment]
Just an update on the information. It's been here for a year. You may find the responsible code that was extracting them for js-comment structures at

https://github.com/serpapi/SerpApi/blob/ddfe9a30eb042c894b5ffd9393f3277e639aaab4/app/models/search/google_shopping/parser.rb#L140

That's for 1 year ago though. There might've been an update.
