### ISSUE TITLE
[Google Search Api] Top Stories mistakenly parse another section

### ISSUE THREAD

**Issue by tanys123** [serpapi/public-roadmap#693]
<img width="1278" alt="Screenshot 2023-03-03 at 1 49 08 PM" src="https://user-images.githubusercontent.com/10222402/222641924-3e34ca62-b5b1-4dd9-83c7-80f56319e6ac.png">

In this case, the action Top Stories are not parsed, instead the carousel under the first organic result is parsed. Probably we should include that inside the first organic result instead.

[Playground](https://serpapi.com/playground?q=NFL&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true)
[Inspect](https://serpapi.com/searches/64002c27c56d9379b18fc425/inspect)

**Comment by schaferyan** [comment]
A customer reported this issue:

[Inspector](https://serpapi.com/searches/654124bdd5ecf48b813f6b51/inspect)

[Google ](https://www.google.com/search?q=stock+market+today&oq=stock+market+today&uule=w+CAIQICIfTmV3IFlvcmssTmV3IFlvcmssVW5pdGVkIFN0YXRlcw&hl=en&gl=us&sourceid=chrome-mobile&ie=UTF-8)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000053108?view=List)

**Comment by ilyazub** [comment]
Related to https://github.com/serpapi/SerpApi/pull/4350#discussion_r1427026909
