### ISSUE TITLE
[Google Shopping API] Scrape 30-day low label

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#695]
Some Google shopping results have a label `30-day low` label

![image](https://user-images.githubusercontent.com/99160364/222698389-f4ac96d5-5544-425f-bb28-a96c61c6f5f4.png)

[Playground](https://serpapi.com/playground?engine=google_shopping&q=Apple+iPhone+12+Pro+5G+128GB+-+Gold&location=Sydney+CBD%2C+New+South+Wales%2C+Australia&google_domain=google.com.au&gl=au&hl=en&no_cache=true) | [Inspect](https://serpapi.com/searches/6401ccff3c3fb2f49bcbe8f3/inspect)

**Comment by kagermanov27** [comment]
@andypple83 Where do you think is a good place for it to be placed in the keys?
Also, did you come across it in any mobile results?
This way we can have a complete approach on how to deal with this.

**Comment by andypple83** [comment]
Yeah, let me try more searches on mobile. This result rarely appears. This result is more like a `refurbished` or `used` field.

**Comment by kagermanov27** [comment]
>This result is more like a refurbished or used field.
Quite unlikely. That is a second-hand condition and has a distinct class name on the desktop. Moreover, it has a distinct extraction in mobile searches as well.

My question was in the ballpark of if we should scrape it in tag (if they don't coexist in the same shopping result), extensions, or a separate field.

**Comment by btaunt** [comment]
We now extract the `30-day low` label (if present) into the existing `extensions` grouping for each item under `shopping_results`:

**Desktop**
<img width="734" alt="Screenshot 2024-03-21 at 11 13 50 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/d2db2abc-e013-49cb-83ea-8b16274e69f6">

**Mobile**
<img width="752" alt="Screenshot 2024-03-21 at 11 13 14 AM" src="https://github.com/serpapi/public-roadmap/assets/137819397/8a77d0bf-384f-468d-b3f0-d12c38a5dc0a">
