### ISSUE TITLE
[Google Maps API] Local Results return a single place

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#70]
Past Canny Conversation:
>Ilya: Some searches on Google Maps HTML with a single place. It's parsed as place_results
 instead of local_results
 which is correct. Direct searches on Google Maps return the same HTML.
Search with local_results
: 60c21d7fcace96c8fb71cfdb
Search with place_results
: 60c21d8dc7ad4172a24877de
How to force Google Maps to return a list of places for a type equals to search?
![image](https://user-images.githubusercontent.com/73674035/157692548-60b6aa1b-ba56-4508-89c6-c64c7c14c244.png)
![image](https://user-images.githubusercontent.com/73674035/157692567-fbb06df7-d918-4123-b7d5-77d445bef8c1.png)
---
[Past Canny Link](https://forum.serpapi.com/bugs/p/google-maps-local-results-return-a-single-place)

**Comment by aciddjus** [comment]
Closing this as it's not an issue.

List results can be returned when `ll` parameter is not provided: [Playground](https://serpapi.com/playground?engine=google_maps&q=ALI%C5%9E+P%C4%B0DE+BAFRA&hl=en&type=search&no_cache=true)

Or if GPS coordinates where places are located are provided: [Playground](https://serpapi.com/playground?engine=google_maps&q=ALI%C5%9E+P%C4%B0DE+BAFRA&ll=%4041.5673119%2C35.9008694%2C17z&hl=en&type=search)

<img width="2560" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/53f98ca1-b842-44d3-a920-e118947b9166">
