### ISSUE TITLE
[Google Search API] Scraping Incorrect Number of Reviews Depending on Location/Language

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#704]
A customer demonstrated that for results in French we are parsing the wrong number of reviews for rich snippets, whereas for results in English` we seem to parse this correctly:

![image](https://user-images.githubusercontent.com/30915304/223862763-91dfecd7-f013-4f19-a496-485eff573979.png)

![image](https://user-images.githubusercontent.com/30915304/223863318-835e2487-7844-44a4-86ce-bb973fd99442.png)

[Playground (U.S/Enlish)](https://serpapi.com/playground?q=24s+avis&location=Austin%2C+TX%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+client) | [Playground(France/French)](https://serpapi.com/playground?q=24s+avis&location=Paris%2C+Paris%2C+Ile-de-France%2C+France&google_domain=google.fr&gl=fr&hl=fr&google_domain=google.fr&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+client) | [Search inspector](https://serpapi.com/searches/640906a63944b0ef91bc657e/inspect)

**Comment by ilyazub** [comment]
Related to https://github.com/serpapi/public-roadmap/issues/658.
