### ISSUE TITLE
[Google Search API] `precipitation_forecast` missing from Weather Answer Box

### ISSUE THREAD

**Issue by ilslaoaycd** [serpapi/public-roadmap#706]
See in documentation, this is supposed to exist as an array. I depend on this for one of my services. 
https://serpapi.com/direct-answer-box-api#:~:text=precipitation_forecast

If you make a request for weather in an area, the precipitation_forecast array is missing from the JSON.
https://serpapi.com/search.json?q=Weather+for+New+York&location=Utah,+United+States&hl=en&gl=us&google_domain=google.com&key=[your api key]
Or if you do not have an api key, here is a cached version of my search: https://serpapi.com/searches/f94f751d48da6f74/640a281c0574f50540619491.json

**Comment by schaferyan** [comment]
From our [documentation](https://serpapi.com/direct-answer-box-api):
![image](https://user-images.githubusercontent.com/30915304/224149302-0186ba47-3250-42bf-9312-52c413c2e21e.png)

[Search Inspector](https://serpapi.com/searches/640a281c0574f50540619491/inspect) | [Playground](https://serpapi.com/playground?q=Weather+in+New+York&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+client)
