### ISSUE TITLE
[Google Shopping API] Searches are getting timed out

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#708]
One of our users reported that the searches in Google Shopping API seem to be getting timed out/taking longer than expected:

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/28161162/224643223-6b29834e-10d7-47af-ae3f-0414ddb1a5e5.png">

User's prolonged searches:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/28161162/224643340-5626381c-fecf-4c06-a485-27caa5acd60f.png">

User's timed-out searches:
<img width="457" alt="image" src="https://user-images.githubusercontent.com/28161162/224643429-425c3cc9-fb0b-4212-88a5-ffdd0b533e59.png">

[Playground](https://serpapi.com/playground?engine=google_shopping&q=8712856059072&location=France&google_domain=google.fr&gl=fr&hl=fr) | [Inspect](https://serpapi.com/searches/640ed9b62bc7d8e5cf921619/inspect)
[User's searches](https://serpapi.com/admin/searches?user_id=6086b0b9303eb125fb55302a)

**Comment by kagermanov27** [comment]
A notice for anyone having this problem:
These problems occur when you use `product_id` instead of a search query.

**Comment by marm123** [comment]
Another user is reporting the issue with long wait times for Google Shopping API calls. However, it could be an overall issue with proxies not working well at the moment and not particularly the same as reported in this thread.

[Intercom conversation](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000038560?view=List)
[User's searches](https://serpapi.com/admin/searches?user_id=63a96baccace96fb90fcb28a)

**Comment by schaferyan** [comment]
The user also reported their Google Shopping searches are taking the proxy location instead of using their Location parameters. For example they are getting results for Malaysia when they are supplying Manhattan, New York, United States:

[Users's Search](https://serpapi.com/searches/640f3dd5477c0ee31f7bc50c/inspect) | [Playground](https://serpapi.com/playground?engine=google_shopping&q=Decanter+set&location=Manhattan%2C+New+York%2C+United+States&gl=us&hl=en)

**Comment by kagermanov27** [comment]
Just a notice:
Those are not Product IDs in the sense we use them in SerpApi Ecosystem. These are GTIN numbers that are general identifiers you can find mostly on barcodes.

**Comment by marm123** [comment]
Customer examples:

[Inspect](https://serpapi.com/searches/643ceaf93e86ac7f1dabff95/inspect)
[Inspect](https://serpapi.com/searches/643ceaf73bea7b8c1c51a97e/inspect)

**Comment by kagermanov27** [comment]
putting the situation to `next` as we are back in operation.

**Comment by marm123** [comment]
The issue is back again. I'm changing it to urgent.
<img width="767" alt="image" src="https://user-images.githubusercontent.com/28161162/233349073-dfb0e6be-c682-4989-8423-38d485353fd8.png">

[User's profile](https://serpapi.com/admin/searches?user_id=6086b0b9303eb125fb55302a)
