### ISSUE TITLE
[Google Shopping API] Location Parameters Ignored for Some Searches

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#711]
A user reported their Google Shopping searches are taking the proxy location instead of using their Location parameters. For example they are getting results for Malaysia when they are supplying Manhattan, New York, United States:
![image](https://user-images.githubusercontent.com/30915304/224764219-22b18522-aa05-415b-b70f-df927552b236.png)

According to the `search_paramaters` in the example they shared, the Location the user provided is used, but some of the results are being returned in Malay.

[Users's Search](https://serpapi.com/searches/640f3dd5477c0ee31f7bc50c/inspect) | [Playground](https://serpapi.com/playground?engine=google_shopping&q=Decanter+set&location=Manhattan%2C+New+York%2C+United+States&gl=us&hl=en)

**Comment by schaferyan** [comment]
May be related to #708

**Comment by schaferyan** [comment]
The user who reported this shared another example: https://serpapi.com/searches/640f62d1f55d77c0f82f63a7/inspect

**Comment by ritu1337** [comment]
I think it should be good now, possibly was an issue with serpapi_proxy IP's.

**Comment by kagermanov27** [comment]
Just a notice:
Those are not Product IDs in the sense we use them in SerpApi Ecosystem. These are GTIN numbers that are general identifiers you can find mostly on barcodes.

**Comment by schaferyan** [comment]
@ritu1337 mentioned yesterday this one was probably due to an issue with one of the proxies and should now be fixed. I haven't heard of any more instances of it from our customers since then, so it may be good to go.

**Comment by kagermanov27** [comment]
I will still look into it to force a result type by playing with parameters and see if it could be applied on a scale.
