### ISSUE TITLE
[Google Search API] Scrape Air quality results

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#713]
Currently, we are not scraping Air quality results:

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/28161162/225537329-dec614de-9d9e-4681-9327-c8f253dbc8f3.png">

[Playground](https://serpapi.com/playground?q=air+quality&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/6412bb0f7d171aed3642055c/inspect)

**Comment by JeehoonChainPartners** [comment]
Please implement it asap.  Many people are interested in air quality...

**Comment by tanys123** [comment]
We have deployed this, feel free checkout the [example](https://serpapi.com/direct-answer-box-api#api-examples-air-quality-answer-box) in our documentation.

**Comment by JeehoonChainPartners** [comment]
Thx for your quick action

2023년 3월 27일 (월) 오후 8:03, Terry Tan ***@***.***>님이 작성:
