### ISSUE TITLE
[Google Local Results API] Differentiate sponsored listings from regular

### ISSUE THREAD

**Issue by wofguy** [serpapi/public-roadmap#717]
The json results from the Google Local Results API does not label sponsored results as a way to separate them from regular results.

[Playground](https://serpapi.com/playground?q=storage&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=lcl&device=desktop)
[Google Results](https://www.google.com/search?q=storage&oq=storage&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM&gl=us&tbm=lcl&sourceid=chrome&ie=UTF-8)
![image](https://user-images.githubusercontent.com/63465495/226069918-4375b8be-23fd-4cdd-bbec-7907b021beac.png)

**Comment by tanys123** [comment]
Sponsored will be added in this [PR](https://github.com/serpapi/SerpApi/pull/3500)
