### ISSUE TITLE
[Google Play Product API] No `reviews` in response

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#718]
Seems like we have issues with the parser as right now it doesn't extract reviews (no `reviews` hash key in the JSON). With `all_reviews: True` situation is the same.

[Playground](https://serpapi.com/playground?engine=google_play_product&product_id=com.google.android.youtube&gl=us&store=apps&all_reviews=true)  | [Search inspect](https://serpapi.com/searches/641572b89b6472a3f15a61b2/inspect)

End of the JSON response:

![image](https://user-images.githubusercontent.com/78694043/226094147-cd1d53a3-f48a-41f6-b87c-b89b0c74f99e.png)

Our docs shows (without `all_reviews` param) that response should contain `reviews` key:

![image](https://user-images.githubusercontent.com/78694043/226094288-485c59bc-8cf6-4dca-af67-c6622878013d.png)

**Comment by dimitryzub** [comment]
Just updating that this issue is still present 🐱

**Comment by ishiharaf** [comment]
@schaferyan Now the first page of reviews can be scraped along with the rest of the page. No need to set the `all_reviews` parameter to `true` as a workaround.

![image](https://github.com/serpapi/public-roadmap/assets/13112082/0e0fca97-c624-4663-bcf9-027bf4ddbb60)
