### ISSUE TITLE
[Google Shopping API] Searches with some special characters are failing

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#720]
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/73674035/226210930-a68aec67-371e-40a5-b97d-4e1d48827cc8.png">

[Playground](https://serpapi.com/playground?engine=google_shopping&google_domain=google.com&no_cache=true&q=%40%40%40%40%40%40%40)
[Inspect](https://serpapi.com/searches/64177c6c47ccf12164f149b5/inspect)

This should return empty results:
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/73674035/226210998-66dd4b60-8123-40cc-af83-50f5bde5f8f0.png">

**Comment by hartator** [comment]
Probably a small change in Google layout as top proxy error is `HTML Check Failed Basic Search Elements Missing`. Maybe regular empty searches are affected in addition of special characters ones? Bumping this to `urgent`.

**Comment by kagermanov27** [comment]
I made a mistake. This is Google Shopping API only. Yes, there is a change in the layout. But it isn't failing in Google Search API.

The solution to https://github.com/serpapi/public-roadmap/issues/167 is overkill nowadays.

**Comment by hartator** [comment]
> @hartator, should we put it to `next` back?

Sure. Thank you @kagermanov27. 👍

**Comment by ilyazub** [comment]
We have fixed this issue. We will now return an empty results error message instead of timing out.

![image](https://github.com/serpapi/public-roadmap/assets/282605/41b0d5b9-b6fb-4424-babc-976b0cb58818)

[Playground](https://serpapi.com/playground?engine=google_shopping&q=%40%40%40%40%40%40%40)
