### ISSUE TITLE
[Google Shopping Results API] Product_IDs of Some Products Not Returned

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#724]
Google Shopping Results API currently does not return product_id for some products. I am not sure if this is due to the fact that products have no respective pages or our parser is having difficulties in scraping them.

![product_id_bug1](https://user-images.githubusercontent.com/64849049/226347320-89b261bd-415c-4901-a186-e98b817d1285.png)

[Playground Link](https://serpapi.com/playground?engine=google_shopping&q=zara&location=Sweden&google_domain=google.se&gl=se&hl=sv&tbs=mr%3A1%2Croot_cat%3A529385&num=100) | [Inspect Link](https://serpapi.com/searches/6418517beb690f5ba3a52e35/inspect) | [Google Shopping Link](https://www.google.se/search?tbm=shop&q=zara&oq=zara&uule=w+CAIQICIGU3dlZGVu&hl=sv&gl=se&num=100&sourceid=chrome&tbs=mr:1,root_cat:529385&ie=UTF-8)

One of our users [recently posted this issue](https://github.com/serpapi/public-roadmap/issues/97#issuecomment-1476073566) in the [old thread (#97) which was the same issue](https://github.com/serpapi/public-roadmap/issues/97).

**Comment by marm123** [comment]
I'm marking it as urgent, as it affects both Google Shopping and Google Product APIs users and their production.

**Comment by ilyazub** [comment]
Links to the products without ID are to external websites.

Here's a product with an ID from the [search above](https://serpapi.com/searches/6418517beb690f5ba3a52e35/inspect): 

![image](https://user-images.githubusercontent.com/282605/226854297-ae3f4775-3ba8-4260-878f-89d352f7ac7e.png)

This issue is related to https://github.com/serpapi/SerpApi/pull/2789.

**Comment by marm123** [comment]
Thank you, @ilyazub. Are we no longer able to extract product_id for each search? I mean, they all have similar product pages, but only one (or a couple) returns product_id while the others don't. Does it look like a change on Google's side, and is there any workaround? Wdyt?

**Product page for the item with product_id:**
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/28161162/226859050-938eb94f-0201-47f1-8f9d-543f36d8a4cd.png">

**Product page for the item without product_id:**
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/28161162/226859430-52665673-114d-4659-87f3-8503ddf709e2.png">

**Comment by aciddjus** [comment]
@ilyazub We can still extract `product_id`

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/6929257/226934721-f7436003-9837-4e2e-baf5-95d9be446611.png">

The fix we added [here](https://github.com/serpapi/SerpApi/pull/3021) was reverted in https://github.com/serpapi/SerpApi/pull/2999
