### ISSUE TITLE
[Accounts API] Provide the monthly subscription cost.

### ISSUE THREAD

**Issue by Jijalba** [serpapi/public-roadmap#726]
In our use case, we would like to estimate how much a Project (Group of searches) costs to charge the application's usage to the respective department.

In order to do that, we get the different Google APIs we use and estimate the total searches we will need, using this information we can merge it with the data in Accounts API and get the percentage of usage the project would use for our monthly cap.

For example, if we do a Project with 
10 keywords, 10 locations in only 1 API (Google Shopping e.g.), and knowing that we have 15.000 monthly searches to use, we would know that this project is using 100 searches (10*10*1= 100)  and it would be around 0,66% (100/15000) of our monthly subscription.

In this case, we would like to know how much money that is and, as the price would change in time with new subscription plans, new limits, or business rules, we wouldn't like to hardcode it as a number.

**Comment by dimitryzub** [comment]
@Jijalba whenever you can, could you please try on your end accessing `plan_monthly_price` key via [account API](https://serpapi.com/account-api)?

![image](https://user-images.githubusercontent.com/78694043/230045298-29db21ed-2712-4104-814a-31da5144a9eb.png)
