### ISSUE TITLE
[Google Maps API] Support filtering by rating and hours

### ISSUE THREAD

**Issue by tanys123** [serpapi/public-roadmap#728]
<img width="160" alt="Screenshot 2023-03-15 at 2 03 05 PM" src="https://user-images.githubusercontent.com/10222402/226547456-69ca335a-621f-45d9-80bb-5ea54ca99653.png">
<img width="362" alt="Screenshot 2023-03-15 at 2 03 08 PM" src="https://user-images.githubusercontent.com/10222402/226547475-1e39ec0a-fb05-4ea7-8a75-ade320a48cd4.png">

In Google Maps search, there are rating and hours filter that allow user to have more refine searches. This can be an enhancement to the Google Maps API

[Google Link (4 stars and above, Open 24 hours)](https://www.google.com/maps/search/Coffee/@2.9263597,101.6184002,14z/data=!3m1!4b1!4m5!2m4!5m2!2e3!4e3!6e5?hl=en)

**Comment by aciddjus** [comment]
This has been resolved.

![image](https://github.com/serpapi/public-roadmap/assets/6929257/709bd28b-772e-4437-b477-fd7609381568)

-----------------

[Playground](https://serpapi.com/playground?engine=google_maps&q=Coffee&ll=%402.9263565%2C101.5565979%2C12z&hl=en&data=!3m1!4b1!4m5!2m4!5m2!2e3!4e3!6e5&type=search)

Resolved in: https://github.com/serpapi/SerpApi/pull/4826
