### ISSUE TITLE
[Google Search API] `device` ignored for some searches

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#739]
A customer shared a search in which the `device` parameter is ignored. Desktop results appear to be served instead of Mobile. The `organic_results` are also not parsed in the search, perhaps as a result. I was unable to replicate it in the playground.

<img width="1153" alt="Screenshot 2023-03-23 at 12 53 38 PM" src="https://user-images.githubusercontent.com/30915304/227336241-68c5d376-d88a-48db-8b4f-d7f9b525ae3b.png">

[Search Inspector](https://serpapi.com/searches/641c6d85359e993b931c3609/inspect) | [Playground (unable to replicate)](https://serpapi.com/playground?q=Stuttering+treatment&gl=us&hl=en&device=mobile)

**Comment by hartator** [comment]
The customer left additional screenshot and information on Intercom: https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000038942

**Comment by hartator** [comment]
I've actually managed to reproduce once: https://serpapi.com/searches/641cc2be2c0844862cc98df3/inspect

**Comment by tanys123** [comment]
Similar issue happened before, it has to do with proxy. https://github.com/serpapi/public-roadmap/issues/623

**Comment by ritu1337** [comment]
The issue should be resolved now, retrying affected searches works 👍

**Comment by ilyazub** [comment]
[Another Search Inspect page](https://serpapi.com/searches/642baf35c9990305ba4d7473/inspect) with desktop instead of mobile results.

Seems to be related to one of the proxy providers that we use. I've asked their support to fix this issue.

**Comment by marm123** [comment]
Another example provided by one of our users:

[Inspect](https://serpapi.com/searches/642bbd012c08440669b77ea4/inspect) | [Intercom thread](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000039404?view=List)

**Comment by schaferyan** [comment]
User who originally reported this had 26 more instances this morning. Here is the screenshot they shared:

![kane@contentharmony_failed_searches2](https://user-images.githubusercontent.com/30915304/229849261-1553c0b5-7f05-4f99-8099-ceadbe461a4e.png)
