### ISSUE TITLE
[Google Events API] Scrape events in different languages for different locations

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#740]
Currently, we are only scraping results in English. However, if I search from a specific location (using VPN connections) with the `hl` parameter corresponding to that country, I can get results in different languages:

Results in German (using VPN connection to Germany):
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/28161162/227582411-8eea6172-1568-42df-a0b7-94eb0a03e829.png">

Results in Spanish (using VPN connection to Spain):
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/28161162/227581662-933a4016-e94d-4e84-8998-0a84459331f7.png">

**Comment by scriptify** [comment]
Great!
