### ISSUE TITLE
[Google Images API] Scrape Related content

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#741]
I'm unsure how feasible this is, but we can try and scrape the Related content, which appears after clicking an image in Google Images:

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/28161162/227864532-efa8b81b-e2b2-491b-ab7f-58091f260740.png">

[Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=isch) | [Inspect](https://serpapi.com/searches/64213f350ead41189ab351bf/inspect) | [Google](https://www.google.com/search?q=Coffee&oq=Coffee&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM&gl=us&tbm=isch&sourceid=chrome&ie=UTF-8)

**Comment by GabrielBianconi** [comment]
+1
