### ISSUE TITLE
[New API] Add Google Finance API

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#75]
>Alaa: https://www.google.com/finance/
![image](https://user-images.githubusercontent.com/73674035/157697633-db0e1f03-882a-49f0-b0eb-1a96a156287a.png)

---

[Past Canny Link](https://forum.serpapi.com/feature-requests/p/add-google-finance-api)

**Comment by dimitryzub** [comment]
@kagermanov27 you meant Google Finance Main page `https://www.google.com/finance/` or Quote page `https://www.google.com/finance/quote/GOOGL:NASDAQ`, or both?

**Comment by dimitryzub** [comment]
Moved to https://github.com/serpapi/public-roadmap/issues/75.

**Comment by dimitryzub** [comment]
Unasigning myself as I didn't worked on it from April.

**Comment by schaferyan** [comment]
Closing this since it was completed.
