### ISSUE TITLE
[Google Play Movies API] Some Category Searches in different regions are giving infinite timeout

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#750]
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/73674035/227909756-9eb46cd5-4ae1-42a9-b580-2382e50fd5c8.png">

[Playground](https://serpapi.com/playground?engine=google_play&gl=tr&hl=en&store=movies&movies_category=MOVIE&no_cache=true)

[Inspect](https://serpapi.com/searches/642166c61c450afb9fecc0bb/inspect)

`freezer` because of the volume of such search is low.

**Comment by aciddjus** [comment]
Closing this as I wasn't able to replicate the issue. We are returning empty results for unsupported countries.

<img width="2560" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/44b70d63-cf32-42e3-9eea-7984d4672f04">
