### ISSUE TITLE
[Yahoo Search API] Searches Returning Empty Results

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#751]
One of our Enterprise users notified us that about 20% of their Yahoo searches are coming back empty. The example they shared produces results both in a manual Yahoo search as well as in our Playground with the same parameters.

<img width="1151" alt="Screenshot 2023-03-28 at 9 17 32 AM" src="https://user-images.githubusercontent.com/30915304/228304311-5f46f812-d061-488a-80f8-956213bfc056.png">

[Playground](https://serpapi.com/playground?engine=yahoo&p=explain+divinity+concept+in+23+words&vl=lang_en) | [Search Inspector](https://serpapi.com/searches/6422d34495bf9226b7b61af8/inspect) | [Yahoo](https://search.yahoo.com/search;_ylt=AwrjW6v7ECNknG8H4dBDDWVH;_ylc=X1MDMTE5NzgwNDg2NwRfcgMyBGZyAwRmcjIDcDpzLHY6c2ZwLG06c2ItdG9wBGdwcmlkA2JvLkIxbnl5UmN1b081NEhmYl9MbEEEbl9yc2x0AzAEbl9zdWdnAzQEb3JpZ2luA3NlYXJjaC55YWhvby5jb20EcG9zAzAEcHFzdHIDBHBxc3RybAMwBHFzdHJsAzM2BHF1ZXJ5A2V4cGxhaW4lMjBkaXZpbml0eSUyMGNvbmNlcHQlMjBpbiUyMDIzJTIwd29yZHMEdF9zdG1wAzE2ODAwMTk3MTg-?p=explain+divinity+concept+in+23+words&fr=sfp&fr2=p%3As%2Cv%3Asfp%2Cm%3Asb-top&iscqry=)

**Comment by tanys123** [comment]
Not able to reproduce as of now.

**Comment by ilyazub** [comment]
Reproduction: [Search Inspect #1](https://serpapi.com/searches/6423e04d94fb03e849fcb925/inspect), [#2](https://serpapi.com/searches/6423e3061071f486c4bf8e62/inspect), [#3](https://serpapi.com/searches/6423e352fe41d0673cbfca0a/inspect), [#4](https://serpapi.com/searches/6423e3529790543873de13bb/inspect).

**Comment by schaferyan** [comment]
The customer reported they experiencing more empty result sets:

![empty_responses_2](https://user-images.githubusercontent.com/30915304/230927395-e32aa68a-e995-46c1-8428-c21c567e2f68.png)
<img width="1272" alt="empty_responses" src="https://user-images.githubusercontent.com/30915304/230927400-1e0ceee9-99ac-49d4-9a2c-5a7d6d9e85ee.png">

**Comment by chibuezedev** [comment]
I believe that the structure of the web page they are scraping may have changed which implies that the spiders crawling will miss out at some points. I would love to take this up.

**Comment by ilyazub** [comment]
@schaferyan Has anyone recently reported this issue again? ([_Previous Intercom thread_](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000036506?view=List).)

**Comment by schaferyan** [comment]
No, I haven't heard anything about this since the above comment in July. It may be that Yahoo Search doesn't see that much use and the issue just hasn't come up in a significant enough way for anyone to report.

I'm going to leave it open but remove the urgent label, as it may still be an issue but it doesn't seem to be urgent anymore.
