### ISSUE TITLE
[Google Sheets Extension] An error is raised when domain doesn't appear in `SERPAPI_RANK`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#756]
Instead of the regular `-` sign, whenever the domain is not found in API call results, users are not receiving `SyntaxError: No number after minus sign in JSON at position 1 (line 543).`

**Current State:**
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/28161162/229043816-645af6e5-b6e2-45cf-baa8-983ab59d1af2.png">

**Expected behaviour:**
![image](https://user-images.githubusercontent.com/28161162/229043128-5e47141c-23ca-424c-8e23-edec6d94d376.png)

**Comment by tanys123** [comment]
<img width="454" alt="Screenshot 2023-04-10 at 6 25 43 PM" src="https://user-images.githubusercontent.com/10222402/230884397-03aa3c81-57cd-420f-9f89-ba692bfa8f6b.png">

Deployed a fix.
