### ISSUE TITLE
[Home Depot API] Add a List of Store IDs and Zip Codes

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#76]
Like Walmart API's [list](https://serpapi.com/walmart-stores), our Home Depot API needs a list of store IDs and zip codes. Our users can then loop through them; mostly to extract price and stock availability data.

**Bangor Store ID example**: 2414 
https://serpapi.com/playground?engine=home_depot&q=Coffee&store_id=2414
https://www.homedepot.com/l/search/2324

Home Depot store selector widget:

<img width="949" alt="homedepot_stores" src="https://user-images.githubusercontent.com/64849049/157857516-3fee6fcf-7b70-46de-99e9-e08dd976bacc.png">

Home Depot store selector:

<img width="943" alt="homedepot_stores_finder" src="https://user-images.githubusercontent.com/64849049/157857727-f20c1e93-cca9-4fb6-a821-814bdd5450c3.png">

**Comment by marm123** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000043044?view=List)

**Comment by schaferyan** [comment]
This customer shared CSV files listing Home Depot store IDs in the U.S and in Canada respectively:
[Canada-HomeDepotStores_geocodio_d0c5470ed8b5f7a4451f8bb176e779ce75841a38 (1).csv](https://github.com/serpapi/public-roadmap/files/12323289/Canada-HomeDepotStores_geocodio_d0c5470ed8b5f7a4451f8bb176e779ce75841a38.1.csv)
[USA_HomeDepotLocations_GeoCoded.csv](https://github.com/serpapi/public-roadmap/files/12323290/USA_HomeDepotLocations_GeoCoded.csv)
