### ISSUE TITLE
[Home Depot] Scrape Store SKU Number

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#77]
<img width="959" alt="home_depot_store_sku" src="https://user-images.githubusercontent.com/64849049/158153101-149b3e79-a92a-404d-a4e4-a35c5964b15a.png">

Refs:
- https://www.homedepot.com/p/Kwikset-Satin-Nickel-Single-Cylinder-Deadbolt-featuring-SmartKey-Security-with-Microban-Antimicrobial-Technology-98015SMTCPK4V1/309567384
- https://www.homedepot.com/p/Hampton-Bay-Braxton-Park-3-Piece-Black-Steel-Outdoor-Patio-Sectional-Sofa-with-CushionGuard-Chili-Cushions-505-0851-000/313436371

Home Depot shows store SKU number for some of the products. This information can be scraped if present on the page.

[Playground](https://serpapi.com/playground?engine=home_depot_product&product_id=309567384) - [Inspect](https://serpapi.com/searches/622f162a2f542e65da52e574/inspect) Both no SKU. Maybe because it's mobile view?

**Comment by marm123** [comment]
This has been requested once again recently.

<a href="https://app.intercom.com/a/apps/yzck75jr/inbox/inbox/all/conversations/102910000033925">Intercom Thread</a>

**Comment by schaferyan** [comment]
This has been requested again:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040401?view=List)

The latest user requesting this can possibly only use our services if we support this.
