### ISSUE TITLE
[Google Search API] `kgmid` is not extracted in `knowledge_graph`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#772]
It looks like the `kgmid` key is missing from the JSON response for most searches:

**Playground search:**
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/28161162/230074064-17b1258d-0fed-40c1-892c-a3483d06dbbc.png">
**Google Search:**
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/28161162/230074558-3d28dc64-6fb9-4387-8205-a14d91d2a1a6.png">
**Page Source:**
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/28161162/230074724-30f85db3-23cc-41dc-a0c3-c1193c97d5db.png">

[Playground](https://serpapi.com/playground?q=Aigburth&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/642d6166033e946cc28e5d7e/inspect) | [Google Search with the `kgmid` parameter](https://www.google.com/search?kgmid=/m/01tqx_)
[Playground](https://serpapi.com/playground?q=Allerton%2C+Liverpool%2C+United+Kingdom&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/642d611ea5ad6d2c263c7739/inspect) | [Google Search with the `kgmid` parameter](https://www.google.com/search?kgmid=/m/01tqzf)

**Comment by Toffee1878** [comment]
Looking forward to seeing this working again.

**Comment by ckosmic** [comment]
This issue seems to have popped up again.
[Playground 1](https://serpapi.com/playground?q=Minecraft&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&newPara=source)
[Playground 2](https://serpapi.com/playground?q=Vikings%3A+Valhalla&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&newPara=source)

<img width="1280" alt="image" src="https://github.com/serpapi/public-roadmap/assets/17561672/813e89d3-f3f2-4e04-98f1-00cc22dadc05">

**Comment by Mrtierne** [comment]
Seeing the issue as well

**Comment by schaferyan** [comment]
Reopening this, since the comments above indicate it's become a problem again

**Comment by marm123** [comment]
Fixing this might help with getting the `city_id` for the Google Flights API. Reference: https://github.com/serpapi/public-roadmap/issues/1344#issuecomment-1886439184

**Comment by martin-serpapi** [comment]
Another customer reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000057262?view=List)

**Comment by dmeltdown** [comment]
I just checked on this and it still appears to be broken.

**Comment by andypple83** [comment]
Thanks for reporting this issue. Google changed the encoding for their page source. I'll fix this issue soon. 

![Screenshot 2024-01-23 at 21 47 22](https://github.com/serpapi/public-roadmap/assets/99160364/ba8a1ec0-02fa-4e28-ab79-d6ab45750f23)

**Comment by dmeltdown** [comment]
great!  thank you.

its also here:
![google kgmid](https://github.com/serpapi/public-roadmap/assets/154466906/fcf538d6-5bdd-41eb-bf6c-8daf750e66fc)

**Comment by andypple83** [comment]
Thanks @dmeltdown, we're scraping all these places to make sure it's available in our results.

**Comment by dmeltdown** [comment]
Hi @andypple83,  Any updates on getting the KGMID results to show back up?

**Comment by redsparkautonetmedia** [comment]
For Vehicles it is usually in 4 different places in page source

data-maindata='[null,"/g/11sbdqtgc8","2023 Acura TLX",

,"/g/11sbdqtgc8","2023 Acura TLX",null,["CARS"],

https://www.google.com/search?kgmid\u003d/g/11sbdqtgc8\u0026hl\u003den-US

,"2023 Acura TLX",[277,"51+","/g/11sbdqtgc8",


Here is link: view-source: view-source:https://www.google.com/search?q=2023+acura+tlx&sca_esv=35124072aa3934e9&rlz=1C1CHBF_enUS920US920&ei=mCm7ZdTWAeGv5NoPrOW34AY&gs_ssp=eJzj4tVP1zc0LE5KKSxJT7YwYPTiMzIwMlZITC4tSlQoyakAAJEHCVM&oq=2023+acura+tlx&gs_lp=Egxnd3Mtd2l6LXNlcnAiDjIwMjMgYWN1cmEgdGx4KgIIADIREC4YgAQYigUYkQIYsQMYgwEyBRAuGIAEMgoQLhhDGIAEGIoFMgUQABiABDIFEAAYgAQyChAAGIAEGIoFGEMyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMiAQLhiABBiKBRiRAhixAxiDARiXBRjcBBjeBBjgBNgBAUivGFAAWO4FcAB4AZABAJgBaaABgAKqAQMyLjG4AQHIAQD4AQHCAg4QLhiRAhixAxiABBiKBcICHRAuGJECGLEDGIAEGIoFGJcFGNwEGN4EGOAE2AEBwgIREC4YgwEYkQIYsQMYgAQYigXCAiAQLhiDARiRAhixAxiABBiKBRiXBRjcBBjeBBjgBNgBAeIDBBgAIEG6BgYIARABGBQ&sclient=gws-wiz-serp

**Comment by marm123** [comment]
Hi @dmeltdown and @redsparkautonetmedia. Thank you guys very much for following up on this thread. I wanted to let you know that we're currently working on this issue, and a pull request was created to resolve it. However, it requires some additional reviews before we can merge it.

Thank you so much for your patience!

**Comment by mertzdog** [comment]
I am having this same problem. An Idea when there will be a fix?

**Comment by andypple83** [comment]
Thanks everyone. The kgmid field should be available in our SerpApi results. Thanks

**Comment by martin-serpapi** [comment]
Reopening the issue as another hight volume customer reported that `kgmid` is not returned in the response for some searches. I was able to reproduce it in the Playground:

<img width="1398" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/88769c98-f60c-4b13-a1a5-668a9661b08e">

[Playground](https://serpapi.com/playground?q=Bob+Evans+Restaurant+Camden&location=Camden%2C+Delaware%2C+United+States&gl=us&hl=en&google_domain=google.com&newPara=chips+stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+as_epq+client) | [Inspect](https://serpapi.com/searches/664f76e4e4a23db2ccd9445c/inspect)

<img width="1394" alt="image" src="https://github.com/serpapi/public-roadmap/assets/144151895/58c303a0-f4a2-41a0-a961-ab7cfb8661f5">

[Google Search](https://www.google.com/search?kgmid=/g/1w_vp7d9)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000066769?view=List)

**Comment by andypple83** [comment]
We've released a fix for this. The `kgmid` should be present in search results.

![Screenshot 2024-06-03 at 20 44 58](https://github.com/serpapi/public-roadmap/assets/99160364/7a432ff5-293b-4594-b18c-9de28db3b96f)
