### ISSUE TITLE
Google job returns empty

### ISSUE THREAD

**Issue by wejarrard** [serpapi/public-roadmap#773]
Hi, when i use your engine to search google jobs using the python API, I get this:

'search_information': {'jobs_results_state': 'Fully empty'}, 'error': "Google hasn't returned any results for this query."

my search is this:
search = "Life science investment analyst san francisco"

Any help would be much appreciated

**Comment by wejarrard** [comment]
By the way, this only happens if i try to search something more than once

**Comment by tanys123** [comment]
Hi @wejarrard, thanks for reporting the issue, can you provide the search ID (you can find it at https://serpapi.com/searches)?
