### ISSUE TITLE
[Ebay API] Scrape Number of Stock Sold

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#775]
Some products on eBay show a number of items sold. We can scrape this for results that include it. A customer has requested this feature.
<img width="1466" alt="Screenshot 2023-04-06 at 10 25 54 AM" src="https://user-images.githubusercontent.com/30915304/230453068-0d55c773-f1c6-4a47-919a-3f7c89efa013.png">
[Playground](https://serpapi.com/playground?engine=ebay&_nkw=Coffee&ebay_domain=ebay.com) |[ Search Inspector](https://serpapi.com/searches/642effd366440ab9a7a229d2/inspect)

**Comment by hartator** [comment]
> A customer has requested this feature.

Can you share the Intercom link next time? Thank you!
