### ISSUE TITLE
[Google Trends API] Internal Error on Some Searches  

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#776]
A user reported they are receiving an internal error on Google Trends searches. I can't identify a clear pattern in the searches that fail, or replicate it in the playground. In the Search Inspector, the error is shown as `783: Unexpected Token At 'Lang=En><Meta Charset=Utf 8><Meta Name=Viewport Content="Initial Scale=1, Minimum Scale=1, Width=Device Width"><Ti`
In the Intercom, the user also shares some details about which searches have and have not worked.
<img width="1151" alt="Screenshot 2023-04-06 at 3 26 00 PM" src="https://user-images.githubusercontent.com/30915304/230505299-c5f414c8-cade-42f9-9eb3-716c29f0e562.png">

 [Search Inspector](https://serpapi.com/searches/642b643137b24a20153d794c/inspect) | [Search Inspector (successful)](https://serpapi.com/searches/642b46dcb5961ec04e871087/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000039532?view=List)

Failed Search ids:
642f3ef32bc7d8bbf72914a5
642f3510a4bb38d91a871167
642b643137b24a20153d794c
642f46018ccee0d3be9085b4

**Comment by marm123** [comment]
Another Customer reported the issue.

[Inspect](https://serpapi.com/searches/643ec60c8b7ed234e6fcdaff/inspect)
[Inspect](https://serpapi.com/searches/643ec60c8b7ed234e6fcdaff/inspect)
[Inspect](https://serpapi.com/searches/643ec60c2d5b128f8c14eea0/inspect)
[Inspect](https://serpapi.com/searches/643ec62ed04d6d0390931755/inspect)
[Inspect](https://serpapi.com/searches/643ec6aa224db12213cd85c9/inspect)
[Inspect](https://serpapi.com/searches/643ec6ac9d1586e6e967d931/inspect)
[Inspect](https://serpapi.com/searches/643ec6ac9d1586e6e967d931/inspect)
[Inspect](https://serpapi.com/searches/643ec6c6c573d5aeea36523e/inspect)
[Inspect](https://serpapi.com/searches/643ec6d09f55b3d1705039b9/inspect)
[Inspect](https://serpapi.com/searches/643ec6d611c8818221c764a7/inspect)

[Intercom thread](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040058?view=List)

**Comment by ilyazub** [comment]
Root cause: https://github.com/serpapi/SerpApi/issues/1482#issuecomment-1521464199

**Comment by aliayar** [comment]
Another user reported having this issues:

[Google trends API errors occurred many times today.](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000041169?view=List)
