### ISSUE TITLE
[Google Lens API] Specify Location for Google Lens Searches

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#788]
A user requested the ability to retrieve result sets for a specific country or location when searching with Google Lens. They shared a link to a search they performed in their browser in incognito mode that delivers results specifically for the UK. Is this something we can support?

<img width="1452" alt="Screenshot 2023-04-13 at 9 13 11 AM" src="https://user-images.githubusercontent.com/30915304/231821710-693f67a4-3349-483a-9376-d32f29f4b713.png">

[Google Lens](https://lens.google.com/search?p=ARADZa4qkp59oTdHAqkosuUE_SuZBzn66vEVrP85M9okf6h-m2cFnADArge4ecsg2AkgpyzpoUxHrYFlggCr16GduLYL9qITTiKJF4n8zDYD3ZCPn1v1C7WHSAiwgyvVv3mtOJSpXGt8g8RMhDoSr4FO-lPZIDVw1DyWGhzqtHhC30P-CZFn3zWR6zm1VYmgvx-HNXMADFr4LIbGbKZ5QClFJUS4kfbtQzm8P0fnpBXth6dESfTuk6jF5GWx2Ohyxls5DQ97oPFFKmCOFGqeqvRtaEapjd_LNLcvYiVIko4%3D&ep=gsbubb&hl=en-GB&re=df#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKRFEzTkRFMU5EVmxMVFExTURFdE5EQXlOaTFoTTJNMExUWmxOMkpoTnprNFpXTXlZUklmVlRKbk5YUjRRV0p2Tm1kV1VVUjFWV2RKVkUxaWJEWjNVR0poTUdSNFp3PT0iXQ==)

**Comment by marm123** [comment]
Another user requesting this feature:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000041867?view=List)

**Comment by marm123** [comment]
Another customer requesting it:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042186)

**Comment by marm123** [comment]
Another customer requested this feature:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042239)

**Comment by marm123** [comment]
We have another customer requesting this feature:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042948?view=List)

**Comment by schaferyan** [comment]
Another user asked for this - they also asked that we support `google_domain`.

https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000048752?view=List

**Comment by ilyazub** [comment]
> Another user asked for this - they also asked that we support `google_domain`.

`google_domain` can't be supported. Google Lens provides the single domain so far: `https://lens.google.com`.

Probably, we (SerpApi) can add support for Google Lens locations by using country-specific IPs when making requests.

**Comment by schaferyan** [comment]
@ilyazub Is that something we can support? I've discussed using country specific IPs for other reasons with @hartator, and my understanding is that it would require too many resources to maintain available proxies in every country.

**Comment by ilyazub** [comment]
@schaferyan We already use the country specific IPs for our Google Maps API: https://github.com/serpapi/SerpApi/pull/3199.

**Comment by kagermanov27** [comment]
I have shared investigation notes of the problem at:

https://github.com/serpapi/SerpApi/issues/4117

**Comment by MartySVK** [comment]
this would be very useful, hope it will be ready soon.

**Comment by schaferyan** [comment]
Another user with a relevant request:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000050377?view=List)
