### ISSUE TITLE
[Google Trends API] Some searches have no data

### ISSUE THREAD

**Issue by cannertang** [serpapi/public-roadmap#790]
key word:
彈珠

Search ID: 
6438c4035119a6ef2e8315bc

The same conditions, google trends official website search has information.
https://trends.google.com.tw/trends/explore?date=today%201-m&geo=TW&q=%E5%BD%88%E7%8F%A0

**Comment by dimitryzub** [comment]
Related:
- https://github.com/serpapi/public-roadmap/issues/556

Possibly related:
- https://github.com/serpapi/public-roadmap/issues/561

**Comment by ilyazub** [comment]
Duplicate of https://github.com/serpapi/public-roadmap/issues/556.
