### ISSUE TITLE
[Apple App Store Reviews API] False Empty Results for Desktop App `product_id`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#801]
Unfortunately, I was not able to recreate the issue with more than one example, but looks like the Apple App Store Reviews API is getting stuck with certain `product_ids`:

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/28161162/233085839-862b2573-6532-40dd-bd63-e810bbbe0adb.png">

[Playground](https://serpapi.com/playground?engine=apple_reviews&product_id=889922906&no_cache=true) | [Inspect](https://serpapi.com/searches/643fe880af5af11bd88ef839/inspect)

**Comment by kagermanov27** [comment]
The product ids for the mac app store is returning 

```
pings metrics dialogIditemNotAvailable messageThe item you’ve requested actionUrlitunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?pageNumber=0&id=1099454186&sortOrdering=0&type=Purple+Software eventTypedialog failureType customerTitleMessageItem Not Available customerMessageThe item you’ve requested is not currently available in the U.S. store. m-allowed dialog m-allowed messageItem Not Available explanationThe item you’ve requested is not currently available in the U.S. store. defaultButtonok okButtonStringOK initialCheckboxValue cancel-purchase-batch
```

which combined with checking for the right country is leading to a timeout:
```rb
!(response[:html].include? "cc=#{self.country}")
```

These are not valid empty results though, they should've been present as they have pages on App Store.

Example:
https://apps.apple.com/us/app/jumpshare-screen-recorder/id889922906?mt=12

**Comment by kagermanov27** [comment]
@tanys123 I am taking over the second part of this issue: Mac App ids not working. I have a working solution I am working on right now.
