### ISSUE TITLE
[Google Search API] Tops Sights Missing `thumbnail`, `rating`, and `reviews`

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#802]
A customer complained that we are not currently parsing the `thumbnail`, `rating`, or `reviews` from top sites blocks.

<img width="1465" alt="Screenshot 2023-04-19 at 10 03 07 AM" src="https://user-images.githubusercontent.com/30915304/233149543-8458db59-babc-4304-8483-1011b84d1942.png">
<img width="649" alt="Screenshot 2023-04-19 at 9 57 10 AM" src="https://user-images.githubusercontent.com/30915304/233149573-028081a3-4149-4c6d-aff7-f8d1a4b0bd97.png">

[Playground](https://serpapi.com/playground?q=top+sights+in+paris&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Search Inspector](https://serpapi.com/searches/64401db6cace96fd055b520c/inspect)

**Comment by hartator** [comment]
> A customer

@schaferyan Can you share the Intercom thread? Thank you!

**Comment by schaferyan** [comment]
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040072?view=List)
