### ISSUE TITLE
[Google Search API] Scrape website's source title

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#803]
One of our customers requested to scrape the website's domain source title:

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/28161162/233267396-cfb55be1-e52a-4843-82a4-0e7d356753cd.png">

[Playground](https://serpapi.com/playground?q=Football&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/6440cdc6c99903b7c506fa56/inspect)

**Comment by schaferyan** [comment]
Another customer requested this:

https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040414?view=List
