### ISSUE TITLE
[Google Local Results API] Mobile and tablet searches return no `gps_coordinates`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#807]
We can extract `gps_coordinates` with Google Local Results API, but only on the desktop version. I'm unsure if Google doesn't provide them for mobile searches or if this is something that we can but do not extract at the moment.

Desktop Search:
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/28161162/233666293-a94752ea-aa9b-4a83-8a9d-81af8d012e17.png">

Tablet Search:
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/28161162/233665824-7e852b15-436d-4aef-884a-c6894b3d3eb7.png">

Mobile search:
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/28161162/233665923-6023c872-fd31-4d52-af9e-54e78dee2e43.png">

[Playground desktop](https://serpapi.com/playground?engine=google_local&q=Coffee&device=desktop) | [Inspect desktop](https://serpapi.com/searches/64429fcbf8f5f7ec3542d4ad/inspect)
[Playground tablet](https://serpapi.com/playground?engine=google_local&q=Coffee&device=tablet) | [Inspect tablet](https://serpapi.com/searches/6442a007f0adfb4f5396cca6/inspect)
[Playground mobile](https://serpapi.com/playground?engine=google_local&q=Coffee&device=mobile) | [Inspect mobile](https://serpapi.com/searches/64429feae0ded48df7ea4571/inspect)

**Comment by hartator** [comment]
@marm123 Can you also share the Intercom link if there is a conversation? Thank you.

I am closing this, but feel free to re-open if an user has asked for it.

**Comment by schaferyan** [comment]
It looks like Bartek opened this one based on this conversation:

https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000040164?view=List

**Comment by marm123** [comment]
Yes, I forgot to add the Intercom thread. A customer requested this. Thank you @schaferyan

**Comment by aciddjus** [comment]
Unfortunately, I don't think there are GPS coordinates for each specific place on mobile.

But we can still extract map GPS coordinates:

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/6929257/234008892-725864f2-d5fa-4da2-b71c-d87f4644ecd2.png">

**Comment by btaunt** [comment]
The `gps_coordinates` seem to be properly parsed on both `tablet` and `mobile` now. (based off the above Playground searches)

<img width="776" alt="Screenshot 2024-11-14 at 11 51 06 AM" src="https://github.com/user-attachments/assets/df629f76-1d57-4416-87b6-93eee700e68f">
<img width="886" alt="Screenshot 2024-11-14 at 11 51 20 AM" src="https://github.com/user-attachments/assets/6d7a6573-9653-417b-baa0-3bf2d869e32d">

---

I'm closing this issue.
