### ISSUE TITLE
[Google Search API] Displayed Link Not Parsed for Ads

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#812]
A [customer](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040346?view=List) complained we are no longer parsing the `displayed_link` in Google Ads.

<img width="1467" alt="Screenshot 2023-04-25 at 5 29 01 PM" src="https://user-images.githubusercontent.com/30915304/234436341-e0b3fc33-7c58-490a-a4ae-581c72529269.png">

[Playground](https://serpapi.com/playground?q=tires&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Inspector](https://serpapi.com/searches/64486f759bddf7839e534ae7/inspect)

**Comment by marm123** [comment]
I'm changing it from freezer to next as this is an issue one of our customers is waiting to be fixed.
