### ISSUE TITLE
[Google Maps] Empty Array Returned When `start` is set to 0

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#814]
A [user](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040386?view=List) reported unexpected results when performing searches for some locations. From what I can see when leaving off the start parameter, the search is performed as expected, but when using `start=0`,  an empty array is returned.

<img width="1110" alt="Screenshot 2023-04-26 at 4 45 25 PM" src="https://user-images.githubusercontent.com/30915304/234725739-c5bbe868-46b6-437d-b57d-f84febfa6c8c.png">

[Playground( start=0)](https://serpapi.com/playground?engine=google_maps&q=george+street+medical+centre%2C+308+george+st%2C+sydney+nsw+2000&ll=%40-33.8658185%2C151.2073788%2C17z&google_domain=google.com.au&hl=en&type=search&start=0) | [Playground (no start parameter)](https://serpapi.com/playground?engine=google_maps&q=george+street+medical+centre%2C+308+george+st%2C+sydney+nsw+2000&ll=%40-33.8658185%2C151.2073788%2C17z&google_domain=google.com.au&hl=en&type=search) | [Search Inspector](https://serpapi.com/searches/6449b192c47d3c6768c73108/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040386?view=List)

**Comment by ilyazub** [comment]
Probably related to https://github.com/serpapi/SerpApi/pull/3765 and https://github.com/serpapi/public-roadmap/issues/804.

**Comment by schaferyan** [comment]
I've migrated this to #1193 as the problem is the same, but the response has changed.
