### ISSUE TITLE
[Google News API] Missing source field

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#820]
Scrape `source` field with Google News API

![Screen Shot 2023-04-28 at 17 56 44](https://user-images.githubusercontent.com/99160364/235130444-144ae230-65fc-4da6-9845-09ee9d5155ae.png)

![Screen Shot 2023-04-28 at 17 56 56](https://user-images.githubusercontent.com/99160364/235130456-11b6bee8-6413-4fa7-b66c-66922bd6f4ef.png)

![Screen Shot 2023-04-28 at 17 57 09](https://user-images.githubusercontent.com/99160364/235130466-f52040d6-0e52-47cc-b364-12726620cf6a.png)

[Playground](https://serpapi.com/playground?q=football&location=Austin%252C+Texas%252C+United+States&gl=us&hl=en&tbm=nws&no_cache=true&google_domain=google.com) | [Inspect](https://serpapi.com/searches/644ba6492f542eb805d5979f/inspect)

**Comment by marm123** [comment]
Thank you, @andypple83, for this thread! One of our users just reported the issue. I am adding it for reference.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040480)
