### ISSUE TITLE
[Google Events API] Incorrect results for German location

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#827]
It appears that the results returned for Germany differ from what the customers are getting. However, I wasn't able to retrieve the same results as a customer using VPN, as the message I'm getting is `Oops, your browser, device and/or location is not yet supported`. I'm unsure what the issue might be.

**Results with our API for Berlin, Germany:**
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/28161162/235933696-4234d197-adae-4d7f-a922-f26bb14e0fbb.png">

**Results with VPN set to USA:**
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/28161162/235934157-05c3864c-edf5-49e0-954d-cc706b502505.png">

**Results customer gets using the same search query locally:**
![image](https://user-images.githubusercontent.com/28161162/235933818-52fac333-ab32-4d6c-b4a7-9e96cce3ecf7.png)

**Results with VPN set to Germany:**
<img width="929" alt="image" src="https://user-images.githubusercontent.com/28161162/235934306-67f77692-ee2b-44f1-bf5e-ead5d4979f3e.png">

[Playground](https://serpapi.com/playground?engine=google_events&q=Veranstaltungen+in+Gemeinde+Achenkirch&location=Berlin%2C+Berlin%2C+Germany) | [Inspect](https://serpapi.com/searches/64525f23359e99748ed43ada/inspect) | [Link customer is using locally](https://www.google.com/search?q=veranstaltungen+in+gemeinde+achenkirch&rlz=1C1ONGR_itIT973IT973&oq=ver&aqs=chrome.1.69i60j69i59j69i57j69i61j69i60j69i61j69i65l2.3441j0j7&sourceid=chrome&ie=UTF-8&ibp=htl;events&rciv=evn&sxsrf=APwXEddweHxDhfCevDtKYiM0XyBOGXLW-Q:1683119243149#htivrt=events&htidocid=L2F1dGhvcml0eS9ob3Jpem9uL2NsdXN0ZXJlZF9ldmVudC8yMDIzLTA1LTA0fDMzNTQ2NTI4MTMyNDk5Mzc3NjI%3D&fpstate=tldetail)
[Intercom thread](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000038763?view=List)

**Comment by andypple83** [comment]
I can get the results with VPN set to Germany. I searched in incognito mode. But the results are different with customer's results. It may be related to the IP location.

<img width="1185" alt="image" src="https://github.com/serpapi/public-roadmap/assets/99160364/ffbe7e6c-b1ff-4851-8ed7-e069b92f5108">

**Comment by andypple83** [comment]
I've checked the Google events results from SerpApi and VPN to Germany. The results are matched. Let me know if you have any other questions. Thanks

![Screenshot 2024-06-04 at 17 01 01](https://github.com/serpapi/public-roadmap/assets/99160364/be0d7d08-876b-4165-a283-8c2b9b4cee0c)
