### ISSUE TITLE
[New API] Support Google Shopping Trending searches

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#829]
We can add a new API that will return trending searches for Google Shopping.

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/28161162/236155843-2567be45-0339-46a8-8341-f5643e19b3b9.png">

[Google Shopping link
](https://shopping.google.com/?nord=1)[Intercom request](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040568)

**Comment by aciddjus** [comment]
I wasn't able to replicate this feature on Google Shopping.

There are trending searches for the main Google Search but not for Google Shopping and other Google products.

<img width="1380" alt="image" src="https://github.com/serpapi/public-roadmap/assets/6929257/a9be1c2e-69a4-4b94-8254-387a90507332">

-----------

Please re-open if I missed it.
