### ISSUE TITLE
[Google Images API] Pagination not working

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#83]
Google Images API does not retrieve the second page of results with start parameter and serpapi_pagination key is not in results at all.

https://user-images.githubusercontent.com/64849049/158784856-dbbe8dc1-9ce7-4ba2-a790-b209a90fbfc2.mp4

|   [The Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=isch&no_cache=true)   
|   [The Inspect](https://serpapi.com/searches/623305681d986ea0ab0cecc5/inspect)   
|   [Google link](https://www.google.com/search?q=coffee&source=lnms&tbm=isch)

**Comment by tanys123** [comment]
For pagination in Google Images, we use `ijn` for pagination.

**Example:**
https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=isch&ijn=1&no_cache=true
