### ISSUE TITLE
[Google Play Product API] Scrape a Unique Identifier for Reviews

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#830]
A customer has request a unique identifier for Google Play Product reviews. Does Google provide anything that can be used as a unique id for reviews?

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040694?view=List) | [Search Inspector](https://serpapi.com/searches/6453c6dde4a23d53f67640df/inspect) | [Playground](https://serpapi.com/playground?engine=google_play_product&product_id=com.android.chrome&gl=us&store=apps&all_reviews=true&num=10)

**Comment by ilyazub** [comment]
Should be possible.

Review ID in the HTML on Google Play:

![image](https://user-images.githubusercontent.com/282605/237006810-efe1f07c-9a37-4d2e-8edf-f607dc3be849.png)

Review ID in the response from Google Play: 

![image](https://user-images.githubusercontent.com/282605/237006924-81e33102-dcfe-4a7a-a8ba-c4e074143320.png)

**Comment by rzhilkibaev** [comment]
This would help us as well. Right now we have to compute an id based on review attributes to avoid storing duplicates. Having this would allow us to deduplicate more reliably.

**Comment by hilmanski** [comment]
A user requested this as well.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000064206?view=List)

**Comment by ishiharaf** [comment]
@schaferyan @hilmanski Reviews have IDs now 😺

![image](https://github.com/serpapi/public-roadmap/assets/13112082/1ab987cc-7267-426e-b0b4-c8134054e4c9)
