### ISSUE TITLE
[New API] Google Places/Google Maps Autocomplete API

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#831]
A customer requested a Google Maps Autocomplete API and/or Google Places Autocomplete API.

Is this something we can implement in the future?

[Intercom thread](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040703?view=List)

**Comment by hartator** [comment]
It seems possible for Google Maps:

![image](https://user-images.githubusercontent.com/307597/236952025-c6ece496-8949-42b7-b41c-373951abc61a.png)

It also seems possible for Google Local:

![image](https://user-images.githubusercontent.com/307597/236951914-1a960a14-05c6-4a1b-858a-47cff3b5aab8.png)
