### ISSUE TITLE
[Google News API] Date not Returned for News

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#836]
Google News API currently does not return date of the news.

![news_issue](https://user-images.githubusercontent.com/64849049/236382809-6402d16e-4914-418a-ab32-f67e15d29c41.png)

[Playground Link](https://serpapi.com/playground?q=secim&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=nws&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+client) | [Inspect Link](https://serpapi.com/searches/64549125303eb1fad502914a/inspect) | [Google](https://www.google.com/search?q=secim&tbm=nws)

**Comment by ikanberjalandidarat** [comment]
Hi I am also having this issue and I'm actively using the 'date' column for products; could I have an estimate when will this be solved?

**Comment by andypple83** [comment]
It will be fixed in an hour. I'll provide updates when it goes live. Thanks

**Comment by andypple83** [comment]
The result should contain the `date` field now. Thanks @ikanberjalandidarat . cc @aliayar

**Comment by aliayar** [comment]
Thank you Andy.
