### ISSUE TITLE
[Google Search API] Missing `next` and `next_link` from JSON response when pagination is used

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#837]
The `next` and `next_link` keys and values are only returned for the first results page in the `serpapi_pagination` block. If we paginate through results, the following pages are missing those keys and values.

1st page:
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/28161162/236741552-2a3a8d49-565b-4f52-a20e-f70ac156b22d.png">

2nd page:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/28161162/236741678-4527a53b-6f6f-4d3b-b7da-ea6048bee8e3.png">

3rd page:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/28161162/236741792-736580b9-aadf-4c39-bbfb-98c929332de3.png">

[Playground 1st page](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Inspect 1st page](https://serpapi.com/searches/64588860cca014a9d4539e35/inspect)
[Playground 2nd page](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&start=10) | [Inspect 2nd page](https://serpapi.com/searches/645888dd4d443df065f199d5/inspect)
[Playground 3rd page](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&start=20) | [Inspect 3rd page](https://serpapi.com/searches/6458891849ecdb3e97a02e93/inspect)

**Comment by ilyazub** [comment]
Probably related to the infinite pagination: https://github.com/serpapi/public-roadmap/issues/537.

I get the page without pagination buttons when visiting the `google_url`: https://www.google.com/search?q=Coffee&oq=Coffee&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM&hl=en&gl=us&start=20&sourceid=chrome&ie=UTF-8`

![image](https://user-images.githubusercontent.com/282605/237004663-e1bb87e7-48b1-4338-b126-8cef0d5b5a3f.png)

**Comment by arjendevos** [comment]
So this means, google just doesn't give more results?

**Comment by marm123** [comment]
Hi @arjendevos. Google provides more results. The issue has been fixed, and you can find `next` and `next_link` in the JSON responses of pages 2,3,4... etc. Please see the examples below:

[2nd page of results](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&start=10)
[3rd page of results](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&start=20)

**Comment by arjendevos** [comment]
@marm123 oke thanks!
