### ISSUE TITLE
[UI] Change Profile Picture

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#839]
We don't currently offer a way to change the profile picture in the top right corner widget. A user has requested this feature.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000040923?view=List)

**Comment by Alaa-abdulridha** [comment]
The user can create an account here https://gravatar.com/ with the same as serpapi.com email and upload their avatar on gravatar and it will automatically show up in the user profile on SerpApi.

**Comment by ghostmanbobby** [comment]
Nope

***@***.***

**Comment by hilmanski** [comment]
Let's close this for now. If we receive another request, we can inform the customers to use Gravatar, as Alaa mentioned.
