### ISSUE TITLE
[SerpAPI Authentication] Sign in with Github on Web UI throws "already taken"

### ISSUE THREAD

**Issue by GitVex** [serpapi/public-roadmap#845]
After signing up with my github account, I cannot sign back in on another device with the same github login. It says 'is already taken'.

**Comment by schaferyan** [comment]
I'm sorry about that. If you email us at contact@serpapi.com or message us through our chat interface, we can help you activate your account.

**Comment by ghostmanbobby** [comment]
Who cares ...
💪

***@***.***

**Comment by GitVex** [comment]
I believe the issue resolved itself. Using my google account it works now. Still odd though.
