### ISSUE TITLE
[Google Shopping API] Full prices are not displayed

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#848]
Same issue as with Google Product API. Full price is not displayed in our API (with the correct `location`), and when searches from my location. However, the prices appear if I set the VPN to Sao Paulo, Brazil. I believe this should be the case when we use our location parameter correctly, but in the current state it doesn't work:

**Search done with our API (location Sao Paulo, Brazil):**
![image](https://github.com/serpapi/public-roadmap/assets/28161162/4a2bb08d-9ba3-43b3-8b25-6dcec29902f7)

**Search done through regular Google Shopping from my location (Gdansk, Poland):**
<img width="1427" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/d2117f13-310e-41e8-8ea9-e50266d96699">

**Search done through regular Google Shopping with VPN set to Sao Paulo, Brazil:**
<img width="1428" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/fcfdc7e1-bd7c-49c8-ad83-f9caed3664c1">

[Playground](https://serpapi.com/playground?engine=google_shopping&q=Best+Vegan+(500g)+Atlhetica+Nutrition%2C+Cocada&location=State+of+Sao+Paulo%2C+Brazil&google_domain=google.com.br&gl=br&hl=pt) | [Inspect](https://serpapi.com/searches/645ccfb529d1777dba23e58c/inspect) | [Google link](https://www.google.com.br/search?tbm=shop&q=Best+Vegan+%28500g%29+Atlhetica+Nutrition%2C+Cocada&uule=w+CAIQICIZU3RhdGUgb2YgU2FvIFBhdWxvLEJyYXppbA&hl=pt&gl=br)

**Comment by marm123** [comment]
Related: https://github.com/serpapi/public-roadmap/issues/847

**Comment by andypple83** [comment]
With @aciddjus , we tried some combination of `location`, `google_domain` and `country`. Google Shopping will return `monthly_prices` based on the `country: br`. This behavior is consistency(I tested for 1 week).

I'll raise the PR to add this to the document page.

![Screen Shot 2023-05-24 at 12 27 34](https://github.com/serpapi/public-roadmap/assets/99160364/10bf89ea-5c10-42da-aed9-46ef027d4dd8)
![Screen Shot 2023-05-24 at 12 28 17](https://github.com/serpapi/public-roadmap/assets/99160364/528618c4-23fb-4385-ab0f-1d2489fcabbd)

![Screen Shot 2023-05-24 at 12 26 44](https://github.com/serpapi/public-roadmap/assets/99160364/7a5cef83-f345-42a5-b089-fe7db60ed1f8)
![Screen Shot 2023-05-24 at 12 25 48](https://github.com/serpapi/public-roadmap/assets/99160364/e2b33b1a-970a-48e6-9006-c2f8f8a4f6b1)

![Screen Shot 2023-05-24 at 12 24 46](https://github.com/serpapi/public-roadmap/assets/99160364/7cf6001e-6677-43aa-bea3-440e6fde4945)

**Comment by dtmaltrain** [comment]
Hi, im having the same issue on some Sellers using location: Chile, domain: cl & country: cl, is there any way of getting the full price out of the monthly prices displayed?
