### ISSUE TITLE
[Duck Duck Go API] Duck Duck Go Searches Returning Empty Results

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#849]
A customer reported all Duck Duck Go searches are returning empty results. I have verified this in the Playground.

<img width="1469" alt="Screenshot 2023-05-11 at 12 11 58 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/5ae0d569-f81a-4a61-be6a-43b5a421c901">

[Playground ](https://serpapi.com/playground?engine=duckduckgo&q=Coffee&kl=us-en)| [Search Archive ](https://serpapi.com/searches/645d3bd166440a1c5c4c49ea/inspect)| [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000041046?view=List)

**Comment by hartator** [comment]
This should be fixed. Feel free to reopen if it's not.
