### ISSUE TITLE
[UI] Playground Tooltip for `filter` in Google Product API is Cutoff

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#852]
Currently the top of the tooltip for the `filter` parameter of the Google Product API appears cutoff at the top of the browser window(at least in Chrome ). 

<img width="403" alt="Screenshot 2023-05-15 at 4 29 46 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/f56850b3-3990-4474-b1cb-31ecd0dd4e63">

To fix this we can display the tooltip below the field instead of above it.

[Playground](https://serpapi.com/playground?engine=google_product&product_id=4887235756540435899&gl=us&hl=en)

**Comment by hartator** [comment]
Can you share a screenshot of the issue? The screenshot you've shared is the potential fix?

**Comment by schaferyan** [comment]
The screenshot I shared is of the issue. I probably should have been more specific in that the text is only slightly clipped - you can still read it. 

However it doesn't look good and it gives the impression that there may be more text above that is being cut off.

**Comment by hartator** [comment]
Do you mean the upper, right, or lower area? Can you point it out in your
screenshot?

On my desktop, this tooltip already shows below.

**Comment by schaferyan** [comment]
Took a slightly wider screenshot and added some markup, hopefully that's clearer

**Comment by hartator** [comment]
I see. Yes, maybe we should fix that logic and force the tooltip to show below instead of above. It's already the case on my desktop and it is a super long tooltip:

![image](https://github.com/serpapi/public-roadmap/assets/307597/49e9780d-e30a-4a12-b19d-f295c9dd9b89)
