### ISSUE TITLE
google_play: organic_results is expected to be an Array

### ISSUE THREAD

**Issue by jvmvik** [serpapi/public-roadmap#853]
All search engines supported return an Array for organic_result except google_play.
This inconsistent behavior is creating complexity.
It leads to a failed test for the integration library.
Please returns organic_result as an array (not a Hash).

https://serpapi.com/playground?engine=google_play&q=kite&store=apps&highlight=organic_results

<img width="373" alt="image" src="https://github.com/serpapi/public-roadmap/assets/330204/c2a3ff53-47fb-4873-9f45-d2b1a6237c9b">

**Comment by hartator** [comment]
`organic_results` is already an array here.

Do you mean having `items` directly as `organic_results`?

**Comment by ilyazub** [comment]
`organic_results` on the main page contain `Popular`, `Recommended for you`, `Watch TV & Movies`.

![image](https://github.com/serpapi/public-roadmap/assets/282605/3ddc3e64-0b06-4431-b4c4-070f9cf10260)


`organic_results` on the search results page contain `Apps` and `Recommended for you`. Probably, these keys are dynamic.

![image](https://github.com/serpapi/public-roadmap/assets/282605/b0786c51-21ae-4770-ab64-941ae2bf9da0)

Usually, we list such results as `recommended_for_you_results`, `apps_results`, `watch_tv_movies_results` in other search engines.

**Comment by jvmvik** [comment]
Thanks for the explanation. Actually, an Array of Array makes sense in this use-case.
