### ISSUE TITLE
[Google Local API] Phone Number Parsed in `address`, City Name Parse in `type`

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#859]
A customer reported that currently the phone number is parsed in `address`, and the city name is parsed in `type` for some Google Local searches.

<img width="1276" alt="Screenshot 2023-05-17 at 11 00 25 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/beba3e4c-a417-4c88-b5e8-946ba15db438">

[Playground ](https://serpapi.com/playground?engine=google_local&q=%C5%A1kola+Slovakia%2C+SLOVAKIA&location=Slovakia&google_domain=google.sk&gl=sk&hl=sk)| [Search Inspector ](https://serpapi.com/searches/6465155df0adfbcd97e48e3a/inspect)| [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000041343?view=List)

**Comment by zyc9012** [comment]
`škola` is correct for type, it means school
