### ISSUE TITLE
[Google Search API] Related questions not showing

### ISSUE THREAD

**Issue by whillas-yabble** [serpapi/public-roadmap#861]
Related questions was the reason I signed up as vanilla google search results are cheaper via GCP. This what I'm getting from your search:
<img width="476" alt="image" src="https://github.com/serpapi/public-roadmap/assets/113950576/b0d2cf7f-03b4-4cd5-be64-e9327e103c61">
and this is what i get for the same search in my browser
<img width="791" alt="image" src="https://github.com/serpapi/public-roadmap/assets/113950576/9ec74b4c-9975-420a-b087-85a0805c77f6">
your API clearly shows related_questions should be outputted from your searched. 
<img width="539" alt="image" src="https://github.com/serpapi/public-roadmap/assets/113950576/f47ac5bf-3867-4874-b22f-3206249d89d1">
what gives?

**Comment by tanys123** [comment]
Hi @whillas-yabble, thanks for reporting the issue. Can you share your search Ids? You can find them on https://serpapi.com/searches.

At the mean time, I have tried a few times and related questions do show up and our API return the result successfully.
<img width="1570" alt="Screenshot 2023-05-18 at 1 33 39 PM" src="https://github.com/serpapi/public-roadmap/assets/10222402/33bf7bfa-0d5e-4050-941d-3756f404252d">

**Comment by whillas-yabble** [comment]
![image](https://github.com/serpapi/public-roadmap/assets/113950576/c07b08f7-07aa-49f2-acd7-358eb8961a28)

**Comment by whillas-yabble** [comment]
did this ever get resolved?

**Comment by tanys123** [comment]
Hi @whillas-yabble, we aren't able to reproduce it, can you share again searches that have related question missing? It might not work if you have set the pagination `start` param as related questions usually appear on first page of Google

If you are trying to extract as much related questions as possible, you can checkout our [Google Related Questions API](https://serpapi.com/google-related-questions-api), which might work better for your case.
