### ISSUE TITLE
[Google Search API] `"organic_results_state": "Fully empty"` Despite Organic Results in HTML

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#866]
A customer reported they are having some searches coming back with  "error": "Google hasn't returned any results for this query." that should return results. 

In the example they shared, our HTML shows organic results, but only the `menu_items` and `related_questions` are scraped.
<img width="1117" alt="Screenshot 2023-05-18 at 10 25 48 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/a268b224-c0a1-44ff-9b68-d10b8c1e6be8">

I couldn't replicate it in the Playground.

[Playground](https://serpapi.com/playground?q=kapalua+airport+to+Lahaina+hotel&location=Hickory+Hills%2C+Illinois%2C+United+States&gl=us&hl=en&newPara=ijn) | [Search Inspector](https://serpapi.com/searches/64654cf8a5ad6d900c6620b8/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000041404?view=List)

**Comment by schaferyan** [comment]
A second customer reported this issue. Since this is Google and multiple customers have reported it I'm bumping it up to urgent.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000041415?view=List)

**Comment by schaferyan** [comment]
Here is another example:

https://serpapi.com/searches/646673d4aa6c9545016a3929/inspect

**Comment by ilyazub** [comment]
For both of the searches SerpApi used the next user agent string: 

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
```

**Comment by ilyazub** [comment]
Related to https://github.com/serpapi/SerpApi/pull/1945. User agents for this proxy provider result into an old HTML layout we don't support.

**Comment by marm123** [comment]
I'm reopening the issue as one of our customers reported that it still persists.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000041519) | [Inspect](https://serpapi.com/searches/646ad81866440a87f3086331/inspect)
