### ISSUE TITLE
[eBay Search API] Support Filter Parameters

### ISSUE THREAD

**Issue by dimitryzub** [serpapi/public-roadmap#869]
Currently, we don't have a param(s) that can utilize search filters:

![image](https://github.com/serpapi/public-roadmap/assets/78694043/f2849322-d969-4aa2-9b61-ec58358a8417)
____
![image](https://github.com/serpapi/public-roadmap/assets/78694043/3bb3898d-edde-4806-9b33-4a02257bc8ab)

It is related to #482, and somewhat related to #455.

**Comment by kagermanov27** [comment]
Resolved by https://github.com/serpapi/SerpApi/pull/4010 and https://github.com/serpapi/SerpApi/pull/4178
