### ISSUE TITLE
[Google Search API] Video Carousel and Organic Results Confusion

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#87]
When searched for celebrity names, Google comes up with pretty different design.

[Google Search](https://www.google.com/search?q=beyonce&num=100) | [The Playground](https://serpapi.com/playground?q=beyonce&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&num=100&newPara=stick) | [The Inspect](https://serpapi.com/searches/623b13b2eb31eba45ef2089c/inspect)

Below Youtube element is not parsed, as the whole organic link and the rich content which happens to be a carousel:

<img width="395" alt="youtubeorganicmi" src="https://user-images.githubusercontent.com/64849049/159707726-6de20b92-7c3b-4695-952c-fb80bcba70a0.png">

The second problem and the confusion is that the Facebook element is the same but returned in inline_video_carousels. This should also be an organic_result like the Youtube element above with rich carousel content.

<img width="407" alt="facebookorganicmi" src="https://user-images.githubusercontent.com/64849049/159708166-359a8bd4-a86e-434b-be3a-0458b13190a3.png">

Just to give an idea of whole page:

<img width="593" alt="wholeorganicmi" src="https://user-images.githubusercontent.com/64849049/159709079-12bcf8c8-8312-4a3d-ab40-f44e4f397c12.png">

We should define, clarify these elements and act on it.

**Comment by ilyazub** [comment]
The videos from Facebook are extracted into `inline_video_carousels` but the X-Ray highlighting is incorrect.

![image](https://user-images.githubusercontent.com/282605/160574990-681c5e13-a858-4f23-8500-847fc16dd8d7.png)

But the carousel with YouTube videos is not parsed. It's a bug.

![image](https://user-images.githubusercontent.com/282605/160575241-d0d63b6e-6afc-417f-be2c-3e98876a2253.png)

All of the `inline_video_carousels` are extracted in a similar search: https://serpapi.com/searches/a29ac89057ba15bd/6242c9c47690dce61dcacf98.json. But JSON contains four groups in `inline_video_carousels` instead of two. It's also a bug.

**Comment by aliayar** [comment]
I believe that those videos with Facebook and Youtube organic results should be classified as organic results with rich video content. I know that we always steer away from changing the structure of the JSON but at least we should discuss about this.

**Comment by ilyazub** [comment]
Actually, we already extract TikTok video carousels on mobile into `.organic_results[].carousel`. [Playground link](https://serpapi.com/playground?q=coinbureau+tiktok&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&highlight=organic_results[0]).

![image](https://user-images.githubusercontent.com/282605/162426215-8408528f-1c0c-4f27-bc11-29d5f66a4d9f.png)

Initially, `carousel` contained top stories only.

![image](https://user-images.githubusercontent.com/282605/162427758-0134d5a3-18c8-4028-842d-2e476c085f69.png)

I was wrong with introducing `inline_video_carousels` a year ago in serpapi/SerpApi#1684. We will extract video carousels into `.organic_results[].carousel` and will deprecate `inline_video_carousels` in a backwards-compatible way.

**Comment by githubfan21** [comment]
@ilyazub 
we used the inline_video_carousel a lot in our data
I would argue that inline video carousels are different from youtube carousels which are called "host carousels"; they are two different modules. Youtube carousel will include links from youtube which are videos while video_carousel have links from different sites

- i recommend to have a place/page where we see current/future json syntax changes, i found this ticket by accident 
- for all carousels, we need type and titles. currently carousels only provide links and thumbnails and it is hard to figure out exactly what type of carousel it is

**Comment by aliayar** [comment]
@githubfan21 We try our best to not change our JSON structure and if we decide to do, we will inform our users way before we make the change. Ilya's last sentence makes this clear:

> We will extract video carousels into `.organic_results[].carousel` and will deprecate `inline_video_carousels` **in a backwards-compatible way**.

**Comment by kagermanov27** [comment]
https://github.com/serpapi/public-roadmap/issues/226 could be resolved here. It wasn't picked up before as organic result with a carousel or an inline video carousel.

![organic_result](https://user-images.githubusercontent.com/73674035/179951824-f2379eae-901b-4085-9f65-5b054e5bf809.png)
[Inspect](https://serpapi.com/searches/62d7cc2de0ded4a6e7c0d369/inspect)
[Playground](https://serpapi.com/playground?q=mrbeast+videos&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true&newPara=stick+highlight+lr+async+as_qdr)

**Comment by dimitryzub** [comment]
@tanys123 If I'm not wrong, inline video carousel results seem to be not extracting right now (x-ray also not working on those elements):

![image](https://user-images.githubusercontent.com/78694043/182304726-afe4ca9c-3730-4c04-98d1-3c808f120750.png)

Playground Search tools also didn't find anything:

![image](https://user-images.githubusercontent.com/78694043/182305000-f26ba98c-00a1-46a5-ae0f-808c68a95b85.png)


[Playground link](https://serpapi.com/playground?q=mrbeast+videos&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=desktop&no_cache=true&engine=google&google_domain=google.com&newPara=stick+highlight+lr+async+as_qdr+safe+engine+google_domain+si+form+filter).

**Comment by ilyazub** [comment]
Video carousel in organic results is not extracted.

[Playground URL](https://serpapi.com/playground?q=mrbeast+videos) | [Search Inspect](https://serpapi.com/searches/633a88ad5119a61084f00695/inspect)

**Comment by ilyazub** [comment]
`organic_results[].carousel` is not extracted on mobile:

![image](https://github.com/serpapi/public-roadmap/assets/282605/45618e56-d0d6-4c2e-8028-09a8b0528458)
[Playground](https://serpapi.com/playground?q=Tom+Hanks&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&google_domain=google.com) | [Search Inspector](https://serpapi.com/searches/657c158d4b91eb98496e13aa/inspect)
