### ISSUE TITLE
[Google Search API] Knowledge Base Financials To Be Scraped

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#871]
When searched for stock names, knowledge base returns the financials of the company. We don't scrape it.

![financials](https://github.com/serpapi/public-roadmap/assets/64849049/b58c34d6-086e-48f6-9176-c83a9bc422a0)

[Playground Link](https://serpapi.com/playground?q=aapl+statistics&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Inspect Link](https://serpapi.com/searches/6467816fb5961e4c83f00ad9/inspect) | [Google Link](https://www.google.com/search?q=aapl+statistics)

**Comment by aciddjus** [comment]
Related: https://github.com/serpapi/public-roadmap/issues/884
