### ISSUE TITLE
[Google Product API] Scrape manufacturer info

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#877]
Google returns manufacturer for some results

![Screen Shot 2023-05-21 at 21 28 29](https://github.com/serpapi/public-roadmap/assets/99160364/a13b4517-ee0f-4d9c-9247-b4991d74c3c0)

[Playground](https://serpapi.com/playground?engine=google_product&product_id=12165436226004321632&gl=us&hl=en&device=desktop) | [Inspect](https://serpapi.com/searches/646a2ae91988e5e7cfba1733/inspect)

**Comment by hartator** [comment]
> Google returns manufacture for some results

What do you mean? Manufacturer?

**Comment by andypple83** [comment]
yeah. typo. Should be manufacturer
