### ISSUE TITLE
[DuckDuckGo Search API] Scrape date from search results

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#881]
We are not scraping dates that are provided for certain results in DuckDuckGo:

<img width="984" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/ac9bf24b-7ca5-43a3-bf60-a2ce033709d6">

[Playground](https://serpapi.com/playground?engine=duckduckgo&q=Football&kl=uk-en&df=w&no_cache=true) | [Inspect](https://serpapi.com/searches/646b806eaa6c9554227e3a19/inspect) | [DuckDuckGo](https://duckduckgo.com/?q=Football&kl=uk-en&df=w&ia=news)

**Comment by hartator** [comment]
Can you point to the Intercom thread?

**Comment by marm123** [comment]
Sure, here it is:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000041477?view=List)
