### ISSUE TITLE
[Google Maps API] Pagination Broken - Searches Returning Empty Results When `start` is Used

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#885]
A customer reported  empty result sets for Google Maps searches. I have noticed that the example they shared works if `start=0` is removed. It returns empty results if `start` is 0 or 20.

This seems to be true of all or most Google Maps searches.

<img width="1465" alt="Screenshot 2023-05-22 at 11 48 21 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/4c146de6-66df-4b87-813b-776ac396af4e">

[Playground(no start)](https://serpapi.com/playground?engine=google_maps&q=Coffee&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&type=search) | [Playground(start=0)](https://serpapi.com/playground?engine=google_maps&q=Coffee&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&type=search&start=0) | [Playground(start=20) ](https://serpapi.com/playground?engine=google_maps&q=Coffee&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&type=search&start=20)| [Search Inspector](https://serpapi.com/searches/646bb3d58e02e4134ee3dbc9/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000041563?view=List)

**Comment by aliayar** [comment]
Another user submitted this issue this morning:

Examples: [1](https://serpapi.com/searches/646c4433d04d6df3ece2706b/inspect) | [2](https://serpapi.com/searches/646c442cc90e0ac56826e798/inspect) | [3](https://serpapi.com/searches/646c45fa3c3fb27b6c6b0eb3/inspect) | [4](https://serpapi.com/searches/646c380e4b91ebc274475318/inspect) | [5](https://serpapi.com/searches/646c43f8c56d934184a35687/inspect)

**Comment by ilyazub** [comment]
Related to https://github.com/serpapi/public-roadmap/issues/804 from a month ago.

**Comment by schaferyan** [comment]
Another user reported this:

[Search Inspector](https://serpapi.com/searches/647fb9f4ea1442e63442f05c/inspect)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042426?view=List)

**Comment by aliayar** [comment]
I am not sure if users are doing it wrong by including `start=0` parameter. On Google itself, the first page is shown without start=0 parameter.

When the same query is performed without `start=0`, it returns results:

https://serpapi.com/playground?engine=google_maps&q=Therapists+in+London&ll=%4051.5261639%2C-0.1998848%2C14z&hl=en&type=search

**The problem here is when `start=20` parameter is added, it returns nothing.**
