### ISSUE TITLE
[Google Search API] Scrape Insurance Information

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#889]
In the Knowledge Graph for some medical providers, there is a "Check insurance info" link. A customer has requested we scrape the information that is displayed when this link is clicked.

<img width="1460" alt="Screenshot 2023-05-23 at 10 54 11 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/0a0bce6a-51b2-4244-a34b-b19b1c5b7605">
<img width="1215" alt="Screenshot 2023-05-23 at 10 55 34 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/03c41efb-8064-4f69-a519-1b6a0e6b0e64">

[Playground](https://serpapi.com/playground?q=A+%26+A+Health+Service%2C+Inc+3408+W+84th+St+Ste+204+Bldg+G+Hialeah%2C+FL+33018&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Search Inspector ](https://serpapi.com/searches/646cfd90d5a5313bbe9f16d4/inspect)| [Google](https://www.google.com/search?q=A+%26+A+Health+Service%2C+Inc+3408+W+84th+St+Ste+204+Bldg+G+Hialeah%2C+FL+33018&ei=UO5sZPn4Ee2EkvQP6byLqAc&ved=0ahUKEwj54IK78ov_AhVtgoQIHWneAnUQ4dUDCBA&uact=5&oq=A+%26+A+Health+Service%2C+Inc+3408+W+84th+St+Ste+204+Bldg+G+Hialeah%2C+FL+33018&gs_lcp=Cgxnd3Mtd2l6LXNlcnAQAzIGCAAQFhAeOgcIABAeELADSgQIQRgBUOQGWN4yYIQ2aAFwAHgAgAFGiAFGkgEBMZgBAKABAaABAsgBAcABAQ&sclient=gws-wiz-serp) | [Intercom ](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000041694?view=List)

**Comment by amplicity** [comment]
Thanks @schaferyan  -- I was the customer who requested this. Please do let me know if it's something ya'll can add. Very helpful for us.
