### ISSUE TITLE
[New API] Scrape food.google.com

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#890]
One of our customers requested that we could scrape Google's ordering page.

Food places listing:
<img width="1425" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/220ca8b8-7ced-4461-8203-30b510dfc1e3">

Order options:
<img width="979" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/59fb89d8-0ef7-43a9-bd1f-c3e0d3f4dcfb">

View from the customer's side (I couldn't recreate it. Looks like it might be location-specific and Google doesn't show it this way for my location):
![image](https://github.com/serpapi/public-roadmap/assets/28161162/d0112074-9f4b-4161-a9f5-332d563c8331)

[Direct link](https://food.google.com/food/homepage?addressId&orderType=2&hl=en-US&gl=us&fo_s=OA&g2lbs=ADZRdktFInzoGMpfLAQhaH_NmkbLdHUDeUZbKsEJ099_vBGLxrXXMymfx_6ozTxEBCW-ndefmfEusAtViM-5dLCFdF00Rjki_qdHXLS7MMQ3Trb4U_lE9kBnUw4FS7J70PFdHNE6lxqY&ei=XRhuZN_xN_-mqtsP6NS3wAw&gei=XRhuZN_xN_-mqtsP6NS3wAw&restaurantId=%2Fg%2F1tlnf8n7&sei=CWNeZAFo6r61EZM3iN922keH&utm_source=search&ved=0CAUQ6I0FahcKEwjwqPHMj47_AhUAAAAAHQAAAAAQUQ&q=Pizza&loc_q=New%20York%2C%20NY%2C%20USA&fo_m=EhESAggCqgEKCggIARIEEgIIAjEAIEKOefYxbzEAtCVaYzy9WDEAeGyJ2MAQ7jEAmEz6eSl4fg&lat=40.7127753&lng=-74.0059728) | [Intercom thread](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000041741?view=List)

**Comment by schaferyan** [comment]
Another user requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000050599?view=List)

**Comment by schaferyan** [comment]
Another customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067944?view=List) | [Front ](https://app.frontapp.com/inboxes/teams/folders/22722524/open/102938592540)

**Comment by kagermanov27** [comment]
Our Google Food API is live and can be accessed via `engine=google_food` parameter.

![image](https://github.com/user-attachments/assets/aa9a3e36-45f6-4272-a08a-d158843c3ace)

[Documentation](https://serpapi.com/google-food-api)
[Playground](https://serpapi.com/playground?engine=google_food)
