### ISSUE TITLE
[Google Search API] Scrape DMCA removal message

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#891]
One of our customers requested that we can scrape the DMCA removal message, which is visible for some searches at the end of the results page:

<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/df66684f-9a65-41c0-94f7-41b6a6a4b7fe">

[Playground](https://serpapi.com/playground?q=free+john+wick+4+online&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/646f186fb7b1cc91c3eb9d26/inspect) | [Google](https://www.google.com/search?q=free+john+wick+4+online&oq=free+john+wick+4+online&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM&hl=en&gl=us&sourceid=chrome&ie=UTF-8#ip=1)
[Playground](https://serpapi.com/playground?q=free+avatar+2+online&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/646f199466d81f3a589ffa17/inspect) | [Google](https://www.google.com/search?q=free+avatar+2+online&oq=free+avatar+2+online&uule=w+CAIQICIaQXVzdGluLFRleGFzLFVuaXRlZCBTdGF0ZXM&hl=en&gl=us&sourceid=chrome&ie=UTF-8)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000041785)

**Comment by aliayar** [comment]
[Another user](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042167?view=List) had a request for this feature.
