### ISSUE TITLE
[All Search APIs] Add a Parameter Allowing Users to Associate a Custom String With Searches

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#901]
A customer requested that we support a parameter in our search APIs for a user comment. This could enable different users of the same account to add their own custom query id, or client id that can be associated with their searches. The user could then differentiate their searches from those of other users sharing the account.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042185?view=List)

**Comment by marm123** [comment]
Customer is looking to scale their business significantly, but they require this feature or a workaround:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042185?view=List)

**Comment by hartator** [comment]
https://github.com/serpapi/public-roadmap/issues/270 should be actually easier to do than this. Let's actually prioritize work on that one.

**Comment by hartator** [comment]
Closed in favor of https://github.com/serpapi/public-roadmap/issues/1017.
