### ISSUE TITLE
[New Integration] Add SerpApi plugin to Auto-GPT

### ISSUE THREAD

**Issue by aciddjus** [serpapi/public-roadmap#905]
Auto-GPT plugins are officially available. SerpApi plugin for Auto-GPT may be useful to fetch data from other search engines besides Bing (an official Auto-GPT plugin).

Auto-GPT plugins quickstart: https://github.com/Significant-Gravitas/Auto-GPT-Plugins

[Request](https://twitter.com/jordythanhvu/status/1660702893966778368)

**Comment by ilyazub** [comment]
Related:
* https://github.com/Significant-Gravitas/Auto-GPT/issues/3372
* https://discuss.streamlit.io/t/auto-gpt-with-internet-search-in-streamlit-community-cloud/41843
* https://news.ycombinator.com/item?id=36187156
* https://www.reddit.com/r/AutoGPT/comments/12qjlnt/how_do_i_let_autogpt_log_in_to_websites_for_me/?utm_source=share&utm_medium=web2x&context=3

**Comment by aciddjus** [comment]
SerpApi was added to Auto-GPT [First Party Plugins](https://github.com/Significant-Gravitas/Auto-GPT-Plugins#first-party-plugins). 🎉 

Thank you, @zyc9012 💯
