### ISSUE TITLE
[Google Search API] Top carousel not extracted anymore

### ISSUE THREAD

**Issue by ilyazub** [serpapi/public-roadmap#91]
[Playground](https://serpapi.com/playground?q=dune+actors&gl=us&hl=en) | [Search Inspect](https://serpapi.com/searches/623dc388aef264fa2d628374/inspect)

![image](https://user-images.githubusercontent.com/282605/160129783-482d48fe-ef2a-4e91-9c8b-6a058974fd78.png)

**Comment by Alaa-abdulridha** [comment]
Thank you @ilyazub 
Could you please give me another example, as I'm not able to reproduce it?

**Comment by ilyazub** [comment]
@Alaa-abdulridha

Examples:
- https://serpapi.com/playground?q=dune&gl=us&hl=en
- https://serpapi.com/playground?q=lost+city+actors&gl=us&hl=en

It seems that only the top carousel from `<something> actors` searches is not extracted. [Other](https://serpapi.com/playground?q=MU+players&gl=us&hl=en) [queries](https://serpapi.com/playground?q=oxxxymiron+albums&gl=us&hl=en) work.
