### ISSUE TITLE
[Google Finance API] Scrape Graph Values for All Available Date Ranges

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#919]
The graph in Google Finance searches allows selecting from different date ranges. Currently we only scrape the data for the default date range "1D". A customer requested support for all available date ranges.

<img width="1457" alt="Screenshot 2023-06-06 at 2 50 08 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/e0fb67ae-c81c-4393-a372-730fa3997ed2">

[Intercom ](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042423?view=List)| [Playground ](https://serpapi.com/playground?engine=google_finance&q=GOOGL%3ANASDAQ)| [Search Inspector](https://serpapi.com/searches/647fa6e7f636ff423f61dcbb/inspect) | [Google](https://www.google.com/finance/quote/.DJI:INDEXDJX?hl=en&window=6M)

**Comment by marm123** [comment]
Another user requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000044301?view=List)

Changing to next
