### ISSUE TITLE
[Google Search API] Missing value for rich snippet in organic results

### ISSUE THREAD

**Issue by andypple83** [serpapi/public-roadmap#924]
We combined the key and value for the rich snippet in this result:

![image](https://github.com/serpapi/public-roadmap/assets/99160364/d10cd1db-4f7c-4928-a96c-47ac5ceb8956)

[Playground](https://serpapi.com/playground?q=apple+inc&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true) | [Inspect](https://serpapi.com/searches/648062f0a74fe0155a771708/inspect)

**Comment by ilyazub** [comment]
@andypple83 Please share search parameters that reproduce this type of rich snippet. (The parameters above no longer return it.)

**Comment by Krugloff** [comment]
Is this now considered part of the 'organic results'?
[Playground](https://serpapi.com/playground?q=apple+inc&location=United+Kingdom&gl=uk&hl=en&no_cache=true)

<img width="1454" alt="image" src="https://github.com/user-attachments/assets/c637a5aa-4ff8-45a6-b17b-c4976d4396ae">

**Comment by Krugloff** [comment]
We have a solution (see the linked PR), but we've decided to hold off on implementing it until we receive more real requests, as the initial issue is not reproducible.
