### ISSUE TITLE
[Documentation] Remove information about advanced search operators for Google Shopping API

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#925]
Per our documentation, users should be able to use advanced search operators such as `site:`, `inurl:` etc., with Google Shopping API, but it looks like those are not supported for this engine:

Documentation:
<img width="1094" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/22ddddea-449f-43d0-acbd-0c76e8e0937c">

Results from the Playground:
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/4103feac-3187-4cca-adb4-f6322015045b">

[Playground](https://serpapi.com/playground?engine=google_shopping&q=site%3Aebay.com+Coffee) | [Inspect](https://serpapi.com/searches/64807ad3dc02f108aa28a760/inspect) | [Documentation](https://serpapi.com/google-shopping-api#api-parameters-search-query)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042471?view=List)

**Comment by kagermanov27** [comment]
For context, @marm123 and I realized that `intitle:` still works. But it seems that Google has dropped its support for others in Shopping. It may or may not be brought back in the future.
