### ISSUE TITLE
[Google Images API] Image Title not Returned

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#935]
Google Images API does not return image title anymore.

![images_api_title](https://github.com/serpapi/public-roadmap/assets/64849049/12fdb0e2-7e1e-49c4-8066-2f68ad1cf692)

[Playground Link](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&tbm=isch) | [Inspect Link](https://serpapi.com/searches/64894e4110d744989fe1db6e/inspect) | [Google ](https://www.google.com/search?q=coffee&tbm=isch)| [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042804?view=List)

**Comment by schaferyan** [comment]
Another user reported this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042860?view=List)
