### ISSUE TITLE
[Google Maps API] Proxy Location Used When "near me" Keywords are Included in `q`

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#938]
A customer reported they are getting results for the wrong location when searching in Google Maps with the "near me" keywords.  I was able to replicate this in the playground. Results for the expected location seem to be given when not including "near me".

<img width="1461" alt="Screenshot 2023-06-14 at 11 30 23 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/c7ceb98c-0049-42a0-bb08-a5a03a0dacd4">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042845?view=List) | [Playground](https://serpapi.com/playground?engine=google_maps&q=dentist+near+me&ll=%4037.773972%2C-122.431297%2C14z&hl=en&type=search&no_cache=true) | Search Inspector: [1](https://serpapi.com/searches/648a01eccace969ae33e2713/inspect) | [2](https://serpapi.com/searches/648a069833b23668ec82f171/inspect) | [3](https://serpapi.com/searches/648a086f629a01003e3e818e/inspect) | [4](https://serpapi.com/searches/648a06e44055aa32e9e04ba4/inspect)

**Comment by ritu1337** [comment]
We mention `near me` in the documentation: https://serpapi.com/google-maps-api
> Some results may be inaccurate for the provided geographic location. Particularly `near me` keyword in query will show results not for provided coordinates. Also city, state and zip code can be added to query to refine search.

When `near me` is used, Google seems to use the user's IP address, so in this case it will show results around the proxy server location.

**Comment by schaferyan** [comment]
That makes sense. I don't suppose there's anything we can do to change this? I'm guessing probably not since it sounds like we would either have to somehow use an IP address for the location given or modify the user's query to include the name of the location instead of "near me".

**Comment by ritu1337** [comment]
> That makes sense. I don't suppose there's anything we can do to change this? I'm guessing probably not since it sounds like we would either have to somehow use an IP address for the location given
Yes, we could use a local proxy, but we might not have coverage for every obscure location.

> or modify the user's query to include the name of the location instead of "near me".

Yes, for example searching for `q`: "dentist near {location}" e.g. `q`: "dentist near 799-701 Oak St, San Francisco". [Playground](https://serpapi.com/playground?engine=google_maps&q=dentist+near+799-701+Oak+St%2C+San+Francisco&hl=en&type=search&no_cache=true)

**Comment by aliayar** [comment]
I am closing this one.
