### ISSUE TITLE
[SerpApi User Registration Flow] Activation Emails Sent Twice and Going to Spam

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#94]
After a user reported that they haven't received activation email, I decided to test registration flow and turns out gmail sees SerpApi emails as spam and activation email is sent twice.

![image(2)](https://user-images.githubusercontent.com/64849049/160595974-97fa0881-791d-4d74-9210-88f8da5eb30a.png)

Ilya suggested that #1756 may be connected to this problem. Excerpt from #1756:

> Do you think it's super necessary though?

> Yeah, it might be very handy in cases where we do outreach to adresses that we have never sent emails to. It would minimize the chance of emails being sent from our business domain ([person@serpapi.com](mailto:person@serpapi.com)) going to spam.

**Comment by aliayar** [comment]
It seems that emails are not sent at all.

**Comment by ilyazub** [comment]
Even the basic test shows that email is sent twice.

Code

```ruby
describe "#send_confirmation_instructions" do
  let(:user) { User.new(email: "test+#{Devise.friendly_token(15)}@serpapi.com", password: Devise.friendly_token(15)) }

  it "sends confirmation instruction once" do
    expect { user.send_confirmation_instructions }.to change { ActionMailer::Base.deliveries.count }.by(1)
  end
end
```

Output 

```
  1) User#send_confirmation_instructions sends confirmation instruction once
     Failure/Error: expect { user.send_confirmation_instructions }.to change { ActionMailer::Base.deliveries.count }.by(1)
       expected `ActionMailer::Base.deliveries.count` to have changed by 1, but was changed by 2
     # ./spec/models/user_spec.rb:98:in `block (3 levels) in <main>'
```

----

According to [mail-tester](https://www.mail-tester.com/test-v1guwmpww), there are two extra warnings:
- From and EnvelopeFrom 2nd level mail domains are different
- HTML-only message, but there is no HTML tag. Your message should contain an <html> tag

![image](https://user-images.githubusercontent.com/282605/161314424-a385a54b-811c-4b29-a005-b6b02024b43b.png)

And an email actually doesn't have an HTML tag.

```ruby
message.body.encoded
=> "<p>Welcome test+J2v2wACzRqVD47c@serpapi.com!</p>\r\n\r\n<p>You can confirm your email through the link below:</p>\r\n\r\n<p><a href=\"http://localhost:3000/users/confirmation?confirmation_token=B5BxXCkWrxiHoes6NHiS\">Confirm your email</a></p>\r\n\r\n<p>Thank you!</p>\r\n"
```

**Comment by ilyazub** [comment]
Emails are no more going to spam. But still sent twice.

**Comment by ilyazub** [comment]
Confirmation email is sent _once_ after clicking `Sign Up`. 

![image](https://user-images.githubusercontent.com/282605/194280008-38a147bc-00be-41f1-ada6-6c7c732de54e.png)

Then, on the `/users/welcome` page there's a `Send email` button which doesn't let know if email was previously sent.

![image](https://user-images.githubusercontent.com/282605/194279939-a46a5999-d99a-456b-97b4-42eb6aff7077.png)

Notice is displayed _only after clicking_ the `Send email` button.

![image](https://user-images.githubusercontent.com/282605/194280433-0f28b7ee-aeb1-4ad2-bddd-166677a42ac4.png)

### The actual fix

- [ ] Display a flash notice on `/users/welcome` page after redirect from the `Sign Up` page.

![image](https://user-images.githubusercontent.com/282605/194280433-0f28b7ee-aeb1-4ad2-bddd-166677a42ac4.png)

- [ ] Rate-limit sending of confirmation emails to at least once a minute, like on any modern website.

**Comment by hartator** [comment]
I think root issue was solved elsewhere by @ritu1337.
