### ISSUE TITLE
Answer box "Key Error" SerpAPI

### ISSUE THREAD

**Issue by Piotrexx** [serpapi/public-roadmap#940]
So I wanted to extract data from answer_box using Your API and an error occured **KeyError: 'answer_box'**
It is working on a [playground](https://serpapi.com/playground?q=Pi) but I can't extract is through code.

I don't see any errors in my code since I wrote the same what is in your [documantation ](https://serpapi.com/direct-answer-box-api).

![playground](https://github.com/serpapi/public-roadmap/assets/114826303/e89dada5-62b0-4528-87d6-65ed12af7022)
![code](https://github.com/serpapi/public-roadmap/assets/114826303/82205a8f-a1ed-4bcf-85c1-bc686e6e35ce)
![error](https://github.com/serpapi/public-roadmap/assets/114826303/53debb8e-0847-456b-b8d8-6e1ad9f4f9ba)

_If there is a mistake in my code then I'm sorry for the trouble_

**Comment by marm123** [comment]
Hi @Piotrexx! It appears that the JSON response doesn't contain the `answer_box` for your query. Please contact us at contact@serpapi.com or through the chatbox widget at https://serpapi.com/. We'll be more than happy to assist you with your code and find the root cause of your issue.
