### ISSUE TITLE
[Google Images API] Scrape full `title`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#941]
For some searches, we are only scraping the truncated version of the `title`, while we were previously scraping the full title every time:

<img width="1438" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/ed7157f7-11b1-4bc0-bfe1-fde583f974f5">

[Playground](https://serpapi.com/playground?engine=google_images&q=Coffee&gl=us&hl=en) | [Inspect](https://serpapi.com/searches/648feeddd737d7d3d45caabf/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042804?view=List)

Connected to https://github.com/serpapi/public-roadmap/issues/935

**Comment by aliayar** [comment]
Mouseover action reveals full text while text under picture is not fully there.

![image](https://github.com/serpapi/public-roadmap/assets/64849049/e44dd5ab-3e33-410c-9885-d9e5a5bcaf6b)

Mouse over the text shows full text ( on the left side) which is "**Coffee and Antioxidants: Everything You Need to Know**" while in JSON response, text is cut short with "..." which is "**Coffee and Antioxidants: Everything You ...**"

Scraping mouse over text should fix this.
