### ISSUE TITLE
[Baidu Search API] Scrape direct `link` instead of redirect link

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#942]
Currently, we only scrape redirect links for Baidu Search API. While this was not directly reported by our user, one of them is trying to use SERPAPI_RANK, failing because no actual link can be found in the response. If we scrape the actual `link` instead of Baidu's redirect link, the issue should be fixed:

Current state:
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/7fdf6706-a0c2-4756-879d-56ea77db4102">

[Playground](https://serpapi.com/playground?engine=baidu&q=Coffee) | [Inspect](https://serpapi.com/searches/64901a1df55d773182b3d538/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000043024?view=List)

**Comment by aliayar** [comment]
Baidu uses those redirect links possibly for statistical reasons. 

However, they don't include redirected links in their redirect link structure like Google. This means that website URL may not be parsed until Baidu redirect link is visited.

**Comment by marm123** [comment]
We've discussed this issue with @zyc9012 and @tanys123, and there appears to be a way to scrape direct links for Baidu. It could be that this was not the case in the past, but we can update the parser to include them.
