### ISSUE TITLE
[Google Maps API] Clarify the `data` definition

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#943]
Currently, the documentation states that we need to use `data_id` for `type=place` searches with other parts to construct the `data` parameter. Since the `data_id` is unique for each place, it implies that the `data` should also be unique. However, you can construct data with part of the `data_id` as well as the whole `data_id`, resulting in at least two ways to use the `data` parameter for the same place. One of our customers reported that it caused some headaches for them since the `data` was considered unique for each place.

Place searches with the whole `data_id` (**0x6018f25321e7fb01:0x7be65bb53b0ce4d2**):
![image](https://github.com/serpapi/public-roadmap/assets/28161162/1823557c-491e-477e-8321-d25ac2c88b09)

Same place reached with a part of `data_id` (~~0x6018f25321e7fb01:~~**0x7be65bb53b0ce4d2**):
![image](https://github.com/serpapi/public-roadmap/assets/28161162/95cc18ad-aebb-4a26-b5f6-b4ccc085a582)

Documentation:
<img width="1077" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/961d7570-4c94-4110-9071-40e168c114e6">

Since the same result can be reached in multiple ways using multiple different `data` values, we should explore how exactly it can be achieved and adjust the documentation not to confuse our customers.

[Playground with full `data_id`](https://serpapi.com/playground?engine=google_maps&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&data=!4m5!3m4!1s0x6018f25321e7fb01%3A0x7be65bb53b0ce4d2!8m2!3d35.652!4d139.705&type=place) | [Inspect with full `data_id` ](https://serpapi.com/searches/6490160dedb034181c6d84b4/inspect)
[Playground with part of the `data_id`](https://serpapi.com/playground?engine=google_maps&ll=%4040.7455096%2C-74.0083012%2C14z&hl=en&data=!4m5!3m4!1s0x0%3A0x7be65bb53b0ce4d2!8m2!3d35.652!4d139.705&type=place) | [Inspect with part of the `data_id` ](https://serpapi.com/searches/649015afd036a7dc3f690cd0/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000042972?view=List)

**Comment by hilmanski** [comment]
I find the documentation a bit confusing as well. 

[Place sample from google maps](https://www.google.com/maps/place/Pancious+Pancake+House/@-5.1620529,119.4363729,17z/data=!3m1!4b1!4m6!3m5!1s0x2dbee2eb319cb05d:0x12708f9d9752958c!8m2!3d-5.1620583!4d119.4412384!16s%2Fg%2F11bw1zgnhg?entry=ttu)

Currently upon copy-pasting `data` from google maps, I can see the result just fine: [playground](https://serpapi.com/playground?engine=google_maps&hl=en&data=!3m1!4b1!4m6!3m5!1s0x2dbee2eb319cb05d%3A0x12708f9d9752958c!8m2!3d-5.1620583!4d119.4412384!16s%252Fg%252F11bw1zgnhg%3Fentry%3Dttu&type=place).

But when following the `formula` which equal to = `!4m5!3m4!1s1s0x2dbee2eb319cb05d:0x12708f9d9752958c!8m2!3d-5.1620583!4d4d119.4412384`
[playground](https://serpapi.com/playground?engine=google_maps&hl=en&data=!4m5!3m4!1s1s0x2dbee2eb319cb05d%3A0x12708f9d9752958c!8m2!3d-5.1620583!4d4d119.4412384&type=place)

*I've try to remove the `1s` after `!4m5!3m4!`, it's still failed.

**Comment by aciddjus** [comment]
@hilmanski 

> **Following formula doesn't work** But when following the `formula` which equal to = `!4m5!3m4!1s1s0x2dbee2eb319cb05d:0x12708f9d9752958c!8m2!3d-5.1620583!4d4d119.4412384` [playground](https://serpapi.com/playground?engine=google_maps&hl=en&data=!4m5!3m4!1s1s0x2dbee2eb319cb05d%3A0x12708f9d9752958c!8m2!3d-5.1620583!4d4d119.4412384&type=place)
> 
> *I've try to remove the `1s` after `!4m5!3m4!`, it's still failed.

Formula works: [Playground](https://serpapi.com/playground?engine=google_maps&hl=en&data=!4m5!3m4!1s0x2dbee2eb319cb05d%3A0x12708f9d9752958c!8m2!3d-5.1620583!4d119.4412384&type=place)

You had double `1s` and `4d`

------

Related to issues: https://github.com/serpapi/public-roadmap/issues/1625
