### ISSUE TITLE
[Google Search API] Related questions missing for some searches in `mobile` 

### ISSUE THREAD

**Issue by tanys123** [serpapi/public-roadmap#945]
[Playground](https://serpapi.com/playground?q=Elon+musk&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&no_cache=true) | [Inspect](https://serpapi.com/searches/6492655a3bea7ba946d9e4c3/inspect)

Related questions is not scraped

<img width="1496" alt="Screenshot 2023-06-21 at 10 52 52 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/e5276e4e-20b9-4950-9b55-74fb7b2fc011">

**Comment by ishiharaf** [comment]
I couldn't reproduce the issue on the particular query above, but it's not being parsed on the following query (on desktop):

[Playground](https://serpapi.com/playground?q=Austin+Texas+Destinations&location=Dallas%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com) | [Inspect](https://serpapi.com/searches/66758731cca014a520990934/inspect)

**Comment by Krugloff** [comment]
I couldn't reproduce either of the issues :(

<img width="1452" alt="image" src="https://github.com/user-attachments/assets/2c602b26-0f06-44c3-bf6f-af27a8a3f4c3">
<img width="1455" alt="image" src="https://github.com/user-attachments/assets/7a09c739-113e-4bc3-89f3-56fa80142b11">

**Comment by Krugloff** [comment]
the issue is no longer applicable

**Comment by tanys123** [comment]
Closing as not longer reproducible.
