### ISSUE TITLE
[Google Play API] Not longer able to scrape Top Charts

### ISSUE THREAD

**Issue by tanys123** [serpapi/public-roadmap#947]
<img width="1481" alt="Screenshot 2023-06-21 at 11 22 09 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/09a5efce-5ca0-4c67-9dd4-37b8cce6d42c">

Top Charts has switched to load asynchronously, thus these data has been missing.

Top Charts endpoint is similar with `pagination_url` endpoint but with different parameters.

[Playground](https://serpapi.com/playground?engine=google_play&gl=us&hl=en&store=apps) | [Inspect](https://serpapi.com/searches/64926cb7272aa5d726679f14/inspect)

**Comment by kagermanov27** [comment]
Closing this as this data can be acquired using chart parameter:

<img width="1452" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/ecd1fa02-94ce-4f71-88da-1d04a7a955cb">
