### ISSUE TITLE
[Google Product API] `start` and `page` not Working with Reviews

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#950]
This is a followup to #689. The `start` and `page` parameters still don't work when searching for reviews with the Google Product API. Users can paginate using the `next_page_filter` as @aliayar mentioned in #689. However, we should either fix `start` and `page` or change the documentation so that users don't get confused.

A user recently asked for help with this.

[Playground ](https://serpapi.com/playground?engine=google_product&product_id=4887235756540435899&gl=us&hl=en&start=10&page=1&reviews=1)  | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000043057?view=List)

**Comment by tanys123** [comment]
Decoding `rpt` is more complicated now compared to [when it first switched](https://github.com/serpapi/public-roadmap/issues/115). 

Playing around with the decoded value,
`0.12345678901234567` part seem to be the localization
```
\x12w
u
s0,0.12345678901234567,\"a:0000000000001692\",\"a:7013589970602158081\",1,\"7013589970602158081\",\"7712433480039810879_CP\"
```
Result (The loaded result (2nd) is in Spanish?):
<img width="774" alt="Screenshot 2023-08-14 at 11 06 38 AM" src="https://github.com/serpapi/public-roadmap/assets/10222402/2e71e060-e542-4f4d-adf0-dccedbb94f85">

`rpt` value does maintain the same for the same pagination, reverse engineer on that might be possible but it will take unforeseen amount of time.

**Comment by schaferyan** [comment]
> rpt value does maintain the same for the same pagination, reverse engineer on that might be possible but it will take unforeseen amount of time.

If this isn't realistically going to be fixed in the near future, should we just go ahead and remove these parameters from the documentation and the Playground for right now?

**Comment by hartator** [comment]
I think @schaferyan just suggests to remove the `start` and `page` parameters from the playground:

![image](https://github.com/serpapi/public-roadmap/assets/307597/3cea84fa-5d47-46bf-819a-8d655e57a057)

And from the rest of the documentation to avoid confusion. And to suggest to use `serpapi_pagination.next` from now on in the documentation. Which still seems to work:

<img width="1495" alt="image" src="https://github.com/serpapi/public-roadmap/assets/307597/3f939994-108a-4da1-8dfa-3ddd384ed762">

`serpapi_pagination.next`:

![image](https://github.com/serpapi/public-roadmap/assets/307597/e0b6bb09-2902-44d5-b844-51a36921f0d1)

![image](https://github.com/serpapi/public-roadmap/assets/307597/b298bb02-8c08-4bbe-811e-564da969a714)

@tanys123, is this not correct?

**Comment by tanys123** [comment]
@hartator Yup, it is correct. Just wanted to point out the possibility of `start` and `page` (I think it is still more intuitive).

The action for this PR is to remove `start` and `page` and showcase the pagination using `serpapi_pagination.next`

**Comment by marm123** [comment]
Another customer reported the issue:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000061040?view=List)
