### ISSUE TITLE
[Google Shopping API] Support Filtering by Multiple Sellers

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#951]
A customer reported that when adding multiple `tbs` values for sellers, only the last value seems to be used.

I have confirmed in the Playground that this seems to be the case with some or most searches.

After a few tests, it seemed to work if only the sellers displayed on the page were used, and if the `tbs` values were given in the same order Google displayed them. However this pattern broke down when I tried to replicate it again to generate examples.

<img width="1465" alt="Screenshot 2023-06-22 at 11 21 13 AM" src="https://github.com/serpapi/public-roadmap/assets/30915304/11163820-e5eb-466b-8af7-b89d74f0bd77">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000043291?view=List) | [Playground](https://serpapi.com/playground?engine=google_shopping&q=Coffee&tbs=mr%3A1%2Cmerchagg%3Ag113872638%257Cg138144780%257Cm114193152%257Cm7388148%257Cm324480236%257Cm1218384%2Cmr%3A1%2Cmerchagg%3Ag113872638%257Cm114193152%257Cm7388148%2Cmr%3A1%2Cmr%3A1%2Cmerchagg%3Ag113872638%257Cg138144780%257Cm114193152%257Cm7388148%257Cm324480236) | [Google Shopping with Multiple Sellers Selected](https://www.google.com/search?tbm=shop&q=ipad&tbs=mr:1,merchagg:g101179491%7Cg8223659%7Cg118563538%7Cm3622330%7Cm8393069%7Cm8393819%7Cm8398729%7Cm8400529%7Cm124005887%7Cm7933&sa=X&ved=0ahUKEwjg6dXT4Nn_AhUfHTQIHbJyALYQsysIyRAoAA&biw=1470&bih=660&dpr=2)

**Comment by marm123** [comment]
You can use multiple sellers in filter by adding `mr:1,merchagg:` at the beginning, followed by the ids of sellers (parts after `mr:1,merchagg:`) separated by `|`. For example, in the Coffee search the following sellers are available (I've chosen 3 of them):
1.
`"text":
"Ami Ventures",`
`"tbs":
"mr:1,merchagg:m138811544"`
2.
`"text":
"Blackout Coffee Co.",`
`"tbs":
"mr:1,merchagg:m126559184"`
3.
`"text":
"Bones Coffee Company",`
`"tbs":
"mr:1,merchagg:m113004272"`

To use all of them together, we need to combine them this way:

`mr:1,merchagg:m138811544|m126559184|m113004272`

This will produce the following query:

[Playground](https://serpapi.com/playground?engine=google_shopping&q=Coffee&tbs=mr%3A1%2Cmerchagg%3Am138811544%7Cm126559184%7Cm113004272)

Hopefully those are the expected results. Please let me know.

**Comment by schaferyan** [comment]
Thank you @marm123 this seems to solve the problem. I am closing this and opening another issue to clarify this in our documentation.
