### ISSUE TITLE
[Google Maps Reviews API] Some results are missing `link` field

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#953]
Our customer reported that some of the searches are missing the `link` in the JSON response. Unfortunately, I wasn't able to recreate the issue in the Playground.

Search containing `link`:
<img width="1096" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/76bce5c9-6988-47c1-b383-ac090d7d76b0">

Search without `links`:
<img width="1098" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/c03363dc-eb5d-4bae-b442-0874ba222116">

[Inspect](https://serpapi.com/searches/6499651ed036a790c6638850/inspect) | [Inspect](https://serpapi.com/searches/6499651e9b64729aa6c3da69/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000043429?view=List)

**Comment by marm123** [comment]
Another customer reported the issue:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000043519?view=List)

**Comment by schaferyan** [comment]
Another customer reported this issue. Bumping this up to `urgent` since 3 customers have reported it in 24 hours.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000043551?view=List)

**Comment by schaferyan** [comment]
Reopening this issue as the customer reported more searches missing `link`.

[Search Inspector](https://serpapi.com/searches/649eef06359e99e8a4b4c40e/inspect) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000043519?view=List)
