### ISSUE TITLE
[Baidu Search API] Internal server error

### ISSUE THREAD

**Issue by ilyazub** [serpapi/public-roadmap#954]
![image](https://github.com/serpapi/public-roadmap/assets/282605/de6ddf06-326b-4220-b53a-1f133ce6b234)

[Playground](https://serpapi.com/playground?engine=baidu&q=%E6%80%8E%E4%B9%88%E5%9C%A8%E5%BE%AE%E4%BF%A1%E4%B8%8A%E5%8F%91%E7%BB%99%E4%BD%A0&ct=2) &middot; [Search Inspector](https://serpapi.com/searches/649ac474d737d737fc599700/inspect)  &middot; [HTML](https://serpapi.com/searches/649ac474d737d737fc599700.html)

**Comment by marm123** [comment]
I'm reopening this thread, as one of our customers reported this issue appearing once again. I'm sharing a single example for now but will follow up with more if the customer shares.

[Inspect](https://serpapi.com/searches/64be4a02797ac683a6a33697/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000045120?view=List)
