### ISSUE TITLE
[Google Search API Local Pack] local_results not Parsed in Mobile Mode

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#96]
local_results are not parsed in **mobile mode**.

[Documentation](https://serpapi.com/local-pack) | [The Playground](https://serpapi.com/playground?q=Coffee&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&newPara=stick) | [Inspect](https://serpapi.com/searches/624325883bea7bca92d015bb/inspect)

<img width="954" alt="local_pack_result" src="https://user-images.githubusercontent.com/64849049/160649941-a383e905-860e-49ee-9369-81cb44d06029.png">

**Comment by ritu1337** [comment]
`local_results` and `local_map` are now being parsed.
