### ISSUE TITLE
[Bing Search API] `related_questions` are not scraped

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#960]
Our customer reported that the `related_questions` are no longer scraped. This is likely to changes in Bing, as they display People also ask block with the new design:

<img width="1098" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/1363ea56-e5c6-436c-9b43-04b418402ab8">

[Playground](https://serpapi.com/playground?engine=bing&q=%22Russell+Athletic%22&cc=US&no_cache=true) | [Inspect](https://serpapi.com/searches/649d302366d81f3a45329d12/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000043645?view=List)

**Comment by andypple83** [comment]
![Screenshot 2024-01-29 at 21 02 15](https://github.com/serpapi/public-roadmap/assets/99160364/5d00ae03-9c8b-47f2-9f3d-49b36748d767)

I've tested Bing search engine. We can scrape the `people also ask` block. Thanks
