### ISSUE TITLE
[New API] Ads Transparency Center API

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#964]
A user contacted us to find out if we can create an API based on Ads Transparency Center portal of Google.

# Search Page:

![transparency_ads](https://github.com/serpapi/public-roadmap/assets/64849049/ed0c4f98-6086-4503-b489-172e076561ea)

# Ad Details:

![transparency_ads_individual](https://github.com/serpapi/public-roadmap/assets/64849049/855a022d-fd34-4f3c-800a-6c63c8b709ee)

[Search Page](https://adstransparency.google.com/?region=PL) | [Detail Page](https://adstransparency.google.com/advertiser/AR03219547204939153409?region=PL) | [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000043702?view=List)

**Comment by netexpoarthur** [comment]
That would be awesome thank you!
