### ISSUE TITLE
[Google Jobs API] Add `htischips` filter on top of `chips`

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#965]
Google serves filters in the `htischips` by default. While we can still apply filters through `chips`, if we want to use multiple filters from the same category, the `chips` parameter is not working. We can add `htischips` as an option for customers who want to use multiple filters from the same category, or completely replace the `chips` parameter. However, some of our customers are using `chips` in their implementation, so we risk breaking their code if we only replace it. Below a couple of tests with two different filters from the same category separated by different separators:

[Search with `requirements:no_degree;no_experience` (separated by `;`):
](https://serpapi.com/playground?engine=google_jobs&q=Cyber+Security+Analyst&location=Dallas%2C+Texas%2C+United+States&gl=us&hl=en&chips=requirements%3Ano_degree%3Bno_experience&no_cache=true)
<img width="1435" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/bf19864b-4bfe-4182-af74-2ae77b668f87">

[Search with `requirements:no_degree,no_experience` (separated by `,`) - results are the same as if the `no_experience` part was not included](https://serpapi.com/playground?engine=google_jobs&q=Cyber+Security+Analyst&location=Dallas%2C+Texas%2C+United+States&gl=us&hl=en&chips=requirements%3Ano_degree%2Cno_experience):
<img width="1435" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/ec77bddc-dc4c-4ca7-ab6d-2444111f4bc9">

[Search with `requirements:no_degree:no_experience` (separated by `:`)
](https://serpapi.com/playground?engine=google_jobs&q=Cyber+Security+Analyst&location=Dallas%2C+Texas%2C+United+States&gl=us&hl=en&chips=requirements%3Ano_degree%3Ano_experience)<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/55d6ce4e-c051-488d-ac5a-ff6ad8af6cf0">

[Search with `requirements:no_degree&no_experience` (separated by `&`) - results are the same as if the `no_experience` part was not included](https://serpapi.com/playground?engine=google_jobs&q=Cyber+Security+Analyst&location=Dallas%2C+Texas%2C+United+States&gl=us&hl=en&chips=requirements%3Ano_degree%26no_experience)
<img width="1436" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/3a6aec51-6e97-4bb9-b36c-e2b6568be286">

With `htischips`, it's easy to apply correct filters based on the URL:
<img width="1126" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/451df0f1-bb6d-414d-80d5-bcb83e7a3ce5">

[Playground](https://serpapi.com/playground?engine=google_jobs&q=Cyber+Security+Analyst&location=Dallas%2C+Texas%2C+United+States&gl=us&hl=en&chips=requirements%3Ano_degree%26no_experience) | [Google Jobs direct link](https://www.google.com/search?q=Cyber+Security+Analyst&ibp=htl;jobs&uule=w+CAIQICIaRGFsbGFzLFRleGFzLFVuaXRlZCBTdGF0ZXM&hl=en&gl=us&chips=requirements:no_degree&no_experience=#htivrt=jobs&fpstate=tldetail&htichips=requirements:no_degree,requirements:no_experience&htischips=requirements;no_degree;no_experience&htidocid=7TX_R130wVQAAAAAAAAAAA%3D%3D)

Related: https://github.com/serpapi/public-roadmap/issues/11

**Comment by andypple83** [comment]
Thanks @marm123 for reporting this issue. We can use `chips` to use multiple filters from same category using this syntax:

`chips=category_name=value,category_name=value`.

E.g in this case, the param will be: `chips=requirements:no_degree,requirements:no_experience`

[Playground](
https://serpapi.com/playground?engine=google_jobs&q=Cyber+Security+Analyst&location=Dallas%2C+Texas%2C+United+States&gl=us&hl=en&chips=requirements%3Ano_degree%2Crequirements%3Ano_experience&no_cache=true) | [Inspect](https://serpapi.com/searches/64c278e6ce87f8ba47380ae2/inspect)

@paigebutler and I checked the results compared to the single filter: `chips=requirements:no_degree` and `chips=requirements:no_experience`. They have different results.

We will add the document to cover this example.
