### ISSUE TITLE
[Google Shopping Results API] All Product Ids not Parsed and Returned

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#97]
[Google Shopping Results API](https://serpapi.com/shopping-results) does not parse and return some of the products' ids.

[The Playground](https://serpapi.com/playground?q=bose+quickcomfort&location=Greater+London%2C+England%2C+United+Kingdom&google_domain=google.co.uk&gl=uk&hl=en&tbm=shop&newPara=stick) | The Inspect [1](https://serpapi.com/searches/6245a86f5f2203da3eacb01a/inspect) [2](https://serpapi.com/searches/6245a86f5f2203da3eacb01a/inspect) [3](https://serpapi.com/searches/6245c2f4607393528492e4ca/inspect)

<img width="949" alt="shopping_results_some_no" src="https://user-images.githubusercontent.com/64849049/161087817-9809dcf4-aae6-49de-9612-85d83cabdf18.png">

In the same conditions, Google Shopping Results API may also return 1 as the product_id which can be seen:

[Inspect](https://serpapi.com/searches/6245a32c8ccee012fff83f55/inspect)

<img width="726" alt="shopping_results_some_1" src="https://user-images.githubusercontent.com/64849049/161089175-8d81fa3d-29d8-4c5a-ba97-b0df860b6998.png">

Additional inspect links can be found [here](https://github.com/serpapi/public-roadmap/files/8390804/lines_with_bad_ids.txt).

**Comment by Alaa-abdulridha** [comment]
Tried to solve these issues, but looks like there is no solution for them.

1- First issue no `product_id` because currently some products just don't belong to google products anymore, they're from external vendors and we use this way to extract the `product_id`:
![image](https://user-images.githubusercontent.com/53356539/161634351-ef4e1847-a823-4d1b-bb3f-31a16289abce.png)

The second issue is about the same, the product URL is : 

`/url?url=/shopping/product/1%3Fhl%3Den%26prds%3Doid:11326610911569872445,pid:11326610911569872445%26sts%3D9%26lsf%3Dseller:7822674,store:7713865243304263507,s:h&rct=j&q=&esrc=s&sa=U&ved=0ahUKEwjSmuyosfD2AhVqomoFHQoOCqQQ2SkI2Ag&usg=AOvVaw1Po5ziSZS6unviluhlZW1f`


That's why it returns `1`

I failed to solve this issue, any tips guys @kagermanov27 @aciddjus @ilyazub ?

**Comment by aciddjus** [comment]
URL that we support:

```
/shopping/product/
17225083693758926213 ?
gl=uk &
amp;hl=en &
amp;q=bose+quickcomfort &
amp;prds=epd:10845427194832108789,eto:10845427194832108789_0,rsk:PC_17370419192671336164
```

URL that we do not support:

```
/shopping/product/
1 ?
gl=uk &
amp;hl=en &
amp;q=bose+quickcomfort &
amp;prds=epd:4570511234455053182,eto:4570511234455053182_0,pid:4570511234455053182
```

As you can see `product_id` is still present, just in a different place (`4570511234455053182`)

In the first example, the `amp;prds` value is not required. And the ID is placed at the beginning of the URL. But in the second example, `amp;prds` is required and contains the product ID.

So we just have to find a way to support both URL structures.

**Comment by Alaa-abdulridha** [comment]
> 

Okay, so we have two issues here, 

The first issue, some URLs comes like this 
` https://serpapi.com/url?url=https://uk.webuy.com/product-detail%3Fid%3D0017817804516A&rct=j&q=&esrc=s&sa=U&ved=0ahUKEwjKoKCmzf32AhUKUt8KHTb2AnwQ1SkIwAkoAA&usg=AOvVaw1IfCwdoLXvBm79WBIIbeLm `

It doesn't have any ID:

![image](https://user-images.githubusercontent.com/53356539/161831789-01fc1772-96f8-4d3f-a63a-e24423d0fde1.png)


---
The other issue, you mentioned, 

> As you can see product_id is still present, just in a different place (4570511234455053182)

I tried that, but it is still the same, if you go to the Google product API, and put the product id it will say invalid product id.

What do you think? @aciddjus

**Comment by aciddjus** [comment]
> I tried that, but it is still the same, if you go to the Google product API, and put the product id it will say invalid product id.

Yes, because we do not support the new URL structure: https://github.com/serpapi/SerpApi/blob/master/app/models/search/google_product/parameters.rb

We would need to update the code to support both: https://github.com/serpapi/public-roadmap/issues/97#issuecomment-1088489157

------------------------

> The first issue, some URLs comes like this `https://serpapi.com/url?url=https://uk.webuy.com/product-detail%3Fid%3D0017817804516A&rct=j&q=&esrc=s&sa=U&ved=0ahUKEwjKoKCmzf32AhUKUt8KHTb2AnwQ1SkIwAkoAA&usg=AOvVaw1IfCwdoLXvBm79WBIIbeLm`
> 
> It doesn't have any ID:

Yes, you are right. The ID is contained inside the expendable block when the item is clicked. But this part is loaded via another request.

<img width="1601" alt="image" src="https://user-images.githubusercontent.com/6929257/161947277-2ff581f3-59f4-4476-85c2-a73ff8a9e8fa.png">

-------------------

So not impossible, but would require a new request to retrieve the Google Shopping link.

**Comment by Alaa-abdulridha** [comment]
Same issue, forwarded for me by @aliayar , reported by a customer.

Google shopping API is not extracting `product_id` and `product_link`

[Playground](https://serpapi.com/playground?q=zara&location=Sweden&google_domain=google.se&gl=se&hl=sv&tbs=mr%3A1%2Croot_cat%3A529385&tbm=shop&num=100)

**Comment by aliayar** [comment]
Product_ids are not parsed and returned at all in the results anymore.

[The Playground](https://serpapi.com/playground?q=zara&location=Sweden&google_domain=google.se&gl=se&hl=sv&tbs=mr%3A1%2Croot_cat%3A529385&tbm=shop&num=100) | [The Inspect](https://serpapi.com/searches/6260f11933b236482fffb871/inspect)


<img width="957" alt="no_product_id" src="https://user-images.githubusercontent.com/64849049/164385316-0ef88fba-234b-4bfc-82c7-a7c1b29392d7.png">

**Comment by aciddjus** [comment]
Product ID is available inside `data-docid` field:

<img width="1520" alt="image" src="https://user-images.githubusercontent.com/6929257/165108754-7a6717bd-5f83-4fa8-846a-9cefd9ca6471.png">

To make this ID work with our [Google Product API](https://serpapi.com/google-product-api), we would also need to refactor the fetch URL in [parameters.rb](https://github.com/serpapi/SerpApi/blob/master/app/models/search/google_product/parameters.rb) to accept the next format:

```
https://www.google.se/shopping/product/1?
gl=... &
hl=... &
q=... &
prds=epd:product_id,eto:product_id_0,pid:product_id
```

Working link for product_id: `16031999104836648407`

https://www.google.se/shopping/product/1?gl=se&hl=sv&q=zara&prds=epd:16031999104836648407,eto:16031999104836648407_0,pid:16031999104836648407

**Comment by theolof** [comment]
Any progress on this? We really need the product id to be able to store and lookup the item later.

This results in 0 product ids: https://serpapi.com/playground?q=zara&location=Sweden&google_domain=google.se&gl=se&hl=sv&tbs=mr%3A1%2Croot_cat%3A529385&tbm=shop&num=100

This results in product ids, but not on all items: https://serpapi.com/playground?q=%22Levi%27s%22&location=Sweden&google_domain=google.se&gl=se&hl=sv&tbs=mr%3A1%2Croot_cat%3A529385&tbm=shop&num=100

As you can see here, the second result doesn't have the `product_id` and thus not the `product_link` either.


<img width="1020" alt="Screenshot 2022-08-12 at 10 11 37" src="https://user-images.githubusercontent.com/14074538/184313206-c29df5b7-3690-40e6-a234-b4bfe65f2e4a.png">

**Comment by aciddjus** [comment]
Hi @theolof,

We should have a fix for the missing `product_id` and `product_link` by the end of the week. 

Unfortunately, we are still working on a solution for our [Google Product API](https://serpapi.com/google-product-api) not returning results for IDs with `1` in the `product_link`.

**Comment by aciddjus** [comment]
This issue should be resolved now. Please let us know if `product_id` and `product_link` are still missing for some searches.

**Comment by theolof** [comment]
This issue seems to have re-emerged. Can you have a look why the `product_id` and `product_link` is missing from certain results. For example
https://serpapi.com/playground?engine=google_shopping&q=zara&location=Sweden&google_domain=google.se&gl=se&hl=sv&tbs=mr%3A1%2Croot_cat%3A529385&num=100

**Comment by aliayar** [comment]
@theolof Please refer to [the new issue](https://github.com/serpapi/public-roadmap/issues/724).
