### ISSUE TITLE
[Google Search API] Assign Proxy Based on Location Parameters

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#975]
A customer requested that we use proxies near the location specified in the parameters. They are having issues with getting results for the wrong location despite using valid location parameters, as discussed in #969. They don't want to include the name of the location directly in their query. 

Is this something we can implement?

@ritu1337 @aliayar 

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000043735?view=List)

**Comment by hartator** [comment]
We can't have enough proxies with a city-level precision unfortunately.

**Comment by schaferyan** [comment]
That makes sense. This specific customer asked for state-level precision - I'm not sure whether we can support that or if it would be helpful for enough customers to justify it.

**Comment by hartator** [comment]
> > We can't have enough proxies with a city-level precision unfortunately.
> 
> @hartator That makes sense - city level would be a lot of proxies. This specific customer asked for **state-level precision** which sounds more reasonable to me- is there a chance we can support that?
> 
> Variations of this are fairly common - customers reporting results for a different state than they are searching in. Depending on how difficult this is to implement and any cost to performance it might have, it might be worth considering.
> 
> Then again, most users are probably okay with including the location in the query as a workaround to avoid getting results from the proxy IP.

The added difficulty is IPs x location databases are more fluid than it seems. Even at a state level. An IP that we think is from FL might actually register from TX with Google. These databases are not set in stone; making the adding benefits of trying to "IP lock" a location actually marginal compared to working through other less infrastructure intensive means.

**Comment by NateSkiles** [comment]
A potential high-volume customer asked if it would be possible to look at this again.

Specifically, their use case requires requests to Baidu which does not support location parameters. We have suggested a solution similar to the one mentioned [here](https://github.com/serpapi/public-roadmap/issues/969#issuecomment-1619591806), but I wanted to clarify the viability of implementing the ability to set a proxy within a given range.

cc @schaferyan @hartator
