### ISSUE TITLE
[Bing Search API] Answer box not available in response json of bing search

### ISSUE THREAD

**Issue by Gokulnath31** [serpapi/public-roadmap#977]
<img width="1438" alt="Screenshot 2023-07-06 at 5 47 02 PM" src="https://github.com/serpapi/public-roadmap/assets/48591613/b5f6ed03-730f-42d9-8079-dd6d62eaf043">

The results include

- Knowledge graph
- Organic results
- Related searches 
- Pagination
- metadata of the search
 
But the answer box is missing in the json. On the other hand, we have answer box in response for Google Search Result. Is there any specific reason for answer box not being present in Bing search results of Serp API?

**Comment by aliayar** [comment]
Bing has a new answer box which Bing API doesn't return in JSON response.

![bing_answer_box](https://github.com/serpapi/public-roadmap/assets/64849049/d1c2a220-71c4-4286-a7e2-4ebb46b49911)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000044064?view=List) | [Playground Link](https://serpapi.com/playground?engine=bing&q=is+coffee+bad+for+you%3F) | [Inspect Link](https://serpapi.com/searches/64a6b2081baebb6246f7f5a7/inspect) | [Bing](https://www.bing.com/search?q=is+coffee+bad+for+you)

**Comment by tanys123** [comment]
Created a [new issue](https://github.com/serpapi/public-roadmap/issues/993) for "People also ask" so that we can resolve this ticket with Answer box issue.
