### ISSUE TITLE
[New API] Extract Bing Short Videos results

### ISSUE THREAD

**Issue by aciddjus** [serpapi/public-roadmap#979]
Let's add a new API endpoint, `Bing Short Videos API`.

![image](https://github.com/serpapi/public-roadmap/assets/6929257/46c2b2be-8745-4939-85aa-605aa62de295)

[Inspect link](https://serpapi.com/searches/64a6baaa5c1059fdcabd7cec/inspect)
[Playground](https://serpapi.com/playground?engine=bing&q=Coffee+videos&device=desktop)

[Google documentation for reference](https://serpapi.com/short-videos)

----------------------------

TODO:

- [ ] Add parser to extract results on desktop and mobile
- [ ] Add xray
- [ ] Add tests for desktop and mobile
- [ ] Add documentation
- [ ] Confirm that the solution works using different localization

**Comment by djsegal** [comment]
resolved by: https://github.com/serpapi/SerpApi/pull/3963
