### ISSUE TITLE
[Marketing] Submit a token spray template to Nuclei repository

### ISSUE THREAD

**Issue by ilyazub** [serpapi/public-roadmap#98]
`Nuclei` is a vulnerability scanner for ProjectDiscovery. It has a [repository of vulnerability templates](https://github.com/projectdiscovery/nuclei-templates/tree/c5df3aadf3e3aa6c139b69f5a17fcb23675fe381/token-spray). We can submit a nuclei-template so a few more people will know about SerpApi.

Bonus is that we can regularly scan Github, Gitlab, Replit, and StackOverflow for the presence of leaked API keys and notify account owners to regenerate and hide API keys.

----

Similarly, we can list SerpApi Account API on [KeyHacks](https://github.com/streaak/keyhacks/blob/2895606f763ffcf579267a8eff33ee7501023d6e/README.md).

**Comment by hartator** [comment]
Closing this as stale.
