### ISSUE TITLE
[New Feature Request] Storing Search Results to be Optional 

### ISSUE THREAD

**Issue by aliayar** [serpapi/public-roadmap#981]
I have had a meeting recently with a financial services company which are very strict with their data retention policies.

SerpApi keeps search results on the servers for a month and then those results are deleted.

Can we offer an option to user to decide whether their results to be stored for a month or not stored at all?

This particular user doesn't want their results to be saved.

**Comment by hartator** [comment]
Can you share the Intercom thread?

**Comment by schaferyan** [comment]
Other users with lots of security/data retention concerns might also like this feature.

If we implement it, we should make it clear to users who want it that this will greatly reduce our capacity to resolve any issues they encounter.

**Comment by hartator** [comment]
@aliayar @aliayar Can you ask if they want just the search to be fully disappear or also the search parameters? Thank you!

**Comment by aliayar** [comment]
I sent them a message. I will find more clients who has asked about this before.

**Comment by aliayar** [comment]
Another user asking for this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/conversation/102910000054099)

**Comment by schaferyan** [comment]
Another user asked for this feature:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000056714?view=List)

**Comment by hilmanski** [comment]
Another user asked for this feature (on a Meeting):

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/admin/6755014/conversation/102910000057358?view=List)

**Comment by marm123** [comment]
Following up on this as this is the main priority for one of the more prestigious companies that is considering SerpApi. They are potentially an Enterprise Customer if we can implement it.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000057358?view=List)

**Comment by schaferyan** [comment]
Another prestigious  potential Enterprise customer requested a feature like this. They are interested in having the ability to store search information for only a short time, i.e 48 hours:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060031?view=List)

**Comment by hartator** [comment]
I am thinking maybe we should add something like a `private=true` param that will aim to disable most logging, delete the search metadata, and delete files after the search is done. And warn the user that degguging will be hard.

**Comment by schaferyan** [comment]
The financial services company that initially requested this are now our Enterprise Customer. They reached out again to ask about this feature.

**Comment by marm123** [comment]
Potential Enterprise Customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067601?view=List)

**Comment by schaferyan** [comment]
The potential enterprise customer followed up on this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000067602?view=List)

**Comment by schaferyan** [comment]
Found another potential customer who requested this feature:

[Intercom](https://github.com/serpapi/public-roadmap/issues/981)

**Comment by martin-serpapi** [comment]
Another potential customer requested this:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000069061?view=List)

**Comment by hilmanski** [comment]
A user (probably their team is a customer) is interested in this.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000070983?view=List)

**Comment by hartator** [comment]
We've released ZeroTrace Mode:

![CleanShot 2024-10-25 at 20 31 09@2x](https://github.com/user-attachments/assets/23347acc-2ba3-46b3-94b4-47c8022918ce)

It's very easy to enable. You just add `zero_trace=true` to your searches with a compatible Enterprise account.

More information: https://serpapi.com/zero-trace-mode
