### ISSUE TITLE
[Google Search API] Support new Knowledge Graph Layout

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#986]
<img width="1464" alt="image" src="https://github.com/serpapi/public-roadmap/assets/73674035/32171b70-87f7-4e64-8a6a-822f8a2162d3">

[Playground](https://serpapi.com/playground?q=Natural+remedies+for+migraines&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&no_cache=true&google_domain=google.com&newPara=stick+highlight+lr+as_qdr+safe+google_domain+si+form+filter+chips+as_epq+client)
[Inspect](https://serpapi.com/searches/64ac1943c504e92e225cd81a/inspect)

**Comment by ilyazub** [comment]
Off-topic. Let's post the new layouts and the new SERP features on our social media and tag `#serp #Google`. People discuss on Twitter.

Examples: https://twitter.com/search?q=%23serp%20%23google%20min_faves%3A5%20from%3AVorticonCmdr&src=typed_query&f=live

**Comment by hartator** [comment]
> Off-topic. Let's post the new layouts and the new SERP features on our social media and tag `#serp #Google`. People discuss this on Twitter. (_I posted the KG from this issue: https://twitter.com/serp_api/status/1678473119906799625_.)

Fixed link: https://twitter.com/serp_api/status/1678473205869060110

Yes, this is a good idea. Maybe just also add the red outline in the tweet.

**Comment by ishiharaf** [comment]
A user opened an issue about this on our public roadmap: https://github.com/serpapi/public-roadmap/issues/1923

**Comment by kagermanov27** [comment]
Duplicate of https://github.com/serpapi/public-roadmap/issues/1923
