### ISSUE TITLE
[Google Product API] Allow searches with the `prds=pid:product_id` parameter

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#988]
We currently extract the product pages with the following link: `https://www.google.com/shopping/product/product_id`. While it works in a lot of cases, some product pages are accessible with the following link only: `https://www.google.com/shopping/product/1?gl=us&prds=pid:product_id`. I'm not sure if there are any other ways to get the product details page, but with our current approach, we are not able to extract a good portion of them.

Product page with our current approach (id: 1981117864379524916):
<img width="1145" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/dd9bb253-e582-4eba-b162-c5f7866557c4">

Product page with the `prds=pid:product_id` parameter (id: 1981117864379524916):
<img width="1148" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/be635a79-e43a-48fe-824d-a39976956fdd">

Product page with our current approach (id: 17119235067872248080):
<img width="1154" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/147f0d5d-dede-432b-8fd5-7cd0455aa069">

Product page with the `prds=pid:product_id` parameter (id: 17119235067872248080):
<img width="1148" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/0a412003-892b-49e6-92b7-c6c6d956e6ad">

As you can see, some of the product pages work with the current approach, and some are not. The same is for searches with the `prds=pid:product_id` parameter.

[Playground 1981117864379524916](https://serpapi.com/playground?engine=google_product&product_id=1981117864379524916&gl=us&hl=en) | [Inspect 1981117864379524916](https://serpapi.com/searches/64acfce2ef7dda5abfd30b3c/inspect)
[Playground 17119235067872248080](https://serpapi.com/playground?engine=google_product&product_id=17119235067872248080&gl=us&hl=en) | [Inspect 17119235067872248080](https://serpapi.com/searches/64acfdf0969c089ca4e25bbd/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000044315?view=List)

Related: https://github.com/serpapi/public-roadmap/issues/846
Related: https://github.com/serpapi/public-roadmap/issues/454

**Comment by marm123** [comment]
Another user reported the issue:

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000044437?view=List)

**Comment by jwilger** [comment]
Happening a lot to us, too. I'd say at least 25% of our product searches the last few days end up with that error page when we try to grab the product details.

**Comment by ilyazub** [comment]
@andypple83 There's a PR addressing that issue: https://github.com/serpapi/SerpApi/pull/2789

**Comment by andypple83** [comment]
Thanks @ilyazub . I'll catch up with the solutions. 👍

**Comment by TadasPik** [comment]
Hello. Any ETA's on when it's gonna be merged?

**Comment by andypple83** [comment]
We're actively working on this. My ETA is the end of next week. I will provide the updates if anything changes. Thanks for your patience.

**Comment by andypple83** [comment]
Thanks for your patience. We are doing the benchmark for our solution. It may take a few business days to finish.

**Comment by TadasPik** [comment]
> Thanks for your patience. We are doing the benchmark for our solution. It may take a few business days to finish.

Has it finished? :)

**Comment by scxliu** [comment]
Anything update on this? 
Thanks!

**Comment by schaferyan** [comment]
@TadasPik @scxliu It looks like we are still fine-tuning the solution. We will update you when it is completed. We appreciate your patience in the meantime.

**Comment by TadasPik** [comment]
@schaferyan any news?

**Comment by TadasPik** [comment]
Anyone any news on this? :)
