### ISSUE TITLE
[Google Shopping API] Display if the result is considered "Best match"

### ISSUE THREAD

**Issue by marm123** [serpapi/public-roadmap#989]
Currently, if there is a "Best match" in the results, there is no way to know if it is a "Best match" or not, as it only appears as the first of the `shopping_results`. "Best match" is not always present in results, so we might consider adding something like `best_match: yes` if the result is actually considered "Best match".

Result with "Best match":
<img width="1435" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/017d0b54-2fe6-4c50-a1e9-43766abc7f06">

Result without "Best match":
<img width="1435" alt="image" src="https://github.com/serpapi/public-roadmap/assets/28161162/25a26f0f-ee83-4884-88d7-d89d8ce02450">

[Playground](https://serpapi.com/playground?engine=google_shopping&q=XSM4396K0-10000S) | [Inspect](https://serpapi.com/searches/64ad4433234884f4c0c1323c/inspect)
[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000044341?view=List)

**Comment by ozguraltuntas** [comment]
Please don't hesitate to reach out if you have any further questions or require additional assistance. I am here to help and will do my best to provide you with the necessary information.

**Comment by marm123** [comment]
The customer is keen on switching to Enterprise Plan in the future if we implement this feature.

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000044341)

**Comment by marm123** [comment]
Yeah, I think, purely from the user perspective, that a separate `"best_match": True` or `"best_match": False` would be the best. I understand if it's not easy to extract it this way, but only noting it as I believe customers mainly need it to determine whether or not the product is the best match. And as @tanys123 mentioned, it would be very hard to use if they search Google Shopping for different markets with different languages.

Thank you for looking into it @btaunt!

**Comment by hartator** [comment]
> Yeah, I think, purely from the user perspective, that a separate `"best_match": True` or `"best_match": False` would be the best. I understand if it's not easy to extract it this way, but only noting it as I believe customers mainly need it to determine whether or not the product is the best match. And as @tanys123 mentioned, it would be very hard to use if they search Google Shopping for different markets with different languages.

Main issue is we keep all `false` flags in our JSON, we are going to end up with a very large JSON with a lot of `false` flags.

Like picture `free_shipping: false`, `free_shipping_us: false`, `free_shipping_eu: false`, `free_installation: false`, and things in the like. It doesn't produce the most interesting JSON and all of this can be inferred.

Also, `best_match` may be retired tomorrow and we still going to display it for years to come. But, more importantly, the absence `best_match` markup doesn't mean it's not a best match. So, we are affirming something that's not there by having a `best_match: false` flag. Which can be confusing. Not sure if my rambling is super clear lol.
