### ISSUE TITLE
[Baidu Search API] `snippet` for some `organic_results` are not parsed 

### ISSUE THREAD

**Issue by kagermanov27** [serpapi/public-roadmap#99]
![snippet7](https://user-images.githubusercontent.com/73674035/161335358-9362c8f9-67a7-449d-842f-9d8da268334b.png)
[Inspect Link](https://serpapi.com/searches/62475cc5d04d6d1217a19368/inspect)

**Comment by Alaa-abdulridha** [comment]
The `date` is not parsed as well.
