### ISSUE TITLE
[Google Search API]`inline_videos` and `short_videos` blocks Scraped into `organic_results`

### ISSUE THREAD

**Issue by schaferyan** [serpapi/public-roadmap#996]
A user reported we are parsing content that should only be included in `inline_videos` or `short_videos` into the `organic_results`.

<img width="1061" alt="Screenshot 2023-07-14 at 12 22 52 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/423b6b0e-d631-4453-9e09-2a39901aeec0">

<img width="1378" alt="Screenshot 2023-07-14 at 12 26 59 PM" src="https://github.com/serpapi/public-roadmap/assets/30915304/2cadab3a-14e7-47d7-9b64-89cdb7aa50ac">

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000044596?view=List) | [Playground](https://serpapi.com/playground?q=kunekune+pigs&location=Austin%2C+Texas%2C+United+States&gl=us&hl=en&device=mobile&newPara=chips) | [Search Inspector](https://serpapi.com/searches/64b19809b7b1ccf93231fb14/inspect)

**Comment by hartator** [comment]
> [Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000044596?view=List) | Playground | [Search Inspector](https://serpapi.com/searches/64b19809b7b1ccf93231fb14/inspect)

@schaferyan I think the playground link might be broken.

**Comment by schaferyan** [comment]
Thank you @hartator, it should be fixed
